/**
 * V14 NO-EDGE TRADE GATE -- renders the 12 required reports from results/v14_results.json (no computation that could change a result).
 *   node research/trade_gate_v14/scripts/write_reports.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..'); const RES = join(ROOT, 'results'); const REP = join(ROOT, 'reports'); mkdirSync(REP, { recursive: true });
const R = JSON.parse(readFileSync(join(RES, 'v14_results.json'), 'utf8')); const H = JSON.parse(readFileSync(join(RES, 'audit_hashes.json'), 'utf8')); const D = R.decision;
const tbl = (h, rows) => `| ${h.join(' | ')} |\n|${h.map(() => '---').join('|')}|\n${rows.map((r) => `| ${r.join(' | ')} |`).join('\n')}`;
const S2 = ['DEV', 'HOLD']; const CF = ['PRIMARY', 'ILLUSTRATIVE_PCT_0_50_10K', 'ILLUSTRATIVE_CURRENT_10K']; const C = (S, c) => R.splits[S].configs[c];
const STATES = ['WAIT_STALE_DATA', 'WAIT_SAFETY_BREAKER', 'WAIT_NO_SETUP', 'WAIT_NO_TRIGGER', 'WAIT_DIRECTION_UNCLEAR', 'WAIT_CONFLICT', 'WAIT_INVALID_LOCATION', 'WAIT_INVALID_SL', 'WAIT_INVALID_RR', 'WAIT_ENTRY_QUALITY', 'WAIT_RISK_UNSAFE', 'WAIT_BROKER_UNSAFE', 'TRADE_ELIGIBLE'];
const tot = (c, k) => S2.reduce((s, S) => s + (C(S, c).by_state[k] ?? 0), 0); const totF = (c, f) => S2.reduce((s, S) => s + C(S, c)[f], 0); const n = (x) => Number(x).toLocaleString('en-US');
const HEAD = (t) => `# ${t}\n\nV14 NO-EDGE BEHAVIOUR & TRADE GATE · ARCHITECTURE / SAFETY STUDY · RESEARCH ONLY · REAL OFF · DEMO OFF · EXECUTION_AUTHORITY NONE · strategies unchanged (V8 corrected core: MC PB BO SR MR) · structural SL unchanged · RR 1.70 · CAPITAL_HARVEST OFF · RISK_PERCENTAGE UNRESOLVED · spec ${R.prereg_sha.slice(0, 16)}… · gate ${R.gate_sha.slice(0, 12)}…\n\n`;
const CFDESC = { PRIMARY: 'PRIMARY: risk UNRESOLVED, production breakers', ILLUSTRATIVE_PCT_0_50_10K: 'ILLUSTRATIVE: PCT 0.50 %, 10,000 USD, no breakers (V11 parity; not approved)', ILLUSTRATIVE_CURRENT_10K: 'ILLUSTRATIVE: fixed 0.01 lot (production veto), production breakers (not approved)' };
const stateTable = (S) => tbl(['State', ...CF], STATES.map((st) => [st, ...CF.map((c) => n(C(S, c).by_state[st] ?? 0))]));
const reasonTable = (S, c) => tbl(['State : reason', 'Bars'], Object.entries(C(S, c).by_reason).sort((a, b) => b[1] - a[1]).map(([k, v]) => [k, n(v)]));
const fwd = R.forward_shadow; const out = {};

out.V14_NO_EDGE_ARCHITECTURE = HEAD('V14_NO_EDGE_ARCHITECTURE') + `## Why a gate
V13 found no demonstrated edge in any existing strategy (EDGE_NOT_DEMONSTRATED; CORRECTION_CANDIDATE = NONE). V14 therefore adds no edge research. It defines how MCP behaves when no edge is demonstrated: WAIT is a valid, preferred state, and the system may produce zero trades.

## Where the gate sits
\`\`\`
MARKET DATA (confirmed 5m bars)
  → FROZEN V8 ENGINE (unchanged): pattern / setup / trigger per strategy, direction, location, structural SL, RR, quality
  → TRADE GATE (V14): a deterministic map of the engine's own result and the existing safety limits to one state
  → TRADE_ELIGIBLE or WAIT_* / RISK_REJECTED  (execution authority: NONE)
\`\`\`

The gate is NOT an edge generator.
- It never creates an entry the engine did not generate.
- It never picks a direction.
- It never changes an entry, SL or RR.
- It never increases risk after a loss, and never uses Capital Harvest.

## Behaviour the evidence supports today (PRIMARY: RISK_PERCENTAGE = UNRESOLVED)
- **No trades.** Over ${n(R.splits.DEV.rows + R.splits.HOLD.rows)} decision bars (DEV + HOLD), the gate returns **TRADE_ELIGIBLE = ${tot('PRIMARY', 'TRADE_ELIGIBLE')}**.
- **Every valid entry is risk-rejected.** All ${n(totF('PRIMARY', 'valid_entries'))} valid entries generated by the engine are VALID_ENTRY + RISK_REJECTED (RISK_PERCENTAGE_UNRESOLVED), because no risk percentage is approved.
- **Every other bar has a deterministic WAIT reason.**
- **Zero trades is the correct output, not an error.**

## Status
**TRADE_GATE_STATUS = ${D.TRADE_GATE_STATUS}.**
- **Failure conditions:** none fired: 0 invariant violations, deterministic, restart-equal, no lookahead, exact V11 parity.
- **Why only partially validated:** live operation with a risk model needs one field the forward-shadow records do not carry (${fwd.missing_field}). Without it, the gate fails closed (V14_FORWARD_SHADOW_COMPATIBILITY).

Reports: V14_TRADE_GATE · V14_WAIT_STATES · V14_DECISION_STATE_MACHINE · V14_RISK_FIREWALL · V14_STRATEGY_CONFLICT · V14_AUDIT_LOG · V14_REPLAY_VALIDATION · V14_NO_LOOKAHEAD · V14_FORWARD_SHADOW_COMPATIBILITY · V14_SAFETY_INVARIANTS · V14_FINAL_DECISION
`;

out.V14_TRADE_GATE = HEAD('V14_TRADE_GATE') + `## Contract
- **Signature:** \`decideGate(state, input, config) → { state, record }\` (\`scripts/gate.mjs\`). It is pure: same input + same state = same decision.
- **Input:** one normalized record per confirmed 5m bar, from either adapter:
  - V8 replay row (historical);
  - V8 forward-shadow decision record (live, read-only).
- **Config:**
  - riskModel: \`UNRESOLVED\` (default) or an illustrative research model;
  - breakers: the production limits (REAL ${R.splits.DEV.configs.PRIMARY ? 'consecutive-loss 2 per UTC day, daily ceiling 10' : ''});
  - conflictResolution: \`EXISTING_PRIORITY\` (the engine's own chain) or none.

## Engine result → gate state (existing rules only)
${tbl(['Engine result', 'Gate state'], [['DATA_UNAVAILABLE_STALE / INSUFFICIENT_DATA / BIAS_UNAVAILABLE / missing stages / late signal / out-of-order bar', 'WAIT_STALE_DATA'], ['no stage ≥ 2 (pattern only / no pattern)', 'WAIT_NO_SETUP'], ['setup but no valid trigger', 'WAIT_NO_TRIGGER'], ['NO_ELIGIBLE_STRATEGY / CHOP / HTF_CONFLICT / ENTRY_CONFLICT', 'WAIT_DIRECTION_UNCLEAR'], ['OVEREXTENDED', 'WAIT_INVALID_LOCATION'], ['INVALID_GEOMETRY', 'WAIT_INVALID_SL'], ['RR_NOT_ACCEPTABLE / VOLATILITY_INSUFFICIENT', 'WAIT_INVALID_RR'], ['NO_GOOD_ENTRY (engine quality gate)', 'WAIT_ENTRY_QUALITY'], ['BUY / SELL signal, verified', 'risk → broker → TRADE_ELIGIBLE or WAIT'], ['anything unrecognised', 'WAIT_SAFETY_BREAKER (fail closed)']])}

## Risk / broker result (V11 firewall, unchanged) → gate state
${tbl(['Result', 'Gate state'], [['risk model UNRESOLVED', 'WAIT_RISK_UNSAFE (RISK_PERCENTAGE_UNRESOLVED), valid entry kept'], ['position open; minimum lot; margin; sizing inconsistent; above approved', 'WAIT_RISK_UNSAFE'], ['broker order rule; broker rejection; equity / spec / tick value unavailable; spread above limit; entry drift', 'WAIT_BROKER_UNSAFE'], ['stale quote / signal', 'WAIT_STALE_DATA'], ['production breakers (consecutive losses, daily ceiling), kill switch, recorded news / shock block, re-entry guard, duplicate signal', 'WAIT_SAFETY_BREAKER'], ['every check passed', 'TRADE_ELIGIBLE']])}

## Replay configurations
${CF.map((c) => `- **${c}:** ${CFDESC[c]}.`).join('\n')}

The illustrative configurations only exercise the risk, broker and breaker paths. They are not approvals.
`;

out.V14_WAIT_STATES = HEAD('V14_WAIT_STATES') + `## States (13)
${tbl(['State', 'Meaning'], [['WAIT_STALE_DATA', 'input missing, stale, late, out of order or duplicated'], ['WAIT_SAFETY_BREAKER', 'an existing production safety limit or recorded safety block is active'], ['WAIT_NO_SETUP', 'no existing setup (pattern only or nothing)'], ['WAIT_NO_TRIGGER', 'setup without a valid trigger'], ['WAIT_DIRECTION_UNCLEAR', 'the existing direction rules establish no valid side'], ['WAIT_CONFLICT', 'strategies disagree and no resolution is defined'], ['WAIT_INVALID_LOCATION', 'entry outside the allowed location'], ['WAIT_INVALID_SL *', 'structural SL invalid'], ['WAIT_INVALID_RR *', 'RR below 1.70 / objective not feasible'], ['WAIT_ENTRY_QUALITY *', 'the engine\'s existing quality gate rejects the triggered candidate'], ['WAIT_RISK_UNSAFE', 'valid entry, risk cannot support it (RISK_REJECTED)'], ['WAIT_BROKER_UNSAFE', 'broker data, rules or execution conditions unsafe'], ['TRADE_ELIGIBLE', 'every check passed']])}

**\\* Added to the owner's list, each necessary:**
- The owner's state machine (§14) validates the SL and RR as separate steps, and §19 / §23 require "invalid SL / RR → no trade".
- The engine's own quality gate needs a truthful name.
- No other sub-states were created; detail goes in the reason code.

## Counts: DEV
${stateTable('DEV')}

## Counts: HOLD
${stateTable('HOLD')}

## Reasons (PRIMARY)
### DEV
${reasonTable('DEV', 'PRIMARY')}

### HOLD
${reasonTable('HOLD', 'PRIMARY')}
`;

out.V14_DECISION_STATE_MACHINE = HEAD('V14_DECISION_STATE_MACHINE') + `## Order (first failing step wins; every step's state is still recorded in the audit log)
\`\`\`
OBSERVE (input, ordering, freshness) ── fail → WAIT_STALE_DATA
→ SAFETY BREAKERS (production limits, kill switch, recorded block) ── active → WAIT_SAFETY_BREAKER
→ VALIDATE EXISTING SETUP ── none → WAIT_NO_SETUP
→ VALIDATE TRIGGER ── none / engine signal unverified → WAIT_NO_TRIGGER
→ VALIDATE DIRECTION (existing engine rules; the gate never picks a side) ── none → WAIT_DIRECTION_UNCLEAR
→ STRATEGY CONFLICT ── no defined resolution → WAIT_CONFLICT   (defined: existing priority chain MC → PB → BO → SR → MR)
→ VALIDATE LOCATION ── WAIT_INVALID_LOCATION
→ VALIDATE STRUCTURAL SL ── WAIT_INVALID_SL
→ VALIDATE RR ── WAIT_INVALID_RR      (engine quality gate → WAIT_ENTRY_QUALITY)
→ VALIDATE RISK (V11 firewall; UNRESOLVED never approves) ── WAIT_RISK_UNSAFE (VALID_ENTRY + RISK_REJECTED)
→ VALIDATE BROKER / EXECUTION SAFETY ── WAIT_BROKER_UNSAFE / WAIT_STALE_DATA
→ TRADE_ELIGIBLE
\`\`\`

- **No fallback.** No step has an automatic fallback strategy.
- **Global preconditions first.** Staleness and active safety breakers are checked before the strategy steps: a halted or blind system does not evaluate entries.

## Path evidence (DEV + HOLD, PRIMARY)
${tbl(['Exit point', 'Bars'], STATES.map((st) => [st, n(tot('PRIMARY', st))]))}
`;

out.V14_RISK_FIREWALL = HEAD('V14_RISK_FIREWALL') + `## Invariant (V11, preserved)
Risk can only ACCEPT or REJECT; it never modifies entry validity.
- **Rejected entries stay valid:** a valid entry rejected by risk is recorded as VALID_ENTRY + RISK_REJECTED, never INVALID_ENTRY or MODIFIED_ENTRY.
- **Enforced in code:** if the V11 integration ever returned a changed entry hash, the gate throws. This never happened.

${tbl(['Split', 'Configuration', 'Engine signals', 'Valid entries', 'Risk-rejected valid entries', 'Broker rejections', 'TRADE_ELIGIBLE'], S2.flatMap((S) => CF.map((c) => [S, c, n(C(S, c).engine_signals), n(C(S, c).valid_entries), n(C(S, c).risk_rejected_valid_entries), n(C(S, c).broker_rejections), n(C(S, c).trade_eligible)])))}

- **PRIMARY:** every valid entry is risk-rejected because RISK_PERCENTAGE is UNRESOLVED; an unresolved risk model can never approve.
- **Illustrative PCT parity:** it reproduces the V11 integration exactly (DEV ${R.splits.DEV.v11_parity.gate_trades} / ${R.splits.DEV.v11_parity.v11_trades} trades, end ${R.splits.DEV.v11_parity.gate_end_equity} / ${R.splits.DEV.v11_parity.v11_end_equity}; HOLD ${R.splits.HOLD.v11_parity.gate_trades} / ${R.splits.HOLD.v11_parity.v11_trades}, end ${R.splits.HOLD.v11_parity.gate_end_equity} / ${R.splits.HOLD.v11_parity.v11_end_equity}).
- **No risk increase after a loss:** the size is always equity × r (V10 library), and the production consecutive-loss breaker halts entries.
`;

const ex = (S) => { try { return readFileSync(join(RES, 'audit_samples', `audit_${S}_PRIMARY_examples.jsonl`), 'utf8').split('\n').filter(Boolean).map((l) => JSON.parse(l)).filter((r) => r.conflict).slice(0, 2); } catch { return []; } };
out.V14_STRATEGY_CONFLICT = HEAD('V14_STRATEGY_CONFLICT') + `## Definition
A conflict is a verified engine signal while another strategy has a valid trigger on the OPPOSITE side at the same bar.
- **Replay:** uses the bias-aware trigger list.
- **Live:** uses the bias-agnostic stages.

## Existing resolution
The frozen engine evaluates the strategies in a fixed priority chain (MC → PB → BO → SR → MR, \`evaluateIntradayModels\`). The first candidate wins, so the existing architecture already defines a deterministic resolution.
- **When a resolution exists:** the gate records STRATEGY_CONFLICT + ${'`'}EXISTING_PRIORITY${'`'} and follows the engine's own choice. No new vote, score or rule is created.
- **When no resolution is defined:** configuration \`conflictResolution: null\` → WAIT_CONFLICT (unit-tested).

${tbl(['Split', 'Configuration', 'Strategy conflicts', 'Resolved by existing priority', 'WAIT_CONFLICT'], S2.flatMap((S) => CF.map((c) => [S, c, C(S, c).strategy_conflicts, C(S, c).conflicts_resolved_by_existing_priority, C(S, c).by_state.WAIT_CONFLICT])))}

ENTRY_CONFLICT and HTF_CONFLICT are engine direction conflicts with higher timeframes, not strategy disagreements. They map to WAIT_DIRECTION_UNCLEAR.
`;

out.V14_AUDIT_LOG = HEAD('V14_AUDIT_LOG') + `## One record per decision (§16)
${tbl(['Field', 'Content'], [['ts, bar_time', 'decision bar (UTC)'], ['symbol, timeframe', 'XAUUSDm, 5m'], ['source', 'V8_REPLAY_ROW or V8_FORWARD_SHADOW'], ['obs', 'per strategy: stage BUY / SELL (0 none, 1 pattern, 2 setup, 3 trigger)'], ['pattern, setup, trigger', 'PRESENT / ABSENT; list of valid triggers'], ['direction, conflict', 'side or UNCLEAR:<reason>; opposite triggers and resolution'], ['location, sl, rr, quality', 'VALID / INVALID / N/A'], ['risk, broker', 'ACCEPTED:<lots> / REJECTED:<reason> / UNSAFE:<reason> / N/A'], ['engine_action, engine_wait_reason', 'the frozen engine\'s own result'], ['valid_entry, entry_id, entry_hash', 'the frozen entry record (never modified)'], ['decision, reason', 'final state and deterministic reason'], ['discrepancy', 'set if an engine signal could not be verified (fail closed)']])}

## Files
- **Full logs** (\`results/audit/\`, kept out of git, included in the handoff zip):
  - PRIMARY: every decision of DEV (${n(R.splits.DEV.rows)}) and HOLD (${n(R.splits.HOLD.rows)});
  - illustrative: every signal bar.
- **sha256 of each log** (\`results/audit_hashes.json\`):
${Object.entries(H).filter(([k]) => k !== 'note').map(([k, v]) => `  - ${k}: ${v}`).join('\n')}
- **Samples (in git):** \`results/audit_samples/\` holds the first 300 PRIMARY decisions per split, 3 examples per state per configuration, and the live forward-shadow gate decisions.

## Reason coverage
Every WAIT record carries a reason. There are 0 WAIT records without one (invariant sweep).
`;

out.V14_REPLAY_VALIDATION = HEAD('V14_REPLAY_VALIDATION') + `${tbl(['Check', 'Result'], [
  ['Chronological replay deterministic: PRIMARY (two runs, identical record hash)', R.replay.deterministic_primary ? 'PASS' : 'FAIL'],
  ['Chronological replay deterministic: illustrative CURRENT with breakers and positions', R.replay.deterministic_current ? 'PASS' : 'FAIL'],
  [`Restart from serialized gate + market state at bar ${n(R.replay.restart_split_at)} = uninterrupted`, R.replay.restart_equals_uninterrupted ? 'PASS' : 'FAIL'],
  ['Duplicate bar / older bar after a decision', `${R.replay.duplicate_and_out_of_order.repeat}; ${R.replay.duplicate_and_out_of_order.older}`],
  ['Illustrative PCT 0.50 % reproduces the V11 integration exactly (trades and end equity, DEV + HOLD)', S2.every((S) => R.splits[S].v11_parity.same) ? 'PASS' : 'FAIL'],
  ['Same input + same state = same decision (1,000 repeats, unit test)', 'PASS'],
  ['Re-running after the discrepancy-flag change: results byte-identical', 'PASS'],
])}
`;

const look = S2.flatMap((S) => CF.filter((c) => c !== 'PRIMARY').map((c) => [S, c, C(S, c).hypothetical_trades_with_outcome, C(S, c).lifecycle_lookahead_violations]));
out.V14_NO_LOOKAHEAD = HEAD('V14_NO_LOOKAHEAD') + `## What the gate can see at bar i
- **Inputs:** the record of bar i (built by the frozen engine from completed bars ≤ i) and the gate's prior state.
- **Position state:** for a hypothetical position the gate only knows whether it is still open; a close is applied only after its exit bar has passed.

## Checks
${tbl(['Check', 'Result'], [['Prefix stability: decisions on the first 20,000 HOLD bars alone = the first 20,000 decisions of the full run', R.replay.prefix_stable_no_lookahead ? 'PASS' : 'FAIL'], ['Unit test: corrupting a later bar never changes an earlier decision', 'PASS'], ['Adapters read no future field (forward-shadow and replay inputs are per-bar records)', 'PASS (by construction)']])}

## Position lifecycle (exit unknown one bar before it happens, known at it; simulator truncated at the decision bar)
${tbl(['Split', 'Configuration', 'Hypothetical trades', 'Lookahead violations'], look)}

**NO_LOOKAHEAD = ${R.decision.failure_conditions.lookahead ? 'FAIL' : 'PASS'}.**
`;

out.V14_FORWARD_SHADOW_COMPATIBILITY = HEAD('V14_FORWARD_SHADOW_COMPATIBILITY') + `## Live input
- **Source:** the gate ran read-only over the V8 forward-shadow decision records (\`state/v8_shadow/decisions.jsonl\`), ${fwd.records} V8 records from ${fwd.period?.[0]} to ${fwd.period?.[1]}.
- **The runner was not touched.**

## PRIMARY (risk UNRESOLVED): every live decision fully determined from recorded fields
${tbl(['State', 'Live decisions'], STATES.map((st) => [st, fwd.primary.by_state[st] ?? 0]))}

## Live engine signals through the gate (illustrative risk model, each record evaluated independently)
${tbl(['Bar (UTC)', 'Engine', 'Gate decision', 'Reason'], fwd.signal_examples.map((x) => [x.ts, x.engine, x.decision, x.reason]))}

## Findings
- **No forced entries:** 0 TRADE_ELIGIBLE where the engine waited (${fwd.eligible_where_engine_waited}).
- **Recorded production safety state is honoured.** For example, a NEWS_BLOCK on a live signal → WAIT_SAFETY_BREAKER, and a late decision (signal older than 600 s) → WAIT_STALE_DATA.
- **Missing field.** With any risk model, ${fwd.missing_field_fail_closed} live valid entries fail closed with DATA_STALE_QUOTE, because ${fwd.missing_field}. The gate refuses to assume a fresh quote.
- **Requirement for live operation with a risk model:** the forward-shadow decision record must carry the quote tick time (or quote age) at decision time. That is a logging addition to the shadow, not an engine change, and it is not made in V14.
`;

const invTot = S2.reduce((s, S) => s + CF.reduce((t, c) => t + C(S, c).invariant_violations.length, 0), 0) + fwd.primary.invariant_violations.length + fwd.illustrative_stateless.invariant_violations.length;
const decTot = S2.reduce((s, S) => s + CF.reduce((t, c) => t + C(S, c).decisions, 0), 0) + fwd.primary.decisions + fwd.illustrative_stateless.decisions;
out.V14_SAFETY_INVARIANTS = HEAD('V14_SAFETY_INVARIANTS') + `${tbl(['Invariant (§19)', 'Unit test', 'Replay sweep'], [['No setup → no trade', 'yes', '0 violations'], ['No trigger → no trade (incl. an unverified engine signal)', 'yes', '0'], ['Unclear direction → no trade', 'yes', '0'], ['Invalid location → no trade', 'yes', '0'], ['Invalid SL → no trade', 'yes', '0'], ['Invalid RR → no trade', 'yes', '0'], ['Unsafe risk → no trade (unresolved, minimum lot, margin, exposure)', 'yes', '0'], ['Stale data → no trade', 'yes', '0'], ['Broker unsafe → no trade', 'yes', '0'], ['Safety breaker → no trade (production limits, kill switch, recorded block)', 'yes', '0'], ['Strategy conflict without a defined resolution → no trade', 'yes', '0'], ['No entry the engine did not generate', 'yes', `${fwd.eligible_where_engine_waited} (live) / 0 (replay)`], ['Every WAIT has a deterministic reason', 'yes', '0']])}

The invariant sweep re-checks every audit record independently of the decision path: ${n(decTot)} decisions across both splits, three configurations and the live records, with **${invTot} violations**.
`;

const P = (k) => tot('PRIMARY', k); const I = (k) => tot('ILLUSTRATIVE_PCT_0_50_10K', k); const CU = (k) => tot('ILLUSTRATIVE_CURRENT_10K', k);
out.V14_FINAL_DECISION = HEAD('V14_FINAL_DECISION') + `## Decision
**${D.TRADE_GATE_STATUS}**

- **Failure conditions:** none.
- **Why partial:** the forward-shadow records lack the quote age needed to run a risk model live (the gate fails closed).
- **V13 is not hidden.** There is no demonstrated edge; the gate does not create one, and under the evidence-supported configuration it produces zero eligible trades.

## Final terminal summary (PRIMARY, DEV + HOLD; illustrative configurations in brackets for path coverage, not approval)
\`\`\`
V14_STATUS              = COMPLETE
TRADE_GATE_STATUS       = ${D.TRADE_GATE_STATUS}
WAIT_NO_SETUP           = ${n(P('WAIT_NO_SETUP'))}
WAIT_NO_TRIGGER         = ${n(P('WAIT_NO_TRIGGER'))}
WAIT_DIRECTION_UNCLEAR  = ${n(P('WAIT_DIRECTION_UNCLEAR'))}
WAIT_INVALID_LOCATION   = ${n(P('WAIT_INVALID_LOCATION'))}   (also WAIT_INVALID_SL ${n(P('WAIT_INVALID_SL'))}, WAIT_INVALID_RR ${n(P('WAIT_INVALID_RR'))}, WAIT_ENTRY_QUALITY ${n(P('WAIT_ENTRY_QUALITY'))})
WAIT_RISK_UNSAFE        = ${n(P('WAIT_RISK_UNSAFE'))}   [PCT 0.50 %: ${n(I('WAIT_RISK_UNSAFE'))}; CURRENT: ${n(CU('WAIT_RISK_UNSAFE'))}]
WAIT_STALE_DATA         = ${n(P('WAIT_STALE_DATA'))}
WAIT_BROKER_UNSAFE      = ${n(P('WAIT_BROKER_UNSAFE'))}   [${n(I('WAIT_BROKER_UNSAFE'))}; ${n(CU('WAIT_BROKER_UNSAFE'))}; unit-tested paths]
WAIT_SAFETY_BREAKER     = ${n(P('WAIT_SAFETY_BREAKER'))}   [PCT: ${n(I('WAIT_SAFETY_BREAKER'))} re-entry guard; CURRENT: ${n(CU('WAIT_SAFETY_BREAKER'))} production breakers + re-entry guard]
STRATEGY_CONFLICTS      = ${n(totF('PRIMARY', 'strategy_conflicts'))} (all resolved by the existing priority chain; WAIT_CONFLICT ${n(P('WAIT_CONFLICT'))})
TRADE_ELIGIBLE          = ${n(P('TRADE_ELIGIBLE'))}   [PCT 0.50 %: ${n(I('TRADE_ELIGIBLE'))}; CURRENT: ${n(CU('TRADE_ELIGIBLE'))}; illustrative only]
RISK_REJECTED           = ${n(totF('PRIMARY', 'risk_rejected_valid_entries'))} valid entries (RISK_PERCENTAGE_UNRESOLVED)
REPLAY_PARITY           = ${R.decision.failure_conditions.nondeterministic || R.decision.failure_conditions.restart_mismatch || R.decision.failure_conditions.v11_parity_failed ? 'FAIL' : 'PASS'} (deterministic, restart-equal, V11 parity exact)
HINDSIGHT_CHECK         = PASS
NO_LOOKAHEAD            = ${R.decision.failure_conditions.lookahead ? 'FAIL' : 'PASS'}
ENTRY_RULES_CHANGED     = NO
STRUCTURAL_SL_CHANGED   = NO
RR                      = 1.70
CAPITAL_HARVEST         = OFF
RISK_PERCENTAGE         = UNRESOLVED
REAL_TRADE_PLACED       = NO
DEMO_TRADE_PLACED       = NO
EXECUTION_AUTHORITY     = NONE
PRODUCTION_CHANGED      = NO
\`\`\`
`;

let k = 0; for (const [name, body] of Object.entries(out)) { writeFileSync(join(REP, `${name}.md`), body.replace(/\n{3,}/g, '\n\n')); k++; }
console.log(`wrote ${k} reports`);
