/**
 * ENTRY ENGINE CORE REBUILD V2 -- study runner (RESEARCH ONLY). Spec: ../V2_PREREGISTRATION.md (hash asserted).
 * EDGE_PHASE=DEV : diagnostics + variant evaluation on DEVELOPMENT only; derives the frozen finalists -> configs/finalists.json
 * EDGE_PHASE=FULL: asserts the finalists hash; evaluates DEV + HOLDOUT once -> results/v2_results.json
 * Same data, same EXIT_F, same costs and same re-entry guard as V1. No production module is modified.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { canReenter } from '../../../src/engine/capitalHarvest/positionManager.js';

const PHASE = process.env.EDGE_PHASE === 'FULL' ? 'FULL' : 'DEV';
const HERE = dirname(fileURLToPath(import.meta.url)); const REPO = join(HERE, '..', '..', '..'); const ROOT = join(REPO, 'research', 'entry_engine_core_rebuild_v2'); const OUT = join(ROOT, 'results'); const CFG = join(ROOT, 'configs'); mkdirSync(OUT, { recursive: true }); mkdirSync(CFG, { recursive: true });
const PREREG_SHA = readFileSync(join(ROOT, 'V2_PREREGISTRATION.sha256'), 'utf8').trim().split(/\s+/)[0];
if (createHash('sha256').update(readFileSync(join(ROOT, 'V2_PREREGISTRATION.md'))).digest('hex') !== PREREG_SHA) throw new Error('V2_PREREGISTRATION hash mismatch');
const LAB = join(REPO, 'handoff', 'edge_discovery_lab', 'data');
const b5 = JSON.parse(readFileSync(join(LAB, 'XAUUSDm_bars.json'), 'utf8'))['5m'];
const COSTS = { normal: { spread: 0.24, slip: 0.10 }, stress: { spread: 0.60, slip: 0.20 } }; const SWAP = 0.56; const HORIZON = 288; const GAP = 3 * 3600;
const r2 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 100) / 100); const r3 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 1000) / 1000);
const iso = (t) => new Date(t * 1000).toISOString(); const day = (t) => iso(t).slice(0, 10); const month = (t) => iso(t).slice(0, 7); const quarter = (t) => { const d = new Date(t * 1000); return `${d.getUTCFullYear()}Q${Math.floor(d.getUTCMonth() / 3) + 1}`; };
const SPLIT = { dev: ['2025-05-07', '2025-12-31'], hold: ['2026-01-01', '2026-09-29'] };
const split = (t) => { const d = day(t); if (d >= SPLIT.dev[0] && d <= SPLIT.dev[1]) return 'DEV'; if (d >= SPLIT.hold[0] && d <= SPLIT.hold[1]) return 'HOLD'; return 'EXCLUDED'; };
const mean = (a) => (a.length ? a.reduce((s, x) => s + x, 0) / a.length : null); const median = (a) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); const m = s.length >> 1; return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2; }; const pct = (a, p) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); return s[Math.min(s.length - 1, Math.floor(p * s.length))]; };
function rng(seed) { let s = seed >>> 0; return () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
function bootCI(v, n = 2000, seed = 20260930, alpha = 0.05) { if (v.length < 2) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0; for (let j = 0; j < v.length; j++) s += v[Math.floor(rand() * v.length)]; ms.push(s / v.length); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor((alpha / 2) * n)]), r3(ms[Math.floor((1 - alpha / 2) * n)])]; }
function blockCI(rows, n = 2000, seed = 7, alpha = 0.05) { const g = {}; for (const r of rows) (g[day(r.e.t)] ??= []).push(r.o.r); const blocks = Object.values(g); if (blocks.length < 5) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0, c = 0; for (let j = 0; j < blocks.length; j++) { const b = blocks[Math.floor(rand() * blocks.length)]; for (const x of b) { s += x; c++; } } ms.push(s / c); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor((alpha / 2) * n)]), r3(ms[Math.floor((1 - alpha / 2) * n)])]; }

// ---------- data ----------
const ROWS = new Map(); const sessions = { DEV: new Set(), HOLD: new Set(), ALL: new Set() }; const ROWLIST = [];
for (const line of readFileSync(join(LAB, 'lab_rows.jsonl'), 'utf8').split('\n')) { if (!line) continue; const r = JSON.parse(line); const sp = split(r.t); if (sp === 'EXCLUDED') continue; r.split = sp; ROWS.set(r.i, r); ROWLIST.push(r); sessions[sp].add(day(r.t)); sessions.ALL.add(day(r.t)); }
const C = readFileSync(join(REPO, 'research', 'entry_architecture_v2', 'results', 'candidates.jsonl'), 'utf8').trim().split('\n').map((l) => JSON.parse(l)).filter((c) => split(c.t) !== 'EXCLUDED');
for (const c of C) { c.split = split(c.t); c.rr = c.geo.rr; c.f = { vol: !!c.vol_ok, ov: !!c.overext_ok, rr: c.geo.rr >= 1.7, q: c.q_final >= c.q_th, fresh: !c.fresh_opp, two: !c.two_factor, htf: !c.htf_conflict }; c.f.all = Object.values(c.f).every(Boolean); c.isSig = c.act === 'BUY' || c.act === 'SELL'; c.row = ROWS.get(c.i) ?? null; c.src = 'CAND'; }
if (C.some((c) => c.f.all !== c.isSig)) throw new Error('FLAG/ACT CONSISTENCY FAILED');
console.log(`phase ${PHASE}; rows ${ROWLIST.length}; candidates ${C.length}; signals ${C.filter((c) => c.isSig).length}`);

// ---------- EXIT_F (identical to V1) ----------
function exitF(e, costs = COSTS.normal, drift = false) {
  const { i, side } = e; const { entry, sl, tp2 } = e.geo; const sp = costs.spread, slip = costs.slip; const sgn = side === 'BUY' ? 1 : -1;
  let fill = side === 'BUY' ? entry + sp : entry, start = i + 1; if (drift) { if (i + 1 >= b5.length) return { status: 'NO_DATA' }; fill = side === 'BUY' ? b5[i + 1].open + sp : b5[i + 1].open; start = i + 2; }
  const d = Math.abs(entry - sl); if (!(d > 0)) return { status: 'INVALID' }; const brokerDist = 1.5 * d + sp; const end = Math.min(b5.length - 1, i + HORIZON);
  let mfe = 0, mae = 0, mae3 = 0, nights = 0, gap = false, exit = null, exitBar = null, pnl = 0;
  for (let j = start; j <= end; j++) { const b = b5[j], p = b5[j - 1]; if (b.time - p.time > GAP) gap = true; if (side === 'BUY' && Math.floor(b.time / 86400) !== Math.floor(p.time / 86400)) nights++;
    const adv = side === 'BUY' ? fill - b.low : (b.high + sp) - fill; const fav = side === 'BUY' ? b.high - fill : fill - (b.low + sp); if (adv > mae) mae = adv; if (j - i <= 3 && adv > mae3) mae3 = adv;
    if (adv >= brokerDist) { exit = 'BROKER_SL'; pnl = -brokerDist - slip; exitBar = j; break; }
    const tpHit = side === 'BUY' ? b.high >= tp2 : (b.low + sp) <= tp2; if (tpHit) { if (fav > mfe) mfe = fav; exit = 'TP2'; pnl = Math.abs(tp2 - fill) - slip; exitBar = j; break; }
    if (fav > mfe) mfe = fav; if (side === 'BUY' ? b.close < sl : b.close > sl) { exit = 'THESIS_INVALIDATION'; pnl = sgn * ((side === 'BUY' ? b.close : b.close + sp) - fill) - slip; exitBar = j; break; } }
  let status = 'RESOLVED'; if (!exit) { if (end < i + HORIZON) return { status: 'NO_DATA' }; status = 'OPEN_AT_HORIZON'; const b = b5[end]; exit = 'HORIZON'; pnl = sgn * ((side === 'BUY' ? b.close : b.close + sp) - fill) - slip; exitBar = end; }
  const swap = side === 'BUY' ? nights * SWAP : 0; pnl -= swap;
  return { status, gap, exit, exitBar, bars: exitBar - i, d: r3(d), pnl_usd: r3(pnl), r: r3(pnl / d), mfe_r: r3(mfe / d), mae_r: r3(mae / d), mae3_r: r3(mae3 / d), cost_usd: r3(sp + slip + swap), cost_r: r3((sp + slip + swap) / d) };
}
const simAll = (arr) => ({ normal: arr.map((e) => exitF(e)), stress: arr.map((e) => exitF(e, COSTS.stress)), drift: arr.map((e) => exitF(e, COSTS.normal, true)) });
console.log('simulating candidates ...'); const OC = simAll(C); C.forEach((c, k) => { c.k = k; });

// ---------- new triggers (PREREGISTRATION section 5) ----------
const NT_PARAMS = { nt1_rngA: 1.5, nt1_body: 0.6, nt2_body: 0.4, nt3_imp6: 0.6, nt3_rngA: 1.2, nt5_body: 0.5 };
function ntGeometry(k, side, atr) { const lows = [b5[k - 2].low, b5[k - 1].low, b5[k].low], highs = [b5[k - 2].high, b5[k - 1].high, b5[k].high]; const entry = b5[k].close; let sl = side === 'BUY' ? Math.min(...lows) - 0.25 * atr : Math.max(...highs) + 0.25 * atr; if (Math.abs(entry - sl) < 0.5 * atr) sl = side === 'BUY' ? entry - 0.5 * atr : entry + 0.5 * atr; const risk = Math.abs(entry - sl); const tp2 = side === 'BUY' ? entry + 2 * risk : entry - 2 * risk; return { entry: r3(entry), sl: r3(sl), tp1: r3(side === 'BUY' ? entry + risk : entry - risk), tp2: r3(tp2), rr: 2.0 }; }
function ntTrigger(r, prev, P = NT_PARAMS) {
  const dirUp = b5[r.i].close > b5[r.i].open; const side0 = dirUp ? 'BUY' : 'SELL';
  if (prev && prev.rg5 === 'COMPRESSION' && r.rngA >= P.nt1_rngA && r.body >= P.nt1_body) return { model: 'NT1_COMPRESSION_EXPANSION', side: side0 };
  if (r.swT === 'SWEEP_LOW' && r.swAge <= 2 && r.slD > 0 && r.body >= P.nt2_body && dirUp) return { model: 'NT2_SWEEP_RECLAIM', side: 'BUY' };
  if (r.swT === 'SWEEP_HIGH' && r.swAge <= 2 && r.shD < 0 && r.body >= P.nt2_body && !dirUp) return { model: 'NT2_SWEEP_RECLAIM', side: 'SELL' };
  if (r.imp6 >= P.nt3_imp6 && r.rngA >= P.nt3_rngA && r.progUp >= 2) return { model: 'NT3_MOMENTUM_IGNITION', side: 'BUY' };
  if (r.imp6 <= -P.nt3_imp6 && r.rngA >= P.nt3_rngA && r.progDn >= 2) return { model: 'NT3_MOMENTUM_IGNITION', side: 'SELL' };
  if (r.evT === 'CHOCH' && r.evAge <= 1 && r.evD === 'BULLISH' && r.evLvlD > 0) return { model: 'NT4_STRUCTURAL_FLIP', side: 'BUY' };
  if (r.evT === 'CHOCH' && r.evAge <= 1 && r.evD === 'BEARISH' && r.evLvlD < 0) return { model: 'NT4_STRUCTURAL_FLIP', side: 'SELL' };
  if (r.evT === 'BOS' && r.bo?.retested && r.bo?.recl && r.bo.age <= 6 && r.body >= P.nt5_body && r.evD === 'BULLISH') return { model: 'NT5_BREAK_RETEST_V2', side: 'BUY' };
  if (r.evT === 'BOS' && r.bo?.retested && r.bo?.recl && r.bo.age <= 6 && r.body >= P.nt5_body && r.evD === 'BEARISH') return { model: 'NT5_BREAK_RETEST_V2', side: 'SELL' };
  return null;
}
function ntGates(r, side) { if (!(r.atr >= 2.0)) return 'ATR_FLOOR'; if (Math.abs(r.e20d) > 2.5) return 'OVEREXTENDED'; if ((r.b15d === 'BULLISH' && side === 'SELL') || (r.b15d === 'BEARISH' && side === 'BUY')) return 'BIAS_OPPOSED'; const trendOpp = (side === 'BUY' && r.m30r === 'BEAR_TREND' && r.m30s === 'BEARISH') || (side === 'SELL' && r.m30r === 'BULL_TREND' && r.m30s === 'BULLISH'); if (trendOpp) return 'TWO_FACTOR_30M'; return null; }
function buildNT(P = NT_PARAMS) { const out = []; const gated = {}; for (let n = 1; n < ROWLIST.length; n++) { const r = ROWLIST[n], prev = ROWLIST[n - 1]; if (r.i < 3) continue; const tr = ntTrigger(r, prev.i === r.i - 1 ? prev : null, P); if (!tr) continue; const g = ntGates(r, tr.side); if (g) { gated[g] = (gated[g] ?? 0) + 1; continue; } out.push({ i: r.i, t: r.t, side: tr.side, model: tr.model, anchor: r.i, geo: ntGeometry(r.i, tr.side, r.atr), atr: r.atr, atrR: r.atrR, rg5: r.rg5, b15d: r.b15d, m30r: r.m30r, h1r: r.h1r, ses: r.ses, split: r.split, row: r, src: 'NT', overext_atr: Math.abs(r.e20d) }); } return { entries: out, gated }; }
console.log('building new triggers ...'); const NTB = buildNT(); const NT = NTB.entries; const ONT = simAll(NT); NT.forEach((e, k) => { e.k = k; }); console.log('NT entries', NT.length, 'gated', JSON.stringify(NTB.gated), Object.entries(NT.reduce((g, e) => { g[e.model] = (g[e.model] ?? 0) + 1; return g; }, {})));
const rowsOf = (arr, O, pred, cse = 'normal') => arr.map((e) => ({ e, o: O[cse][e.k] })).filter((x) => pred(x.e) && x.o.status !== 'NO_DATA' && x.o.status !== 'INVALID');
const inS = (S) => (e) => S === 'ALL' || e.split === S;

// ---------- statistics ----------
function seqWalk(rows) { const trades = []; let exitBar = -1, lastTrade = null, lastLoss = false; const skipped = { SAME_OR_EARLIER_CANDLE: 0, STALE_SAME_SETUP: 0, REVENGE_GUARD: 0 }; const occ = []; for (const x of [...rows].sort((a, b) => a.e.i - b.e.i)) { const ok = canReenter({ signal: x.e, exitBar, lastTrade, lastExitWasLoss: lastLoss }); if (!ok.ok) { skipped[ok.reason]++; continue; } trades.push(x); occ.push([x.e.i, x.o.exitBar]); exitBar = x.o.exitBar; lastTrade = x.e; lastLoss = x.o.r <= 0; } return { trades, skipped, occ }; }
function pathDD(rows, key = 'r') { let cum = 0, peak = 0, dd = 0, streak = 0, maxStreak = 0, sincePeak = 0; const rec = []; for (const x of rows) { cum += x.o[key]; if (cum > peak) { if (sincePeak) rec.push(sincePeak); peak = cum; sincePeak = 0; } else sincePeak++; dd = Math.max(dd, peak - cum); if (x.o[key] <= 0) { streak++; maxStreak = Math.max(maxStreak, streak); } else streak = 0; } return { max_dd: r2(dd), final: r2(cum), max_loss_streak: maxStreak, median_trades_to_recover: median(rec), unrecovered_at_end: sincePeak }; }
function stats(rows, sessSet = null, { ci = true, block = false } = {}) { const R = rows.map((x) => x.o.r); if (!R.length) return { n: 0 }; const w = R.filter((x) => x > 0), l = R.filter((x) => x <= 0); const gw = w.reduce((a, b) => a + b, 0), gl = -l.reduce((a, b) => a + b, 0); const U = rows.map((x) => x.o.pnl_usd); const perDay = {}; for (const x of rows) perDay[day(x.e.t)] = (perDay[day(x.e.t)] ?? 0) + 1; const counts = sessSet ? [...sessSet].map((d) => perDay[d] ?? 0) : null; const months = {}; for (const x of rows) months[month(x.e.t)] = (months[month(x.e.t)] ?? 0) + x.o.r; const mv = Object.values(months); const costU = rows.reduce((s, x) => s + x.o.cost_usd, 0); const ddR = pathDD(rows, 'r'), ddU = pathDD(rows, 'pnl_usd'); const losers = rows.filter((x) => x.o.r <= 0);
  return { n: R.length, win_rate: r3(w.length / R.length), avg_win_r: r3(mean(w)), avg_loss_r: l.length ? r3(-mean(l)) : null, expectancy_r: r3(mean(R)), expectancy_usd: r3(mean(U)), gross_expectancy_usd: r3(mean(U) + costU / R.length), pf: gl > 0 ? r2(gw / gl) : (gw > 0 ? 99 : null), ci95_r: ci ? bootCI(R) : null, ci99_r: ci ? bootCI(R, 2000, 20260930, 0.01) : null, block_ci95_r: block ? blockCI(rows) : null, block_ci99_r: block ? blockCI(rows, 2000, 7, 0.01) : null, max_dd_r: ddR.max_dd, max_dd_usd: ddU.max_dd, net_r: ddR.final, max_loss_streak: ddR.max_loss_streak, median_trades_to_recover: ddR.median_trades_to_recover, mfe_r: r3(mean(rows.map((x) => x.o.mfe_r))), mae_r: r3(mean(rows.map((x) => x.o.mae_r))), mae3_r: r3(mean(rows.map((x) => x.o.mae3_r))), avg_bars: r2(mean(rows.map((x) => x.o.bars))), cost_usd: r3(costU / R.length), cost_r: r3(mean(rows.map((x) => x.o.cost_r))), cost_pct_gross: (mean(U) + costU / R.length) > 0 ? r3((costU / R.length) / (mean(U) + costU / R.length)) : null, trades_per_session: counts ? { median: pct(counts, 0.5), p10: pct(counts, 0.1), p90: pct(counts, 0.9), mean: r2(mean(counts)) } : null, zero_trade_session_rate: counts ? r3(counts.filter((x) => x === 0).length / counts.length) : null, months_positive_share: mv.length ? r3(mv.filter((x) => x > 0).length / mv.length) : null, top5_share: gw > 0 ? r3([...R].sort((a, b) => b - a).slice(0, 5).filter((x) => x > 0).reduce((s, x) => s + x, 0) / gw) : null, exit_mix: Object.fromEntries(Object.entries(rows.reduce((g, x) => { g[x.o.exit] = (g[x.o.exit] ?? 0) + 1; return g; }, {}))), model_mix: Object.fromEntries(Object.entries(rows.reduce((g, x) => { g[x.e.model] = (g[x.e.model] ?? 0) + 1; return g; }, {}))), losers_reaching: losers.length ? { r025: r3(losers.filter((x) => x.o.mfe_r >= 0.25).length / losers.length), r050: r3(losers.filter((x) => x.o.mfe_r >= 0.5).length / losers.length), r075: r3(losers.filter((x) => x.o.mfe_r >= 0.75).length / losers.length), r100: r3(losers.filter((x) => x.o.mfe_r >= 1.0).length / losers.length) } : null, wrong_direction_loss_share: l.length ? r3(losers.filter((x) => x.o.mfe_r < 0.25).length / l.length) : null }; }
const cell = (rows) => { const s = stats(rows, null, { ci: rows.length >= 30 }); return { n: s.n ?? 0, sample: (s.n ?? 0) < 30 ? 'INSUFFICIENT' : 'ok', win_rate: s.win_rate, expectancy_r: s.expectancy_r, pf: s.pf, mfe_r: s.mfe_r, mae_r: s.mae_r, ci95_r: s.ci95_r }; };
const MODELS = ['MC', 'PB', 'BO', 'SR', 'MR'];
const sigRows = (S, cse = 'normal') => rowsOf(C, OC, (c) => c.isSig && inS(S)(c), cse);

// ---------- controls ----------
const ctrl = (() => { const rand = rng(99); const leak = [], nul = []; for (const c of C.filter((c, k) => c.isSig && k % 5 === 0)) { if (c.i + 13 >= b5.length) continue; const fut = b5[c.i + 12].close - b5[c.i].close; const mk = (side) => ({ i: c.i, side, geo: { entry: b5[c.i].close, sl: side === 'BUY' ? b5[c.i].close - c.atr : b5[c.i].close + c.atr, tp2: side === 'BUY' ? b5[c.i].close + c.atr : b5[c.i].close - c.atr } }); const o1 = exitF(mk(fut >= 0 ? 'BUY' : 'SELL')), o2 = exitF(mk(rand() < 0.5 ? 'BUY' : 'SELL')); if (o1.status !== 'NO_DATA' && !o1.gap) leak.push(o1.r); if (o2.status !== 'NO_DATA' && !o2.gap) nul.push(o2.r); }
  const s = C.slice(0, 400); const diff = mean(s.map((c) => exitF(c, { spread: 0.24, slip: 0 }).pnl_usd)) - mean(s.map((c) => exitF(c).pnl_usd));
  const ntOk = NT.every((e) => Math.abs(Math.abs(e.geo.tp2 - e.geo.entry) - 2 * Math.abs(e.geo.entry - e.geo.sl)) < 0.003 && Math.abs(e.geo.entry - e.geo.sl) >= 0.5 * e.atr - 0.002 && b5[e.i].time === e.t && Math.abs(b5[e.i].close - e.geo.entry) < 0.001); /* geometry fields are rounded to 0.001 */ const ntFirstExit = NT.slice(0, 3000).every((e, k) => ONT.normal[k].status === 'NO_DATA' || ONT.normal[k].exitBar >= e.i + 1);
  return { leak_mean_r: r3(mean(leak)), leak_n: leak.length, null_mean_r: r3(mean(nul)), null_n: nul.length, cost_test: { diff: r3(diff), expected: 0.10, pass: Math.abs(diff - 0.10) < 0.001 }, nt_geometry_ok: ntOk, nt_first_exit_after_entry: ntFirstExit, flags_reproduce_production_signals: true }; })();
console.log('controls', JSON.stringify(ctrl)); if (!(ctrl.leak_mean_r > 0.3) || !(Math.abs(ctrl.null_mean_r) < 0.15) || !ctrl.cost_test.pass || !ctrl.nt_geometry_ok || !ctrl.nt_first_exit_after_entry) throw new Error('CONTROL FAILED');

// ---------- rebuilt-model variant specs (PREREGISTRATION section 4) ----------
const aligned = (v, side) => (side === 'BUY' ? v === 1 : v === -1); const trendAligned = (rg, side) => (side === 'BUY' ? rg === 'BULL_TREND' : rg === 'BEAR_TREND');
const evAligned = (r, side) => (side === 'BUY' ? r.evD === 'BULLISH' : r.evD === 'BEARISH'); const run = (r, side) => (side === 'BUY' ? r.runUp : r.runDn); const sameSwing = (r, side) => (side === 'BUY' ? r.slD : -r.shD);
const VARIANTS = {
  BO1: { model: 'BO', p: { age: 3, body: 0.5 }, nb: { age: [2, 4], body: [0.4, 0.6] }, test: (c, r, p) => r.bo?.age <= p.age && r.body >= p.body },
  BO2: { model: 'BO', p: { rngA: 1.0, atrR: 1.0 }, nb: { rngA: [0.8, 1.2], atrR: [0.9, 1.1] }, test: (c, r, p) => r.rngA >= p.rngA && c.atrR >= p.atrR },
  BO3: { model: 'BO', p: {}, nb: {}, test: (c) => aligned(c.a30r, c.side) && aligned(c.a1h, c.side) },
  BO4: { model: 'BO', p: {}, nb: {}, test: (c) => trendAligned(c.rg5, c.side) && aligned(c.a30r, c.side) },
  SR1: { model: 'SR', p: { wick: 0.6, d: 0.3, age: 30 }, nb: { wick: [0.5, 0.7], d: [0.2, 0.4], age: [20, 40] }, test: (c, r, p) => (r.sr?.wick ?? 0) >= p.wick && Math.abs(r.sr?.d ?? 9) <= p.d && (r.evAge ?? 99) <= p.age },
  SR2: { model: 'SR', p: { wick: 0.6, d: 0.3, age: 30 }, nb: { wick: [0.5, 0.7], d: [0.2, 0.4], age: [20, 40] }, test: (c, r, p) => (r.sr?.wick ?? 0) >= p.wick && Math.abs(r.sr?.d ?? 9) <= p.d && (r.evAge ?? 99) <= p.age && ['RANGE', 'COMPRESSION'].includes(c.rg5) },
  SR3: { model: 'SR', p: { age: 3 }, nb: { age: [2, 4] }, test: (c, r, p) => r.evT === 'CHOCH' && evAligned(r, c.side) && r.evAge <= p.age },
  MC1: { model: 'MC', p: { run: 4 }, nb: { run: [3, 5] }, test: (c, r, p) => run(r, c.side) <= p.run },
  MC2: { model: 'MC', p: { age: 3 }, nb: { age: [2, 4] }, test: (c, r, p) => r.evT === 'BOS' && evAligned(r, c.side) && r.evAge <= p.age },
  MC3: { model: 'MC', p: { e20: 1.0 }, nb: { e20: [0.75, 1.25] }, test: (c, r, p) => trendAligned(c.rg5, c.side) && Math.abs(r.e20d) <= p.e20 },
  PB1: { model: 'PB', p: {}, nb: {}, test: (c, r) => trendAligned(c.rg5, c.side) && (c.side === 'BUY' ? r.e20d > 0 : r.e20d < 0) },
  PB2: { model: 'PB', p: { sw: 1.0, body: 0.5 }, nb: { sw: [0.75, 1.25], body: [0.4, 0.6] }, test: (c, r, p) => sameSwing(r, c.side) <= p.sw && r.body >= p.body },
  PB3a: { model: 'PB', p: {}, nb: {}, test: (c) => c.rg5 === 'RANGE' },
  PB3b: { model: 'PB', p: {}, nb: {}, test: (c) => c.side === 'SELL' },
  MR1: { model: 'MR', p: {}, nb: {}, test: (c) => c.side === 'BUY' },
  MR2: { model: 'MR', p: { atrR: 1.0 }, nb: { atrR: [0.9, 1.1] }, test: (c, r, p) => c.atrR >= p.atrR },
  MR3: { model: 'MR', p: { age: 3 }, nb: { age: [2, 4] }, test: (c, r, p) => c.side === 'BUY' && r.swT === 'SWEEP_LOW' && r.swAge <= p.age },
  MR4: { model: 'MR', p: {}, nb: {}, test: (c) => c.rg5 !== 'RANGE' },
};
const variantRows = (name, S, p = null, cse = 'normal') => { const v = VARIANTS[name]; const P = p ?? v.p; return rowsOf(C, OC, (c) => c.isSig && c.model === v.model && inS(S)(c) && c.row && v.test(c, c.row, P), cse); };
const baseRows = (model, S, cse = 'normal') => rowsOf(C, OC, (c) => c.isSig && c.model === model && inS(S)(c), cse);

// ---------- quality V2 (section 6) ----------
const COMPS = ['qStructure', 'qTrigger', 'qEntryLocation', 'qMomentum', 'qVolatility', 'qMtf', 'qSession', 'qRr'];
function qualityAudit(S) { const pop = rowsOf(C, OC, (c) => inS(S)(c) && c.f.vol && c.f.ov && c.f.rr && c.f.fresh && c.f.two && c.f.htf); const out = {}; for (const k of COMPS) { const byV = {}; for (const x of pop) (byV[String(x.e.q_break?.[k] ?? 0)] ??= []).push(x); const vals = Object.entries(byV).map(([v, rows]) => ({ value: Number(v), ...cell(rows), win_rate: stats(rows, null, { ci: false }).win_rate })).sort((a, b) => a.value - b.value); const big = vals.filter((v) => v.n >= 30); const lo = big[0], hi = big.at(-1); const spread = lo && hi && hi.value > lo.value ? hi.expectancy_r - lo.expectancy_r : null; out[k] = { values: vals, spread_r: r3(spread), decision: spread == null ? 'NEUTRAL' : spread >= 0.05 ? 'KEEP' : spread <= -0.05 ? 'REMOVE' : 'NEUTRAL', top_cut: hi?.value ?? null }; } return { population: pop.length, components: out }; }
function qv2Score(c, keep) { return keep.reduce((s, k) => s + (c.q_break?.[k] ?? 0), 0); }

// ---------- move events (V1 definition) ----------
const ATR14 = new Array(b5.length).fill(null); { let sum = 0; const tr = []; for (let k = 1; k < b5.length; k++) { const t = Math.max(b5[k].high - b5[k].low, Math.abs(b5[k].high - b5[k - 1].close), Math.abs(b5[k].low - b5[k - 1].close)); tr.push(t); sum += t; if (tr.length > 14) sum -= tr[tr.length - 15]; if (tr.length >= 14) ATR14[k] = sum / 14; } }
function findEvents(S) { const events = []; let k = 500; const lo = S === 'DEV' ? SPLIT.dev[0] : SPLIT.hold[0], hi = S === 'DEV' ? SPLIT.dev[1] : SPLIT.hold[1]; if (S === 'ALL') return [...findEvents('DEV'), ...findEvents('HOLD')];
  while (k < b5.length - 25) { const d = day(b5[k].time); if (d < lo) { k++; continue; } if (d > hi) break; const a = ATR14[k]; if (!a) { k++; continue; } const c0 = b5[k].close; let up = null, dn = null, maxH = -Infinity, minL = Infinity; for (let j = k + 1; j <= k + 24; j++) { const b = b5[j]; if (b.time - b5[j - 1].time > GAP) break; maxH = Math.max(maxH, b.high); minL = Math.min(minL, b.low); if (up == null && maxH - c0 >= 3 * a && c0 - minL <= a) up = j; if (dn == null && c0 - minL >= 3 * a && maxH - c0 <= a) dn = j; if (up != null || dn != null) break; }
    if (up != null || dn != null) { events.push({ k, t: b5[k].time, dir: up != null ? 'BUY' : 'SELL', atr: r3(a), bars: (up ?? dn) - k }); k += 24; } else k++; } return events; }
function captureStats(events, rows, occ = []) { const by = {}; for (const x of rows) (by[x.e.i] ??= []).push(x.e.side); let cap = 0, early = 0, late = 0, wrong = 0, none = 0, positioned = 0; for (const ev of events) { let e = false, l = false, w = false; for (let j = ev.k - 6; j <= ev.k + 6; j++) for (const s of by[j] ?? []) { if (s === ev.dir) { if (j <= ev.k) e = true; else l = true; } else w = true; } if (e || l) { cap++; if (e) early++; else late++; } else if (w) wrong++; else if (occ.some(([a, b]) => ev.k >= a && ev.k <= b)) positioned++; else none++; } const n = Math.max(1, events.length); return { events: events.length, capture_rate: r3(cap / n), early_capture_rate: r3(early / n), late_capture_rate: r3(late / n), wrong_direction_rate: r3(wrong / n), already_positioned_rate: r3(positioned / n), no_signal_rate: r3(none / n) }; }

// ---------- diagnostics ----------
function diagnostics(S) {
  const sess = sessions[S]; const SIGS = sigRows(S); const D = {};
  const port = (rows) => { const w = seqWalk(rows); return { ...stats(w.trades, sess), skipped: w.skipped }; };
  const withModels = (ms) => SIGS.filter((x) => ms.includes(x.e.model));
  D.structural = { CONTROL: port(SIGS), NO_BO: port(withModels(['MC', 'PB', 'SR', 'MR'])), NO_SR: port(withModels(['MC', 'PB', 'BO', 'MR'])), NO_BO_NO_SR: port(withModels(['MC', 'PB', 'MR'])), MC_ONLY: port(withModels(['MC'])), PB_ONLY: port(withModels(['PB'])), MR_ONLY: port(withModels(['MR'])), MC_PB: port(withModels(['MC', 'PB'])), MC_MR: port(withModels(['MC', 'MR'])), PB_MR: port(withModels(['PB', 'MR'])), MC_PB_MR: port(withModels(['MC', 'PB', 'MR'])) };
  // BO / SR loss classification
  const tagBO = (x) => { const c = x.e, r = c.row, o = x.o, t = []; if (o.mfe_r < 0.25) t.push('FALSE_BREAK'); if ((r?.bo?.age ?? 0) > 6) t.push('LATE'); if (Math.abs(r?.e20d ?? 0) > 2.0) t.push('EXHAUSTION'); if (c.side === 'BUY' ? (r?.shD ?? -9) > -1.0 : (r?.slD ?? 9) < 1.0) t.push('INTO_OPPOSING_STRUCTURE'); if ((r?.rngA ?? 1) < 0.8 && c.atrR < 1.0) t.push('NO_EXPANSION'); if (!aligned(c.a30r, c.side) && c.a30r !== 0 || (!aligned(c.a1h, c.side) && c.a1h !== 0)) t.push('HTF_INCOMPATIBLE'); if (c.overext_atr > 1.5) t.push('EXCESS_DISPLACEMENT'); if ((r?.body ?? 1) < 0.4) t.push('WEAK_CLOSE'); if (o.d / c.atr > 2.0) t.push('FAR_FROM_INVALIDATION'); if (c.rr < 2.0) t.push('POOR_GEOMETRY'); return t; };
  const tagSR = (x) => { const c = x.e, r = c.row, t = []; if (c.side === 'BUY' ? c.rg5 === 'BEAR_TREND' : c.rg5 === 'BULL_TREND') t.push('COUNTERTREND'); if ((r?.sr?.wick ?? 0) < 0.6) t.push('WEAK_REJECTION'); if ((r?.evAge ?? 0) > 30) t.push('STALE_LEVEL'); if ((r?.body ?? 1) < 0.4) t.push('NO_CONFIRMATION'); if ((!aligned(c.a30r, c.side) && c.a30r !== 0) || (!aligned(c.a1h, c.side) && c.a1h !== 0)) t.push('HTF_CONTEXT'); if (c.side === 'BUY' ? (r?.imp6 ?? 0) <= -0.5 : (r?.imp6 ?? 0) >= 0.5) t.push('AGAINST_MOMENTUM'); if (c.side === 'BUY' ? (r?.shD ?? -9) > -1.0 : (r?.slD ?? 9) < 1.0) t.push('NEAR_OPPOSING'); return t; };
  const classify = (rows, tagger) => { const losers = rows.filter((x) => x.o.r <= 0); const tagCount = {}; const perTag = {}; for (const x of rows) { const tags = tagger(x); for (const t of tags) { (perTag[t] ??= []).push(x); if (x.o.r <= 0) tagCount[t] = (tagCount[t] ?? 0) + 1; } } const untagged = losers.filter((x) => tagger(x).length === 0).length; return { signals: rows.length, losers: losers.length, loser_tag_shares: Object.fromEntries(Object.entries(tagCount).sort((a, b) => b[1] - a[1]).map(([k, v]) => [k, r3(v / Math.max(1, losers.length))])), untagged_losers: untagged, tagged_population_economics: Object.fromEntries(Object.entries(perTag).map(([k, v]) => [k, { ...cell(v), share_of_all: r3(v.length / rows.length) }])), untagged_population: cell(rows.filter((x) => tagger(x).length === 0)) }; };
  D.bo_classification = classify(SIGS.filter((x) => x.e.model === 'BO'), tagBO); D.sr_classification = classify(SIGS.filter((x) => x.e.model === 'SR'), tagSR);
  // model feature tables
  const e20b = (v) => (Math.abs(v) < 0.5 ? '<0.5' : Math.abs(v) < 1 ? '0.5-1' : Math.abs(v) < 2 ? '1-2' : '>=2'); const runb = (v) => (v <= 2 ? '<=2' : v <= 4 ? '3-4' : v <= 8 ? '5-8' : '>8'); const swb = (v) => (v < 0.5 ? '<0.5' : v < 1 ? '0.5-1' : v < 2 ? '1-2' : '>=2');
  const atrT = (() => { const v = SIGS.map((x) => x.e.atrR).sort((a, b) => a - b); return [v[Math.floor(v.length / 3)], v[Math.floor((2 * v.length) / 3)]]; })(); const atrb = (v) => (v < atrT[0] ? 'LOW' : v < atrT[1] ? 'MID' : 'HIGH');
  D.model_features = {}; for (const m of MODELS) { const rows = SIGS.filter((x) => x.e.model === m && x.e.row); const grp = (f) => { const g = {}; for (const x of rows) (g[String(f(x))] ??= []).push(x); return Object.fromEntries(Object.entries(g).sort((a, b) => b[1].length - a[1].length).map(([k, v]) => [k, cell(v)])); }; D.model_features[m] = { n: rows.length, by_side: grp((x) => x.e.side), by_rg5: grp((x) => x.e.rg5), by_atr_tercile: grp((x) => atrb(x.e.atrR)), by_e20d: grp((x) => e20b(x.e.row.e20d)), by_run: grp((x) => runb(run(x.e.row, x.e.side))), by_event: grp((x) => `${x.e.row.evT}_${evAligned(x.e.row, x.e.side) ? 'ALIGNED' : 'OPPOSED'}_${x.e.row.evAge <= 3 ? 'FRESH' : 'OLD'}`), by_same_swing_dist: grp((x) => swb(sameSwing(x.e.row, x.e.side))), by_session: grp((x) => x.e.ses), by_sweep: grp((x) => (x.e.row.swT && x.e.row.swAge <= 3 ? `${x.e.row.swT}_FRESH` : 'NO_FRESH_SWEEP')), by_b15d: grp((x) => x.e.b15d), by_h1r: grp((x) => x.e.h1r) }; }
  // variants
  D.variants = {}; for (const [name, v] of Object.entries(VARIANTS)) { const rows = variantRows(name, S); const base = baseRows(v.model, S); const st = stats(rows, sess), bs = stats(base, null, { ci: false }); const w = seqWalk(rows); const sq = stats(w.trades, null, { ci: false }); const stress = stats(variantRows(name, S, null, 'stress'), null, { ci: false }); const nb = {}; for (const [pk, [lo, hi]] of Object.entries(v.nb)) nb[pk] = { [lo]: stats(variantRows(name, S, { ...v.p, [pk]: lo }), null, { ci: false }).expectancy_r ?? null, [v.p[pk]]: st.expectancy_r, [hi]: stats(variantRows(name, S, { ...v.p, [pk]: hi }), null, { ci: false }).expectancy_r ?? null }; D.variants[name] = { model: v.model, params: v.p, n: st.n, share_of_model: r3(st.n / Math.max(1, bs.n)), expectancy_r: st.expectancy_r, ci95_r: st.ci95_r, pf: st.pf, win_rate: st.win_rate, mfe_r: st.mfe_r, mae_r: st.mae_r, base_expectancy_r: bs.expectancy_r, improvement_r: r3((st.expectancy_r ?? 0) - (bs.expectancy_r ?? 0)), sequential: { n: sq.n, expectancy_r: sq.expectancy_r, pf: sq.pf, max_dd_r: sq.max_dd_r }, stress_expectancy_r: stress.expectancy_r, neighbours: nb, supported: st.n >= 80 && st.expectancy_r > 0 && st.pf > 1.05 && st.expectancy_r > (bs.expectancy_r ?? -9) }; }
  // new triggers
  D.new_triggers = {}; const ntModels = [...new Set(NT.map((e) => e.model))].sort(); for (const m of ntModels) { const rows = rowsOf(NT, ONT, (e) => e.model === m && inS(S)(e)); const w = seqWalk(rows); const st = stats(w.trades, sess); const stress = stats(seqWalk(rowsOf(NT, ONT, (e) => e.model === m && inS(S)(e), 'stress')).trades, null, { ci: false }); const drift = stats(seqWalk(rowsOf(NT, ONT, (e) => e.model === m && inS(S)(e), 'drift')).trades, null, { ci: false }); const perSig = stats(rows, null, { ci: rows.length >= 30 }); D.new_triggers[m] = { raw_entries: rows.length, per_entry: { expectancy_r: perSig.expectancy_r, pf: perSig.pf, win_rate: perSig.win_rate, ci95_r: perSig.ci95_r, mfe_r: perSig.mfe_r, mae_r: perSig.mae_r, mae3_r: perSig.mae3_r }, sequential: st, stress_expectancy_r: stress.expectancy_r, drift_expectancy_r: drift.expectancy_r, by_side: { BUY: cell(rows.filter((x) => x.e.side === 'BUY')), SELL: cell(rows.filter((x) => x.e.side === 'SELL')) }, by_rg5: Object.fromEntries(Object.entries(rows.reduce((g, x) => { (g[x.e.rg5] ??= []).push(x); return g; }, {})).map(([k, v]) => [k, cell(v)])), supported: st.n >= 100 && st.expectancy_r > 0.05 && st.pf > 1.10 && (stress.expectancy_r ?? -1) > 0 }; }
  D.new_triggers._gated = NTB.gated; D.new_triggers._all_sequential = stats(seqWalk(rowsOf(NT, ONT, inS(S))).trades, sess);
  // quality
  D.quality = qualityAudit(S); const keep = COMPS.filter((k) => D.quality.components[k].decision === 'KEEP'); const qPop = rowsOf(C, OC, (c) => inS(S)(c) && c.f.vol && c.f.ov && c.f.rr && c.f.fresh && c.f.two && c.f.htf); const scores = qPop.map((x) => qv2Score(x.e, keep)); const thr = keep.length ? median(scores) : null;
  const qb = (s) => String(s); const buckets = {}; if (keep.length) for (const x of qPop) (buckets[qb(qv2Score(x.e, keep))] ??= []).push(x); D.quality.v2 = { keep, remove: COMPS.filter((k) => D.quality.components[k].decision === 'REMOVE'), neutral: COMPS.filter((k) => D.quality.components[k].decision === 'NEUTRAL'), threshold: thr, buckets: Object.fromEntries(Object.entries(buckets).sort((a, b) => Number(a[0]) - Number(b[0])).map(([k, v]) => [k, cell(v)])), QV2A: keep.length ? stats(seqWalk(qPop.filter((x) => qv2Score(x.e, keep) >= thr)).trades, sess) : { n: 0 }, QV2B: keep.length ? stats(seqWalk(qPop.filter((x) => keep.every((k) => (x.e.q_break?.[k] ?? 0) >= D.quality.components[k].top_cut))).trades, sess) : { n: 0 }, production_quality_gate: stats(seqWalk(qPop.filter((x) => x.e.f.q)).trades, sess), no_quality_gate: stats(seqWalk(qPop).trades, sess), v1_buckets: (() => { const b = {}; const qbk = (q) => (q < 55 ? '<55' : q < 65 ? '55-64' : q < 70 ? '65-69' : q < 75 ? '70-74' : q < 80 ? '75-79' : q < 85 ? '80-84' : '>=85'); for (const x of qPop) (b[qbk(x.e.q_final)] ??= []).push(x); return Object.fromEntries(Object.entries(b).map(([k, v]) => [k, cell(v)])); })() };
  // move events: pre-move state, opposite-signal classification, capture
  const events = findEvents(S); const ctlW = seqWalk(SIGS); D.moves = { events: events.length, control: captureStats(events, SIGS, ctlW.occ) };
  const pre = { rg5_k1: {}, rg5_k: {}, event_within3: {}, sweep_within3: {}, compression_k1: 0, imp6_sign: {}, b15d: {}, nt_fires_dir_within_pm3: {} }; const inc = (o, k) => { o[k] = (o[k] ?? 0) + 1; }; const ntBy = {}; for (const e of NT) (ntBy[e.i] ??= []).push(e);
  for (const ev of events) { const r = ROWS.get(ev.k), r1 = ROWS.get(ev.k - 1); if (!r) continue; inc(pre.rg5_k, r.rg5); if (r1) { inc(pre.rg5_k1, r1.rg5); if (r1.rg5 === 'COMPRESSION') pre.compression_k1++; } inc(pre.event_within3, r.evT && r.evAge <= 3 ? `${r.evT}_${r.evD === (ev.dir === 'BUY' ? 'BULLISH' : 'BEARISH') ? 'WITH' : 'AGAINST'}` : 'none'); inc(pre.sweep_within3, r.swT && r.swAge <= 3 ? r.swT : 'none'); inc(pre.imp6_sign, r.imp6 == null ? 'na' : (ev.dir === 'BUY' ? r.imp6 : -r.imp6) >= 0.3 ? 'WITH>=0.3' : (ev.dir === 'BUY' ? r.imp6 : -r.imp6) <= -0.3 ? 'AGAINST<=-0.3' : 'flat'); inc(pre.b15d, r.b15d); let fired = 'none'; for (let j = ev.k - 3; j <= ev.k + 3; j++) for (const e of ntBy[j] ?? []) if (e.side === ev.dir) fired = e.model; inc(pre.nt_fires_dir_within_pm3, fired); }
  D.moves.pre_move_state = pre;
  const oppo = { n: 0, classes: {} }; const sigBy = {}; for (const x of SIGS) (sigBy[x.e.i] ??= []).push(x); const candBy = {}; for (const c of C) (candBy[c.i] ??= []).push(c);
  for (const ev of events) { let opp = null; for (let j = ev.k - 6; j <= ev.k + 6 && !opp; j++) for (const x of sigBy[j] ?? []) if (x.e.side !== ev.dir) { opp = x; break; } if (!opp) continue; oppo.n++; const r = ROWS.get(opp.e.i); const c = opp.e; const tags = []; if (['RANGE', 'TRANSITION', 'COMPRESSION'].includes(c.rg5)) tags.push('REGIME_LAG'); if (c.model === 'MR') tags.push('MEAN_REVERSION_CONFLICT'); if (r?.evT === 'CHOCH' && r.evAge <= 3 && !evAligned(r, ev.dir)) tags.push('LATE_TREND_FLIP'); if (!aligned(c.a1h, c.side) && c.a1h !== 0) tags.push('HTF_CONFLICT'); if (r && (c.side === 'BUY' ? r.imp6 <= -0.5 : r.imp6 >= 0.5)) tags.push('MOMENTUM_LAG'); if (r && (ev.dir === 'BUY' ? r.st5 === 'BEARISH' : r.st5 === 'BULLISH')) tags.push('STRUCTURE_MISREAD'); let mc = false; for (let j = c.i - 3; j <= c.i + 3; j++) for (const d of candBy[j] ?? []) if (d.model !== c.model && d.side === ev.dir) mc = true; if (mc) tags.push('MODEL_CONFLICT'); if (!tags.length) tags.push('UNCLASSIFIED'); for (const t of tags) inc(oppo.classes, t); }
  D.moves.opposite_signal = { ...oppo, classes: Object.fromEntries(Object.entries(oppo.classes).sort((a, b) => b[1] - a[1])) };
  // vetoes as ablations
  const vOpp = (x) => !(x.e.row && (x.e.side === 'BUY' ? x.e.row.imp6 <= -0.5 : x.e.row.imp6 >= 0.5)); const vConf = (x) => { for (let j = x.e.i - 3; j < x.e.i; j++) for (const d of candBy[j] ?? []) if (d.model !== x.e.model && d.side !== x.e.side) return false; return true; };
  const ctl = D.structural.CONTROL; const vetoEval = (name, f) => { const s = port(SIGS.filter(f)); return { name, trades: s.n, removed: SIGS.length - SIGS.filter(f).length, expectancy_r: s.expectancy_r, delta_expectancy_r: r3(s.expectancy_r - ctl.expectancy_r), pf: s.pf, max_dd_r: s.max_dd_r, delta_dd_r: r2(s.max_dd_r - ctl.max_dd_r), removed_population: cell(SIGS.filter((x) => !f(x))), passes: s.expectancy_r > ctl.expectancy_r && s.max_dd_r < ctl.max_dd_r }; };
  D.vetoes = { V_OPP: vetoEval('V_OPP momentum-lag veto', vOpp), V_CONFLICT: vetoEval('V_CONFLICT opposite candidate within 3 bars', vConf) };
  // entry location & timing (CONTROL signals)
  const tercile = (rows, f, label) => { const v = rows.map(f).filter((x) => x != null).sort((a, b) => a - b); const c1 = v[Math.floor(v.length / 3)], c2 = v[Math.floor((2 * v.length) / 3)]; return { cuts: [r3(c1), r3(c2)], LOW: cell(rows.filter((x) => f(x) != null && f(x) < c1)), MID: cell(rows.filter((x) => f(x) != null && f(x) >= c1 && f(x) < c2)), HIGH: cell(rows.filter((x) => f(x) != null && f(x) >= c2)), label }; };
  const rangePos = (x) => { const k = x.e.i; let lo = Infinity, hi = -Infinity; for (let j = k - 19; j <= k; j++) { if (j < 0) continue; lo = Math.min(lo, b5[j].low); hi = Math.max(hi, b5[j].high); } return hi > lo ? (b5[k].close - lo) / (hi - lo) : null; };
  const withRow = SIGS.filter((x) => x.e.row); D.entry_location = { abs_e20d: tercile(withRow, (x) => Math.abs(x.e.row.e20d), 'distance from EMA20 in ATR'), same_side_swing_dist: tercile(withRow, (x) => sameSwing(x.e.row, x.e.side), 'distance from the same-side swing (support for BUY) in ATR'), risk_atr: tercile(SIGS, (x) => x.o.d / x.e.atr, 'structural stop distance in ATR'), tp2_atr: tercile(SIGS, (x) => Math.abs(x.e.geo.tp2 - x.e.geo.entry) / x.e.atr, 'TP2 distance in ATR'), overext_atr: tercile(SIGS, (x) => x.e.overext_atr, 'displacement from the model anchor in ATR'), range_position_20: tercile(SIGS, rangePos, 'position inside the 20-bar range (0 = low, 1 = high; BUY and SELL pooled)'), range_position_20_directional: tercile(SIGS, (x) => { const p = rangePos(x); return p == null ? null : x.e.side === 'BUY' ? p : 1 - p; }, 'position in the 20-bar range in the trade direction (0 = best location, 1 = chasing the extreme)') };
  const tclass = (c) => (c.overext_atr < 0.15 ? 'PREMATURE' : c.overext_atr <= 1.0 ? 'CONFIRMED' : 'LATE_CHASED'); D.timing = Object.fromEntries(['PREMATURE', 'CONFIRMED', 'LATE_CHASED'].map((k) => { const rows = SIGS.filter((x) => tclass(x.e) === k); const s = stats(rows, null, { ci: rows.length >= 30 }); return [k, { ...cell(rows), mae3_r: s.mae3_r, wrong_direction_loss_share: s.wrong_direction_loss_share }]; }));
  // regime review
  const regChanges = {}; let prevR = null, prevDay = null; for (const r of ROWLIST) { if (r.split !== S && S !== 'ALL') continue; const d = day(r.t); if (d !== prevDay) { prevDay = d; prevR = r.rg5; regChanges[d] = 0; continue; } if (r.rg5 !== prevR) { regChanges[d]++; prevR = r.rg5; } } const rc = Object.values(regChanges);
  D.regime_review = { regime_changes_per_session: { median: median(rc), p90: pct(rc, 0.9), mean: r2(mean(rc)) }, moves_starting_in: pre.rg5_k, moves_starting_non_trend_share: r3(events.filter((e) => ['RANGE', 'TRANSITION', 'COMPRESSION'].includes(ROWS.get(e.k)?.rg5)).length / Math.max(1, events.length)), moves_preceded_by_compression_share: r3(pre.compression_k1 / Math.max(1, events.length)), signal_expectancy_by_rg5: Object.fromEntries(Object.entries(SIGS.reduce((g, x) => { (g[x.e.rg5] ??= []).push(x); return g; }, {})).map(([k, v]) => [k, cell(v)])) };
  D.conflict = { with_opposite_candidate_prev3: cell(SIGS.filter((x) => !vConf(x))), without: cell(SIGS.filter(vConf)) };
  return D;
}

// ---------- finalists ----------
function deriveFinalists(D) {
  const supportedVariant = {}; for (const m of MODELS) { const cands = Object.entries(D.variants).filter(([, v]) => v.model === m && v.supported).sort((a, b) => b[1].expectancy_r - a[1].expectancy_r); supportedVariant[m] = cands[0]?.[0] ?? null; }
  const supportedNT = Object.entries(D.new_triggers).filter(([k, v]) => !k.startsWith('_') && v.supported).map(([k]) => k);
  const structural = Object.entries(D.structural).filter(([, v]) => v.n >= 150).sort((a, b) => (b[1].expectancy_r ?? -9) - (a[1].expectancy_r ?? -9)); const f2 = structural[0]?.[0] ?? 'CONTROL';
  const subsets = Object.entries(supportedVariant).filter(([, v]) => v).map(([m, v]) => ({ model: m, variant: v, dev_expectancy_r: D.variants[v].expectancy_r })).sort((a, b) => b.dev_expectancy_r - a.dev_expectancy_r);
  const vetoes = Object.entries(D.vetoes).filter(([, v]) => v.passes).map(([k]) => k);
  return { derived_from: 'DEV', supported_variant_per_model: supportedVariant, supported_new_triggers: supportedNT, quality_v2: { keep: D.quality.v2.keep, threshold: D.quality.v2.threshold, top_cuts: Object.fromEntries(D.quality.v2.keep.map((k) => [k, D.quality.components[k].top_cut])) }, vetoes_attached: vetoes, finalists: { F1: { def: 'CONTROL_NO_BO_NO_SR', models: ['MC', 'PB', 'MR'] }, F2: { def: `best structural combination on DEV: ${f2}`, structural: f2 }, F3: { def: 'union of supported rebuilt subsets', subsets: subsets.map((s) => s.variant) }, F4: { def: 'F3 plus supported new triggers', subsets: subsets.map((s) => s.variant), nt: supportedNT }, F5: { def: 'supported new triggers only', nt: supportedNT }, F6: { def: 'F3 with QV2A replacing the quality gate', subsets: subsets.map((s) => s.variant), qv2a: true }, F7: { def: 'SIMPLE_A: single best supported subset', subsets: subsets.slice(0, 1).map((s) => s.variant) }, F8: { def: 'SIMPLE_B: two best supported subsets', subsets: subsets.slice(0, 2).map((s) => s.variant) } }, nt_params: NT_PARAMS, variant_params: Object.fromEntries(Object.entries(VARIANTS).map(([k, v]) => [k, v.p])) };
}
const STRUCT_MODELS = { CONTROL: MODELS, NO_BO: ['MC', 'PB', 'SR', 'MR'], NO_SR: ['MC', 'PB', 'BO', 'MR'], NO_BO_NO_SR: ['MC', 'PB', 'MR'], MC_ONLY: ['MC'], PB_ONLY: ['PB'], MR_ONLY: ['MR'], MC_PB: ['MC', 'PB'], MC_MR: ['MC', 'MR'], PB_MR: ['PB', 'MR'], MC_PB_MR: ['MC', 'PB', 'MR'] };
function finalistRows(defn, name, S, cse = 'normal', over = {}) { const F = defn.finalists[name]; const keep = defn.quality_v2.keep; const thr = over.qv2_threshold ?? defn.quality_v2.threshold; let rows = [];
  if (F.models) rows = rowsOf(C, OC, (c) => c.isSig && inS(S)(c) && F.models.includes(c.model), cse);
  else if (F.structural) rows = rowsOf(C, OC, (c) => c.isSig && inS(S)(c) && STRUCT_MODELS[F.structural].includes(c.model), cse);
  else { if (F.subsets?.length) { if (F.qv2a && keep.length) { for (const v of F.subsets) { const spec = VARIANTS[v]; rows.push(...rowsOf(C, OC, (c) => inS(S)(c) && c.model === spec.model && c.f.vol && c.f.ov && c.f.rr && c.f.fresh && c.f.two && c.f.htf && qv2Score(c, keep) >= thr && c.row && spec.test(c, c.row, over.variant_params?.[v] ?? spec.p), cse)); } } else for (const v of F.subsets) rows.push(...variantRows(v, S, over.variant_params?.[v] ?? null, cse)); } if (F.nt?.length) { const P = over.nt_params ?? NT_PARAMS; const src = over.nt_params ? buildNTFor(P) : { entries: NT, O: ONT }; rows.push(...rowsOf(src.entries, src.O, (e) => inS(S)(e) && F.nt.includes(e.model), cse)); } }
  const vetoed = rows.filter((x) => { if (defn.vetoes_attached.includes('V_OPP') && x.e.row && (x.e.side === 'BUY' ? x.e.row.imp6 <= -0.5 : x.e.row.imp6 >= 0.5)) return false; return true; });
  return vetoed; }
const NT_CACHE = {}; function buildNTFor(P) { const key = JSON.stringify(P); if (!NT_CACHE[key]) { const b = buildNT(P); const O = simAll(b.entries); b.entries.forEach((e, k) => { e.k = k; }); NT_CACHE[key] = { entries: b.entries, O }; } return NT_CACHE[key]; }
function evaluateFinalist(defn, name, S) { const sess = sessions[S]; const rows = finalistRows(defn, name, S); if (!rows.length) return { n: 0, empty: true }; const w = seqWalk(rows); const st = stats(w.trades, sess, { block: true }); const stress = stats(seqWalk(finalistRows(defn, name, S, 'stress')).trades, null, { ci: false }); const drift = stats(seqWalk(finalistRows(defn, name, S, 'drift')).trades, null, { ci: false }); const q = {}; for (const x of w.trades) (q[quarter(x.e.t)] ??= []).push(x); const walk = Object.fromEntries(Object.entries(q).sort().map(([k, v]) => { const s = stats(v, null, { ci: false }); return [k, { n: s.n, expectancy_r: s.expectancy_r, pf: s.pf, max_dd_r: s.max_dd_r }]; })); const pos = Object.values(walk).filter((v) => v.expectancy_r > 0).length;
  const shuffle = (() => { const rand = rng(11); const byM = {}; for (const x of w.trades) (byM[month(x.e.t)] ??= []).push(x.o.r); const dds = [], streaks = [], recov = []; for (let k = 0; k < 500; k++) { const order = Object.values(byM).sort(() => rand() - 0.5); let cum = 0, peak = 0, dd = 0, stk = 0, ms = 0, since = 0, maxSince = 0; for (const m of order) for (const r of [...m].sort(() => rand() - 0.5)) { cum += r; if (cum > peak) { peak = cum; since = 0; } else { since++; maxSince = Math.max(maxSince, since); } dd = Math.max(dd, peak - cum); if (r <= 0) { stk++; ms = Math.max(ms, stk); } else stk = 0; } dds.push(dd); streaks.push(ms); recov.push(maxSince); } return { dd_r_p50: r2(median(dds)), dd_r_p90: r2(pct(dds, 0.9)), dd_r_p99: r2(pct(dds, 0.99)), loss_streak_p50: median(streaks), loss_streak_p90: pct(streaks, 0.9), longest_underwater_trades_p50: median(recov), longest_underwater_trades_p90: pct(recov, 0.9), tail_loss_r_p99: r2(pct(w.trades.map((x) => -x.o.r), 0.99)) }; })();
  return { signals: rows.length, ...st, skipped: w.skipped, stress: { n: stress.n, expectancy_r: stress.expectancy_r, pf: stress.pf }, drift: { n: drift.n, expectancy_r: drift.expectancy_r, pf: drift.pf }, walk_forward: walk, quarters_positive_share: Object.keys(walk).length ? r3(pos / Object.keys(walk).length) : null, adverse: shuffle, occ: w.occ }; }
function neighbourhood(defn, name, S) { const F = defn.finalists[name]; const out = {}; const evalWith = (over) => { const s = stats(seqWalk(finalistRows(defn, name, S, 'normal', over)).trades, null, { ci: false }); return { n: s.n, expectancy_r: s.expectancy_r, pf: s.pf }; };
  for (const v of F.subsets ?? []) for (const [pk, [lo, hi]] of Object.entries(VARIANTS[v].nb)) { const centre = VARIANTS[v].p[pk]; out[`${v}.${pk}`] = { [lo]: evalWith({ variant_params: { [v]: { ...VARIANTS[v].p, [pk]: lo } } }), [centre]: evalWith({}), [hi]: evalWith({ variant_params: { [v]: { ...VARIANTS[v].p, [pk]: hi } } }) }; }
  if (F.nt?.length) { const NB = { nt1_rngA: [1.25, 1.75], nt1_body: [0.5, 0.7], nt3_imp6: [0.5, 0.7], nt3_rngA: [1.0, 1.4], nt2_body: [0.3, 0.5], nt5_body: [0.4, 0.6] }; for (const [pk, [lo, hi]] of Object.entries(NB)) { const rel = F.nt.some((m) => m.startsWith(pk.slice(0, 3).toUpperCase())); if (!rel) continue; out[`NT.${pk}`] = { [lo]: evalWith({ nt_params: { ...NT_PARAMS, [pk]: lo } }), [NT_PARAMS[pk]]: evalWith({}), [hi]: evalWith({ nt_params: { ...NT_PARAMS, [pk]: hi } }) }; } }
  if (F.qv2a && defn.quality_v2.threshold != null) { const t = defn.quality_v2.threshold; out['QV2A.threshold'] = { [t - 2.5]: evalWith({ qv2_threshold: t - 2.5 }), [t]: evalWith({}), [t + 2.5]: evalWith({ qv2_threshold: t + 2.5 }) }; }
  const classify = (o) => { const vals = Object.values(o).map((v) => v.expectancy_r ?? -9); const centre = vals[1]; return vals.every((v) => v > 0) ? 'ROBUST' : centre > 0 && vals.some((v) => v > 0 && v !== centre) ? 'SENSITIVE' : centre > 0 ? 'FRAGILE' : 'NEGATIVE_CENTRE'; }; for (const k of Object.keys(out)) out[k].classification = classify(out[k]); return out; }

// ---------- run ----------
const result = { meta: { phase: PHASE, generated_utc: new Date().toISOString(), prereg_sha256: PREREG_SHA, controls: ctrl, rows: ROWLIST.length, candidates: C.length, signals: C.filter((c) => c.isSig).length, nt_entries: NT.length, nt_gated: NTB.gated, nt_params: NT_PARAMS, sessions_dev: sessions.DEV.size, sessions_hold: sessions.HOLD.size, split: SPLIT, costs: COSTS } };
console.log('diagnostics DEV ...'); result.DEV = diagnostics('DEV');
const defPath = join(CFG, 'finalists.json');
if (PHASE === 'DEV') { const defn = deriveFinalists(result.DEV); writeFileSync(defPath, JSON.stringify(defn, null, 1)); result.finalist_definitions = defn; result.finalists_DEV = {}; for (const n of Object.keys(defn.finalists)) { const ev = evaluateFinalist(defn, n, 'DEV'); delete ev.occ; result.finalists_DEV[n] = ev; } writeFileSync(join(OUT, 'v2_results_DEV_phase.json'), JSON.stringify(result, null, 1)); console.log('DERIVED', JSON.stringify({ ...defn, variant_params: undefined })); console.log('finalists.json sha256', createHash('sha256').update(readFileSync(defPath)).digest('hex')); }
else { const defn = JSON.parse(readFileSync(defPath, 'utf8')); const frozen = readFileSync(join(CFG, 'finalists.sha256'), 'utf8').trim().split(/\s+/)[0]; if (createHash('sha256').update(readFileSync(defPath)).digest('hex') !== frozen) throw new Error('finalists.json does not match its frozen hash'); result.finalist_definitions = defn; result.finalists_sha256 = frozen;
  console.log('diagnostics HOLD ...'); result.HOLD = diagnostics('HOLD');
  result.finalists = {}; for (const S of ['DEV', 'HOLD']) { result.finalists[S] = {}; const events = findEvents(S); const ctlRows = sigRows(S); const ctlW = seqWalk(ctlRows); const ctlEv = evaluateFinalist({ ...defn, finalists: { CONTROL: { models: MODELS } }, vetoes_attached: [] }, 'CONTROL', S); result.finalists[S].CONTROL = { ...ctlEv, move_capture: captureStats(events, ctlRows, ctlW.occ), occ: undefined };
    for (const n of Object.keys(defn.finalists)) { const ev = evaluateFinalist(defn, n, S); const rows = finalistRows(defn, n, S); const extra = rows.filter((x) => !(x.e.src === 'CAND' && x.e.isSig)); const removed = ctlRows.length - rows.filter((x) => x.e.src === 'CAND' && x.e.isSig).length; result.finalists[S][n] = { ...ev, move_capture: ev.n ? captureStats(events, rows, ev.occ) : null, false_positive: { extra_entries_vs_control: extra.length, extra_winners: extra.filter((x) => x.o.r > 0).length, extra_losers: extra.filter((x) => x.o.r <= 0).length, extra_expectancy_r: stats(extra, null, { ci: extra.length >= 30 }).expectancy_r ?? null, extra_pf: stats(extra, null, { ci: false }).pf ?? null, control_signals_removed: removed }, neighbourhood: S === 'HOLD' || S === 'DEV' ? neighbourhood(defn, n, S) : null, occ: undefined }; } }
  const H = result.finalists.HOLD, ctl = H.CONTROL; const dec = {}; for (const n of Object.keys(defn.finalists)) { const c = H[n]; const reasons = []; if (!c.n || c.empty) { dec[n] = { status: 'EMPTY', reasons: ['no entries'] }; continue; } if (c.n < 200) reasons.push('N<200'); if (!(c.expectancy_r > 0)) reasons.push('expectancy<=0'); if (!(c.ci95_r?.[0] > 0)) reasons.push('trade CI includes 0'); if (!(c.block_ci95_r?.[0] > 0)) reasons.push('session-block CI includes 0'); if (!(c.pf > 1.10)) reasons.push('PF<=1.10'); if (!(c.max_dd_r <= ctl.max_dd_r)) reasons.push('DD worse than CONTROL'); if ((c.top5_share ?? 1) > 0.3) reasons.push('top5>30%'); if (!((c.quarters_positive_share ?? 0) >= 0.6)) reasons.push('quarters positive <60%'); if (!(c.stress.expectancy_r > 0)) reasons.push('stress<=0'); if (!(c.drift.expectancy_r > 0)) reasons.push('drift<=0'); if (!(result.finalists.DEV[n]?.expectancy_r > 0)) reasons.push('DEV<=0'); const nbBad = Object.entries(c.neighbourhood ?? {}).filter(([, v]) => v.classification !== 'ROBUST').map(([k, v]) => `${k}:${v.classification}`); if (nbBad.length) reasons.push(`thresholds not ROBUST (${nbBad.join(', ')})`); dec[n] = { status: reasons.length ? 'FAILS_FINALIST_REQUIREMENTS' : 'FINALIST_QUALIFIED', reasons, hold_n: c.n, hold_expectancy_r: c.expectancy_r, hold_pf: c.pf, hold_dd_r: c.max_dd_r, block_ci95_r: c.block_ci95_r }; }
  const qualified = Object.entries(dec).filter(([, d]) => d.status === 'FINALIST_QUALIFIED').sort((a, b) => (H[b[0]].block_ci95_r?.[0] ?? -9) - (H[a[0]].block_ci95_r?.[0] ?? -9)); const finalist = qualified[0]?.[0] ?? null;
  const anyPos = Object.keys(defn.finalists).some((n) => H[n].n >= 200 && H[n].expectancy_r > 0 && !(H[n].ci95_r?.[0] > 0));
  result.decisions = { candidates: dec, finalist, edge_demonstrated: finalist ? 'YES' : anyPos ? 'INCONCLUSIVE' : 'NO', v2_beats_v1_control: finalist ? ((H[finalist].ci95_r[0] > ctl.expectancy_r && H[finalist].max_dd_r <= ctl.max_dd_r) ? 'YES' : (H[finalist].expectancy_r > ctl.expectancy_r ? 'INCONCLUSIVE' : 'NO')) : (Object.keys(defn.finalists).some((n) => H[n].n >= 200 && H[n].expectancy_r > ctl.expectancy_r) ? 'INCONCLUSIVE (higher point estimate, no qualifying finalist)' : 'NO'), demo_eligible: finalist ? 'YES (subject to parity fixtures + P1)' : 'NO' };
  writeFileSync(join(OUT, 'v2_results.json'), JSON.stringify(result, null, 1)); console.log('DECISIONS', JSON.stringify(result.decisions, null, 1)); }
console.log('written', PHASE);
