// Generates the machine-derived markdown documents of handoff/ENTRY_ENGINE_CORE_REBUILD_V2 from results/v2_results.json.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const HERE = dirname(fileURLToPath(import.meta.url)); const REPO = join(HERE, '..', '..', '..'); const R = JSON.parse(readFileSync(join(REPO, 'research', 'entry_engine_core_rebuild_v2', 'results', 'v2_results.json'), 'utf8')); const OUT = join(REPO, 'handoff', 'ENTRY_ENGINE_CORE_REBUILD_V2'); mkdirSync(OUT, { recursive: true });
const f = (x, d = 3) => (x == null ? '—' : typeof x === 'number' ? (Number.isInteger(x) ? String(x) : x.toFixed(d)) : String(x)); const ci = (c) => (c ? `[${f(c[0])}, ${f(c[1])}]` : '—'); const pc = (x) => (x == null ? '—' : `${(x * 100).toFixed(1)} %`); const S2 = ['DEV', 'HOLD']; const W = (name, md) => writeFileSync(join(OUT, name), md);
const cellRow = (k, v, extra = '') => `| ${k} | ${v.n}${v.sample === 'INSUFFICIENT' ? ' (INSUFFICIENT)' : ''} | ${pc(v.win_rate)} | ${f(v.expectancy_r)} | ${f(v.pf, 2)} | ${f(v.mfe_r, 2)} / ${f(v.mae_r, 2)} | ${ci(v.ci95_r)} |${extra}`;
const CELLH = '| Segment | N | Win rate | Expectancy (R) | PF | MFE / MAE (R) | 95 % CI |\n|---|---|---|---|---|---|---|';
const grp = (o) => Object.entries(o).map(([k, v]) => cellRow(k, v)).join('\n');
// ---- diagnosis per model
const DIAG = { MC: 'MC_DIAGNOSIS.md', PB: 'PB_DIAGNOSIS.md', BO: 'BO_DIAGNOSIS.md', SR: 'SR_DIAGNOSIS.md', MR: 'MR_DIAGNOSIS.md' };
for (const [m, file] of Object.entries(DIAG)) { let md = `# ${m} DIAGNOSIS (production ${m} signals, EXIT_F normal costs; feature tables by DEV and HOLDOUT; cells with N < 30 are INSUFFICIENT)\n`;
  for (const S of S2) { const F = R[S].model_features[m]; md += `\n## ${S} (${F.n} signals)\n`; for (const [title, key] of [['Side', 'by_side'], ['5m regime', 'by_rg5'], ['ATR-ratio tercile', 'by_atr_tercile'], ['|EMA20 distance| (ATR)', 'by_e20d'], ['Run length on the trade side (bars beyond EMA20)', 'by_run'], ['Last structure event (type_alignment_freshness ≤ 3 bars)', 'by_event'], ['Distance from the same-side swing (ATR)', 'by_same_swing_dist'], ['Fresh sweep (≤ 3 bars)', 'by_sweep'], ['Session', 'by_session'], ['15m bias', 'by_b15d'], ['1H regime', 'by_h1r']]) md += `\n### ${title}\n${CELLH}\n${grp(F[key])}\n`; }
  if (m === 'BO') for (const S of S2) { const c = R[S].bo_classification; md += `\n## ${S} — BO loss classification (${c.signals} signals, ${c.losers} losers; tags are not exclusive)\n| Tag | Share of losers | Population N | Share of all BO | Population expectancy (R) | PF | 95 % CI |\n|---|---|---|---|---|---|---|\n${Object.entries(c.loser_tag_shares).map(([k, v]) => { const e = c.tagged_population_economics[k]; return `| ${k} | ${pc(v)} | ${e.n} | ${pc(e.share_of_all)} | ${f(e.expectancy_r)} | ${f(e.pf, 2)} | ${ci(e.ci95_r)} |`; }).join('\n')}\n\nUntagged losers: ${c.untagged_losers}; untagged population: n ${c.untagged_population.n}, expectancy ${f(c.untagged_population.expectancy_r)} R.\n`; }
  if (m === 'SR') for (const S of S2) { const c = R[S].sr_classification; md += `\n## ${S} — SR loss classification (${c.signals} signals, ${c.losers} losers)\n| Tag | Share of losers | Population N | Population expectancy (R) | PF | 95 % CI |\n|---|---|---|---|---|---|\n${Object.entries(c.loser_tag_shares).map(([k, v]) => { const e = c.tagged_population_economics[k]; return `| ${k} | ${pc(v)} | ${e.n} | ${f(e.expectancy_r)} | ${f(e.pf, 2)} | ${ci(e.ci95_r)} |`; }).join('\n')}\n`; }
  W(file, md); }
// ---- rebuild / research per model (variants)
const REB = { BO: 'BO_REBUILD.md', SR: 'SR_REBUILD.md', MC: 'MC_RESEARCH.md', PB: 'PB_RESEARCH.md', MR: 'MR_RESEARCH.md' };
for (const [m, file] of Object.entries(REB)) { let md = `# ${m} — pre-registered variant family (filters on production ${m} signals; every downstream gate identical; EXIT_F)\n\nSupported (DEV rule): N ≥ 80, expectancy > 0, PF > 1.05 and above the model's base expectancy.\n`;
  for (const S of S2) { md += `\n## ${S}\n| Variant | Params | N | Share of ${m} | Win rate | Expectancy (R) | 95 % CI | PF | MFE / MAE (R) | Base ${m} expectancy | Improvement (R) | Sequential N / exp / PF / DD | Stress exp | Supported (DEV rule) | Neighbours |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n`; const base = R[S].model_features[m]; md += `| ${m}0 (current) | — | ${base.n} | 100 % | — | ${f(Object.values(R[S].variants).find((v) => v.model === m)?.base_expectancy_r)} | — | — | — | — | — | — | — | — | — |\n`; for (const [k, v] of Object.entries(R[S].variants).filter(([, v]) => v.model === m)) md += `| ${k} | ${JSON.stringify(v.params)} | ${v.n} | ${pc(v.share_of_model)} | ${pc(v.win_rate)} | ${f(v.expectancy_r)} | ${ci(v.ci95_r)} | ${f(v.pf, 2)} | ${f(v.mfe_r, 2)} / ${f(v.mae_r, 2)} | ${f(v.base_expectancy_r)} | ${f(v.improvement_r)} | ${v.sequential.n} / ${f(v.sequential.expectancy_r)} / ${f(v.sequential.pf, 2)} / ${f(v.sequential.max_dd_r, 1)} | ${f(v.stress_expectancy_r)} | ${v.supported ? 'YES' : 'no'} | ${Object.entries(v.neighbours).map(([p, o]) => `${p}: ${Object.entries(o).map(([a, b]) => `${a}→${f(b)}`).join(' ')}`).join('; ') || '—'} |\n`; }
  W(file, md); }
// ---- quality
let md = `# QUALITY COMPONENT AUDIT (candidates passing every gate except quality; EXIT_F; per discrete component value)\n\nDecision rule (pre-registered): KEEP if the largest well-populated value (N ≥ 30) beats the smallest by ≥ +0.05 R; REMOVE if it is worse by ≥ 0.05 R (inverse); otherwise NEUTRAL.\n`;
for (const S of S2) { const Q = R[S].quality; md += `\n## ${S} (population ${Q.population})\n| Component | Decision | Top − bottom (R) | Values: score → N / expectancy (R) / PF / win rate |\n|---|---|---|---|\n${Object.entries(Q.components).map(([k, v]) => `| ${k} | **${v.decision}** | ${f(v.spread_r)} | ${v.values.map((x) => `${x.value} → ${x.n} / ${f(x.expectancy_r)} / ${f(x.pf, 2)} / ${pc(x.win_rate)}`).join('; ')} |`).join('\n')}\n`; }
W('QUALITY_COMPONENT_AUDIT.md', md);
md = `# QUALITY V2\n\nQV2A = simplified score from the DEV-KEEP components (${R.finalist_definitions.quality_v2.keep.join(', ')}), threshold ${R.finalist_definitions.quality_v2.threshold} (DEV median). QV2B = every KEEP component at its DEV top value. Both replace only the production quality gate; all other gates identical. Sequential one-position portfolios.\n`;
for (const S of S2) { const v = R[S].quality.v2; const t = (s) => (s && s.n ? `${s.n} / ${f(s.expectancy_r)} / ${f(s.pf, 2)} / ${f(s.max_dd_r, 1)}` : '0'); md += `\n## ${S}\nComponent decisions on ${S}: KEEP ${v.keep.join(', ') || 'none'}; REMOVE ${v.remove.join(', ') || 'none'}; NEUTRAL ${v.neutral.join(', ') || 'none'}; ${S}-median threshold ${v.threshold}.\n\n| Gate | N / expectancy (R) / PF / max DD (R) |\n|---|---|\n| Production quality gate (65/70) | ${t(v.production_quality_gate)} |\n| No quality gate | ${t(v.no_quality_gate)} |\n| QV2A (${S}-derived components, threshold ${v.threshold}) | ${t(v.QV2A)} |\n| QV2B (explicit component gates) | ${t(v.QV2B)} |\n\nV1 production-score buckets on ${S}: ${Object.entries(v.v1_buckets).map(([k, b]) => `${k} → n ${b.n}, ${f(b.expectancy_r)} R`).join('; ')}.\n\nQV2A score buckets on ${S} (score → n / expectancy / PF): ${Object.entries(v.buckets).filter(([, b]) => b.n >= 30).map(([k, b]) => `${k} → ${b.n} / ${f(b.expectancy_r)} / ${f(b.pf, 2)}`).join('; ')}.\n`; }
md += `\n## Verdict\nQUALITY_V1_MONOTONIC = NO (both splits). QUALITY_V2_MONOTONIC = NO: the components that looked monotonic on DEV (structure, trigger, momentum, volatility, RR) reversed on HOLDOUT; only qMtf kept its sign, and qEntryLocation is inverted in both splits (mid values 3–7 best, 12–15 worst). No reconstructed score or explicit component gate beats the production gate or no gate at all (QV2A ${f(R.HOLD.quality.v2.QV2A?.expectancy_r)} vs production ${f(R.HOLD.quality.v2.production_quality_gate.expectancy_r)} vs none ${f(R.HOLD.quality.v2.no_quality_gate.expectancy_r)} R on HOLDOUT). The aggregate score is not a reliable ranking of trade quality and should not be trusted as one; economically its gate is close to neutral (removing it changes expectancy by ≈ 0.01 R and DD by 16 R). Recommendation recorded, not applied: stop using the score as a quality ranking; if a gate is wanted, an explicit MTF-alignment gate is the only component with same-sign evidence.\n`;
W('QUALITY_V2.md', md);
// ---- setup / trigger
md = `# SETUP / TRIGGER DIAGNOSIS (state immediately before objective move events; contemporaneous features only)\n`;
for (const S of S2) { const M = R[S].moves; const p = M.pre_move_state; const n = M.events; const dist = (o) => Object.entries(o).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${v} (${pc(v / n)})`).join(', '); md += `\n## ${S} — ${n} move events; CONTROL capture ${pc(M.control.capture_rate)} (early ${pc(M.control.early_capture_rate)}, late ${pc(M.control.late_capture_rate)}), wrong direction ${pc(M.control.wrong_direction_rate)}, already positioned ${pc(M.control.already_positioned_rate)}, no signal ${pc(M.control.no_signal_rate)}\n| Pre-move state at k−1 / k | Distribution |\n|---|---|\n| 5m regime at k−1 | ${dist(p.rg5_k1)} |\n| 5m regime at k | ${dist(p.rg5_k)} |\n| Structure event within 3 bars (with/against the coming move) | ${dist(p.event_within3)} |\n| Fresh sweep within 3 bars | ${dist(p.sweep_within3)} |\n| Compression at k−1 | ${p.compression_k1} (${pc(p.compression_k1 / n)}) |\n| 6-bar efficiency sign vs the move | ${dist(p.imp6_sign)} |\n| 15m bias at k | ${dist(p.b15d)} |\n| New-trigger fired in the move direction within ± 3 bars | ${dist(p.nt_fires_dir_within_pm3)} |\n`; }
md += `\n## Reading\nMoves start from non-trend states (≈ 53 % RANGE/COMPRESSION/TRANSITION; 26–28 % directly after a COMPRESSION candle), with NO structure event within the previous 3 bars in ≈ 78 % of cases and no fresh sweep in ≈ 78 %; the 6-bar efficiency is flat in ≈ 75 %. There is therefore no recurring, deterministic pre-move structure in the engine's feature set: the move IS the first structural evidence, and any trigger that waits for it enters after 1–3 ATR of the 3-ATR move. PRIMARY_SETUP_TRIGGER_FAILURE = moves begin without confirmable structure; confirmation-based triggers (production models and the five new triggers) arrive late or on the wrong side (STRUCTURE_MISREAD 88 % of opposite signals).\n`;
W('SETUP_TRIGGER_DIAGNOSIS.md', md);
md = `# SETUP / TRIGGER REBUILD — five new deterministic triggers (PREREGISTRATION §5), frozen gates, EXIT_F with 2 R objective\n`;
for (const S of S2) { const NT = R[S].new_triggers; md += `\n## ${S}\n| Trigger | Raw entries | Per-entry expectancy (R) / PF / win / MAE3 | Sequential N / expectancy / PF / DD (R) / 95 % CI | Stress exp | Drift exp | BUY N / exp | SELL N / exp | Supported (DEV rule) |\n|---|---|---|---|---|---|---|---|---|\n${Object.entries(NT).filter(([k]) => !k.startsWith('_')).map(([k, v]) => `| ${k} | ${v.raw_entries} | ${f(v.per_entry.expectancy_r)} / ${f(v.per_entry.pf, 2)} / ${pc(v.per_entry.win_rate)} / ${f(v.per_entry.mae3_r, 2)} | ${v.sequential.n} / ${f(v.sequential.expectancy_r)} / ${f(v.sequential.pf, 2)} / ${f(v.sequential.max_dd_r, 1)} / ${ci(v.sequential.ci95_r)} | ${f(v.stress_expectancy_r)} | ${f(v.drift_expectancy_r)} | ${v.by_side.BUY.n} / ${f(v.by_side.BUY.expectancy_r)} | ${v.by_side.SELL.n} / ${f(v.by_side.SELL.expectancy_r)} | ${v.supported ? 'YES' : 'no'} |`).join('\n')}\n\nAll five together (sequential): n ${NT._all_sequential.n}, ${f(NT._all_sequential.expectancy_r)} R, PF ${f(NT._all_sequential.pf, 2)}. Gated out before entry: ${Object.entries(R.meta.nt_gated).map(([k, v]) => `${k} ${v}`).join(', ')}.\n`; }
md += `\n## Result\nSETUP_TRIGGER_REBUILD_RESULT = NO STABLE EDGE. NT1 (compression → expansion bar) was the only trigger supported on DEV (+0.087 R, PF 1.12, n 188, stress +0.02) and reversed on HOLDOUT (−0.036 R, PF 0.96, n 295; both threshold neighbours negative). Sweep-reclaim, structural flip and break-retest V2 are negative in both splits; momentum ignition fires 5–13 times (too rare). The new triggers raise raw capture of move events only from 26.6 % to at most 15.7 % for F4 (they replace, not add to, CONTROL's set) and add 431 HOLDOUT entries at −0.054 R (FALSE_POSITIVE_ANALYSIS.md).\n`;
W('SETUP_TRIGGER_REBUILD.md', md);
// ---- opposite signal, location, timing, regime, conflict
md = `# OPPOSITE-SIGNAL ANALYSIS (move events with an opposite-direction CONTROL signal within ± 6 bars; tags not exclusive)\n`;
for (const S of S2) { const o = R[S].moves.opposite_signal; md += `\n## ${S}: ${o.n} events (${pc(o.n / R[S].moves.events)} of moves)\n| Class | Count | Share |\n|---|---|---|\n${Object.entries(o.classes).map(([k, v]) => `| ${k} | ${v} | ${pc(v / o.n)} |`).join('\n')}\n\nDeterministic vetoes tested on CONTROL (${S}): ${Object.values(R[S].vetoes).map((v) => `${v.name}: removes ${v.removed} signals (removed population ${f(v.removed_population.expectancy_r)} R), Δexpectancy ${f(v.delta_expectancy_r)}, ΔDD ${f(v.delta_dd_r, 1)} R → ${v.passes ? 'PASS' : 'no improvement'}`).join('; ')}.\n`; }
md += `\n## Reading\nThe engine's opposite signals during major moves are overwhelmingly STRUCTURE_MISREAD (the 5m structure state at signal time pointed the other way and the move then broke it) combined with REGIME_LAG (non-trend regime label); HTF conflict and late flips are secondary; mean-reversion conflict is small. Neither pre-registered veto helps: the momentum-lag veto almost never fires (|imp6| ≥ 0.5 is rare) and the conflict veto removes a population that is no worse than the rest. No deterministic veto or regime-transition tweak available in the current feature set reduces wrong-direction entries without hindsight.\n`;
W('OPPOSITE_SIGNAL_ANALYSIS.md', md);
md = `# ENTRY LOCATION ANALYSIS (CONTROL signals; deterministic geometry; terciles)\n`;
for (const S of S2) { const L = R[S].entry_location; md += `\n## ${S}\n| Feature | Tercile cuts | LOW N / expectancy (R) | MID N / expectancy | HIGH N / expectancy |\n|---|---|---|---|---|\n${Object.entries(L).map(([k, v]) => `| ${v.label} | ${v.cuts.join(' / ')} | ${v.LOW.n} / ${f(v.LOW.expectancy_r)} | ${v.MID.n} / ${f(v.MID.expectancy_r)} | ${v.HIGH.n} / ${f(v.HIGH.expectancy_r)} |`).join('\n')}\n`; }
md += `\n## Reading\nSame sign in both splits: wider structural stops (HIGH risk-ATR tercile) and larger displacement from the anchor (HIGH overext tercile) earn more; entries closest to the same-side swing (LOW distance) earn least; premature entries (low displacement) have the highest immediate adverse excursion. Distance-to-objective and EMA distance are not monotonic. The production entry-location component rewards exactly the region (close to the anchor, low displacement) that performs worst — which is why it is inverted in the quality audit.\n`;
W('ENTRY_LOCATION_ANALYSIS.md', md);
md = `# ENTRY TIMING ANALYSIS (PREMATURE < 0.15 ATR, CONFIRMED 0.15–1.0, LATE/CHASED > 1.0 displacement from the anchor)\n`;
for (const S of S2) md += `\n## ${S}\n| Class | N | Win rate | Expectancy (R) | PF | MFE / MAE (R) | MAE within 3 bars (R) | Wrong-direction loss share | 95 % CI |\n|---|---|---|---|---|---|---|---|---|\n${Object.entries(R[S].timing).map(([k, v]) => `| ${k} | ${v.n} | ${pc(v.win_rate)} | ${f(v.expectancy_r)} | ${f(v.pf, 2)} | ${f(v.mfe_r, 2)} / ${f(v.mae_r, 2)} | ${f(v.mae3_r, 2)} | ${pc(v.wrong_direction_loss_share)} | ${ci(v.ci95_r)} |`).join('\n')}\n`;
md += `\nReading: identical to V1 and stable across splits — later entries have lower immediate adverse excursion (0.46 vs 1.07 R within 3 bars) and higher expectancy; "waiting for more confirmation" does not collapse RR here because production's objective is already ≥ 2 R. Exhaustion entries (|EMA20 distance| > 2 ATR) are not worse than others (BO EXHAUSTION population +0.114 R on HOLDOUT).\n`;
W('ENTRY_TIMING_ANALYSIS.md', md);
md = `# REGIME ENGINE REVIEW\n`;
for (const S of S2) { const g = R[S].regime_review; md += `\n## ${S}\nRegime changes per session: median ${g.regime_changes_per_session.median}, P90 ${g.regime_changes_per_session.p90}, mean ${g.regime_changes_per_session.mean} (a 5m regime label flips roughly every 8–9 candles). Moves starting in a non-trend regime: ${pc(g.moves_starting_non_trend_share)}; preceded by a COMPRESSION candle: ${pc(g.moves_preceded_by_compression_share)}. Moves by regime at onset: ${Object.entries(g.moves_starting_in).map(([k, v]) => `${k} ${v}`).join(', ')}.\n\n${CELLH}\n${grp(g.signal_expectancy_by_rg5)}\n`; }
md += `\n## Verdict\nThe regime engine oscillates heavily and its labels do not separate signal economics consistently (BULL_TREND +0.018 on DEV / −0.101 on HOLDOUT; BEAR_TREND −0.161 / +0.059; RANGE −0.309 / +0.064). It contributes lag (52 % of opposite signals carry REGIME_LAG) but rebuilding it is out of this project's scope; the minimal deterministic candidate for a future pre-registration is hysteresis (require k consecutive candles before a regime label changes). Not implemented.\n`;
W('REGIME_REVIEW.md', md);
md = `# MODEL CONFLICT ANALYSIS\n\nProduction emits one candidate per candle (fixed model order), so same-bar conflicts cannot occur. Conflict is measured as an opposite-side candidate from another model within the previous 3 bars.\n`;
for (const S of S2) { const c = R[S].conflict; md += `\n## ${S}\n${CELLH}\n${cellRow('signal WITH an opposite-side candidate in the previous 3 bars', c.with_opposite_candidate_prev3)}\n${cellRow('signal WITHOUT', c.without)}\n`; }
md += `\nV_CONFLICT veto (skip such signals): ${S2.map((S) => `${S}: Δexpectancy ${f(R[S].vetoes.V_CONFLICT.delta_expectancy_r)} R, ΔDD ${f(R[S].vetoes.V_CONFLICT.delta_dd_r, 1)} R`).join('; ')} → no improvement. Model agreement within ± 3 bars (V1) improved expectancy modestly but never to a positive CI. Conflict resolution rule: none supported; explicit WAIT on conflict is not better than the current first-model-wins order.\n`;
W('MODEL_CONFLICT_ANALYSIS.md', md);
// ---- structural / candidates / finalists
const st = (S) => `| Portfolio | N | Expectancy (R) | 95 % CI | PF | Max DD (R) | Zero-trade sessions | Win rate |\n|---|---|---|---|---|---|---|---|\n${Object.entries(R[S].structural).map(([k, v]) => `| ${k} | ${v.n} | ${f(v.expectancy_r)} | ${ci(v.ci95_r)} | ${f(v.pf, 2)} | ${f(v.max_dd_r, 1)} | ${pc(v.zero_trade_session_rate)} | ${pc(v.win_rate)} |`).join('\n')}`;
W('CANDIDATE_DEFINITIONS.md', `# CANDIDATE DEFINITIONS\n\n## Structural simplification (§6) — sequential one-position portfolios\n${S2.map((S) => `\n### ${S}\n${st(S)}`).join('\n')}\n\nReading: removing BO and SR removes most of the drawdown (98.9 → 35.5 R on HOLDOUT) and turns the point estimate positive (+0.044 R) but not the confidence interval; on DEV the same portfolio is −0.058 R. Removing damage does not create edge; it reduces variance.\n\n## Rebuilt-model variants (§4) — see BO_REBUILD.md, SR_REBUILD.md, MC_RESEARCH.md, PB_RESEARCH.md, MR_RESEARCH.md\n## New triggers (§5) — see SETUP_TRIGGER_REBUILD.md\n## Quality V2 (§6) — see QUALITY_V2.md\n## Vetoes (§7) — see OPPOSITE_SIGNAL_ANALYSIS.md (neither passed)\n\n## Frozen finalists (derived from DEV; configs/finalists.json sha256 ${R.finalists_sha256})\n${Object.entries(R.finalist_definitions.finalists).map(([k, v]) => `- **${k}**: ${v.def}${v.subsets ? ` — subsets ${v.subsets.join(', ') || 'none'}` : ''}${v.nt ? `; new triggers ${v.nt.join(', ') || 'none'}` : ''}${v.qv2a ? `; QV2A components ${R.finalist_definitions.quality_v2.keep.join(', ')} ≥ ${R.finalist_definitions.quality_v2.threshold}` : ''}`).join('\n')}\n\nSupported variant per model (DEV rule): ${JSON.stringify(R.finalist_definitions.supported_variant_per_model)}; supported new triggers: ${R.finalist_definitions.supported_new_triggers.join(', ') || 'none'}; vetoes attached: ${R.finalist_definitions.vetoes_attached.join(', ') || 'none'}.\n`);
W('FROZEN_FINALISTS.md', `# FROZEN FINALISTS\n\nFrozen 2026-09-30 21:22:00Z before HOLDOUT was opened: \`configs/finalists.json\`, sha256 **${R.finalists_sha256}** (asserted by the FULL pass). Parameters: new-trigger thresholds ${JSON.stringify(R.meta.nt_params)}; variant thresholds ${JSON.stringify(R.finalist_definitions.variant_params)}; QV2 ${JSON.stringify(R.finalist_definitions.quality_v2)}.\n\n| Finalist | Hypothesis | Definition |\n|---|---|---|\n| F1 | removing the two harmful models leaves an edge | CONTROL without BO and SR (MC + PB + MR) |\n| F2 | the best structural combination on DEV generalises | ${R.finalist_definitions.finalists.F2.structural} |\n| F3 | the DEV-supported rebuilt subsets carry positive expectancy | ${R.finalist_definitions.finalists.F3.subsets.join(' ∪ ')} |\n| F4 | adding the DEV-supported new trigger increases capture without losing expectancy | F3 ∪ ${R.finalist_definitions.finalists.F4.nt.join(', ')} |\n| F5 | a compression-expansion trigger alone has edge | ${R.finalist_definitions.finalists.F5.nt.join(', ')} |\n| F6 | a DEV-validated simplified quality gate improves F3 | F3 with QV2A ≥ ${R.finalist_definitions.quality_v2.threshold} |\n| F7 SIMPLE_A | one model subset beats the engine | ${R.finalist_definitions.finalists.F7.subsets.join(', ')} |\n| F8 SIMPLE_B | two subsets beat the engine | ${R.finalist_definitions.finalists.F8.subsets.join(', ')} (identical to F3 with two supported subsets) |\n\nNo threshold was chosen by inspecting outcomes; every value is the output of a rule written in V2_PREREGISTRATION.md before the DEV pass.\n`);
const FN = ['CONTROL', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8'];
const ftab = (S) => `| Candidate | Signals | Trades | Trades/session (median) | Zero-trade sessions | Win rate | Avg win / loss (R) | Expectancy (R) | Expectancy (USD) | 95 % CI (trade) | 99 % CI | 95 % CI (session block) | PF | Max DD (R / USD) | Loss streak | MFE / MAE (R) | Cost/trade (USD) | Cost % of gross | Top-5 share | Quarters positive |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n${FN.map((n) => { const v = R.finalists[S][n]; if (!v || !v.n) return `| ${n} | 0 | | | | | | | | | | | | | | | | | | |`; return `| ${n} | ${v.signals} | ${v.n} | ${v.trades_per_session?.median} | ${pc(v.zero_trade_session_rate)} | ${pc(v.win_rate)} | ${f(v.avg_win_r, 2)} / ${f(v.avg_loss_r, 2)} | **${f(v.expectancy_r)}** | ${f(v.expectancy_usd, 2)} | ${ci(v.ci95_r)} | ${ci(v.ci99_r)} | ${ci(v.block_ci95_r)} | ${f(v.pf, 2)} | ${f(v.max_dd_r, 1)} / ${f(v.max_dd_usd, 1)} | ${v.max_loss_streak} | ${f(v.mfe_r, 2)} / ${f(v.mae_r, 2)} | ${f(v.cost_usd, 2)} | ${pc(v.cost_pct_gross)} | ${pc(v.top5_share)} | ${pc(v.quarters_positive_share)} |`; }).join('\n')}`;
W('DEVELOPMENT_RESULTS.md', `# DEVELOPMENT RESULTS (2025-05-07 → 2025-12-31; ${R.meta.sessions_dev} sessions; EXIT_F normal costs; sequential one-position)\n\n${ftab('DEV')}\n\nModel mix per finalist (DEV): ${FN.map((n) => `${n} ${JSON.stringify(R.finalists.DEV[n]?.model_mix ?? {})}`).join('; ')}.\n`);
W('HOLDOUT_RESULTS.md', `# HOLDOUT RESULTS (2026-01-01 → 2026-09-29; ${R.meta.sessions_hold} sessions; opened once after finalists.json was frozen, sha256 ${R.finalists_sha256})\n\n${ftab('HOLD')}\n\n## Decisions (V2_PREREGISTRATION §9)\n| Finalist | Status | Failing requirements | HOLD N | Expectancy (R) | PF | Max DD (R) | Session-block 95 % CI |\n|---|---|---|---|---|---|---|---|\n${Object.entries(R.decisions.candidates).map(([k, d]) => `| ${k} | ${d.status} | ${(d.reasons ?? []).join(', ') || '—'} | ${d.hold_n ?? 0} | ${f(d.hold_expectancy_r)} | ${f(d.hold_pf, 2)} | ${f(d.hold_dd_r, 1)} | ${ci(d.block_ci95_r)} |`).join('\n')}\n\nV2_FINALIST = ${R.decisions.finalist ?? 'none'} · EDGE_DEMONSTRATED = ${R.decisions.edge_demonstrated} · V2_BEATS_V1_CONTROL = ${R.decisions.v2_beats_v1_control} · DEMO_ELIGIBLE = ${R.decisions.demo_eligible}\n\nModel mix per finalist (HOLD): ${FN.map((n) => `${n} ${JSON.stringify(R.finalists.HOLD[n]?.model_mix ?? {})}`).join('; ')}.\n`);
const costTab = (S) => `| Candidate | N | Gross expectancy (USD) | Cost (USD/trade) | Net expectancy (USD) | Net expectancy (R) | PF | Max DD (R) | Stress N / exp (R) / PF | Drift N / exp / PF |\n|---|---|---|---|---|---|---|---|---|---|\n${FN.map((n) => { const v = R.finalists[S][n]; if (!v?.n) return `| ${n} | 0 | | | | | | | | |`; return `| ${n} | ${v.n} | ${f(v.gross_expectancy_usd, 2)} | ${f(v.cost_usd, 2)} | ${f(v.expectancy_usd, 2)} | ${f(v.expectancy_r)} | ${f(v.pf, 2)} | ${f(v.max_dd_r, 1)} | ${v.stress.n} / ${f(v.stress.expectancy_r)} / ${f(v.stress.pf, 2)} | ${v.drift.n} / ${f(v.drift.expectancy_r)} / ${f(v.drift.pf, 2)} |`; }).join('\n')}`;
W('NORMAL_COST_RESULTS.md', `# NORMAL COST RESULTS (spread 0.24 + slippage 0.10 per exit; swap on BUY nights)\n${S2.map((S) => `\n## ${S}\n${costTab(S)}`).join('\n')}\n`);
W('STRESS_COST_RESULTS.md', `# STRESS COST RESULTS (spread 0.60 + slippage 0.20; DRIFT = next-open fill)\n${S2.map((S) => `\n## ${S}\n${costTab(S)}`).join('\n')}\n\nReading: on HOLDOUT only F3/F8 stay positive under stress (+0.029 R, PF 1.03) and only marginally; F1, F2, F4, F7 turn negative; the new-trigger-only and QV2 candidates are negative at normal cost already. Cost per trade is 0.34–0.40 USD, 18–24 % of gross expectancy for the positive candidates and > 50 % for CONTROL.\n`);
W('WALK_FORWARD_RESULTS.md', `# WALK-FORWARD RESULTS (calendar quarters; sequential trades; EXIT_F normal costs)\n${S2.map((S) => { const qs = Object.keys(R.finalists[S].CONTROL.walk_forward); return `\n## ${S}\n| Candidate | ${qs.join(' | ')} | Quarters positive |\n|---|${qs.map(() => '---').join('|')}|---|\n${FN.map((n) => { const w = R.finalists[S][n]?.walk_forward ?? {}; return `| ${n} | ${qs.map((q) => (w[q] ? `n ${w[q].n}, ${f(w[q].expectancy_r)} R, PF ${f(w[q].pf, 2)}, DD ${f(w[q].max_dd_r, 1)}` : '—')).join(' | ')} | ${pc(R.finalists[S][n]?.quarters_positive_share)} |`; }).join('\n')}`; }).join('\n')}\n\nReading: F3/F8 are positive in 2026Q1 and Q2 and slightly negative in Q3 (2 of 3 HOLDOUT quarters; 1 of 3 DEV quarters); no candidate is positive in every quarter; CONTROL is positive only in 2026Q2. No single quarter carries F3 (Q1 +0.20, Q2 +0.135 R).\n`);
const nb = (S) => Object.entries(R.finalists[S]).filter(([k]) => k !== 'CONTROL').map(([k, v]) => `| ${k} | ${Object.entries(v.neighbourhood ?? {}).map(([p, o]) => `${p}: ${Object.entries(o).filter(([a]) => a !== 'classification').map(([a, b]) => `${a} → ${f(b.expectancy_r)} R (n ${b.n})`).join(', ')} ⇒ **${o.classification}**`).join('<br>') || 'no numeric thresholds introduced'} |`).join('\n');
W('PARAMETER_STABILITY.md', `# PARAMETER STABILITY (every introduced numeric threshold and its neighbours; ROBUST = all neighbours positive, SENSITIVE = some neighbour ≤ 0, FRAGILE = only the centre positive, NEGATIVE_CENTRE = centre ≤ 0)\n${S2.map((S) => `\n## ${S}\n| Finalist | Threshold neighbourhoods |\n|---|---|\n${nb(S)}`).join('\n')}\n\nReading: the BO2 thresholds (range ≥ 1.0 ATR, ATR ratio ≥ 1.0) are ROBUST on HOLDOUT inside F3/F4/F8; the NT1 thresholds are ROBUST only inside F4 (where F3 carries the result) and NEGATIVE_CENTRE alone (F5); the QV2A threshold is FRAGILE (positive only at 58.5, negative at 61 and 63.5). Fragile thresholds cannot support DEMO.\n`);
W('UNCERTAINTY_ANALYSIS.md', `# UNCERTAINTY ANALYSIS (trade bootstrap 2000 draws seed 20260930; session-block bootstrap 2000 draws seed 7; month-shuffled adverse sequences 500 draws)\n${S2.map((S) => `\n## ${S}\n| Candidate | N | Expectancy (R) | 95 % trade CI | 99 % trade CI | 95 % session-block CI | 99 % session-block CI | PF | DD observed (R) | DD P50 / P90 / P99 | Loss streak observed | Loss streak P50 / P90 | Longest underwater (trades) P50 / P90 | Tail loss P99 (R) |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n${FN.map((n) => { const v = R.finalists[S][n]; if (!v?.n) return `| ${n} | 0 | | | | | | | | | | | | |`; const a = v.adverse ?? {}; return `| ${n} | ${v.n} | ${f(v.expectancy_r)} | ${ci(v.ci95_r)} | ${ci(v.ci99_r)} | ${ci(v.block_ci95_r)} | ${ci(v.block_ci99_r)} | ${f(v.pf, 2)} | ${f(v.max_dd_r, 1)} | ${f(a.dd_r_p50, 1)} / ${f(a.dd_r_p90, 1)} / ${f(a.dd_r_p99, 1)} | ${v.max_loss_streak} | ${a.loss_streak_p50} / ${a.loss_streak_p90} | ${a.longest_underwater_trades_p50} / ${a.longest_underwater_trades_p90} | ${f(a.tail_loss_r_p99, 2)} |`; }).join('\n')}`).join('\n')}\n\nLimitations: session blocks remove within-day dependence only; regimes span days, so true uncertainty is wider than the block intervals. Every HOLDOUT interval includes zero. The adverse-sequence test (ADVERSE SEQUENCE TEST §30) is the month-shuffle: for F3 a 90th-percentile drawdown of ${f(R.finalists.HOLD.F3.adverse.dd_r_p90, 1)} R with loss streaks of ${R.finalists.HOLD.F3.adverse.loss_streak_p90} and up to ${R.finalists.HOLD.F3.adverse.longest_underwater_trades_p90} trades underwater is the survivable-economics envelope a 0.01-lot account would have to absorb (≈ ${f(R.finalists.HOLD.F3.adverse.dd_r_p90 * 6.3, 0)} USD at the median 6.3 USD structural stop).\n`);
W('MOVE_CAPTURE_COMPARISON.md', `# MOVE CAPTURE COMPARISON (V1 move-event definition; capture = same-direction entry within ± 6 bars of onset; early = at or before onset, late = after)\n${S2.map((S) => `\n## ${S} (${R.finalists[S].CONTROL.move_capture.events} events)\n| Candidate | Capture | Early | Late | Wrong direction | Already positioned | No signal | Expectancy (R) | PF |\n|---|---|---|---|---|---|---|---|---|\n${FN.map((n) => { const v = R.finalists[S][n]; const m = v?.move_capture; if (!m) return `| ${n} | — | | | | | | | |`; return `| ${n} | ${pc(m.capture_rate)} | ${pc(m.early_capture_rate)} | ${pc(m.late_capture_rate)} | ${pc(m.wrong_direction_rate)} | ${pc(m.already_positioned_rate)} | ${pc(m.no_signal_rate)} | ${f(v.expectancy_r)} | ${f(v.pf, 2)} |`; }).join('\n')}`).join('\n')}\n\nReading: every V2 candidate captures fewer moves than CONTROL (they are subsets); the candidates with positive expectancy capture 10–16 % of moves and are on the wrong side of 6–9 % (vs CONTROL 27 % / 20 %). Capture is not the objective; a candidate that captured more while losing money would be rejected, and none captured more.\n`);
W('FALSE_POSITIVE_ANALYSIS.md', `# FALSE-POSITIVE ANALYSIS (entries a candidate adds beyond CONTROL's signal set; new triggers only, since all other candidates are subsets)\n${S2.map((S) => `\n## ${S}\n| Candidate | Extra entries vs CONTROL | Extra winners | Extra losers | Extra-population expectancy (R) | Extra PF | CONTROL signals removed |\n|---|---|---|---|---|---|---|\n${FN.filter((n) => n !== 'CONTROL').map((n) => { const v = R.finalists[S][n]?.false_positive; return v ? `| ${n} | ${v.extra_entries_vs_control} | ${v.extra_winners} | ${v.extra_losers} | ${f(v.extra_expectancy_r)} | ${f(v.extra_pf, 2)} | ${v.control_signals_removed} |` : `| ${n} | — | | | | | |`; }).join('\n')}`).join('\n')}\n\nReading: the only new entries (NT1 compression-expansion) are 431 on HOLDOUT with 164 winners / 267 losers, −0.054 R, PF 0.93: raw recall without economic precision. F4 (F3 + NT1) therefore earns less than F3 despite higher capture.\n`);
W('EXIT_GEOMETRY_DIAGNOSTIC.md', `# EXIT GEOMETRY DIAGNOSTIC (share of LOSING trades that first reached a favourable excursion; diagnostic only — no exit was changed in V2)\n${S2.map((S) => `\n## ${S}\n| Candidate | Losers reaching +0.25 R | +0.5 R | +0.75 R | +1 R | Wrong-direction loss share (MFE < 0.25 R) |\n|---|---|---|---|---|---|\n${FN.map((n) => { const v = R.finalists[S][n]; const l = v?.losers_reaching; return l ? `| ${n} | ${pc(l.r025)} | ${pc(l.r050)} | ${pc(l.r075)} | ${pc(l.r100)} | ${pc(v.wrong_direction_loss_share)} |` : `| ${n} | — | | | | |`; }).join('\n')}`).join('\n')}\n\nFor the future Capital Harvest evidence base: about half of all losing trades in every entry set first reached +0.5 R and roughly 30 % reached +1 R before losing. This is recorded here and was not used to alter any entry comparison.\n`);
const c0 = R.finalists.HOLD.CONTROL, best = R.finalists.HOLD.F3;
W('V1_CONTROL_VS_V2.md', `# V1 CONTROL vs V2 (HOLDOUT, identical EXIT_F and costs)\n\nV2_FINALIST = **${R.decisions.finalist ?? 'none (no candidate met the frozen requirements)'}**. The best V2 candidate, F3 (= F8), is shown for transparency; it failed only the two confidence-interval requirements.\n\n| Metric | V1 CONTROL | F3 (best V2 candidate, NOT a finalist) |\n|---|---|---|\n| Models | MC, PB, BO, SR, MR (all gates) | BO2 (BO with range ≥ 1.0 ATR and ATR ratio ≥ 1.0) ∪ PB3b (PB SELL side); all other production gates unchanged |\n| Rules changed | — | subset filters only; no new trigger, no quality change, no veto |\n| Signals | ${c0.signals} | ${best.signals} |\n| Trades (sequential) | ${c0.n} | ${best.n} |\n| Trades/session (median) | ${c0.trades_per_session.median} | ${best.trades_per_session.median} |\n| Zero-trade sessions | ${pc(c0.zero_trade_session_rate)} | ${pc(best.zero_trade_session_rate)} |\n| Move capture | ${pc(c0.move_capture.capture_rate)} | ${pc(best.move_capture.capture_rate)} |\n| Wrong-direction rate (moves) | ${pc(c0.move_capture.wrong_direction_rate)} | ${pc(best.move_capture.wrong_direction_rate)} |\n| Win rate | ${pc(c0.win_rate)} | ${pc(best.win_rate)} |\n| Avg win / loss (R) | ${f(c0.avg_win_r, 2)} / ${f(c0.avg_loss_r, 2)} | ${f(best.avg_win_r, 2)} / ${f(best.avg_loss_r, 2)} |\n| Expectancy (R) | ${f(c0.expectancy_r)} | ${f(best.expectancy_r)} |\n| Expectancy (USD, 0.01 lot) | ${f(c0.expectancy_usd, 2)} | ${f(best.expectancy_usd, 2)} |\n| PF | ${f(c0.pf, 2)} | ${f(best.pf, 2)} |\n| Max DD (R / USD) | ${f(c0.max_dd_r, 1)} / ${f(c0.max_dd_usd, 1)} | ${f(best.max_dd_r, 1)} / ${f(best.max_dd_usd, 1)} |\n| MFE / MAE (R) | ${f(c0.mfe_r, 2)} / ${f(c0.mae_r, 2)} | ${f(best.mfe_r, 2)} / ${f(best.mae_r, 2)} |\n| Cost/trade (USD) | ${f(c0.cost_usd, 2)} | ${f(best.cost_usd, 2)} |\n| Loss streak | ${c0.max_loss_streak} | ${best.max_loss_streak} |\n| 95 % CI trade / session-block | ${ci(c0.ci95_r)} / ${ci(c0.block_ci95_r)} | ${ci(best.ci95_r)} / ${ci(best.block_ci95_r)} |\n| Stress expectancy (R) | ${f(c0.stress.expectancy_r)} | ${f(best.stress.expectancy_r)} |\n| DEV expectancy (R) | ${f(R.finalists.DEV.CONTROL.expectancy_r)} | ${f(R.finalists.DEV.F3.expectancy_r)} |\n\nWhere the improvement came from: removing 78 % of CONTROL's trades — all SR, all MC, all MR, PB BUYs and the 78 % of BO signals without range/ATR expansion — removes most of the drawdown (98.9 → 23.5 R) and lifts the point expectancy from −0.064 to +0.099 R with PF 1.13, stress-positive, robust BO2 thresholds and 2 of 3 HOLDOUT quarters positive. Why it is not a finalist: on DEV the same subset earned only +0.011 R (PF 1.01), and on HOLDOUT both confidence intervals include zero ([−0.054, +0.252] trade; [−0.059, +0.251] session-block). V2_BEATS_V1_CONTROL = ${R.decisions.v2_beats_v1_control}.\n`);
console.log('tables written');
