/**
 * ENTRY CORE V4 -- invariant tests over the frozen research artefacts (research/entry_core_v4).
 * Pre-registration discipline (hashes), built-in controls (leak/null/cost/first-exit/prefix invariance), move-event definition,
 * setup/trigger detection rules on synthetic bars (compression, expansion, sweep, reclaim, structure break, confirmation, pullback,
 * continuation, momentum ignition, range acceptance, trend resumption, direction), information-time (no look-ahead), RR/risk geometry,
 * one-position semantics, finalist derivation from DEV, decision recomputation, production preservation.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
const ROOT = new URL('../research/entry_core_v4/', import.meta.url);
const R = JSON.parse(readFileSync(new URL('results/v4_results.json', ROOT), 'utf8'));
const RD = JSON.parse(readFileSync(new URL('results/v4_results_DEV_phase.json', ROOT), 'utf8'));
const DEFN = JSON.parse(readFileSync(new URL('configs/finalists.json', ROOT), 'utf8'));
const V3 = JSON.parse(readFileSync(new URL('../research/entry_edge_v3/results/v3_results.json', import.meta.url), 'utf8'));
const sha = (u) => createHash('sha256').update(readFileSync(u)).digest('hex');
const FAMS = ['A', 'B', 'C', 'D', 'E', 'F', 'G']; const S7 = ['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7']; const S2 = ['DEV', 'HOLD'];

// --- reference implementations of the frozen rules on synthetic bars (information-time: bars <= t only) ---
const bar = (o, h, l, c) => ({ open: o, high: h, low: l, close: c });
function atr14(bars, t) { let s = 0; for (let k = t - 13; k <= t; k++) s += Math.max(bars[k].high - bars[k].low, Math.abs(bars[k].high - bars[k - 1].close), Math.abs(bars[k].low - bars[k - 1].close)); return s / 14; }
function range12(bars, t) { let h = -Infinity, l = Infinity; for (let q = 0; q < 12; q++) { h = Math.max(h, bars[t - q].high); l = Math.min(l, bars[t - q].low); } return { h, l }; }
function pivotsKnownAt(bars, t) { const H = [], L = []; for (let j = 3; j + 3 <= t; j++) { let ph = true, pl = true; for (let q = 1; q <= 3; q++) { if (!(bars[j].high > bars[j - q].high) || !(bars[j].high >= bars[j + q].high)) ph = false; if (!(bars[j].low < bars[j - q].low) || !(bars[j].low <= bars[j + q].low)) pl = false; } if (ph) H.push({ idx: j, price: bars[j].high }); if (pl) L.push({ idx: j, price: bars[j].low }); } return { SH: H.at(-1) ?? null, SL: L.at(-1) ?? null }; }
function compressionExpansion(bars, t, wA = 3, xA = 1.5) { const A1 = atr14(bars, t - 1); const r = range12(bars, t - 1); if (!((r.h - r.l) / A1 <= wA)) return null; const b = bars[t]; const exp = (b.high - b.low) / A1; if (!(exp >= xA)) return null; const loc = (b.close - b.low) / (b.high - b.low); if (loc >= 0.7 && b.close > r.h) return { side: 'BUY', sl: r.l }; if (loc <= 0.3 && b.close < r.l) return { side: 'SELL', sl: r.h }; return null; }
function sweep(bars, t) { const { SH, SL } = pivotsKnownAt(bars, t - 1); const b = bars[t]; if (SH && t - SH.idx >= 6 && b.high > SH.price && b.close < SH.price) return { side: 'SELL', level: SH.price, extreme: b.high, low: b.low }; if (SL && t - SL.idx >= 6 && b.low < SL.price && b.close > SL.price) return { side: 'BUY', level: SL.price, extreme: b.low, high: b.high }; return null; }
function firstBreak(bars, t) { const { SH, SL } = pivotsKnownAt(bars, t); const c = bars[t].close, p = bars[t - 1].close; if (SH && c > SH.price && !(p > SH.price)) return { side: 'BUY', level: SH.price }; if (SL && c < SL.price && !(p < SL.price)) return { side: 'SELL', level: SL.price }; return null; }
function geometry(entry, sl, A, side, rr = 1.7) { let risk = Math.abs(entry - sl); let block = null; if (A < 2.0) block = 'ATR_FLOOR'; if (risk < 0.5 * A) { risk = 0.5 * A; sl = side === 'BUY' ? entry - risk : entry + risk; } if (risk > 3.0 * A) block = block ?? 'RISK'; return { sl, risk, tp2: side === 'BUY' ? entry + rr * risk : entry - rr * risk, block }; }
// synthetic tape: 40 flat bars (range 1.0 around 100), then an expansion bar
function flatTape(n = 40, mid = 100, half = 0.5) { const out = []; for (let k = 0; k < n; k++) { const w = half * (0.6 + 0.4 * ((k * 7) % 5) / 4); out.push(bar(mid, mid + w, mid - w, mid + (k % 2 ? 0.1 : -0.1))); } return out; }

describe('pre-registration discipline', () => {
  it('V4 pre-registration and control-baseline hashes match the frozen .sha256 files and are carried in the results', () => { const p = readFileSync(new URL('V4_PREREGISTRATION.sha256', ROOT), 'utf8').trim().split(/\s+/)[0]; const c = readFileSync(new URL('V4_CONTROL_BASELINE.sha256', ROOT), 'utf8').trim().split(/\s+/)[0]; assert.equal(sha(new URL('V4_PREREGISTRATION.md', ROOT)), p); assert.equal(sha(new URL('V4_CONTROL_BASELINE.md', ROOT)), c); assert.equal(R.meta.prereg_sha256, p); assert.equal(R.meta.control_baseline_sha256, c); assert.equal(RD.meta.prereg_sha256, p); });
  it('finalists were frozen from DEV before the FULL pass (hash matches; identical to the DEV-phase derivation)', () => { const frozen = readFileSync(new URL('configs/finalists.sha256', ROOT), 'utf8').trim().split(/\s+/)[0]; assert.equal(sha(new URL('configs/finalists.json', ROOT)), frozen); assert.equal(R.finalists_sha256, frozen); assert.equal(DEFN.derived_from, 'DEV'); assert.deepEqual(RD.finalist_definitions, DEFN); assert.deepEqual(R.finalist_definitions, DEFN); });
  it('the grid is the pre-registered family set (38 points) and the candidate set is S1..S7 plus justified combinations only', () => { assert.equal(R.meta.grid.length, 38); for (const fam of FAMS) assert.ok(R.meta.grid.some((k) => k.startsWith(fam === 'E' ? 'E1' : fam === 'G' ? 'G1' : fam)), fam); assert.deepEqual(Object.keys(DEFN.finalists), S7); for (const [k, v] of Object.entries(DEFN.combinations)) { assert.ok(['S1+S3', 'S2+S3', 'S4+S3', 'S1+S5'].includes(k)); if (!v.tested) assert.ok(!DEFN.candidates.includes(k)); } assert.deepEqual(DEFN.candidates.slice(0, 7), S7); assert.equal(R.meta.rr, 1.7); assert.deepEqual(R.meta.risk_atr, [0.5, 3]); assert.equal(R.meta.atr_floor_usd, 2); });
  it('CONTROL reproduces the V3 (= V2 = V1) CONTROL exactly on both splits, including move capture', () => { for (const S of S2) { const a = R[S].control, b = V3.finalists[S].CONTROL; assert.equal(a.n, b.n); assert.equal(a.expectancy_r, b.expectancy_r); assert.equal(a.pf, b.pf); assert.equal(a.max_dd_r, b.max_dd_r); assert.equal(a.move_capture.capture_rate, b.move_capture.capture_rate); assert.equal(a.move_capture.no_setup_or_trigger_rate, b.move_capture.no_setup_or_trigger_rate); } assert.equal(R.meta.controls.control_reproduces_v3_dev, true); assert.equal(R.meta.controls.control_reproduces_v3_hold, true); });
  it('move-event set is identical to V1-V3 (1,640 DEV / 1,842 HOLD)', () => { assert.deepEqual(R.meta.events, { DEV: 1640, HOLD: 1842 }); assert.equal(R.DEV.pre_move.events, 1640); assert.equal(R.HOLD.pre_move.events, 1842); for (const e of RD.DEV.events_sample) { assert.ok(e.end > e.k && e.time_to_move >= 1 && e.time_to_move <= 24); assert.ok(e.magnitude_atr >= 3); assert.ok(['BUY', 'SELL'].includes(e.dir)); } });
});

describe('built-in controls', () => {
  it('leak / null / cost / first-exit / prefix-invariance controls pass and are identical between phases', () => { const c = R.meta.controls; assert.ok(c.leak_mean_r > 0.3); assert.ok(Math.abs(c.null_mean_r) < 0.15); assert.equal(c.cost_test.pass, true); assert.equal(c.cost_test.diff, 0.1); assert.equal(c.first_exit_after_entry, true); assert.equal(c.prefix_invariance, true); const d = RD.meta.controls; for (const k of ['leak_mean_r', 'null_mean_r', 'first_exit_after_entry', 'prefix_invariance']) assert.deepEqual(d[k], c[k]); });
  it('DEV diagnostics are identical between the DEV phase and the FULL phase (restart determinism)', () => { assert.deepEqual(RD.DEV.grid, R.DEV.grid); assert.deepEqual(RD.DEV.pre_move, R.DEV.pre_move); for (const k of S7) { assert.equal(RD.DEV.candidates[k].n, R.DEV.candidates[k].n); assert.equal(RD.DEV.candidates[k].expectancy_r, R.DEV.candidates[k].expectancy_r); assert.deepEqual(RD.DEV.candidates[k].forensics, R.DEV.candidates[k].forensics); } });
});

describe('setup / trigger rules on synthetic bars (information-time)', () => {
  it('compression -> expansion: a 1.5 ATR directional bar closing beyond a <= 3 ATR 12-bar range triggers BUY/SELL with the range end as stop; a mid-close bar does not', () => { const tape = flatTape(); const A = atr14(tape, 39); const r = range12(tape, 39); assert.ok((r.h - r.l) / A <= 3); tape.push(bar(100, 100 + 2.2 * A, 99.9, 100 + 2.1 * A)); const up = compressionExpansion(tape, 40); assert.equal(up?.side, 'BUY'); assert.equal(up.sl, r.l); tape[40] = bar(100, 100.1, 100 - 2.2 * A, 100 - 2.1 * A); assert.equal(compressionExpansion(tape, 40)?.side, 'SELL'); tape[40] = bar(100, 100 + 1.2 * A, 100 - 1.2 * A, 100); assert.equal(compressionExpansion(tape, 40), null, 'mid close is not directional'); });
  it('expansion requires compression at t-1: a trending prior window (12-bar range >> 3 ATR) is not a setup', () => { const tape = []; for (let k = 0; k < 40; k++) tape.push(bar(100 + 2 * k, 100 + 2 * k + 0.6, 100 + 2 * k - 0.4, 100 + 2 * k + 0.4)); const A = atr14(tape, 39); const r = range12(tape, 39); assert.ok((r.h - r.l) / A > 3, 'trending window is wide relative to ATR'); tape.push(bar(178.4, 178.4 + 2 * A, 178.3, 178.4 + 1.9 * A)); assert.equal(compressionExpansion(tape, 40), null); });
  it('liquidity sweep: a bar trading beyond a confirmed swing (known at t-1, >= 6 bars old) and closing back inside is a sweep; the swing is only known 3 bars after the pivot', () => { const tape = flatTape(30); tape.push(bar(100, 103, 99.8, 100.2)); for (let k = 0; k < 8; k++) tape.push(bar(100, 100.4, 99.6, 100)); const t = tape.length; const { SH } = pivotsKnownAt(tape, t - 1); assert.equal(SH.idx, 30); assert.notEqual(pivotsKnownAt(tape, 32).SH?.idx, 30, 'pivot not yet confirmed 2 bars later'); assert.equal(pivotsKnownAt(tape, 33).SH.idx, 30, 'pivot confirmed exactly 3 bars later'); tape.push(bar(100.2, 103.4, 100, 102.5)); const s = sweep(tape, t); assert.equal(s?.side, 'SELL'); assert.equal(s.level, 103); assert.equal(s.extreme, 103.4); tape[t] = bar(100.2, 103.4, 100, 103.2); assert.equal(sweep(tape, t), null, 'a close beyond the level is a break, not a sweep'); });
  it('reclaim confirmation (B2) = first later close beyond the sweep bar opposite extreme; structure break (C1) = first close beyond the confirmed swing; the second consecutive close is confirmation (C2)', () => { const tape = flatTape(30); tape.push(bar(100, 103, 99.8, 100.2)); for (let k = 0; k < 8; k++) tape.push(bar(100, 100.4, 99.6, 100)); const t = tape.length; tape.push(bar(100.2, 103.4, 100, 102.5)); const s = sweep(tape, t); tape.push(bar(102, 102.4, 99.5, 99.7)); assert.ok(tape[t + 1].close < s.low, 'B2 confirmation close below the sweep bar low'); const tape2 = flatTape(30); tape2.push(bar(100, 103, 99.8, 100.2)); for (let k = 0; k < 8; k++) tape2.push(bar(100, 100.4, 99.6, 100)); const u = tape2.length; tape2.push(bar(100.2, 103.6, 100, 103.3)); const br = firstBreak(tape2, u); assert.equal(br?.side, 'BUY'); assert.equal(br.level, 103); tape2.push(bar(103.3, 103.9, 103.1, 103.5)); assert.equal(firstBreak(tape2, u + 1), null, 'second close beyond is confirmation, not a new first break'); assert.ok(tape2[u + 1].close > br.level); });
  it('geometry: TP = entry +/- 1.70 x risk, risk floored at 0.5 ATR, blocked above 3 ATR or below the 2 USD ATR floor', () => { const g = geometry(100, 99, 2.5, 'BUY'); assert.equal(g.risk, 1.25, 'floored to 0.5 ATR'); assert.equal(g.sl, 98.75); assert.ok(Math.abs(g.tp2 - (100 + 1.7 * 1.25)) < 1e-9); assert.equal(g.block, null); assert.equal(geometry(100, 90, 2.5, 'BUY').block, 'RISK'); assert.equal(geometry(100, 99, 1.5, 'BUY').block, 'ATR_FLOOR'); const s = geometry(100, 101.5, 2.5, 'SELL'); assert.ok(Math.abs(s.tp2 - (100 - 1.7 * 1.5)) < 1e-9); });
  it('no look-ahead: a setup/trigger decision at t is unchanged when bars after t are altered', () => { const tape = flatTape(); const A = atr14(tape, 39); tape.push(bar(100, 100 + 2.2 * A, 99.9, 100 + 2.1 * A)); const a = compressionExpansion(tape, 40); const tape2 = [...tape, bar(50, 60, 40, 45), bar(1, 2, 0, 1)]; const b = compressionExpansion(tape2, 40); assert.deepEqual(a, b); assert.deepEqual(pivotsKnownAt(tape, 39), pivotsKnownAt(tape2, 39)); });
  it('every V4 signal in the study is a pure function of bars <= t: first exit bar >= t + 1 and blocked signals never trade', () => { assert.equal(R.meta.controls.first_exit_after_entry, true); for (const S of S2) for (const k of S7) { const v = R[S].candidates[k]; assert.ok(v.diagnostics.unblocked_signals <= v.diagnostics.raw_signals, k); assert.equal(v.signals, v.diagnostics.unblocked_signals, k); assert.ok(v.n <= v.signals, k); } });
});

describe('accounting invariants', () => {
  for (const S of S2) {
    it(`${S}: forensics categories partition every move event and detection rates are consistent`, () => { for (const k of S7) { const f = R[S].candidates[k].forensics; const sum = Object.values(f.counts).reduce((a, b) => a + b, 0); assert.equal(sum, f.events, k); assert.equal(f.events, R.meta.events[S]); const m = R[S].candidates[k].move_capture; assert.ok(Math.abs(m.capture_rate - (f.rates.VALID + f.rates.LATE)) < 0.01, k); assert.equal(f.counts.SAFETY_BLOCK, 0); assert.ok(f.earliest_setup_rel_onset.median == null || (f.earliest_setup_rel_onset.median >= -12 && f.earliest_setup_rel_onset.median <= 6), k); } });
    it(`${S}: sequential walk (one position, re-entry guard): trades + skips = signals; exit mix sums to one`, () => { for (const k of ['CONTROL', ...S7]) { const v = k === 'CONTROL' ? R[S].control : R[S].candidates[k]; assert.equal(v.n + Object.values(v.skipped).reduce((a, b) => a + b, 0), v.signals, k); const s = Object.values(v.exit_mix).reduce((a, b) => a + b, 0); assert.ok(Math.abs(s - 1) < 0.01, k); } });
    it(`${S}: directional accounting (BUY + SELL = N) and false-move accounting (followed + false = signals) reconcile`, () => { for (const k of S7) { const v = R[S].candidates[k]; const sides = Object.values(v.side_mix ?? {}).reduce((a, b) => a + b, 0); assert.equal(sides, v.n, k); const fm = v.false_move; assert.equal(fm.followed + fm.false, fm.signals, k); assert.equal(Object.values(fm.labels).reduce((a, b) => a + b, 0), fm.false, k); } });
    it(`${S}: family grid points are internally consistent (blocked <= raw; sequential N <= independent N; capture <= 1)`, () => { for (const [k, g] of Object.entries(R[S].grid)) { assert.ok(g.blocked <= g.raw, k); assert.ok((g.sequential.n ?? 0) <= g.independent.n, k); assert.ok(g.capture >= 0 && g.capture <= 1, k); assert.ok(FAMS.includes(g.fam)); } });
    it(`${S}: pre-move feature research quintile shares sum to one and categorical lifts are base-consistent`, () => { for (const [k, v] of Object.entries(R[S].pre_move.numeric)) { assert.ok(Math.abs(v.base_share.reduce((a, b) => a + b, 0) - 1) < 0.01, k); assert.ok(Math.abs(v.pre_share.reduce((a, b) => a + b, 0) - 1) < 0.02, k); assert.equal(v.lift.length, 5); } for (const [k, v] of Object.entries(R[S].pre_move.categorical)) { const bs = Object.values(v).reduce((a, x) => a + x.base_share, 0); assert.ok(Math.abs(bs - 1) < 0.02, k); } });
  }
  it('regime / HTF context are diagnostics only: no candidate definition carries a regime or HTF gate (G uses the 30m regime as pre-registered context)', () => { for (const [k, f] of Object.entries(DEFN.finalists)) { assert.ok(!('regime' in f.params) && !('htf' in f.params), k); } assert.equal(DEFN.finalists.S7.family, 'G'); });
});

describe('finalist derivation reproduces the pre-registered DEV rules', () => {
  it('per family: highest DEV sequential expectancy among grid points with N >= 80, else largest-N point UNSUPPORTED; supported = exp > 0, PF > 1.05, stress > 0', () => { for (const [name, f] of Object.entries(DEFN.finalists)) { const pts = Object.entries(RD.DEV.grid).filter(([, g]) => g.fam === f.family); const elig = pts.filter(([, g]) => g.sequential.n >= 80); if (elig.length) { const best = elig.sort((a, b) => b[1].sequential.expectancy_r - a[1].sequential.expectancy_r)[0]; assert.equal(f.grid_key, best[0], name); assert.equal(f.supported, best[1].sequential.expectancy_r > 0 && best[1].sequential.pf > 1.05 && best[1].stress_expectancy_r > 0, name); } else { assert.equal(f.supported, false, name); assert.ok(f.note.includes('UNSUPPORTED')); } } });
  it('combinations are tested only when both components are DEV-supported, and kept only with incremental value', () => { for (const [k, v] of Object.entries(DEFN.combinations)) { const [a, b] = v.components; const both = DEFN.finalists[a].supported && DEFN.finalists[b].supported; assert.equal(v.tested, both, k); if (v.tested) assert.equal(DEFN.candidates.includes(k), v.kept); else assert.ok(!DEFN.candidates.includes(k)); } });
});

describe('decision rules recompute from the persisted HOLDOUT statistics', () => {
  const H = R.HOLD.candidates, ctl = R.HOLD.control;
  it('each candidate status follows the section-9 gate including the detection (14) and false-positive (15) items', () => { for (const k of DEFN.candidates) { const v = H[k]; const reasons = []; if (!(v.expectancy_r > 0)) reasons.push('(1)'); if (!(v.stress.expectancy_r > 0)) reasons.push('(2)'); if (!(v.pf > 1.10)) reasons.push('(3)'); if (!(v.expectancy_r >= ctl.expectancy_r + 0.10)) reasons.push('(4)'); if (!(v.max_dd_r <= ctl.max_dd_r)) reasons.push('(5)'); if (!(v.n >= 200)) reasons.push('(6)'); if (v.tiny_cells && !v.tiny_cells.pass) reasons.push('(7)'); if (!((v.quarters_positive_share ?? 0) >= 0.6)) reasons.push('(8)'); if (Object.values(v.neighbourhood).some((x) => x && x.classification && x.classification !== 'ROBUST')) reasons.push('(9)'); if (!(v.ci95_r?.[0] > 0)) reasons.push('(10)'); if (!(v.block_ci95_r?.[0] > 0)) reasons.push('(10)'); const ns = v.forensics.rates.NO_SETUP + v.forensics.rates.SETUP_NO_TRIGGER; const det = v.move_capture.capture_rate >= ctl.move_capture.capture_rate && ns <= ctl.move_capture.no_setup_or_trigger_rate - 0.10; if (!det) reasons.push('(14)'); if (!(v.false_move.fp_rate_24 <= ctl.false_move.fp_rate_24)) reasons.push('(15)'); if (!(R.DEV.candidates[k].expectancy_r > 0)) reasons.push('DEV'); if (!(v.drift.expectancy_r > 0)) reasons.push('drift'); const d = R.decisions.candidates[k]; assert.deepEqual(d.reasons.map((r) => (r.startsWith('(') ? r.slice(0, r.indexOf(')') + 1) : r.startsWith('DEV') ? 'DEV' : 'drift')), reasons, k); assert.equal(d.detection_met, det, k); assert.equal(d.status, reasons.length ? (reasons.every((r) => r === '(10)') ? 'PROMISING_INCONCLUSIVE (fails only the CI requirement)' : 'FAILS_GATE') : 'PASS', k); } });
  it('aggregate decisions: no pass, EDGE NO, DEMO NO, best candidate = highest HOLD expectancy with N >= 200, V4_BEATS_CONTROL per the frozen rule', () => { const D = R.decisions; assert.deepEqual(D.passing, DEFN.candidates.filter((c) => D.candidates[c].status === 'PASS')); assert.equal(D.v4_pass, D.passing.length > 0); const anyPos = DEFN.candidates.some((c) => H[c].n >= 200 && H[c].expectancy_r > 0 && !(H[c].ci95_r?.[0] > 0)); assert.equal(D.edge_demonstrated, D.passing.length ? 'YES' : anyPos ? 'INCONCLUSIVE' : 'NO'); assert.equal(D.demo_eligible, D.passing.length ? 'YES (subject to parity fixtures)' : 'NO'); if (!D.passing.length) { const best = DEFN.candidates.filter((c) => H[c].n >= 200).sort((a, b) => H[b].expectancy_r - H[a].expectancy_r)[0]; assert.equal(D.best_candidate, best); } const b = H[D.best_candidate]; const det = D.candidates[D.best_candidate].detection_met; assert.equal(D.v4_beats_control, (b.ci95_r[0] > ctl.expectancy_r && b.max_dd_r <= ctl.max_dd_r && det) ? 'YES' : b.expectancy_r > ctl.expectancy_r ? 'INCONCLUSIVE' : 'NO'); assert.equal(D.v4_pass, false); assert.equal(D.demo_eligible, 'NO'); assert.equal(D.edge_demonstrated, 'NO'); });
  it('no candidate has positive HOLDOUT expectancy with N >= 200; the only positive HOLDOUT candidate (S7) has N < 50', () => { for (const k of DEFN.candidates) { if (H[k].n >= 200) assert.ok(H[k].expectancy_r <= 0, k); } assert.ok(H.S7.n < 50 && H.S7.expectancy_r > 0); });
});

describe('production preservation', () => {
  it('the study imports only the pure re-entry guard; no executor, bridge, watcher or MT5 module; no V4 runtime module exists', () => { const src = readFileSync(new URL('scripts/v4_study.mjs', ROOT), 'utf8'); const imports = [...src.matchAll(/from '([^']+)'/g)].map((m) => m[1]).filter((p) => p.startsWith('.')); assert.deepEqual(imports, ['../../../src/engine/capitalHarvest/positionManager.js']); for (const bad of ['mt5Executor', 'mt5_bridge', 'watcher.js', 'order_send', 'startWatcher']) assert.ok(!src.includes(bad), bad); assert.throws(() => readFileSync(new URL('../src/engine/entryCoreV4.js', import.meta.url))); });
  it('frozen registry present; costs, split and RR unchanged; R economics and 0.01-lot USD reported separately', () => { const reg = JSON.parse(readFileSync(new URL('../src/engine/strategy.frozen.json', import.meta.url), 'utf8')); assert.equal(reg.strategy_fingerprint, '356e41898259af88e459c4d5287f346992ad5c308c9f7aee1ee141671f1e46ed'); assert.deepEqual(R.meta.costs, { normal: { spread: 0.24, slip: 0.1 }, stress: { spread: 0.6, slip: 0.2 } }); assert.deepEqual(R.meta.split, { dev: ['2025-05-07', '2025-12-31'], hold: ['2026-01-01', '2026-09-29'] }); for (const S of S2) for (const k of S7) { const v = R[S].candidates[k]; assert.ok(typeof v.expectancy_r === 'number' && typeof v.expectancy_usd === 'number', k); } });
});
