/**
 * INFORMATION EDGE V6 -- deterministic tests over the frozen research artefacts (research/information_edge_v6) and the context rules.
 * Market context (HTF, session, volatility, regime, momentum, range, location, liquidity, news, cross-TF, volume, shock), direction and
 * conflict rules, setup/trigger population reproduction, geometry/risk/margin reporting, no-lookahead (prefix invariance), confirmed
 * candle, spread/dedup/one-position semantics, restart determinism, decision recomputation, production preservation.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
const ROOT = new URL('../research/information_edge_v6/', import.meta.url);
const R = JSON.parse(readFileSync(new URL('results/v6_results.json', ROOT), 'utf8'));
const RD = JSON.parse(readFileSync(new URL('results/v6_results_DEV_phase.json', ROOT), 'utf8'));
const DEFN = JSON.parse(readFileSync(new URL('configs/finalists.json', ROOT), 'utf8'));
const V5 = JSON.parse(readFileSync(new URL('../research/trade_economics_v5/results/v5_results.json', import.meta.url), 'utf8'));
const V4 = JSON.parse(readFileSync(new URL('../research/entry_core_v4/results/v4_results.json', import.meta.url), 'utf8'));
const sha = (u) => createHash('sha256').update(readFileSync(u)).digest('hex');
const CANDS = ['C1 V6-HTF', 'C2 V6-AGREE', 'C3 V6-MOM', 'C4 V6-LOC', 'C5 V6-SAFETY', 'C6 V6-DIR', 'C7 V6-SIMPLE', 'C8 V6-COMPOSITE']; const S2 = ['DEV', 'HOLD'];
const FAMILIES = ['A_HTF', 'A2_HTF_TREND', 'B_SESSION', 'B2_TIME', 'C_VOL', 'C2_RANGE_STATE', 'D_REGIME', 'E_MOM', 'E2_MOM_FLAGS', 'F_RANGE_POS', 'F2_RANGE_FLAGS', 'G_LOCATION', 'H_SWEEP', 'H2_EQUAL', 'I_NEWS', 'J_XTF', 'K_VOLUME', 'L_SHOCK'];

// --- reference implementations of the frozen context rules (pure, information-time) ---
const dirOf = (s) => (s === 'BULLISH' ? 'BUY' : s === 'BEARISH' ? 'SELL' : null);
function htfState(side, m30s, h1s) { const d = [dirOf(m30s), dirOf(h1s)]; const agree = d.filter((x) => x === side).length, oppose = d.filter((x) => x && x !== side).length; return agree === 2 ? 'HTF_ALIGNED' : oppose === 2 ? 'HTF_CONFLICTING' : 'HTF_MIXED'; }
function momState(side, mom6, thr = 0.3) { const sgn = side === 'BUY' ? 1 : -1; return Math.abs(mom6) < thr ? 'FLAT' : Math.sign(mom6) === sgn ? 'SUPPORTIVE' : 'OPPOSING'; }
function location(side, entry, sl, oppSwing, atr, thr = 1.7) { const risk = Math.abs(entry - sl); const d = oppSwing == null ? null : side === 'BUY' ? oppSwing - entry : entry - oppSwing; const ratio = d == null || d > 6 * atr ? Infinity : d / risk; return ratio >= thr ? 'GOOD' : ratio >= 1.0 ? 'NEUTRAL' : 'BAD'; }
function agreement(side, dirs, thr = 2) { const n = dirs.filter((x) => x === side).length; return { n, state: n >= 4 ? 'FULL' : n >= thr ? 'PARTIAL' : 'CONFLICT' }; }
function newsState(tClose, events, win = 60) { let st = 'NORMAL'; for (const ev of events) { if (ev > tClose && ev - tClose <= win * 60) return 'PRE_NEWS'; if (ev <= tClose && tClose - ev <= win * 60) st = 'POST_NEWS'; } return st; }
function shock(bars, i, atr, atrR, spreadP99, spreadMed, thr = 3) { let big = false; for (let q = 0; q < 3; q++) if ((bars[i - q].high - bars[i - q].low) / atr >= thr) big = true; return big || (atrR != null && atrR >= 1.5) || (bars[i].spread_pts > spreadP99 && bars[i].spread_pts >= 2 * spreadMed); }
function dirEngine(side, m30s, h1s, mom, loc) { const d = [dirOf(m30s), dirOf(h1s)]; return d.some((x) => x === side) && !d.some((x) => x && x !== side) && mom !== 'OPPOSING' && loc !== 'BAD'; }
const sessionOf = (hr) => (hr >= 13 && hr < 16 ? 'OVERLAP' : [22, 7, 12].includes(hr) ? 'SESSION_OPEN' : 'OTHER');

describe('market-context rules (reference implementations)', () => {
  it('HTF structure: aligned / conflicting / mixed relative to the side; a missing 30m structure is mixed', () => { assert.equal(htfState('BUY', 'BULLISH', 'BULLISH'), 'HTF_ALIGNED'); assert.equal(htfState('BUY', 'BEARISH', 'BEARISH'), 'HTF_CONFLICTING'); assert.equal(htfState('SELL', 'BEARISH', 'BEARISH'), 'HTF_ALIGNED'); assert.equal(htfState('BUY', null, 'BULLISH'), 'HTF_MIXED'); assert.equal(htfState('BUY', 'BULLISH', 'BEARISH'), 'HTF_MIXED'); });
  it('momentum: supportive / opposing / flat by sign and the 0.3 ATR threshold (neighbours 0.2 / 0.5)', () => { assert.equal(momState('BUY', 0.5), 'SUPPORTIVE'); assert.equal(momState('BUY', -0.5), 'OPPOSING'); assert.equal(momState('BUY', 0.2), 'FLAT'); assert.equal(momState('BUY', 0.2, 0.2), 'SUPPORTIVE'); assert.equal(momState('SELL', -0.4), 'SUPPORTIVE'); assert.equal(momState('SELL', 0.4, 0.5), 'FLAT'); });
  it('structural location: opposing-swing distance / risk >= 1.7 GOOD, >= 1.0 NEUTRAL, else BAD; no swing within 6 ATR = GOOD', () => { assert.equal(location('BUY', 100, 98, 104, 2.5), 'GOOD'); assert.equal(location('BUY', 100, 98, 102.5, 2.5), 'NEUTRAL'); assert.equal(location('BUY', 100, 98, 101, 2.5), 'BAD'); assert.equal(location('BUY', 100, 98, null, 2.5), 'GOOD'); assert.equal(location('BUY', 100, 98, 120, 2.5), 'GOOD'); assert.equal(location('SELL', 100, 102, 96, 2.5), 'GOOD'); assert.equal(location('BUY', 100, 98, 103.2, 2.5, 2.0), 'NEUTRAL'); });
  it('cross-timeframe agreement: count of 5m/15m/30m/1H directions agreeing with the side; FULL 4, PARTIAL >= 2, CONFLICT otherwise', () => { assert.deepEqual(agreement('BUY', ['BUY', 'BUY', 'BUY', 'BUY']), { n: 4, state: 'FULL' }); assert.deepEqual(agreement('BUY', ['BUY', 'SELL', 'BUY', null]), { n: 2, state: 'PARTIAL' }); assert.deepEqual(agreement('BUY', ['SELL', 'SELL', 'BUY', null]), { n: 1, state: 'CONFLICT' }); assert.equal(agreement('BUY', ['SELL', 'SELL', 'BUY', null], 1).state, 'PARTIAL'); });
  it('news state uses scheduled release timestamps only: PRE within 60 min before, POST within 60 min after, else NORMAL', () => { const ev = [1_000_000]; assert.equal(newsState(1_000_000 - 1800, ev), 'PRE_NEWS'); assert.equal(newsState(1_000_000 + 1800, ev), 'POST_NEWS'); assert.equal(newsState(1_000_000 - 7200, ev), 'NORMAL'); assert.equal(newsState(1_000_000 - 7200, ev, 180), 'PRE_NEWS'); });
  it('shock: a 3 ATR bar in the last 3 bars, ATR ratio >= 1.5, or an abnormal spread (> trailing p99 AND >= 2 x median); the modal spread is never a shock', () => { const bars = Array.from({ length: 10 }, () => ({ high: 101, low: 100, spread_pts: 160 })); assert.equal(shock(bars, 9, 2.5, 1.0, 160, 160), false, 'modal spread equal to p99 is not abnormal'); bars[9].spread_pts = 400; assert.equal(shock(bars, 9, 2.5, 1.0, 160, 160), true); bars[9].spread_pts = 160; bars[8].high = 110; assert.equal(shock(bars, 9, 2.5, 1.0, 160, 160), true); bars[8].high = 101; assert.equal(shock(bars, 9, 2.5, 1.6, 160, 160), true); assert.equal(shock(bars, 9, 2.5, 1.0, 160, 160), false); });
  it('session / time windows: overlap 13-15 UTC, session opens 22 / 07 / 12 UTC', () => { assert.equal(sessionOf(14), 'OVERLAP'); assert.equal(sessionOf(7), 'SESSION_OPEN'); assert.equal(sessionOf(3), 'OTHER'); });
  it('directional bias engine: at least one HTF aligned and none opposing, momentum not opposing, location not BAD; conflict -> WAIT', () => { assert.equal(dirEngine('BUY', 'BULLISH', null, 'FLAT', 'NEUTRAL'), true); assert.equal(dirEngine('BUY', 'BULLISH', 'BEARISH', 'SUPPORTIVE', 'GOOD'), false, 'HTF conflict -> WAIT'); assert.equal(dirEngine('BUY', 'BULLISH', 'BULLISH', 'OPPOSING', 'GOOD'), false); assert.equal(dirEngine('BUY', 'BULLISH', 'BULLISH', 'SUPPORTIVE', 'BAD'), false); assert.equal(dirEngine('SELL', null, null, 'SUPPORTIVE', 'GOOD'), false, 'no HTF evidence -> WAIT'); });
});

describe('pre-registration discipline and controls', () => {
  it('pre-registration, control-baseline and finalists hashes match and are carried in the results; finalists derived from DEV only', () => { for (const [f, k] of [['V6_PREREGISTRATION', 'prereg_sha256'], ['V6_CONTROL_BASELINE', 'control_baseline_sha256']]) { const frozen = readFileSync(new URL(`${f}.sha256`, ROOT), 'utf8').trim().split(/\s+/)[0]; assert.equal(sha(new URL(`${f}.md`, ROOT)), frozen); assert.equal(R.meta[k], frozen); } const fz = readFileSync(new URL('configs/finalists.sha256', ROOT), 'utf8').trim().split(/\s+/)[0]; assert.equal(sha(new URL('configs/finalists.json', ROOT)), fz); assert.equal(R.finalists_sha256, fz); assert.equal(DEFN.derived_from, 'DEV'); assert.deepEqual(RD.finalist_definitions, DEFN); assert.equal(R.meta.news_file_sha256, sha(new URL('../validation/v5_news_edge/events_usd_official.json', import.meta.url))); });
  it('leak / null / cost / first-exit / context prefix-invariance controls pass; CONTROL reproduces V5 and V4 exactly; S3 reproduces V4', () => { const c = R.meta.controls; assert.ok(c.leak_mean_r > 0.3); assert.ok(Math.abs(c.null_mean_r) < 0.15); assert.equal(c.cost_test.pass, true); assert.equal(c.first_exit_after_entry, true); assert.equal(c.context_prefix_invariance, true); assert.equal(c.control_reproduces_v5_dev, true); assert.equal(c.control_reproduces_v5_hold, true); for (const S of S2) { const a = R[S].candidates.CONTROL.CONTROL, b = V5[S].grid.CONTROL['CTL|PROD_TP2']; assert.equal(a.n, b.n); assert.equal(a.expectancy_r, b.expectancy_r); assert.equal(a.max_dd_r, b.max_dd_r); assert.equal(a.move_capture.capture_rate, V4[S].control.move_capture.capture_rate); assert.equal(a.move_capture.wrong_direction_rate, V4[S].control.move_capture.wrong_direction_rate); const s3 = R[S].candidates.S3.CONTROL; assert.equal(s3.n, V4[S].candidates.S3.n); assert.equal(s3.expectancy_r, V4[S].candidates.S3.expectancy_r); } });
  it('restart determinism: DEV family tables, fixed-rule results and redundancy are identical between the DEV phase and the FULL phase', () => { assert.deepEqual(RD.DEV.tables, R.DEV.tables); assert.deepEqual(RD.DEV.redundancy, R.DEV.redundancy); for (const k of Object.keys(RD.DEV.fixed.CONTROL)) { assert.equal(RD.DEV.fixed.CONTROL[k].n, R.DEV.fixed.CONTROL[k].n); assert.equal(RD.DEV.fixed.CONTROL[k].expectancy_r, R.DEV.fixed.CONTROL[k].expectancy_r); } });
  it('populations, families and candidate set are the pre-registered ones; tick volume is labelled as a proxy', () => { assert.deepEqual(Object.keys(R.meta.populations), ['CONTROL', 'S3']); assert.equal(R.meta.populations.CONTROL.all, 9617); assert.deepEqual(R.meta.families, FAMILIES); assert.deepEqual(DEFN.candidates, CANDS); assert.match(R.meta.tick_volume_note, /not exchange volume/); assert.deepEqual(R.meta.params, { mom: 0.3, loc: 1.7, agree: 2, news: 60, shock: 3, atrLo: 0.25, atrHi: 0.75, sessShift: 0 }); });
});

describe('derivation and accounting invariants', () => {
  it('DEV-derived state sets follow the frozen rule (N >= 150, expectancy above base, wrong direction below base; supported = some but not all states)', () => { const T = RD.DEV.tables.CONTROL; for (const [fam, states] of Object.entries(T.families)) { const keep = Object.entries(states).filter(([, v]) => v.n >= 150 && v.expectancy_r > T.base.expectancy_r && v.wrong_direction_rate < T.base.wrong_direction_rate).map(([k]) => k); assert.deepEqual(DEFN.state_sets[fam].states, keep, fam); assert.equal(DEFN.state_sets[fam].supported, keep.length > 0 && keep.length < Object.keys(states).length, fam); } });
  it('V6-SIMPLE = the <=3 DEV-incremental fixed rules, else the single best fixed rule; incremental = N >= 200, +0.05 R and lower wrong direction', () => { const base = RD.DEV.fixed.CONTROL.CONTROL; for (const f of DEFN.fixed_rule_dev_value) { const r = RD.DEV.fixed.CONTROL[f.k]; assert.equal(f.incremental, r.n >= 200 && r.expectancy_r - base.expectancy_r >= 0.05 && r.wrong_direction_rate < base.wrong_direction_rate, f.k); } const inc = DEFN.fixed_rule_dev_value.filter((x) => x.incremental); if (inc.length) assert.deepEqual(DEFN.simple, inc.sort((a, b) => b.improvement_r - a.improvement_r).slice(0, 3).map((x) => x.k)); else { const best = DEFN.fixed_rule_dev_value.filter((x) => x.improvement_r != null).sort((a, b) => b.improvement_r - a.improvement_r)[0]; assert.deepEqual(DEFN.simple, [best.k]); } });
  for (const S of S2) {
    it(`${S}: family states partition the population; wrong-direction, bad-entry and right-direction labels are consistent`, () => { for (const pop of ['CONTROL', 'S3']) { const T = R[S].tables[pop]; for (const [fam, states] of Object.entries(T.families)) assert.equal(Object.values(states).reduce((a, v) => a + v.n, 0), T.base.n, `${pop} ${fam}`); const c = R[S].candidates[pop].CONTROL; assert.ok(c.wrong_direction_rate <= c.bad_entry_rate + 1e-9, 'wrong direction is a subset of bad entries'); assert.ok(Math.abs(c.bad_entry_rate + c.right_direction_rate + (c.open_path_unresolved ?? 0) / c.n - 1) < 0.01, `${pop} bad + right (+ unresolved) = 1`); } });
    it(`${S}: every candidate is a WAIT filter on the frozen entries (kept <= in; trades + skips = signals; capture <= control capture + blocked share accounted)`, () => { for (const pop of ['CONTROL', 'S3']) { const ctl = R[S].candidates[pop].CONTROL; for (const k of CANDS) { const v = R[S].candidates[pop][k]; assert.ok(v.signals_kept <= v.signals_in, k); assert.equal(v.signals_in, ctl.signals_in); if (!v.n) continue; assert.equal(v.n + Object.values(v.skipped).reduce((a, b) => a + b, 0), v.signals_kept - (v.signals_kept - v.n - Object.values(v.skipped).reduce((a, b) => a + b, 0)), k); assert.ok(Math.abs(v.wait_share - (1 - v.signals_kept / v.signals_in)) < 0.001, k); const m = v.move_capture; assert.ok(Math.abs(m.capture_rate + m.wrong_direction_rate + m.already_positioned_rate + m.no_signal_rate - 1) < 0.01, k); assert.ok(v.blocked_events_share >= 0 && v.blocked_events_share <= 1); } } });
  }
  it('redundancy: phi coefficients are in [-1, 1] and support rates in [0, 1]; redundant pairs are those with |phi| >= 0.5', () => { for (const S of S2) { const rd = R[S].redundancy.CONTROL; for (const v of Object.values(rd.phi)) if (v != null) assert.ok(v >= -1 && v <= 1); for (const v of Object.values(rd.support_rates)) assert.ok(v >= 0 && v <= 1); const expected = Object.entries(rd.phi).filter(([, v]) => v != null && Math.abs(v) >= 0.5).map(([k, v]) => `${k} (${v})`); assert.deepEqual(rd.redundant_pairs, expected); } });
  it('risk / margin gate reporting: 0.01 lot is infeasible below ~71 USD equity (MARGIN_SAFETY_VETO) and feasible at 100 / 1,000 / 10,000', () => { const cap = R.HOLD.candidates.CONTROL.CONTROL.capital; assert.equal(cap.lot, 0.01); assert.match(cap.by_capital['62'].feasible_001_lot, /^NO/); for (const k of ['100', '1000', '10000']) assert.equal(cap.by_capital[k].feasible_001_lot, 'YES'); assert.ok(cap.margin_usd_approx > 15 && cap.margin_usd_approx < 30); });
});

describe('decision rules recompute from the persisted HOLDOUT statistics', () => {
  const H = R.HOLD.candidates.CONTROL, D = R.DEV.candidates.CONTROL, ctl = H.CONTROL;
  it('each candidate status follows the section-9 gate', () => { for (const k of CANDS) { const c = H[k]; const d = R.decisions.candidates[k]; if (!c.n) { assert.equal(d.status, 'EMPTY'); continue; } const reasons = []; if (!(c.wrong_direction_rate < ctl.wrong_direction_rate && c.move_capture.wrong_direction_rate < ctl.move_capture.wrong_direction_rate)) reasons.push('(1)'); if (!(c.bad_entry_rate < ctl.bad_entry_rate)) reasons.push('(2)'); if (!(c.expectancy_r > 0)) reasons.push('(3)'); if (!(c.pf > 1.10)) reasons.push('(4)'); if (!(c.expectancy_r >= ctl.expectancy_r + 0.10 && c.max_dd_r <= ctl.max_dd_r)) reasons.push('(5)'); if (!(c.n >= 200)) reasons.push('(6)'); if (!((c.quarters_positive_share ?? 0) >= 0.6)) reasons.push('(7)'); if (!R.neighbourhoods[k].classification.startsWith('ROBUST')) reasons.push('(8)'); if (c.tiny_cells && !c.tiny_cells.pass) reasons.push('(9)'); if (!(c.stress.expectancy_r > 0)) reasons.push('(10)'); if (!(c.ci95_r?.[0] > 0)) reasons.push('(11)'); if (!(c.block_ci95_r?.[0] > 0)) reasons.push('(11)'); if (!(c.move_capture.capture_rate >= 0.5 * ctl.move_capture.capture_rate)) reasons.push('(12)'); if (!(D[k].expectancy_r > 0)) reasons.push('DEV'); if (!(c.drift.expectancy_r > 0)) reasons.push('drift'); assert.deepEqual(d.reasons.map((r) => (r.startsWith('(') ? r.slice(0, r.indexOf(')') + 1) : r.startsWith('DEV') ? 'DEV' : 'drift')), reasons, k); assert.equal(d.status, reasons.length ? (reasons.every((r) => r === '(11)') ? 'PROMISING_INCONCLUSIVE (fails only the CI requirement)' : 'FAILS_GATE') : 'PASS', k); } });
  it('aggregate: no pass, information incremental value NO, directional accuracy NO, EDGE NO, DEMO NO; best = highest HOLD expectancy with N >= 200', () => { const Dc = R.decisions; assert.deepEqual(Dc.passing, []); assert.equal(Dc.edge_demonstrated, 'NO'); assert.equal(Dc.demo_eligible, 'NO'); assert.deepEqual(Dc.families_with_incremental_value_both_splits, []); assert.equal(Dc.information_incremental_value, Dc.families_with_incremental_value_both_splits.length ? 'YES' : Dc.families_with_incremental_value_one_split.length ? 'INCONCLUSIVE' : 'NO'); const best = CANDS.filter((k) => H[k].n >= 200).sort((a, b) => H[b].expectancy_r - H[a].expectancy_r)[0]; assert.equal(Dc.best_candidate, best); const b = H[best]; const dir = (ctl.wrong_direction_rate - b.wrong_direction_rate >= 0.03 && ctl.move_capture.wrong_direction_rate - b.move_capture.wrong_direction_rate >= 0.03 && b.n >= 200) ? 'YES' : (ctl.wrong_direction_rate - b.wrong_direction_rate >= 0.03 || ctl.move_capture.wrong_direction_rate - b.move_capture.wrong_direction_rate >= 0.03) ? 'INCONCLUSIVE' : 'NO'; assert.equal(Dc.directional_accuracy_improved, dir); assert.equal(Dc.entry_economics_improved, b.ci95_r[0] > ctl.expectancy_r && b.expectancy_r > 0 ? 'YES' : b.expectancy_r > ctl.expectancy_r ? 'INCONCLUSIVE' : 'NO'); for (const k of CANDS) if (H[k].n >= 200) assert.ok(H[k].expectancy_r <= 0, `${k} negative on HOLD`); });
  it('incremental value per family recomputes (N >= 200, +0.05 R, lower wrong direction) and V6-COMPOSITE is empty by construction of the frozen rule', () => { for (const S of S2) { const base = R[S].fixed.CONTROL.CONTROL; for (const [k, v] of Object.entries(R.incremental[S].CONTROL)) { const f = R[S].fixed.CONTROL[k]; assert.equal(v.incremental, f.n >= 200 && f.expectancy_r - base.expectancy_r >= 0.05 && f.wrong_direction_rate < base.wrong_direction_rate, `${S} ${k}`); } } assert.equal(R.HOLD.candidates.CONTROL['C8 V6-COMPOSITE'].n, 0); assert.ok(Object.values(DEFN.state_sets).filter((v) => v.supported).length >= 10, 'many families "supported" individually, intersection empty'); });
});

describe('production preservation', () => {
  it('the study imports only the pure re-entry guard and the V5 research modules; no executor, bridge, watcher or MT5; no V6 runtime module', () => { const src = readFileSync(new URL('scripts/v6_study.mjs', ROOT), 'utf8'); for (const bad of ['mt5Executor', 'mt5_bridge', 'watcher.js', 'order_send', 'startWatcher', 'newsMonitor', 'protectionGuards']) assert.ok(!src.includes(bad), bad); const imports = [...src.matchAll(/from '([^']+)'/g)].map((m) => m[1]).filter((p) => p.includes('src/')); assert.deepEqual(imports, ['../../../src/engine/capitalHarvest/positionManager.js']); assert.throws(() => readFileSync(new URL('../src/engine/informationEdgeV6.js', import.meta.url))); });
  it('CONTROL geometry, costs, split and safety unchanged; RR 1.70 and lot 0.01 frozen; exits not optimised (control exit everywhere)', () => { const reg = JSON.parse(readFileSync(new URL('../src/engine/strategy.frozen.json', import.meta.url), 'utf8')); assert.equal(reg.strategy_fingerprint, '356e41898259af88e459c4d5287f346992ad5c308c9f7aee1ee141671f1e46ed'); assert.deepEqual(R.meta.costs, { normal: { spread: 0.24, slip: 0.1 }, stress: { spread: 0.6, slip: 0.2 } }); assert.deepEqual(R.meta.split, { dev: ['2025-05-07', '2025-12-31'], hold: ['2026-01-01', '2026-09-29'] }); assert.equal(R.HOLD.candidates.CONTROL.CONTROL.n, 1163); assert.equal(R.HOLD.candidates.CONTROL.CONTROL.expectancy_r, -0.064); });
});
