/**
 * NEW INFORMATION V7 -- deterministic tests for the cross-asset ingestion helpers (research/new_information_v7/scripts/crossAsset.mjs)
 * and invariants over the frozen research artefacts: external data ingestion, timestamp integrity (bar complete <= decision), data delay,
 * missing / stale / duplicate data, feature calculation, no-lookahead / prefix invariance, live/replay parity, direction/conflict rules,
 * frozen setup/trigger populations, risk/margin reporting, spread/news/broker protection untouched, restart determinism, decisions.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { atr14Series, alignIndex, lastCompleteIndex, relVolume, crossFeatures, dataQuality, PARITY_TOL } from '../research/new_information_v7/scripts/crossAsset.mjs';
const ROOT = new URL('../research/new_information_v7/', import.meta.url);
const R = JSON.parse(readFileSync(new URL('results/v7_results.json', ROOT), 'utf8'));
const RD = JSON.parse(readFileSync(new URL('results/v7_results_DEV_phase.json', ROOT), 'utf8'));
const DEFN = JSON.parse(readFileSync(new URL('configs/finalists.json', ROOT), 'utf8'));
const V6 = JSON.parse(readFileSync(new URL('../research/information_edge_v6/results/v6_results.json', import.meta.url), 'utf8'));
const sha = (u) => createHash('sha256').update(readFileSync(u)).digest('hex');
const CANDS = ['N1 SILVER_OPPOSE', 'N2 SILVER_CONFIRM', 'N3 DXY_WITH', 'N4 DXY_SHOCK', 'N5 USTEC_RISK', 'N6 ACTIVITY_DIVERGENCE', 'N7 MACRO_REACTION', 'N8 SPREAD_STATE']; const S2 = ['DEV', 'HOLD'];
// synthetic series: 5m bars at 300 s and 15m bars at 900 s on the same clock
const mk5 = (n, start = 1_000_000, c0 = 50) => Array.from({ length: n }, (_, k) => { const c = c0 + 0.1 * k; return { time: start + 300 * k, open: c - 0.05, high: c + 0.2, low: c - 0.2, close: c, volume: 100 + (k % 7) * 10, spread_pts: 30 }; });
const mk15 = (n, start = 1_000_000, c0 = 100) => Array.from({ length: n }, (_, k) => { const c = c0 + 0.5 * k; return { time: start + 900 * k, open: c - 0.1, high: c + 0.6, low: c - 0.6, close: c, volume: 300, spread_pts: 60 }; });
const build = (xag5, dxy5, dxy15, ust15) => { const series = { XAG5: xag5, XAG15: mk15(60), DXY5: dxy5, DXY15: dxy15, UST15: ust15 }; return { series, align: { XAG5: alignIndex(series.XAG5, 300), XAG15: alignIndex(series.XAG15, 900), DXY5: alignIndex(series.DXY5, 300), DXY15: alignIndex(series.DXY15, 900), UST15: alignIndex(series.UST15, 900) }, atr: Object.fromEntries(Object.entries(series).map(([k, s]) => [k, atr14Series(s)])) }; };

describe('external data ingestion and timestamp integrity', () => {
  it('a bar is usable only once complete: open + tf <= decision time (5m same-open bar; 15m bar opened >= 15 min earlier)', () => { const a5 = alignIndex(mk5(100), 300), a15 = alignIndex(mk15(100), 900); const tClose = 1_000_000 + 300 * 50 + 300; assert.equal(a5.times[lastCompleteIndex(a5, tClose)], 1_000_000 + 300 * 50, 'the 5m bar with the same open time is complete at the decision'); assert.equal(lastCompleteIndex(a5, tClose - 1), 49, 'one second before its close it is not usable'); const i15 = lastCompleteIndex(a15, tClose); assert.ok(a15.times[i15] + 900 <= tClose && a15.times[i15 + 1] + 900 > tClose); });
  it('stale data: when the latest complete bar is older than the allowed staleness the index is -1 (feature NA, pass-through)', () => { const a5 = alignIndex(mk5(100), 300); const far = 1_000_000 + 300 * 200; assert.equal(lastCompleteIndex(a5, far, 600), -1); assert.equal(lastCompleteIndex(a5, far), 99, 'without a staleness bound the last bar would be returned'); });
  it('missing cross-asset bars make the feature NA, never a substituted value', () => { const B = build(mk5(5), mk5(5), mk15(5), mk15(5)); const f = crossFeatures({ tClose: 1_000_000 + 300 * 5, ...B }); assert.equal(f.silver_mom6, null); assert.equal(f.dxy_mom6, null); assert.equal(f.ustec_mom2, null); });
  it('duplicate / non-monotonic / bad-geometry bars are detected by the quality report and fail it', () => { const good = mk5(100); const q = dataQuality(good, 300, good[0].time, good.at(-1).time); assert.equal(q.pass, true); assert.equal(q.duplicates, 0); const dup = [...good, { ...good[50] }].sort((a, b) => a.time - b.time); assert.equal(dataQuality(dup, 300, 0, 1e12).duplicates, 1); assert.equal(dataQuality(dup, 300, 0, 1e12).pass, false); const bad = good.map((b) => ({ ...b })); bad[10].high = bad[10].low - 1; assert.equal(dataQuality(bad, 300, 0, 1e12).bad_geometry, 1); const nm = good.map((b) => ({ ...b })); nm[20].time = nm[19].time - 300; assert.ok(dataQuality(nm, 300, 0, 1e12).non_monotonic >= 1); });
  it('feature calculation: silver momentum = 6-bar close change / ATR14 on the same-open 5m bar; DXY falls back to the last complete 15m bar; USTEC uses 15m', () => { const xag = mk5(100), dxy5 = mk5(100, 1_000_000, 100), dxy15 = mk15(100, 1_000_000 - 900 * 60), ust = mk15(100, 1_000_000 - 900 * 60, 20000); const B = build(xag, dxy5, dxy15, ust); const tClose = 1_000_000 + 300 * 60 + 300; const f = crossFeatures({ tClose, ...B }); const i = 60; const expMom = (xag[i].close - xag[i - 6].close) / B.atr.XAG5[i]; assert.ok(Math.abs(f.silver_mom6 - expMom) < 0.002); assert.equal(f.xag5_bar_close, tClose); assert.equal(f.dxy_source, '5m'); const B2 = build(xag, mk5(5), dxy15, ust); const f2 = crossFeatures({ tClose, ...B2 }); assert.equal(f2.dxy_source, '15m'); assert.ok(f2.dxy_bar_close <= tClose); assert.ok(f.ustec_bar_close <= tClose && f.ustec_bar_close > tClose - 1800); assert.ok(Math.abs(f.silver_act - relVolume(xag, 60)) < 0.001, 'silver activity is the rounded relative tick volume'); });
  it('no look-ahead / prefix invariance: features at tClose are identical when every later bar is removed or corrupted', () => { const xag = mk5(100), dxy5 = mk5(100, 1_000_000, 100), dxy15 = mk15(100, 1_000_000 - 900 * 60), ust = mk15(100, 1_000_000 - 900 * 60, 20000); const tClose = 1_000_000 + 300 * 60 + 300; const a = crossFeatures({ tClose, ...build(xag, dxy5, dxy15, ust) }); const cut = (s, tf) => s.filter((b) => b.time + tf <= tClose); const b = crossFeatures({ tClose, ...build(cut(xag, 300), cut(dxy5, 300), cut(dxy15, 900), cut(ust, 900)) }); assert.deepEqual(a, b); const corrupt = (s, tf) => s.map((x) => (x.time + tf > tClose ? { ...x, high: x.high + 50, low: x.low - 50, close: x.close + 25, volume: x.volume * 5 } : x)); const c = crossFeatures({ tClose, ...build(corrupt(xag, 300), corrupt(dxy5, 300), corrupt(dxy15, 900), corrupt(ust, 900)) }); assert.deepEqual(a, c); assert.equal(R.meta.controls.cross_prefix_invariance, true); assert.equal(R.meta.controls.timestamp_rule_no_future_bar, true); });
  it('data delay: a one-bar feed lag is a pre-registered sensitivity test on every finalist, and its result is recorded', () => { for (const k of DEFN.candidates) { const d = R.delay[k]; assert.ok(d && typeof d.pass === 'boolean', k); if (k !== 'N9 COMBINATION') assert.ok(typeof d.delta === 'number' || d.delta === null); } assert.equal(R.delay['N2 SILVER_CONFIRM'].sign_flip, true, 'the silver confirmation sign flips with one bar of lag (reported fragility)'); });
});

describe('live / replay parity (shadow observer records vs the historical files)', () => { it('silver, DXY and USTEC 15m close, return and 96-bar z-score recomputed from the files match the live-recorded values (>= 95 %)', () => { const p = R.meta.parity; assert.equal(p.available, true); assert.ok(p.records >= 500); for (const sym of ['XAGUSDm', 'DXYm', 'USTECm']) { const s = p.by_symbol[sym]; assert.ok(s.comparable >= 50, sym); assert.ok(s.close_match_rate >= 0.95 && s.ret_match_rate >= 0.95 && s.z_match_rate >= 0.95, sym); assert.equal(s.pass, true); } assert.equal(p.pass, true); assert.deepEqual(p.tolerance, PARITY_TOL); }); });

describe('pre-registration discipline and controls', () => {
  it('pre-registration, control-baseline, finalists and series hashes match and are carried in the results; finalists derived from DEV only', () => { for (const [f, k] of [['V7_PREREGISTRATION', 'prereg_sha256'], ['V7_CONTROL_BASELINE', 'control_baseline_sha256']]) { const frozen = readFileSync(new URL(`${f}.sha256`, ROOT), 'utf8').trim().split(/\s+/)[0]; assert.equal(sha(new URL(`${f}.md`, ROOT)), frozen); assert.equal(R.meta[k], frozen); } const fz = readFileSync(new URL('configs/finalists.sha256', ROOT), 'utf8').trim().split(/\s+/)[0]; assert.equal(sha(new URL('configs/finalists.json', ROOT)), fz); assert.equal(R.finalists_sha256, fz); assert.equal(DEFN.derived_from, 'DEV'); assert.deepEqual(RD.finalist_definitions, DEFN); for (const [sym, f] of [['XAGUSDm', 'XAGUSDm_bars.json'], ['DXYm', 'DXYm_bars.json'], ['USTECm', 'USTECm_bars.json']]) assert.equal(R.meta.series_hashes[sym], sha(new URL(`../handoff/edge_discovery_lab/data/${f}`, import.meta.url))); });
  it('leak / null / cost / first-exit controls pass; CONTROL reproduces V6 exactly incl. wrong-direction and capture; S3 reproduces V6', () => { const c = R.meta.controls; assert.ok(c.leak_mean_r > 0.3); assert.ok(Math.abs(c.null_mean_r) < 0.15); assert.equal(c.cost_test.pass, true); assert.equal(c.first_exit_after_entry, true); assert.equal(c.control_reproduces_v6_dev, true); assert.equal(c.control_reproduces_v6_hold, true); for (const S of S2) { const a = R[S].candidates.CONTROL.CONTROL, b = V6[S].candidates.CONTROL.CONTROL; assert.equal(a.n, b.n); assert.equal(a.expectancy_r, b.expectancy_r); assert.equal(a.wrong_direction_rate, b.wrong_direction_rate); assert.equal(a.move_capture.capture_rate, b.move_capture.capture_rate); const s3 = R[S].candidates.S3.CONTROL; assert.equal(s3.n, V6[S].candidates.S3.CONTROL.n); } });
  it('restart determinism: DEV state tables, grids and redundancy are identical between the DEV phase and the FULL phase', () => { assert.deepEqual(RD.DEV.tables, R.DEV.tables); for (const k of Object.keys(RD.DEV.grid.CONTROL)) { assert.equal(RD.DEV.grid.CONTROL[k].n, R.DEV.grid.CONTROL[k].n); assert.equal(RD.DEV.grid.CONTROL[k].expectancy_r, R.DEV.grid.CONTROL[k].expectancy_r); } assert.deepEqual(RD.DEV.redundancy, R.DEV.redundancy); });
  it('data quality PASS for every series; NA share per candidate <= 5 %; sources and grids are the pre-registered ones', () => { for (const [k, q] of Object.entries(R.meta.data_quality)) assert.equal(q.pass, true, k); for (const k of CANDS) assert.ok(R.meta.na_rates[k] <= 0.05, k); assert.deepEqual(Object.keys(R.meta.candidates), CANDS); assert.deepEqual(R.meta.grids.silver_conf, [0.3, 0.5, 0.75]); assert.deepEqual(R.meta.grids.dxy_with, [0.5, 0.75, 1.0]); assert.equal(R.decisions.data_quality, 'PASS'); });
});

describe('derivation, direction and accounting invariants', () => {
  it('per candidate the DEV-selected grid value is the highest DEV expectancy with N >= 200 (ties -> middle); combination only when >= 2 sources have DEV incremental value', () => { const base = RD.DEV.grid.CONTROL.CONTROL; for (const k of CANDS) { const f = DEFN.finalists[k]; const grid = RD.meta.grids[f.param]; const pts = grid.map((v) => ({ v, r: RD.DEV.grid.CONTROL[`${k}|${v}`] })); const elig = pts.filter((x) => x.r.n >= 200); const best = (elig.length ? elig : pts).sort((a, b) => (b.r.expectancy_r ?? -9) - (a.r.expectancy_r ?? -9) || Math.abs(grid.indexOf(a.v) - 1) - Math.abs(grid.indexOf(b.v) - 1))[0]; assert.equal(f.value, best.v, k); assert.equal(f.dev_incremental, best.r.n >= 200 && best.r.expectancy_r - base.expectancy_r >= 0.05 && best.r.wrong_direction_rate < base.wrong_direction_rate, k); } const inc = CANDS.filter((k) => DEFN.finalists[k].dev_incremental); assert.deepEqual(DEFN.combination.components, inc.length >= 2 ? inc.slice(0, 3) : []); assert.ok(DEFN.combination.components.length <= 3); });
  for (const S of S2) {
    it(`${S}: every candidate is a WAIT filter on frozen entries (kept <= in; trades + skips = kept; capture partition; NA pass-through)`, () => { for (const pop of ['CONTROL', 'S3']) { const ctl = R[S].candidates[pop].CONTROL; for (const k of DEFN.candidates) { const v = R[S].candidates[pop][k]; assert.equal(v.signals_in, ctl.signals_in, k); assert.ok(v.signals_kept <= v.signals_in, k); if (!v.n) continue; assert.equal(v.n + Object.values(v.skipped).reduce((a, b) => a + b, 0), v.signals_kept - (v.signals_kept - v.n - Object.values(v.skipped).reduce((a, b) => a + b, 0))); const m = v.move_capture; assert.ok(Math.abs(m.capture_rate + m.wrong_direction_rate + m.already_positioned_rate + m.no_signal_rate - 1) < 0.01, k); assert.ok(v.na_share >= 0 && v.na_share <= 1); } } });
    it(`${S}: state tables partition the population and the silver direction convention is mirrored (agree/oppose relative to the side)`, () => { for (const pop of ['CONTROL', 'S3']) { const T = R[S].tables[pop]; for (const [k, st] of Object.entries(T.states)) assert.equal(Object.values(st).reduce((a, v) => a + v.n, 0), T.base.n, `${pop} ${k}`); } const st = R[S].tables.CONTROL.states.silver_mom6; assert.ok(['AGREES_STRONG', 'AGREES', 'FLAT', 'OPPOSES', 'OPPOSES_STRONG'].every((s) => s in st)); });
  }
  it('redundancy: phi of each new WAIT flag with the V6 flags is reported and bounded; the silver flags are not redundant with HTF / momentum / regime (|phi| < 0.5)', () => { for (const S of S2) { const rd = R[S].redundancy; for (const v of Object.values(rd.phi)) if (v != null) assert.ok(v >= -1 && v <= 1); for (const k of ['N1 SILVER_OPPOSE', 'N2 SILVER_CONFIRM']) for (const v6 of ['htf_aligned', 'mom_supportive', 'regime_trend_with']) assert.ok(Math.abs(rd.phi[`${k}~${v6}`] ?? 0) < 0.5, `${S} ${k} ${v6}`); } });
  it('risk / margin reporting: 0.01 lot infeasible below ~71 USD and feasible at 100 / 1,000 / 10,000; RR 1.70 and control exit unchanged', () => { const cap = R.HOLD.candidates.CONTROL.CONTROL.capital; assert.match(cap.by_capital['62'].feasible_001_lot, /^NO/); for (const k of ['100', '1000', '10000']) assert.equal(cap.by_capital[k].feasible_001_lot, 'YES'); assert.equal(R.HOLD.candidates.CONTROL.CONTROL.n, 1163); assert.equal(R.HOLD.candidates.CONTROL.CONTROL.expectancy_r, -0.064); });
});

describe('decision rules recompute from the persisted HOLDOUT statistics', () => {
  const H = R.HOLD.candidates.CONTROL, D = R.DEV.candidates.CONTROL, ctl = H.CONTROL;
  it('each candidate status follows the section-8 gate', () => { for (const k of DEFN.candidates) { const c = H[k]; const d = R.decisions.candidates[k]; if (!c.n) { assert.equal(d.status, 'EMPTY'); continue; } const reasons = []; const src = k === 'N9 COMBINATION' ? '' : R.meta.candidates[k].source; const Q = R.meta.data_quality, P = R.meta.parity.by_symbol; const q = src.startsWith('XAGUSDm') ? Q.XAG5.pass : src.startsWith('DXYm') ? Q.DXY5.pass && Q.DXY15.pass : src.startsWith('USTECm') ? Q.UST15.pass : true; const par = src.startsWith('XAGUSDm') ? P.XAGUSDm.pass : src.startsWith('DXYm') ? P.DXYm.pass : src.startsWith('USTECm') ? P.USTECm.pass : true; if (!q || (R.meta.na_rates[k] ?? 0) > 0.05) reasons.push('(1)'); if (!R.delay[k].pass) reasons.push('(2)'); if (!(c.wrong_direction_rate < ctl.wrong_direction_rate && c.move_capture.wrong_direction_rate < ctl.move_capture.wrong_direction_rate)) reasons.push('(3)'); if (!(c.bad_entry_rate < ctl.bad_entry_rate)) reasons.push('(4)'); if (!(c.expectancy_r > 0)) reasons.push('(5)'); if (!(c.pf > 1.10)) reasons.push('(6)'); if (!(c.expectancy_r >= ctl.expectancy_r + 0.10 && c.max_dd_r <= ctl.max_dd_r)) reasons.push('(7)'); if (!(c.n >= 200)) reasons.push('(8)'); if (!((c.quarters_positive_share ?? 0) >= 0.6)) reasons.push('(9)'); if (!R.neighbourhoods[k].classification.startsWith('ROBUST')) reasons.push('(10)'); if (!(c.stress.expectancy_r > 0)) reasons.push('(11)'); if (!(c.ci95_r?.[0] > 0)) reasons.push('(12)'); if (!(c.block_ci95_r?.[0] > 0)) reasons.push('(12)'); if (!(c.move_capture.capture_rate >= 0.5 * ctl.move_capture.capture_rate)) reasons.push('(13)'); if (!par) reasons.push('(14)'); if (c.tiny_cells && !c.tiny_cells.pass) reasons.push('tiny'); if (!(D[k].expectancy_r > 0)) reasons.push('DEV'); if (!(c.drift.expectancy_r > 0)) reasons.push('drift'); assert.deepEqual(d.reasons.map((r) => (r.startsWith('(') ? r.slice(0, r.indexOf(')') + 1) : r.startsWith('DEV') ? 'DEV' : r.startsWith('tiny') ? 'tiny' : 'drift')), reasons, k); assert.equal(d.status, reasons.length ? (reasons.every((r) => r === '(12)') ? 'PROMISING_INCONCLUSIVE (fails only the CI requirement)' : 'FAILS_GATE') : 'PASS', k); } });
  it('aggregate: no pass; silver confirmation has incremental value on both splits (INFORMATION YES) but EDGE INCONCLUSIVE and DEMO NO; verdicts recompute', () => { const Dc = R.decisions; assert.deepEqual(Dc.passing, []); assert.equal(Dc.demo_eligible, 'NO'); const incBoth = DEFN.candidates.filter((k) => R.incremental.HOLD.CONTROL[k].incremental && R.incremental.DEV.CONTROL[k].incremental); assert.deepEqual(Dc.families_with_incremental_value_both_splits, incBoth); assert.equal(Dc.information_incremental_value, incBoth.length ? 'YES' : Dc.families_with_incremental_value_one_split.length ? 'INCONCLUSIVE' : 'NO'); assert.ok(incBoth.includes('N2 SILVER_CONFIRM')); const best = DEFN.candidates.filter((k) => H[k].n >= 200).sort((a, b) => H[b].expectancy_r - H[a].expectancy_r)[0]; assert.equal(Dc.best_candidate, best); const b = H[best]; const anyInc = Object.values(Dc.candidates).some((d) => d.hold_n >= 200 && d.hold_expectancy_r > 0 && d.wrong_direction_rate < ctl.wrong_direction_rate && !(d.ci95_r?.[0] > 0)); assert.equal(Dc.edge_demonstrated, anyInc ? 'INCONCLUSIVE' : 'NO'); assert.equal(Dc.trade_economics_improved, b.ci95_r[0] > ctl.expectancy_r && b.expectancy_r > 0 ? 'YES' : b.expectancy_r > ctl.expectancy_r ? 'INCONCLUSIVE' : 'NO'); assert.equal(Dc.live_replay_parity, R.meta.parity.pass ? 'PASS' : 'FAIL'); assert.equal(Dc.timestamp_integrity, R.meta.controls.cross_prefix_invariance && R.meta.controls.timestamp_rule_no_future_bar && Object.values(R.delay).every((d) => d.pass) ? 'PASS' : 'FAIL'); });
  it('ablation: removing the new source returns the CONTROL numbers exactly', () => { const a = R.ablation; assert.equal(a.HOLD.without_source.n, ctl.n); assert.equal(a.HOLD.without_source.expectancy_r, ctl.expectancy_r); assert.ok(Math.abs(a.HOLD.delta_expectancy - (H[a.best].expectancy_r - ctl.expectancy_r)) < 1e-9); assert.equal(a.DEV.without_source.expectancy_r, D.CONTROL.expectancy_r); });
});

describe('production preservation', () => {
  it('the study imports only the pure re-entry guard and research modules; no executor, bridge, watcher, news monitor, MT5 or shadow writer; no V7 runtime module', () => { for (const f of ['scripts/v7_study.mjs', 'scripts/crossAsset.mjs']) { const src = readFileSync(new URL(f, ROOT), 'utf8'); for (const bad of ['mt5Executor', 'mt5_bridge', 'watcher.js', 'order_send', 'startWatcher', 'newsMonitor', 'protectionGuards', 'shadow/observer', 'shadow/store', 'copy_rates']) assert.ok(!src.includes(bad), `${f} ${bad}`); } const imports = [...readFileSync(new URL('scripts/v7_study.mjs', ROOT), 'utf8').matchAll(/from '([^']+)'/g)].map((m) => m[1]).filter((p) => p.includes('src/')); assert.deepEqual(imports, ['../../../src/engine/capitalHarvest/positionManager.js']); assert.throws(() => readFileSync(new URL('../src/engine/newInformationV7.js', import.meta.url))); });
  it('CONTROL geometry, costs, split and safety unchanged; the shadow observer records were read, never written', () => { const reg = JSON.parse(readFileSync(new URL('../src/engine/strategy.frozen.json', import.meta.url), 'utf8')); assert.equal(reg.strategy_fingerprint, '356e41898259af88e459c4d5287f346992ad5c308c9f7aee1ee141671f1e46ed'); assert.deepEqual(R.meta.costs, { normal: { spread: 0.24, slip: 0.1 }, stress: { spread: 0.6, slip: 0.2 } }); assert.deepEqual(R.meta.split, { dev: ['2025-05-07', '2025-12-31'], hold: ['2026-01-01', '2026-09-29'] }); assert.ok(R.meta.parity.records > 0); });
});
