/**
 * SILVER N2 + DOM FORWARD OBSERVATION (2026-10-01) -- deterministic tests. MEASURE ONLY.
 * Covers: frozen registry (SC3/SC4 added, SC1/SC2 unchanged), silver N2 classification (same-bar / one-bar-lag, mirrored sides,
 * stale / missing -> NA), anti-lookahead (only bars complete at the decision), hypothetical geometry (1.70R), hypothetical
 * EXIT_F outcome labelling (reach, MFE/MAE, wrong-direction, normal vs stress costs, labelled HYPOTHETICAL_NOT_EXECUTED,
 * never before resolution), DOM snapshot parsing (unavailable -> recorded, never fabricated), report gate (300, not win rate),
 * no execution path (reader protocol, imports, no order-like calls), and an observer cycle with a fake reader.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CANDIDATES, candidateById, verifyFrozenRegistry, registryHashes } from '../src/shadow/candidates.js';
import { silverN2Snapshot, hypotheticalGeometry, domSnapshot, buildSilverN2Observation, labelHypothetical, SILVER_N2, HYP_LABEL, HYP_MILESTONES } from '../src/shadow/core.js';
import { validateObservation, validateOutcome } from '../src/shadow/schema.js';
import { createShadowObserver, OUTCOME_PLAN } from '../src/shadow/observer.js';
import { READER_COMMANDS } from '../src/shadow/mt5Reader.js';
import { evaluateSilver, evaluateDom, renderReports, SILVER_GATE } from '../src/shadow/silverReport.js';
import { createProductionReader } from '../src/shadow/production.js';
const ROOT = fileURLToPath(new URL('../', import.meta.url));
const T0 = 1_800_000_000 - (1_800_000_000 % 300); // aligned 5m
const mkSilver = (n, c0 = 60, step = 0) => Array.from({ length: n }, (_, k) => { const c = c0 + step * k; return { time: T0 + 300 * k, open: c, high: c + 0.05, low: c - 0.05, close: c, volume: 100 }; });
const mkGold = (closes, start) => closes.map((c, k) => ({ time: start + 300 * k, open: c, high: c + 0.3, low: c - 0.3, close: c, volume: 500 }));

describe('frozen registry', () => {
  it('SC3_SILVER_N2_v1 and SC4_DOM_SNAPSHOT_v1 are frozen MEASURE_ONLY candidates with execution authority NONE; SC1 / SC2 hashes unchanged', () => { const v = verifyFrozenRegistry(); assert.deepEqual(v.ids, ['SC1_SILVER_LEAD_v1', 'SC2_PRODUCTION_SIGNAL_v1', 'SC3_SILVER_N2_v1', 'SC4_DOM_SNAPSHOT_v1']); const h = registryHashes(); assert.equal(h.SC1_SILVER_LEAD_v1, 'e5216ec3501a0b8bc019185bfa33083a35a586ed4282e1f8f1cb2ef1530a05c0'); assert.equal(h.SC2_PRODUCTION_SIGNAL_v1, '4414f8142ebe64425fccfdb60182bd79442de2b0652ecfc76668a6ebc6486afd'); const c3 = candidateById('SC3_SILVER_N2_v1'), c4 = candidateById('SC4_DOM_SNAPSHOT_v1'); assert.equal(c3.status, 'MEASURE_ONLY'); assert.equal(c3.execution_authority, 'NONE'); assert.equal(c3.minimum_forward_sample, 300); assert.equal(c3.rule.threshold_atr, 0.75); assert.equal(c3.hypothetical_geometry.label, HYP_LABEL); assert.equal(c4.status, 'DOM_MEASURE_ONLY'); assert.equal(c4.execution_authority, 'NONE'); assert.match(c4.data_source, /FORWARD_ONLY_DATA = true/); assert.ok(Object.isFrozen(CANDIDATES)); });
});

describe('silver N2 classification (information-time)', () => {
  it('uses the XAGUSDm bar with the SAME open time as the signal bar; CONFIRMED / CONFLICT / NEUTRAL mirror the side at +/- 0.75 silver ATR', () => { const s = mkSilver(60, 60, 0); const i = 50; for (let k = i - 5; k <= i; k++) s[k].close = s[k].open = 60 + 0.02 * (k - (i - 6)); // rising 0.12 over 6 bars; ATR ~ 0.1 -> mom6 ~ +1.2 ATR
    const dec = s[i].time + 300; const b = silverN2Snapshot(s, dec, 'BUY'); assert.equal(b.available, true); assert.equal(b.timing, 'SAME_BAR'); assert.equal(b.same_open_as_signal, true); assert.equal(b.bar_time, s[i].time); assert.equal(b.bar_close_time, dec); assert.ok(b.mom6_atr > 0.75); assert.equal(b.state, 'CONFIRMED'); assert.equal(b.silver_direction, 'UP'); const sell = silverN2Snapshot(s, dec, 'SELL'); assert.equal(sell.state, 'CONFLICT'); assert.equal(sell.signed_mom6_atr, -b.signed_mom6_atr); const flat = silverN2Snapshot(mkSilver(60), dec, 'BUY'); assert.equal(flat.state, 'NEUTRAL'); });
  it('one-bar-lag uses the previous completed bar; forming / future silver bars are never used; stale or missing silver -> NA, never substituted', () => { const s = mkSilver(60); const i = 50; const dec = s[i].time + 300; const lag = silverN2Snapshot(s, dec, 'BUY', { lag: 1 }); assert.equal(lag.timing, 'LAG_1'); assert.equal(lag.bar_time, s[i - 1].time); assert.equal(lag.same_open_as_signal, false); const withFuture = s.map((b, k) => (k > i ? { ...b, close: 999, high: 999 } : b)); const a = silverN2Snapshot(withFuture, dec, 'BUY'); const b = silverN2Snapshot(s.slice(0, i + 1), dec, 'BUY'); assert.deepEqual(a, b, 'bars after the decision cannot change the snapshot'); const stale = silverN2Snapshot(s.slice(0, i - 5), dec, 'BUY'); assert.equal(stale.available, false); assert.equal(stale.reason, 'STALE'); assert.equal(stale.state, 'NA'); const none = silverN2Snapshot([], dec, 'BUY'); assert.equal(none.state, 'NA'); assert.equal(none.reason, 'NO_COMPLETED_BAR'); assert.equal(SILVER_N2.stale_sec, 600); });
});

describe('hypothetical geometry and outcome (HYPOTHETICAL_NOT_EXECUTED)', () => {
  const sig = { signal_id: 'abc', side: 'BUY', entry: 100, stop_loss: 98, tp1: 102, tp2: 106, rr: 3, model: 'BO', quality: 80, signal_bar_time: T0 + 300 * 60, created_at: new Date((T0 + 300 * 61 + 30) * 1000).toISOString() };
  it('1.70R target from the production entry and structural stop; production tp2 recorded, not used', () => { const g = hypotheticalGeometry(sig); assert.equal(g.label, HYP_LABEL); assert.equal(g.risk_usd, 2); assert.equal(g.target_170r, 103.4); assert.equal(g.production_tp2, 106); assert.equal(hypotheticalGeometry({ side: 'BUY', entry: 100, stop_loss: 100 }), null); const s = hypotheticalGeometry({ side: 'SELL', entry: 100, stop_loss: 102 }); assert.equal(s.target_170r, 96.6); });
  it('labels only after the open path resolved; target reach, MFE/MAE, exit_R normal vs stress, duration; never executed', () => { const c3 = candidateById('SC3_SILVER_N2_v1'); const start = sig.signal_bar_time + 300; const o = buildSilverN2Observation({ candidate: c3, nowSec: start + 100, signal: sig, provenance: 'TEST', silver5: mkSilver(80).map((b) => ({ ...b, time: b.time + 300 * 20 })), bars5: mkGold([100], sig.signal_bar_time) }); assert.equal(validateObservation(o).ok, true, JSON.stringify(validateObservation(o).errors)); assert.equal(o.execution_authority, 'NONE'); assert.equal(o.measure_only, true);
    const rising = mkGold([100.5, 101.2, 102.0, 102.9, 103.6, 104.5, 105.0], start); let r = labelHypothetical({ observation: o, bars5: rising, nowSec: start + 300 * 7, provenance: 'TEST' }); assert.equal(r, null, 'open path not resolved (no stop, horizon not elapsed) -> no label yet');
    const falling = [...rising, ...mkGold([103, 101, 99.5, 97.5, 97.4], start + 300 * 7)]; r = labelHypothetical({ observation: o, bars5: falling, nowSec: start + 300 * 12, provenance: 'TEST' }); assert.ok(r); assert.equal(validateOutcome(r).ok, true, JSON.stringify(validateOutcome(r).errors)); assert.equal(r.label, HYP_LABEL); assert.equal(r.executed, false); assert.equal(r.hypothetical_normal_cost.exit, 'TARGET_170R'); assert.ok(Math.abs(r.hypothetical_normal_cost.exit_r - ((103.4 - 100.24 - 0.10) / 2)) < 0.001); assert.ok(r.hypothetical_stress_cost.exit_r < r.hypothetical_normal_cost.exit_r); assert.equal(r.open_path.reach['1.7'], true); assert.equal(r.open_path.reach['2'], true); assert.equal(r.wrong_direction, false); assert.equal(r.bad_entry, false); assert.ok(r.open_path.mfe_r > 2); assert.ok(['BROKER_SL', 'THESIS_INVALIDATION'].includes(r.open_path.exit)); for (const m of HYP_MILESTONES) assert.ok(m in r.open_path.reach); });
  it('a wrong-direction signal: immediate stop, MFE < 0.5R, reach all false, negative exit_R in both cost models', () => { const c3 = candidateById('SC3_SILVER_N2_v1'); const start = sig.signal_bar_time + 300; const o = buildSilverN2Observation({ candidate: c3, nowSec: start + 100, signal: sig, provenance: 'TEST', silver5: [], bars5: [] }); assert.equal(o.payload.silver_confirmation_state, 'NA'); assert.equal(o.payload.silver_available_at_decision, false); const path = mkGold([99.6, 99.0, 97.9, 97.0], start); const r = labelHypothetical({ observation: o, bars5: path, nowSec: start + 300 * 4, provenance: 'TEST' }); assert.ok(r); assert.equal(r.wrong_direction, true); assert.equal(r.bad_entry, true); assert.ok(r.hypothetical_normal_cost.exit_r < 0 && r.hypothetical_stress_cost.exit_r < r.hypothetical_normal_cost.exit_r); assert.equal(Object.values(r.open_path.reach).some(Boolean), false); });
});

describe('DOM snapshot (DOM_MEASURE_ONLY, FORWARD_ONLY_DATA)', () => {
  it('parses a market book into depth, imbalance, spread, level counts and change vs previous; unavailable books are recorded with a reason, never fabricated', () => { const book = { ok: true, time: 1, levels: [{ type: 'BID', price: 99.9, volume: 10 }, { type: 'BID', price: 99.8, volume: 20 }, { type: 'ASK', price: 100.1, volume: 15 }, { type: 'ASK', price: 100.2, volume: 5 }] }; const d = domSnapshot(book, { tick: { bid: 99.9, ask: 100.1 }, nowSec: 5 }); assert.equal(d.available, true); assert.equal(d.measure_only, true); assert.equal(d.forward_only_data, true); assert.equal(d.bid_depth, 30); assert.equal(d.ask_depth, 20); assert.equal(d.imbalance, 0.2); assert.equal(d.best_bid, 99.9); assert.equal(d.best_ask, 100.1); assert.ok(Math.abs(d.spread - 0.2) < 1e-9); assert.equal(d.level_count, 4); const d2 = domSnapshot({ ok: true, levels: [{ type: 'BID', price: 99.9, volume: 5 }, { type: 'ASK', price: 100.1, volume: 5 }] }, { prev: d }); assert.equal(d2.liquidity_withdrawal, true); assert.ok(d2.depth_change_vs_prev < -0.5); const u = domSnapshot({ ok: false, error: 'NO_BOOK (1, Success)' }); assert.equal(u.available, false); assert.match(u.reason, /NO_BOOK/); assert.equal(domSnapshot(null).available, false); assert.equal(domSnapshot({ ok: true, levels: [] }).reason, 'EMPTY_BOOK'); });
});

describe('observer cycle with a fake reader: SC3 and SC4 records, provenance, dedup, outcome plan', () => {
  it('records one SC3 observation per production signal with same-bar and lag silver, DOM on forward records only, and labels the hypothetical outcome later', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'silver-dom-')); const prodDir = join(dir, 'prod'); mkdirSync(prodDir);
    const sigBar = T0 + 300 * 200; let nowSec = sigBar + 300 + 150; const gold = mkGold(Array.from({ length: 520 }, (_, k) => 4000 + 0.1 * k), T0); const silver = mkSilver(260, 60, 0.02); const bars = (arr, upto) => arr.filter((b) => b.time <= upto);
    const sigStore = { signals: [{ signal_id: 'sig1', side: 'BUY', model: 'BO', quality: 70, entry: 4020.5, stop_loss: 4018.5, tp1: 4022.5, tp2: 4026.5, rr: 3, signal_bar_time: sigBar, created_at: new Date((sigBar + 300 + 60) * 1000).toISOString() }] };
    writeFileSync(join(prodDir, 'signals.json'), JSON.stringify(sigStore)); writeFileSync(join(prodDir, 'wait.jsonl'), ''); writeFileSync(join(prodDir, 'audit.jsonl'), ''); writeFileSync(join(prodDir, 'cal.json'), JSON.stringify({ events: [], source: 'test', source_timestamp: new Date(nowSec * 1000).toISOString(), fetched_at: new Date(nowSec * 1000).toISOString() }));
    const reader = { rates: async (symbol, tf) => ({ ok: true, bars: symbol === 'XAGUSDm' && tf === '5m' ? bars(silver, nowSec) : tf === '5m' ? bars(gold, nowSec) : [] }), tick: async () => ({ ok: true, tick: { time: nowSec - 5, bid: 4020.4, ask: 4020.6 } }), book: async () => ({ ok: true, time: nowSec, levels: [{ type: 'BID', price: 4020.4, volume: 12 }, { type: 'ASK', price: 4020.6, volume: 8 }] }) };
    const prod = createProductionReader({ waitLog: join(prodDir, 'wait.jsonl'), signalStore: join(prodDir, 'signals.json'), auditLog: join(prodDir, 'audit.jsonl'), calendarSnapshot: join(prodDir, 'cal.json') });
    const obs = createShadowObserver({ dir, reader, prod, now: () => nowSec, log: () => {} }); await obs.cycle();
    const all = obs.store.readAll('observations'); const sc3 = all.filter((o) => o.candidate_id === 'SC3_SILVER_N2_v1'); assert.equal(sc3.length, 1); const o = sc3[0]; assert.equal(o.provenance, 'FORWARD_LIVE'); assert.equal(o.hypothesis_side, 'BUY'); assert.equal(o.execution_authority, 'NONE'); assert.equal(o.payload.silver_same_bar.bar_time, sigBar); assert.equal(o.payload.silver_same_bar.same_open_as_signal, true); assert.equal(o.payload.silver_lag_1.bar_time, sigBar - 300); assert.equal(o.payload.hypothetical.target_170r, 4023.9); assert.equal(o.payload.dom.available, true); assert.equal(o.payload.dom.bid_depth, 12); assert.ok(o.cross_asset.XAGUSDm_5m.bar_close_time <= Date.parse(o.decision_time_utc) / 1000);
    const candle = all.find((x) => x.type === 'CANDLE_5M' && x.provenance === 'FORWARD_LIVE'); assert.ok(candle && candle.dom && candle.dom.available === true, 'forward candle carries the DOM snapshot'); assert.equal(obs.status().silver_n2.observations, 1); assert.equal(obs.status().dom.available_cycles, 1);
    await obs.cycle(); assert.equal(obs.store.readAll('observations').filter((x) => x.candidate_id === 'SC3_SILVER_N2_v1').length, 1, 'no duplicate SC3 for the same signal');
    assert.equal(obs.store.readAll('outcomes').filter((r) => r.horizon === 'hyp288').length, 0, 'not labelled while the open path is unresolved');
    nowSec = sigBar + 300 * 60; await obs.cycle(); // gold rose 0.1/bar -> target 1.7R (3.4 USD) reached within ~35 bars, open path still unresolved (no stop)
    assert.equal(obs.store.readAll('outcomes').filter((r) => r.horizon === 'hyp288').length, 0);
    nowSec = sigBar + 300 * 300; await obs.cycle(); // horizon elapsed -> label
    const outs = obs.store.readAll('outcomes').filter((r) => r.horizon === 'hyp288'); assert.equal(outs.length, 1); assert.equal(outs[0].label, HYP_LABEL); assert.equal(outs[0].executed, false); assert.equal(outs[0].hypothetical_normal_cost.exit, 'TARGET_170R'); assert.equal(outs[0].open_path.reach['1.7'], true); assert.equal(outs[0].provenance, 'FORWARD_LIVE');
    assert.deepEqual(OUTCOME_PLAN.SC3_SILVER_N2_v1, [['hyp288', 288, '5m']]);
    rmSync(dir, { recursive: true, force: true });
  });
});

describe('report generator and gate', () => {
  it('status stays COLLECTING / INSUFFICIENT below 300 forward labelled observations; backfill never counts; POSITIVE requires every check, not win rate', () => { const mk = (i, prov, state, exitR, wrong, reach) => ({ o: { candidate_id: 'SC3_SILVER_N2_v1', observation_id: `id${i}`.padEnd(20, 'x'), provenance: prov, decision_time_utc: new Date((1_790_000_000 + 600 * i) * 1000).toISOString(), payload: { signal_id: `s${i}`, silver_confirmation_state: state, silver_available_at_decision: true, hypothetical: {}, silver_same_bar: { available: true, same_open_as_signal: true } } }, r: { observation_id: `id${i}`.padEnd(20, 'x'), horizon: 'hyp288', status: 'LABELED', silver_state_same_bar: state, silver_state_lag_1: state, wrong_direction: wrong, bad_entry: !reach, open_path: { mfe_r: reach ? 2 : 0.2, mae_r: 0.5, reach: { 1: reach, 1.25: reach, 1.5: reach, 1.7: reach, 2: reach } }, hypothetical_normal_cost: { exit_r: exitR, exit: exitR > 0 ? 'TARGET_170R' : 'BROKER_SL', duration_bars: 10 }, hypothetical_stress_cost: { exit_r: exitR - 0.1, exit: 'x' } } });
    const recs = []; for (let i = 0; i < 50; i++) recs.push(mk(i, 'FORWARD_LIVE', i % 2 ? 'CONFIRMED' : 'CONFLICT', i % 2 ? 1.6 : -1.1, !(i % 2), !!(i % 2))); for (let i = 50; i < 400; i++) recs.push(mk(i, 'BACKFILL', 'CONFIRMED', 1.6, false, true));
    const s = evaluateSilver(recs.map((x) => x.o), recs.map((x) => x.r)); assert.equal(s.data_quality.forward_live, 50); assert.equal(s.data_quality.backfill_or_other, 350); assert.equal(s.status, 'INSUFFICIENT_FORWARD_EVIDENCE'); assert.equal(s.interim, true); assert.equal(s.final_decision, 'NOT_YET'); assert.equal(s.forward_live_count, 50); assert.equal(s.remaining_to_300, 250); assert.equal(s.frozen_dataset, null); assert.equal(s.same_bar.CONTROL.n, 50); assert.equal(s.same_bar.CONFIRMED.n, 25); assert.equal(SILVER_GATE.min_forward_observations, 300);
    const big = []; for (let i = 0; i < 320; i++) big.push(mk(i, 'FORWARD_LIVE', i % 2 ? 'CONFIRMED' : 'CONFLICT', i % 2 ? 1.6 : -1.1, !(i % 2), !!(i % 2))); const s2 = evaluateSilver(big.map((x) => x.o), big.map((x) => x.r)); assert.equal(s2.data_quality.forward_live, 320); assert.equal(s2.frozen_dataset.n, 300, 'dataset frozen at the first 300 forward observations'); assert.equal(s2.data_quality.analysis_set, 300); assert.equal(s2.same_bar.CONTROL.n, 300); assert.match(s2.frozen_dataset.observation_ids_sha256, /^[0-9a-f]{64}$/); assert.ok(['POSITIVE', 'INCONCLUSIVE', 'NEGATIVE'].includes(s2.status)); assert.equal(s2.interim, false); assert.ok(['PROMISING_REQUIRES_NEW_RESEARCH_SPEC', 'REJECTED', 'INCONCLUSIVE'].includes(s2.final_decision));
    const unl = evaluateSilver(big.map((x) => x.o), big.slice(0, 250).map((x) => x.r)); assert.equal(unl.status, 'GATE_REACHED_AWAITING_LABELS'); assert.equal(unl.interim, true); assert.equal(s2.timing_sensitive, false);
    const d = evaluateDom([{ provenance: 'FORWARD_LIVE', dom: { available: true, bid_depth: 10, ask_depth: 5, imbalance: 0.333, level_count: 4, spread: 0.2, liquidity_withdrawal: false } }, { provenance: 'FORWARD_LIVE', dom: { available: false, reason: 'NO_BOOK' } }, { provenance: 'BACKFILL', dom: { available: true, bid_depth: 1, ask_depth: 1, imbalance: 0, level_count: 2, spread: 0.2 } }]); assert.equal(d.forward_live, 2); assert.equal(d.available, 1); assert.equal(d.unavailable_reasons.NO_BOOK, 1); assert.equal(d.dom_measure_only, true);
    const R = renderReports({ silver: s, dom: d, nowIso: '2026-10-01T00:00:00.000Z' }); assert.deepEqual(Object.keys(R).sort(), ['DOM_FORWARD_REPORT.md', 'FORWARD_DATA_QUALITY.md', 'SILVER_CONTROL_COMPARISON.md', 'SILVER_COST_STRESS.md', 'SILVER_N2_FORWARD_REPORT.md', 'SILVER_TIMING_ANALYSIS.md', 'V8_RESEARCH_RECOMMENDATION.md']); for (const md of Object.values(R)) { assert.ok(md.includes(HYP_LABEL)); assert.ok(md.includes('INTERIM — NOT FINAL — INSUFFICIENT_SAMPLE')); } assert.ok(R['SILVER_CONTROL_COMPARISON.md'].includes('SILVER NEUTRAL')); });
});

describe('no execution path', () => {
  it('reader protocol is the closed read-only list incl. the market book; the python reader has no trading call; shadow modules import no engine/executor/bridge; the silver report writes nothing under state', () => { assert.deepEqual([...READER_COMMANDS], ['rates', 'tick', 'select', 'ping', 'quit', 'book']); const py = readFileSync(join(ROOT, 'mt5/mt5_shadow_reader.py'), 'utf8'); for (const bad of ['order_send', 'order_check', 'order_calc', 'positions_close', 'TRADE_ACTION', 'position_modify', 'order_modify', 'Close(', 'Buy(', 'Sell(']) assert.ok(!py.includes(bad), bad); assert.ok(py.includes('market_book_get') && py.includes('market_book_release')); for (const f of ['core.js', 'observer.js', 'silverReport.js', 'candidates.js']) { const s = readFileSync(join(ROOT, `src/shadow/${f}`), 'utf8'); for (const bad of ['mt5Executor', 'mt5Bridge', 'mt5Policy', 'mt5RealPolicy', 'watcher.js', 'xauusd_calculate', 'signalStore', 'protectionGuards']) assert.ok(!s.includes(`/${bad}`) && !s.includes(`'${bad}`), `${f} ${bad}`); assert.ok(!/order_send|\.request\('open'|order\(/.test(s), `${f} order-like call`); } const rep = readFileSync(join(ROOT, 'src/shadow/silverReport.js'), 'utf8'); assert.ok(!rep.includes('appendObservation') && !rep.includes('appendOutcome'), 'report is read-only on the store'); });
});
