/**
 * TRADE ECONOMICS V5 -- deterministic tests for the pure exit-policy simulator (research/trade_economics_v5/scripts/exitPolicies.mjs)
 * and invariants over the frozen research artefacts: R normalisation, SL/target calculation, MFE/MAE, milestone reach, give-back,
 * break-even / partial / floor / adaptive-harvest / structural-trail / time logic, right-tail metric, cost accounting, no look-ahead
 * (a raised stop never acts on the bar that produced it), confirmed-candle entry (first exit >= t+1), one-position semantics,
 * restart determinism, pre-registration discipline, decision recomputation, production preservation.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { simulate, normalizeTrade, targetPrice, rightTail, giveback, MILESTONES } from '../research/trade_economics_v5/scripts/exitPolicies.mjs';
const ROOT = new URL('../research/trade_economics_v5/', import.meta.url);
const R = JSON.parse(readFileSync(new URL('results/v5_results.json', ROOT), 'utf8'));
const RD = JSON.parse(readFileSync(new URL('results/v5_results_DEV_phase.json', ROOT), 'utf8'));
const DEFN = JSON.parse(readFileSync(new URL('configs/finalists.json', ROOT), 'utf8'));
const V4 = JSON.parse(readFileSync(new URL('../research/entry_core_v4/results/v4_results.json', import.meta.url), 'utf8'));
const sha = (u) => createHash('sha256').update(readFileSync(u)).digest('hex');
const MEANINGFUL = ['CONTROL', 'S2', 'S3', 'S4']; const FAMS = ['FIXED', 'BE', 'PARTIAL', 'FLOOR', 'HARVEST', 'STRUCT_TRAIL', 'TIME'];
const COST = { spread: 0.24, slip: 0.10 };
// synthetic tape helpers: bars at 300 s spacing, flat 100 then a scripted path of closes with +-0.3 wicks
const mk = (closes, start = 1_700_000_000) => closes.map((c, k) => ({ time: start + 300 * k, open: c, high: c + 0.3, low: c - 0.3, close: c }));
const buy = (i, entry, sl) => ({ i, side: 'BUY', pop: 'T', geo: { entry, sl }, atr: 2.5 });
const sell = (i, entry, sl) => ({ i, side: 'SELL', pop: 'T', geo: { entry, sl }, atr: 2.5 });

describe('R normalisation, SL and target geometry', () => {
  it('1R = planned structural distance; BUY fill includes the spread; target = entry +/- rr x R from the planned entry', () => { const e = buy(5, 100, 98); const n = normalizeTrade(e, COST); assert.equal(n.risk, 2); assert.equal(n.fill, 100.24); assert.equal(n.sgn, 1); assert.equal(n.risk_atr, 0.8); assert.equal(targetPrice(e, 1.7), 103.4); const s = sell(5, 100, 102); assert.equal(normalizeTrade(s, COST).fill, 100); assert.equal(targetPrice(s, 2), 96); });
  it('an explicit target price (production TP2) overrides the R multiple', () => { const bars = mk([100, 100, 100, 100, 100, 100, 101, 102, 103, 104, 105]); const e = buy(5, 100, 98); const o = simulate(bars, e, { type: 'FIXED', tpPrice: 102.5 }, COST); assert.equal(o.exit, 'TP'); assert.equal(o.exitBar, 8, 'bar 7 high 102.3 < 102.5; bar 8 high 103.3 touches'); assert.ok(Math.abs(o.pnl_usd - (102.5 - 100.24 - 0.10)) < 1e-9); });
});

describe('MFE / MAE / milestones / cost accounting', () => {
  const bars = mk([100, 100, 100, 100, 100, 100, 99.2, 101.5, 102.8, 103.2, 101.0, 99.0, 97.0, 97, 97, 97]);
  it('MFE, MAE and milestone bars are measured from the fill in R; milestones record the FIRST bar reaching each level', () => { const e = buy(5, 100, 98); const o = simulate(bars, e, { type: 'OPEN' }, COST); assert.equal(o.exit, 'BROKER_SL', 'bar 12 low 96.7 -> adverse 3.54 >= 1.5R + spread (3.24) intrabar, before the close-based invalidation'); assert.equal(o.exitBar, 12); assert.ok(Math.abs(o.mfe_r - (103.5 - 100.24) / 2) < 0.001); assert.ok(Math.abs(o.mae_r - (100.24 - 96.7) / 2) < 0.001); assert.equal(o.milestones[0.5], 7); assert.equal(o.milestones[1], 8); assert.equal(o.milestones[1.5], 9); assert.equal(o.milestones[2], null); assert.ok(o.giveback_r > 1.5); });
  it('cost accounting: spread + slippage (+ swap for BUY nights) is charged exactly once; stress costs reduce R by the cost difference', () => { const e = buy(5, 100, 98); const a = simulate(bars, e, { type: 'FIXED', rr: 1 }, { spread: 0.24, slip: 0 }), b = simulate(bars, e, { type: 'FIXED', rr: 1 }, COST); assert.ok(Math.abs(a.pnl_usd - b.pnl_usd - 0.10) < 1e-9); assert.equal(b.cost_usd, 0.34); assert.ok(Math.abs(b.cost_r - 0.17) < 1e-9); });
  it('SL before TP on the same bar; broker fail-safe (1.5R + spread) is intrabar; thesis invalidation needs a CLOSE beyond the structural stop', () => { const wide = mk([100, 100, 100, 100, 100, 100, 100]); wide.push({ time: wide.at(-1).time + 300, open: 100, high: 104, low: 96.5, close: 100 }); const e = buy(5, 100, 98); const o = simulate(wide, e, { type: 'FIXED', rr: 1.7 }, COST); assert.equal(o.exit, 'BROKER_SL', 'adverse 3.74 >= 1.5*2+0.24 -> broker stop before the target on the same bar'); const dip = mk([100, 100, 100, 100, 100, 100, 97.9, 100.5, 100.5, 100.5]); const o2 = simulate(dip, e, { type: 'OPEN' }, COST); assert.equal(o2.exit, 'THESIS_INVALIDATION'); assert.equal(o2.exitBar, 6); const wick = mk([100, 100, 100, 100, 100, 100, 100, 100, 100]); wick[6] = { ...wick[6], low: 97.9 }; const o3 = simulate(wick, e, { type: 'OPEN' }, COST); assert.notEqual(o3.exit, 'THESIS_INVALIDATION', 'a wick below the structural stop without a close is not an invalidation'); });
});

describe('exit policies (information-time)', () => {
  // path: entry 100 (fill 100.24), R = 2; rises to +1.63R, then falls back through the entry to the structural stop
  const path = mk([100, 100, 100, 100, 100, 100, 101.0, 102.0, 103.2, 103.5, 102.0, 100.5, 99.0, 97.5, 97.5, 97.5]);
  it('break-even: once a completed bar reaches m R the stop moves to the fill (+spread) from the NEXT bar and exits intrabar', () => { const e = buy(5, 100, 98); const o = simulate(path, e, { type: 'BE', m: 0.5, rr: 3 }, COST); assert.equal(o.exit, 'PROTECTED_STOP'); assert.equal(o.stop_raised_bar, 6, 'bar 6 high 101.3 >= fill + 0.5R (101.24)'); assert.ok(o.exitBar > o.stop_raised_bar); assert.equal(o.exitBar, 11); assert.ok(Math.abs(o.pnl_usd - (0.24 - 0.10)) < 1e-9, 'break-even including the spread already paid, minus slippage'); });
  it('partial protection and profit floor place the stop at fill - protect R / fill + floor R', () => { const e = buy(5, 100, 98); const p = simulate(path, e, { type: 'PARTIAL', m: 0.5, protect: 0.5, rr: 3 }, COST); assert.equal(p.exit, 'PROTECTED_STOP'); assert.ok(Math.abs(p.pnl_usd - (-0.5 * 2 - 0.10)) < 1e-9); const f = simulate(path, e, { type: 'FLOOR', m: 1.0, floor: 0.5, rr: 3 }, COST); assert.equal(f.exit, 'PROTECTED_STOP'); assert.equal(f.stop_raised_bar, 7, 'bar 7 high 102.3 >= fill + 1R (102.24)'); assert.ok(Math.abs(f.pnl_usd - (0.5 * 2 - 0.10)) < 1e-9); });
  it('adaptive harvest ratchets the stop to MFE - gap once armed; the ratchet is monotone and never acts on the bar that set it', () => { const e = buy(5, 100, 98); const h = simulate(path, e, { type: 'HARVEST', arm: 1.0, gap: 0.5 }, COST); assert.equal(h.exit, 'PROTECTED_STOP'); assert.equal(h.stop_raised_bar, 7); assert.ok(h.exitBar > h.stop_raised_bar); assert.equal(h.exitBar, 10, 'ratchet set by bar 9 (MFE 1.78R -> stop 102.80) fills on bar 10 low 101.7'); const mfeR = (103.8 - 100.24) / 2; assert.ok(Math.abs(h.r - (mfeR - 0.5 - 0.05)) < 0.01, 'exit at MFE - 0.5R minus slippage'); const ctl = simulate(path, e, { type: 'FIXED', rr: 1.7 }, COST); assert.equal(ctl.exit, 'TP'); });
  it('structural trail uses only swings known at the completed bar and only once the swing is beyond the fill', () => { const e = buy(5, 100, 98); const swings = { 8: 101.0, 9: 101.0, 10: 102.5 }; const t = simulate(path, e, { type: 'STRUCT_TRAIL', swingAt: (j, side) => (side === 'BUY' ? swings[j] ?? null : null) }, COST); assert.equal(t.exit, 'PROTECTED_STOP'); assert.equal(t.stop_raised_bar, 8); assert.ok(Math.abs(t.pnl_usd - (102.5 - 100.24 - 0.10)) < 1e-9, 'trailed to the 102.5 swing known at bar 10, hit on bar 11'); const none = simulate(path, e, { type: 'STRUCT_TRAIL', swingAt: () => 99.5 }, COST); assert.notEqual(none.exit, 'PROTECTED_STOP', 'a swing below the fill never raises the stop'); });
  it('time stop exits at the close of bar n only if the trade is at or below -level R at that close', () => { const slow = mk([100, 100, 100, 100, 100, 100, 99.5, 99.0, 98.9, 99.5, 101, 102, 103, 104]); const e = buy(5, 100, 98); const t = simulate(slow, e, { type: 'TIME', bars: 3, level: 0.5, rr: 1.7 }, COST); assert.equal(t.exit, 'TIME_STOP'); assert.equal(t.exitBar, 8); const ok = simulate(slow, e, { type: 'TIME', bars: 3, level: 0.8, rr: 1.7 }, COST); assert.notEqual(ok.exit, 'TIME_STOP'); });
  it('no look-ahead: altering bars after the exit never changes the result; a raised stop never fires on its own bar', () => { const e = buy(5, 100, 98); const a = simulate(path, e, { type: 'HARVEST', arm: 1.0, gap: 0.5 }, COST); const path2 = [...path.slice(0, a.exitBar + 1), ...mk([50, 60, 150], path[a.exitBar].time + 300)]; const b = simulate(path2, e, { type: 'HARVEST', arm: 1.0, gap: 0.5 }, COST); assert.deepEqual({ ...a, milestones: null }, { ...b, milestones: null }); const spike = mk([100, 100, 100, 100, 100, 100, 100]); spike.push({ time: spike.at(-1).time + 300, open: 100, high: 103.3, low: 100, close: 103 }); spike.push({ time: spike.at(-1).time + 300, open: 103, high: 103.1, low: 99.5, close: 99.6 }); const s = simulate(spike, e, { type: 'BE', m: 1.0, rr: 5 }, COST); assert.equal(s.stop_raised_bar, 7); assert.equal(s.exitBar, 8, 'the break-even stop set by bar 7 acts on bar 8, not on bar 7'); assert.equal(R.meta.controls.raised_stop_no_lookahead, true); });
  it('confirmed-candle entry: the first exit bar is always >= entry + 1 (study control)', () => { assert.equal(R.meta.controls.first_exit_after_entry, true); const e = buy(5, 100, 98); const bars = mk([100, 100, 100, 100, 100, 100, 100]); bars[5] = { ...bars[5], high: 110 }; const o = simulate(bars, e, { type: 'FIXED', rr: 1 }, COST); assert.notEqual(o.exitBar, 5); });
});

describe('right tail and give-back metrics', () => {
  it('right-tail ratio = policy mean realized / control mean realized on trades whose OPEN MFE >= 2R; verdict thresholds 0.8 / 0.6', () => { const open = [{ e: { i: 1, side: 'BUY' }, o: { mfe_r: 2.5 } }, { e: { i: 2, side: 'BUY' }, o: { mfe_r: 0.5 } }, { e: { i: 3, side: 'SELL' }, o: { mfe_r: 3 } }]; const ctl = [{ e: { i: 1, side: 'BUY' }, o: { r: 2 } }, { e: { i: 2, side: 'BUY' }, o: { r: -1 } }, { e: { i: 3, side: 'SELL' }, o: { r: 2 } }]; const pol = [{ e: { i: 1, side: 'BUY' }, o: { r: 1.2 } }, { e: { i: 2, side: 'BUY' }, o: { r: 0.4 } }, { e: { i: 3, side: 'SELL' }, o: { r: 0.8 } }]; const rt = rightTail(open, pol, ctl); assert.equal(rt.tail_trades, 2); assert.equal(rt.control_mean_realized_r, 2); assert.equal(rt.policy_mean_realized_r, 1); assert.equal(rt.ratio, 0.5); assert.equal(rt.verdict, 'NO'); assert.equal(rt.truncation_rate, 0.5); assert.equal(rt.profit_lost_r, 2); const good = rightTail(open, ctl, ctl); assert.equal(good.verdict, 'YES'); });
  it('give-back = MFE - realized for trades with MFE >= threshold', () => { const rows = [{ o: { mfe_r: 1.2, r: 0.3 } }, { o: { mfe_r: 0.6, r: -1 } }, { o: { mfe_r: 0.2, r: -1 } }]; const g = giveback(rows); assert.equal(g[0.5].n, 2); assert.ok(Math.abs(g[0.5].mean_giveback_r - ((1.2 - 0.3 + 0.6 + 1) / 2)) < 1e-9); assert.equal(g[1].n, 1); assert.equal(g[0.5].losers_share, 0.5); });
});

describe('pre-registration discipline and controls', () => {
  it('pre-registration, control-baseline and finalists hashes match and are carried in the results; finalists derived from DEV', () => { for (const [f, k] of [['V5_PREREGISTRATION', 'prereg_sha256'], ['V5_CONTROL_BASELINE', 'control_baseline_sha256']]) { const frozen = readFileSync(new URL(`${f}.sha256`, ROOT), 'utf8').trim().split(/\s+/)[0]; assert.equal(sha(new URL(`${f}.md`, ROOT)), frozen); assert.equal(R.meta[k], frozen); } const fz = readFileSync(new URL('configs/finalists.sha256', ROOT), 'utf8').trim().split(/\s+/)[0]; assert.equal(sha(new URL('configs/finalists.json', ROOT)), fz); assert.equal(R.finalists_sha256, fz); assert.equal(DEFN.derived_from, 'DEV'); assert.deepEqual(RD.finalist_definitions, DEFN); assert.equal(R.meta.v4_finalists_sha256, sha(new URL('../research/entry_core_v4/configs/finalists.json', import.meta.url))); });
  it('leak / null / cost / first-exit / no-lookahead controls pass; CONTROL and V4 S3 reproduce V4 exactly under the control exit', () => { const c = R.meta.controls; assert.ok(c.leak_mean_r > 0.3); assert.ok(Math.abs(c.null_mean_r) < 0.15); assert.equal(c.cost_test.pass, true); assert.equal(c.control_reproduces_v4_dev, true); assert.equal(c.control_reproduces_v4_hold, true); for (const S of ['DEV', 'HOLD']) { const a = R[S].grid.CONTROL['CTL|PROD_TP2']; const b = S === 'DEV' ? V4.DEV.control : V4.HOLD.control; assert.equal(a.n, b.n); assert.equal(a.expectancy_r, b.expectancy_r); assert.equal(a.max_dd_r, b.max_dd_r); const s3 = R[S].grid.S3['FIXED|rr1.7'], v = V4[S].candidates.S3; assert.equal(s3.n, v.n); assert.equal(s3.expectancy_r, v.expectancy_r); } });
  it('restart determinism: DEV diagnostics and grids are identical between the DEV phase and the FULL phase', () => { assert.deepEqual(RD.DEV.grid, R.DEV.grid); assert.deepEqual(RD.DEV.diagnostics.CONTROL.mfe, R.DEV.diagnostics.CONTROL.mfe); assert.deepEqual(RD.DEV.diagnostics.S3.target_reach, R.DEV.diagnostics.S3.target_reach); });
  it('populations are the frozen V4 finalists plus CONTROL; the policy grid is the pre-registered 27 + open path', () => { assert.deepEqual(Object.keys(R.meta.populations), ['CONTROL', 'S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7']); assert.equal(R.meta.populations.CONTROL.all, 9617); assert.equal(R.meta.policies.length, 28); assert.deepEqual(R.meta.meaningful, MEANINGFUL); });
});

describe('finalist derivation and accounting invariants', () => {
  it('per population x family: highest DEV sequential expectancy among policies with N >= 200', () => { for (const pop of MEANINGFUL) for (const fam of FAMS) { const pts = R.meta.policies.filter((k) => k !== 'OPEN' && (k.split('|')[0] === fam)).map((k) => ({ k, ...RD.DEV.grid[pop][k] })).filter((x) => x.n >= 200); const f = DEFN.finalists[pop][fam]; if (!pts.length) { assert.equal(f, null); continue; } pts.sort((a, b) => b.expectancy_r - a.expectancy_r); assert.equal(f.key, pts[0].k, `${pop} ${fam}`); assert.equal(f.dev_expectancy_r, pts[0].expectancy_r); } });
  for (const S of ['DEV', 'HOLD']) {
    it(`${S}: one-position semantics (trades + skips = signals), exit mix sums to one, win/loss decomposition consistent`, () => { for (const pop of MEANINGFUL) for (const [fam, v] of Object.entries(R.finalists[S][pop])) { if (!v) continue; assert.equal(v.n + Object.values(v.skipped).reduce((a, b) => a + b, 0), v.signals, `${pop} ${fam}`); const s = Object.values(v.exit_mix).reduce((a, b) => a + b, 0); assert.ok(Math.abs(s - 1) < 0.01); if (v.avg_loss_r != null) { const e = v.win_rate * v.avg_win_r - (1 - v.win_rate) * v.avg_loss_r; assert.ok(Math.abs(e - v.expectancy_r) < 0.02, `${pop} ${fam} ${e} vs ${v.expectancy_r}`); } } });
    it(`${S}: MFE/MAE buckets partition winners and losers; milestone reach rates are monotone non-increasing`, () => { for (const pop of MEANINGFUL) { const d = R[S].diagnostics[pop]; const wn = Object.values(d.mae.winners).reduce((a, v) => a + v.n, 0), ln = Object.values(d.mae.losers).reduce((a, v) => a + v.n, 0); assert.equal(wn + ln, d.normalisation.n, pop); const reach = MILESTONES.map((m) => d.target_reach.overall[m]); for (let k = 1; k < reach.length; k++) assert.ok(reach[k] <= reach[k - 1] + 1e-9, `${pop} reach monotone`); for (const m of MILESTONES) assert.ok((d.mfe.winners_reaching_open[m] ?? 0) >= (d.mfe.losers_reaching_open[m] ?? 0), `${pop} winners reach >= losers at ${m}`); } });
  }
  it('right tail: the control exit scores ratio 1.0 against itself; HARVEST policies truncate the tail (ratio < 1)', () => { for (const pop of MEANINGFUL) { const c = R.finalists.HOLD[pop].CONTROL_EXIT.right_tail; assert.equal(c.ratio, 1); assert.equal(c.verdict, 'YES'); const h = R.finalists.HOLD[pop].HARVEST; if (h) assert.ok(h.right_tail.ratio < 1, pop); } });
});

describe('decision rules recompute from the persisted HOLDOUT statistics', () => {
  it('each policy status follows the section-7 gate', () => { for (const pop of MEANINGFUL) { const H = R.finalists.HOLD[pop], D = R.finalists.DEV[pop], ctl = H.CONTROL_EXIT; for (const [fam, c] of Object.entries(H)) { if (fam === 'CONTROL_EXIT') continue; const reasons = []; if (!(c.expectancy_r > 0)) reasons.push('(1)'); if (!(c.pf > 1.10)) reasons.push('(2)'); if (!(c.expectancy_r >= ctl.expectancy_r + 0.10 && c.max_dd_r <= ctl.max_dd_r)) reasons.push('(3)'); if (!(c.n >= 200)) reasons.push('(4)'); if (!((c.quarters_positive_share ?? 0) >= 0.6)) reasons.push('(5)'); if (c.neighbourhood.classification !== 'ROBUST') reasons.push('(6)'); if (c.tiny_cells && !c.tiny_cells.pass) reasons.push('(7)'); if (c.right_tail.verdict !== 'YES') reasons.push('(8)'); if (!(c.stress.expectancy_r > 0)) reasons.push('(10)'); if (!(c.ci95_r?.[0] > 0)) reasons.push('(13)'); if (!(c.block_ci95_r?.[0] > 0)) reasons.push('(13)'); if (!(D[fam].expectancy_r > 0)) reasons.push('DEV'); if (!(c.drift.expectancy_r > 0)) reasons.push('drift'); const d = R.decisions.by_population[pop].policies[fam]; assert.deepEqual(d.reasons.map((r) => (r.startsWith('(') ? r.slice(0, r.indexOf(')') + 1) : r.startsWith('DEV') ? 'DEV' : 'drift')), reasons, `${pop} ${fam}`); assert.equal(d.status, reasons.length ? (reasons.every((r) => r === '(13)') ? 'PROMISING_INCONCLUSIVE (fails only the CI requirement)' : 'FAILS_GATE') : 'PASS'); } } });
  it('aggregate: no pass; ENTRY NEGATIVE (every meaningful population <= 0 under its control exit); EXIT INCONCLUSIVE; EDGE NO; DEMO NO', () => { const D = R.decisions; assert.deepEqual(D.passing, []); for (const pop of MEANINGFUL) assert.ok(R.finalists.HOLD[pop].CONTROL_EXIT.expectancy_r <= 0, pop); assert.equal(D.entry_economics_result, 'NEGATIVE'); const anyImprove = MEANINGFUL.some((pop) => Object.values(D.by_population[pop].policies).some((p) => p.improvement_r >= 0.10)); assert.equal(D.exit_geometry_result, anyImprove ? 'INCONCLUSIVE' : 'NEGATIVE'); assert.equal(D.edge_demonstrated, 'NO'); assert.equal(D.demo_eligible, 'NO'); const b = D.best; const ctl = R.finalists.HOLD.CONTROL.CONTROL_EXIT; assert.equal(D.control_vs_v5, b.ci95_r[0] > ctl.expectancy_r && b.hold_dd_r <= ctl.max_dd_r ? 'BETTER' : b.hold_expectancy_r < ctl.expectancy_r ? 'WORSE' : 'INCONCLUSIVE'); assert.ok(D.four_way.CONTROL_ENTRY_WITH_CONTROL_EXIT.expectancy_r < 0 && D.four_way.V4_ENTRY_WITH_CONTROL_EXIT.expectancy_r < 0); });
});

describe('production preservation', () => {
  it('the study and simulator import nothing from the executor, bridge, watcher or MT5; no V5 runtime module exists', () => { for (const f of ['scripts/v5_study.mjs', 'scripts/exitPolicies.mjs', 'scripts/v4_populations.mjs']) { const src = readFileSync(new URL(f, ROOT), 'utf8'); for (const bad of ['mt5Executor', 'mt5_bridge', 'watcher.js', 'order_send', 'startWatcher', 'capitalHarvest/index']) assert.ok(!src.includes(bad), `${f} ${bad}`); } const imports = [...readFileSync(new URL('scripts/v5_study.mjs', ROOT), 'utf8').matchAll(/from '([^']+)'/g)].map((m) => m[1]).filter((p) => p.includes('src/')); assert.deepEqual(imports, ['../../../src/engine/capitalHarvest/positionManager.js']); assert.throws(() => readFileSync(new URL('../src/engine/tradeEconomicsV5.js', import.meta.url))); });
  it('CONTROL geometry unchanged: RR 1.70 reference, lot-neutral R economics with 0.01-lot USD reported separately; costs and split frozen', () => { const reg = JSON.parse(readFileSync(new URL('../src/engine/strategy.frozen.json', import.meta.url), 'utf8')); assert.equal(reg.strategy_fingerprint, '356e41898259af88e459c4d5287f346992ad5c308c9f7aee1ee141671f1e46ed'); assert.deepEqual(R.meta.costs, { normal: { spread: 0.24, slip: 0.1 }, stress: { spread: 0.6, slip: 0.2 } }); assert.deepEqual(R.meta.split, { dev: ['2025-05-07', '2025-12-31'], hold: ['2026-01-01', '2026-09-29'] }); for (const pop of MEANINGFUL) { const v = R.finalists.HOLD[pop].CONTROL_EXIT; assert.ok(typeof v.expectancy_r === 'number' && typeof v.expectancy_usd === 'number' && v.capital.lot === 0.01, pop); } });
});
