/**
 * ENTRY ENGINE EDGE V1 -- study runner (RESEARCH ONLY). Spec: ../ENTRY_EDGE_PREREGISTRATION.md (hash asserted).
 * EDGE_PHASE=DEV : every diagnostic on DEVELOPMENT only; derives candidate definitions mechanically -> results/candidate_definitions.json
 * EDGE_PHASE=FULL: asserts the frozen candidate_definitions hash, runs DEV + HOLDOUT once -> results/edge_results.json
 * Reads Edge Lab bars/rows and the enriched candidate set read-only. No production module is modified; imports only pure helpers.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { canReenter } from '../../../src/engine/capitalHarvest/positionManager.js';

const PHASE = process.env.EDGE_PHASE === 'FULL' ? 'FULL' : 'DEV';
const HERE = dirname(fileURLToPath(import.meta.url)); const REPO = join(HERE, '..', '..', '..'); const ROOT = join(REPO, 'research', 'entry_engine_edge_v1'); const OUT = join(ROOT, 'results'); mkdirSync(OUT, { recursive: true });
const PREREG_SHA = readFileSync(join(ROOT, 'ENTRY_EDGE_PREREGISTRATION.sha256'), 'utf8').trim().split(/\s+/)[0];
if (createHash('sha256').update(readFileSync(join(ROOT, 'ENTRY_EDGE_PREREGISTRATION.md'))).digest('hex') !== PREREG_SHA) throw new Error('PREREGISTRATION hash mismatch');
const LAB = join(REPO, 'handoff', 'edge_discovery_lab', 'data');
const b5 = JSON.parse(readFileSync(join(LAB, 'XAUUSDm_bars.json'), 'utf8'))['5m'];
const COSTS = { normal: { spread: 0.24, slip: 0.10 }, stress: { spread: 0.60, slip: 0.20 } }; const SWAP = 0.56; const HORIZON = 288; const GAP = 3 * 3600;
const r2 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 100) / 100); const r3 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 1000) / 1000); const r4 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 10000) / 10000);
const iso = (t) => new Date(t * 1000).toISOString(); const day = (t) => iso(t).slice(0, 10); const month = (t) => iso(t).slice(0, 7); const quarter = (t) => { const d = new Date(t * 1000); return `${d.getUTCFullYear()}Q${Math.floor(d.getUTCMonth() / 3) + 1}`; };
const SPLIT = { dev: ['2025-05-07', '2025-12-31'], hold: ['2026-01-01', '2026-09-29'] };
const split = (t) => { const d = day(t); if (d >= SPLIT.dev[0] && d <= SPLIT.dev[1]) return 'DEV'; if (d >= SPLIT.hold[0] && d <= SPLIT.hold[1]) return 'HOLD'; return 'EXCLUDED'; };
const mean = (a) => (a.length ? a.reduce((s, x) => s + x, 0) / a.length : null); const median = (a) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); const m = s.length >> 1; return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2; }; const pct = (a, p) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); return s[Math.min(s.length - 1, Math.floor(p * s.length))]; };
function rng(seed) { let s = seed >>> 0; return () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
function bootCI(v, n = 2000, seed = 20260930, alpha = 0.05) { if (v.length < 2) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0; for (let j = 0; j < v.length; j++) s += v[Math.floor(rand() * v.length)]; ms.push(s / v.length); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor((alpha / 2) * n)]), r3(ms[Math.floor((1 - alpha / 2) * n)])]; }
function blockCI(rows, keyFn, n = 2000, seed = 7, alpha = 0.05) { const g = {}; for (const r of rows) (g[keyFn(r)] ??= []).push(r.o.r); const blocks = Object.values(g); if (blocks.length < 5) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0, c = 0; for (let j = 0; j < blocks.length; j++) { const b = blocks[Math.floor(rand() * blocks.length)]; for (const x of b) { s += x; c++; } } ms.push(s / c); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor((alpha / 2) * n)]), r3(ms[Math.floor((1 - alpha / 2) * n)])]; }

// ---------- data ----------
const C = readFileSync(join(REPO, 'research', 'entry_architecture_v2', 'results', 'candidates.jsonl'), 'utf8').trim().split('\n').map((l) => JSON.parse(l)).filter((c) => split(c.t) !== 'EXCLUDED');
for (const c of C) { c.split = split(c.t); c.rr = c.geo.rr; c.f = { vol: !!c.vol_ok, ov: !!c.overext_ok, rr: c.geo.rr >= 1.7, q: c.q_final >= c.q_th, fresh: !c.fresh_opp, two: !c.two_factor, htf: !c.htf_conflict }; c.f.all = Object.values(c.f).every(Boolean); c.isSig = c.act === 'BUY' || c.act === 'SELL'; }
if (C.some((c) => c.f.all !== c.isSig)) { const bad = C.filter((c) => c.f.all !== c.isSig).length; if (bad) throw new Error(`FLAG/ACT CONSISTENCY FAILED ${bad}`); }
let misaligned = 0; for (const c of C) if (b5[c.i]?.time !== c.t) misaligned++; let nonMono = 0; for (let k = 1; k < b5.length; k++) if (!(b5[k].time > b5[k - 1].time)) nonMono++;
if (misaligned || nonMono) throw new Error('ALIGNMENT CONTROL FAILED');
const ROWS = new Map(); const sessions = { DEV: new Set(), HOLD: new Set(), ALL: new Set() }; let rowCounts = { DEV: { total: 0, chop: 0, noElig: 0, noSetup: 0, candidate: 0 }, HOLD: { total: 0, chop: 0, noElig: 0, noSetup: 0, candidate: 0 } };
for (const line of readFileSync(join(LAB, 'lab_rows.jsonl'), 'utf8').split('\n')) { if (!line) continue; const r = JSON.parse(line); const sp = split(r.t); if (sp === 'EXCLUDED') continue; ROWS.set(r.i, { t: r.t, act: r.act, wr: r.wr, mdl: r.mdl, cs: r.cs, elig: r.elig, rg5: r.rg5, atr: r.atr }); sessions[sp].add(day(r.t)); sessions.ALL.add(day(r.t)); const rc = rowCounts[sp]; rc.total++; if (r.wr === 'CHOP') rc.chop++; else if (r.wr === 'NO_ELIGIBLE_STRATEGY') { if (!r.elig) rc.noElig++; else rc.noSetup++; } else rc.candidate++; }
const inSplit = (S) => (c) => S === 'ALL' || c.split === S;
console.log(`phase ${PHASE}; candidates ${C.length} (DEV ${C.filter((c) => c.split === 'DEV').length} HOLD ${C.filter((c) => c.split === 'HOLD').length}); signals ${C.filter((c) => c.isSig).length}; rows DEV ${rowCounts.DEV.total} HOLD ${rowCounts.HOLD.total}`);

// ---------- EXIT_F ----------
function exitF(c, costs = COSTS.normal, drift = false) {
  const { i, side } = c; const { entry, sl, tp2 } = c.geo; const sp = costs.spread, slip = costs.slip; const sgn = side === 'BUY' ? 1 : -1;
  let fill = side === 'BUY' ? entry + sp : entry, start = i + 1; if (drift) { if (i + 1 >= b5.length) return { status: 'NO_DATA' }; fill = side === 'BUY' ? b5[i + 1].open + sp : b5[i + 1].open; start = i + 2; }
  const d = Math.abs(entry - sl); if (!(d > 0)) return { status: 'INVALID' }; const brokerDist = 1.5 * d + sp; const end = Math.min(b5.length - 1, i + HORIZON);
  let mfe = 0, mae = 0, mae3 = 0, nights = 0, gap = false, exit = null, exitBar = null, pnl = 0;
  for (let j = start; j <= end; j++) { const b = b5[j], p = b5[j - 1]; if (b.time - p.time > GAP) gap = true; if (side === 'BUY' && Math.floor(b.time / 86400) !== Math.floor(p.time / 86400)) nights++;
    const adv = side === 'BUY' ? fill - b.low : (b.high + sp) - fill; const fav = side === 'BUY' ? b.high - fill : fill - (b.low + sp);
    if (adv > mae) mae = adv; if (j - i <= 3 && adv > mae3) mae3 = adv;
    if (adv >= brokerDist) { exit = 'BROKER_SL'; pnl = -brokerDist - slip; exitBar = j; break; }
    const tpHit = side === 'BUY' ? b.high >= tp2 : (b.low + sp) <= tp2; if (tpHit) { if (fav > mfe) mfe = fav; exit = 'TP2'; pnl = Math.abs(tp2 - fill) - slip; exitBar = j; break; }
    if (fav > mfe) mfe = fav;
    if (side === 'BUY' ? b.close < sl : b.close > sl) { exit = 'THESIS_INVALIDATION'; pnl = sgn * ((side === 'BUY' ? b.close : b.close + sp) - fill) - slip; exitBar = j; break; } }
  let status = 'RESOLVED'; if (!exit) { if (end < i + HORIZON) return { status: 'NO_DATA' }; status = 'OPEN_AT_HORIZON'; const b = b5[end]; exit = 'HORIZON'; pnl = sgn * ((side === 'BUY' ? b.close : b.close + sp) - fill) - slip; exitBar = end; }
  const swap = side === 'BUY' ? nights * SWAP : 0; pnl -= swap;
  return { status, gap, exit, exitBar, bars: exitBar - i, d: r3(d), pnl_usd: r3(pnl), r: r3(pnl / d), mfe_r: r3(mfe / d), mae_r: r3(mae / d), mae3_r: r3(mae3 / d), cost_usd: r3(sp + slip + swap), cost_r: r3((sp + slip + swap) / d), win: pnl > 0 };
}
console.log('simulating EXIT_F ...'); const O = { normal: C.map((c) => exitF(c)), stress: C.map((c) => exitF(c, COSTS.stress)), drift: C.map((c) => exitF(c, COSTS.normal, true)) }; console.log('done');
const rowsOf = (pred, cse = 'normal') => C.map((c, k) => ({ c, o: O[cse][k], k })).filter((x) => pred(x.c) && x.o.status !== 'NO_DATA' && x.o.status !== 'INVALID');

// ---------- statistics ----------
function indepRows(rows) { const out = []; let lastI = -1e9, lastSide = null; for (const x of [...rows].sort((a, b) => a.c.i - b.c.i)) { if (x.c.side !== lastSide || x.c.i - lastI > 12) out.push(x); lastI = x.c.i; lastSide = x.c.side; } return out; }
function seqWalk(rows) { const trades = []; let exitBar = -1, lastTrade = null, lastLoss = false; const skipped = { SAME_OR_EARLIER_CANDLE: 0, STALE_SAME_SETUP: 0, REVENGE_GUARD: 0 }; const occ = []; for (const x of [...rows].sort((a, b) => a.c.i - b.c.i)) { const ok = canReenter({ signal: x.c, exitBar, lastTrade, lastExitWasLoss: lastLoss }); if (!ok.ok) { skipped[ok.reason]++; continue; } trades.push(x); occ.push([x.c.i, x.o.exitBar]); exitBar = x.o.exitBar; lastTrade = x.c; lastLoss = x.o.r <= 0; } return { trades, skipped, occ }; }
function pathDD(rows, key = 'r') { let cum = 0, peak = 0, dd = 0, streak = 0, maxStreak = 0; for (const x of rows) { cum += x.o[key]; if (cum > peak) peak = cum; dd = Math.max(dd, peak - cum); if (x.o[key] <= 0) { streak++; maxStreak = Math.max(maxStreak, streak); } else streak = 0; } return { max_dd: r2(dd), final: r2(cum), max_loss_streak: maxStreak }; }
function stats(rows, sessSet = null, { ci = true, block = false } = {}) { const R = rows.map((x) => x.o.r); if (!R.length) return { n: 0 }; const w = R.filter((x) => x > 0), l = R.filter((x) => x <= 0); const gw = w.reduce((a, b) => a + b, 0), gl = -l.reduce((a, b) => a + b, 0); const U = rows.map((x) => x.o.pnl_usd); const perDay = {}; for (const x of rows) perDay[day(x.c.t)] = (perDay[day(x.c.t)] ?? 0) + 1; const counts = sessSet ? [...sessSet].map((d) => perDay[d] ?? 0) : null; const months = {}; for (const x of rows) months[month(x.c.t)] = (months[month(x.c.t)] ?? 0) + x.o.r; const mv = Object.values(months); const gwU = U.filter((x) => x > 0).reduce((a, b) => a + b, 0); const costU = rows.reduce((s, x) => s + x.o.cost_usd, 0); const ddR = pathDD(rows, 'r'), ddU = pathDD(rows, 'pnl_usd');
  return { n: R.length, independent_n: indepRows(rows).length, win_rate: r3(w.length / R.length), avg_win_r: r3(mean(w)), avg_loss_r: l.length ? r3(-mean(l)) : null, expectancy_r: r3(mean(R)), expectancy_usd: r3(mean(U)), pf: gl > 0 ? r2(gw / gl) : (gw > 0 ? 99 : null), ci95_r: ci ? bootCI(R) : null, ci99_r: ci ? bootCI(R, 2000, 20260930, 0.01) : null, session_block_ci95_r: block ? blockCI(rows, (x) => day(x.c.t)) : null, session_block_ci99_r: block ? blockCI(rows, (x) => day(x.c.t), 2000, 7, 0.01) : null, max_dd_r: ddR.max_dd, max_dd_usd: ddU.max_dd, net_r: ddR.final, net_usd: ddU.final, max_loss_streak: ddR.max_loss_streak, mfe_r_mean: r3(mean(rows.map((x) => x.o.mfe_r))), mae_r_mean: r3(mean(rows.map((x) => x.o.mae_r))), mae3_r_mean: r3(mean(rows.map((x) => x.o.mae3_r))), avg_bars: r2(mean(rows.map((x) => x.o.bars))), median_bars: median(rows.map((x) => x.o.bars)), cost_usd_per_trade: r3(costU / R.length), cost_r_per_trade: r3(mean(rows.map((x) => x.o.cost_r))), cost_pct_of_gross_profit: gwU > 0 ? r3(costU / (gwU + costU)) : null, gross_expectancy_usd: r3(mean(U) + costU / R.length), cost_pct_of_gross_expectancy: (mean(U) + costU / R.length) > 0 ? r3((costU / R.length) / (mean(U) + costU / R.length)) : null, avg_d_usd: r2(mean(rows.map((x) => x.o.d))), trades_per_session: counts ? { median: pct(counts, 0.5), p10: pct(counts, 0.1), p90: pct(counts, 0.9) } : null, zero_trade_session_rate: counts ? r3(counts.filter((x) => x === 0).length / counts.length) : null, months_positive_share: mv.length ? r3(mv.filter((x) => x > 0).length / mv.length) : null, top5_share: gw > 0 ? r3([...R].sort((a, b) => b - a).slice(0, 5).filter((x) => x > 0).reduce((s, x) => s + x, 0) / gw) : null, exit_mix: Object.fromEntries(Object.entries(rows.reduce((g, x) => { g[x.o.exit] = (g[x.o.exit] ?? 0) + 1; return g; }, {}))), wrong_direction_loss_share: l.length ? r3(rows.filter((x) => x.o.r <= 0 && x.o.mfe_r < 0.25).length / l.length) : null, right_direction_loss_share: l.length ? r3(rows.filter((x) => x.o.r <= 0 && x.o.mfe_r >= 0.5).length / l.length) : null }; }
const MODELS = ['MC', 'PB', 'BO', 'SR', 'MR']; const insuff = (n) => (n < 30 ? 'INSUFFICIENT' : 'ok');
const sigRows = (S, cse = 'normal') => rowsOf((c) => c.isSig && inSplit(S)(c), cse);

// ---------- controls ----------
const ctrl = (() => { const rand = rng(99); const leak = [], nul = []; const base = C.filter((c, k) => c.isSig && k % 5 === 0); for (const c of base) { if (c.i + 13 >= b5.length) continue; const fut = b5[c.i + 12].close - b5[c.i].close; const mk = (side) => ({ i: c.i, side, geo: { entry: b5[c.i].close, sl: side === 'BUY' ? b5[c.i].close - c.atr : b5[c.i].close + c.atr, tp2: side === 'BUY' ? b5[c.i].close + c.atr : b5[c.i].close - c.atr } }); const o1 = exitF(mk(fut >= 0 ? 'BUY' : 'SELL')), o2 = exitF(mk(rand() < 0.5 ? 'BUY' : 'SELL')); if (o1.status !== 'NO_DATA' && !o1.gap) leak.push(o1.r); if (o2.status !== 'NO_DATA' && !o2.gap) nul.push(o2.r); }
  const s = C.slice(0, 400); const a = s.map((c) => exitF(c).pnl_usd), b = s.map((c) => exitF(c, { spread: 0.24, slip: 0 }).pnl_usd); const diff = mean(b) - mean(a); const first = C.slice(0, 2000).every((c, k) => O.normal[k].status === 'NO_DATA' || O.normal[k].exitBar >= c.i + 1);
  return { leak_mean_r: r3(mean(leak)), leak_n: leak.length, null_mean_r: r3(mean(nul)), null_n: nul.length, cost_test: { diff: r3(diff), expected: 0.10, pass: Math.abs(diff - 0.10) < 0.001 }, confirmed_candle_first_exit_after_entry: first, flags_reproduce_production_signals: true, timestamp_misaligned: misaligned, non_monotone_bars: nonMono }; })();
console.log('controls', JSON.stringify(ctrl)); if (!(ctrl.leak_mean_r > 0.3) || !(Math.abs(ctrl.null_mean_r) < 0.15) || !ctrl.cost_test.pass || !ctrl.confirmed_candle_first_exit_after_entry) throw new Error('CONTROL FAILED');

// ---------- diagnostics for a split ----------
function diagnostics(S) {
  const sess = sessions[S]; const SIGS = sigRows(S); const ALLC = rowsOf(inSplit(S));
  const D = {};
  // 1. decomposition
  D.decomposition = {}; for (const m of MODELS) { const cm = C.filter((c) => c.model === m && inSplit(S)(c)); const fun = (pred) => cm.filter(pred).length; const funnel = { candidates: cm.length, pass_atr_floor: fun((c) => c.f.vol), pass_overextension: fun((c) => c.f.vol && c.f.ov), pass_rr: fun((c) => c.f.vol && c.f.ov && c.f.rr), pass_quality: fun((c) => c.f.vol && c.f.ov && c.f.rr && c.f.q), pass_fresh_choch: fun((c) => c.f.vol && c.f.ov && c.f.rr && c.f.q && c.f.fresh), pass_two_factor: fun((c) => c.f.vol && c.f.ov && c.f.rr && c.f.q && c.f.fresh && c.f.two), pass_htf: fun((c) => c.f.all), signals: fun((c) => c.isSig), safety_gates: 'not in replay (constant)' }; const rows = SIGS.filter((x) => x.c.model === m); const only = seqWalk(rows); D.decomposition[m] = { funnel, signals_all: stats(rows, sess), signals_long: stats(rows.filter((x) => x.c.side === 'BUY'), sess), signals_short: stats(rows.filter((x) => x.c.side === 'SELL'), sess), executable_only_this_model: stats(only.trades, sess), executable_skipped: only.skipped }; }
  // 2. contribution
  const port = (rows) => { const w = seqWalk(rows); const st = stats(w.trades, sess); return { ...st, skipped: w.skipped, regimes_covered: Object.keys(w.trades.reduce((g, x) => { g[x.c.rg5] = 1; return g; }, {})).length }; };
  D.contribution = { ALL: port(SIGS) }; for (const m of MODELS) { D.contribution[`NO_${m}`] = port(SIGS.filter((x) => x.c.model !== m)); D.contribution[`ONLY_${m}`] = port(SIGS.filter((x) => x.c.model === m)); }
  // 3. regime x model matrix
  const cell = (rows) => { const s = stats(rows, null, { ci: rows.length >= 30 }); return { n: s.n ?? 0, sample: insuff(s.n ?? 0), win_rate: s.win_rate, avg_win_r: s.avg_win_r, avg_loss_r: s.avg_loss_r, expectancy_r: s.expectancy_r, expectancy_usd: s.expectancy_usd, pf: s.pf, mfe_r: s.mfe_r_mean, mae_r: s.mae_r_mean, cost_r: s.cost_r_per_trade, ci95_r: s.ci95_r }; };
  const atrT = (() => { const v = SIGS.map((x) => x.c.atrR).sort((a, b) => a - b); return [v[Math.floor(v.length / 3)], v[Math.floor((2 * v.length) / 3)]]; })(); const atrBucket = (a) => (a < atrT[0] ? 'ATR_LOW' : a < atrT[1] ? 'ATR_MID' : 'ATR_HIGH');
  D.matrix = { atr_terciles: atrT.map(r3), by_5m_regime: {}, by_15m_bias: {}, by_30m_regime: {}, by_1h_regime: {}, by_atr_tercile: {}, opportunities_by_5m_regime: {} };
  for (const m of MODELS) { const rows = SIGS.filter((x) => x.c.model === m); const grp = (f) => { const g = {}; for (const x of rows) (g[String(f(x.c))] ??= []).push(x); return Object.fromEntries(Object.entries(g).map(([k, v]) => [k, cell(v)])); }; D.matrix.by_5m_regime[m] = grp((c) => c.rg5); D.matrix.by_15m_bias[m] = grp((c) => c.b15d); D.matrix.by_30m_regime[m] = grp((c) => c.m30r); D.matrix.by_1h_regime[m] = grp((c) => c.h1r); D.matrix.by_atr_tercile[m] = grp((c) => atrBucket(c.atrR)); const og = {}; for (const c of C.filter((c) => c.model === m && inSplit(S)(c))) og[c.rg5] = (og[c.rg5] ?? 0) + 1; D.matrix.opportunities_by_5m_regime[m] = og; }
  // 4. directional
  D.directional = {}; for (const m of [...MODELS, 'ALL']) { const rows = m === 'ALL' ? SIGS : SIGS.filter((x) => x.c.model === m); const L = rows.filter((x) => x.c.side === 'BUY'), Sh = rows.filter((x) => x.c.side === 'SELL'); const sL = stats(L, sess), sS = stats(Sh, sess); const stL = stats(rowsOf((c) => c.isSig && inSplit(S)(c) && c.side === 'BUY' && (m === 'ALL' || c.model === m), 'stress'), null, { ci: false }), stS = stats(rowsOf((c) => c.isSig && inSplit(S)(c) && c.side === 'SELL' && (m === 'ALL' || c.model === m), 'stress'), null, { ci: false }); D.directional[m] = { LONG: { ...sL, stress_expectancy_r: stL.expectancy_r }, SHORT: { ...sS, stress_expectancy_r: stS.expectancy_r }, asymmetry_r: sL.n && sS.n ? r3(sL.expectancy_r - sS.expectancy_r) : null }; }
  // 5. funnel attribution (candle level + candidate level)
  const rc = S === 'ALL' ? { total: rowCounts.DEV.total + rowCounts.HOLD.total, chop: rowCounts.DEV.chop + rowCounts.HOLD.chop, noElig: rowCounts.DEV.noElig + rowCounts.HOLD.noElig, noSetup: rowCounts.DEV.noSetup + rowCounts.HOLD.noSetup, candidate: rowCounts.DEV.candidate + rowCounts.HOLD.candidate } : rowCounts[S];
  const gates = [['ATR_FLOOR', (c) => c.f.vol], ['OVEREXTENSION', (c) => c.f.ov], ['RR>=1.70', (c) => c.f.rr], ['QUALITY', (c) => c.f.q], ['FRESH_15M_CHOCH_VETO', (c) => c.f.fresh], ['30M_TWO_FACTOR_VETO', (c) => c.f.two], ['1H_HTF_VETO', (c) => c.f.htf]];
  let entering = ALLC; D.funnel = { candles: { completed_5m: rc.total, regime_chop: rc.chop, no_model_eligible: rc.noElig, model_eligible_no_setup_or_trigger: rc.noSetup, candidate_candles: rc.candidate }, gates: [] };
  for (const [name, f] of gates) { const pass = entering.filter((x) => f(x.c)), rej = entering.filter((x) => !f(x.c)); const rs = stats(rej, null, { ci: rej.length >= 30 }); const ps = stats(pass, null, { ci: false }); D.funnel.gates.push({ gate: name, entering: entering.length, passing: pass.length, rejected: rej.length, pass_pct: r3(pass.length / Math.max(1, entering.length)), rejected_expectancy_r: rs.expectancy_r ?? null, rejected_pf: rs.pf ?? null, rejected_ci95_r: rs.ci95_r ?? null, rejected_n: rs.n ?? 0, passing_expectancy_r: ps.expectancy_r ?? null, verdict: (rs.n ?? 0) < 30 ? 'INSUFFICIENT' : rs.expectancy_r < -0.05 ? 'PROTECTIVE' : rs.expectancy_r > 0.05 ? 'SUPPRESSES_VALUE' : 'NEUTRAL_FREQUENCY_ONLY' }); entering = pass; }
  D.funnel.final_signals = entering.length;
  // 6. ablation
  const ctlW = seqWalk(SIGS); const ctlS = stats(ctlW.trades, sess); const abl = (name, keep) => { const rows = rowsOf((c) => inSplit(S)(c) && Object.entries(c.f).filter(([k]) => k !== 'all' && k !== keep).every(([, v]) => v)); const w = seqWalk(rows); const s = stats(w.trades, sess); const extra = rows.filter((x) => !x.c.isSig); const es = stats(extra, null, { ci: extra.length >= 30 }); return { name, trades: s.n, extra_signals: extra.length, extra_trades: s.n - ctlS.n, extra_pop_expectancy_r: es.expectancy_r ?? null, extra_pop_pf: es.pf ?? null, extra_pop_ci95_r: es.ci95_r ?? null, extra_pop_win_rate: es.win_rate ?? null, extra_wins: extra.filter((x) => x.o.r > 0).length, extra_losses: extra.filter((x) => x.o.r <= 0).length, expectancy_r: s.expectancy_r, delta_expectancy_r: r3(s.expectancy_r - ctlS.expectancy_r), pf: s.pf, delta_pf: r2(s.pf - ctlS.pf), max_dd_r: s.max_dd_r, delta_dd_r: r2(s.max_dd_r - ctlS.max_dd_r), cost_usd_per_trade: s.cost_usd_per_trade, verdict: (es.n ?? 0) < 30 ? 'INSUFFICIENT' : (s.expectancy_r < ctlS.expectancy_r && s.max_dd_r >= ctlS.max_dd_r) ? 'GATE_USEFUL (removal worsens economics)' : (s.expectancy_r > ctlS.expectancy_r && s.max_dd_r <= ctlS.max_dd_r) ? 'GATE_QUESTIONABLE (removal improves economics)' : 'MIXED' }; };
  D.ablation = { CONTROL: { trades: ctlS.n, expectancy_r: ctlS.expectancy_r, pf: ctlS.pf, max_dd_r: ctlS.max_dd_r, cost_usd_per_trade: ctlS.cost_usd_per_trade }, variants: [abl('CONTROL minus QUALITY', 'q'), abl('CONTROL minus OVEREXTENSION', 'ov'), abl('CONTROL minus 30M_TWO_FACTOR_VETO', 'two'), abl('CONTROL minus 1H_HTF_VETO', 'htf'), abl('CONTROL minus FRESH_CHOCH_VETO', 'fresh'), abl('CONTROL minus ATR_FLOOR', 'vol')] };
  // 7. quality audit (candidates passing everything except quality)
  const qPop = rowsOf((c) => inSplit(S)(c) && c.f.vol && c.f.ov && c.f.rr && c.f.fresh && c.f.two && c.f.htf); const qb = (q) => (q < 55 ? '<55' : q < 65 ? '55-64' : q < 70 ? '65-69' : q < 75 ? '70-74' : q < 80 ? '75-79' : q < 85 ? '80-84' : '>=85');
  D.quality = { buckets: {}, components: {} }; for (const b of ['<55', '55-64', '65-69', '70-74', '75-79', '80-84', '>=85']) D.quality.buckets[b] = cell(qPop.filter((x) => qb(x.c.q_final) === b));
  const comps = ['qStructure', 'qTrigger', 'qEntryLocation', 'qMomentum', 'qVolatility', 'qMtf', 'qSession', 'qRr']; for (const k of comps) { const v = qPop.map((x) => x.c.q_break?.[k] ?? 0).sort((a, b) => a - b); const t1 = v[Math.floor(v.length / 3)], t2 = v[Math.floor((2 * v.length) / 3)]; const lo = qPop.filter((x) => (x.c.q_break?.[k] ?? 0) <= t1), hi = qPop.filter((x) => (x.c.q_break?.[k] ?? 0) >= t2); const sl = stats(lo, null, { ci: false }), sh = stats(hi, null, { ci: false }); D.quality.components[k] = { tercile_cuts: [t1, t2], bottom_n: sl.n, bottom_expectancy_r: sl.expectancy_r, top_n: sh.n, top_expectancy_r: sh.expectancy_r, spread_r: r3((sh.expectancy_r ?? 0) - (sl.expectancy_r ?? 0)), monotonic_helpful: ((sh.expectancy_r ?? 0) - (sl.expectancy_r ?? 0)) >= 0.05 && (t2 > t1) }; }
  D.quality.monotonic_overall = (() => { const b = D.quality.buckets; const seq = ['55-64', '65-69', '70-74', '75-79', '80-84'].map((k) => b[k].expectancy_r).filter((x) => x != null); let up = 0; for (let k = 1; k < seq.length; k++) if (seq[k] > seq[k - 1]) up++; return { increasing_steps: up, steps: seq.length - 1, verdict: seq.length > 2 && up === seq.length - 1 ? 'MONOTONIC' : 'NOT_MONOTONIC' }; })();
  // 8. RR geometry
  const rrPop = rowsOf((c) => inSplit(S)(c) && c.f.vol && c.f.ov); const rrb = (r) => (r < 1 ? '<1.0' : r < 1.25 ? '1.0-1.25' : r < 1.5 ? '1.25-1.50' : r < 1.7 ? '1.50-1.70' : r < 2 ? '1.70-2.0' : r < 2.5 ? '2.0-2.5' : '>2.5'); D.rr = {}; for (const b of ['<1.0', '1.0-1.25', '1.25-1.50', '1.50-1.70', '1.70-2.0', '2.0-2.5', '>2.5']) { const rows = rrPop.filter((x) => rrb(x.c.rr) === b); const st = stats(rowsOf((c) => inSplit(S)(c) && c.f.vol && c.f.ov && rrb(c.rr) === b, 'stress'), null, { ci: false }); D.rr[b] = { ...cell(rows), stress_expectancy_r: st.expectancy_r ?? null }; }
  // 9. entry timing
  const tclass = (c) => (c.overext_atr < 0.15 ? 'EARLY' : c.overext_atr <= 1.0 ? 'WELL_TIMED' : 'LATE_CHASED'); D.timing = { classes: {}, by_model: {}, displacement_quantiles: { p10: r3(pct(SIGS.map((x) => x.c.overext_atr), 0.1)), median: r3(median(SIGS.map((x) => x.c.overext_atr))), p90: r3(pct(SIGS.map((x) => x.c.overext_atr), 0.9)) }, risk_atr_median: r3(median(SIGS.map((x) => x.o.d / x.c.atr))), tp2_atr_median: r3(median(SIGS.map((x) => Math.abs(x.c.geo.tp2 - x.c.geo.entry) / x.c.atr))) };
  for (const k of ['EARLY', 'WELL_TIMED', 'LATE_CHASED']) D.timing.classes[k] = { ...cell(SIGS.filter((x) => tclass(x.c) === k)), mae3_r: r3(mean(SIGS.filter((x) => tclass(x.c) === k).map((x) => x.o.mae3_r))), wrong_direction_loss_share: stats(SIGS.filter((x) => tclass(x.c) === k), null, { ci: false }).wrong_direction_loss_share, right_direction_loss_share: stats(SIGS.filter((x) => tclass(x.c) === k), null, { ci: false }).right_direction_loss_share };
  for (const m of MODELS) D.timing.by_model[m] = Object.fromEntries(['EARLY', 'WELL_TIMED', 'LATE_CHASED'].map((k) => [k, cell(SIGS.filter((x) => x.c.model === m && tclass(x.c) === k))]));
  D.timing.loss_decomposition = { losers: SIGS.filter((x) => x.o.r <= 0).length, wrong_direction: SIGS.filter((x) => x.o.r <= 0 && x.o.mfe_r < 0.25).length, right_direction_poor_timing: SIGS.filter((x) => x.o.r <= 0 && x.o.mfe_r >= 0.5).length, intermediate: SIGS.filter((x) => x.o.r <= 0 && x.o.mfe_r >= 0.25 && x.o.mfe_r < 0.5).length, immediate_adverse_gt_half_r: SIGS.filter((x) => x.o.r <= 0 && x.o.mae3_r >= 0.5).length };
  // 10. move events
  D.moves = moveEvents(S, SIGS, ctlW.occ);
  // 11. false entry forensics
  const losers = SIGS.filter((x) => x.o.r <= 0), winners = SIGS.filter((x) => x.o.r > 0); const dist = (rows, f) => { const g = {}; for (const x of rows) g[String(f(x.c))] = (g[String(f(x.c))] ?? 0) + 1; return Object.fromEntries(Object.entries(g).map(([k, v]) => [k, r3(v / Math.max(1, rows.length))])); };
  D.falseEntries = { losers: losers.length, winners: winners.length, loser_share_immediate_mae3_ge_half_r: r3(losers.filter((x) => x.o.mae3_r >= 0.5).length / Math.max(1, losers.length)), loser_share_no_progress_mfe_lt_quarter_r: r3(losers.filter((x) => x.o.mfe_r < 0.25).length / Math.max(1, losers.length)), loser_avg_bars: r2(mean(losers.map((x) => x.o.bars))), winner_avg_bars: r2(mean(winners.map((x) => x.o.bars))), by: { regime: { losers: dist(losers, (c) => c.rg5), winners: dist(winners, (c) => c.rg5) }, model: { losers: dist(losers, (c) => c.model), winners: dist(winners, (c) => c.model) }, side: { losers: dist(losers, (c) => c.side), winners: dist(winners, (c) => c.side) }, timing: { losers: dist(losers, tclass), winners: dist(winners, tclass) }, quality_bucket: { losers: dist(losers, (c) => qb(c.q_final)), winners: dist(winners, (c) => qb(c.q_final)) }, rr_bucket: { losers: dist(losers, (c) => rrb(c.rr)), winners: dist(winners, (c) => rrb(c.rr)) }, b15d: { losers: dist(losers, (c) => c.b15d), winners: dist(winners, (c) => c.b15d) }, atr_tercile: { losers: dist(losers, (c) => atrBucket(c.atrR)), winners: dist(winners, (c) => atrBucket(c.atrR)) } }, weak_cells: [] };
  const cells = {}; for (const x of SIGS) (cells[`${x.c.model}|${x.c.rg5}|${x.c.side}`] ??= []).push(x); for (const [k, v] of Object.entries(cells)) { const s = stats(v, null, { ci: v.length >= 30 }); if (v.length >= 30 && s.expectancy_r <= -0.30) D.falseEntries.weak_cells.push({ cell: k, n: v.length, expectancy_r: s.expectancy_r, pf: s.pf, ci95_r: s.ci95_r, win_rate: s.win_rate }); }
  D.falseEntries.all_cells_n_ge_30 = Object.entries(cells).filter(([, v]) => v.length >= 30).map(([k, v]) => ({ cell: k, n: v.length, expectancy_r: stats(v, null, { ci: false }).expectancy_r, pf: stats(v, null, { ci: false }).pf })).sort((a, b) => a.expectancy_r - b.expectancy_r);
  // 12. overlap
  const byBar = {}; for (const c of C.filter(inSplit(S))) (byBar[c.i] ??= []).push(c); const multi = Object.values(byBar).filter((v) => v.length >= 2); const pairs = {}; for (const v of multi) { const ms = [...new Set(v.map((c) => c.model))].sort(); if (ms.length >= 2) pairs[ms.join('+')] = (pairs[ms.join('+')] ?? 0) + 1; }
  const agree = SIGS.filter((x) => (byBar[x.c.i] ?? []).some((c) => c.model !== x.c.model && c.side === x.c.side)), conflict = SIGS.filter((x) => (byBar[x.c.i] ?? []).some((c) => c.model !== x.c.model && c.side !== x.c.side)), alone = SIGS.filter((x) => (byBar[x.c.i] ?? []).length === 1);
  const near = SIGS.filter((x) => C.some((c) => c.i !== x.c.i && Math.abs(c.i - x.c.i) <= 3 && c.model !== x.c.model && c.side === x.c.side && inSplit(S)(c)));
  D.overlap = { bars_with_candidates: Object.keys(byBar).length, bars_with_2plus_models: multi.length, pair_counts: pairs, signals_with_same_bar_agreement: cell(agree), signals_with_same_bar_conflict: cell(conflict), signals_alone: cell(alone), signals_with_agreement_within_3_bars: cell(near), signals_without_agreement_within_3_bars: cell(SIGS.filter((x) => !near.includes(x))), duplicate_theses_same_bar_same_side: SIGS.filter((x) => (byBar[x.c.i] ?? []).filter((c) => c.isSig && c.side === x.c.side).length >= 2).length };
  return D;
}
// ATR14 (simple mean TR) for move events
const ATR14 = new Array(b5.length).fill(null); { let sum = 0; const tr = []; for (let k = 1; k < b5.length; k++) { const t = Math.max(b5[k].high - b5[k].low, Math.abs(b5[k].high - b5[k - 1].close), Math.abs(b5[k].low - b5[k - 1].close)); tr.push(t); sum += t; if (tr.length > 14) sum -= tr[tr.length - 15]; if (tr.length >= 14) ATR14[k] = sum / 14; } }
function moveEvents(S, SIGS, occ, extraSets = {}) {
  const sigBy = {}; for (const x of SIGS) (sigBy[x.c.i] ??= []).push(x.c.side); const setsBy = {}; for (const [name, rows] of Object.entries(extraSets)) { setsBy[name] = {}; for (const x of rows) (setsBy[name][x.c.i] ??= []).push(x.c.side); }
  const events = []; let k = 500; const lo = S === 'DEV' ? SPLIT.dev[0] : S === 'HOLD' ? SPLIT.hold[0] : SPLIT.dev[0], hi = S === 'DEV' ? SPLIT.dev[1] : S === 'HOLD' ? SPLIT.hold[1] : SPLIT.hold[1];
  while (k < b5.length - 25) { const d = day(b5[k].time); if (d < lo) { k++; continue; } if (d > hi) break; const a = ATR14[k]; if (!a) { k++; continue; } const c0 = b5[k].close; let up = null, dn = null; let maxH = -Infinity, minL = Infinity; for (let j = k + 1; j <= k + 24; j++) { const b = b5[j]; if (b.time - b5[j - 1].time > GAP) break; maxH = Math.max(maxH, b.high); minL = Math.min(minL, b.low); if (up == null && maxH - c0 >= 3 * a && c0 - minL <= a) up = j; if (dn == null && c0 - minL >= 3 * a && maxH - c0 <= a) dn = j; if (up != null || dn != null) break; }
    if (up != null || dn != null) { const dir = up != null ? 'BUY' : 'SELL'; const cap = (by) => { for (let j = k - 6; j <= k + 6; j++) if ((by[j] ?? []).includes(dir)) return true; return false; }; const row = ROWS.get(k); let blocker = 'OTHER'; if (cap(sigBy)) { blocker = occ.some(([a, b]) => k > a && k <= b && !sigBy[k]) ? 'CAPTURED' : 'CAPTURED'; } else { const inPos = occ.some(([a, b]) => k >= a && k <= b); const sigHere = [];
        for (let j = k - 6; j <= k + 6; j++) for (const s of sigBy[j] ?? []) sigHere.push(s); if (sigHere.some((s) => s !== dir)) blocker = 'OPPOSITE_SIGNAL'; else if (inPos) blocker = 'ALREADY_POSITIONED'; else if (!row) blocker = 'OTHER'; else if (row.wr === 'CHOP') blocker = 'REGIME_CHOP'; else if (row.wr === 'NO_ELIGIBLE_STRATEGY') blocker = row.elig ? 'NO_SETUP_OR_TRIGGER' : 'NO_MODEL_ELIGIBLE'; else if (row.wr === 'VOLATILITY_INSUFFICIENT') blocker = 'ATR_FLOOR'; else if (row.wr === 'OVEREXTENDED') blocker = 'OVEREXTENSION'; else if (row.wr === 'RR_NOT_ACCEPTABLE') blocker = 'RR'; else if (row.wr === 'NO_GOOD_ENTRY') blocker = 'QUALITY'; else if (row.wr === 'ENTRY_CONFLICT' || row.wr === 'HTF_CONFLICT') blocker = 'MTF'; else if (row.wr === 'INVALID_GEOMETRY') blocker = 'GEOMETRY'; else blocker = `OTHER:${row.wr ?? row.act}`; }
      const ev = { k, t: b5[k].time, dir, atr: r3(a), bars_to_3atr: (up ?? dn) - k, blocker, rg5: row?.rg5 ?? null }; for (const name of Object.keys(setsBy)) ev[`captured_${name}`] = cap(setsBy[name]); events.push(ev); k += 24; } else k++; }
  const dist = {}; for (const e of events) dist[e.blocker] = (dist[e.blocker] ?? 0) + 1; const captured = events.filter((e) => e.blocker === 'CAPTURED').length; const out = { events: events.length, captured, move_capture_rate: r3(captured / Math.max(1, events.length)), missed_move_rate: r3(1 - captured / Math.max(1, events.length)), first_blocker_distribution: Object.fromEntries(Object.entries(dist).sort((a, b) => b[1] - a[1])), by_direction: { BUY: events.filter((e) => e.dir === 'BUY').length, SELL: events.filter((e) => e.dir === 'SELL').length }, by_regime: Object.fromEntries(Object.entries(events.reduce((g, e) => { g[e.rg5] = (g[e.rg5] ?? 0) + 1; return g; }, {}))), sample_events: events.slice(0, 20).map((e) => ({ ...e, t: iso(e.t) })) }; for (const name of Object.keys(setsBy)) out[`capture_rate_${name}`] = r3(events.filter((e) => e[`captured_${name}`]).length / Math.max(1, events.length)); return out;
}

// ---------- candidate derivation (DEV only; mechanical) ----------
function deriveCandidates(D) {
  const supported = MODELS.filter((m) => { const s = D.decomposition[m].signals_all; return s.n >= 100 && s.expectancy_r > 0 && s.pf > 1.0; });
  const regimes = {}; for (const m of supported) regimes[m] = Object.entries(D.matrix.by_5m_regime[m]).filter(([, v]) => v.n >= 50 && v.expectancy_r > 0).map(([k]) => k);
  const keptComponents = Object.entries(D.quality.components).filter(([, v]) => v.monotonic_helpful).map(([k]) => k);
  const devRows = rowsOf((c) => c.split === 'DEV' && c.f.vol && c.f.ov && c.f.rr && c.f.fresh && c.f.two && c.f.htf && supported.includes(c.model)); const simpleScore = (c) => keptComponents.reduce((s, k) => s + (c.q_break?.[k] ?? 0), 0); const qThreshold = keptComponents.length ? median(devRows.map((x) => simpleScore(x.c))) : null;
  const c1 = rowsOf((c) => c.split === 'DEV' && c.isSig && supported.includes(c.model)); const base = stats(c1, null, { ci: false }).expectancy_r ?? -Infinity; const XS = [0.5, 0.75, 1.0, 1.25, 1.5]; const ex = XS.map((X) => ({ X, exp: stats(c1.filter((x) => x.c.overext_atr <= X), null, { ci: false }).expectancy_r ?? -Infinity })); let best = null; for (let k = 0; k < ex.length; k++) { const nb = [ex[k - 1], ex[k + 1]].filter(Boolean); if (ex[k].exp > base && nb.every((n) => n.exp > base) && (!best || ex[k].exp > best.exp)) best = ex[k]; }
  return { derived_from: 'DEV', supported_models: supported, c2_regimes: regimes, c3_components: keptComponents, c3_threshold: r3(qThreshold), c4_X: best ? best.X : null, c4_scan: ex.map((e) => ({ X: e.X, dev_expectancy_r: r3(e.exp) })), c1_dev_expectancy_r: r3(base), c5_window_bars: 3 };
}
function candidateRows(defn, name, S, cse = 'normal') { const sup = defn.supported_models; const keptSum = (c) => defn.c3_components.reduce((s, k) => s + (c.q_break?.[k] ?? 0), 0); const near = (c) => C.some((d) => d.i !== c.i && Math.abs(d.i - c.i) <= defn.c5_window_bars && d.model !== c.model && d.side === c.side);
  const pred = { C0: (c) => c.isSig, C1: (c) => c.isSig && sup.includes(c.model), C2: (c) => c.isSig && sup.includes(c.model) && (defn.c2_regimes[c.model] ?? []).includes(c.rg5), C3: (c) => sup.includes(c.model) && c.f.vol && c.f.ov && c.f.rr && c.f.fresh && c.f.two && c.f.htf && defn.c3_threshold != null && keptSum(c) >= defn.c3_threshold, C4: (c) => c.isSig && sup.includes(c.model) && (defn.c4_X == null || c.overext_atr <= defn.c4_X), C5: (c) => c.isSig && sup.includes(c.model) && near(c) }[name];
  return rowsOf((c) => inSplit(S)(c) && pred(c), cse); }
function evaluateCandidate(defn, name, S) { const sess = sessions[S]; const rows = candidateRows(defn, name, S); const w = seqWalk(rows); const st = stats(w.trades, sess, { block: true }); const stress = stats(seqWalk(candidateRows(defn, name, S, 'stress')).trades, null, { ci: false }); const drift = stats(seqWalk(candidateRows(defn, name, S, 'drift')).trades, null, { ci: false }); const q = {}; for (const x of w.trades) (q[quarter(x.c.t)] ??= []).push(x); const walk = Object.fromEntries(Object.entries(q).sort().map(([k, v]) => { const s = stats(v, null, { ci: false }); return [k, { n: s.n, expectancy_r: s.expectancy_r, pf: s.pf, max_dd_r: s.max_dd_r }]; })); const pos = Object.values(walk).filter((v) => v.expectancy_r > 0).length;
  const shuffle = (() => { if (!w.trades.length) return null; const rand = rng(11); const byM = {}; for (const x of w.trades) (byM[month(x.c.t)] ??= []).push(x.o.r); const dds = [], streaks = []; for (let k = 0; k < 500; k++) { const order = Object.values(byM).sort(() => rand() - 0.5); let cum = 0, peak = 0, dd = 0, st = 0, ms = 0; for (const m of order) for (const r of [...m].sort(() => rand() - 0.5)) { cum += r; peak = Math.max(peak, cum); dd = Math.max(dd, peak - cum); if (r <= 0) { st++; ms = Math.max(ms, st); } else st = 0; } dds.push(dd); streaks.push(ms); } return { dd_r_p50: r2(median(dds)), dd_r_p90: r2(pct(dds, 0.9)), dd_r_p99: r2(pct(dds, 0.99)), loss_streak_p50: median(streaks), loss_streak_p90: pct(streaks, 0.9) }; })();
  return { signals: rows.length, ...st, skipped: w.skipped, stress: { n: stress.n, expectancy_r: stress.expectancy_r, pf: stress.pf }, drift: { n: drift.n, expectancy_r: drift.expectancy_r, pf: drift.pf }, walk_forward: walk, quarters_positive_share: Object.keys(walk).length ? r3(pos / Object.keys(walk).length) : null, month_shuffle: shuffle }; }
function stabilityScan(defn, S) { const out = { c3_threshold: {}, c4_X: {} }; if (defn.c3_threshold != null) for (const dt of [-5, 0, 5]) { const d2 = { ...defn, c3_threshold: defn.c3_threshold + dt }; const s = stats(seqWalk(candidateRows(d2, 'C3', S)).trades, null, { ci: false }); out.c3_threshold[String(defn.c3_threshold + dt)] = { n: s.n, expectancy_r: s.expectancy_r, pf: s.pf }; } if (defn.c4_X != null) for (const X of [defn.c4_X - 0.25, defn.c4_X, defn.c4_X + 0.25]) { const d2 = { ...defn, c4_X: X }; const s = stats(seqWalk(candidateRows(d2, 'C4', S)).trades, null, { ci: false }); out.c4_X[String(X)] = { n: s.n, expectancy_r: s.expectancy_r, pf: s.pf }; } return out; }

// ---------- run ----------
const result = { meta: { phase: PHASE, generated_utc: new Date().toISOString(), prereg_sha256: PREREG_SHA, controls: ctrl, candidates: C.length, signals: C.filter((c) => c.isSig).length, signals_dev: C.filter((c) => c.isSig && c.split === 'DEV').length, signals_hold: C.filter((c) => c.isSig && c.split === 'HOLD').length, sessions_dev: sessions.DEV.size, sessions_hold: sessions.HOLD.size, rows: rowCounts, costs: COSTS, split: SPLIT, bars: b5.length, bars_first: iso(b5[0].time), bars_last: iso(b5.at(-1).time) } };
console.log('diagnostics DEV ...'); result.DEV = diagnostics('DEV');
const defPath = join(OUT, 'candidate_definitions.json');
if (PHASE === 'DEV') { const defn = deriveCandidates(result.DEV); writeFileSync(defPath, JSON.stringify(defn, null, 1)); result.candidate_definitions = defn; result.candidates_DEV = Object.fromEntries(['C0', 'C1', 'C2', 'C3', 'C4', 'C5'].map((n) => [n, evaluateCandidate(defn, n, 'DEV')])); result.candidates_DEV_stability = stabilityScan(defn, 'DEV'); writeFileSync(join(OUT, 'edge_results_DEV_phase.json'), JSON.stringify(result, null, 1)); console.log('DERIVED', JSON.stringify(defn)); console.log('candidate_definitions.json sha256', createHash('sha256').update(readFileSync(defPath)).digest('hex')); }
else { const defn = JSON.parse(readFileSync(defPath, 'utf8')); const frozen = readFileSync(join(OUT, 'candidate_definitions.sha256'), 'utf8').trim().split(/\s+/)[0]; if (createHash('sha256').update(readFileSync(defPath)).digest('hex') !== frozen) throw new Error('candidate_definitions.json does not match its frozen hash'); result.candidate_definitions = defn; result.candidate_definitions_sha256 = frozen;
  console.log('diagnostics HOLD ...'); result.HOLD = diagnostics('HOLD'); console.log('diagnostics ALL ...'); result.ALL = diagnostics('ALL');
  result.candidates = {}; for (const S of ['DEV', 'HOLD']) { result.candidates[S] = Object.fromEntries(['C0', 'C1', 'C2', 'C3', 'C4', 'C5'].map((n) => [n, evaluateCandidate(defn, n, S)])); result.candidates[`${S}_stability`] = stabilityScan(defn, S); }
  // move capture for candidate sets on HOLD
  const holdSigs = sigRows('HOLD'); const occ = seqWalk(holdSigs).occ; result.HOLD.moves = moveEvents('HOLD', holdSigs, occ, Object.fromEntries(['C1', 'C2', 'C3', 'C4', 'C5'].map((n) => [n, candidateRows(defn, n, 'HOLD')])));
  // decisions
  const H = result.candidates.HOLD, ctl = H.C0; const dec = {}; for (const n of ['C1', 'C2', 'C3', 'C4', 'C5']) { const c = H[n]; const reasons = []; if (!c.n || c.n < 200) reasons.push('N<200'); if (!(c.expectancy_r > 0)) reasons.push('expectancy<=0'); if (!(c.ci95_r?.[0] > 0)) reasons.push('trade CI includes 0'); if (!(c.session_block_ci95_r?.[0] > 0)) reasons.push('session-block CI includes 0'); if (!(c.pf > 1.10)) reasons.push('PF<=1.10'); if (!(c.max_dd_r <= ctl.max_dd_r)) reasons.push('DD worse than CONTROL'); if ((c.top5_share ?? 1) > 0.3) reasons.push('top5>30%'); if (!((c.quarters_positive_share ?? 0) >= 0.6)) reasons.push('quarters positive <60%'); if (!(c.stress.expectancy_r > 0)) reasons.push('stress<=0'); if (!(c.drift.expectancy_r > 0)) reasons.push('drift<=0'); if (!(result.candidates.DEV[n].expectancy_r > 0)) reasons.push('DEV<=0'); if (n === 'C3' && Object.values(result.candidates.HOLD_stability.c3_threshold).some((v) => !(v.expectancy_r > 0))) reasons.push('C3 neighbours not all positive'); if (n === 'C4' && defn.c4_X != null && Object.values(result.candidates.HOLD_stability.c4_X).some((v) => !(v.expectancy_r > 0))) reasons.push('C4 neighbours not all positive'); dec[n] = { status: reasons.length ? 'FAILS_FINALIST_REQUIREMENTS' : 'FINALIST_QUALIFIED', reasons, hold_expectancy_r: c.expectancy_r, hold_pf: c.pf, hold_n: c.n, session_block_ci95_r: c.session_block_ci95_r }; }
  const qualified = Object.entries(dec).filter(([, d]) => d.status === 'FINALIST_QUALIFIED').sort((a, b) => (H[b[0]].session_block_ci95_r?.[0] ?? -9) - (H[a[0]].session_block_ci95_r?.[0] ?? -9)); const finalist = qualified[0]?.[0] ?? null;
  const anyPosCiSpan = ['C0', 'C1', 'C2', 'C3', 'C4', 'C5'].some((n) => H[n].n >= 200 && H[n].expectancy_r > 0 && !(H[n].ci95_r?.[0] > 0));
  result.decisions = { candidates: dec, finalist, edge_demonstrated: finalist ? 'YES' : anyPosCiSpan ? 'INCONCLUSIVE' : 'NO', finalist_beats_control: finalist ? ((H[finalist].ci95_r[0] > ctl.expectancy_r && H[finalist].max_dd_r <= ctl.max_dd_r) ? 'YES' : (H[finalist].expectancy_r > ctl.expectancy_r ? 'INCONCLUSIVE' : 'NO')) : 'NO', demo_eligible: finalist ? 'YES (subject to parity + P1 checks)' : 'NO' };
  writeFileSync(join(OUT, 'edge_results.json'), JSON.stringify(result, null, 1)); console.log('DECISIONS', JSON.stringify(result.decisions, null, 1)); }
console.log('written', PHASE);
