// Generates the machine-derived markdown documents of handoff/ENTRY_ENGINE_EDGE_V1 from results/edge_results.json.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const HERE = dirname(fileURLToPath(import.meta.url)); const REPO = join(HERE, '..', '..', '..'); const R = JSON.parse(readFileSync(join(REPO, 'research', 'entry_engine_edge_v1', 'results', 'edge_results.json'), 'utf8')); const OUT = join(REPO, 'handoff', 'ENTRY_ENGINE_EDGE_V1'); mkdirSync(OUT, { recursive: true });
const MODELS = ['MC', 'PB', 'BO', 'SR', 'MR']; const f = (x, d = 3) => (x == null ? '—' : typeof x === 'number' ? (Number.isInteger(x) ? String(x) : x.toFixed(d)) : String(x)); const ci = (c) => (c ? `[${f(c[0])}, ${f(c[1])}]` : '—'); const pc = (x) => (x == null ? '—' : `${(x * 100).toFixed(1)} %`);
const statRow = (s) => (!s || !s.n ? '| 0 | | | | | | | | | | | | |' : `| ${s.n} | ${s.independent_n ?? '—'} | ${pc(s.win_rate)} | ${f(s.avg_win_r, 2)} / ${f(s.avg_loss_r, 2)} | **${f(s.expectancy_r)}** | ${f(s.expectancy_usd, 2)} | ${ci(s.ci95_r)} | ${f(s.pf, 2)} | ${f(s.max_dd_r, 1)} | ${f(s.mfe_r_mean, 2)} / ${f(s.mae_r_mean, 2)} | ${f(s.avg_bars, 1)} | ${f(s.cost_usd_per_trade, 2)} (${f(s.cost_r_per_trade, 3)} R) | ${s.max_loss_streak ?? '—'} |`);
const HDR = '| N | Independent | Win rate | Avg win / loss (R) | Expectancy (R) | Expectancy (USD, 0.01 lot) | 95 % CI (R) | PF | Max DD (R) | MFE / MAE (R) | Avg bars | Cost/trade | Loss streak |';
const SEP = '|---|---|---|---|---|---|---|---|---|---|---|---|---|';
const S2 = ['DEV', 'HOLD'];
// 1. decomposition
let md = `# CURRENT MODEL DECOMPOSITION (EXIT_F, normal costs; DEVELOPMENT ${R.meta.split.dev.join(' → ')} and HOLDOUT ${R.meta.split.hold.join(' → ')})\n\nR = structural stop distance; USD = R × distance at 0.01 lot. "Signals" = production BUY/SELL of that model (per-signal outcomes); "executable only this model" = one-position sequential walk with the frozen re-entry guard using only that model.\n`;
for (const S of S2) { md += `\n## ${S}\n### Funnel per model\n| Model | Candidates | ATR floor | Overextension | RR ≥ 1.70 | Quality | Fresh CHoCH | 30m two-factor | 1H | Signals |\n|---|---|---|---|---|---|---|---|---|---|\n`; for (const m of MODELS) { const u = R[S].decomposition[m].funnel; md += `| ${m} | ${u.candidates} | ${u.pass_atr_floor} | ${u.pass_overextension} | ${u.pass_rr} | ${u.pass_quality} | ${u.pass_fresh_choch} | ${u.pass_two_factor} | ${u.pass_htf} | ${u.signals} |\n`; }
  md += `\n### Signals (all sides)\n| Model ${HDR}\n|---${SEP}\n`; for (const m of MODELS) md += `| ${m} ${statRow(R[S].decomposition[m].signals_all)}\n`;
  md += `\n### LONG\n| Model ${HDR}\n|---${SEP}\n`; for (const m of MODELS) md += `| ${m} ${statRow(R[S].decomposition[m].signals_long)}\n`;
  md += `\n### SHORT\n| Model ${HDR}\n|---${SEP}\n`; for (const m of MODELS) md += `| ${m} ${statRow(R[S].decomposition[m].signals_short)}\n`;
  md += `\n### Executable trades, one model alone (sequential, one position)\n| Model ${HDR} Zero-trade sessions | Trades/session median |\n|---${SEP}---|---|\n`; for (const m of MODELS) { const s = R[S].decomposition[m].executable_only_this_model; md += `| ${m} ${statRow(s)} ${pc(s.zero_trade_session_rate)} | ${s.trades_per_session?.median ?? '—'} |\n`; } }
writeFileSync(join(OUT, 'CURRENT_MODEL_DECOMPOSITION.md'), md);
// 2. contribution
md = `# MODEL CONTRIBUTION (sequential one-position portfolios on production signals, EXIT_F, normal costs)\n`;
for (const S of S2) { md += `\n## ${S}\n| Portfolio ${HDR} Regimes covered | Zero-trade sessions |\n|---${SEP}---|---|\n`; for (const k of Object.keys(R[S].contribution)) { const s = R[S].contribution[k]; md += `| ${k} ${statRow(s)} ${s.regimes_covered} | ${pc(s.zero_trade_session_rate)} |\n`; } const all = R[S].contribution.ALL; md += `\nMarginal value of each model (ALL minus NO_x): ${MODELS.map((m) => { const n = R[S].contribution[`NO_${m}`]; return `${m}: Δexp ${f(all.expectancy_r - n.expectancy_r)} R, ΔPF ${f(all.pf - n.pf, 2)}, ΔDD ${f(all.max_dd_r - n.max_dd_r, 1)} R, Δtrades ${all.n - n.n}`; }).join('; ')}.\n`; }
writeFileSync(join(OUT, 'MODEL_CONTRIBUTION.md'), md);
// 3. matrix
md = `# REGIME × MODEL MATRIX (production signals, per-signal EXIT_F outcomes; cells with N < 30 marked INSUFFICIENT)\n`;
const cellRow = (k, v) => `| ${k} | ${v.n} ${v.sample === 'INSUFFICIENT' ? '(INSUFFICIENT)' : ''} | ${pc(v.win_rate)} | ${f(v.avg_win_r, 2)} / ${f(v.avg_loss_r, 2)} | ${f(v.expectancy_r)} | ${f(v.pf, 2)} | ${f(v.mfe_r, 2)} / ${f(v.mae_r, 2)} | ${f(v.cost_r)} | ${ci(v.ci95_r)} |`;
for (const S of S2) { md += `\n## ${S}\n`; for (const [title, key] of [['5m regime', 'by_5m_regime'], ['15m bias', 'by_15m_bias'], ['30m regime', 'by_30m_regime'], ['1H regime', 'by_1h_regime'], [`ATR-ratio tercile (cuts ${R[S].matrix.atr_terciles.join(' / ')})`, 'by_atr_tercile']]) { md += `\n### ${title}\n`; for (const m of MODELS) { md += `\n**${m}** (opportunities by 5m regime: ${Object.entries(R[S].matrix.opportunities_by_5m_regime[m]).map(([k, v]) => `${k} ${v}`).join(', ')})\n\n| Segment | N | Win rate | Avg win / loss (R) | Expectancy (R) | PF | MFE / MAE (R) | Cost (R) | 95 % CI |\n|---|---|---|---|---|---|---|---|---|\n`; for (const [k, v] of Object.entries(R[S].matrix[key][m]).sort((a, b) => b[1].n - a[1].n)) md += cellRow(k, v) + '\n'; } } }
writeFileSync(join(OUT, 'REGIME_MODEL_MATRIX.md'), md);
// 4. directional
md = `# DIRECTIONAL ANALYSIS (LONG vs SHORT, production signals, EXIT_F)\n`;
for (const S of S2) { md += `\n## ${S}\n| Model | Side | N | Expectancy (R) | 95 % CI | PF | Win rate | Max DD (R) | MAE (R) | MFE (R) | Stress expectancy (R) | Cost/trade (USD) |\n|---|---|---|---|---|---|---|---|---|---|---|---|\n`; for (const m of [...MODELS, 'ALL']) for (const side of ['LONG', 'SHORT']) { const v = R[S].directional[m][side]; md += `| ${m} | ${side} | ${v.n ?? 0} | ${f(v.expectancy_r)} | ${ci(v.ci95_r)} | ${f(v.pf, 2)} | ${pc(v.win_rate)} | ${f(v.max_dd_r, 1)} | ${f(v.mae_r_mean, 2)} | ${f(v.mfe_r_mean, 2)} | ${f(v.stress_expectancy_r)} | ${f(v.cost_usd_per_trade, 2)} |\n`; } md += `\nAsymmetry (LONG − SHORT expectancy, R): ${[...MODELS, 'ALL'].map((m) => `${m} ${f(R[S].directional[m].asymmetry_r)}`).join(', ')}.\n`; }
writeFileSync(join(OUT, 'DIRECTIONAL_ANALYSIS.md'), md);
// 5. funnel
md = `# SIGNAL FUNNEL ATTRIBUTION\n\nCandle level from the replay rows; candidate level from the frozen gate flags in production order. "Rejected expectancy" = EXIT_F economics of the population the gate removes (independent per-candidate outcomes). Verdict: PROTECTIVE if the rejected population loses ≤ −0.05 R, SUPPRESSES_VALUE if it earns ≥ +0.05 R, otherwise NEUTRAL (frequency only). Safety gates (news, spread, drift, breaker, identity) are outside the replay and identical for every candidate.\n`;
for (const S of S2) { const u = R[S].funnel; md += `\n## ${S}\n| Stage | Count |\n|---|---|\n| Completed 5m candles | ${u.candles.completed_5m} |\n| Regime CHOP (WAIT) | ${u.candles.regime_chop} |\n| No model eligible (15m bias) | ${u.candles.no_model_eligible} |\n| Model eligible, no setup/trigger | ${u.candles.model_eligible_no_setup_or_trigger} |\n| Candidate candles (setup + trigger) | ${u.candles.candidate_candles} |\n\n| Gate | Entering | Passing | Rejected | Pass % | Rejected N | Rejected expectancy (R) | Rejected PF | Rejected 95 % CI | Passing expectancy (R) | Verdict |\n|---|---|---|---|---|---|---|---|---|---|---|\n`; for (const g of u.gates) md += `| ${g.gate} | ${g.entering} | ${g.passing} | ${g.rejected} | ${pc(g.pass_pct)} | ${g.rejected_n} | ${f(g.rejected_expectancy_r)} | ${f(g.rejected_pf, 2)} | ${ci(g.rejected_ci95_r)} | ${f(g.passing_expectancy_r)} | ${g.verdict} |\n`; md += `| FINAL SIGNALS | | ${u.final_signals} | | | | | | | | |\n`; }
writeFileSync(join(OUT, 'SIGNAL_FUNNEL.md'), md);
// 6. ablation
md = `# GATE ABLATION (one change at a time; sequential one-position portfolio; safety gates never ablated)\n`;
for (const S of S2) { const a = R[S].ablation; md += `\n## ${S}\nCONTROL: trades ${a.CONTROL.trades}, expectancy ${f(a.CONTROL.expectancy_r)} R, PF ${f(a.CONTROL.pf, 2)}, max DD ${f(a.CONTROL.max_dd_r, 1)} R, cost ${f(a.CONTROL.cost_usd_per_trade, 2)} USD/trade.\n\n| Ablation | Extra signals | Extra trades | Extra wins / losses | Extra-pop expectancy (R) | Extra-pop 95 % CI | Extra-pop PF | Portfolio expectancy (R) | Δ expectancy | Portfolio PF | Δ PF | Max DD (R) | Δ DD | Cost/trade | Verdict |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n`; for (const v of a.variants) md += `| ${v.name} | ${v.extra_signals} | ${v.extra_trades} | ${v.extra_wins} / ${v.extra_losses} | ${f(v.extra_pop_expectancy_r)} | ${ci(v.extra_pop_ci95_r)} | ${f(v.extra_pop_pf, 2)} | ${f(v.expectancy_r)} | ${f(v.delta_expectancy_r)} | ${f(v.pf, 2)} | ${f(v.delta_pf, 2)} | ${f(v.max_dd_r, 1)} | ${f(v.delta_dd_r, 1)} | ${f(v.cost_usd_per_trade, 2)} | ${v.verdict} |\n`; }
writeFileSync(join(OUT, 'GATE_ABLATION.md'), md);
// 7. quality
md = `# QUALITY SCORE AUDIT (candidates passing every production gate except quality; EXIT_F)\n`;
for (const S of S2) { const q = R[S].quality; md += `\n## ${S}\n| Quality bucket | N | Win rate | Expectancy (R) | PF | MFE / MAE (R) | Cost (R) | 95 % CI |\n|---|---|---|---|---|---|---|---|\n`; for (const [k, v] of Object.entries(q.buckets)) md += `| ${k} | ${v.n} ${v.sample === 'INSUFFICIENT' ? '(INSUFFICIENT)' : ''} | ${pc(v.win_rate)} | ${f(v.expectancy_r)} | ${f(v.pf, 2)} | ${f(v.mfe_r, 2)} / ${f(v.mae_r, 2)} | ${f(v.cost_r)} | ${ci(v.ci95_r)} |\n`; md += `\nMonotonic with expectancy: **${q.monotonic_overall.verdict}** (${q.monotonic_overall.increasing_steps} of ${q.monotonic_overall.steps} bucket steps increase).\n\n| Component | Tercile cuts | Bottom N / expectancy (R) | Top N / expectancy (R) | Top − bottom (R) | Helpful (≥ +0.05 R) |\n|---|---|---|---|---|---|\n`; for (const [k, v] of Object.entries(q.components)) md += `| ${k} | ${v.tercile_cuts.join(' / ')} | ${v.bottom_n} / ${f(v.bottom_expectancy_r)} | ${v.top_n} / ${f(v.top_expectancy_r)} | ${f(v.spread_r)} | ${v.monotonic_helpful ? 'YES' : 'no'} |\n`; }
writeFileSync(join(OUT, 'QUALITY_AUDIT.md'), md);
// 8. rr
md = `# RR GEOMETRY AUDIT (candidates reaching the RR evaluation: ATR floor and overextension passed; EXIT_F; RR 1.70 stays the CONTROL)\n`;
for (const S of S2) { md += `\n## ${S}\n| Effective RR bucket | N | Win rate | Expectancy (R) | PF | MFE / MAE (R) | 95 % CI | Stress expectancy (R) |\n|---|---|---|---|---|---|---|---|\n`; for (const [k, v] of Object.entries(R[S].rr)) md += `| ${k} | ${v.n} ${v.sample === 'INSUFFICIENT' ? '(INSUFFICIENT)' : ''} | ${pc(v.win_rate)} | ${f(v.expectancy_r)} | ${f(v.pf, 2)} | ${f(v.mfe_r, 2)} / ${f(v.mae_r, 2)} | ${ci(v.ci95_r)} | ${f(v.stress_expectancy_r)} |\n`; }
writeFileSync(join(OUT, 'RR_GEOMETRY.md'), md);
// 9. timing
md = `# ENTRY TIMING AUDIT (production signals; displacement from the model anchor in ATR: EARLY < 0.15, WELL_TIMED 0.15–1.0, LATE/CHASED > 1.0; frozen definitions)\n`;
for (const S of S2) { const t = R[S].timing; md += `\n## ${S}\nDisplacement quantiles P10 / median / P90: ${t.displacement_quantiles.p10} / ${t.displacement_quantiles.median} / ${t.displacement_quantiles.p90} ATR; structural stop median ${t.risk_atr_median} ATR; TP2 distance median ${t.tp2_atr_median} ATR.\n\n| Class | N | Win rate | Expectancy (R) | PF | MFE / MAE (R) | MAE within 3 bars (R) | Wrong-direction loss share | Right-direction loss share | 95 % CI |\n|---|---|---|---|---|---|---|---|---|---|\n`; for (const [k, v] of Object.entries(t.classes)) md += `| ${k} | ${v.n} | ${pc(v.win_rate)} | ${f(v.expectancy_r)} | ${f(v.pf, 2)} | ${f(v.mfe_r, 2)} / ${f(v.mae_r, 2)} | ${f(v.mae3_r, 2)} | ${pc(v.wrong_direction_loss_share)} | ${pc(v.right_direction_loss_share)} | ${ci(v.ci95_r)} |\n`; const L = t.loss_decomposition; md += `\nLoss decomposition: ${L.losers} losers; wrong direction (MFE < 0.25 R) ${L.wrong_direction} (${pc(L.wrong_direction / L.losers)}); right direction but poor timing/exit (MFE ≥ 0.5 R) ${L.right_direction_poor_timing} (${pc(L.right_direction_poor_timing / L.losers)}); intermediate ${L.intermediate}; immediate adverse excursion ≥ 0.5 R within 3 bars ${L.immediate_adverse_gt_half_r} (${pc(L.immediate_adverse_gt_half_r / L.losers)}).\n\n| Model | EARLY N / exp | WELL_TIMED N / exp | LATE_CHASED N / exp |\n|---|---|---|---|\n`; for (const m of MODELS) { const b = t.by_model[m]; md += `| ${m} | ${b.EARLY.n} / ${f(b.EARLY.expectancy_r)} | ${b.WELL_TIMED.n} / ${f(b.WELL_TIMED.expectancy_r)} | ${b.LATE_CHASED.n} / ${f(b.LATE_CHASED.expectancy_r)} |\n`; } }
writeFileSync(join(OUT, 'ENTRY_TIMING.md'), md);
// 10. moves
md = `# MISSED MOVE FORENSICS (retrospective move events: ≥ 3 × ATR14 favourable within 24 bars before 1 × ATR14 adverse; non-overlapping; capture = same-direction CONTROL signal within ± 6 bars)\n`;
for (const S of S2) { const m = R[S].moves; md += `\n## ${S}\nEvents ${m.events} (BUY ${m.by_direction.BUY}, SELL ${m.by_direction.SELL}); captured ${m.captured}; **MOVE_CAPTURE_RATE ${pc(m.move_capture_rate)}**, MISSED_MOVE_RATE ${pc(m.missed_move_rate)}.\n\n| First blocker | Events | Share |\n|---|---|---|\n${Object.entries(m.first_blocker_distribution).map(([k, v]) => `| ${k} | ${v} | ${pc(v / m.events)} |`).join('\n')}\n\nEvents by 5m regime at onset: ${Object.entries(m.by_regime).map(([k, v]) => `${k} ${v}`).join(', ')}.\n${Object.entries(m).filter(([k]) => k.startsWith('capture_rate_')).map(([k, v]) => `${k}: ${pc(v)}`).join('; ')}\n\nSample events (first 20): ${m.sample_events.map((e) => `${e.t.slice(0, 16)} ${e.dir} ${e.blocker}`).join('; ')}\n`; }
writeFileSync(join(OUT, 'MISSED_MOVE_FORENSICS.md'), md);
// 11. false entries
md = `# FALSE ENTRY FORENSICS (losing production signals under EXIT_F)\n`;
for (const S of S2) { const fe = R[S].falseEntries; md += `\n## ${S}\nLosers ${fe.losers}, winners ${fe.winners}. Loser share with immediate adverse excursion ≥ 0.5 R within 3 bars: ${pc(fe.loser_share_immediate_mae3_ge_half_r)}; loser share that never progressed 0.25 R: ${pc(fe.loser_share_no_progress_mfe_lt_quarter_r)}; average bars losers / winners ${fe.loser_avg_bars} / ${fe.winner_avg_bars}.\n\n| Attribute | Losers distribution | Winners distribution |\n|---|---|---|\n${Object.entries(fe.by).map(([k, v]) => `| ${k} | ${Object.entries(v.losers).map(([a, b]) => `${a} ${pc(b)}`).join(', ')} | ${Object.entries(v.winners).map(([a, b]) => `${a} ${pc(b)}`).join(', ')} |`).join('\n')}\n\n### Systematic weak populations (model × 5m regime × side, N ≥ 30, expectancy ≤ −0.30 R)\n| Cell | N | Expectancy (R) | PF | Win rate | 95 % CI |\n|---|---|---|---|---|---|\n${fe.weak_cells.length ? fe.weak_cells.map((w) => `| ${w.cell} | ${w.n} | ${f(w.expectancy_r)} | ${f(w.pf, 2)} | ${pc(w.win_rate)} | ${ci(w.ci95_r)} |`).join('\n') : '| none | | | | | |'}\n\n### All cells with N ≥ 30, worst → best\n| Cell | N | Expectancy (R) | PF |\n|---|---|---|---|\n${fe.all_cells_n_ge_30.map((c) => `| ${c.cell} | ${c.n} | ${f(c.expectancy_r)} | ${f(c.pf, 2)} |`).join('\n')}\n`; }
writeFileSync(join(OUT, 'FALSE_ENTRY_FORENSICS.md'), md);
// 12. overlap
md = `# MODEL OVERLAP / CONFLICT\n\nThe production engine evaluates models in a fixed order and emits at most ONE candidate per confirmed candle (\`evaluateIntradayModels\` returns the first eligible candidate), so same-bar multi-model overlap is not observable in the replay (bars with ≥ 2 models = 0) and duplicate theses on one bar cannot occur. Overlap is therefore measured as a second model's same-side candidate within ± 3 bars.\n`;
for (const S of S2) { const o = R[S].overlap; md += `\n## ${S}\n| Population | N | Expectancy (R) | PF | Win rate | 95 % CI |\n|---|---|---|---|---|---|\n| Signals with another model's same-side candidate within ± 3 bars | ${o.signals_with_agreement_within_3_bars.n} | ${f(o.signals_with_agreement_within_3_bars.expectancy_r)} | ${f(o.signals_with_agreement_within_3_bars.pf, 2)} | ${pc(o.signals_with_agreement_within_3_bars.win_rate)} | ${ci(o.signals_with_agreement_within_3_bars.ci95_r)} |\n| Signals without | ${o.signals_without_agreement_within_3_bars.n} | ${f(o.signals_without_agreement_within_3_bars.expectancy_r)} | ${f(o.signals_without_agreement_within_3_bars.pf, 2)} | ${pc(o.signals_without_agreement_within_3_bars.win_rate)} | ${ci(o.signals_without_agreement_within_3_bars.ci95_r)} |\n\nBars with candidates ${o.bars_with_candidates}; bars with ≥ 2 models ${o.bars_with_2plus_models}; duplicate same-bar same-side theses ${o.duplicate_theses_same_bar_same_side}. One-position semantics are preserved by the sequential walk in every portfolio.\n`; }
writeFileSync(join(OUT, 'MODEL_OVERLAP.md'), md);
// 13. candidates
const cand = (S) => R.candidates[S]; const CN = ['C0', 'C1', 'C2', 'C3', 'C4', 'C5'];
const candTable = (S) => `| Candidate | Signals | Trades | Trades/session (median) | Zero-trade sessions | Win rate | Avg win / loss (R) | Expectancy (R) | Expectancy (USD) | 95 % CI (trade) | 99 % CI (trade) | 95 % CI (session block) | PF | Max DD (R) | Max DD (USD) | Loss streak | MFE / MAE (R) | Cost/trade (USD) | Cost % of gross expectancy | Top-5 share | Quarters positive |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n${CN.map((n) => { const v = cand(S)[n]; return `| ${n} | ${v.signals} | ${v.n ?? 0} | ${v.trades_per_session?.median ?? '—'} | ${pc(v.zero_trade_session_rate)} | ${pc(v.win_rate)} | ${f(v.avg_win_r, 2)} / ${f(v.avg_loss_r, 2)} | **${f(v.expectancy_r)}** | ${f(v.expectancy_usd, 2)} | ${ci(v.ci95_r)} | ${ci(v.ci99_r)} | ${ci(v.session_block_ci95_r)} | ${f(v.pf, 2)} | ${f(v.max_dd_r, 1)} | ${f(v.max_dd_usd, 1)} | ${v.max_loss_streak ?? '—'} | ${f(v.mfe_r_mean, 2)} / ${f(v.mae_r_mean, 2)} | ${f(v.cost_usd_per_trade, 2)} | ${pc(v.cost_pct_of_gross_expectancy)} | ${pc(v.top5_share)} | ${pc(v.quarters_positive_share)} |`; }).join('\n')}`;
writeFileSync(join(OUT, 'DEVELOPMENT_RESULTS.md'), `# DEVELOPMENT RESULTS (${R.meta.split.dev.join(' → ')}; ${R.meta.signals_dev} production signals; ${R.meta.sessions_dev} sessions; EXIT_F, normal costs, sequential one-position)\n\n${candTable('DEV')}\n\nCandidate definitions were derived from these DEV diagnostics by the pre-registered rules (CANDIDATE_DEFINITIONS.md). Diagnostics on DEV: CURRENT_MODEL_DECOMPOSITION.md, MODEL_CONTRIBUTION.md, SIGNAL_FUNNEL.md, GATE_ABLATION.md, QUALITY_AUDIT.md, RR_GEOMETRY.md, ENTRY_TIMING.md, MISSED_MOVE_FORENSICS.md, FALSE_ENTRY_FORENSICS.md, MODEL_OVERLAP.md.\n`);
writeFileSync(join(OUT, 'HOLDOUT_RESULTS.md'), `# HOLDOUT RESULTS (${R.meta.split.hold.join(' → ')}; ${R.meta.signals_hold} production signals; ${R.meta.sessions_hold} sessions; touched once, after the candidate definitions were frozen — sha256 ${R.candidate_definitions_sha256})\n\n${candTable('HOLD')}\n\n## Finalist decisions (ENTRY_EDGE_PREREGISTRATION §8)\n| Candidate | Status | Failing requirements | HOLD expectancy (R) | HOLD PF | HOLD N | Session-block 95 % CI |\n|---|---|---|---|---|---|---|\n${Object.entries(R.decisions.candidates).map(([k, d]) => `| ${k} | ${d.status} | ${d.reasons.join(', ') || '—'} | ${f(d.hold_expectancy_r)} | ${f(d.hold_pf, 2)} | ${d.hold_n} | ${ci(d.session_block_ci95_r)} |`).join('\n')}\n\nFINALIST = ${R.decisions.finalist ?? 'none'} · EDGE_DEMONSTRATED = ${R.decisions.edge_demonstrated} · FINALIST_BEATS_CONTROL = ${R.decisions.finalist_beats_control} · DEMO_ELIGIBLE = ${R.decisions.demo_eligible}\n`);
writeFileSync(join(OUT, 'COST_STRESS_RESULTS.md'), `# COST / STRESS RESULTS (sequential portfolios; NORMAL 0.24 + 0.10; STRESS 0.60 + 0.20; DRIFT next-open fill)\n${S2.map((S) => `\n## ${S}\n| Candidate | Normal N / expectancy (R) / PF | Stress N / expectancy (R) / PF | Drift N / expectancy (R) / PF | Cost USD/trade | Cost % of gross expectancy | Gross expectancy (USD) | Verdict |\n|---|---|---|---|---|---|---|---|\n${CN.map((n) => { const v = cand(S)[n]; return `| ${n} | ${v.n ?? 0} / ${f(v.expectancy_r)} / ${f(v.pf, 2)} | ${v.stress.n ?? 0} / ${f(v.stress.expectancy_r)} / ${f(v.stress.pf, 2)} | ${v.drift.n ?? 0} / ${f(v.drift.expectancy_r)} / ${f(v.drift.pf, 2)} | ${f(v.cost_usd_per_trade, 2)} | ${pc(v.cost_pct_of_gross_expectancy)} | ${f(v.gross_expectancy_usd, 2)} | ${(v.expectancy_r ?? -1) > 0 && (v.stress.expectancy_r ?? -1) > 0 ? 'positive after both cost cases' : (v.expectancy_r ?? -1) > 0 ? 'REJECTED: negative under stress' : 'negative even at normal cost'} |`; }).join('\n')}`).join('\n')}\n\nRanking is unchanged by costs: every candidate is negative or ≈ 0 before stress and more negative under stress; no candidate "works only before costs" because none works after normal costs either.\n`);
writeFileSync(join(OUT, 'WALK_FORWARD_RESULTS.md'), `# WALK-FORWARD / STABILITY (calendar quarters; sequential one-position trades; EXIT_F normal costs)\n${S2.map((S) => `\n## ${S}\n| Candidate | ${Object.keys(cand(S).C0.walk_forward).join(' | ')} | Quarters positive |\n|---|${Object.keys(cand(S).C0.walk_forward).map(() => '---').join('|')}|---|\n${CN.map((n) => { const w = cand(S)[n].walk_forward; return `| ${n} | ${Object.keys(cand(S).C0.walk_forward).map((q) => (w[q] ? `n ${w[q].n}, ${f(w[q].expectancy_r)} R, PF ${f(w[q].pf, 2)}, DD ${f(w[q].max_dd_r, 1)}` : '—')).join(' | ')} | ${pc(cand(S)[n].quarters_positive_share)} |`; }).join('\n')}`).join('\n')}\n\nNo candidate shows distributed positive expectancy across quarters; positive quarters are isolated and offset by negative ones.\n`);
writeFileSync(join(OUT, 'PARAMETER_STABILITY.md'), `# PARAMETER STABILITY (neighbouring values of every numeric threshold introduced)\n\nC3 simplified-quality threshold (derived ${R.candidate_definitions.c3_threshold}; components ${R.candidate_definitions.c3_components.join(', ') || 'none'}): ${S2.map((S) => `${S}: ${Object.entries(R.candidates[`${S}_stability`].c3_threshold).map(([k, v]) => `${k} → n ${v.n}, ${f(v.expectancy_r)} R, PF ${f(v.pf, 2)}`).join('; ')}`).join(' · ')}.\n\nC4 displacement cap X: derived ${R.candidate_definitions.c4_X ?? 'none (no X improved on C1 with stable neighbours; C4 = C1)'}; DEV scan ${R.candidate_definitions.c4_scan.map((e) => `X ${e.X} → ${f(e.dev_expectancy_r)} R`).join(', ')} vs unrestricted C1 ${f(R.candidate_definitions.c1_dev_expectancy_r)} R.${Object.keys(R.candidates.HOLD_stability.c4_X).length ? ` HOLD neighbours: ${Object.entries(R.candidates.HOLD_stability.c4_X).map(([k, v]) => `${k} → ${f(v.expectancy_r)} R`).join(', ')}.` : ''}\n\nClassification: no introduced threshold has a broad positive region; C3's threshold neighbours are all negative on HOLDOUT (fragile by absence of an effect, not a needle peak); C4 has no admissible value.\n`);
writeFileSync(join(OUT, 'UNCERTAINTY_ANALYSIS.md'), `# UNCERTAINTY ANALYSIS (trade bootstrap 2000 draws seed 20260930; session-block bootstrap 2000 draws seed 7; month-shuffled paths 500 draws)\n${S2.map((S) => `\n## ${S}\n| Candidate | N | Expectancy (R) | 95 % trade CI | 99 % trade CI | 95 % session-block CI | 99 % session-block CI | PF | Max DD observed (R) | DD P50 / P90 / P99 (shuffled) | Loss streak observed | Loss streak P50 / P90 (shuffled) |\n|---|---|---|---|---|---|---|---|---|---|---|---|\n${CN.map((n) => { const v = cand(S)[n]; const s = v.month_shuffle ?? {}; return `| ${n} | ${v.n ?? 0} | ${f(v.expectancy_r)} | ${ci(v.ci95_r)} | ${ci(v.ci99_r)} | ${ci(v.session_block_ci95_r)} | ${ci(v.session_block_ci99_r)} | ${f(v.pf, 2)} | ${f(v.max_dd_r, 1)} | ${f(s.dd_r_p50, 1)} / ${f(s.dd_r_p90, 1)} / ${f(s.dd_r_p99, 1)} | ${v.max_loss_streak ?? '—'} | ${s.loss_streak_p50 ?? '—'} / ${s.loss_streak_p90 ?? '—'} |`; }).join('\n')}`).join('\n')}\n\nEvery interval that matters (HOLDOUT, all candidates) includes zero or lies below it; no point estimate is treated as certainty.\n`);
// control vs finalist
const c0 = cand('HOLD').C0; const best = Object.entries(cand('HOLD')).filter(([k]) => k !== 'C0').sort((a, b) => (b[1].expectancy_r ?? -9) - (a[1].expectancy_r ?? -9))[0]; const bn = best[0], bv = best[1];
writeFileSync(join(OUT, 'CONTROL_VS_FINALIST.md'), `# CONTROL vs FINALIST\n\nFINALIST = **${R.decisions.finalist ?? 'none'}** (no candidate met the frozen finalist requirements). The best-performing candidate on HOLDOUT (${bn}) is shown for transparency only; it is NOT a finalist.\n\n| Metric (HOLDOUT, EXIT_F, normal costs) | CONTROL (C0) | ${bn} (best non-qualifying candidate) |\n|---|---|---|\n| Signals | ${c0.signals} | ${bv.signals} |\n| Trades (sequential) | ${c0.n} | ${bv.n} |\n| Trades/session (median) | ${c0.trades_per_session?.median} | ${bv.trades_per_session?.median} |\n| Zero-trade sessions | ${pc(c0.zero_trade_session_rate)} | ${pc(bv.zero_trade_session_rate)} |\n| Win rate | ${pc(c0.win_rate)} | ${pc(bv.win_rate)} |\n| Avg win / loss (R) | ${f(c0.avg_win_r, 2)} / ${f(c0.avg_loss_r, 2)} | ${f(bv.avg_win_r, 2)} / ${f(bv.avg_loss_r, 2)} |\n| Expectancy (R) | ${f(c0.expectancy_r)} | ${f(bv.expectancy_r)} |\n| Expectancy (USD, 0.01 lot) | ${f(c0.expectancy_usd, 2)} | ${f(bv.expectancy_usd, 2)} |\n| PF | ${f(c0.pf, 2)} | ${f(bv.pf, 2)} |\n| Max DD (R / USD) | ${f(c0.max_dd_r, 1)} / ${f(c0.max_dd_usd, 1)} | ${f(bv.max_dd_r, 1)} / ${f(bv.max_dd_usd, 1)} |\n| MFE / MAE (R) | ${f(c0.mfe_r_mean, 2)} / ${f(c0.mae_r_mean, 2)} | ${f(bv.mfe_r_mean, 2)} / ${f(bv.mae_r_mean, 2)} |\n| Loss streak | ${c0.max_loss_streak} | ${bv.max_loss_streak} |\n| Cost/trade (USD) | ${f(c0.cost_usd_per_trade, 2)} | ${f(bv.cost_usd_per_trade, 2)} |\n| 95 % CI (trade / session-block) | ${ci(c0.ci95_r)} / ${ci(c0.session_block_ci95_r)} | ${ci(bv.ci95_r)} / ${ci(bv.session_block_ci95_r)} |\n| Move capture (HOLD) | ${pc(R.HOLD.moves.move_capture_rate)} | ${pc(R.HOLD.moves[`capture_rate_${bn}`])} |\n| False-entry rate (losers / trades) | ${pc(1 - c0.win_rate)} | ${pc(1 - bv.win_rate)} |\n| Stress expectancy (R) | ${f(c0.stress.expectancy_r)} | ${f(bv.stress.expectancy_r)} |\n\nWhat changed: ${bn} = ${{ C1: 'only the DEV-supported model(s) ' + R.candidate_definitions.supported_models.join(', '), C2: 'supported model(s) restricted to DEV-positive 5m regimes ' + JSON.stringify(R.candidate_definitions.c2_regimes), C3: 'supported model(s) with the quality gate replaced by the DEV-monotonic component(s) ' + R.candidate_definitions.c3_components.join(', ') + ' ≥ ' + R.candidate_definitions.c3_threshold, C4: 'supported model(s) with displacement cap ' + (R.candidate_definitions.c4_X ?? 'none (identical to C1)'), C5: 'supported model(s) requiring a second model\'s same-side candidate within ± 3 bars' }[bn]}. Why economics did not improve: the DEV-supported subset (PB) did not keep its DEV sign on HOLDOUT (DEV +0.07 R on 495 signals → HOLDOUT negative), so every restriction built on it inherits a non-existent edge; fewer trades did not raise expectancy, and the sequential one-position walk removes the mild per-signal positives of the wider set. FINALIST_BEATS_CONTROL = ${R.decisions.finalist_beats_control}.\n`);
console.log('tables written');
