/**
 * ENTRY CORE V4 -- SETUP + TRIGGER + TIMING research (RESEARCH ONLY). Spec: ../V4_PREREGISTRATION.md (hash asserted).
 * EDGE_PHASE=DEV : pre-move feature research, family grids, forensics on DEVELOPMENT; derives configs/finalists.json (one grid point per family + justified combinations)
 * EDGE_PHASE=FULL: asserts the finalists hash; evaluates DEV + HOLDOUT once -> results/v4_results.json
 * Information-time rule: every feature at bar t uses bars <= t and the replay row of t only. Forward bars are used only to label move events / false-move forensics.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { canReenter } from '../../../src/engine/capitalHarvest/positionManager.js';

const PHASE = process.env.EDGE_PHASE === 'FULL' ? 'FULL' : 'DEV';
const HERE = dirname(fileURLToPath(import.meta.url)); const REPO = join(HERE, '..', '..', '..'); const ROOT = join(REPO, 'research', 'entry_core_v4'); const OUT = join(ROOT, 'results'); const CFG = join(ROOT, 'configs'); mkdirSync(OUT, { recursive: true }); mkdirSync(CFG, { recursive: true });
const shaFile = (p) => createHash('sha256').update(readFileSync(p)).digest('hex');
const PREREG_SHA = readFileSync(join(ROOT, 'V4_PREREGISTRATION.sha256'), 'utf8').trim().split(/\s+/)[0]; if (shaFile(join(ROOT, 'V4_PREREGISTRATION.md')) !== PREREG_SHA) throw new Error('V4_PREREGISTRATION hash mismatch');
const CONTROL_SHA = readFileSync(join(ROOT, 'V4_CONTROL_BASELINE.sha256'), 'utf8').trim().split(/\s+/)[0]; if (shaFile(join(ROOT, 'V4_CONTROL_BASELINE.md')) !== CONTROL_SHA) throw new Error('V4_CONTROL_BASELINE hash mismatch');
const LAB = join(REPO, 'handoff', 'edge_discovery_lab', 'data');
const b5 = JSON.parse(readFileSync(join(LAB, 'XAUUSDm_bars.json'), 'utf8'))['5m']; const N = b5.length;
const COSTS = { normal: { spread: 0.24, slip: 0.10 }, stress: { spread: 0.60, slip: 0.20 } }; const SWAP = 0.56; const HORIZON = 288; const GAP = 3 * 3600; const RR = 1.70; const ATR_FLOOR_USD = 2.0; const MIN_RISK_ATR = 0.5; const MAX_RISK_ATR = 3.0;
const r2 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 100) / 100); const r3 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 1000) / 1000);
const iso = (t) => new Date(t * 1000).toISOString(); const day = (t) => iso(t).slice(0, 10); const month = (t) => iso(t).slice(0, 7); const quarter = (t) => { const d = new Date(t * 1000); return `${d.getUTCFullYear()}Q${Math.floor(d.getUTCMonth() / 3) + 1}`; };
const SPLIT = { dev: ['2025-05-07', '2025-12-31'], hold: ['2026-01-01', '2026-09-29'] };
const split = (t) => { const d = day(t); if (d >= SPLIT.dev[0] && d <= SPLIT.dev[1]) return 'DEV'; if (d >= SPLIT.hold[0] && d <= SPLIT.hold[1]) return 'HOLD'; return 'EXCLUDED'; };
const mean = (a) => (a.length ? a.reduce((s, x) => s + x, 0) / a.length : null); const median = (a) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); const m = s.length >> 1; return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2; }; const pct = (a, p) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); return s[Math.min(s.length - 1, Math.floor(p * s.length))]; };
function rng(seed) { let s = seed >>> 0; return () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
function bootCI(v, n = 2000, seed = 20260930, alpha = 0.05) { if (v.length < 2) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0; for (let j = 0; j < v.length; j++) s += v[Math.floor(rand() * v.length)]; ms.push(s / v.length); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor((alpha / 2) * n)]), r3(ms[Math.floor((1 - alpha / 2) * n)])]; }
function blockCI(rows, n = 2000, seed = 7, alpha = 0.05) { const g = {}; for (const r of rows) (g[day(r.e.t)] ??= []).push(r.o.r); const blocks = Object.values(g); if (blocks.length < 5) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0, c = 0; for (let j = 0; j < blocks.length; j++) { const b = blocks[Math.floor(rand() * blocks.length)]; for (const x of b) { s += x; c++; } } ms.push(s / c); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor((alpha / 2) * n)]), r3(ms[Math.floor((1 - alpha / 2) * n)])]; }

// ---------- replay rows (context + CONTROL) ----------
const ROWS = new Map(); const ROWLIST = []; const sessions = { DEV: new Set(), HOLD: new Set(), ALL: new Set() };
for (const line of readFileSync(join(LAB, 'lab_rows.jsonl'), 'utf8').split('\n')) { if (!line) continue; const r = JSON.parse(line); const sp = split(r.t); if (sp === 'EXCLUDED') continue; r.split = sp; ROWS.set(r.i, r); ROWLIST.push(r); sessions[sp].add(day(r.t)); sessions.ALL.add(day(r.t)); }
ROWLIST.sort((a, b) => a.i - b.i); const FIRST_I = ROWLIST[0].i, LAST_I = ROWLIST[ROWLIST.length - 1].i;
const C = readFileSync(join(REPO, 'research', 'entry_architecture_v2', 'results', 'candidates.jsonl'), 'utf8').trim().split('\n').map((l) => JSON.parse(l)).filter((c) => split(c.t) !== 'EXCLUDED');
for (const c of C) { c.split = split(c.t); c.isSig = c.act === 'BUY' || c.act === 'SELL'; c.fam = 'CONTROL'; c.anchorLevel = c.geo?.entry; }
console.log(`phase ${PHASE}; bars ${N}; rows ${ROWLIST.length}; control signals ${C.filter((c) => c.isSig).length}`);

// ---------- EXIT_F (identical to V1/V2/V3) ----------
const EXIT_MEMO = new Map();
function exitF(e, costs = COSTS.normal, drift = false) { const key = `${e.i}|${e.side}|${e.geo.entry}|${e.geo.sl}|${e.geo.tp2}|${costs.spread}|${costs.slip}|${drift}`; const m = EXIT_MEMO.get(key); if (m) return m; const o = exitFRaw(e, costs, drift); EXIT_MEMO.set(key, o); return o; }
function exitFRaw(e, costs, drift) { const { i, side } = e; const { entry, sl, tp2 } = e.geo; const sp = costs.spread, slip = costs.slip; const sgn = side === 'BUY' ? 1 : -1; let fill = side === 'BUY' ? entry + sp : entry, start = i + 1; if (drift) { if (i + 1 >= N) return { status: 'NO_DATA' }; fill = side === 'BUY' ? b5[i + 1].open + sp : b5[i + 1].open; start = i + 2; } const d = Math.abs(entry - sl); if (!(d > 0)) return { status: 'INVALID' }; const brokerDist = 1.5 * d + sp; const end = Math.min(N - 1, i + HORIZON); let mfe = 0, mae = 0, mae3 = 0, nights = 0, gap = false, exit = null, exitBar = null, pnl = 0;
  for (let j = start; j <= end; j++) { const b = b5[j], p = b5[j - 1]; if (b.time - p.time > GAP) gap = true; if (side === 'BUY' && Math.floor(b.time / 86400) !== Math.floor(p.time / 86400)) nights++; const adv = side === 'BUY' ? fill - b.low : (b.high + sp) - fill; const fav = side === 'BUY' ? b.high - fill : fill - (b.low + sp); if (adv > mae) mae = adv; if (j - i <= 3 && adv > mae3) mae3 = adv; if (adv >= brokerDist) { exit = 'BROKER_SL'; pnl = -brokerDist - slip; exitBar = j; break; } const tpHit = side === 'BUY' ? b.high >= tp2 : (b.low + sp) <= tp2; if (tpHit) { if (fav > mfe) mfe = fav; exit = 'TP2'; pnl = Math.abs(tp2 - fill) - slip; exitBar = j; break; } if (fav > mfe) mfe = fav; if (side === 'BUY' ? b.close < sl : b.close > sl) { exit = 'THESIS_INVALIDATION'; pnl = sgn * ((side === 'BUY' ? b.close : b.close + sp) - fill) - slip; exitBar = j; break; } }
  let status = 'RESOLVED'; if (!exit) { if (end < i + HORIZON) return { status: 'NO_DATA' }; status = 'OPEN_AT_HORIZON'; const b = b5[end]; exit = 'HORIZON'; pnl = sgn * ((side === 'BUY' ? b.close : b.close + sp) - fill) - slip; exitBar = end; } const swap = side === 'BUY' ? nights * SWAP : 0; pnl -= swap;
  return { status, gap, exit, exitBar, bars: exitBar - i, d: r3(d), pnl_usd: r3(pnl), r: r3(pnl / d), mfe_r: r3(mfe / d), mae_r: r3(mae / d), mae3_r: r3(mae3 / d), cost_usd: r3(sp + slip + swap), cost_r: r3((sp + slip + swap) / d) }; }

// ---------- per-bar features (bars <= t only) ----------
console.log('features ...');
const F = { atr: new Array(N).fill(null), atrPct: new Array(N).fill(null), rng12: new Array(N).fill(null), rng24: new Array(N).fill(null), hi12: new Array(N).fill(null), lo12: new Array(N).fill(null), hi20: new Array(N).fill(null), hi36p: new Array(N).fill(null), lo36p: new Array(N).fill(null), contraction: new Array(N).fill(null), overlap6: new Array(N).fill(null), body: new Array(N).fill(null), closeLoc: new Array(N).fill(null), rngA: new Array(N).fill(null), ema20: new Array(N).fill(null), ema50: new Array(N).fill(null), slope20: new Array(N).fill(null), mom3: new Array(N).fill(null), mom6: new Array(N).fill(null), mom12: new Array(N).fill(null), accel: new Array(N).fill(null), run: new Array(N).fill(0), lastSH: new Array(N).fill(null), lastSL: new Array(N).fill(null), swingW: new Array(N).fill(null), dSH: new Array(N).fill(null), dSL: new Array(N).fill(null), eqHigh: new Array(N).fill(false), eqLow: new Array(N).fill(false), sweepHigh: new Array(N).fill(null), sweepLow: new Array(N).fill(null), sinceSweep: new Array(N).fill(null), sinceFailedBO: new Array(N).fill(null), trendUp: new Array(N).fill(false), trendDn: new Array(N).fill(false) };
{ const tr = new Array(N).fill(null); let sum = 0; for (let k = 1; k < N; k++) { tr[k] = Math.max(b5[k].high - b5[k].low, Math.abs(b5[k].high - b5[k - 1].close), Math.abs(b5[k].low - b5[k - 1].close)); sum += tr[k]; if (k > 14) sum -= tr[k - 14]; if (k >= 14) F.atr[k] = sum / 14; }
  const a20 = 2 / 21, a50 = 2 / 51; for (let k = 0; k < N; k++) { const c = b5[k].close; F.ema20[k] = k === 0 ? c : F.ema20[k - 1] + a20 * (c - F.ema20[k - 1]); F.ema50[k] = k === 0 ? c : F.ema50[k - 1] + a50 * (c - F.ema50[k - 1]); }
  const pivH = []; const pivL = []; // confirmed pivots (3 left / 3 right), pushed when confirmed at j + 3
  for (let t = 0; t < N; t++) { const b = b5[t]; const A = F.atr[t]; const range = b.high - b.low; F.body[t] = range > 0 ? Math.abs(b.close - b.open) / range : 0; F.closeLoc[t] = range > 0 ? (b.close - b.low) / range : 0.5; F.rngA[t] = A ? range / A : null;
    const j = t - 3; if (j >= 3) { let ph = true, pl = true; for (let q = 1; q <= 3; q++) { if (!(b5[j].high > b5[j - q].high) || !(b5[j].high >= b5[j + q].high)) ph = false; if (!(b5[j].low < b5[j - q].low) || !(b5[j].low <= b5[j + q].low)) pl = false; } if (ph) pivH.push({ idx: j, price: b5[j].high }); if (pl) pivL.push({ idx: j, price: b5[j].low }); }
    F.lastSH[t] = pivH.length ? pivH[pivH.length - 1] : null; F.lastSL[t] = pivL.length ? pivL[pivL.length - 1] : null;
    if (t >= 36 && A) { let h12 = -Infinity, l12 = Infinity, h24 = -Infinity, l24 = Infinity, hp = -Infinity, lp = Infinity, h20 = -Infinity, h36 = -Infinity, l36 = Infinity; for (let q = 0; q < 12; q++) { h12 = Math.max(h12, b5[t - q].high); l12 = Math.min(l12, b5[t - q].low); } for (let q = 0; q < 24; q++) { h24 = Math.max(h24, b5[t - q].high); l24 = Math.min(l24, b5[t - q].low); } for (let q = 12; q < 24; q++) { hp = Math.max(hp, b5[t - q].high); lp = Math.min(lp, b5[t - q].low); } for (let q = 0; q < 20; q++) h20 = Math.max(h20, b5[t - q].high); for (let q = 1; q <= 36; q++) { h36 = Math.max(h36, b5[t - q].high); l36 = Math.min(l36, b5[t - q].low); }
      F.hi12[t] = h12; F.lo12[t] = l12; F.hi20[t] = h20; F.hi36p[t] = h36; F.lo36p[t] = l36; F.rng12[t] = (h12 - l12) / A; F.rng24[t] = (h24 - l24) / A; F.contraction[t] = hp - lp > 0 ? (h12 - l12) / (hp - lp) : null; let ov = 0; for (let q = 0; q < 6; q++) { const x = b5[t - q], y = b5[t - q - 1]; const inter = Math.min(x.high, y.high) - Math.max(x.low, y.low); const un = Math.max(x.high, y.high) - Math.min(x.low, y.low); ov += un > 0 ? Math.max(0, inter) / un : 1; } F.overlap6[t] = ov / 6;
      F.slope20[t] = (F.ema20[t] - F.ema20[t - 6]) / A; F.mom3[t] = (b.close - b5[t - 3].close) / A; F.mom6[t] = (b.close - b5[t - 6].close) / A; F.mom12[t] = (b.close - b5[t - 12].close) / A; F.accel[t] = F.mom6[t - 3] != null ? F.mom6[t] - F.mom6[t - 3] : null;
      const side = b.close > F.ema20[t] ? 1 : -1; const prev = F.run[t - 1] ?? 0; F.run[t] = Math.sign(prev) === side ? prev + side : side;
      F.trendUp[t] = F.ema20[t] > F.ema50[t] && F.ema50[t] > F.ema50[t - 12]; F.trendDn[t] = F.ema20[t] < F.ema50[t] && F.ema50[t] < F.ema50[t - 12];
      if (F.lastSH[t] && F.lastSL[t]) { F.swingW[t] = (F.lastSH[t].price - F.lastSL[t].price) / A; F.dSH[t] = (F.lastSH[t].price - b.close) / A; F.dSL[t] = (b.close - F.lastSL[t].price) / A; }
      const recentH = pivH.filter((p) => t - p.idx <= 48), recentL = pivL.filter((p) => t - p.idx <= 48); F.eqHigh[t] = recentH.some((p, a) => recentH.some((q, c) => c !== a && Math.abs(p.price - q.price) <= 0.2 * A)); F.eqLow[t] = recentL.some((p, a) => recentL.some((q, c) => c !== a && Math.abs(p.price - q.price) <= 0.2 * A));
      // sweeps: this bar traded beyond the swing known at t-1 and closed back inside (level older than 6 bars)
      const SH = F.lastSH[t - 1], SL = F.lastSL[t - 1]; if (SH && t - SH.idx >= 6 && b.high > SH.price && b.close < SH.price) F.sweepHigh[t] = { level: SH.price, extreme: b.high, low: b.low }; if (SL && t - SL.idx >= 6 && b.low < SL.price && b.close > SL.price) F.sweepLow[t] = { level: SL.price, extreme: b.low, high: b.high };
      F.sinceSweep[t] = F.sweepHigh[t] || F.sweepLow[t] ? 0 : F.sinceSweep[t - 1] == null ? null : F.sinceSweep[t - 1] + 1;
      // failed breakout: a close beyond the swing (known then) followed by a close back inside within 3 bars (known at the re-entry bar)
      let failed = false; for (let q = 1; q <= 3; q++) { const u = t - q; const sh = F.lastSH[u], sl2 = F.lastSL[u]; if (sh && b5[u].close > sh.price && b.close < sh.price) failed = true; if (sl2 && b5[u].close < sl2.price && b.close > sl2.price) failed = true; } F.sinceFailedBO[t] = failed ? 0 : F.sinceFailedBO[t - 1] == null ? null : F.sinceFailedBO[t - 1] + 1; } }
  // ATR percentile over the trailing 288 bars
  for (let t = 300; t < N; t++) { let below = 0, cnt = 0; for (let q = 0; q < 288; q++) { const v = F.atr[t - q]; if (v == null) continue; cnt++; if (v < F.atr[t]) below++; } F.atrPct[t] = cnt ? below / cnt : null; } }

// ---------- move events (V1/V2/V3 definition; validated against V3 counts) ----------
function findEvents(S) { if (S === 'ALL') return [...findEvents('DEV'), ...findEvents('HOLD')]; const events = []; let k = 500; const lo = S === 'DEV' ? SPLIT.dev[0] : SPLIT.hold[0], hi = S === 'DEV' ? SPLIT.dev[1] : SPLIT.hold[1]; while (k < N - 25) { const d = day(b5[k].time); if (d < lo) { k++; continue; } if (d > hi) break; const a = F.atr[k]; if (!a) { k++; continue; } const c0 = b5[k].close; let up = null, dn = null, maxH = -Infinity, minL = Infinity, endBar = null; for (let j = k + 1; j <= k + 24; j++) { const b = b5[j]; if (b.time - b5[j - 1].time > GAP) break; maxH = Math.max(maxH, b.high); minL = Math.min(minL, b.low); if (up == null && maxH - c0 >= 3 * a && c0 - minL <= a) { up = j; } if (dn == null && c0 - minL >= 3 * a && maxH - c0 <= a) { dn = j; } if (up != null || dn != null) { endBar = j; break; } } if (up != null || dn != null) { const dir = up != null ? 'BUY' : 'SELL'; let mag = 0; for (let j = k + 1; j <= Math.min(N - 1, k + 24); j++) { if (b5[j].time - b5[j - 1].time > GAP) break; mag = Math.max(mag, dir === 'BUY' ? b5[j].high - c0 : c0 - b5[j].low); } events.push({ k, t: b5[k].time, dir, end: endBar, time_to_move: endBar - k, magnitude_usd: r2(mag), magnitude_atr: r2(mag / a), atr: r2(a) }); k += 24; } else k++; } return events; }
const EVENTS = { DEV: findEvents('DEV'), HOLD: findEvents('HOLD') }; console.log('events', EVENTS.DEV.length, EVENTS.HOLD.length);
if (EVENTS.DEV.length !== 1640 || EVENTS.HOLD.length !== 1842) throw new Error('event set differs from V3');
const EV_BY_K = { DEV: new Map(EVENTS.DEV.map((e) => [e.k, e])), HOLD: new Map(EVENTS.HOLD.map((e) => [e.k, e])) };
const onsetNear = (S, i, side, lo, hi) => { for (let k = i + lo; k <= i + hi; k++) { const e = EV_BY_K[S].get(k); if (e && e.dir === side) return e; } return null; };

// ---------- setup / trigger families (information-time) ----------
const inRange = (t) => t >= FIRST_I && t <= LAST_I && ROWS.has(t);
function mkSignal(t, side, fam, variant, p, sl, originBar, originLevel, extra = {}) { const b = b5[t]; const A = F.atr[t]; const entry = b.close; let risk = Math.abs(entry - sl); let block = null; if (A < ATR_FLOOR_USD) block = 'ATR_FLOOR'; if (risk < MIN_RISK_ATR * A) { sl = side === 'BUY' ? entry - MIN_RISK_ATR * A : entry + MIN_RISK_ATR * A; risk = MIN_RISK_ATR * A; } if (risk > MAX_RISK_ATR * A) block = block ?? 'RISK'; if (extra.chase) block = block ?? extra.chase; const tp2 = side === 'BUY' ? entry + RR * risk : entry - RR * risk; const origin = side === 'BUY' ? F.lo12[t] : F.hi12[t]; const disp = Math.abs(entry - origin) / A; const row = ROWS.get(t); return { i: t, t: b.time, side, fam, variant, p, model: `${fam}`, geo: { entry: r3(entry), sl: r3(sl), tp2: r3(tp2) }, atr: r3(A), riskAtr: r3(risk / A), originBar, setupAge: t - originBar, anchor: r3(originLevel), anchorLevel: r3(originLevel), disp: r3(disp), block, split: split(b.time), rg5: row?.rg5 ?? null, m30r: row?.m30r ?? null, h1r: row?.h1r ?? null, b15d: row?.b15d ?? null, ses: row?.ses ?? null, isSig: true }; }
const ok = (t) => t >= 400 && inRange(t) && F.atr[t] && F.rng12[t] != null && F.rng12[t - 1] != null;
// setup-state functions (direction: 'BUY' | 'SELL' | 'ANY') used for forensics; signal generators per grid point
const SETUP = {
  A: (t, p) => (F.rng12[t] <= p.wA && F.atrPct[t] != null && F.atrPct[t] <= 0.5 ? 'ANY' : null),
  B: (t, p) => { for (let q = 0; q <= p.aB; q++) { if (F.sweepHigh[t - q]) return 'SELL'; if (F.sweepLow[t - q]) return 'BUY'; } return null; },
  C: (t) => { const sh = F.lastSH[t], sl = F.lastSL[t]; const A = F.atr[t]; const c = b5[t].close; if (sh && c <= sh.price && sh.price - c <= 1.0 * A) return 'BUY'; if (sl && c >= sl.price && c - sl.price <= 1.0 * A) return 'SELL'; return null; },
  D: (t, p) => (pullbackState(t, 'BUY', p.dD) ? 'BUY' : pullbackState(t, 'SELL', p.dD) ? 'SELL' : null),
  E: (t) => (F.mom6[t] != null && Math.abs(F.mom6[t]) <= 0.5 && F.rng12[t] <= 3 ? 'ANY' : null),
  F: (t, p) => ((F.hi36p[t] - F.lo36p[t]) / F.atr[t] <= p.wF ? 'ANY' : null),
  G: (t, p) => (resumptionState(t, 'BUY') ? 'BUY' : resumptionState(t, 'SELL') ? 'SELL' : null),
};
function pullbackState(t, side, dD) { const A = F.atr[t]; if (side === 'BUY' ? !F.trendUp[t] : !F.trendDn[t]) return null; let extIdx = t; for (let q = 0; q < 20; q++) { const u = t - q; if (side === 'BUY' ? b5[u].high > b5[extIdx].high : b5[u].low < b5[extIdx].low) extIdx = u; } if (extIdx === t) return null; let pbIdx = extIdx, touched = false; for (let u = extIdx; u <= t; u++) { if (side === 'BUY' ? b5[u].low < b5[pbIdx].low : b5[u].high > b5[pbIdx].high) pbIdx = u; if (side === 'BUY' ? b5[u].low <= F.ema20[u] + 0.3 * A : b5[u].high >= F.ema20[u] - 0.3 * A) touched = true; } const depth = side === 'BUY' ? (b5[extIdx].high - b5[pbIdx].low) / A : (b5[pbIdx].high - b5[extIdx].low) / A; if (!(depth >= dD) || !touched) return null; const sw = side === 'BUY' ? F.lastSL[t] : F.lastSH[t]; if (sw && (side === 'BUY' ? b5[pbIdx].low <= sw.price : b5[pbIdx].high >= sw.price)) return null; return { extIdx, pbIdx, depth }; }
function resumptionState(t, side) { const A = F.atr[t]; const row = ROWS.get(t); if (!row) return null; if (side === 'BUY' ? !(F.ema50[t] > F.ema50[t - 24] && b5[t].close > F.ema50[t] && row.m30r === 'BULL_TREND') : !(F.ema50[t] < F.ema50[t - 24] && b5[t].close < F.ema50[t] && row.m30r === 'BEAR_TREND')) return null; let touched = false, pbIdx = t; for (let q = 0; q < 12; q++) { const u = t - q; if (side === 'BUY' ? b5[u].close < F.ema50[u] : b5[u].close > F.ema50[u]) return null; if (side === 'BUY' ? b5[u].low <= F.ema20[u] + 0.3 * A : b5[u].high >= F.ema20[u] - 0.3 * A) touched = true; if (side === 'BUY' ? b5[u].low < b5[pbIdx].low : b5[u].high > b5[pbIdx].high) pbIdx = u; } if (!touched) return null; const sw = side === 'BUY' ? F.lastSL[t] : F.lastSH[t]; if (sw && (side === 'BUY' ? b5[pbIdx].low <= sw.price : b5[pbIdx].high >= sw.price)) return null; return { pbIdx }; }
const GRID = [];
for (const wA of [2.0, 2.5, 3.0]) for (const xA of [1.5, 2.0]) for (const v of ['A1', 'A2', 'A3']) GRID.push({ key: `${v}|wA${wA}|xA${xA}`, fam: 'A', variant: v, p: { wA, xA } });
for (const aB of [3, 6]) for (const v of ['B1', 'B2']) GRID.push({ key: `${v}|aB${aB}`, fam: 'B', variant: v, p: { aB } });
GRID.push({ key: 'C1', fam: 'C', variant: 'C1', p: {} }, { key: 'C2', fam: 'C', variant: 'C2', p: {} }); for (const rC of [6, 12]) GRID.push({ key: `C3|rC${rC}`, fam: 'C', variant: 'C3', p: { rC } });
for (const dD of [0.8, 1.2]) for (const v of ['D1', 'D2']) GRID.push({ key: `${v}|dD${dD}`, fam: 'D', variant: v, p: { dD } });
for (const mE of [1.0, 1.5]) GRID.push({ key: `E1|mE${mE}`, fam: 'E', variant: 'E1', p: { mE } });
for (const wF of [3, 4]) for (const v of ['F1', 'F2']) GRID.push({ key: `${v}|wF${wF}`, fam: 'F', variant: v, p: { wF } });
for (const dG of [1.0, 1.5]) GRID.push({ key: `G1|dG${dG}`, fam: 'G', variant: 'G1', p: { dG } });
function generate(g) { const out = []; const seen = new Set(); const push = (s) => { if (!s) return; const k = `${s.i}|${s.side}`; if (seen.has(k)) return; seen.add(k); out.push(s); }; const { fam, variant, p } = g;
  for (let t = 400; t < N; t++) { if (!ok(t)) continue; const b = b5[t]; const A1 = F.atr[t - 1]; const A = F.atr[t];
    if (fam === 'A') { if (!SETUP.A(t - 1, p)) continue; const exp = (b.high - b.low) / A1; if (!(exp >= p.xA)) continue; const hi = F.hi12[t - 1], lo = F.lo12[t - 1]; const up = F.closeLoc[t] >= 0.7, dn = F.closeLoc[t] <= 0.3; let side = null; if (variant === 'A3') side = up ? 'BUY' : dn ? 'SELL' : null; else { if (up && b.close > hi) side = 'BUY'; else if (dn && b.close < lo) side = 'SELL'; if (side && variant === 'A2') { const sw = side === 'BUY' ? F.lastSH[t] : F.lastSL[t]; if (!sw || !(side === 'BUY' ? b.close > sw.price : b.close < sw.price)) side = null; } } if (!side) continue; let origin = t - 1; while (origin > t - 12 && SETUP.A(origin - 1, p)) origin--; push(mkSignal(t, side, 'A', variant, p, side === 'BUY' ? lo : hi, origin, side === 'BUY' ? hi : lo)); }
    else if (fam === 'B') { for (const side of ['SELL', 'BUY']) { const sw = side === 'SELL' ? F.sweepHigh : F.sweepLow; if (variant === 'B1') { const s = sw[t]; if (!s) continue; const chase = Math.abs(b.close - s.level) > 1.5 * A ? 'CHASE' : null; push(mkSignal(t, side, 'B', variant, p, side === 'SELL' ? s.extreme + 0.1 * A : s.extreme - 0.1 * A, t, s.level, { chase })); } else { for (let q = 1; q <= p.aB; q++) { const j = t - q; const s = sw[j]; if (!s) continue; const confirmed = side === 'SELL' ? b.close < s.low : b.close > s.high; if (!confirmed) continue; let earlier = false; for (let u = j + 1; u < t; u++) if (side === 'SELL' ? b5[u].close < s.low : b5[u].close > s.high) earlier = true; if (earlier) continue; const chase = Math.abs(b.close - s.level) > 1.5 * A ? 'CHASE' : null; push(mkSignal(t, side, 'B', variant, p, side === 'SELL' ? s.extreme + 0.1 * A : s.extreme - 0.1 * A, j, s.level, { chase })); } } } }
    else if (fam === 'C') { for (const side of ['BUY', 'SELL']) { const swArr = side === 'BUY' ? F.lastSH : F.lastSL; const isBreak = (u) => { const sw = swArr[u]; if (!sw) return null; const beyond = side === 'BUY' ? b5[u].close > sw.price : b5[u].close < sw.price; const prevBeyond = side === 'BUY' ? b5[u - 1].close > sw.price : b5[u - 1].close < sw.price; return beyond && !prevBeyond ? sw : null; }; const stopOf = (u) => { const s = side === 'BUY' ? F.lastSL[u] : F.lastSH[u]; return s ? s.price : (side === 'BUY' ? b5[u].close - 1.5 * F.atr[u] : b5[u].close + 1.5 * F.atr[u]); };
        if (variant === 'C1') { const sw = isBreak(t); if (!sw) continue; const chase = Math.abs(b.close - sw.price) > 1.5 * A ? 'CHASE' : null; push(mkSignal(t, side, 'C', variant, p, stopOf(t), t, sw.price, { chase })); }
        else if (variant === 'C2') { const sw = isBreak(t - 1); if (!sw) continue; if (!(side === 'BUY' ? b.close > sw.price : b.close < sw.price)) continue; const chase = Math.abs(b5[t - 1].close - sw.price) > 1.5 * A ? 'CHASE' : null; push(mkSignal(t, side, 'C', variant, p, stopOf(t), t - 1, sw.price, { chase })); }
        else { for (let q = 1; q <= p.rC; q++) { const u = t - q; const sw = isBreak(u); if (!sw) continue; let failed = false, retestedEarlier = false; for (let v = u + 1; v < t; v++) { if (side === 'BUY' ? b5[v].close < sw.price : b5[v].close > sw.price) failed = true; if (side === 'BUY' ? b5[v].low <= sw.price + 0.3 * F.atr[v] && b5[v].close > sw.price : b5[v].high >= sw.price - 0.3 * F.atr[v] && b5[v].close < sw.price) retestedEarlier = true; } if (failed || retestedEarlier) continue; const retest = side === 'BUY' ? b.low <= sw.price + 0.3 * A && b.close > sw.price : b.high >= sw.price - 0.3 * A && b.close < sw.price; if (!retest) continue; const chase = Math.abs(b5[u].close - sw.price) > 1.5 * F.atr[u] ? 'CHASE' : null; push(mkSignal(t, side, 'C', variant, p, stopOf(t), u, sw.price, { chase })); } } } }
    else if (fam === 'D') { for (const side of ['BUY', 'SELL']) { if (variant === 'D1') { const st = pullbackState(t - 1, side, p.dD); if (!st) continue; if (t - st.pbIdx > 3) continue; const cont = side === 'BUY' ? b.close > b5[t - 1].high && b.close > F.ema20[t] : b.close < b5[t - 1].low && b.close < F.ema20[t]; if (!cont) continue; push(mkSignal(t, side, 'D', variant, p, side === 'BUY' ? b5[st.pbIdx].low : b5[st.pbIdx].high, st.pbIdx, side === 'BUY' ? b5[st.extIdx].high : b5[st.extIdx].low)); } else { const st = pullbackState(t - 2, side, p.dD); if (!st) continue; const two = side === 'BUY' ? b.close > F.ema20[t] && b5[t - 1].close > F.ema20[t - 1] && !(b5[t - 2].close > F.ema20[t - 2]) : b.close < F.ema20[t] && b5[t - 1].close < F.ema20[t - 1] && !(b5[t - 2].close < F.ema20[t - 2]); if (!two) continue; push(mkSignal(t, side, 'D', variant, p, side === 'BUY' ? b5[st.pbIdx].low : b5[st.pbIdx].high, st.pbIdx, side === 'BUY' ? b5[st.extIdx].high : b5[st.extIdx].low)); } } }
    else if (fam === 'E') { if (!SETUP.E(t - 3)) continue; if (F.accel[t] == null || !(F.accel[t] > 0) || F.body[t] < 0.6) continue; let side = null; if (F.mom3[t] >= p.mE && F.closeLoc[t] >= 0.75) side = 'BUY'; else if (F.mom3[t] <= -p.mE && F.closeLoc[t] <= 0.25) side = 'SELL'; if (!side) continue; const origin = side === 'BUY' ? F.lo12[t] : F.hi12[t]; const disp = Math.abs(b.close - origin) / A; const sl = side === 'BUY' ? Math.min(b5[t].low, b5[t - 1].low, b5[t - 2].low) : Math.max(b5[t].high, b5[t - 1].high, b5[t - 2].high); push(mkSignal(t, side, 'E', variant, p, sl, t - 3, origin, { chase: disp > 2.0 ? 'LATE_EXHAUSTION' : null })); }
    else if (fam === 'F') { if (variant === 'F1') { if (!SETUP.F(t, p)) continue; const hi = F.hi36p[t], lo = F.lo36p[t]; let side = null; if (b.close > hi && F.closeLoc[t] >= 0.6) side = 'BUY'; else if (b.close < lo && F.closeLoc[t] <= 0.4) side = 'SELL'; if (!side) continue; push(mkSignal(t, side, 'F', variant, p, side === 'BUY' ? hi - 0.5 * A : lo + 0.5 * A, t - 1, side === 'BUY' ? hi : lo)); } else { if (!SETUP.F(t - 1, p)) continue; const hi = F.hi36p[t - 1], lo = F.lo36p[t - 1]; let side = null; if (b5[t - 1].close > hi && b.close > hi && !(b5[t - 2].close > hi)) side = 'BUY'; else if (b5[t - 1].close < lo && b.close < lo && !(b5[t - 2].close < lo)) side = 'SELL'; if (!side) continue; push(mkSignal(t, side, 'F', variant, p, side === 'BUY' ? hi - 0.5 * A : lo + 0.5 * A, t - 1, side === 'BUY' ? hi : lo)); } }
    else if (fam === 'G') { for (const side of ['BUY', 'SELL']) { const st = resumptionState(t - 1, side); if (!st) continue; const trig = side === 'BUY' ? F.mom3[t] >= 0.5 && b.close > b5[t - 1].high : F.mom3[t] <= -0.5 && b.close < b5[t - 1].low; if (!trig) continue; const pb = side === 'BUY' ? b5[st.pbIdx].low : b5[st.pbIdx].high; const disp = Math.abs(b.close - pb) / A; push(mkSignal(t, side, 'G', variant, p, pb, st.pbIdx, pb, { chase: disp > p.dG ? 'CHASE' : null })); } } }
  return out; }
console.log('generating grid signals ...'); const SIG = {}; for (const g of GRID) { SIG[g.key] = generate(g); }
console.log(GRID.map((g) => `${g.key}:${SIG[g.key].length}/${SIG[g.key].filter((s) => !s.block).length}`).join(' '));

// ---------- controls ----------
const ctrl = (() => { const rand = rng(99); const leak = [], nul = []; for (let t = 600; t < N - 300; t += 37) { if (!inRange(t)) continue; const a = F.atr[t]; const fut = b5[t + 12].close - b5[t].close; const mk = (side) => ({ i: t, side, geo: { entry: b5[t].close, sl: side === 'BUY' ? b5[t].close - a : b5[t].close + a, tp2: side === 'BUY' ? b5[t].close + a : b5[t].close - a } }); const o1 = exitF(mk(fut >= 0 ? 'BUY' : 'SELL')), o2 = exitF(mk(rand() < 0.5 ? 'BUY' : 'SELL')); if (o1.status !== 'NO_DATA' && !o1.gap) leak.push(o1.r); if (o2.status !== 'NO_DATA' && !o2.gap) nul.push(o2.r); }
  const sample = SIG['C1'].filter((s) => !s.block).slice(0, 400); const diff = mean(sample.map((s) => exitF(s, { spread: 0.24, slip: 0 }).pnl_usd)) - mean(sample.map((s) => exitF(s).pnl_usd)); const firstExitOk = sample.every((s) => exitF(s).status === 'NO_DATA' || exitF(s).exitBar >= s.i + 1);
  // prefix invariance: recompute a feature window on a truncated copy of the bars and compare
  let prefixOk = true; { const t = 5000; const copy = b5.slice(0, t + 1); let sum = 0; const tr = []; for (let k = 1; k <= t; k++) { tr.push(Math.max(copy[k].high - copy[k].low, Math.abs(copy[k].high - copy[k - 1].close), Math.abs(copy[k].low - copy[k - 1].close))); } for (let k = tr.length - 14; k < tr.length; k++) sum += tr[k]; if (Math.abs(sum / 14 - F.atr[t]) > 1e-9) prefixOk = false; if (F.lastSH[t] && F.lastSH[t].idx > t - 3) prefixOk = false; }
  return { leak_mean_r: r3(mean(leak)), leak_n: leak.length, null_mean_r: r3(mean(nul)), null_n: nul.length, cost_test: { diff: r3(diff), expected: 0.10, pass: Math.abs(diff - 0.10) < 0.001 }, first_exit_after_entry: firstExitOk, prefix_invariance: prefixOk, events_match_v3: true }; })();
console.log('controls', JSON.stringify(ctrl)); if (!(ctrl.leak_mean_r > 0.3) || !(Math.abs(ctrl.null_mean_r) < 0.15) || !ctrl.cost_test.pass || !ctrl.first_exit_after_entry || !ctrl.prefix_invariance) throw new Error('CONTROL FAILED');

// ---------- statistics ----------
const rowsOf = (sigs, cse = 'normal') => sigs.filter((s) => !s.block).map((s) => ({ e: s, o: exitF(s, COSTS[cse === 'drift' ? 'normal' : cse], cse === 'drift') })).filter((x) => x.o.status !== 'NO_DATA' && x.o.status !== 'INVALID');
const ctlSigs = (S) => C.filter((c) => c.isSig && (S === 'ALL' || c.split === S));
const ctlRows = (S, cse = 'normal') => rowsOf(ctlSigs(S), cse);
const inS = (S) => (s) => S === 'ALL' || s.split === S;
function seqWalk(rows) { const trades = []; let exitBar = -1, lastTrade = null, lastLoss = false; const skipped = { SAME_OR_EARLIER_CANDLE: 0, STALE_SAME_SETUP: 0, REVENGE_GUARD: 0 }; const occ = []; for (const x of [...rows].sort((a, b) => a.e.i - b.e.i)) { const ok2 = canReenter({ signal: x.e, exitBar, lastTrade, lastExitWasLoss: lastLoss }); if (!ok2.ok) { skipped[ok2.reason] = (skipped[ok2.reason] ?? 0) + 1; continue; } trades.push(x); occ.push([x.e.i, x.o.exitBar]); exitBar = x.o.exitBar; lastTrade = x.e; lastLoss = x.o.r <= 0; } return { trades, skipped, occ }; }
function pathDD(rows, key = 'r') { let cum = 0, peak = 0, dd = 0, streak = 0, maxStreak = 0; for (const x of rows) { cum += x.o[key]; if (cum > peak) peak = cum; dd = Math.max(dd, peak - cum); if (x.o[key] <= 0) { streak++; maxStreak = Math.max(maxStreak, streak); } else streak = 0; } return { max_dd: r2(dd), final: r2(cum), max_loss_streak: maxStreak }; }
function stats(rows, sessSet = null, { ci = true, block = false } = {}) { const R = rows.map((x) => x.o.r); if (!R.length) return { n: 0 }; const w = R.filter((x) => x > 0), l = R.filter((x) => x <= 0); const gw = w.reduce((a, b) => a + b, 0), gl = -l.reduce((a, b) => a + b, 0); const U = rows.map((x) => x.o.pnl_usd); const perDay = {}; for (const x of rows) perDay[day(x.e.t)] = (perDay[day(x.e.t)] ?? 0) + 1; const counts = sessSet ? [...sessSet].map((d) => perDay[d] ?? 0) : null; const costU = rows.reduce((s, x) => s + x.o.cost_usd, 0); const ddR = pathDD(rows, 'r'), ddU = pathDD(rows, 'pnl_usd');
  return { n: R.length, win_rate: r3(w.length / R.length), avg_win_r: r3(mean(w)), avg_loss_r: l.length ? r3(-mean(l)) : null, expectancy_r: r3(mean(R)), expectancy_usd: r3(mean(U)), gross_expectancy_usd: r3(mean(U) + costU / R.length), pf: gl > 0 ? r2(gw / gl) : (gw > 0 ? 99 : null), ci95_r: ci ? bootCI(R) : null, ci99_r: ci ? bootCI(R, 2000, 20260930, 0.01) : null, block_ci95_r: block ? blockCI(rows) : null, block_ci99_r: block ? blockCI(rows, 2000, 7, 0.01) : null, max_dd_r: ddR.max_dd, max_dd_usd: ddU.max_dd, net_r: ddR.final, max_loss_streak: ddR.max_loss_streak, mfe_r: r3(mean(rows.map((x) => x.o.mfe_r))), mae_r: r3(mean(rows.map((x) => x.o.mae_r))), mae3_r: r3(mean(rows.map((x) => x.o.mae3_r))), avg_bars: r2(mean(rows.map((x) => x.o.bars))), cost_usd: r3(costU / R.length), cost_pct_gross: (mean(U) + costU / R.length) > 0 ? r3((costU / R.length) / (mean(U) + costU / R.length)) : null, trades_per_session: counts ? { median: pct(counts, 0.5), p10: pct(counts, 0.1), p90: pct(counts, 0.9), mean: r2(mean(counts)) } : null, zero_trade_session_rate: counts ? r3(counts.filter((x) => x === 0).length / counts.length) : null, top5_share: gw > 0 ? r3([...R].sort((a, b) => b - a).slice(0, 5).filter((x) => x > 0).reduce((s, x) => s + x, 0) / gw) : null, family_mix: Object.fromEntries(Object.entries(rows.reduce((g, x) => { const k = x.e.fam === 'CONTROL' ? x.e.model : `${x.e.fam}:${x.e.variant}`; g[k] = (g[k] ?? 0) + 1; return g; }, {}))), side_mix: rows.reduce((g, x) => { g[x.e.side] = (g[x.e.side] ?? 0) + 1; return g; }, {}) }; }
const cell = (rows) => { const s = stats(rows, null, { ci: rows.length >= 30 }); return { n: s.n ?? 0, win_rate: s.win_rate, avg_win_r: s.avg_win_r, avg_loss_r: s.avg_loss_r, expectancy_r: s.expectancy_r, expectancy_usd: s.expectancy_usd, pf: s.pf, mfe_r: s.mfe_r, mae_r: s.mae_r, mae3_r: s.mae3_r, ci95_r: s.ci95_r }; };

// ---------- move capture / forensics ----------
function captureStats(S, rows, occ = []) { const by = {}; for (const x of rows) (by[x.e.i] ??= []).push(x.e.side); let valid = 0, late = 0, wrong = 0, none = 0, positioned = 0, noSetup = 0, gate = 0; for (const ev of EVENTS[S]) { let e = false, l = false, w = false; for (let j = ev.k - 6; j <= ev.k + 6; j++) for (const s of by[j] ?? []) { if (s === ev.dir) { if (j <= ev.k) e = true; else l = true; } else w = true; } if (e) valid++; else if (l) late++; else if (w) wrong++; else if (occ.some(([a, b]) => ev.k >= a && ev.k <= b)) positioned++; else { none++; const r = ROWS.get(ev.k); if (!r || r.wr === 'NO_ELIGIBLE_STRATEGY' || r.wr === 'CHOP') noSetup++; else gate++; } } const n = Math.max(1, EVENTS[S].length); return { events: EVENTS[S].length, capture_rate: r3((valid + late) / n), valid_entry_rate: r3(valid / n), late_entry_rate: r3(late / n), wrong_direction_rate: r3(wrong / n), already_positioned_rate: r3(positioned / n), no_signal_rate: r3(none / n), no_setup_or_trigger_rate: r3(noSetup / n), gate_or_filter_rate: r3(gate / n) }; }
// V4 forensics: NO_SETUP / SETUP_NO_TRIGGER / TRIGGER_BLOCKED / WRONG_DIRECTION / LATE / ALREADY_POSITIONED / VALID, plus earliest detectable setup & trigger (bars relative to onset)
function forensics(S, members, rows, occ) { // members = [{fam, p, sigsAll}] (all generated signals incl. blocked) for the candidate's components
  const sigBy = {}; for (const m of members) for (const s of m.sigsAll) if (inS(S)(s)) (sigBy[s.i] ??= []).push(s); const tradeBy = {}; for (const x of rows) (tradeBy[x.e.i] ??= []).push(x.e.side);
  const setupDir = (t, dir) => members.some((m) => { const st = SETUP[m.fam](t, m.p); return st === 'ANY' || st === dir; });
  const cls = { VALID: 0, LATE: 0, WRONG_DIRECTION: 0, ALREADY_POSITIONED: 0, TRIGGER_BLOCKED: 0, SETUP_NO_TRIGGER: 0, NO_SETUP: 0, SAFETY_BLOCK: 0 }; const earliestSetup = [], earliestTrigger = [], blockReasons = {}; const perFamSetup = {};
  for (const ev of EVENTS[S]) { let valid = false, late = false, wrong = false, blocked = null; for (let j = ev.k - 6; j <= ev.k + 6; j++) { for (const sd of tradeBy[j] ?? []) { if (sd === ev.dir) { if (j <= ev.k) valid = true; else late = true; } else wrong = true; } for (const s of sigBy[j] ?? []) if (s.side === ev.dir && s.block) blocked = blocked ?? s.block; } let es = null, et = null; for (let j = ev.k - 12; j <= ev.k + 6; j++) { if (es == null && j >= 400 && j < N && setupDir(j, ev.dir)) es = j - ev.k; if (et == null && (sigBy[j] ?? []).some((s) => s.side === ev.dir)) et = j - ev.k; } if (es != null) earliestSetup.push(es); if (et != null) earliestTrigger.push(et); for (const m of members) { let hit = false; for (let j = ev.k - 12; j <= ev.k && !hit; j++) { const st = SETUP[m.fam](j, m.p); if (st === 'ANY' || st === ev.dir) hit = true; } perFamSetup[m.fam] = (perFamSetup[m.fam] ?? 0) + (hit ? 1 : 0); }
    if (valid) cls.VALID++; else if (late) cls.LATE++; else if (wrong) cls.WRONG_DIRECTION++; else if (occ.some(([a, b]) => ev.k >= a && ev.k <= b)) cls.ALREADY_POSITIONED++; else if (blocked) { cls.TRIGGER_BLOCKED++; blockReasons[blocked] = (blockReasons[blocked] ?? 0) + 1; } else if (es != null && es <= 0) cls.SETUP_NO_TRIGGER++; else cls.NO_SETUP++; }
  const n = EVENTS[S].length; const rates = Object.fromEntries(Object.entries(cls).map(([k, v]) => [k, r3(v / n)])); return { events: n, counts: cls, rates, block_reasons: blockReasons, earliest_setup_rel_onset: { detected: earliestSetup.length, share: r3(earliestSetup.length / n), median: median(earliestSetup), p10: pct(earliestSetup, 0.1), p90: pct(earliestSetup, 0.9), at_or_before_onset: r3(earliestSetup.filter((x) => x <= 0).length / n) }, earliest_trigger_rel_onset: { detected: earliestTrigger.length, share: r3(earliestTrigger.length / n), median: median(earliestTrigger), p10: pct(earliestTrigger, 0.1), p90: pct(earliestTrigger, 0.9), at_or_before_onset: r3(earliestTrigger.filter((x) => x <= 0).length / n) }, setup_present_before_onset_by_family: Object.fromEntries(Object.entries(perFamSetup).map(([k, v]) => [k, r3(v / n)])) }; }
const FAIL_LABEL = { A: 'FALSE_EXPANSION', B: 'FAILED_RECLAIM', C: 'FAILED_BREAKOUT', D: 'CONTINUATION_FAILURE', E: 'FAKE_MOMENTUM', F: 'RANGE_REENTRY', G: 'CONTINUATION_FAILURE' };
function falseMove(S, sigs) { // signals (unblocked) not followed by a same-direction onset within [i-6, i+12]; failure label from the next 12 bars (labelling only)
  const out = { signals: 0, followed: 0, false: 0, labels: {}, false_expectancy_r: null, followed_expectancy_r: null, fp_rate_24: null }; const fR = [], tR = []; let fp24 = 0; for (const s of sigs) { if (!inS(S)(s) || s.block) continue; out.signals++; const o = exitF(s); const followed = onsetNear(S, s.i, s.side, -6, 12); if (!onsetNear(S, s.i, s.side, -6, 24)) fp24++; if (followed) { out.followed++; if (o.r != null) tR.push(o.r); continue; } out.false++; if (o.r != null) fR.push(o.r); const A = s.atr; let label = 'NO_FOLLOW_THROUGH'; const end = Math.min(N - 1, s.i + 12); const lvl = s.anchorLevel; for (let j = s.i + 1; j <= end; j++) { const c = b5[j].close; if (s.fam === 'A' && (s.side === 'BUY' ? c < lvl : c > lvl)) { label = FAIL_LABEL.A; break; } if (s.fam === 'B' && (s.side === 'SELL' ? b5[j].high > s.geo.sl : b5[j].low < s.geo.sl)) { label = FAIL_LABEL.B; break; } if (s.fam === 'C' && (s.side === 'BUY' ? c < lvl : c > lvl)) { label = FAIL_LABEL.C; break; } if ((s.fam === 'D' || s.fam === 'G') && (s.side === 'BUY' ? c < s.geo.sl : c > s.geo.sl)) { label = FAIL_LABEL.D; break; } if (s.fam === 'F' && (s.side === 'BUY' ? c < lvl : c > lvl)) { label = FAIL_LABEL.F; break; } } if (s.fam === 'E' && label === 'NO_FOLLOW_THROUGH' && F.mom6[end] != null && (s.side === 'BUY' ? F.mom6[end] <= 0 : F.mom6[end] >= 0)) label = FAIL_LABEL.E; out.labels[label] = (out.labels[label] ?? 0) + 1; }
  out.false_rate = out.signals ? r3(out.false / out.signals) : null; out.fp_rate_24 = out.signals ? r3(fp24 / out.signals) : null; out.false_expectancy_r = r3(mean(fR)); out.followed_expectancy_r = r3(mean(tR)); out.false_n = fR.length; out.followed_n = tR.length; return out; }
const ctlFalse = (S) => { const sigs = ctlSigs(S).map((c) => ({ ...c, fam: 'CONTROL', block: null, atr: c.atr })); let fp = 0, n = 0; for (const s of sigs) { n++; if (!onsetNear(S, s.i, s.side, -6, 24)) fp++; } return { signals: n, fp_rate_24: r3(fp / n) }; };

// ---------- evaluation ----------
function evaluate(rows, S, { block = true } = {}) { const sess = sessions[S]; const w = seqWalk(rows); const st = stats(w.trades, sess, { block }); const q = {}; for (const x of w.trades) (q[quarter(x.e.t)] ??= []).push(x); const walk = Object.fromEntries(Object.entries(q).sort().map(([k, v]) => { const s = stats(v, null, { ci: false }); return [k, { n: s.n, expectancy_r: s.expectancy_r, pf: s.pf, max_dd_r: s.max_dd_r, trades_per_session: r2(v.length / new Set(v.map((x) => day(x.e.t))).size) }]; })); const pos = Object.values(walk).filter((v) => v.expectancy_r > 0).length;
  const shuffle = w.trades.length ? (() => { const rand = rng(11); const byM = {}; for (const x of w.trades) (byM[month(x.e.t)] ??= []).push(x.o.r); const dds = [], streaks = []; for (let k = 0; k < 500; k++) { const order = Object.values(byM).sort(() => rand() - 0.5); let cum = 0, peak = 0, dd = 0, stk = 0, ms = 0; for (const m of order) for (const r of [...m].sort(() => rand() - 0.5)) { cum += r; peak = Math.max(peak, cum); dd = Math.max(dd, peak - cum); if (r <= 0) { stk++; ms = Math.max(ms, stk); } else stk = 0; } dds.push(dd); streaks.push(ms); } return { dd_r_p50: r2(median(dds)), dd_r_p90: r2(pct(dds, 0.9)), dd_r_p99: r2(pct(dds, 0.99)), loss_streak_p50: median(streaks), loss_streak_p90: pct(streaks, 0.9) }; })() : null;
  const ex = {}; for (const x of w.trades) ex[x.o.exit] = (ex[x.o.exit] ?? 0) + 1; const exit_mix = Object.fromEntries(Object.entries(ex).map(([k, v]) => [k, r3(v / Math.max(1, w.trades.length))]));
  return { signals: rows.length, ...st, exit_mix, skipped: w.skipped, walk_forward: walk, quarters_positive_share: Object.keys(walk).length ? r3(pos / Object.keys(walk).length) : null, adverse: shuffle, occ: w.occ, trades: w.trades }; }
function tinyCells(trades) { const cells = {}; for (const x of trades) (cells[`${x.e.fam}|${x.e.side}|${x.e.rg5 ?? x.e.row?.rg5 ?? 'NA'}`] ??= []).push(x.o.r); const net = trades.reduce((s, x) => s + x.o.r, 0); let maxTiny = 0, maxCell = null, sumTiny = 0; const list = Object.entries(cells).map(([k, v]) => { const s = v.reduce((a, b) => a + b, 0); if (v.length < 30 && s > 0) { sumTiny += s; if (s > maxTiny) { maxTiny = s; maxCell = k; } } return { cell: k, n: v.length, net_r: r2(s), share_of_net: net > 0 ? r3(s / net) : null }; }).sort((a, b) => b.net_r - a.net_r); return { cells: list.slice(0, 12), max_tiny_cell: maxCell, max_tiny_cell_share: net > 0 ? r3(maxTiny / net) : null, tiny_sum_share: net > 0 ? r3(sumTiny / net) : null, pass: !(net > 0) || maxTiny / net <= 0.30 }; }
const timingClass = (s) => (s.disp < 0.3 ? 'EARLY' : s.disp <= 1.5 ? 'VALID' : 'LATE_CHASED');
function byGroup(rows, keyFn) { const g = {}; for (const x of rows) (g[keyFn(x)] ??= []).push(x); return Object.fromEntries(Object.entries(g).sort((a, b) => b[1].length - a[1].length).map(([k, v]) => [k, cell(v)])); }
const htfState = (s) => { const al = (rg) => (rg === 'BULL_TREND' ? 'BUY' : rg === 'BEAR_TREND' ? 'SELL' : null); const m = al(s.m30r), h = al(s.h1r); const agree = [m, h].filter(Boolean); if (!agree.length) return 'NEUTRAL'; if (agree.every((d) => d === s.side)) return 'ALIGNED'; if (agree.every((d) => d !== s.side)) return 'CONFLICTING'; return 'MIXED'; };
const terc = (rows, f) => { const v = rows.map(f).filter((x) => x != null).sort((a, b) => a - b); if (v.length < 9) return null; const c1 = v[Math.floor(v.length / 3)], c2 = v[Math.floor((2 * v.length) / 3)]; return { cuts: [r3(c1), r3(c2)], LOW: cell(rows.filter((x) => f(x) < c1)), MID: cell(rows.filter((x) => f(x) >= c1 && f(x) < c2)), HIGH: cell(rows.filter((x) => f(x) >= c2)) }; };
function diagnoseRows(S, sigsAll, rows, ev) { const unb = rowsOf(sigsAll.filter(inS(S))); return { timing: byGroup(unb, (x) => timingClass(x.e)), timing_setup_age: terc(unb, (x) => x.e.setupAge), direction: byGroup(unb, (x) => x.e.side), regime: byGroup(unb, (x) => x.e.rg5 ?? 'NA'), htf: byGroup(unb, (x) => htfState(x.e)), location: { risk_atr: terc(unb, (x) => x.e.riskAtr), displacement_atr: terc(unb, (x) => x.e.disp), dist_swing_high_atr: terc(unb, (x) => F.dSH[x.e.i]), dist_swing_low_atr: terc(unb, (x) => F.dSL[x.e.i]) }, blocked: sigsAll.filter(inS(S)).filter((s) => s.block).reduce((g, s) => { g[s.block] = (g[s.block] ?? 0) + 1; return g; }, {}), raw_signals: sigsAll.filter(inS(S)).length, unblocked_signals: unb.length, independent: cell(unb) }; }

// ---------- pre-move feature research ----------
const FEATS = { atr_pct_288: (t) => F.atrPct[t], range12_atr: (t) => F.rng12[t], range24_atr: (t) => F.rng24[t], contraction_12_vs_prev12: (t) => F.contraction[t], overlap6: (t) => F.overlap6[t], body_ratio: (t) => F.body[t], close_location: (t) => F.closeLoc[t], bar_range_atr: (t) => F.rngA[t], ema20_slope6_atr: (t) => F.slope20[t], mom6_atr: (t) => F.mom6[t], mom12_atr: (t) => F.mom12[t], accel_atr: (t) => F.accel[t], abs_mom6_atr: (t) => (F.mom6[t] == null ? null : Math.abs(F.mom6[t])), run_abs: (t) => Math.abs(F.run[t]), dist_swing_high_atr: (t) => F.dSH[t], dist_swing_low_atr: (t) => F.dSL[t], swing_width_atr: (t) => F.swingW[t], bars_since_sweep: (t) => F.sinceSweep[t], bars_since_failed_bo: (t) => F.sinceFailedBO[t] };
const CATS = { regime_5m: (t) => ROWS.get(t)?.rg5 ?? 'NA', bias_15m: (t) => ROWS.get(t)?.b15d ?? 'NA', regime_30m: (t) => ROWS.get(t)?.m30r ?? 'NA', regime_1h: (t) => ROWS.get(t)?.h1r ?? 'NA', ema20_vs_ema50: (t) => (F.trendUp[t] ? 'UP' : F.trendDn[t] ? 'DOWN' : 'FLAT'), equal_highs: (t) => String(F.eqHigh[t]), equal_lows: (t) => String(F.eqLow[t]), setup_A_w2_5: (t) => String(!!SETUP.A(t, { wA: 2.5 })), setup_E_quiet: (t) => String(!!SETUP.E(t)), setup_F_w3: (t) => String(!!SETUP.F(t, { wF: 3 })) };
function preMoveResearch(S) { const base = ROWLIST.filter((r) => r.split === S && r.i >= 400).map((r) => r.i); const evs = EVENTS[S]; const out = { numeric: {}, categorical: {}, events: evs.length, baseline_candles: base.length, magnitude_atr: { median: median(evs.map((e) => e.magnitude_atr)), p90: pct(evs.map((e) => e.magnitude_atr), 0.9) }, time_to_move_bars: { median: median(evs.map((e) => e.time_to_move)), p10: pct(evs.map((e) => e.time_to_move), 0.1), p90: pct(evs.map((e) => e.time_to_move), 0.9) }, direction: evs.reduce((g, e) => { g[e.dir] = (g[e.dir] ?? 0) + 1; return g; }, {}) };
  for (const [name, f] of Object.entries(FEATS)) { const bv = base.map(f).filter((x) => x != null).sort((a, b) => a - b); if (bv.length < 100) continue; const cuts = [1, 2, 3, 4].map((q) => bv[Math.floor((q / 5) * bv.length)]); const qOf = (v) => cuts.filter((c) => v >= c).length; const baseQ = [0, 0, 0, 0, 0]; for (const v of bv) baseQ[qOf(v)]++; const pre = evs.map((e) => f(e.k)).filter((x) => x != null); const preW = []; for (const e of evs) { const vals = []; for (let j = e.k - 6; j <= e.k - 1; j++) { const v = f(j); if (v != null) vals.push(v); } if (vals.length) preW.push(mean(vals)); } const preQ = [0, 0, 0, 0, 0]; for (const v of pre) preQ[qOf(v)]++; const dirDiff = (() => { const up = evs.filter((e) => e.dir === 'BUY').map((e) => f(e.k)).filter((x) => x != null), dn = evs.filter((e) => e.dir === 'SELL').map((e) => f(e.k)).filter((x) => x != null); return { buy_median: r3(median(up)), sell_median: r3(median(dn)) }; })();
    out.numeric[name] = { base_median: r3(median(bv)), pre_median: r3(median(pre)), pre_window_median: r3(median(preW)), quintile_cuts: cuts.map(r3), base_share: baseQ.map((x) => r3(x / bv.length)), pre_share: preQ.map((x) => r3(x / Math.max(1, pre.length))), lift: preQ.map((x, q) => r3((x / Math.max(1, pre.length)) / Math.max(1e-9, baseQ[q] / bv.length))), ...dirDiff, n_pre: pre.length }; }
  for (const [name, f] of Object.entries(CATS)) { const bc = {}, pc = {}; for (const i of base) bc[f(i)] = (bc[f(i)] ?? 0) + 1; for (const e of evs) pc[f(e.k)] = (pc[f(e.k)] ?? 0) + 1; out.categorical[name] = Object.fromEntries(Object.keys(bc).sort().map((k) => [k, { base_share: r3(bc[k] / base.length), pre_share: r3((pc[k] ?? 0) / evs.length), lift: r3(((pc[k] ?? 0) / evs.length) / Math.max(1e-9, bc[k] / base.length)) }])); }
  return out; }
function featureEconomics(S, sigs) { // pooled unblocked trigger signals of the selected grid points: expectancy by feature quintile at the trigger bar (monotonicity check)
  const rows = rowsOf(sigs.filter(inS(S))); const out = {}; for (const [name, f] of Object.entries(FEATS)) { const vals = rows.map((x) => f(x.e.i)); const sorted = vals.filter((v) => v != null).sort((a, b) => a - b); if (sorted.length < 100) continue; const cuts = [1, 2, 3, 4].map((q) => sorted[Math.floor((q / 5) * sorted.length)]); const g = [[], [], [], [], []]; rows.forEach((x, idx) => { const v = vals[idx]; if (v == null) return; g[cuts.filter((c) => v >= c).length].push(x); }); const ex = g.map((v) => (v.length ? r3(mean(v.map((x) => x.o.r))) : null)); let mono = 0; for (let q = 1; q < 5; q++) { if (ex[q] != null && ex[q - 1] != null) mono += Math.sign(ex[q] - ex[q - 1]); } out[name] = { cuts: cuts.map(r3), n: g.map((v) => v.length), expectancy_r: ex, monotonic: Math.abs(mono) === 4 ? (mono > 0 ? 'INCREASING' : 'DECREASING') : 'NON_MONOTONIC' }; } return out; }

// ---------- family grid evaluation and selection (DEV) ----------
function gridEval(S) { const out = {}; for (const g of GRID) { const sigs = SIG[g.key].filter(inS(S)); const rows = rowsOf(sigs); const w = seqWalk(rows); const st = stats(w.trades, sessions[S], { ci: w.trades.length >= 30 }); const stress = stats(seqWalk(rowsOf(sigs, 'stress')).trades, null, { ci: false }); const buy = cell(rows.filter((x) => x.e.side === 'BUY')), sell = cell(rows.filter((x) => x.e.side === 'SELL')); const fm = falseMove(S, sigs); let precedes = 0; for (const s of sigs) if (!s.block && onsetNear(S, s.i, s.side, -6, 12)) precedes++; out[g.key] = { fam: g.fam, variant: g.variant, p: g.p, raw: sigs.length, blocked: sigs.filter((s) => s.block).length, independent: cell(rows), sequential: { n: st.n ?? 0, expectancy_r: st.expectancy_r, pf: st.pf, max_dd_r: st.max_dd_r, ci95_r: st.ci95_r, trades_per_session: st.trades_per_session?.median ?? null }, stress_expectancy_r: stress.expectancy_r, buy, sell, precedes_move_rate: rows.length ? r3(precedes / rows.length) : null, false_rate: fm.false_rate, fp_rate_24: fm.fp_rate_24, capture: captureStats(S, rows, w.occ).capture_rate }; } return out; }
function selectFinalists(GE) { const fin = {}; for (const fam of ['A', 'B', 'C', 'D', 'E', 'F', 'G']) { const pts = GRID.filter((g) => g.fam === fam).map((g) => ({ key: g.key, ...GE[g.key] })).filter((x) => x.sequential.n >= 80); let best = null; for (const x of pts) if (!best || x.sequential.expectancy_r > best.sequential.expectancy_r) best = x; if (!best) { const any = GRID.filter((g) => g.fam === fam).map((g) => ({ key: g.key, ...GE[g.key] })).sort((a, b) => (b.sequential.n ?? 0) - (a.sequential.n ?? 0))[0]; fin[`S${'ABCDEFG'.indexOf(fam) + 1}`] = { family: fam, grid_key: any.key, variant: any.variant, params: any.p, dev_n: any.sequential.n, dev_expectancy_r: any.sequential.expectancy_r, dev_pf: any.sequential.pf, dev_stress_r: any.stress_expectancy_r, supported: false, note: 'no grid point reached DEV N >= 80; largest-N point carried, UNSUPPORTED' }; continue; } fin[`S${'ABCDEFG'.indexOf(fam) + 1}`] = { family: fam, grid_key: best.key, variant: best.variant, params: best.p, dev_n: best.sequential.n, dev_expectancy_r: best.sequential.expectancy_r, dev_pf: best.sequential.pf, dev_stress_r: best.stress_expectancy_r, supported: best.sequential.expectancy_r > 0 && best.sequential.pf > 1.05 && best.stress_expectancy_r > 0 }; }
  const combos = {}; const pairs = { 'S1+S3': ['S1', 'S3'], 'S2+S3': ['S2', 'S3'], 'S4+S3': ['S4', 'S3'], 'S1+S5': ['S1', 'S5'] }; for (const [name, [a, b]] of Object.entries(pairs)) { if (!fin[a].supported || !fin[b].supported) { combos[name] = { components: [a, b], tested: false, reason: 'a component is UNSUPPORTED on DEV' }; continue; } const sigs = unionSignals([SIG[fin[a].grid_key], SIG[fin[b].grid_key]]).filter((s) => s.split === 'DEV'); const rows = rowsOf(sigs); const w = seqWalk(rows); const st = stats(w.trades, null, { ci: false }); const cap = captureStats('DEV', rows, w.occ).capture_rate; const ea = GE[fin[a].grid_key], eb = GE[fin[b].grid_key]; const keep = st.expectancy_r >= Math.max(ea.sequential.expectancy_r, eb.sequential.expectancy_r) && cap > Math.max(ea.capture, eb.capture); combos[name] = { components: [a, b], tested: true, dev_n: st.n, dev_expectancy_r: st.expectancy_r, dev_pf: st.pf, dev_capture: cap, kept: keep }; }
  return { derived_from: 'DEV', finalists: fin, combinations: combos, candidates: [...Object.keys(fin), ...Object.entries(combos).filter(([, v]) => v.kept).map(([k]) => k)] }; }
function unionSignals(lists) { const by = new Map(); for (const l of lists) for (const s of l) { const k = s.i; const cur = by.get(k); if (!cur) by.set(k, { ...s }); else if (cur.side !== s.side) by.set(k, { ...cur, conflict: true }); } return [...by.values()].filter((s) => !s.conflict).sort((a, b) => a.i - b.i); }
const candSignals = (defn, name) => { if (defn.finalists[name]) return SIG[defn.finalists[name].grid_key]; const [a, b] = defn.combinations[name].components; return unionSignals([SIG[defn.finalists[a].grid_key], SIG[defn.finalists[b].grid_key]]); };
const candMembers = (defn, name) => { const names = defn.finalists[name] ? [name] : defn.combinations[name].components; return names.map((n) => ({ fam: defn.finalists[n].family, p: defn.finalists[n].params, sigsAll: SIG[defn.finalists[n].grid_key] })); };
function neighbourhood(defn, name, S) { const f = defn.finalists[name]; if (!f) return { note: 'combination: see components' }; const out = {}; const ev = (key) => { const rows = rowsOf(SIG[key].filter(inS(S))); const s = stats(seqWalk(rows).trades, null, { ci: false }); return { n: s.n ?? 0, expectancy_r: s.expectancy_r, pf: s.pf }; }; const cls = (o) => { const v = Object.values(o).map((x) => x.expectancy_r ?? -9); const centre = o[f.grid_key]?.expectancy_r ?? -9; return v.every((x) => x > 0) ? 'ROBUST' : centre > 0 && v.some((x) => x > 0) ? 'SENSITIVE' : centre > 0 ? 'FRAGILE' : 'NEGATIVE_CENTRE'; }; for (const pk of Object.keys(f.params)) { const nb = {}; for (const g of GRID) if (g.fam === f.family && g.variant === f.variant && Object.keys(g.p).every((k) => k === pk || g.p[k] === f.params[k])) nb[g.key] = ev(g.key); out[pk] = { ...nb, classification: cls(nb) }; } const vars = {}; for (const g of GRID) if (g.fam === f.family && JSON.stringify(g.p) === JSON.stringify(f.params)) vars[g.key] = ev(g.key); out.variant = { ...vars, classification: cls(vars) }; if (!Object.keys(f.params).length && Object.keys(vars).length <= 1) out.variant.note = 'no parameter family (structure-only rule)'; return out; }
function evaluateCandidate(defn, name, S) { const sigsAll = candSignals(defn, name); const rows = rowsOf(sigsAll.filter(inS(S))); const ev = evaluate(rows, S); const stress = stats(seqWalk(rowsOf(sigsAll.filter(inS(S)), 'stress')).trades, null, { ci: false }); const drift = stats(seqWalk(rowsOf(sigsAll.filter(inS(S)), 'drift')).trades, null, { ci: false }); const members = candMembers(defn, name); const fx = forensics(S, members, rows, ev.occ); const fm = falseMove(S, sigsAll); return { definition: defn.finalists[name] ?? defn.combinations[name], ...ev, stress: { n: stress.n ?? 0, expectancy_r: stress.expectancy_r, pf: stress.pf }, drift: { n: drift.n ?? 0, expectancy_r: drift.expectancy_r, pf: drift.pf }, move_capture: captureStats(S, rows, ev.occ), forensics: fx, false_move: fm, tiny_cells: ev.n ? tinyCells(ev.trades) : null, diagnostics: diagnoseRows(S, sigsAll, rows, ev), neighbourhood: neighbourhood(defn, name, S), occ: undefined, trades: undefined }; }
function evaluateControl(S) { const rows = ctlRows(S); const ev = evaluate(rows, S); const stress = stats(seqWalk(ctlRows(S, 'stress')).trades, null, { ci: false }); const drift = stats(seqWalk(ctlRows(S, 'drift')).trades, null, { ci: false }); const unb = rows; return { ...ev, stress: { n: stress.n, expectancy_r: stress.expectancy_r, pf: stress.pf }, drift: { n: drift.n, expectancy_r: drift.expectancy_r, pf: drift.pf }, move_capture: captureStats(S, rows, ev.occ), false_move: ctlFalse(S), tiny_cells: tinyCells(ev.trades.map((x) => ({ ...x, e: { ...x.e, fam: x.e.model, rg5: x.e.rg5 } }))), diagnostics: { direction: byGroup(unb, (x) => x.e.side), regime: byGroup(unb, (x) => x.e.rg5 ?? 'NA'), htf: byGroup(unb, (x) => htfState(x.e)) }, occ: undefined, trades: undefined }; }

// ---------- run ----------
const result = { meta: { phase: PHASE, generated_utc: new Date().toISOString(), prereg_sha256: PREREG_SHA, control_baseline_sha256: CONTROL_SHA, controls: ctrl, bars: N, rows: ROWLIST.length, control_signals: C.filter((c) => c.isSig).length, sessions_dev: sessions.DEV.size, sessions_hold: sessions.HOLD.size, split: SPLIT, costs: COSTS, rr: RR, atr_floor_usd: ATR_FLOOR_USD, risk_atr: [MIN_RISK_ATR, MAX_RISK_ATR], grid: GRID.map((g) => g.key), events: { DEV: EVENTS.DEV.length, HOLD: EVENTS.HOLD.length } } };
console.log('DEV: control, pre-move research, grid ...'); result.DEV = { control: evaluateControl('DEV'), pre_move: preMoveResearch('DEV'), grid: gridEval('DEV') };
{ const c = result.DEV.control; const v3 = JSON.parse(readFileSync(join(REPO, 'research', 'entry_edge_v3', 'results', 'v3_results.json'), 'utf8')).finalists.DEV.CONTROL; if (c.n !== v3.n || c.expectancy_r !== v3.expectancy_r || c.max_dd_r !== v3.max_dd_r || c.move_capture.capture_rate !== v3.move_capture.capture_rate || c.move_capture.no_setup_or_trigger_rate !== v3.move_capture.no_setup_or_trigger_rate) throw new Error('CONTROL does not reproduce V3 DEV CONTROL'); result.meta.controls.control_reproduces_v3_dev = true; }
const defPath = join(CFG, 'finalists.json');
if (PHASE === 'DEV') { const defn = selectFinalists(result.DEV.grid); result.finalist_definitions = defn; result.DEV.candidates = {}; for (const name of defn.candidates) result.DEV.candidates[name] = evaluateCandidate(defn, name, 'DEV'); result.DEV.feature_economics = featureEconomics('DEV', Object.values(defn.finalists).flatMap((f) => SIG[f.grid_key])); result.DEV.events_sample = EVENTS.DEV.slice(0, 30); writeFileSync(defPath, JSON.stringify(defn, null, 1)); writeFileSync(join(OUT, 'v4_results_DEV_phase.json'), JSON.stringify(result, null, 1)); console.log('DERIVED', JSON.stringify(defn)); console.log('finalists.json sha256', shaFile(defPath)); }
else { const defn = JSON.parse(readFileSync(defPath, 'utf8')); const frozen = readFileSync(join(CFG, 'finalists.sha256'), 'utf8').trim().split(/\s+/)[0]; if (shaFile(defPath) !== frozen) throw new Error('finalists.json does not match its frozen hash'); result.finalist_definitions = defn; result.finalists_sha256 = frozen; result.DEV.candidates = {}; for (const name of defn.candidates) result.DEV.candidates[name] = evaluateCandidate(defn, name, 'DEV'); result.DEV.feature_economics = featureEconomics('DEV', Object.values(defn.finalists).flatMap((f) => SIG[f.grid_key]));
  console.log('HOLD ...'); result.HOLD = { control: evaluateControl('HOLD'), pre_move: preMoveResearch('HOLD'), grid: gridEval('HOLD'), candidates: {} }; for (const name of defn.candidates) result.HOLD.candidates[name] = evaluateCandidate(defn, name, 'HOLD'); result.HOLD.feature_economics = featureEconomics('HOLD', Object.values(defn.finalists).flatMap((f) => SIG[f.grid_key]));
  { const c = result.HOLD.control; const v3 = JSON.parse(readFileSync(join(REPO, 'research', 'entry_edge_v3', 'results', 'v3_results.json'), 'utf8')).finalists.HOLD.CONTROL; if (c.n !== v3.n || c.expectancy_r !== v3.expectancy_r || c.max_dd_r !== v3.max_dd_r || c.move_capture.capture_rate !== v3.move_capture.capture_rate) throw new Error('CONTROL does not reproduce V3 HOLD CONTROL'); result.meta.controls.control_reproduces_v3_hold = true; }
  const H = result.HOLD.candidates, ctl = result.HOLD.control; const ctlNS = ctl.move_capture.no_setup_or_trigger_rate; const dec = {}; for (const name of defn.candidates) { const c = H[name]; if (!c.n) { dec[name] = { status: 'EMPTY', reasons: ['no trades'] }; continue; } const reasons = []; if (!(c.expectancy_r > 0)) reasons.push('(1) normal expectancy<=0'); if (!(c.stress.expectancy_r > 0)) reasons.push('(2) stress expectancy<=0'); if (!(c.pf > 1.10)) reasons.push('(3) PF<=1.10'); if (!(c.expectancy_r >= ctl.expectancy_r + 0.10)) reasons.push('(4) improvement < +0.10 R over CONTROL'); if (!(c.max_dd_r <= ctl.max_dd_r)) reasons.push('(5) DD worse than CONTROL'); if (!(c.n >= 200)) reasons.push('(6) N<200'); if (c.tiny_cells && !c.tiny_cells.pass) reasons.push('(7) tiny-cell dependence'); if (!((c.quarters_positive_share ?? 0) >= 0.6)) reasons.push('(8) quarters positive <60%'); const nbBad = Object.entries(c.neighbourhood).filter(([, v]) => v && v.classification && v.classification !== 'ROBUST').map(([k, v]) => `${k}:${v.classification}`); if (nbBad.length) reasons.push(`(9) thresholds not ROBUST (${nbBad.join(', ')})`); if (!(c.ci95_r?.[0] > 0)) reasons.push('(10) trade CI includes 0'); if (!(c.block_ci95_r?.[0] > 0)) reasons.push('(10) session-block CI includes 0'); const nsV4 = c.forensics.rates.NO_SETUP + c.forensics.rates.SETUP_NO_TRIGGER; const detection = c.move_capture.capture_rate >= ctl.move_capture.capture_rate && nsV4 <= ctlNS - 0.10; if (!detection) reasons.push(`(14) detection not improved (capture ${c.move_capture.capture_rate} vs ${ctl.move_capture.capture_rate}; no-setup/no-trigger ${r3(nsV4)} vs ${ctlNS})`); if (!(c.false_move.fp_rate_24 <= ctl.false_move.fp_rate_24)) reasons.push(`(15) false-positive rate ${c.false_move.fp_rate_24} > CONTROL ${ctl.false_move.fp_rate_24}`); if (!(result.DEV.candidates[name].expectancy_r > 0)) reasons.push('DEV expectancy<=0'); if (!(c.drift.expectancy_r > 0)) reasons.push('drift expectancy<=0'); const onlyCI = reasons.length > 0 && reasons.every((r) => r.startsWith('(10)')); dec[name] = { status: reasons.length ? (onlyCI ? 'PROMISING_INCONCLUSIVE (fails only the CI requirement)' : 'FAILS_GATE') : 'PASS', reasons, hold_n: c.n, hold_expectancy_r: c.expectancy_r, hold_pf: c.pf, hold_dd_r: c.max_dd_r, ci95_r: c.ci95_r, block_ci95_r: c.block_ci95_r, dev_expectancy_r: result.DEV.candidates[name].expectancy_r, capture: c.move_capture.capture_rate, no_setup_no_trigger: r3(nsV4), fp_rate_24: c.false_move.fp_rate_24, detection_met: detection }; }
  const passing = Object.entries(dec).filter(([, d]) => d.status === 'PASS').map(([k]) => k); const withN = Object.entries(dec).filter(([, d]) => d.hold_n >= 200); const best = passing[0] ?? (withN.length ? withN.sort((a, b) => (b[1].hold_expectancy_r ?? -9) - (a[1].hold_expectancy_r ?? -9))[0][0] : Object.entries(dec).sort((a, b) => (b[1].hold_expectancy_r ?? -9) - (a[1].hold_expectancy_r ?? -9))[0]?.[0] ?? null); const anyPos = Object.values(dec).some((d) => d.hold_n >= 200 && d.hold_expectancy_r > 0 && !(d.ci95_r?.[0] > 0)); const b = best ? H[best] : null;
  const bestDet = best ? Object.values(dec).find((d) => d === dec[best]).detection_met : false; const bestSetup = Object.entries(H).filter(([k]) => defn.finalists[k]).sort((a, b) => (b[1].forensics.earliest_setup_rel_onset.at_or_before_onset ?? 0) - (a[1].forensics.earliest_setup_rel_onset.at_or_before_onset ?? 0))[0]?.[0] ?? null; const bestTrigger = Object.entries(H).filter(([k]) => defn.finalists[k]).sort((a, b) => (b[1].move_capture.capture_rate ?? 0) - (a[1].move_capture.capture_rate ?? 0))[0]?.[0] ?? null;
  result.decisions = { candidates: dec, passing, best_candidate: best, best_setup_by_detection: bestSetup, best_trigger_by_capture: bestTrigger, v4_pass: passing.length > 0, edge_demonstrated: passing.length ? 'YES' : anyPos ? 'INCONCLUSIVE' : 'NO', v4_beats_control: b ? ((b.ci95_r?.[0] > ctl.expectancy_r && b.max_dd_r <= ctl.max_dd_r && bestDet) ? 'YES' : b.expectancy_r > ctl.expectancy_r ? 'INCONCLUSIVE' : 'NO') : 'NO', demo_eligible: passing.length ? 'YES (subject to parity fixtures)' : 'NO' };
  writeFileSync(join(OUT, 'v4_results.json'), JSON.stringify(result, null, 1)); console.log('DECISIONS', JSON.stringify(result.decisions, null, 1)); }
console.log('written', PHASE);
