/**
 * HISTORICAL FREQUENCY RECONCILIATION + ZERO-TRADE-DAY DISTRIBUTION + LIVE-DAY MARKET CONTEXT. READ-ONLY research.
 * Reproduces V2's "trades/session" metric and recomputes an apples-to-apples production-semantics metric:
 *   signal candles -> NEW theses (production signalStore dedup: same side + same round2(anchor) folded while OPEN;
 *   OPEN resolves on 5m bars by SL/TP2 first touch) -> executor (one position, production exit stack from the Edge Lab
 *   production simulation, daily cap 10, POSITION_ALREADY_OPEN skips never retried).
 * Usage: node historical_reconciliation.mjs <parity_results.json>
 */
import { readFileSync, writeFileSync, createReadStream } from 'node:fs';
import { createInterface } from 'node:readline';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const HERE = dirname(fileURLToPath(import.meta.url)); const REPO = join(HERE, '..', '..', '..'); const OUT = join(REPO, 'research', 'live_replay_parity_audit', 'results'); const LAB = join(REPO, 'handoff', 'edge_discovery_lab', 'data');
const PARITY = JSON.parse(readFileSync(process.argv[2], 'utf8'));
const BARS = JSON.parse(readFileSync(join(LAB, 'XAUUSDm_bars.json'), 'utf8')); const b5 = BARS['5m'];
const iso = (t) => new Date(t * 1000).toISOString(); const day = (t) => iso(t).slice(0, 10); const r2 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 100) / 100); const r3 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 1000) / 1000);
const EXCL = '2026-09-30';
const pct = (a, p) => { const s = [...a].sort((x, y) => x - y); return s[Math.min(s.length - 1, Math.floor(p * s.length))]; }; const median = (a) => pct(a, 0.5); const mean = (a) => (a.length ? a.reduce((s, x) => s + x, 0) / a.length : null);
const percentileOf = (arr, v) => r3(arr.filter((x) => x <= v).length / arr.length);
// ---------- sessions and per-session market features from lab rows ----------
const sess = {}; const rl = createInterface({ input: createReadStream(join(LAB, 'lab_rows.jsonl')) });
for await (const line of rl) { if (!line) continue; const r = JSON.parse(line); const d = day(r.t); if (d === EXCL) continue; const s = (sess[d] ??= { candles: 0, atr: [], atrR: [], trend5: 0, comp5: 0, dir15: 0, breaks: 0, no_elig: 0, cand: 0, sig: 0, r15: {}, r30: {}, b1h: {} }); s.candles++; if (r.atr != null) s.atr.push(r.atr); if (r.atrR != null) s.atrR.push(r.atrR); if (r.rg5 === 'BULL_TREND' || r.rg5 === 'BEAR_TREND') s.trend5++; if (r.rg5 === 'COMPRESSION' || r.rg5 === 'RANGE') s.comp5++; if (r.b15d === 'BULLISH' || r.b15d === 'BEARISH') s.dir15++; if (r.evAge === 0) s.breaks++; if (r.wr === 'NO_ELIGIBLE_STRATEGY') s.no_elig++; if (r.mdl || ['NO_GOOD_ENTRY', 'RR_NOT_ACCEPTABLE', 'ENTRY_CONFLICT', 'HTF_CONFLICT', 'OVEREXTENDED', 'VOLATILITY_INSUFFICIENT'].includes(r.wr)) s.cand++; if (r.act === 'BUY' || r.act === 'SELL') s.sig++; s.r15[r.b15r] = (s.r15[r.b15r] ?? 0) + 1; s.r30[r.m30r] = (s.r30[r.m30r] ?? 0) + 1; s.b1h[r.h1s] = (s.b1h[r.h1s] ?? 0) + 1; }
const days = Object.keys(sess).sort(); const full = days.filter((d) => sess[d].candles >= 60); // sessions with >= 5h of candles
// ---------- production signal candles and production dedup semantics ----------
const C = readFileSync(join(REPO, 'research', 'entry_architecture_v2', 'results', 'candidates.jsonl'), 'utf8').trim().split('\n').map((l) => JSON.parse(l)).filter((c) => (c.act === 'BUY' || c.act === 'SELL') && day(c.t) !== EXCL).sort((a, b) => a.i - b.i);
const LT = new Map(JSON.parse(readFileSync(join(LAB, 'lab_trades.json'), 'utf8')).filter((t) => t.signal).map((t) => [t.i, t]));
const key = (c) => `${c.side}|${Math.round(c.anchor * 100) / 100}`; // computeSetupId: direction + round2(anchor); regime only when no anchor
function resolveBar(c) { const sl = c.geo.sl, tp2 = c.geo.tp2, long = c.side === 'BUY'; for (let j = c.i + 1; j < b5.length; j++) { const b = b5[j]; const hitSl = long ? b.low <= sl : b.high >= sl; const hitTp = long ? b.high >= tp2 : b.low <= tp2; if (hitSl || hitTp) return j; } return b5.length - 1; }
const open = new Map(); // thesis key -> resolve bar index
const perDay = {}; const DAILY_CAP = 10; let busyUntil = -1; let dayTrades = {};
for (const c of C) { const d = day(c.t); const p = (perDay[d] ??= { signal_candles: 0, new_theses: 0, executed: 0, skipped_position_open: 0, skipped_cap: 0, folded_same_thesis: 0 }); p.signal_candles++;
  for (const [k, rb] of open) if (rb <= c.i) open.delete(k); // resolve theses whose SL/TP2 was touched by this bar (bars strictly after signal bar)
  const k = key(c); if (open.has(k)) { p.folded_same_thesis++; continue; } open.set(k, resolveBar(c)); p.new_theses++;
  // executor: one position, cap 10 per UTC day, production exit stack (Edge Lab prod sim hold)
  const lt = LT.get(c.i); if (c.i <= busyUntil) { p.skipped_position_open++; continue; } dayTrades[d] = dayTrades[d] ?? 0; if (dayTrades[d] >= DAILY_CAP) { p.skipped_cap++; continue; } if (lt?.prod && !lt.prod.skipped) { busyUntil = lt.prod.closeIdx; p.executed++; dayTrades[d]++; } else { p.executed++; dayTrades[d]++; busyUntil = c.i + 6; } }
const dist = (arr) => ({ n: arr.length, mean: r2(mean(arr)), p10: pct(arr, 0.1), p25: pct(arr, 0.25), median: median(arr), p75: pct(arr, 0.75), p90: pct(arr, 0.9), zero: r3(arr.filter((x) => x === 0).length / arr.length), one: r3(arr.filter((x) => x === 1).length / arr.length), two: r3(arr.filter((x) => x === 2).length / arr.length), three: r3(arr.filter((x) => x === 3).length / arr.length), four_six: r3(arr.filter((x) => x >= 4 && x <= 6).length / arr.length), seven_ten: r3(arr.filter((x) => x >= 7 && x <= 10).length / arr.length), over_ten: r3(arr.filter((x) => x > 10).length / arr.length) });
const longestZero = (arr) => { let best = 0, cur = 0; for (const x of arr) { cur = x === 0 ? cur + 1 : 0; best = Math.max(best, cur); } return best; };
const seq = (k) => full.map((d) => perDay[d]?.[k] ?? 0);
const metrics = { sessions_total: days.length, sessions_full_ge_60_candles: full.length, signal_candles: dist(seq('signal_candles')), new_theses_production_dedup: dist(seq('new_theses')), executed_trades_production_stack_cap10: dist(seq('executed')), folded_same_thesis_total: full.reduce((s, d) => s + (perDay[d]?.folded_same_thesis ?? 0), 0), skipped_position_open_total: full.reduce((s, d) => s + (perDay[d]?.skipped_position_open ?? 0), 0), skipped_cap_total: full.reduce((s, d) => s + (perDay[d]?.skipped_cap ?? 0), 0), longest_zero_streak: { signal_candles: longestZero(seq('signal_candles')), new_theses: longestZero(seq('new_theses')), executed: longestZero(seq('executed')) } };
// V2 metric for reference (H2a sequential trades, holdout) is read from the V2 results
const V2 = JSON.parse(readFileSync(join(REPO, 'research', 'capital_harvest_v2', 'results', 'study_results.json'), 'utf8')); const v2h = V2.thresholds['R0_1.70'].HOLD;
const v2 = { definition: 'V2 "trades/session" = SEQUENTIAL H2a-managed hypothetical trades on every production BUY/SELL replay candle (one position at a time; re-entry after exit on any later signal candle not on the same (model,side,anchor) within 12 bars; 3.3-bar average hold; no News V2/shock/spread/drift/breaker gates; no production thesis folding; session = UTC day with >= 1 replay candle; holdout 2026-01 -> 09-29)', median_trades_per_session: v2h.trades_per_session.median, mean: v2h.trades_per_session.mean, zero_rate: v2h.session_rate.zero, trades: v2h.trades };
// today's live values from the parity ledger
const rows = PARITY.rows.filter((r) => !r.replay.error); const today = { candles: rows.length, processed: rows.filter((r) => r.live.processed).length, signal_candles: rows.filter((r) => r.replay.action === 'BUY' || r.replay.action === 'SELL').length, new_theses: 1, executed: 0, atr_mean: r2(mean(rows.map((r) => r.replay.atr))), atrR_mean: r3(mean(rows.map((r) => r.replay.atrRatio))), trend5_share: r3(rows.filter((r) => ['BULL_TREND', 'BEAR_TREND'].includes(r.replay.regime5)).length / rows.length), comp_range5_share: r3(rows.filter((r) => ['COMPRESSION', 'RANGE'].includes(r.replay.regime5)).length / rows.length), dir15_share: r3(rows.filter((r) => r.replay.bias15 !== 'NEUTRAL').length / rows.length), breaks: rows.filter((r) => r.replay.event_age === 0).length, candidates: rows.filter((r) => r.replay.candidate).length, no_elig_share: r3(rows.filter((r) => r.replay.reason === 'NO_ELIGIBLE_STRATEGY').length / rows.length), r15: Object.fromEntries([...new Set(rows.map((r) => r.replay.regime15))].map((k) => [k, rows.filter((r) => r.replay.regime15 === k).length])), r30: Object.fromEntries([...new Set(rows.map((r) => r.replay.regime30))].map((k) => [k, rows.filter((r) => r.replay.regime30 === k).length])), b1h: Object.fromEntries([...new Set(rows.map((r) => r.replay.bias1h))].map((k) => [k, rows.filter((r) => r.replay.bias1h === k).length])), news_blocked_candles: PARITY.summary.news_safety.blocked_candles };
const hist = (f) => full.map((d) => f(sess[d])); const per = (arr, v) => ({ today: v, hist_p10: r2(pct(arr, 0.1)), hist_median: r2(median(arr)), hist_p90: r2(pct(arr, 0.9)), today_percentile: percentileOf(arr, v) });
// scale today's per-candle counts to a full session equivalent where it matters (candidates, breaks are per-candle rates)
const context = { atr_mean_usd: per(hist((s) => mean(s.atr)), today.atr_mean), atr_ratio_mean: per(hist((s) => mean(s.atrR)), today.atrR_mean), share_5m_trend_regime: per(hist((s) => s.trend5 / s.candles), today.trend5_share), share_5m_compression_or_range: per(hist((s) => s.comp5 / s.candles), today.comp_range5_share), share_15m_directional_bias: per(hist((s) => s.dir15 / s.candles), today.dir15_share), structural_breaks_per_100_candles: per(hist((s) => 100 * s.breaks / s.candles), r2(100 * today.breaks / today.candles)), candidates_per_100_candles: per(hist((s) => 100 * s.cand / s.candles), r2(100 * today.candidates / today.candles)), no_eligible_share: per(hist((s) => s.no_elig / s.candles), today.no_elig_share), signal_candles_per_100_candles: per(hist((s) => 100 * s.sig / s.candles), r2(100 * today.signal_candles / today.candles)), sessions_with_15m_directional_share_le_today: r3(full.filter((d) => sess[d].dir15 / sess[d].candles <= today.dir15_share).length / full.length), regimes_today: { r15: today.r15, r30: today.r30, b1h: today.b1h }, news_blocked_candles_today: today.news_blocked_candles };
const todayPercentiles = { signal_candles_today: today.signal_candles, signal_candles_percentile_vs_full_sessions: percentileOf(seq('signal_candles'), today.signal_candles), new_theses_today: today.new_theses, new_theses_percentile: percentileOf(seq('new_theses'), today.new_theses), executed_today: today.executed, executed_zero_rate_hist: metrics.executed_trades_production_stack_cap10.zero, note: 'today has 110 expected candles (frozen ledger 07:30-16:40Z) of a normal ~288; percentiles compare raw counts, so today is disadvantaged by session length; rate-based context percentiles above are length-neutral' };
const out = { v2_metric: v2, apples_to_apples: metrics, today: todayPercentiles, market_context: context, method_notes: ['Production dedup approximated with computeSetupId semantics (direction + round2(candidate anchor); regime only used when no anchor) and resolveOpenSignals (SL/TP2 first touch on 5m bars strictly after the signal bar).', 'Executor approximated with one position, daily cap 10, production exit stack from the Edge Lab production simulation (broker structural/monetary stops, +30 TP, adaptive management); News V2/shock/spread/drift/breaker are not in the replay so these counts are an UPPER bound on live executions.', 'Sessions with fewer than 60 replay candles (holidays, partial days) excluded from distributions.'] };
writeFileSync(join(OUT, 'historical_reconciliation.json'), JSON.stringify(out, null, 1)); console.log(JSON.stringify(out, null, 1));
