/**
 * LIVE vs REPLAY PARITY AUDIT -- 2026-09-30 v9 live window. READ-ONLY research. Imports production pure functions;
 * reads state/, validation/, handoff/edge_discovery_lab data and the scratchpad MT5 bars read-only; writes only results/.
 * Usage: node parity_audit.mjs <mt5_bars.json> <tv30_bars.json>
 */
import { readFileSync, writeFileSync, mkdirSync, createReadStream } from 'node:fs';
import { createInterface } from 'node:readline';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const HERE = dirname(fileURLToPath(import.meta.url)); const REPO = join(HERE, '..', '..', '..'); const OUT = join(REPO, 'research', 'live_replay_parity_audit', 'results'); mkdirSync(OUT, { recursive: true });
const E = (p) => 'file:///' + join(REPO, 'src', 'engine', p).replace(/\\/g, '/');
const { runPipeline } = await import(E('pipeline.js')); const { computeHtfContext } = await import(E('htf.js')); const { computeBias, sideAllowedByBias } = await import(E('intraday/bias.js')); const { runIntradayPipeline, combineIntraday } = await import(E('intraday/pipeline5m.js')); const { classifyRegime, REGIME_PARAMS } = await import(E('regime.js')); const { computeStructure, STRUCTURE_PARAMS } = await import(E('structure.js')); const { computeCorrection, CORRECTION_PARAMS } = await import(E('correction.js')); const { atr, ema } = await import(E('math.js')); const { INTRADAY_PARAMS: P } = await import(E('intraday/params.js'));
const BARS = JSON.parse(readFileSync(process.argv[2], 'utf8')); const TV30 = JSON.parse(readFileSync(process.argv[3], 'utf8')).bars;
const TF = { '5m': 300, '15m': 900, '30m': 1800, '1H': 3600 }; const conf = (tf, T) => BARS[tf].filter((b) => b.time < Math.floor(T / TF[tf]) * TF[tf]).slice(-499);
const iso = (t) => new Date(t * 1000).toISOString(); const hm = (t) => iso(t).slice(11, 16); const r2 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 100) / 100); const r3 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 1000) / 1000);
const START = 1790753400; // 07:30Z first v9 candle

// ---------- LIVE ledger sources ----------
const WAIT = readFileSync(join(REPO, 'state', 'xauusd_wait_opportunity_log.jsonl'), 'utf8').trim().split('\n').map((l) => JSON.parse(l)).filter((r) => r.confirmed_bar_time >= START);
const liveBy = new Map(WAIT.map((r) => [r.confirmed_bar_time, r]));
const END_CANDLE = Number(process.env.PARITY_END_CANDLE ?? 1790786100); // 16:35Z candle (close 16:40Z): frozen ledger end so the window does not drift while reports are written
const lastLive = Math.min(END_CANDLE, Math.max(...WAIT.map((r) => r.confirmed_bar_time)));
const TRADE = readFileSync(join(REPO, 'state', 'xauusd_mt5_real_trade_log.jsonl'), 'utf8').trim().split('\n').map((l) => JSON.parse(l)).filter((r) => r.timestamp.startsWith('2026-09-30'));
const SIGSTORE = JSON.parse(readFileSync(join(REPO, 'validation', 'mcp_engine_signals.json'), 'utf8')); const sigToday = (SIGSTORE.signals ?? []).filter((s) => String(s.created_at).startsWith('2026-09-30'));
const LOG = readFileSync(join(REPO, 'state', 'watcher_real_v9.log'), 'utf8').split('\n');
const IST_OFFSET = 5.5 * 3600; const logUtc = (line) => { const m = line.match(/^\[(\d\d):(\d\d):(\d\d)\]/); if (!m) return null; const d = new Date('2026-09-30T00:00:00Z'); const s = (+m[1]) * 3600 + (+m[2]) * 60 + (+m[3]) - IST_OFFSET; return d.getTime() / 1000 + s; };
const logEvents = { read_failures: [], tick_skips: 0, stalls: [], recoveries: [], baselines: [], alerts: [], exec: [] };
for (const l of LOG) { if (l.includes('Could not read latest confirmed')) logEvents.read_failures.push({ t: logUtc(l), reason: l.includes('bar spacing') ? 'WRONG_TIMEFRAME_SERIES' : l.includes('stale 5m data') ? 'STALE_FORMING_BAR' : 'OHLCV_NOT_EXTRACTABLE' }); else if (l.includes('tick skipped')) logEvents.tick_skips++; else if (l.includes('FEED STALLED')) logEvents.stalls.push(l.slice(0, 160)); else if (l.includes('FEED RECOVERED')) logEvents.recoveries.push(l.slice(0, 160)); else if (l.includes('re-baselining') || l.includes('Watcher baseline')) logEvents.baselines.push(l.slice(0, 160)); else if (l.includes('alert sent')) logEvents.alerts.push(l.slice(0, 160)); else if (l.includes('MT5 execution')) logEvents.exec.push(l.slice(0, 200)); }
// protection timeline from the REAL trade log
const protTimeline = TRADE.filter((r) => r.protection).map((r) => ({ t: Date.parse(r.timestamp) / 1000, blocking: r.protection.blocking, reasons: r.protection.block_reasons ?? [], news: r.protection.news_state, shock: r.protection.shock_state }));
const protAt = (t) => { let cur = { blocking: false, reasons: [], news: 'NORMAL', shock: 'INSUFFICIENT_DATA' }; for (const p of protTimeline) if (p.t <= t) cur = p; return cur; };

// ---------- REPLAY at each candle ----------
function firstFail(b, b15, bias, regime, st, atrRatio, a, e) { const i = b.length - 1; const out = {}; const bs = bias.direction === 'BULLISH' ? 'BUY' : bias.direction === 'BEARISH' ? 'SELL' : null; const allowed = (m, side) => bias.eligible_models.includes(m) && sideAllowedByBias(bias, side);
  if (!bs) out.MC = out.PB = 'bias NEUTRAL'; else { if (!allowed('MC', bs)) out.MC = 'not eligible'; else { const closes = [0, 1, 2].map((k) => ({ c: b[i - k].close, e: e[i - k] })); const onSide = closes.every((x) => (bs === 'BUY' ? x.c > x.e : x.c < x.e)); const prog = [0, 1].every((k) => (bs === 'BUY' ? b[i - k].close > b[i - k - 1].close : b[i - k].close < b[i - k - 1].close)); const sw = bs === 'BUY' ? st.lastSwingHigh : st.lastSwingLow; out.MC = !(atrRatio >= P.mcMinAtrRatio) ? `atrRatio ${r2(atrRatio)}<1` : !onSide ? 'closes not all beyond EMA20' : !prog ? 'closes not progressing' : !sw ? 'no swing' : !(bs === 'BUY' ? b[i].close > sw.price : b[i].close < sw.price) ? `close ${b[i].close} vs swing ${r2(sw.price)} (short by ${r2(Math.abs(sw.price - b[i].close))})` : 'break too old'; }
    if (!allowed('PB', bs)) out.PB = 'not eligible'; else { const corr = computeCorrection(b, bias.direction, { ...CORRECTION_PARAMS, swingLookback: P.pbSwingLookback, corrAtrMultiplier: P.pbCorrAtrMultiplier, corrResolveConfirmBars: P.pbResolveConfirmBars }); let run = 0; for (let k = i; k >= 0; k--) { if (!(bs === 'BUY' ? b[k].close > e[k] : b[k].close < e[k])) break; run++; } const since = run - P.pbResolveConfirmBars; out.PB = corr.state !== 'RESOLVED' ? `correction ${corr.state}` : (since < 0 || since > P.pbMaxEntryLateBars) ? `resolved ${since} bars ago (late)` : 'would trigger'; } }
  const ev = st.lastEvent; if (!ev) out.BO = 'no BOS/CHoCH'; else { const side = ev.direction === 'BULLISH' ? 'BUY' : 'SELL'; const age = i - ev.bar; const tol = a * P.boRetestAtrTol; let minD = Infinity; for (let j = ev.bar + 1; j <= i; j++) { const d = ev.direction === 'BULLISH' ? b[j].low - ev.level : ev.level - b[j].high; minD = Math.min(minD, d); } const retested = Number.isFinite(minD) && minD <= tol; const reclaimed = side === 'BUY' ? b[i].close > ev.level : b[i].close < ev.level; out.BO = !allowed('BO', side) ? `${side} not allowed` : !(age <= P.boMaxEntryLateBars) ? `${ev.type} ${age} bars old (>10)` : !retested ? `no retest (closest ${r2(minD / a)} ATR vs 0.3)` : !reclaimed ? 'retested not reclaimed' : 'would trigger'; }
  const bar = b[i]; const lv = []; const push = (s, src, side) => { if (s?.price != null) lv.push({ p: s.price, src, side }); }; push(bias.structure?.lastSwingLow, '15m_low', 'BUY'); push(bias.structure?.lastSwingHigh, '15m_high', 'SELL'); push(st.lastSwingLow, '5m_low', 'BUY'); push(st.lastSwingHigh, '5m_high', 'SELL');
  out.SR = !bias.eligible_models.includes('SR') ? 'not eligible' : lv.filter((l) => sideAllowedByBias(bias, l.side)).map((l) => { const dist = l.side === 'BUY' ? (bar.low - l.p) / a : (l.p - bar.high) / a; return `${l.src} ${r2(dist)}ATR`; }).join(';') || 'no allowed level';
  out.MR = !bias.eligible_models.includes('MR') ? 'not eligible' : !st.lastSweep ? 'no sweep' : (i - st.lastSweep.bar) > P.mrSweepMaxAgeBars ? `sweep ${i - st.lastSweep.bar} bars old` : 'sweep fresh (other MR conditions)';
  return out; }
function replayAt(t, T) { const b5 = conf('5m', T); if (b5.at(-1)?.time !== t) return { error: `replay last bar ${hm(b5.at(-1)?.time ?? 0)} != ${hm(t)}` }; const b15 = conf('15m', T), b30 = conf('30m', T), b1h = conf('1H', T);
  const ctx1H = computeHtfContext(b1h, { includeCorrection: true }); const m30 = runPipeline({ confirmedBars: b30 }); const bias = computeBias({ confirmedBars: b15, params: P }); const intra = runIntradayPipeline({ bars5: b5, bias, m30Regime: m30.regime, ctx1H, params: P }); const live = combineIntraday({ intraday: intra, bias, m30, ctx1H });
  const { regime, evidence: re } = classifyRegime(b5, REGIME_PARAMS); const st = computeStructure(b5, STRUCTURE_PARAMS); const a = atr(b5, 14).at(-1); const e = ema(b5.map((x) => x.close), 20); const atrRatio = re?.atrRatio ?? 1; const c = intra.evidence?.candidate, rk = intra.evidence?.risk; const bar = b5.at(-1);
  return { ohlc: { o: bar.open, h: bar.high, l: bar.low, c: bar.close }, htf_last: { m15: hm(b15.at(-1).time), m30: hm(b30.at(-1).time), h1: hm(b1h.at(-1).time) }, bars_available: { m5: b5.length, m15: b15.length, m30: b30.length, h1: b1h.length }, regime5: regime, atrRatio: r3(atrRatio), atr: r3(a), structure5: st.state, event: st.lastEvent ? `${st.lastEvent.type}/${st.lastEvent.direction}` : null, event_level: r2(st.lastEvent?.level), event_age: st.lastEvent ? b5.length - 1 - st.lastEvent.bar : null, anchor5: r2(st.state === 'BULLISH' ? st.lastSwingLow?.price : st.lastSwingHigh?.price), momentum: { adx: r2(re?.adx), ema20_dist: r2(bar.close - e.at(-1)) }, bias15: bias.direction, regime15: bias.regime, structure15: bias.structure?.state, choch15: bias.fresh_opposing_choch ? `${bias.fresh_opposing_choch.direction} ${bias.fresh_opposing_choch.bars_ago}b` : null, regime30: m30.regime, structure30: m30.structure?.state, regime1h: ctx1H.regime, bias1h: ctx1H.structure_direction, eligible: bias.eligible_models.join(''), models: firstFail(b5, b15, bias, regime, st, atrRatio, a, e), candidate: c ? `${c.model} ${c.side}` : null, entry: rk?.entry ?? null, sl: rk?.stop_loss ?? null, tp1: rk?.tp1 ?? null, tp2: rk?.tp2 ?? null, rr: rk?.rr ?? null, rr_gate: rk?.gate ?? null, quality: intra.quality?.score ?? null, q_threshold: intra.quality?.threshold ?? null, quality_pass: intra.quality ? intra.quality.score >= intra.quality.threshold : null, overextension: rk?.gate === 'OVEREXTENDED' ? 'FAIL' : c ? 'PASS' : null, mtf: live.conflict ?? (live.wait_reason === 'HTF_CONFLICT' ? live.conflict : null), action: live.action, reason: live.wait_reason ?? null, intraday_reason: intra.decision.wait_reason ?? null }; }

// ---------- build ledgers ----------
const rows = []; const missing = [];
for (let t = START; t <= lastLive; t += 300) { const lr = liveBy.get(t); const T = lr ? Math.floor(Date.parse(lr.observed_at) / 1000) : t + 300 + 85; let rp = replayAt(t, T); let replay_T_used = 'observed_at'; if (rp.error) { rp = replayAt(t, t + 300 + 85); replay_T_used = 'close+85s (late live processing would have sliced a later bar)'; } rp.T_used = replay_T_used; const prot = protAt(T);
  const live = lr ? { available: true, processed: true, observed_at: lr.observed_at, delay_s: r2(T - (t + 300)), action: lr.authoritative_action, reason: lr.authoritative_wait_reason ?? null, regime5: lr.regime, structure5: lr.structure_state, event: lr.structure_event, regime15_ref: lr.candidates?.['15m']?.regime ?? null, regime30_ref: lr.candidates?.['30m']?.regime ?? null, status30_ref: lr.candidates?.['30m']?.status ?? null, location_price: lr.location?.price ?? null, invalidation_level: lr.invalidation_level ?? null, anchor_price: lr.structural_anchor_price ?? null, dist_atr: lr.distance_to_trigger?.atr_multiple ?? null, pre_entry: lr.pre_entry_state, model_code: lr.mapped_model_code ?? null, waiting_for: (lr.waiting_for ?? [])[0] ?? null } : { available: true, processed: false, observed_at: null, delay_s: null, action: 'NOT_PROCESSED', reason: 'FEED_STALL_CANDLE_READ_FAILED' };
  if (!lr) missing.push(hm(t));
  const sig = sigToday.find((s) => s.signal_bar_time === t); const exec = sig ? TRADE.find((r) => r.signal_id === sig.signal_id) : null;
  const cmp = {}; const norm = (x) => (x == null ? null : String(x));
  if (lr && !rp.error) { cmp.action = live.action === rp.action ? 'MATCH' : 'MISMATCH'; cmp.reason = norm(live.reason) === norm(rp.reason) ? 'MATCH' : (live.reason === 'insufficient/invalid market data' ? 'LIVE_DATA_UNAVAILABLE' : 'MISMATCH'); cmp.regime5 = live.regime5 === rp.regime5 ? 'MATCH' : 'MISMATCH'; cmp.structure5 = live.structure5 === rp.structure5 ? 'MATCH' : 'MISMATCH'; cmp.event_type = (live.event ?? null) === (rp.event ? rp.event.split('/')[0] : null) ? 'MATCH' : 'MISMATCH'; cmp.regime15 = live.regime15_ref === rp.regime15 ? 'MATCH' : 'MISMATCH'; cmp.regime30 = live.status30_ref === 'UNAVAILABLE' ? 'LIVE_UNAVAILABLE' : live.regime30_ref === rp.regime30 ? 'MATCH' : 'MISMATCH'; cmp.level_diff_usd = live.invalidation_level != null && rp.anchor5 != null ? r2(Math.abs(live.invalidation_level - rp.anchor5)) : null; cmp.location_vs_event_level_diff = live.location_price != null && rp.event_level != null ? r2(Math.abs(live.location_price - rp.event_level)) : null; }
  rows.push({ t, utc: iso(t).slice(0, 16), ist: new Date((t + IST_OFFSET) * 1000).toISOString().slice(11, 16), live, replay: rp, protection: { blocking: prot.blocking, reasons: prot.reasons.join('|'), news: prot.news, shock: prot.shock }, executor: exec ? { reached: true, type: exec.type, reason: exec.reason, live_ask: exec.live_ask, drift: exec.entry_drift, engine_entry: exec.engine_entry } : { reached: false }, signal_store: sig ? { signal_id: sig.signal_id, entry: sig.entry, sl: sig.stop_loss, tp2: sig.tp2, rr: sig.rr, quality: sig.quality } : null, compare: cmp }); }

// ---------- summaries ----------
const processed = rows.filter((r) => r.live.processed); const compared = processed.filter((r) => !r.replay.error);
const decisionMatch = compared.filter((r) => r.compare.action === 'MATCH' && (r.compare.reason === 'MATCH')).length; const dataUnavail = compared.filter((r) => r.compare.reason === 'LIVE_DATA_UNAVAILABLE').length; const decisionMismatch = compared.filter((r) => r.compare.action === 'MISMATCH' || (r.compare.reason === 'MISMATCH')).length;
const ctxMismatch = compared.filter((r) => ['regime5', 'structure5', 'event_type', 'regime15', 'regime30'].some((k) => r.compare[k] === 'MISMATCH'));
const funnelReplay = (rs) => { const c = rs.filter((r) => !r.replay.error); const f = { processed: c.length, model_eligible: c.filter((r) => r.replay.eligible).length, candidate_trigger: c.filter((r) => r.replay.candidate).length }; f.after_overextension = c.filter((r) => r.replay.candidate && r.replay.rr_gate !== 'OVEREXTENDED' && r.replay.rr_gate !== 'VOLATILITY_INSUFFICIENT').length; f.rr_reached = f.after_overextension; f.after_rr = c.filter((r) => r.replay.candidate && r.replay.rr_gate === 'OK').length; f.after_quality = c.filter((r) => r.replay.rr_gate === 'OK' && r.replay.quality_pass).length; f.after_mtf = c.filter((r) => r.replay.action === 'BUY' || r.replay.action === 'SELL').length; f.final_signals = f.after_mtf; return f; };
const funnelLive = (rs) => { const p = rs.filter((r) => r.live.processed); const reason = (x) => p.filter((r) => r.live.reason === x).length; return { expected: rs.length, processed: p.length, not_processed: rs.length - p.length, reasons: Object.fromEntries([...new Set(p.map((r) => r.live.reason ?? r.live.action))].map((k) => [k, p.filter((r) => (r.live.reason ?? r.live.action) === k).length])), candidate_reached_risk_or_later: reason('RR_NOT_ACCEPTABLE') + reason('OVEREXTENDED') + reason('NO_GOOD_ENTRY') + reason('ENTRY_CONFLICT') + reason('HTF_CONFLICT') + p.filter((r) => r.live.action === 'BUY' || r.live.action === 'SELL').length, final_signals: p.filter((r) => r.live.action === 'BUY' || r.live.action === 'SELL').length, executor_reached: rows.filter((r) => r.executor.reached).length, broker_orders: TRADE.filter((r) => r.type === 'OPENED').length }; };
const rrReached = compared.filter((r) => r.replay.candidate && r.replay.rr != null && r.replay.rr_gate !== 'OVEREXTENDED' && r.replay.rr_gate !== 'VOLATILITY_INSUFFICIENT');
const rrBucket = (rr) => (rr < 1.0 ? '<1.00' : rr < 1.25 ? '1.00-1.25' : rr < 1.5 ? '1.25-1.50' : rr < 1.7 ? '1.50-1.70' : '>=1.70');
const rrBuckets = Object.fromEntries(['<1.00', '1.00-1.25', '1.25-1.50', '1.50-1.70', '>=1.70'].map((b) => [b, rrReached.filter((r) => rrBucket(r.replay.rr) === b).map((r) => `${hm(r.t)} ${r.replay.candidate} rr ${r.replay.rr}`)]));
// what lowering RR would have created: candidates with rr in [x,1.7) that ALSO pass quality (recomputed with production coupling: q + delta qRr) and MTF
const qRr = (rr, m) => Math.min(10, Math.max(0, (10 * (rr - m)) / m));
const wouldCreate = {}; for (const m of [1.5, 1.25, 1.0]) wouldCreate[String(m)] = rrReached.filter((r) => r.replay.rr >= m && r.replay.rr < 1.7 && r.replay.quality != null && (r.replay.quality + qRr(r.replay.rr, m) - qRr(r.replay.rr, 1.7)) >= r.replay.q_threshold && !r.replay.mtf && !protAt(r.t + 385).blocking).map((r) => `${hm(r.t)} ${r.replay.candidate} rr ${r.replay.rr} q ${r.replay.quality}/${r.replay.q_threshold}`);
const qualityDist = compared.filter((r) => r.replay.rr_gate === 'OK' && r.replay.quality != null).map((r) => ({ t: hm(r.t), cand: r.replay.candidate, q: r.replay.quality, th: r.replay.q_threshold, pass: r.replay.quality_pass, band: r.replay.quality < 65 ? '<65' : r.replay.quality < 70 ? '65-69' : r.replay.quality < 75 ? '70-74' : '75+' }));
const mtf = { fresh_choch_veto: compared.filter((r) => String(r.replay.mtf ?? '').includes('fresh opposing CHoCH')).length, two_factor_30m: compared.filter((r) => String(r.replay.mtf ?? '').includes('two-factor')).length, htf_1h: compared.filter((r) => r.replay.reason === 'HTF_CONFLICT').length, side_not_allowed_by_15m_bias: compared.filter((r) => Object.values(r.replay.models ?? {}).some((v) => String(v).includes('not allowed'))).length, bias_neutral_candles: compared.filter((r) => r.replay.bias15 === 'NEUTRAL').length, bias_directional_candles: compared.filter((r) => r.replay.bias15 !== 'NEUTRAL').length };
const newsBlockedCandles = rows.filter((r) => r.protection.blocking).length;
// near misses: candidates that reached risk/quality/MTF (closest), plus per-model near-trigger distances
const nearMisses = compared.filter((r) => r.replay.candidate || (r.replay.models && Object.values(r.replay.models).some((v) => /short by|would trigger|resolved \d+ bars|closest -?0\.[0-6]/.test(String(v))))).map((r) => ({ t: hm(r.t), candidate: r.replay.candidate, first_failed_gate: r.replay.candidate ? (r.replay.rr_gate !== 'OK' ? r.replay.rr_gate : !r.replay.quality_pass ? 'QUALITY' : r.replay.mtf ? 'MTF' : r.replay.action !== 'WAIT' ? (r.executor.reached ? `EXECUTOR:${r.executor.reason}` : 'SIGNAL') : 'OTHER') : 'NO_TRIGGER', rr: r.replay.rr, rr_margin: r.replay.rr != null ? r2(r.replay.rr - 1.7) : null, quality: r.replay.quality, q_margin: r.replay.quality != null ? r.replay.quality - r.replay.q_threshold : null, mtf: r.replay.mtf, news_block: r.protection.blocking ? r.protection.reasons : null, models: r.replay.models, bias15: `${r.replay.bias15}/${r.replay.regime15}`, regime30: `${r.replay.regime30}/${r.replay.structure30}` })).sort((a, b) => (a.candidate ? 0 : 1) - (b.candidate ? 0 : 1));
// data parity: TV 30m vs MT5 30m for today
const mt30 = new Map(BARS['30m'].map((b) => [b.time, b])); const dp = TV30.map((b) => { const m = mt30.get(b.time); return m ? { t: hm(b.time), dO: r3(b.open - m.open), dH: r3(b.high - m.high), dL: r3(b.low - m.low), dC: r3(b.close - m.close) } : { t: hm(b.time), missing_in_mt5: true }; }); const dvals = dp.filter((d) => !d.missing_in_mt5); const absMean = (k) => r3(dvals.reduce((s, d) => s + Math.abs(d[k]), 0) / dvals.length); const signedMean = (k) => r3(dvals.reduce((s, d) => s + d[k], 0) / dvals.length);
const dataParity = { tv_30m_bars_today: TV30.length, matched_timestamps: dvals.length, missing_in_mt5: dp.filter((d) => d.missing_in_mt5).length, mean_abs_diff: { o: absMean('dO'), h: absMean('dH'), l: absMean('dL'), c: absMean('dC') }, mean_signed_diff_tv_minus_mt5: { o: signedMean('dO'), h: signedMean('dH'), l: signedMean('dL'), c: signedMean('dC') }, max_abs_diff: r3(Math.max(...dvals.flatMap((d) => [Math.abs(d.dO), Math.abs(d.dH), Math.abs(d.dL), Math.abs(d.dC)]))), per_bar: dp, signal_entry_parity: sigToday.map((s) => { const r = rows.find((x) => x.t === s.signal_bar_time); return { signal_bar: hm(s.signal_bar_time), live_entry_tv: s.entry, replay_entry_mt5: r?.replay.entry, diff: r2(s.entry - (r?.replay.entry ?? 0)), live_sl: s.stop_loss, replay_sl: r?.replay.sl, live_q: s.quality, replay_q: r?.replay.quality, live_rr: s.rr, replay_rr: r?.replay.rr }; }), structure_level_diffs_usd: compared.map((r) => r.compare.level_diff_usd).filter((x) => x != null) };
dataParity.structure_level_diff_summary = { n: dataParity.structure_level_diffs_usd.length, median: r2([...dataParity.structure_level_diffs_usd].sort((a, b) => a - b)[Math.floor(dataParity.structure_level_diffs_usd.length / 2)]), max: r2(Math.max(...dataParity.structure_level_diffs_usd)) };
// watcher reliability
const delays = processed.map((r) => r.live.delay_s); const sorted = [...delays].sort((a, b) => a - b);
const reliability = { poll_interval_s: 60, processed_candles: processed.length, expected_candles: rows.length, missing_candles: missing, processing_delay_after_close_s: { min: sorted[0], median: sorted[Math.floor(sorted.length / 2)], p90: sorted[Math.floor(sorted.length * 0.9)], max: sorted.at(-1) }, late_over_150s: processed.filter((r) => r.live.delay_s > 150).map((r) => `${hm(r.t)} +${r.live.delay_s}s`), tick_skips: logEvents.tick_skips, read_failures: logEvents.read_failures.length, read_failure_reasons: Object.fromEntries([...new Set(logEvents.read_failures.map((f) => f.reason))].map((k) => [k, logEvents.read_failures.filter((f) => f.reason === k).length])), stalls: logEvents.stalls, recoveries: logEvents.recoveries, baselines: logEvents.baselines, alerts: logEvents.alerts, executions: logEvents.exec, data_unavailable_candles: processed.filter((r) => r.live.reason === 'insufficient/invalid market data').map((r) => hm(r.t)) };

const summary = { window: { start_utc: iso(START), end_utc: iso(lastLive + 300), duration_h: r2((lastLive + 300 - START) / 3600), expected_candles: rows.length, processed_candles: processed.length, missing: missing, complete: false, note: 'PARTIAL CURRENT WINDOW: v9 started 07:30:29Z today; the session is still open at audit time. No earlier complete v9 day exists (v8 was blind and was stopped 07:16Z).' }, parity: { compared: compared.length, replay_errors: processed.length - compared.length, decision_match: decisionMatch, live_data_unavailable: dataUnavail, decision_mismatch: decisionMismatch, context_mismatch_rows: ctxMismatch.map((r) => ({ t: hm(r.t), ...Object.fromEntries(Object.entries(r.compare).filter(([k, v]) => v === 'MISMATCH')) })), live_final_signals: processed.filter((r) => r.live.action === 'BUY' || r.live.action === 'SELL').length, replay_final_signals: rows.filter((r) => !r.replay.error && (r.replay.action === 'BUY' || r.replay.action === 'SELL')).map((r) => `${hm(r.t)} ${r.replay.candidate}${r.live.processed ? '' : ' (candle NOT processed live)'}`) }, funnel_live: funnelLive(rows), funnel_replay: funnelReplay(rows), funnel_replay_missing_candles_only: funnelReplay(rows.filter((r) => !r.live.processed)), rr: { reached: rrReached.length, buckets: rrBuckets, would_create_with_lower_rr: wouldCreate }, quality: { triggered_and_rr_ok: qualityDist.length, bands: Object.fromEntries(['<65', '65-69', '70-74', '75+'].map((b) => [b, qualityDist.filter((q) => q.band === b).length])), failed: qualityDist.filter((q) => !q.pass), passed: qualityDist.filter((q) => q.pass) }, mtf, news_safety: { blocked_candles: newsBlockedCandles, block_window: protTimeline.filter((p) => p.blocking).map((p) => iso(p.t).slice(11, 19) + ' ' + p.reasons.join('+')), signals_blocked_by_safety_as_final_blocker: rows.filter((r) => (r.live.action === 'BUY' || r.live.action === 'SELL')).map((r) => ({ t: hm(r.t), executor: r.executor })) }, data_parity: dataParity, reliability, near_misses: nearMisses.slice(0, 40) };
writeFileSync(join(OUT, 'parity_results.json'), JSON.stringify({ generated_utc: new Date().toISOString(), summary, rows }, null, 1));
// CSVs
const esc = (v) => { const s = v == null ? '' : typeof v === 'object' ? JSON.stringify(v) : String(v); return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s; };
const liveCols = ['utc', 'ist', 'processed', 'observed_at', 'delay_s', 'action', 'reason', 'regime5', 'structure5', 'event', 'regime15_ref', 'regime30_ref', 'status30_ref', 'location_price', 'invalidation_level', 'anchor_price', 'dist_atr', 'pre_entry', 'model_code', 'waiting_for', 'news', 'shock', 'blocking', 'block_reasons', 'executor_reached', 'executor_result', 'broker_reached'];
writeFileSync(join(OUT, 'LIVE_LEDGER.csv'), [liveCols.join(',')].concat(rows.map((r) => [r.utc, r.ist, r.live.processed, r.live.observed_at, r.live.delay_s, r.live.action, r.live.reason, r.live.regime5, r.live.structure5, r.live.event, r.live.regime15_ref, r.live.regime30_ref, r.live.status30_ref, r.live.location_price, r.live.invalidation_level, r.live.anchor_price, r.live.dist_atr, r.live.pre_entry, r.live.model_code, r.live.waiting_for, r.protection.news, r.protection.shock, r.protection.blocking, r.protection.reasons, r.executor.reached, r.executor.reached ? `${r.executor.type}:${r.executor.reason}` : 'EXECUTOR_NOT_REACHED_BECAUSE_NO_FINAL_SIGNAL', 'NO'].map(esc).join(','))).join('\n'));
const repCols = ['utc', 'o', 'h', 'l', 'c', 'm15_last', 'm30_last', 'h1_last', 'bars5', 'regime5', 'atrRatio', 'atr', 'structure5', 'event', 'event_level', 'event_age', 'anchor5', 'adx', 'ema20_dist', 'bias15', 'regime15', 'structure15', 'choch15', 'regime30', 'structure30', 'regime1h', 'bias1h', 'eligible', 'MC', 'PB', 'BO', 'SR', 'MR', 'candidate', 'entry', 'sl', 'tp1', 'tp2', 'rr', 'rr_gate', 'quality', 'q_threshold', 'quality_pass', 'overextension', 'mtf', 'action', 'reason'];
writeFileSync(join(OUT, 'REPLAY_LEDGER.csv'), [repCols.join(',')].concat(rows.map((r) => { const p = r.replay; if (p.error) return [r.utc, p.error].map(esc).join(','); return [r.utc, p.ohlc.o, p.ohlc.h, p.ohlc.l, p.ohlc.c, p.htf_last.m15, p.htf_last.m30, p.htf_last.h1, p.bars_available.m5, p.regime5, p.atrRatio, p.atr, p.structure5, p.event, p.event_level, p.event_age, p.anchor5, p.momentum.adx, p.momentum.ema20_dist, p.bias15, p.regime15, p.structure15, p.choch15, p.regime30, p.structure30, p.regime1h, p.bias1h, p.eligible, p.models.MC, p.models.PB, p.models.BO, p.models.SR, p.models.MR, p.candidate, p.entry, p.sl, p.tp1, p.tp2, p.rr, p.rr_gate, p.quality, p.q_threshold, p.quality_pass, p.overextension, p.mtf, p.action, p.reason].map(esc).join(','); })).join('\n'));
const diffCols = ['utc', 'live_processed', 'live_action', 'replay_action', 'action_cmp', 'live_reason', 'replay_reason', 'reason_cmp', 'regime5_cmp', 'structure5_cmp', 'event_type_cmp', 'regime15_cmp', 'regime30_cmp', 'structure_level_diff_usd', 'location_vs_event_level_diff_usd', 'quality_live_vs_replay', 'rr_live_vs_replay', 'entry_live_vs_replay'];
writeFileSync(join(OUT, 'LIVE_REPLAY_DIFF.csv'), [diffCols.join(',')].concat(rows.map((r) => [r.utc, r.live.processed, r.live.action, r.replay.action ?? r.replay.error, r.compare.action ?? (r.live.processed ? 'UNAVAILABLE' : 'LIVE_NOT_PROCESSED'), r.live.reason, r.replay.reason, r.compare.reason ?? 'UNAVAILABLE', r.compare.regime5 ?? 'UNAVAILABLE', r.compare.structure5 ?? 'UNAVAILABLE', r.compare.event_type ?? 'UNAVAILABLE', r.compare.regime15 ?? 'UNAVAILABLE', r.compare.regime30 ?? 'UNAVAILABLE', r.compare.level_diff_usd, r.compare.location_vs_event_level_diff, r.signal_store ? `${r.signal_store.quality} vs ${r.replay.quality}` : 'UNAVAILABLE (live logs quality only for signals)', r.signal_store ? `${r.signal_store.rr} vs ${r.replay.rr}` : 'UNAVAILABLE', r.signal_store ? `${r.signal_store.entry} vs ${r.replay.entry}` : 'UNAVAILABLE'].map(esc).join(','))).join('\n'));
console.log('\n=== DECISION/CONTEXT MISMATCH ROWS ===');
for (const r of compared.filter((x) => x.compare.action === 'MISMATCH' || x.compare.reason === 'MISMATCH' || x.compare.reason === 'LIVE_DATA_UNAVAILABLE' || ['regime5','structure5','event_type','regime15','regime30'].some((k) => x.compare[k] === 'MISMATCH'))) console.log(hm(r.t), JSON.stringify({ cmp: r.compare, live: { a: r.live.action, r: r.live.reason, rg5: r.live.regime5, st5: r.live.structure5, ev: r.live.event, rg15: r.live.regime15_ref, rg30: r.live.regime30_ref, st30: r.live.status30_ref, delay: r.live.delay_s }, replay: { a: r.replay.action, r: r.replay.reason, rg5: r.replay.regime5, atrR: r.replay.atrRatio, st5: r.replay.structure5, ev: r.replay.event, rg15: r.replay.regime15, rg30: r.replay.regime30, T: r.replay.T_used } }));
console.log('\n=== RR-REACHED CANDIDATES (replay) ===');
for (const r of rrReached) console.log(hm(r.t), JSON.stringify({ cand: r.replay.candidate, rr: r.replay.rr, gate: r.replay.rr_gate, q: r.replay.quality, th: r.replay.q_threshold, qpass: r.replay.quality_pass, mtf: r.replay.mtf, action: r.replay.action, reason: r.replay.reason, live: r.live.reason ?? r.live.action, news_block: r.protection.blocking ? r.protection.reasons : null, processed: r.live.processed }));
console.log('\n=== NEAR MISSES (top 25) ===');
for (const n of nearMisses.slice(0, 25)) console.log(JSON.stringify(n));
console.log('\n=== REPLAY_T_USED fallbacks ===', rows.filter((r) => r.replay.T_used && r.replay.T_used !== 'observed_at').map((r) => hm(r.t) + ' ' + r.live.delay_s + 's'));
console.log(JSON.stringify({ window: summary.window, parity: { ...summary.parity, context_mismatch_rows: summary.parity.context_mismatch_rows.length }, funnel_live: summary.funnel_live, funnel_replay: summary.funnel_replay, funnel_missing: summary.funnel_replay_missing_candles_only, rr: { reached: summary.rr.reached, buckets: Object.fromEntries(Object.entries(rrBuckets).map(([k, v]) => [k, v.length])), would_create: Object.fromEntries(Object.entries(wouldCreate).map(([k, v]) => [k, v])) }, quality: { n: summary.quality.triggered_and_rr_ok, bands: summary.quality.bands, failed: summary.quality.failed.length }, mtf, news_blocked_candles: newsBlockedCandles, data_parity: { mean_abs: dataParity.mean_abs_diff, signed: dataParity.mean_signed_diff_tv_minus_mt5, max: dataParity.max_abs_diff, signal: dataParity.signal_entry_parity, level_diff: dataParity.structure_level_diff_summary }, reliability: { ...reliability, stalls: reliability.stalls.length, recoveries: reliability.recoveries.length, alerts: reliability.alerts, executions: reliability.executions } }, null, 1));
