/**
 * SILVER N2 + DOM FORWARD OBSERVATION -- READ-ONLY report generator (2026-10-01). MEASURE ONLY.
 * Summarises SC3 (silver N2 at production signals) and SC4 (DOM snapshots) from the append-only store; applies the
 * pre-declared 300-observation gate (docs/XAUUSD_SILVER_N2_FORWARD_OBSERVATION.md). Only FORWARD_LIVE records count;
 * BACKFILL / replay / test records are reported separately and never count. Every trade statistic is HYPOTHETICAL_NOT_EXECUTED.
 *   node src/shadow/silverReport.js [--dir state/shadow] [--out handoff/SILVER_DOM_FORWARD_OBSERVATION] [--json]
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { createEvidenceStore } from './store.js';
import { HYP_MILESTONES, HYP_LABEL } from './core.js';

export const SILVER_GATE = Object.freeze({ min_forward_observations: 300, min_labeled: 300, improvement_r_min: 0.10, wd_reduction_min: 0.03, pf_min: 1.10, ci_lower_gt: 0, stress_gt: 0 });
export const STATUSES = Object.freeze(['COLLECTING', 'INSUFFICIENT_FORWARD_EVIDENCE', 'GATE_REACHED_AWAITING_LABELS', 'POSITIVE', 'NEGATIVE', 'INCONCLUSIVE']);
// owner wording for the final decision (never a deployment): POSITIVE is at most PROMISING and requires a NEW research specification
export const FINAL_DECISION = Object.freeze({ POSITIVE: 'PROMISING_REQUIRES_NEW_RESEARCH_SPEC', NEGATIVE: 'REJECTED', INCONCLUSIVE: 'INCONCLUSIVE' });
export const INTERIM_BANNER = '**INTERIM — NOT FINAL — INSUFFICIENT_SAMPLE.** No edge conclusion is drawn before the frozen 300-observation dataset is fully labelled.';
const mean = (a) => (a.length ? a.reduce((x, y) => x + y, 0) / a.length : null); const r3 = (x) => (x == null || !Number.isFinite(x) ? null : +x.toFixed(3)); const pc = (x) => (x == null ? '—' : `${(x * 100).toFixed(1)} %`); const f = (x, d = 3) => (x == null ? '—' : typeof x === 'number' ? x.toFixed(d) : String(x));
let seed = 7; const rnd = () => { seed = (seed * 1664525 + 1013904223) % 4294967296; return seed / 4294967296; };
function bootCI(v, R = 2000) { if (v.length < 5) return null; const out = []; for (let k = 0; k < R; k++) { let s = 0; for (let i = 0; i < v.length; i++) s += v[Math.floor(rnd() * v.length)]; out.push(s / v.length); } out.sort((a, b) => a - b); return [r3(out[Math.floor(0.025 * R)]), r3(out[Math.floor(0.975 * R)])]; }
function groupStats(rows, key = 'hypothetical_normal_cost') { const R = rows.map((r) => r[key].exit_r).filter((x) => x != null); if (!R.length) return { n: 0 }; const w = R.filter((x) => x > 0), l = R.filter((x) => x <= 0); const gw = w.reduce((a, b) => a + b, 0), gl = -l.reduce((a, b) => a + b, 0); let cum = 0, peak = 0, dd = 0; for (const x of R) { cum += x; peak = Math.max(peak, cum); dd = Math.max(dd, peak - cum); } return { n: R.length, expectancy_r: r3(mean(R)), pf: gl > 0 ? r3(gw / gl) : (gw > 0 ? 99 : null), win_rate: r3(w.length / R.length), avg_win_r: r3(mean(w)), avg_loss_r: l.length ? r3(-mean(l)) : null, max_dd_r: r3(dd), ci95_r: bootCI(R), wrong_direction_rate: r3(rows.filter((r) => r.wrong_direction).length / rows.length), bad_entry_rate: r3(rows.filter((r) => r.bad_entry).length / rows.length), mfe_r: r3(mean(rows.map((r) => r.open_path.mfe_r))), mae_r: r3(mean(rows.map((r) => r.open_path.mae_r))), reach: Object.fromEntries(HYP_MILESTONES.map((m) => [m, r3(rows.filter((r) => r.open_path.reach[String(m)]).length / rows.length)])), duration_bars_median: (() => { const d = rows.map((r) => r[key].duration_bars).sort((a, b) => a - b); return d.length ? d[Math.floor(d.length / 2)] : null; })(), exits: rows.reduce((g, r) => { g[r[key].exit] = (g[r[key].exit] ?? 0) + 1; return g; }, {}) }; }

export function evaluateSilver(observations, outcomes) {
  const sc3 = observations.filter((o) => o.candidate_id === 'SC3_SILVER_N2_v1'); const fwdAll = sc3.filter((o) => o.provenance === 'FORWARD_LIVE').sort((a, b) => String(a.decision_time_utc).localeCompare(String(b.decision_time_utc)) || String(a.observation_id).localeCompare(String(b.observation_id))); const nonFwd = sc3.length - fwdAll.length;
  // freeze rule (pre-declared before any SC3 data): the analysis set is the FIRST 300 forward observations in decision-time order; later records are kept but never analysed
  const gateN = SILVER_GATE.min_forward_observations; const frozenSet = fwdAll.length >= gateN ? fwdAll.slice(0, gateN) : null; const fwd = frozenSet ?? fwdAll;
  const byId = new Map(fwd.map((o) => [o.observation_id, o])); const outs = outcomes.filter((r) => r.horizon === 'hyp288' && byId.has(r.observation_id) && r.status === 'LABELED');
  const rows = outs.map((r) => ({ ...r, obs: byId.get(r.observation_id) }));
  const by = (timing) => { const key = timing === 'LAG_1' ? 'silver_state_lag_1' : 'silver_state_same_bar'; return { CONTROL: groupStats(rows), CONFIRMED: groupStats(rows.filter((r) => r[key] === 'CONFIRMED')), CONFLICT: groupStats(rows.filter((r) => r[key] === 'CONFLICT')), NEUTRAL: groupStats(rows.filter((r) => r[key] === 'NEUTRAL')), NA: groupStats(rows.filter((r) => r[key] === 'NA')) }; };
  const same = by('SAME_BAR'), lag = by('LAG_1'); const stress = { CONTROL: groupStats(rows, 'hypothetical_stress_cost'), CONFIRMED: groupStats(rows.filter((r) => r.silver_state_same_bar === 'CONFIRMED'), 'hypothetical_stress_cost'), CONFLICT: groupStats(rows.filter((r) => r.silver_state_same_bar === 'CONFLICT'), 'hypothetical_stress_cost'), NEUTRAL: groupStats(rows.filter((r) => r.silver_state_same_bar === 'NEUTRAL'), 'hypothetical_stress_cost') };
  const dq = { observations: sc3.length, forward_live: fwdAll.length, analysis_set: fwd.length, remaining_to_300: Math.max(0, gateN - fwdAll.length), backfill_or_other: nonFwd, silver_na_at_decision: fwd.filter((o) => !o.payload?.silver_available_at_decision).length, same_open_mismatch: fwd.filter((o) => o.payload?.silver_same_bar?.available && !o.payload.silver_same_bar.same_open_as_signal).length, missing_geometry: fwd.filter((o) => !o.payload?.hypothetical).length, duplicate_signal_ids: fwd.length - new Set(fwd.map((o) => o.payload?.signal_id)).size, labeled: rows.length, pending: fwd.length - rows.length, provenance_counts: sc3.reduce((g, o) => { g[o.provenance] = (g[o.provenance] ?? 0) + 1; return g; }, {}) };
  const states = fwdAll.reduce((g, o) => { const k = o.payload?.silver_confirmation_state ?? 'NA'; g[k] = (g[k] ?? 0) + 1; return g; }, {});
  const c = same.CONTROL, s = same.CONFIRMED, sl = lag.CONFIRMED; let status = 'COLLECTING', reasons = [];
  const sameSign = s.n && sl.n ? Math.sign(s.expectancy_r - c.expectancy_r) === Math.sign(sl.expectancy_r - c.expectancy_r) : null; const timingSensitive = sameSign === false || (s.n && sl.n && Math.sign(s.expectancy_r) !== Math.sign(sl.expectancy_r));
  if (fwd.length < SILVER_GATE.min_forward_observations || rows.length < SILVER_GATE.min_labeled) { status = frozenSet ? 'GATE_REACHED_AWAITING_LABELS' : fwdAll.length ? 'INSUFFICIENT_FORWARD_EVIDENCE' : 'COLLECTING'; reasons.push(`forward observations ${fwdAll.length} / ${SILVER_GATE.min_forward_observations}; labeled ${rows.length} / ${SILVER_GATE.min_labeled}`); }
  else { const checks = { improvement: s.expectancy_r - c.expectancy_r >= SILVER_GATE.improvement_r_min, wrong_direction: c.wrong_direction_rate - s.wrong_direction_rate >= SILVER_GATE.wd_reduction_min, pf: s.pf > SILVER_GATE.pf_min, ci: s.ci95_r?.[0] > SILVER_GATE.ci_lower_gt, stress: stress.CONFIRMED.expectancy_r > SILVER_GATE.stress_gt, timing: !timingSensitive, reach_170: s.reach['1.7'] > c.reach['1.7'], mfe: s.mfe_r > c.mfe_r, mae: s.mae_r < c.mae_r, dd: s.max_dd_r <= c.max_dd_r }; const failed = Object.entries(checks).filter(([, v]) => !v).map(([k]) => k); if (!failed.length) status = 'POSITIVE'; else if (s.expectancy_r <= c.expectancy_r || checks.wrong_direction === false && checks.improvement === false) status = 'NEGATIVE'; else status = 'INCONCLUSIVE'; reasons = failed.length ? [`failed: ${failed.join(', ')}`] : ['all pre-declared checks passed']; }
  const isFinal = Object.hasOwn(FINAL_DECISION, status); const frozenDataset = frozenSet ? { n: frozenSet.length, first_decision_utc: frozenSet[0].decision_time_utc, last_decision_utc: frozenSet.at(-1).decision_time_utc, observation_ids_sha256: createHash('sha256').update(frozenSet.map((o) => o.observation_id).join('\n')).digest('hex') } : null;
  return { candidate: 'SC3_SILVER_N2_v1', forward_live_count: fwdAll.length, remaining_to_300: Math.max(0, gateN - fwdAll.length), interim: !isFinal, final_decision: isFinal ? FINAL_DECISION[status] : 'NOT_YET', frozen_dataset: frozenDataset, label: HYP_LABEL, execution_authority: 'NONE', gate: SILVER_GATE, data_quality: dq, states_forward: states, same_bar: same, lag_1: lag, stress_cost: stress, timing_sensitive: timingSensitive === true, timing_note: sameSign == null ? 'insufficient data' : sameSign ? 'same-bar and one-bar-lag improvements have the same sign' : 'SIGN DIFFERS between same-bar and one-bar-lag silver -> TIMING_SENSITIVE = TRUE', status, reasons };
}
export function evaluateDom(observations) {
  const withDom = observations.filter((o) => o.dom || o.payload?.dom); const fwd = withDom.filter((o) => o.provenance === 'FORWARD_LIVE'); const snaps = fwd.map((o) => o.dom ?? o.payload.dom); const avail = snaps.filter((d) => d && d.available); const reasons = snaps.filter((d) => d && !d.available).reduce((g, d) => { g[d.reason] = (g[d.reason] ?? 0) + 1; return g; }, {});
  const imb = avail.map((d) => d.imbalance).filter((x) => x != null); const withdraw = avail.filter((d) => d.liquidity_withdrawal === true).length;
  return { candidate: 'SC4_DOM_SNAPSHOT_v1', dom_measure_only: true, forward_only_data: true, execution_authority: 'NONE', records_with_dom_field: withDom.length, forward_live: fwd.length, available: avail.length, unavailable: snaps.length - avail.length, unavailable_reasons: reasons, availability_rate: snaps.length ? r3(avail.length / snaps.length) : null, imbalance: imb.length ? { n: imb.length, mean: r3(mean(imb)), p10: r3([...imb].sort((a, b) => a - b)[Math.floor(0.1 * imb.length)]), p90: r3([...imb].sort((a, b) => a - b)[Math.floor(0.9 * imb.length)]) } : null, level_count_mean: avail.length ? r3(mean(avail.map((d) => d.level_count))) : null, spread_mean: avail.length ? r3(mean(avail.map((d) => d.spread))) : null, liquidity_withdrawal_events: withdraw, data_quality: avail.length ? 'COLLECTING' : snaps.length ? 'DOM_UNAVAILABLE_FROM_BROKER' : 'NO_SNAPSHOTS_YET', status: avail.length >= 300 ? 'COLLECTED_300_SNAPSHOTS_NO_HYPOTHESIS_YET' : 'COLLECTING' };
}

export function renderReports({ silver, dom, nowIso }) {
  const g = (o) => `| n | exp (R) | PF | win | avg win / loss | DD (R) | 95 % CI | WD | bad entry | MFE / MAE (R) | reach 1 / 1.25 / 1.5 / 1.7 / 2 R | median bars | exits |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|\n` + Object.entries(o).map(([k, v]) => v.n ? `| **${k}** ${v.n} | ${f(v.expectancy_r)} | ${f(v.pf, 2)} | ${pc(v.win_rate)} | ${f(v.avg_win_r, 2)} / ${f(v.avg_loss_r, 2)} | ${f(v.max_dd_r, 1)} | ${v.ci95_r ? `[${v.ci95_r[0]}, ${v.ci95_r[1]}]` : '—'} | ${pc(v.wrong_direction_rate)} | ${pc(v.bad_entry_rate)} | ${f(v.mfe_r, 2)} / ${f(v.mae_r, 2)} | ${HYP_MILESTONES.map((m) => pc(v.reach[String(m)])).join(' / ')} | ${v.duration_bars_median ?? '—'} | ${Object.entries(v.exits).map(([a, b]) => `${a} ${b}`).join(', ')} |` : `| **${k}** 0 | — | — | — | — | — | — | — | — | — | — | — | — |`).join('\n');
  const head = `${silver.interim ? `${INTERIM_BANNER} FORWARD_LIVE_COUNT = ${silver.forward_live_count}; REMAINING_TO_300 = ${silver.remaining_to_300}.\n\n` : `**FINAL (frozen dataset n ${silver.frozen_dataset?.n}, ids sha256 ${silver.frozen_dataset?.observation_ids_sha256}).** FINAL_DECISION = ${silver.final_decision}.\n\n`}Generated ${nowIso}. ALL TRADE STATISTICS ARE ${HYP_LABEL}: no order was placed, modified or closed; the observer has no execution authority. Only FORWARD_LIVE records count; backfill/replay never count. Gate: ${silver.gate.min_forward_observations} genuine forward production signals with labelled outcomes.`;
  const R = {};
  R['SILVER_N2_FORWARD_REPORT.md'] = `# SILVER N2 FORWARD REPORT (SC3_SILVER_N2_v1, MEASURE_ONLY)\n\n${head}\n\n## Status: **${silver.status}** — ${silver.reasons.join('; ')}\n\n| Counter | Value |\n|---|---|\n| SC3 observations (all provenance) | ${silver.data_quality.observations} |\n| FORWARD_LIVE observations (count toward the gate) | ${silver.data_quality.forward_live} |\n| Backfill / other provenance (never count) | ${silver.data_quality.backfill_or_other} |\n| Labelled hypothetical outcomes (forward) | ${silver.data_quality.labeled} |\n| Pending (horizon not elapsed) | ${silver.data_quality.pending} |\n| Silver state at decision (forward): ${Object.entries(silver.states_forward).map(([k, v]) => `${k} ${v}`).join(', ') || 'none yet'} | |\n\n## Three-way comparison (same-bar silver, NORMAL cost; hypothetical EXIT_F with 1.70R target on the production geometry)\n${g(silver.same_bar)}\n\n## Stress cost (0.60 + 0.20 USD)\n${g(silver.stress_cost)}\n\nSILVER_EDGE_STATUS = ${silver.status}. Not POSITIVE unless every pre-declared check passes on >= 300 forward observations (expectancy +0.10 R over CONTROL, wrong-direction −3 points, PF > 1.10, CI lower bound > 0, stress > 0, not timing-sensitive, reach 1.7R / MFE / MAE / DD not worse). Win rate, drawdown or trade count alone never make it POSITIVE.\n`;
  R['SILVER_TIMING_ANALYSIS.md'] = `# SILVER TIMING ANALYSIS\n\n${head}\n\nSame-bar silver = XAGUSDm 5m bar with the SAME open time as the production signal bar (complete at the decision instant); one-bar-lag = the previous completed bar (realistic latency). Future silver bars are structurally excluded (bar close <= decision; schema anti-future check on cross_asset).\n\n## SAME_BAR\n${g(silver.same_bar)}\n\n## LAG_1\n${g(silver.lag_1)}\n\nTIMING_SENSITIVE = ${silver.timing_sensitive ? 'TRUE' : silver.timing_note === 'insufficient data' ? 'UNKNOWN (insufficient data)' : 'FALSE'} — ${silver.timing_note}. Same-open mismatches (silver bar not the same open as the signal bar): ${silver.data_quality.same_open_mismatch}; silver NA at decision: ${silver.data_quality.silver_na_at_decision}.\n`;
  R['SILVER_COST_STRESS.md'] = `# SILVER COST STRESS\n\n${head}\n\nNORMAL = spread 0.24 + slippage 0.10 USD; STRESS = 0.60 + 0.20 USD; entry pays the spread (BUY) and exit pays slippage; broker fail-safe 1.5R + spread intrabar.\n\n## NORMAL (same-bar states)\n${g(silver.same_bar)}\n\n## STRESS\n${g(silver.stress_cost)}\n\nNORMAL_COST_RESULT = ${silver.same_bar.CONFIRMED.n ? (silver.same_bar.CONFIRMED.expectancy_r > 0 ? 'positive point estimate' : 'not positive') : 'no data'}; STRESS_COST_RESULT = ${silver.stress_cost.CONFIRMED.n ? (silver.stress_cost.CONFIRMED.expectancy_r > 0 ? 'positive point estimate' : 'not positive') : 'no data'}. No profitability is claimed before costs.\n`;
  R['SILVER_CONTROL_COMPARISON.md'] = `# SILVER vs CONTROL COMPARISON\n\n${head}\n\n| Metric | CONTROL (all forward signals) | SILVER CONFIRMED | SILVER CONFLICT | SILVER NEUTRAL |\n|---|---|---|---|---|\n${[['N', (v) => v.n], ['Expectancy (R)', (v) => f(v.expectancy_r)], ['PF', (v) => f(v.pf, 2)], ['Wrong-direction', (v) => pc(v.wrong_direction_rate)], ['Bad entry (never +1R)', (v) => pc(v.bad_entry_rate)], ['MFE (R)', (v) => f(v.mfe_r, 2)], ['MAE (R)', (v) => f(v.mae_r, 2)], ['1.70R reach', (v) => pc(v.reach?.['1.7'])], ['Max DD (R)', (v) => f(v.max_dd_r, 1)], ['95 % CI', (v) => (v.ci95_r ? `[${v.ci95_r[0]}, ${v.ci95_r[1]}]` : '—')]].map(([k, fn]) => `| ${k} | ${silver.same_bar.CONTROL.n ? fn(silver.same_bar.CONTROL) : '—'} | ${silver.same_bar.CONFIRMED.n ? fn(silver.same_bar.CONFIRMED) : '—'} | ${silver.same_bar.CONFLICT.n ? fn(silver.same_bar.CONFLICT) : '—'} | ${silver.same_bar.NEUTRAL.n ? fn(silver.same_bar.NEUTRAL) : '—'} |`).join('\n')}\n\nCONTROL = the unfiltered production decision stream (every genuine forward signal, hypothetical geometry). Nothing about execution changed; CONTROL and SILVER are the same signals partitioned after the fact.\n`;
  R['FORWARD_DATA_QUALITY.md'] = `# FORWARD DATA QUALITY\n\n${head}\n\n| Check | Value |\n|---|---|\n| SC3 observations by provenance | ${Object.entries(silver.data_quality.provenance_counts).map(([k, v]) => `${k} ${v}`).join(', ') || 'none'} |\n| Duplicate signal ids among forward records | ${silver.data_quality.duplicate_signal_ids} |\n| Silver unavailable / stale at decision (NA, never substituted) | ${silver.data_quality.silver_na_at_decision} |\n| Silver bar open != signal bar open (same-bar variant) | ${silver.data_quality.same_open_mismatch} |\n| Observations without hypothetical geometry (entry/SL missing) | ${silver.data_quality.missing_geometry} |\n| Timestamp integrity | observation_id includes bar_time; FORWARD_LIVE requires creation <= 15 min after the decision; cross_asset bars with close > decision are rejected by the schema; outcomes only after the open path resolved / horizon elapsed |\n| Timezone | all times UTC seconds on the Exness server clock (same for XAUUSDm and XAGUSDm) |\n| Feed interruption / stale | reader STALE/NO_BOOK reasons recorded per record; no repair from future data |\n| DOM data quality | ${dom.data_quality} (${dom.available} available / ${dom.unavailable} unavailable forward snapshots; reasons ${JSON.stringify(dom.unavailable_reasons)}) |\n`;
  R['DOM_FORWARD_REPORT.md'] = `# DOM FORWARD REPORT (SC4_DOM_SNAPSHOT_v1, DOM_MEASURE_ONLY = TRUE, FORWARD_ONLY_DATA = TRUE)\n\n${head}\n\n| Counter | Value |\n|---|---|\n| Records carrying a DOM field | ${dom.records_with_dom_field} |\n| FORWARD_LIVE DOM snapshots | ${dom.forward_live} |\n| Available (broker returned a book) | ${dom.available} |\n| Unavailable | ${dom.unavailable} (${Object.entries(dom.unavailable_reasons).map(([k, v]) => `${k} ${v}`).join(', ') || '—'}) |\n| Availability rate | ${pc(dom.availability_rate)} |\n| Imbalance (bid−ask)/(bid+ask): n / mean / p10 / p90 | ${dom.imbalance ? `${dom.imbalance.n} / ${dom.imbalance.mean} / ${dom.imbalance.p10} / ${dom.imbalance.p90}` : '—'} |\n| Mean level count / mean book spread | ${f(dom.level_count_mean, 1)} / ${f(dom.spread_mean, 3)} |\n| Liquidity-withdrawal events (total depth fell >= 50 % vs previous snapshot) | ${dom.liquidity_withdrawal_events} |\n| Status | ${dom.status} |\n\nNo entry rule is derived from DOM. Broker depth (Exness CFD) is not global market depth. No historical DOM exists and none was fabricated. DOM cannot influence order authorisation (the observer has no execution path).\n`;
  R['V8_RESEARCH_RECOMMENDATION.md'] = `# V8 RESEARCH RECOMMENDATION\n\n${head}\n\nSilver status: **${silver.status}** (${silver.reasons.join('; ')}). DOM status: **${dom.status}**.\n\n${silver.status === 'POSITIVE' ? 'Silver demonstrated stable improvement on >= 300 forward signals: prepare a NEW research specification (pre-registered, frozen) for an information-eligibility layer; do NOT activate it automatically.' : silver.status === 'NEGATIVE' ? 'Silver failed the forward gate: reject silver as an execution filter.' : silver.status === 'INCONCLUSIVE' ? 'Silver reached the sample without passing every check: not proven; continue measurement or reject; no activation.' : 'The 300-observation gate has not been reached; no recommendation is made before it. Continue MEASURE_ONLY collection.'}\n\n${dom.available >= 300 ? 'DOM: 300+ forward snapshots collected; a separate, pre-registered DOM research proposal may be written (no rule has been derived).' : 'DOM: insufficient forward snapshots (or broker depth unavailable); no DOM proposal yet.'}\n\n${silver.status !== 'POSITIVE' && dom.available < 300 ? 'Current verdict: NO_FORWARD_INFORMATION_EDGE demonstrated yet (collection in progress).' : ''}\n\nSafety: REAL_TRADE_PLACED NO · DEMO_TRADE_PLACED NO · REAL/DEMO positions unmodified · SILVER_EXECUTION_FILTER OFF · DOM_EXECUTION_FILTER OFF · CAPITAL_HARVEST OFF · AUTO_SCALING OFF · RR 1.70 · LOT 0.01.\n`;
  return R;
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const ROOT = fileURLToPath(new URL('../../', import.meta.url)); const argv = process.argv.slice(2); const arg = (k, d) => { const i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : d; };
  const dir = arg('--dir', `${ROOT}state/shadow`); const out = arg('--out', null); const store = createEvidenceStore({ dir }); const obs = store.readAll('observations'), outs = store.readAll('outcomes');
  const silver = evaluateSilver(obs, outs), dom = evaluateDom(obs); const nowIso = new Date().toISOString(); const reports = renderReports({ silver, dom, nowIso });
  if (out) { mkdirSync(out, { recursive: true }); for (const [name, md] of Object.entries(reports)) writeFileSync(`${out}/${name}`, md); writeFileSync(`${out}/silver_dom_status.json`, JSON.stringify({ generated_at: nowIso, silver, dom }, null, 1)); console.log(`reports written to ${out}`); }
  if (argv.includes('--json') || !out) console.log(JSON.stringify({ generated_at: nowIso, silver: { status: silver.status, reasons: silver.reasons, data_quality: silver.data_quality, states_forward: silver.states_forward, timing_sensitive: silver.timing_sensitive }, dom: { status: dom.status, available: dom.available, unavailable: dom.unavailable, reasons: dom.unavailable_reasons } }, null, 1));
}
