/**
 * V9 CAPITAL HARVEST -- study runner (RESEARCH ONLY). Spec: ../V9_PREREGISTRATION.md (hash asserted).
 * EDGE_PHASE=DEV: baseline reproduction gate, full DEV grid, selection -> configs/selection.json (+ freeze).
 * EDGE_PHASE=FULL: freeze verified, baseline + frozen selections on DEV and HOLDOUT (normal + stress), production-entry sensitivity,
 * live-time vs chronological replay parity, hindsight corruption test, determinism, cost accounting, decision.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { canReenter } from '../../../src/engine/capitalHarvest/positionManager.js';
import { simulate } from '../../trade_economics_v5/scripts/exitPolicies.mjs';
import { features, simulateTrade, postExitContinuation, COSTS, MILESTONES } from './harvest.mjs';

const PHASE = process.env.EDGE_PHASE === 'FULL' ? 'FULL' : 'DEV';
const HERE = dirname(fileURLToPath(import.meta.url)); const ROOT = join(HERE, '..'); const REPO = join(ROOT, '..', '..');
const OUT = join(ROOT, 'results'); const CFG = join(ROOT, 'configs'); mkdirSync(OUT, { recursive: true }); mkdirSync(CFG, { recursive: true });
const sha = (s) => createHash('sha256').update(s).digest('hex'); const shaFile = (p) => sha(readFileSync(p));
if (shaFile(join(ROOT, 'V9_PREREGISTRATION.md')) !== readFileSync(join(ROOT, 'V9_PREREGISTRATION.sha256'), 'utf8').trim().split(/\s+/)[0]) throw new Error('V9_PREREGISTRATION hash mismatch');
const r2 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 100) / 100); const r3 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 1000) / 1000);
const mean = (a) => (a.length ? a.reduce((s, x) => s + x, 0) / a.length : null); const day = (t) => new Date(t * 1000).toISOString().slice(0, 10);
const split = (t) => { const d = day(t); return d >= '2025-05-07' && d <= '2025-12-31' ? 'DEV' : d >= '2026-01-01' && d <= '2026-09-29' ? 'HOLD' : 'EXCLUDED'; };
function rng(seed) { let s = seed >>> 0; return () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
function bootCI(v, n = 2000, seed = 20261001) { if (v.length < 2) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0; for (let j = 0; j < v.length; j++) s += v[Math.floor(rand() * v.length)]; ms.push(s / v.length); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor(0.025 * n)]), r3(ms[Math.floor(0.975 * n)])]; }

// ---------- data ----------
const b5 = JSON.parse(readFileSync(join(REPO, 'handoff', 'edge_discovery_lab', 'data', 'XAUUSDm_bars.json'), 'utf8'))['5m']; const F = features(b5);
function entries(variant, phases) { const out = []; for (const S of phases) { const p = join(REPO, 'research', 'core_pattern_audit_v8', 'results', 'rows', `${variant}_${S}.jsonl`); if (!existsSync(p)) throw new Error(`missing V8 rows ${p} (regenerate with the V8 replay)`); for (const l of readFileSync(p, 'utf8').split('\n')) { if (!l) continue; const r = JSON.parse(l); if (r.act !== 'BUY' && r.act !== 'SELL') continue; out.push({ i: r.i, t: r.t, side: r.act, entry: r.g.e, sl: r.g.sl, model: r.mdl, anchor: r.anc ?? r.g.e, split: split(r.t), tp2: r.g.tp2 }); } } return out.sort((a, b) => a.i - b.i); }
const PH = PHASE === 'FULL' ? ['DEV', 'HOLD'] : ['DEV'];
const E8 = entries('ALL', PH); const sessions = { DEV: new Set(), HOLD: new Set() }; for (const l of readFileSync(join(REPO, 'handoff', 'edge_discovery_lab', 'data', 'lab_rows.jsonl'), 'utf8').split('\n')) { if (!l) continue; const t = Number(l.slice(l.indexOf('"t":') + 4, l.indexOf(',', l.indexOf('"t":')))); const s = split(t); if (s !== 'EXCLUDED') sessions[s].add(day(t)); }

// ---------- policies ----------
const BASE = { name: 'BASELINE_A_FIXED_170R', kind: 'BASELINE' }; const RUN = { name: 'RUN_TO_END', kind: 'RUN_TO_END' };
const GRID = [];
for (const arm of [0.75, 1.0]) { for (const lag of [0.5, 0.75]) GRID.push({ name: `FLOOR_A_arm${arm}_lag${lag}`, family: 'A', kind: 'FLOOR', floor: { family: 'A', arm, lag } }); for (const k of [1.0, 1.5, 2.0]) GRID.push({ name: `FLOOR_B_arm${arm}_k${k}`, family: 'B', kind: 'FLOOR', floor: { family: 'B', arm, k } }); GRID.push({ name: `FLOOR_C_arm${arm}`, family: 'C', kind: 'FLOOR', floor: { family: 'C', arm } }); for (const rho of [0.4, 0.5, 0.6]) GRID.push({ name: `FLOOR_D_arm${arm}_rho${rho}`, family: 'D', kind: 'FLOOR', floor: { family: 'D', arm, rho } }); for (const k of [1.0, 1.5]) GRID.push({ name: `FLOOR_E_arm${arm}_k${k}`, family: 'E', kind: 'FLOOR', floor: { family: 'E', arm, k } }); }
for (const arm of [0.75, 1.0]) for (const h of [0.75, 1.0, 1.25]) { for (const rho of [0.5, 0.6]) GRID.push({ name: `POLICY1_D_arm${arm}_rho${rho}_h${h}`, family: 'POLICY1', kind: 'ADAPTIVE', floor: { family: 'D', arm, rho }, harvestMinR: h }); for (const k of [1.0, 1.5]) GRID.push({ name: `POLICY2_E_arm${arm}_k${k}_h${h}`, family: 'POLICY2', kind: 'ADAPTIVE', floor: { family: 'E', arm, k }, harvestMinR: h }); for (const lag of [0.5, 0.75]) GRID.push({ name: `POLICY3_A_arm${arm}_lag${lag}_h${h}`, family: 'POLICY3', kind: 'ADAPTIVE', floor: { family: 'A', arm, lag }, harvestMinR: h }); }

// ---------- evaluation ----------
const run = (trades, pol, cost = 'normal') => trades.map((t) => ({ t, o: simulateTrade(b5, F, t, pol, COSTS[cost]) })).filter((x) => x.o.status !== 'NO_DATA' && x.o.status !== 'INVALID');
function seqWalk(rows) { const trades = []; let exitBar = -1, last = null, lastLoss = false; for (const x of [...rows].sort((a, b) => a.t.i - b.t.i)) { const ok = canReenter({ signal: { i: x.t.i, model: x.t.model, side: x.t.side, anchor: x.t.anchor }, exitBar, lastTrade: last ? { i: last.i, model: last.model, side: last.side, anchor: last.anchor } : null, lastExitWasLoss: lastLoss }); if (!ok.ok) continue; trades.push(x); exitBar = x.o.exitBar; last = x.t; lastLoss = x.o.r <= 0; } return trades; }
function core(rows) { const R = rows.map((x) => x.o.r); if (!R.length) return { n: 0 }; const w = R.filter((x) => x > 0), l = R.filter((x) => x <= 0); const gw = w.reduce((a, b) => a + b, 0), gl = -l.reduce((a, b) => a + b, 0); let cum = 0, peak = 0, dd = 0, stk = 0, ms = 0; for (const r of R) { cum += r; peak = Math.max(peak, cum); dd = Math.max(dd, peak - cum); if (r <= 0) { stk++; ms = Math.max(ms, stk); } else stk = 0; } return { n: R.length, expectancy_r: r3(mean(R)), pf: gl > 0 ? r2(gw / gl) : null, win_rate: r3(w.length / R.length), avg_win_r: r3(mean(w)), avg_loss_r: l.length ? r3(-mean(l)) : null, max_dd_r: r2(dd), max_loss_streak: ms, net_r: r2(cum), mfe_r: r3(mean(rows.map((x) => x.o.mfe_r))), mae_r: r3(mean(rows.map((x) => x.o.mae_r))), duration_bars: r2(mean(rows.map((x) => x.o.bars))) }; }
function capital(rows, start) { let eq = start, peak = start, dd = 0, minEq = start; for (const x of rows) { eq += x.o.pnl_usd; peak = Math.max(peak, eq); dd = Math.max(dd, (peak - eq) / peak); minEq = Math.min(minEq, eq); } return { start, end: r2(eq), min_equity: r2(minEq), max_dd_pct: r3(dd), survived: minEq > 0 }; }
function evaluate(trades, pol, base, open, cost = 'normal', { detail = false } = {}) {
  const rows = run(trades, pol, cost); const B = new Map(base.map((x) => [`${x.t.i}|${x.t.side}`, x])); const O = new Map(open.map((x) => [`${x.t.i}|${x.t.side}`, x]));
  const paired = rows.map((x) => { const b = B.get(`${x.t.i}|${x.t.side}`); return b ? x.o.r - b.o.r : null; }).filter((v) => v != null);
  const give = rows.filter((x) => x.o.mfe_r >= 0.5).map((x) => ({ r: x.o.mfe_r - x.o.r, mfe: x.o.mfe_r, usd: (x.o.mfe_r - x.o.r) * Math.abs(x.t.entry - x.t.sl) }));
  const early = rows.filter((x) => x.o.early && x.o.r > 0); const cls = { GOOD: 0, ACCEPTABLE: 0, PREMATURE: 0 }; const lost = []; const post = [];
  for (const x of early) { const b = B.get(`${x.t.i}|${x.t.side}`); if (!b) continue; const cont = postExitContinuation(b5, x.t, x.o.exitBar, x.o.exitPx, COSTS[cost]); post.push(cont); const diff = b.o.r - x.o.r; lost.push(Math.max(0, diff)); if (diff >= 0.5 || cont >= 1.0) cls.PREMATURE++; else if (diff > 0) cls.ACCEPTABLE++; else cls.GOOD++; }
  const strong = rows.filter((x) => (O.get(`${x.t.i}|${x.t.side}`)?.o.mfe_r ?? 0) >= 2.0); const preserved = strong.filter((x) => x.o.r >= (B.get(`${x.t.i}|${x.t.side}`)?.o.r ?? -99) - 0.05).length; const closedLow = strong.filter((x) => x.o.early && x.o.r < 1.0).length;
  const armed = rows.filter((x) => x.o.armed_bar != null); const ran = armed.filter((x) => x.o.r > 1.70);
  const exits = rows.reduce((g, x) => { g[x.o.exit] = (g[x.o.exit] ?? 0) + 1; return g; }, {});
  const seq = seqWalk(rows); const res = { policy: pol.name, cost, per_signal: core(rows), paired_mean_r: r3(mean(paired)), paired_ci95_r: bootCI(paired), giveback: { trades_with_mfe_ge_0_5r: give.length, mean_r: r3(mean(give.map((g) => g.r))), aggregate_pct_of_mfe: r3(give.reduce((a, g) => a + g.r, 0) / Math.max(1e-9, give.reduce((a, g) => a + g.mfe, 0))), mean_usd_001lot: r3(mean(give.map((g) => g.usd))) }, early_exits: { n: early.length, share_of_trades: r3(early.length / Math.max(1, rows.length)), classes: cls, premature_rate: early.length ? r3(cls.PREMATURE / early.length) : 0, profit_lost_mean_r: r3(mean(lost)), post_exit_continuation_mean_r: r3(mean(post)) }, harvested_early_share: r3(rows.filter((x) => x.o.exit === 'HARVEST' && x.o.r < 1.70).length / Math.max(1, rows.length)), protected_and_ran_share: r3(ran.length / Math.max(1, rows.length)), armed_share: r3(armed.length / Math.max(1, rows.length)), additional_profit_after_protection_r: r3(mean(armed.map((x) => x.o.r - (x.o.armed_open_r ?? 0)))), right_tail: { strong: strong.length, preserved: preserved, preservation: strong.length ? r3(preserved / strong.length) : null, closed_below_1r: strong.length ? r3(closedLow / strong.length) : null, mean_r_policy: r3(mean(strong.map((x) => x.o.r))), mean_r_baseline: r3(mean(strong.map((x) => B.get(`${x.t.i}|${x.t.side}`)?.o.r).filter((v) => v != null))) }, exits, sequential: { ...core(seq), trades_per_session: null, capital_10k: capital(seq, 10000), capital_62: capital(seq, 62.07) } };
  if (detail) res._rows = rows; return res;
}
const milestoneTable = (open) => Object.fromEntries(MILESTONES.map((m) => [m, r3(open.filter((x) => x.o.milestones[m] != null).length / Math.max(1, open.length))]));

// ---------- DEV phase ----------
const dev = E8.filter((t) => t.split === 'DEV');
const baseDev = run(dev, BASE), openDev = run(dev, RUN);
// gate: baseline / RUN_TO_END reproduce the V5/V8 simulator on every DEV signal
const repro = (() => { let n = 0, mis = 0; const ex = []; for (const t of dev) { const e = { i: t.i, side: t.side, geo: { entry: t.entry, sl: t.sl }, atr: null }; for (const [pol, v5] of [[BASE, { type: 'FIXED', rr: 1.7 }], [RUN, { type: 'OPEN' }]]) { const a = simulateTrade(b5, F, t, pol, COSTS.normal); const b = simulate(b5, e, v5, COSTS.normal); n++; const same = a.status === b.status && (a.status === 'NO_DATA' || (a.exitBar === b.exitBar && Math.abs(a.r - b.r) < 0.0011 && ((a.exit === 'TARGET_170R' && b.exit === 'TP') || a.exit === b.exit))); if (!same) { mis++; if (ex.length < 5) ex.push({ i: t.i, pol: pol.name, v9: [a.status, a.exit, a.exitBar, a.r], v5: [b.status, b.exit, b.exitBar, b.r] }); } } } return { compared: n, mismatches: mis, examples: ex }; })();
console.log('baseline reproduction', JSON.stringify(repro)); if (repro.mismatches) throw new Error('BASELINE REPRODUCTION FAILED');

if (PHASE === 'DEV') {
  const t0 = Date.now(); const grid = GRID.map((pol) => { const ev = evaluate(dev, pol, baseDev, openDev); return { name: pol.name, family: pol.family, params: { ...pol.floor, harvestMinR: pol.harvestMinR ?? null }, ...ev }; });
  const families = [...new Set(GRID.map((g) => g.family))]; const selection = {};
  for (const fam of families) { const cands = grid.filter((g) => g.family === fam); const ok = cands.filter((g) => (g.right_tail.preservation ?? 0) >= 0.8 && (g.early_exits.premature_rate ?? 0) <= 0.3); const pool = ok.length ? ok : cands; const best = [...pool].sort((a, b) => b.paired_mean_r - a.paired_mean_r)[0]; selection[fam] = { name: best.name, constraint: ok.length ? 'MET' : 'CONSTRAINT_UNMET', dev_paired_mean_r: best.paired_mean_r, policy: GRID.find((p) => p.name === best.name) }; }
  const baseline = { per_signal: core(baseDev), sequential: core(seqWalk(baseDev)), milestones_open_path: milestoneTable(openDev), run_to_end: core(openDev) };
  writeFileSync(join(OUT, 'v9_dev_grid.json'), JSON.stringify({ generated_utc: new Date().toISOString(), runtime_s: Math.round((Date.now() - t0) / 1000), signals: dev.length, baseline_reproduction: repro, baseline, grid: grid.map(({ _rows, ...x }) => x), selection }, null, 1));
  writeFileSync(join(CFG, 'selection.json'), JSON.stringify(selection, null, 1));
  const freeze = { frozen_utc: new Date().toISOString(), prereg_sha: shaFile(join(ROOT, 'V9_PREREGISTRATION.md')), harvest_sha: shaFile(join(HERE, 'harvest.mjs')), selection_sha: shaFile(join(CFG, 'selection.json')), dev_grid_sha: shaFile(join(OUT, 'v9_dev_grid.json')) };
  writeFileSync(join(CFG, 'v9_freeze.json'), JSON.stringify(freeze, null, 1)); console.log('selection', JSON.stringify(Object.fromEntries(Object.entries(selection).map(([k, v]) => [k, [v.name, v.constraint, v.dev_paired_mean_r]])))); console.log('frozen', JSON.stringify(freeze));
} else {
  const fz = JSON.parse(readFileSync(join(CFG, 'v9_freeze.json'), 'utf8')); for (const [k, p] of [['prereg_sha', join(ROOT, 'V9_PREREGISTRATION.md')], ['harvest_sha', join(HERE, 'harvest.mjs')], ['selection_sha', join(CFG, 'selection.json')]]) if (fz[k] !== shaFile(p)) throw new Error(`freeze violated: ${k}`);
  const selection = JSON.parse(readFileSync(join(CFG, 'selection.json'), 'utf8')); const SEL = Object.values(selection).map((s) => s.policy);
  const res = { phase: 'FULL', generated_utc: new Date().toISOString(), freeze: fz, baseline_reproduction: repro, splits: {} };
  for (const S of ['DEV', 'HOLD']) { const tr = E8.filter((t) => t.split === S); const out = {}; for (const cost of ['normal', 'stress']) { const base = run(tr, BASE, cost), open = run(tr, RUN, cost); out[cost] = { baseline: { per_signal: core(base), sequential: { ...core(seqWalk(base)), capital_10k: capital(seqWalk(base), 10000), capital_62: capital(seqWalk(base), 62.07) }, giveback: evaluate(tr, BASE, base, open, cost).giveback, right_tail: evaluate(tr, BASE, base, open, cost).right_tail }, run_to_end: core(open), milestones_open_path: milestoneTable(open), policies: Object.fromEntries(SEL.map((p) => [p.name, evaluate(tr, p, base, open, cost)])) }; } out.signals = tr.length; out.sessions = sessions[S].size; res.splits[S] = out; }
  // production-entry sensitivity (HOLD, normal)
  const C8 = entries('CONTROL', ['HOLD']); const cb = run(C8, BASE), co = run(C8, RUN); res.sensitivity_production_entries_hold = { signals: C8.length, baseline: core(cb), policies: Object.fromEntries(SEL.filter((p) => p.kind === 'ADAPTIVE').map((p) => { const e = evaluate(C8, p, cb, co); return [p.name, { per_signal: e.per_signal, paired_mean_r: e.paired_mean_r, paired_ci95_r: e.paired_ci95_r }]; })) };
  // live-time vs chronological replay, hindsight corruption, determinism, cost accounting
  const sample = E8.filter((t, k) => k % 41 === 0).slice(0, 160); let par = { trades: 0, bars: 0, mismatches: 0, examples: [] }, hind = { trades: 0, checks: 0, violations: 0 };
  for (const p of SEL.filter((x) => x.kind === 'ADAPTIVE')) for (const t of sample) { const full = simulateTrade(b5, F, t, p, COSTS.normal, { log: true }); if (full.status === 'NO_DATA') continue; par.trades++; const live = []; const off = Math.max(0, t.i - 600); for (const dlog of full.decisions) { const j = dlog.j; const pre = b5.slice(off, j + 1); const o = simulateTrade(pre, features(pre), { ...t, i: t.i - off }, p, COSTS.normal, { log: true }); const last0 = o.decisions?.at(-1) ?? null; const last = last0 ? { ...last0, j: last0.j + off } : null; live.push(last); par.bars++; if (!last || last.j !== j || last.action !== dlog.action || last.state !== dlog.state || last.floor !== dlog.floor || last.tp_active !== dlog.tp_active) { par.mismatches++; if (par.examples.length < 5) par.examples.push({ i: t.i, j, live: last, replay: dlog }); } }
    // hindsight: corrupt everything after a decision bar; decisions up to it must not change
    hind.trades++; const cut = full.decisions[Math.floor(full.decisions.length / 2)]?.j; if (cut != null) { const bad = b5.map((b, k) => (k > cut ? { ...b, open: b.open * 1.3, high: b.high * 1.5, low: b.low * 0.6, close: b.close * 0.7 } : b)); const o2 = simulateTrade(bad, features(bad), t, p, COSTS.normal, { log: true }); for (const d1 of full.decisions.filter((d) => d.j <= cut)) { hind.checks++; const d2 = o2.decisions.find((d) => d.j === d1.j); if (!d2 || JSON.stringify(d2) !== JSON.stringify(d1)) hind.violations++; } } }
  const det = (() => { const p = SEL.find((x) => x.kind === 'ADAPTIVE'); const h = () => sha(JSON.stringify(run(E8.filter((t) => t.split === 'HOLD'), p).map((x) => [x.t.i, x.o.exit, x.o.r]))); const a = h(), b = h(); return { identical: a === b, sha: a }; })();
  const costCheck = (() => { const tr = E8.filter((t) => t.split === 'HOLD').slice(0, 400); const a = run(tr, BASE, 'normal'), b = run(tr, BASE, 'normal').map((x) => x); const z = tr.map((t) => simulateTrade(b5, F, t, BASE, { spread: 0.24, slip: 0 })).filter((o) => o.status !== 'NO_DATA'); const diff = mean(z.map((o) => o.pnl_usd)) - mean(a.map((x) => x.o.pnl_usd)); return { mean_diff_usd: r3(diff), expected: 0.10, pass: Math.abs(diff - 0.10) < 0.001 && b.length === a.length }; })();
  res.integrity = { live_time_vs_replay: par, hindsight: hind, determinism: det, cost_accounting: costCheck };
  // decision
  const dec = {}; for (const p of SEL.filter((x) => x.kind === 'ADAPTIVE')) { const H = res.splits.HOLD.normal.policies[p.name], D = res.splits.DEV.normal.policies[p.name], Hs = res.splits.HOLD.stress.policies[p.name], B = res.splits.HOLD.normal.baseline; const winVsAvg = !(H.per_signal.win_rate > B.per_signal.win_rate && H.per_signal.expectancy_r < B.per_signal.expectancy_r); const checks = { hold_paired_mean_gt_0: H.paired_mean_r > 0, dev_paired_mean_gt_0: D.paired_mean_r > 0, hold_paired_ci_lower_gt_0: (H.paired_ci95_r?.[0] ?? -1) > 0, hold_stress_paired_mean_gt_0: Hs.paired_mean_r > 0, hold_pf_ge_baseline: (H.per_signal.pf ?? 0) >= (B.per_signal.pf ?? 0), hold_seq_dd_le_baseline: H.sequential.max_dd_r <= B.sequential.max_dd_r, right_tail_preserved_ge_80: (H.right_tail.preservation ?? 0) >= 0.8, premature_rate_le_30: (H.early_exits.premature_rate ?? 1) <= 0.3, no_winrate_for_expectancy_trade: winVsAvg, replay_parity: par.mismatches === 0, hindsight: hind.violations === 0 }; const all = Object.values(checks).every(Boolean); dec[p.name] = { checks, verdict: all ? 'DEMONSTRATED' : (checks.hold_paired_mean_gt_0 && checks.dev_paired_mean_gt_0 ? 'INCONCLUSIVE' : 'NOT_DEMONSTRATED') }; }
  const verdicts = Object.values(dec).map((x) => x.verdict); res.decision = { per_policy: dec, CAPITAL_HARVEST_EDGE: verdicts.includes('DEMONSTRATED') ? 'DEMONSTRATED' : verdicts.includes('INCONCLUSIVE') ? 'INCONCLUSIVE' : 'NOT_DEMONSTRATED', PROPOSED_POLICY: verdicts.includes('DEMONSTRATED') ? 'YES' : 'NO' };
  writeFileSync(join(OUT, 'v9_results_FULL.json'), JSON.stringify(res, null, 1)); console.log('integrity', JSON.stringify(res.integrity)); console.log('decision', JSON.stringify(res.decision));
}
