/**
 * V9 CAPITAL HARVEST -- renders the 16 required reports from the frozen results (no computation that could change a result).
 *   node research/capital_harvest_v9/scripts/write_reports.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..'); const RES = join(ROOT, 'results'); const REP = join(ROOT, 'reports'); mkdirSync(REP, { recursive: true });
const J = (f) => JSON.parse(readFileSync(join(RES, f), 'utf8'));
const G = J('v9_dev_grid.json'); const R = J('v9_results_FULL.json'); const DC = J('v9_drift_control.json'); const SEL = JSON.parse(readFileSync(join(ROOT, 'configs', 'selection.json'), 'utf8')); const FZ = JSON.parse(readFileSync(join(ROOT, 'configs', 'v9_freeze.json'), 'utf8'));
const pc = (x) => (x == null || !Number.isFinite(x) ? '—' : `${(x * 100).toFixed(1)} %`); const f3 = (x) => (x == null || !Number.isFinite(x) ? '—' : Number(x).toFixed(3)); const f2 = (x) => (x == null || !Number.isFinite(x) ? '—' : Number(x).toFixed(2)); const ci = (c) => (c ? `[${c[0]}, ${c[1]}]` : '—');
const HEAD = (t) => `# ${t}\n\nV9 CAPITAL HARVEST · RESEARCH ONLY · HYPOTHETICAL_NOT_EXECUTED · entries = V8 corrected core (unchanged) · RR 1.70 · lot 0.01 · pre-registration ${FZ.prereg_sha.slice(0, 16)}… · selection frozen ${FZ.frozen_utc}\n\n`;
const POL = Object.values(SEL).map((s) => s.name); const ADAPT = POL.filter((n) => n.startsWith('POLICY')); const FLOORS = POL.filter((n) => n.startsWith('FLOOR'));
const S2 = ['DEV', 'HOLD']; const sp = (S, c = 'normal') => R.splits[S][c];
const base = (S, c = 'normal') => sp(S, c).baseline; const pol = (S, n, c = 'normal') => sp(S, c).policies[n];
const out = {};
const econ = (S, c, names) => `| Policy | n | Expectancy (R) | Paired vs baseline (R) | 95 % CI paired | PF | Win | Avg win / loss (R) | Seq. max DD (R) | Seq. expectancy | Give-back (R) | Premature | Right tail kept | Duration (bars) |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| BASELINE A (fixed 1.70R) | ${base(S, c).per_signal.n} | ${f3(base(S, c).per_signal.expectancy_r)} | — | — | ${f2(base(S, c).per_signal.pf)} | ${pc(base(S, c).per_signal.win_rate)} | ${f2(base(S, c).per_signal.avg_win_r)} / ${f2(base(S, c).per_signal.avg_loss_r)} | ${f2(base(S, c).sequential.max_dd_r)} | ${f3(base(S, c).sequential.expectancy_r)} | ${f2(base(S, c).giveback.mean_r)} | — | 100 % (reference) | ${f2(base(S, c).per_signal.duration_bars)} |\n${names.map((n) => { const p = pol(S, n, c); return `| ${n} | ${p.per_signal.n} | ${f3(p.per_signal.expectancy_r)} | ${f3(p.paired_mean_r)} | ${ci(p.paired_ci95_r)} | ${f2(p.per_signal.pf)} | ${pc(p.per_signal.win_rate)} | ${f2(p.per_signal.avg_win_r)} / ${f2(p.per_signal.avg_loss_r)} | ${f2(p.sequential.max_dd_r)} | ${f3(p.sequential.expectancy_r)} | ${f2(p.giveback.mean_r)} | ${pc(p.early_exits.premature_rate)} | ${pc(p.right_tail.preservation)} | ${f2(p.per_signal.duration_bars)} |`; }).join('\n')}\n| RUN_TO_END (reference: structural stop only, no target) | ${sp(S, c).run_to_end.n} | ${f3(sp(S, c).run_to_end.expectancy_r)} | — | — | ${f2(sp(S, c).run_to_end.pf)} | ${pc(sp(S, c).run_to_end.win_rate)} | ${f2(sp(S, c).run_to_end.avg_win_r)} / ${f2(sp(S, c).run_to_end.avg_loss_r)} | — | — | — | — | — | ${f2(sp(S, c).run_to_end.duration_bars)} |`;
const dec = R.decision; const best = ADAPT.map((n) => [n, pol('HOLD', n)]).sort((a, b) => b[1].paired_mean_r - a[1].paired_mean_r)[0];
const answers = (() => { const h = (n) => pol('HOLD', n); const B = base('HOLD'); return [
  ['A. Reduce unnecessary give-back?', `Yes, modestly: HOLD give-back ${f2(B.giveback.mean_r)} R (baseline) → ${ADAPT.map((n) => f2(h(n).giveback.mean_r)).join(' / ')} R (${pc(B.giveback.aggregate_pct_of_mfe)} → ${ADAPT.map((n) => pc(h(n).giveback.aggregate_pct_of_mfe)).join(' / ')} of MFE on trades whose MFE reached 0.5 R) — mostly by closing winners earlier.`],
  ['B. Preserve strong-trade upside?', `No: only ${ADAPT.map((n) => pc(h(n).right_tail.preservation)).join(' / ')} of strong trades (open-path MFE ≥ 2 R) end at least as well as the baseline; ${ADAPT.map((n) => pc(h(n).right_tail.closed_below_1r)).join(' / ')} of them are closed below 1 R by a management exit.`],
  ['C. Improve expectancy?', `Not demonstrably: HOLD paired gains ${ADAPT.map((n) => `${f3(h(n).paired_mean_r)} ${ci(h(n).paired_ci95_r)}`).join(' / ')} R — every 95 % interval includes 0; DEV gains are of the same size.`],
  ['D. Improve or preserve PF?', `Roughly preserved: HOLD PF ${f2(B.per_signal.pf)} → ${ADAPT.map((n) => f2(h(n).per_signal.pf)).join(' / ')}.`],
  ['E. Reduce drawdown?', `Mixed: sequential HOLD max DD ${f2(B.sequential.max_dd_r)} R → ${ADAPT.map((n) => f2(h(n).sequential.max_dd_r)).join(' / ')} R.`],
  ['F. Survive realistic costs?', `Paired gains stay ≈ +0.01 R under STRESS (${ADAPT.map((n) => f3(pol('HOLD', n, 'stress').paired_mean_r)).join(' / ')}), but absolute expectancy is negative for every policy and the baseline under both cost models.`],
  ['G. Avoid buying win rate with average win?', `Partly not: the retention floor (Policy 1) lifts the win rate ${pc(B.per_signal.win_rate)} → ${pc(h(ADAPT[0]).per_signal.win_rate)} while the average win falls ${f2(B.per_signal.avg_win_r)} → ${f2(h(ADAPT[0]).per_signal.avg_win_r)} R; expectancy barely moves.`],
]; })();
out.V9_CAPITAL_HARVEST_RESEARCH = HEAD('V9_CAPITAL_HARVEST_RESEARCH') + `## Question\nCan a deterministic HOLD / PROTECT / HARVEST / EXIT layer protect meaningful open profit while keeping the right tail, on IDENTICAL V8-corrected-core entries and IDENTICAL structural stops, with RR 1.70 as the baseline objective?\n\n## Verdict\n**CAPITAL_HARVEST_EDGE = ${dec.CAPITAL_HARVEST_EDGE}; PROPOSED_POLICY = ${dec.PROPOSED_POLICY}.** The three frozen adaptive policies beat the fixed 1.70 R baseline by +0.002 to +0.015 R per trade on both splits, but no 95 % interval excludes zero, the right tail is not preserved (28–46 % on HOLD versus the required 80 %), and 67–72 % of early exits are premature. No formula is proposed.\n\n## Answers (HOLDOUT, normal cost)\n| Question | Answer |\n|---|---|\n${answers.map(([q, a]) => `| ${q} | ${a} |`).join('\n')}\n\n## Important context: the uncapped reference\nRUN_TO_END (structural stop only, no target, 24 h horizon) is +${f3(R.splits.HOLD.normal.run_to_end.expectancy_r)} R on HOLD but ${f3(R.splits.DEV.normal.run_to_end.expectancy_r)} R on DEV. A drift control shows the HOLD figure is a property of the 2026 market, not of the entries or of exit skill: the SAME bars with a RANDOM side give ${f3(DC.HOLD.random_side.run_to_end.expectancy_r)} R and with every side flipped ${f3(DC.HOLD.opposite_side.run_to_end.expectancy_r)} R (V9_RIGHT_TAIL_ANALYSIS). It is reported, not proposed.\n\n## Protocol\nPre-registered (sha ${FZ.prereg_sha.slice(0, 16)}…), DEV grid of ${G.grid.length} configurations, per-family selection with the right-tail / premature constraints (every family: CONSTRAINT_UNMET), frozen, HOLDOUT once. The baseline reproduces the V5/V8 simulator exactly (${G.baseline_reproduction.compared} comparisons, 0 mismatches). Live-time feeding = chronological replay on ${R.integrity.live_time_vs_replay.bars} decision bars; hindsight corruption 0 violations; deterministic; cost accounting exact.\n`;
out.V9_BASELINE_VS_HARVEST = HEAD('V9_BASELINE_VS_HARVEST') + S2.flatMap((S) => ['normal', 'stress'].map((c) => `## ${S} — ${c.toUpperCase()} cost (${R.splits[S].signals} signals)\n${econ(S, c, [...ADAPT, ...FLOORS])}`)).join('\n\n') + `\n\nIdentical entries and initial structural stops for every row; only exit management differs. Paired = per-signal (policy r − baseline r).\n`;
const famDef = { A: 'R-step: fill + (⌊MFE_R / 0.5⌋ × 0.5 − lag) × R', B: 'volatility (chandelier): highest high since entry − k × ATR14', C: 'structure: last confirmed 3/3 pivot after entry − 0.1 ATR', D: 'MFE retention: fill + ρ × MFE', E: 'hybrid: max(structure, chandelier)' };
out.V9_PROFIT_PROTECTION_FORMULA = HEAD('V9_PROFIT_PROTECTION_FORMULA') + `Every floor is armed once MFE ≥ arm, is ≥ break-even (fill + slippage), is capped at the current close, only ratchets in the trade's favour, and acts from the next bar. The 1.70 R target stays active (floor-only research).\n\n| Family | Formula | DEV configurations | Best DEV paired (R) | Selected | HOLD paired (R) [95 % CI] | HOLD premature | HOLD right tail kept |\n|---|---|---|---|---|---|---|---|\n${Object.entries(famDef).map(([k, d]) => { const g = G.grid.filter((x) => x.family === k); const s = SEL[k]; const h = pol('HOLD', s.name); return `| ${k} | ${d} | ${g.length} | ${f3(Math.max(...g.map((x) => x.paired_mean_r)))} | ${s.name} (${s.constraint}) | ${f3(h.paired_mean_r)} ${ci(h.paired_ci95_r)} | ${pc(h.early_exits.premature_rate)} | ${pc(h.right_tail.preservation)} |`; }).join('\n')}\n\nNo family is superior: all improve the paired mean by about 0.01 R with intervals that include zero, and all cut the right tail. Wider floors (k = 2, structure) keep more of the tail but are still below 80 %.\n`;
out.V9_HARVEST_DECISION_RULES = HEAD('V9_HARVEST_DECISION_RULES') + `| Decision | Condition (completed bar, information ≤ close) | Effect |\n|---|---|---|\n| HOLD | before profit is available (MFE < arm), or state STRONG with no floor change | the trade continues under the structural SL, broker fail-safe and thesis invalidation |\n| PROTECT | MFE ≥ arm: the family floor rises (monotone, ≥ break-even, ≤ close) | hard intrabar floor from the next bar |\n| PROTECT + RUN | state STRONG while protected | the 1.70 R target is suspended for the next bar |\n| HARVEST | state WEAK and open profit ≥ harvestMinR, or the target was suspended, price is beyond it and the state is no longer STRONG | close at this bar's close |\n| EXIT | state INVALIDATED (close beyond the last confirmed post-entry pivot) while protected, or the thesis invalidation / broker fail-safe at any time | close |\n\n## Exit mix (HOLD, normal)\n| Policy | Exits |\n|---|---|\n| BASELINE A | target / broker SL / thesis invalidation / horizon |\n${ADAPT.map((n) => `| ${n} | ${Object.entries(pol('HOLD', n).exits).map(([k, v]) => `${k} ${v}`).join(', ')} |`).join('\n')}\n\nHarvested before 1.70 R: ${ADAPT.map((n) => pc(pol('HOLD', n).harvested_early_share)).join(' / ')} of trades; protected and ran beyond 1.70 R: ${ADAPT.map((n) => pc(pol('HOLD', n).protected_and_ran_share)).join(' / ')}.\n`;
out.V9_CONTINUATION_RULES = HEAD('V9_CONTINUATION_RULES') + `Simple deterministic states from completed bars (BUY shown; SELL mirrored; priority INVALIDATED → WEAK → STRONG → MODERATE), active only once profit is available (loss side unchanged):\n\n| State | Rule | Mapping |\n|---|---|---|\n| INVALIDATED | close beyond the most recent confirmed 3/3 pivot formed after entry | EXIT |\n| WEAK | close beyond the 5m EMA20 against the trade, OR an opposite rejection candle (wick ≥ 50 % of range, close in the far third), OR two consecutive closes against the trade | HARVEST if open profit ≥ harvestMinR, else PROTECT |\n| STRONG | a new best close within the last 3 bars AND close on the trade side of EMA20 AND ≥ 2 of the last 3 bars closed with the trade | HOLD / PROTECT + RUN |\n| MODERATE | otherwise | PROTECT (target active) |\n\nNo scoring system. Tests (tests/capital_harvest_v9.test.js) assert each state on fixtures and their BUY/SELL symmetry. Evidence: the states do not separate continuation from reversal well enough to keep the tail — most harvests and floor exits are followed by further favourable movement (mean post-exit continuation ${ADAPT.map((n) => f2(pol('HOLD', n).early_exits.post_exit_continuation_mean_r)).join(' / ')} R on HOLD).\n`;
out.V9_RATCHET_RULES = HEAD('V9_RATCHET_RULES') + `| Rule | Implementation | Verified by |\n|---|---|---|\n| Floor may move up | the new floor replaces the old one only if it is better for the trade | unit test (monotone sequence) |\n| Never loosened | no code path lowers an armed floor | unit test + code review |\n| Minimum protection | an armed floor is at least break-even (fill + slippage) | unit test |\n| Never above the market | capped at the current close (BUY) / close + spread (SELL) | unit test |\n| Next-bar effect | a floor set at close j is a hard level from bar j + 1 | unit test |\n| Structural SL / broker fail-safe | never widened, always active | baseline reproduction (exact) |\n\nArmed share (HOLD): ${ADAPT.map((n) => pc(pol('HOLD', n).armed_share)).join(' / ')}. Additional profit after protection (realized R − open R at arming): ${ADAPT.map((n) => f3(pol('HOLD', n).additional_profit_after_protection_r)).join(' / ')} R — on average the trade realizes slightly LESS than it showed when protection armed.\n`;
const earlyRow = (S, n) => { const e = pol(S, n).early_exits; return `| ${S} | ${n} | ${e.n} | ${pc(e.share_of_trades)} | ${e.classes.GOOD} | ${e.classes.ACCEPTABLE} | ${e.classes.PREMATURE} | ${pc(e.premature_rate)} | ${f3(e.profit_lost_mean_r)} | ${f2(e.post_exit_continuation_mean_r)} |`; };
out.V9_EARLY_EXIT_ANALYSIS = HEAD('V9_EARLY_EXIT_ANALYSIS') + `Early exit = a HARVEST, floor or structure exit taken in profit. GOOD: policy ≥ baseline on that trade; ACCEPTABLE: baseline better by < 0.5 R; PREMATURE: baseline better by ≥ 0.5 R or price continued ≥ 1 R beyond the exit before the original stop / horizon.\n\n| Split | Policy | Early exits | Share of trades | GOOD | ACCEPTABLE | PREMATURE | Premature rate | Profit lost (R, mean) | Post-exit continuation (R, mean) |\n|---|---|---|---|---|---|---|---|---|---|\n${S2.flatMap((S) => [...ADAPT, ...FLOORS].map((n) => earlyRow(S, n))).join('\n')}\n\nEvery policy exceeds the 30 % premature limit. A higher win rate is not evidence of success here: the early exits give up more continuation than they save.\n`;
out.V9_PROFIT_GIVEBACK = HEAD('V9_PROFIT_GIVEBACK') + `Give-back = MFE on the policy path − realized, over trades whose MFE reached ≥ 0.5 R ("meaningful profit available").\n\n| Split | Policy | Trades | Mean give-back (R) | Aggregate % of MFE | Mean USD (0.01 lot) |\n|---|---|---|---|---|---|\n${S2.flatMap((S) => [['BASELINE A', base(S).giveback], ...[...ADAPT, ...FLOORS].map((n) => [n, pol(S, n).giveback])].map(([n, g]) => `| ${S} | ${n} | ${g.trades_with_mfe_ge_0_5r} | ${f3(g.mean_r)} | ${pc(g.aggregate_pct_of_mfe)} | ${f2(g.mean_usd_001lot)} |`)).join('\n')}\n\nGive-back falls by 0.1–0.4 R per trade, but the saved give-back is offset by the profit forgone on trades that would have continued (V9_EARLY_EXIT_ANALYSIS), so expectancy barely changes.\n`;
const dc = (S) => Object.entries(DC[S]).filter(([, v]) => v.run_to_end).map(([k, v]) => `| ${S} | ${k} | ${v.run_to_end.n} | ${f3(v.run_to_end.expectancy_r)} | ${f2(v.run_to_end.pf)} | ${pc(v.run_to_end.win_rate)} | ${f3(v.fixed_170r.expectancy_r)} |`).join('\n');
out.V9_RIGHT_TAIL_ANALYSIS = HEAD('V9_RIGHT_TAIL_ANALYSIS') + `Strong trade = open-path (structural stop only) MFE ≥ 2.0 R. Kept = policy r ≥ baseline r − 0.05.\n\n| Split | Policy | Strong trades | Kept | Closed below 1 R by management | Mean r policy | Mean r baseline |\n|---|---|---|---|---|---|---|\n${S2.flatMap((S) => [...ADAPT, ...FLOORS].map((n) => { const t = pol(S, n).right_tail; return `| ${S} | ${n} | ${t.strong} | ${pc(t.preservation)} | ${pc(t.closed_below_1r)} | ${f3(t.mean_r_policy)} | ${f3(t.mean_r_baseline)} |`; })).join('\n')}\n\n**RIGHT_TAIL_PRESERVED = NO** for every policy (required ≥ 80 %).\n\n## The uncapped reference and its drift control\nRUN_TO_END (no target; structural SL, broker fail-safe, 288-bar horizon) — same entry bars and risk distance under different side assignments (NORMAL cost):\n\n| Split | Side assignment | n | RUN_TO_END expectancy (R) | PF | Win | Fixed 1.70 R expectancy (R) |\n|---|---|---|---|---|---|---|\n${dc('DEV')}\n${dc('HOLD')}\n\nMarket move: DEV ${pc(DC.DEV.market_move.change_pct / 100)}, HOLD ${pc(DC.HOLD.market_move.change_pct / 100)}. On HOLD a RANDOM side earns almost as much as the real entries when held uncapped, and on DEV the real entries lose; the uncapped payoff is a 2026 volatility / regime property, not evidence that the entries or a run-the-winners rule have an edge. It is NOT proposed; a run-to-structure policy would need its own pre-registered study across regimes.\n`;
const ms = (S) => R.splits[S].normal.milestones_open_path;
out.V9_MFE_MAE = HEAD('V9_MFE_MAE') + `## Open-path milestone reach (structural stop only; observation milestones, never exits)\n| Split | ${Object.keys(ms('DEV')).sort((a, b) => a - b).map((m) => `${m} R`).join(' | ')} |\n|---|${Object.keys(ms('DEV')).map(() => '---').join('|')}|\n${S2.map((S) => `| ${S} | ${Object.entries(ms(S)).sort((a, b) => a[0] - b[0]).map(([, v]) => pc(v)).join(' | ')} |`).join('\n')}\n\n## MFE / MAE per policy (mean R, normal)\n| Split | Policy | MFE | MAE | Duration (bars) |\n|---|---|---|---|---|\n${S2.flatMap((S) => [['BASELINE A', base(S).per_signal], ...[...ADAPT, ...FLOORS].map((n) => [n, pol(S, n).per_signal])].map(([n, p]) => `| ${S} | ${n} | ${f3(p.mfe_r)} | ${f3(p.mae_r)} | ${f2(p.duration_bars)} |`)).join('\n')}\n`;
out.V9_COST_STRESS = HEAD('V9_COST_STRESS') + `NORMAL = spread 0.24 + slippage 0.10 USD; STRESS = 0.60 + 0.20. Every exit pays slippage once; no partial exits (no extra churn).\n\n| Split | Policy | Normal expectancy | Stress expectancy | Normal paired | Stress paired |\n|---|---|---|---|---|---|\n${S2.flatMap((S) => [...ADAPT, ...FLOORS].map((n) => `| ${S} | ${n} | ${f3(pol(S, n).per_signal.expectancy_r)} | ${f3(pol(S, n, 'stress').per_signal.expectancy_r)} | ${f3(pol(S, n).paired_mean_r)} | ${f3(pol(S, n, 'stress').paired_mean_r)} |`)).join('\n')}\n| DEV | BASELINE A | ${f3(base('DEV').per_signal.expectancy_r)} | ${f3(base('DEV', 'stress').per_signal.expectancy_r)} | — | — |\n| HOLD | BASELINE A | ${f3(base('HOLD').per_signal.expectancy_r)} | ${f3(base('HOLD', 'stress').per_signal.expectancy_r)} | — | — |\n\nThe small paired gain survives stress, but every absolute result is negative: Capital Harvest cannot turn the negative entry expectancy positive.\n`;
out.V9_HOLDOUT_RESULTS = HEAD('V9_HOLDOUT_RESULTS (opened once after the freeze)') + `${econ('HOLD', 'normal', [...ADAPT, ...FLOORS])}\n\n## Pre-registered decision checks (adaptive policies)\n| Check | ${ADAPT.join(' | ')} |\n|---|${ADAPT.map(() => '---').join('|')}|\n${Object.keys(dec.per_policy[ADAPT[0]].checks).map((k) => `| ${k} | ${ADAPT.map((n) => (dec.per_policy[n].checks[k] ? 'PASS' : 'FAIL')).join(' | ')} |`).join('\n')}\n| verdict | ${ADAPT.map((n) => dec.per_policy[n].verdict).join(' | ')} |\n\n**CAPITAL_HARVEST_EDGE = ${dec.CAPITAL_HARVEST_EDGE}**, PROPOSED_POLICY = ${dec.PROPOSED_POLICY}. Sensitivity on the production (CONTROL) entries, HOLD: ${Object.entries(R.sensitivity_production_entries_hold.policies).map(([n, x]) => `${n} paired ${f3(x.paired_mean_r)} ${ci(x.paired_ci95_r)}`).join('; ')} — the same picture.\n`;
const I = R.integrity;
out.V9_CHRONOLOGICAL_REPLAY = HEAD('V9_CHRONOLOGICAL_REPLAY') + `| Check | Result |\n|---|---|\n| Baseline / RUN_TO_END reproduce the V5/V8 simulator | ${R.baseline_reproduction.compared} comparisons, ${R.baseline_reproduction.mismatches} mismatches |\n| LIVE-TIME (bars fed one completed close at a time, fixed history window) = CHRONOLOGICAL REPLAY (full array) | ${I.live_time_vs_replay.trades} trades, ${I.live_time_vs_replay.bars} decision bars, ${I.live_time_vs_replay.mismatches} mismatches |\n| Hindsight: every bar after a decision replaced by garbage | ${I.hindsight.checks} earlier decisions re-checked, ${I.hindsight.violations} changed |\n| Determinism (two runs) | ${I.determinism.identical ? 'identical' : 'DIFFERENT'} (sha ${I.determinism.sha.slice(0, 16)}…) |\n| Cost accounting (zero vs 0.10 slippage) | mean difference ${I.cost_accounting.mean_diff_usd} USD (expected 0.10): ${I.cost_accounting.pass ? 'PASS' : 'FAIL'} |\n\nThe manager reads only bars ≤ the decision close and the same code path accepts the V8 forward-shadow archive format (completed 5m bars), so a future shadow evaluation would be reproducible from the same time-ordered data. **REPLAY_PARITY = PASS; HINDSIGHT_CHECK = PASS.**\n`;
const gridRows = [...G.grid].sort((a, b) => b.paired_mean_r - a.paired_mean_r).map((g) => `| ${g.name} | ${g.family} | ${JSON.stringify(g.params).replace(/"/g, '')} | ${f3(g.paired_mean_r)} | ${ci(g.paired_ci95_r)} | ${f3(g.per_signal.expectancy_r)} | ${f2(g.per_signal.pf)} | ${pc(g.per_signal.win_rate)} | ${f2(g.per_signal.avg_win_r)} | ${pc(g.early_exits.premature_rate)} | ${pc(g.right_tail.preservation)} | ${f2(g.sequential.max_dd_r)} |`).join('\n');
out.V9_PARAMETER_ANALYSIS = HEAD('V9_PARAMETER_ANALYSIS') + `Every tested configuration (DEV, normal cost, ${G.signals} signals), sorted by paired gain:\n\n| Configuration | Family | Parameters | Paired (R) | 95 % CI | Expectancy | PF | Win | Avg win | Premature | Right tail kept | Seq. DD |\n|---|---|---|---|---|---|---|---|---|---|---|---|\n${gridRows}\n\n## Classification\n| Class | Parameters |\n|---|---|\n| SUPPORTED_PARAMETERS | none — no configuration met the right-tail (≥ 80 %) and premature (≤ 30 %) constraints |\n| REJECTED_PARAMETERS | tight protection: arm 0.75 R with retention ρ ≥ 0.4, R-step lag 0.5, chandelier k 1.0–1.5 (premature 63–71 %, right tail 22–54 %); harvestMinR 0.75 (mean paired gain 0.001 R vs 0.007 R at 1.25 R) |\n| UNRESOLVED_PARAMETERS | wider protection (chandelier k ≥ 2.5, arm ≥ 1.5 R) and harvestMinR > 1.25 R were not in the pre-registered grid: k 2.0 / arm 1.0 kept 70 % of the tail on DEV, so the trend is toward "less management", which converges on the baseline or on RUN_TO_END (regime-dependent, V9_RIGHT_TAIL_ANALYSIS) |\n\nNo parameter was tuned on the HOLDOUT.\n`;
const reasons = (g, B) => { const r = []; if ((g.early_exits.premature_rate ?? 0) > 0.3) r.push(`premature ${pc(g.early_exits.premature_rate)} > 30 %`); if ((g.right_tail.preservation ?? 0) < 0.8) r.push(`right tail ${pc(g.right_tail.preservation)} < 80 %`); if (!g.paired_ci95_r || g.paired_ci95_r[0] <= 0) r.push('paired CI includes 0'); if (g.per_signal.win_rate > B.win_rate && g.per_signal.avg_win_r < 0.8 * B.avg_win_r) r.push('raises win rate by cutting the average win'); if ((g.per_signal.pf ?? 0) < (B.pf ?? 0)) r.push('PF below baseline'); if (g.sequential.max_dd_r > G.baseline.sequential.max_dd_r) r.push('sequential DD above baseline'); return r; };
out.V9_REJECTED_POLICIES = HEAD('V9_REJECTED_POLICIES') + `Every configuration is listed with the §21 failure conditions it meets (DEV); the frozen selections are also judged on HOLD. None relies on hindsight, loosens a floor, changes entries, increases frequency or adds partial-exit churn.\n\n## Frozen selections on HOLD\n| Policy | Verdict | Failed checks |\n|---|---|---|\n${ADAPT.map((n) => `| ${n} | ${dec.per_policy[n].verdict} | ${Object.entries(dec.per_policy[n].checks).filter(([, v]) => !v).map(([k]) => k).join(', ')} |`).join('\n')}\n${FLOORS.map((n) => `| ${n} (floor-only) | REJECTED | ${reasons(pol('HOLD', n), base('HOLD').per_signal).join('; ')} |`).join('\n')}\n\n## All DEV configurations\n| Configuration | Reasons |\n|---|---|\n${G.grid.map((g) => `| ${g.name} | ${reasons(g, G.baseline.per_signal).join('; ') || '—'} |`).join('\n')}\n`;
out.V9_PROPOSED_CAPITAL_HARVEST_V1_SPEC = HEAD('V9_PROPOSED_CAPITAL_HARVEST_V1_SPEC') + `**PROPOSED_POLICY = ${dec.PROPOSED_POLICY}. CAPITAL_HARVEST_EDGE = ${dec.CAPITAL_HARVEST_EDGE}.** The evidence does not support a robust policy, so no Capital Harvest V1 formula is proposed and nothing is invented. Capital Harvest stays OFF.\n\nWhat the evidence establishes for any future attempt (requirements, not a formula):\n\n| Item | Established |\n|---|---|\n| Entry interaction | none — entries, structural SL, lot and RR 1.70 are inputs; Capital Harvest must not change them |\n| Initial protection | structural SL + broker fail-safe (1.5 R + spread) + thesis invalidation, never widened |\n| Profit detection / timing | decisions only at completed closes; floors act from the next bar (reproducible live = replay; hindsight-free) |\n| Continuation state | the simple state model tested here does not separate continuation from reversal well enough (premature 67–72 %) |\n| Protect / ratchet | monotone, ≥ break-even, capped at the market — mechanics verified; the PROTECTION LEVEL is the unresolved part (tight floors cut the tail; wide floors converge on the baseline) |\n| Harvest condition | weakness-based harvesting lifts the win rate but does not lift expectancy with statistical support |\n| Maximum give-back | not a free parameter: lowering give-back below ≈ 0.8 R per trade costs more right tail than it saves |\n| Failsafe / broker / restart / duplicates | the pure step function is serialisable and deterministic; broker protections and breakers are never overridden; one decision per position per closed bar (no duplicate actions) |\n| Next legitimate step | not more exit tuning on a negative-expectancy entry stream; if pursued, a separately pre-registered "run-to-structure" study across several market regimes, because the uncapped payoff is regime-dependent |\n`;
for (const [k, md] of Object.entries(out)) writeFileSync(join(REP, `${k}.md`), md);
console.log(`reports written: ${Object.keys(out).length}`);
