/**
 * STAGE 12 read-only report. Summarises system health, the DEMO evidence store and applies the pre-declared
 * Stage 12 gates (docs/XAUUSD_STAGE12_DEMO_FORWARD_PROTOCOL.md). Only FORWARD_LIVE_DEMO evidence counts.
 *   node src/demo/report.js [--dir state/demo_forward] [--json] [--export <path>]
 */
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { createDemoEvidenceStore } from './evidence.js';

export const STAGE12_GATES = Object.freeze({ min_completed_trades: 60, min_sessions: 40, min_calendar_days: 90, min_models_covered: 2, expectancy_metric: 'mean R per completed trade (realized net P&L / initial broker risk), bootstrap 95% CI lower bound > 0', profit_factor_min: 1.15, max_drawdown_R: 'PREDECLARED_REVIEW_REQUIRED (report the observed max drawdown in R and USD; no pass/fail number until >= 60 trades exist)', top_winner_removal: 5, cost_stress_usd: 0.40, buy_sell: 'both sides non-negative expectancy or the negative side < 25% of trades', monthly_stability: '>= 60% of months (>= 10 trades) positive, >= 3 months', execution: { max_fill_failure_share: 0.05, max_median_entry_slippage_usd: 0.30, max_unreconciled_events: 0, max_duplicate_attempts: 0 }, missing_data_max_share: 0.10, news_evidence_min: 'at least one Tier B and one Tier A window observed with the executor blocking as designed', restart_recovery: 'every validator restart reconciled without an anomaly record' });
export const STAGE12_STATUSES = Object.freeze(['COLLECTING', 'INSUFFICIENT_FORWARD_EVIDENCE', 'EXECUTION_RELIABILITY_ISSUE', 'PROMISING_UNPROVEN', 'FAILED_FORWARD_GATE', 'ELIGIBLE_FOR_INDEPENDENT_VALIDATION']);
const mean = (a) => (a.length ? a.reduce((x, y) => x + y, 0) / a.length : null); const r3 = (x) => (x == null || !Number.isFinite(x) ? null : +x.toFixed(3));
let seed = 3; const rnd = () => { seed = (seed * 1664525 + 1013904223) % 4294967296; return seed / 4294967296; };
function bootCI(v, R = 2000) { if (v.length < 5) return null; const out = []; for (let k = 0; k < R; k++) { let s = 0; for (let i = 0; i < v.length; i++) s += v[Math.floor(rnd() * v.length)]; out.push(s / v.length); } out.sort((a, b) => a - b); return [r3(out[Math.floor(0.025 * R)]), r3(out[Math.floor(0.975 * R)])]; }

export function buildDemoReport({ dir, nowSec = Date.now() / 1000 } = {}) {
  const store = createDemoEvidenceStore({ dir }); const all = store.readAll(); const status = existsSync(`${dir}/validator_status.json`) ? JSON.parse(readFileSync(`${dir}/validator_status.json`, 'utf8')) : null; const exState = existsSync(`${dir}/executor_state.json`) ? JSON.parse(readFileSync(`${dir}/executor_state.json`, 'utf8')) : null;
  const fwd = all.filter((r) => r.provenance === 'FORWARD_LIVE_DEMO'); const hist = all.length - fwd.length;
  const signals = fwd.filter((r) => r.kind === 'SIGNAL'); const execs = fwd.filter((r) => r.kind === 'EXECUTION'); const outs = fwd.filter((r) => r.kind === 'OUTCOME');
  const executed = signals.filter((s) => s.execution_eligibility === 'EXECUTED'); const blocked = signals.filter((s) => s.execution_eligibility === 'BLOCKED'); const blockReasons = {}; for (const b of blocked) blockReasons[b.block_reason] = (blockReasons[b.block_reason] || 0) + 1;
  const opened = execs.filter((e) => e.event_type === 'OPENED'); const closed = execs.filter((e) => e.event_type === 'CLOSED'); const rejected = execs.filter((e) => e.event_type === 'SKIPPED' && /BROKER|REJECT|RETCODE|ORDER_FAILED|EXECUTOR_THREW/.test(e.reason ?? '')); const dup = execs.filter((e) => /DUPLICATE/.test(e.reason ?? '')); const recon = execs.filter((e) => /RECONCIL|RESUMED_POSITION|INTENT_RESOLVED|ANOMALY/.test(e.event_type)); const retcodes = {}; for (const e of execs) if (e.retcode != null) retcodes[e.retcode] = (retcodes[e.retcode] || 0) + 1;
  const bySignal = new Map(signals.map((s) => [s.signal_id, s])); const trades = closed.map((c) => { const s = bySignal.get(c.signal_id); const open = opened.find((o) => o.signal_id === c.signal_id); const risk = s && Number.isFinite(s.entry) && Number.isFinite(s.structural_stop) ? Math.abs(s.entry - s.structural_stop) * 100 * 0.01 : null; return { signal_id: c.signal_id, side: s?.side ?? null, model: s?.model ?? null, month: (c.event_time_utc ?? '').slice(0, 7), net: Number.isFinite(c.net_pnl) ? c.net_pnl : null, r: risk && Number.isFinite(c.net_pnl) ? c.net_pnl / risk : null, entry_slippage: open && Number.isFinite(open.fill_price) && Number.isFinite(open.requested_price) ? +(Math.abs(open.fill_price - open.requested_price)).toFixed(3) : null, reason: c.reason ?? null, mfe: c.mfe_usd ?? null, mae: c.mae_usd ?? null }; }).filter((t) => t.net != null);
  const nets = trades.map((t) => t.net); const rs = trades.map((t) => t.r).filter(Number.isFinite); const wins = trades.filter((t) => t.net > 0).length; const losses = trades.filter((t) => t.net < 0).length; const pf = nets.filter((x) => x < 0).length ? nets.filter((x) => x > 0).reduce((a, b) => a + b, 0) / -nets.filter((x) => x < 0).reduce((a, b) => a + b, 0) : null;
  let peak = 0, eq = 0, dd = 0; for (const n of nets) { eq += n; peak = Math.max(peak, eq); dd = Math.min(dd, eq - peak); }
  const months = {}; for (const t of trades) (months[t.month] ??= []).push(t.net); const monthRows = Object.entries(months).map(([m, v]) => ({ m, n: v.length, net: r3(v.reduce((a, b) => a + b, 0)) }));
  const sessions = new Set(signals.map((s) => (s.decision_time_utc ?? '').slice(0, 10))).size; const first = signals.length ? Math.min(...signals.map((s) => Date.parse(s.created_at_utc))) : null; const days = first ? (nowSec * 1000 - first) / 86400000 : 0; const modelsCovered = new Set(trades.map((t) => t.model).filter(Boolean)).size;
  const slips = trades.map((t) => t.entry_slippage).filter(Number.isFinite); const median = (a) => { const s = [...a].sort((x, y) => x - y); return s.length ? s[s.length >> 1] : null; };
  const g = STAGE12_GATES; const execIssue = (opened.length + rejected.length ? rejected.length / (opened.length + rejected.length) : 0) > g.execution.max_fill_failure_share || dup.length > g.execution.max_duplicate_attempts || execs.some((e) => e.event_type === 'ANOMALY');
  let stage = 'COLLECTING';
  if (trades.length >= 20) { const enough = trades.length >= g.min_completed_trades && sessions >= g.min_sessions && days >= g.min_calendar_days && modelsCovered >= g.min_models_covered && monthRows.filter((x) => x.n >= 10).length >= 3; const ci = bootCI(rs); const sorted = [...rs].sort((a, b) => b - a); const noTop = sorted.length > 5 ? mean(sorted.slice(5)) : null; const posMonths = monthRows.filter((x) => x.n >= 10); const monthOk = posMonths.length >= 3 && posMonths.filter((x) => x.net > 0).length / posMonths.length >= 0.6;
    if (execIssue) stage = 'EXECUTION_RELIABILITY_ISSUE'; else if (!enough) stage = 'INSUFFICIENT_FORWARD_EVIDENCE'; else { const pass = ci && ci[0] > 0 && (pf ?? 0) >= g.profit_factor_min && (noTop ?? -1) > 0 && monthOk; stage = pass ? 'ELIGIBLE_FOR_INDEPENDENT_VALIDATION' : (mean(rs) > 0 && ci && ci[1] > 0 ? 'PROMISING_UNPROVEN' : 'FAILED_FORWARD_GATE'); } }
  else if (execIssue && (opened.length + rejected.length) >= 5) stage = 'EXECUTION_RELIABILITY_ISSUE';
  return { generated_at: new Date(nowSec * 1000).toISOString(), dir, system: { validator: status ? { status: status.status, pid: status.pid, started_at: status.started_at, gate_ok: status.gate?.ok ?? null, blocker: status.gate?.blocker ?? null, verified: status.gate?.verified ?? null } : null, executor_state: exState ? { position: exState.position ? 'OPEN' : null, daily: exState.daily, halted: exState.halted, protection: exState.protection ? { blocking: exState.protection.blocking, reasons: exState.protection.block_reasons } : null } : null }, demo_account: status?.gate?.account ?? null, by_provenance: { forward_live_demo: fwd.length, historical_or_backfill_or_test: hist }, forward: { signals: signals.length, executed_signals: executed.length, blocked_signals: blocked.length, block_reasons: blockReasons, opened: opened.length, closed: closed.length, open_positions: exState?.position ? 1 : 0, wins, losses, realized_net_usd: r3(nets.reduce((a, b) => a + b, 0)), mean_R: r3(mean(rs)), ci95_R: bootCI(rs), profit_factor: r3(pf), max_drawdown_usd: r3(dd), mean_mfe_usd: r3(mean(trades.map((t) => t.mfe).filter(Number.isFinite))), mean_mae_usd: r3(mean(trades.map((t) => t.mae).filter(Number.isFinite))), median_entry_slippage_usd: median(slips), broker_retcodes: retcodes, rejected: rejected.length, duplicate_attempts: dup.length, reconciliation_events: recon.length, sessions, calendar_days: r3(days), models_covered: modelsCovered, months: monthRows, outcomes_labeled: outs.filter((o) => o.status === 'LABELED').length, outcomes_incomplete: outs.filter((o) => o.status !== 'LABELED').length, blocks: { news: blocked.filter((b) => /NEWS/.test(b.block_reason)).length, shock: blocked.filter((b) => /SHOCK/.test(b.block_reason)).length, spread: blocked.filter((b) => /SPREAD/.test(b.block_reason)).length, feed: blocked.filter((b) => /FEED|STALE_QUOTE/.test(b.block_reason)).length, breaker: blocked.filter((b) => /CONSECUTIVE|DAILY|CEILING/.test(b.block_reason)).length, stale_signal: blocked.filter((b) => /STALE_SIGNAL|PREDATES/.test(b.block_reason)).length, duplicate: blocked.filter((b) => /DUPLICATE/.test(b.block_reason)).length, account_guard: blocked.filter((b) => /DEMO_ACCOUNT|IDENTITY|NOT_VERIFIED/.test(b.block_reason)).length } }, missing_data: { signals_without_context: signals.filter((s) => !s.news && !s.shock_state).length, share: signals.length ? r3(signals.filter((s) => !s.news && !s.shock_state).length / signals.length) : null }, stage12_status: stage, gates: g, store: store.stats(), note: 'A DEMO trade, a profitable day or week is NOT evidence of an edge; EDGE_DEMONSTRATED stays NO until the predeclared gates and a separate independent validation are complete.' };
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) { const arg = (k) => { const i = process.argv.indexOf(k); return i > -1 ? process.argv[i + 1] : null; }; const dir = arg('--dir') ?? fileURLToPath(new URL('../../state/demo_forward', import.meta.url)); const rep = buildDemoReport({ dir }); if (arg('--export')) console.log(JSON.stringify(createDemoEvidenceStore({ dir }).exportSnapshot(arg('--export'), { report: rep }))); if (process.argv.includes('--json')) console.log(JSON.stringify(rep, null, 1)); else { console.log(`STAGE 12 DEMO FORWARD REPORT ${rep.generated_at}`); console.log(`SYSTEM: ${JSON.stringify(rep.system)}`); console.log(`DEMO ACCOUNT: ${JSON.stringify(rep.demo_account)}`); console.log(`PROVENANCE: ${JSON.stringify(rep.by_provenance)}`); console.log(`FORWARD_LIVE_DEMO: ${JSON.stringify(rep.forward)}`); console.log(`MISSING: ${JSON.stringify(rep.missing_data)}`); console.log(`STATUS: ${rep.stage12_status}`); console.log(rep.note); } }
