/**
 * V4 entry populations for TRADE ECONOMICS V5: the feature layer, move-event finder and setup/trigger generator extracted VERBATIM
 * from research/entry_core_v4/scripts/v4_study.mjs (frozen, committed 186c427) so the V4 populations are regenerated identically.
 * Research only; imports nothing from src/.
 */
export function buildV4(b5, ROWS, { split, day, SPLIT, FIRST_I, LAST_I }) {
  const N = b5.length; const GAP = 3 * 3600; const RR = 1.70; const ATR_FLOOR_USD = 2.0; const MIN_RISK_ATR = 0.5; const MAX_RISK_ATR = 3.0;
  const r3 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 1000) / 1000); const r2 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 100) / 100);
console.log('features ...');
const F = { atr: new Array(N).fill(null), atrPct: new Array(N).fill(null), rng12: new Array(N).fill(null), rng24: new Array(N).fill(null), hi12: new Array(N).fill(null), lo12: new Array(N).fill(null), hi20: new Array(N).fill(null), hi36p: new Array(N).fill(null), lo36p: new Array(N).fill(null), contraction: new Array(N).fill(null), overlap6: new Array(N).fill(null), body: new Array(N).fill(null), closeLoc: new Array(N).fill(null), rngA: new Array(N).fill(null), ema20: new Array(N).fill(null), ema50: new Array(N).fill(null), slope20: new Array(N).fill(null), mom3: new Array(N).fill(null), mom6: new Array(N).fill(null), mom12: new Array(N).fill(null), accel: new Array(N).fill(null), run: new Array(N).fill(0), lastSH: new Array(N).fill(null), lastSL: new Array(N).fill(null), swingW: new Array(N).fill(null), dSH: new Array(N).fill(null), dSL: new Array(N).fill(null), eqHigh: new Array(N).fill(false), eqLow: new Array(N).fill(false), sweepHigh: new Array(N).fill(null), sweepLow: new Array(N).fill(null), sinceSweep: new Array(N).fill(null), sinceFailedBO: new Array(N).fill(null), trendUp: new Array(N).fill(false), trendDn: new Array(N).fill(false) };
{ const tr = new Array(N).fill(null); let sum = 0; for (let k = 1; k < N; k++) { tr[k] = Math.max(b5[k].high - b5[k].low, Math.abs(b5[k].high - b5[k - 1].close), Math.abs(b5[k].low - b5[k - 1].close)); sum += tr[k]; if (k > 14) sum -= tr[k - 14]; if (k >= 14) F.atr[k] = sum / 14; }
  const a20 = 2 / 21, a50 = 2 / 51; for (let k = 0; k < N; k++) { const c = b5[k].close; F.ema20[k] = k === 0 ? c : F.ema20[k - 1] + a20 * (c - F.ema20[k - 1]); F.ema50[k] = k === 0 ? c : F.ema50[k - 1] + a50 * (c - F.ema50[k - 1]); }
  const pivH = []; const pivL = []; // confirmed pivots (3 left / 3 right), pushed when confirmed at j + 3
  for (let t = 0; t < N; t++) { const b = b5[t]; const A = F.atr[t]; const range = b.high - b.low; F.body[t] = range > 0 ? Math.abs(b.close - b.open) / range : 0; F.closeLoc[t] = range > 0 ? (b.close - b.low) / range : 0.5; F.rngA[t] = A ? range / A : null;
    const j = t - 3; if (j >= 3) { let ph = true, pl = true; for (let q = 1; q <= 3; q++) { if (!(b5[j].high > b5[j - q].high) || !(b5[j].high >= b5[j + q].high)) ph = false; if (!(b5[j].low < b5[j - q].low) || !(b5[j].low <= b5[j + q].low)) pl = false; } if (ph) pivH.push({ idx: j, price: b5[j].high }); if (pl) pivL.push({ idx: j, price: b5[j].low }); }
    F.lastSH[t] = pivH.length ? pivH[pivH.length - 1] : null; F.lastSL[t] = pivL.length ? pivL[pivL.length - 1] : null;
    if (t >= 36 && A) { let h12 = -Infinity, l12 = Infinity, h24 = -Infinity, l24 = Infinity, hp = -Infinity, lp = Infinity, h20 = -Infinity, h36 = -Infinity, l36 = Infinity; for (let q = 0; q < 12; q++) { h12 = Math.max(h12, b5[t - q].high); l12 = Math.min(l12, b5[t - q].low); } for (let q = 0; q < 24; q++) { h24 = Math.max(h24, b5[t - q].high); l24 = Math.min(l24, b5[t - q].low); } for (let q = 12; q < 24; q++) { hp = Math.max(hp, b5[t - q].high); lp = Math.min(lp, b5[t - q].low); } for (let q = 0; q < 20; q++) h20 = Math.max(h20, b5[t - q].high); for (let q = 1; q <= 36; q++) { h36 = Math.max(h36, b5[t - q].high); l36 = Math.min(l36, b5[t - q].low); }
      F.hi12[t] = h12; F.lo12[t] = l12; F.hi20[t] = h20; F.hi36p[t] = h36; F.lo36p[t] = l36; F.rng12[t] = (h12 - l12) / A; F.rng24[t] = (h24 - l24) / A; F.contraction[t] = hp - lp > 0 ? (h12 - l12) / (hp - lp) : null; let ov = 0; for (let q = 0; q < 6; q++) { const x = b5[t - q], y = b5[t - q - 1]; const inter = Math.min(x.high, y.high) - Math.max(x.low, y.low); const un = Math.max(x.high, y.high) - Math.min(x.low, y.low); ov += un > 0 ? Math.max(0, inter) / un : 1; } F.overlap6[t] = ov / 6;
      F.slope20[t] = (F.ema20[t] - F.ema20[t - 6]) / A; F.mom3[t] = (b.close - b5[t - 3].close) / A; F.mom6[t] = (b.close - b5[t - 6].close) / A; F.mom12[t] = (b.close - b5[t - 12].close) / A; F.accel[t] = F.mom6[t - 3] != null ? F.mom6[t] - F.mom6[t - 3] : null;
      const side = b.close > F.ema20[t] ? 1 : -1; const prev = F.run[t - 1] ?? 0; F.run[t] = Math.sign(prev) === side ? prev + side : side;
      F.trendUp[t] = F.ema20[t] > F.ema50[t] && F.ema50[t] > F.ema50[t - 12]; F.trendDn[t] = F.ema20[t] < F.ema50[t] && F.ema50[t] < F.ema50[t - 12];
      if (F.lastSH[t] && F.lastSL[t]) { F.swingW[t] = (F.lastSH[t].price - F.lastSL[t].price) / A; F.dSH[t] = (F.lastSH[t].price - b.close) / A; F.dSL[t] = (b.close - F.lastSL[t].price) / A; }
      const recentH = pivH.filter((p) => t - p.idx <= 48), recentL = pivL.filter((p) => t - p.idx <= 48); F.eqHigh[t] = recentH.some((p, a) => recentH.some((q, c) => c !== a && Math.abs(p.price - q.price) <= 0.2 * A)); F.eqLow[t] = recentL.some((p, a) => recentL.some((q, c) => c !== a && Math.abs(p.price - q.price) <= 0.2 * A));
      // sweeps: this bar traded beyond the swing known at t-1 and closed back inside (level older than 6 bars)
      const SH = F.lastSH[t - 1], SL = F.lastSL[t - 1]; if (SH && t - SH.idx >= 6 && b.high > SH.price && b.close < SH.price) F.sweepHigh[t] = { level: SH.price, extreme: b.high, low: b.low }; if (SL && t - SL.idx >= 6 && b.low < SL.price && b.close > SL.price) F.sweepLow[t] = { level: SL.price, extreme: b.low, high: b.high };
      F.sinceSweep[t] = F.sweepHigh[t] || F.sweepLow[t] ? 0 : F.sinceSweep[t - 1] == null ? null : F.sinceSweep[t - 1] + 1;
      // failed breakout: a close beyond the swing (known then) followed by a close back inside within 3 bars (known at the re-entry bar)
      let failed = false; for (let q = 1; q <= 3; q++) { const u = t - q; const sh = F.lastSH[u], sl2 = F.lastSL[u]; if (sh && b5[u].close > sh.price && b.close < sh.price) failed = true; if (sl2 && b5[u].close < sl2.price && b.close > sl2.price) failed = true; } F.sinceFailedBO[t] = failed ? 0 : F.sinceFailedBO[t - 1] == null ? null : F.sinceFailedBO[t - 1] + 1; } }
  // ATR percentile over the trailing 288 bars
  for (let t = 300; t < N; t++) { let below = 0, cnt = 0; for (let q = 0; q < 288; q++) { const v = F.atr[t - q]; if (v == null) continue; cnt++; if (v < F.atr[t]) below++; } F.atrPct[t] = cnt ? below / cnt : null; } }

// ---------- move events (V1/V2/V3 definition; validated against V3 counts) ----------
function findEvents(S) { if (S === 'ALL') return [...findEvents('DEV'), ...findEvents('HOLD')]; const events = []; let k = 500; const lo = S === 'DEV' ? SPLIT.dev[0] : SPLIT.hold[0], hi = S === 'DEV' ? SPLIT.dev[1] : SPLIT.hold[1]; while (k < N - 25) { const d = day(b5[k].time); if (d < lo) { k++; continue; } if (d > hi) break; const a = F.atr[k]; if (!a) { k++; continue; } const c0 = b5[k].close; let up = null, dn = null, maxH = -Infinity, minL = Infinity, endBar = null; for (let j = k + 1; j <= k + 24; j++) { const b = b5[j]; if (b.time - b5[j - 1].time > GAP) break; maxH = Math.max(maxH, b.high); minL = Math.min(minL, b.low); if (up == null && maxH - c0 >= 3 * a && c0 - minL <= a) { up = j; } if (dn == null && c0 - minL >= 3 * a && maxH - c0 <= a) { dn = j; } if (up != null || dn != null) { endBar = j; break; } } if (up != null || dn != null) { const dir = up != null ? 'BUY' : 'SELL'; let mag = 0; for (let j = k + 1; j <= Math.min(N - 1, k + 24); j++) { if (b5[j].time - b5[j - 1].time > GAP) break; mag = Math.max(mag, dir === 'BUY' ? b5[j].high - c0 : c0 - b5[j].low); } events.push({ k, t: b5[k].time, dir, end: endBar, time_to_move: endBar - k, magnitude_usd: r2(mag), magnitude_atr: r2(mag / a), atr: r2(a) }); k += 24; } else k++; } return events; }
const EVENTS = { DEV: findEvents('DEV'), HOLD: findEvents('HOLD') }; console.log('events', EVENTS.DEV.length, EVENTS.HOLD.length);
if (EVENTS.DEV.length !== 1640 || EVENTS.HOLD.length !== 1842) throw new Error('event set differs from V3');
const EV_BY_K = { DEV: new Map(EVENTS.DEV.map((e) => [e.k, e])), HOLD: new Map(EVENTS.HOLD.map((e) => [e.k, e])) };
const onsetNear = (S, i, side, lo, hi) => { for (let k = i + lo; k <= i + hi; k++) { const e = EV_BY_K[S].get(k); if (e && e.dir === side) return e; } return null; };

// ---------- setup / trigger families (information-time) ----------
const inRange = (t) => t >= FIRST_I && t <= LAST_I && ROWS.has(t);
function mkSignal(t, side, fam, variant, p, sl, originBar, originLevel, extra = {}) { const b = b5[t]; const A = F.atr[t]; const entry = b.close; let risk = Math.abs(entry - sl); let block = null; if (A < ATR_FLOOR_USD) block = 'ATR_FLOOR'; if (risk < MIN_RISK_ATR * A) { sl = side === 'BUY' ? entry - MIN_RISK_ATR * A : entry + MIN_RISK_ATR * A; risk = MIN_RISK_ATR * A; } if (risk > MAX_RISK_ATR * A) block = block ?? 'RISK'; if (extra.chase) block = block ?? extra.chase; const tp2 = side === 'BUY' ? entry + RR * risk : entry - RR * risk; const origin = side === 'BUY' ? F.lo12[t] : F.hi12[t]; const disp = Math.abs(entry - origin) / A; const row = ROWS.get(t); return { i: t, t: b.time, side, fam, variant, p, model: `${fam}`, geo: { entry: r3(entry), sl: r3(sl), tp2: r3(tp2) }, atr: r3(A), riskAtr: r3(risk / A), originBar, setupAge: t - originBar, anchor: r3(originLevel), anchorLevel: r3(originLevel), disp: r3(disp), block, split: split(b.time), rg5: row?.rg5 ?? null, m30r: row?.m30r ?? null, h1r: row?.h1r ?? null, b15d: row?.b15d ?? null, ses: row?.ses ?? null, isSig: true }; }
const ok = (t) => t >= 400 && inRange(t) && F.atr[t] && F.rng12[t] != null && F.rng12[t - 1] != null;
// setup-state functions (direction: 'BUY' | 'SELL' | 'ANY') used for forensics; signal generators per grid point
const SETUP = {
  A: (t, p) => (F.rng12[t] <= p.wA && F.atrPct[t] != null && F.atrPct[t] <= 0.5 ? 'ANY' : null),
  B: (t, p) => { for (let q = 0; q <= p.aB; q++) { if (F.sweepHigh[t - q]) return 'SELL'; if (F.sweepLow[t - q]) return 'BUY'; } return null; },
  C: (t) => { const sh = F.lastSH[t], sl = F.lastSL[t]; const A = F.atr[t]; const c = b5[t].close; if (sh && c <= sh.price && sh.price - c <= 1.0 * A) return 'BUY'; if (sl && c >= sl.price && c - sl.price <= 1.0 * A) return 'SELL'; return null; },
  D: (t, p) => (pullbackState(t, 'BUY', p.dD) ? 'BUY' : pullbackState(t, 'SELL', p.dD) ? 'SELL' : null),
  E: (t) => (F.mom6[t] != null && Math.abs(F.mom6[t]) <= 0.5 && F.rng12[t] <= 3 ? 'ANY' : null),
  F: (t, p) => ((F.hi36p[t] - F.lo36p[t]) / F.atr[t] <= p.wF ? 'ANY' : null),
  G: (t, p) => (resumptionState(t, 'BUY') ? 'BUY' : resumptionState(t, 'SELL') ? 'SELL' : null),
};
function pullbackState(t, side, dD) { const A = F.atr[t]; if (side === 'BUY' ? !F.trendUp[t] : !F.trendDn[t]) return null; let extIdx = t; for (let q = 0; q < 20; q++) { const u = t - q; if (side === 'BUY' ? b5[u].high > b5[extIdx].high : b5[u].low < b5[extIdx].low) extIdx = u; } if (extIdx === t) return null; let pbIdx = extIdx, touched = false; for (let u = extIdx; u <= t; u++) { if (side === 'BUY' ? b5[u].low < b5[pbIdx].low : b5[u].high > b5[pbIdx].high) pbIdx = u; if (side === 'BUY' ? b5[u].low <= F.ema20[u] + 0.3 * A : b5[u].high >= F.ema20[u] - 0.3 * A) touched = true; } const depth = side === 'BUY' ? (b5[extIdx].high - b5[pbIdx].low) / A : (b5[pbIdx].high - b5[extIdx].low) / A; if (!(depth >= dD) || !touched) return null; const sw = side === 'BUY' ? F.lastSL[t] : F.lastSH[t]; if (sw && (side === 'BUY' ? b5[pbIdx].low <= sw.price : b5[pbIdx].high >= sw.price)) return null; return { extIdx, pbIdx, depth }; }
function resumptionState(t, side) { const A = F.atr[t]; const row = ROWS.get(t); if (!row) return null; if (side === 'BUY' ? !(F.ema50[t] > F.ema50[t - 24] && b5[t].close > F.ema50[t] && row.m30r === 'BULL_TREND') : !(F.ema50[t] < F.ema50[t - 24] && b5[t].close < F.ema50[t] && row.m30r === 'BEAR_TREND')) return null; let touched = false, pbIdx = t; for (let q = 0; q < 12; q++) { const u = t - q; if (side === 'BUY' ? b5[u].close < F.ema50[u] : b5[u].close > F.ema50[u]) return null; if (side === 'BUY' ? b5[u].low <= F.ema20[u] + 0.3 * A : b5[u].high >= F.ema20[u] - 0.3 * A) touched = true; if (side === 'BUY' ? b5[u].low < b5[pbIdx].low : b5[u].high > b5[pbIdx].high) pbIdx = u; } if (!touched) return null; const sw = side === 'BUY' ? F.lastSL[t] : F.lastSH[t]; if (sw && (side === 'BUY' ? b5[pbIdx].low <= sw.price : b5[pbIdx].high >= sw.price)) return null; return { pbIdx }; }
const GRID = [];
for (const wA of [2.0, 2.5, 3.0]) for (const xA of [1.5, 2.0]) for (const v of ['A1', 'A2', 'A3']) GRID.push({ key: `${v}|wA${wA}|xA${xA}`, fam: 'A', variant: v, p: { wA, xA } });
for (const aB of [3, 6]) for (const v of ['B1', 'B2']) GRID.push({ key: `${v}|aB${aB}`, fam: 'B', variant: v, p: { aB } });
GRID.push({ key: 'C1', fam: 'C', variant: 'C1', p: {} }, { key: 'C2', fam: 'C', variant: 'C2', p: {} }); for (const rC of [6, 12]) GRID.push({ key: `C3|rC${rC}`, fam: 'C', variant: 'C3', p: { rC } });
for (const dD of [0.8, 1.2]) for (const v of ['D1', 'D2']) GRID.push({ key: `${v}|dD${dD}`, fam: 'D', variant: v, p: { dD } });
for (const mE of [1.0, 1.5]) GRID.push({ key: `E1|mE${mE}`, fam: 'E', variant: 'E1', p: { mE } });
for (const wF of [3, 4]) for (const v of ['F1', 'F2']) GRID.push({ key: `${v}|wF${wF}`, fam: 'F', variant: v, p: { wF } });
for (const dG of [1.0, 1.5]) GRID.push({ key: `G1|dG${dG}`, fam: 'G', variant: 'G1', p: { dG } });
function generate(g) { const out = []; const seen = new Set(); const push = (s) => { if (!s) return; const k = `${s.i}|${s.side}`; if (seen.has(k)) return; seen.add(k); out.push(s); }; const { fam, variant, p } = g;
  for (let t = 400; t < N; t++) { if (!ok(t)) continue; const b = b5[t]; const A1 = F.atr[t - 1]; const A = F.atr[t];
    if (fam === 'A') { if (!SETUP.A(t - 1, p)) continue; const exp = (b.high - b.low) / A1; if (!(exp >= p.xA)) continue; const hi = F.hi12[t - 1], lo = F.lo12[t - 1]; const up = F.closeLoc[t] >= 0.7, dn = F.closeLoc[t] <= 0.3; let side = null; if (variant === 'A3') side = up ? 'BUY' : dn ? 'SELL' : null; else { if (up && b.close > hi) side = 'BUY'; else if (dn && b.close < lo) side = 'SELL'; if (side && variant === 'A2') { const sw = side === 'BUY' ? F.lastSH[t] : F.lastSL[t]; if (!sw || !(side === 'BUY' ? b.close > sw.price : b.close < sw.price)) side = null; } } if (!side) continue; let origin = t - 1; while (origin > t - 12 && SETUP.A(origin - 1, p)) origin--; push(mkSignal(t, side, 'A', variant, p, side === 'BUY' ? lo : hi, origin, side === 'BUY' ? hi : lo)); }
    else if (fam === 'B') { for (const side of ['SELL', 'BUY']) { const sw = side === 'SELL' ? F.sweepHigh : F.sweepLow; if (variant === 'B1') { const s = sw[t]; if (!s) continue; const chase = Math.abs(b.close - s.level) > 1.5 * A ? 'CHASE' : null; push(mkSignal(t, side, 'B', variant, p, side === 'SELL' ? s.extreme + 0.1 * A : s.extreme - 0.1 * A, t, s.level, { chase })); } else { for (let q = 1; q <= p.aB; q++) { const j = t - q; const s = sw[j]; if (!s) continue; const confirmed = side === 'SELL' ? b.close < s.low : b.close > s.high; if (!confirmed) continue; let earlier = false; for (let u = j + 1; u < t; u++) if (side === 'SELL' ? b5[u].close < s.low : b5[u].close > s.high) earlier = true; if (earlier) continue; const chase = Math.abs(b.close - s.level) > 1.5 * A ? 'CHASE' : null; push(mkSignal(t, side, 'B', variant, p, side === 'SELL' ? s.extreme + 0.1 * A : s.extreme - 0.1 * A, j, s.level, { chase })); } } } }
    else if (fam === 'C') { for (const side of ['BUY', 'SELL']) { const swArr = side === 'BUY' ? F.lastSH : F.lastSL; const isBreak = (u) => { const sw = swArr[u]; if (!sw) return null; const beyond = side === 'BUY' ? b5[u].close > sw.price : b5[u].close < sw.price; const prevBeyond = side === 'BUY' ? b5[u - 1].close > sw.price : b5[u - 1].close < sw.price; return beyond && !prevBeyond ? sw : null; }; const stopOf = (u) => { const s = side === 'BUY' ? F.lastSL[u] : F.lastSH[u]; return s ? s.price : (side === 'BUY' ? b5[u].close - 1.5 * F.atr[u] : b5[u].close + 1.5 * F.atr[u]); };
        if (variant === 'C1') { const sw = isBreak(t); if (!sw) continue; const chase = Math.abs(b.close - sw.price) > 1.5 * A ? 'CHASE' : null; push(mkSignal(t, side, 'C', variant, p, stopOf(t), t, sw.price, { chase })); }
        else if (variant === 'C2') { const sw = isBreak(t - 1); if (!sw) continue; if (!(side === 'BUY' ? b.close > sw.price : b.close < sw.price)) continue; const chase = Math.abs(b5[t - 1].close - sw.price) > 1.5 * A ? 'CHASE' : null; push(mkSignal(t, side, 'C', variant, p, stopOf(t), t - 1, sw.price, { chase })); }
        else { for (let q = 1; q <= p.rC; q++) { const u = t - q; const sw = isBreak(u); if (!sw) continue; let failed = false, retestedEarlier = false; for (let v = u + 1; v < t; v++) { if (side === 'BUY' ? b5[v].close < sw.price : b5[v].close > sw.price) failed = true; if (side === 'BUY' ? b5[v].low <= sw.price + 0.3 * F.atr[v] && b5[v].close > sw.price : b5[v].high >= sw.price - 0.3 * F.atr[v] && b5[v].close < sw.price) retestedEarlier = true; } if (failed || retestedEarlier) continue; const retest = side === 'BUY' ? b.low <= sw.price + 0.3 * A && b.close > sw.price : b.high >= sw.price - 0.3 * A && b.close < sw.price; if (!retest) continue; const chase = Math.abs(b5[u].close - sw.price) > 1.5 * F.atr[u] ? 'CHASE' : null; push(mkSignal(t, side, 'C', variant, p, stopOf(t), u, sw.price, { chase })); } } } }
    else if (fam === 'D') { for (const side of ['BUY', 'SELL']) { if (variant === 'D1') { const st = pullbackState(t - 1, side, p.dD); if (!st) continue; if (t - st.pbIdx > 3) continue; const cont = side === 'BUY' ? b.close > b5[t - 1].high && b.close > F.ema20[t] : b.close < b5[t - 1].low && b.close < F.ema20[t]; if (!cont) continue; push(mkSignal(t, side, 'D', variant, p, side === 'BUY' ? b5[st.pbIdx].low : b5[st.pbIdx].high, st.pbIdx, side === 'BUY' ? b5[st.extIdx].high : b5[st.extIdx].low)); } else { const st = pullbackState(t - 2, side, p.dD); if (!st) continue; const two = side === 'BUY' ? b.close > F.ema20[t] && b5[t - 1].close > F.ema20[t - 1] && !(b5[t - 2].close > F.ema20[t - 2]) : b.close < F.ema20[t] && b5[t - 1].close < F.ema20[t - 1] && !(b5[t - 2].close < F.ema20[t - 2]); if (!two) continue; push(mkSignal(t, side, 'D', variant, p, side === 'BUY' ? b5[st.pbIdx].low : b5[st.pbIdx].high, st.pbIdx, side === 'BUY' ? b5[st.extIdx].high : b5[st.extIdx].low)); } } }
    else if (fam === 'E') { if (!SETUP.E(t - 3)) continue; if (F.accel[t] == null || !(F.accel[t] > 0) || F.body[t] < 0.6) continue; let side = null; if (F.mom3[t] >= p.mE && F.closeLoc[t] >= 0.75) side = 'BUY'; else if (F.mom3[t] <= -p.mE && F.closeLoc[t] <= 0.25) side = 'SELL'; if (!side) continue; const origin = side === 'BUY' ? F.lo12[t] : F.hi12[t]; const disp = Math.abs(b.close - origin) / A; const sl = side === 'BUY' ? Math.min(b5[t].low, b5[t - 1].low, b5[t - 2].low) : Math.max(b5[t].high, b5[t - 1].high, b5[t - 2].high); push(mkSignal(t, side, 'E', variant, p, sl, t - 3, origin, { chase: disp > 2.0 ? 'LATE_EXHAUSTION' : null })); }
    else if (fam === 'F') { if (variant === 'F1') { if (!SETUP.F(t, p)) continue; const hi = F.hi36p[t], lo = F.lo36p[t]; let side = null; if (b.close > hi && F.closeLoc[t] >= 0.6) side = 'BUY'; else if (b.close < lo && F.closeLoc[t] <= 0.4) side = 'SELL'; if (!side) continue; push(mkSignal(t, side, 'F', variant, p, side === 'BUY' ? hi - 0.5 * A : lo + 0.5 * A, t - 1, side === 'BUY' ? hi : lo)); } else { if (!SETUP.F(t - 1, p)) continue; const hi = F.hi36p[t - 1], lo = F.lo36p[t - 1]; let side = null; if (b5[t - 1].close > hi && b.close > hi && !(b5[t - 2].close > hi)) side = 'BUY'; else if (b5[t - 1].close < lo && b.close < lo && !(b5[t - 2].close < lo)) side = 'SELL'; if (!side) continue; push(mkSignal(t, side, 'F', variant, p, side === 'BUY' ? hi - 0.5 * A : lo + 0.5 * A, t - 1, side === 'BUY' ? hi : lo)); } }
    else if (fam === 'G') { for (const side of ['BUY', 'SELL']) { const st = resumptionState(t - 1, side); if (!st) continue; const trig = side === 'BUY' ? F.mom3[t] >= 0.5 && b.close > b5[t - 1].high : F.mom3[t] <= -0.5 && b.close < b5[t - 1].low; if (!trig) continue; const pb = side === 'BUY' ? b5[st.pbIdx].low : b5[st.pbIdx].high; const disp = Math.abs(b.close - pb) / A; push(mkSignal(t, side, 'G', variant, p, pb, st.pbIdx, pb, { chase: disp > p.dG ? 'CHASE' : null })); } } }
  return out; }

  return { F, GRID, generate, EVENTS, SETUP, onsetNear };
}
