/**
 * INFORMATION EDGE V6 -- market context x directional accuracy on FROZEN entry populations (RESEARCH ONLY). Spec: ../V6_PREREGISTRATION.md (hash asserted).
 * EDGE_PHASE=DEV : family diagnostics + fixed/derived filters on DEVELOPMENT; derives configs/finalists.json (DEV-derived state sets, V6-SIMPLE composition)
 * EDGE_PHASE=FULL: asserts the finalists hash; evaluates DEV + HOLDOUT once -> results/v6_results.json
 * Exits frozen (production TP2 for CONTROL, 1.70 R for S3); V6 adds only WAIT decisions.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { canReenter } from '../../../src/engine/capitalHarvest/positionManager.js';
import { buildV4 } from '../../trade_economics_v5/scripts/v4_populations.mjs';
import { simulate } from '../../trade_economics_v5/scripts/exitPolicies.mjs';

const PHASE = process.env.EDGE_PHASE === 'FULL' ? 'FULL' : 'DEV';
const HERE = dirname(fileURLToPath(import.meta.url)); const REPO = join(HERE, '..', '..', '..'); const ROOT = join(REPO, 'research', 'information_edge_v6'); const OUT = join(ROOT, 'results'); const CFG = join(ROOT, 'configs'); mkdirSync(OUT, { recursive: true }); mkdirSync(CFG, { recursive: true });
const shaFile = (p) => createHash('sha256').update(readFileSync(p)).digest('hex');
const PREREG_SHA = readFileSync(join(ROOT, 'V6_PREREGISTRATION.sha256'), 'utf8').trim().split(/\s+/)[0]; if (shaFile(join(ROOT, 'V6_PREREGISTRATION.md')) !== PREREG_SHA) throw new Error('V6_PREREGISTRATION hash mismatch');
const CONTROL_SHA = readFileSync(join(ROOT, 'V6_CONTROL_BASELINE.sha256'), 'utf8').trim().split(/\s+/)[0]; if (shaFile(join(ROOT, 'V6_CONTROL_BASELINE.md')) !== CONTROL_SHA) throw new Error('V6_CONTROL_BASELINE hash mismatch');
const LAB = join(REPO, 'handoff', 'edge_discovery_lab', 'data');
const b5 = JSON.parse(readFileSync(join(LAB, 'XAUUSDm_bars.json'), 'utf8'))['5m']; const N = b5.length;
const COSTS = { normal: { spread: 0.24, slip: 0.10 }, stress: { spread: 0.60, slip: 0.20 } };
const r2 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 100) / 100); const r3 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 1000) / 1000);
const iso = (t) => new Date(t * 1000).toISOString(); const day = (t) => iso(t).slice(0, 10); const month = (t) => iso(t).slice(0, 7); const quarter = (t) => { const d = new Date(t * 1000); return `${d.getUTCFullYear()}Q${Math.floor(d.getUTCMonth() / 3) + 1}`; };
const SPLIT = { dev: ['2025-05-07', '2025-12-31'], hold: ['2026-01-01', '2026-09-29'] };
const split = (t) => { const d = day(t); if (d >= SPLIT.dev[0] && d <= SPLIT.dev[1]) return 'DEV'; if (d >= SPLIT.hold[0] && d <= SPLIT.hold[1]) return 'HOLD'; return 'EXCLUDED'; };
const mean = (a) => (a.length ? a.reduce((s, x) => s + x, 0) / a.length : null); const median = (a) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); const m = s.length >> 1; return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2; }; const pct = (a, p) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); return s[Math.min(s.length - 1, Math.floor(p * s.length))]; };
function rng(seed) { let s = seed >>> 0; return () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
function bootCI(v, n = 2000, seed = 20260930, alpha = 0.05) { if (v.length < 2) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0; for (let j = 0; j < v.length; j++) s += v[Math.floor(rand() * v.length)]; ms.push(s / v.length); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor((alpha / 2) * n)]), r3(ms[Math.floor((1 - alpha / 2) * n)])]; }
function blockCI(rows, n = 2000, seed = 7, alpha = 0.05) { const g = {}; for (const r of rows) (g[day(r.e.t)] ??= []).push(r.o.r); const blocks = Object.values(g); if (blocks.length < 5) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0, c = 0; for (let j = 0; j < blocks.length; j++) { const b = blocks[Math.floor(rand() * blocks.length)]; for (const x of b) { s += x; c++; } } ms.push(s / c); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor((alpha / 2) * n)]), r3(ms[Math.floor((1 - alpha / 2) * n)])]; }

// ---------- data ----------
const ROWS = new Map(); const ROWLIST = []; const sessions = { DEV: new Set(), HOLD: new Set(), ALL: new Set() };
for (const line of readFileSync(join(LAB, 'lab_rows.jsonl'), 'utf8').split('\n')) { if (!line) continue; const r = JSON.parse(line); const sp = split(r.t); if (sp === 'EXCLUDED') continue; r.split = sp; ROWS.set(r.i, r); ROWLIST.push(r); sessions[sp].add(day(r.t)); sessions.ALL.add(day(r.t)); }
ROWLIST.sort((a, b) => a.i - b.i); const FIRST_I = ROWLIST[0].i, LAST_I = ROWLIST[ROWLIST.length - 1].i;
const C = readFileSync(join(REPO, 'research', 'entry_architecture_v2', 'results', 'candidates.jsonl'), 'utf8').trim().split('\n').map((l) => JSON.parse(l)).filter((c) => split(c.t) !== 'EXCLUDED');
const V4 = buildV4(b5, ROWS, { split, day, SPLIT, FIRST_I, LAST_I }); const F = V4.F; const EVENTS = V4.EVENTS;
const V4DEFN = JSON.parse(readFileSync(join(REPO, 'research', 'entry_core_v4', 'configs', 'finalists.json'), 'utf8'));
const NEWS = JSON.parse(readFileSync(join(REPO, 'validation', 'v5_news_edge', 'events_usd_official.json'), 'utf8')).events.map((e) => ({ t: Math.floor(Date.parse(e.utc) / 1000), family: e.family })).filter((e) => e.t >= b5[0].time && e.t <= b5[N - 1].time + 300).sort((a, b) => a.t - b.t);
console.log(`phase ${PHASE}; news events in range ${NEWS.length}`);
// tick-volume relative and spread percentile (information-time)
const relVol = new Array(N).fill(null), spreadP99 = new Array(N).fill(null), spreadMed = new Array(N).fill(null); { for (let t = 48; t < N; t++) { let s = 0; for (let q = 1; q <= 48; q++) s += b5[t - q].volume; relVol[t] = s ? b5[t].volume / (s / 48) : null; } for (let t = 300; t < N; t++) { const w = []; for (let q = 1; q <= 288; q++) w.push(b5[t - q].spread_pts); w.sort((a, b) => a - b); spreadP99[t] = w[Math.floor(0.99 * w.length)]; spreadMed[t] = w[Math.floor(0.5 * w.length)]; } }
const POP = {}; POP.CONTROL = C.filter((c) => c.act === 'BUY' || c.act === 'SELL').map((c) => ({ i: c.i, t: c.t, side: c.side, model: c.model, anchor: c.anchor ?? c.geo.entry, geo: { entry: c.geo.entry, sl: c.geo.sl, tp2: c.geo.tp2 }, atr: c.atr, atrR: c.atrR, split: split(c.t), pop: 'CONTROL' }));
{ const g = V4.GRID.find((x) => x.key === V4DEFN.finalists.S3.grid_key); POP.S3 = V4.generate(g).filter((s) => !s.block).map((s) => ({ i: s.i, t: s.t, side: s.side, model: 'C', anchor: s.anchor, geo: { entry: s.geo.entry, sl: s.geo.sl, tp2: s.geo.tp2 }, atr: s.atr, atrR: ROWS.get(s.i)?.atrR ?? null, split: s.split, pop: 'S3' })); }
const P0 = { mom: 0.3, loc: 1.7, agree: 2, news: 60, shock: 3.0, atrLo: 0.25, atrHi: 0.75, sessShift: 0 };
// ---------- context features (bars <= i, row at i, scheduled timestamps) ----------
function context(e, p = P0) { const i = e.i, side = e.side, sgn = side === 'BUY' ? 1 : -1; const row = ROWS.get(i) ?? {}; const b = b5[i]; const A = e.atr; const risk = Math.abs(e.geo.entry - e.geo.sl);
  const dirOf = (s) => (s === 'BULLISH' ? 'BUY' : s === 'BEARISH' ? 'SELL' : null); const m30 = dirOf(row.m30s), h1 = dirOf(row.h1s), s15 = dirOf(row.b15s), s5 = dirOf(row.st5), b15 = dirOf(row.b15d);
  const agree = [m30, h1].filter((d) => d === side).length, oppose = [m30, h1].filter((d) => d && d !== side).length; const htf = agree === 2 ? 'HTF_ALIGNED' : oppose === 2 ? 'HTF_CONFLICTING' : 'HTF_MIXED';
  const trendOf = (rg) => (rg === 'BULL_TREND' ? 'BUY' : rg === 'BEAR_TREND' ? 'SELL' : null); const htfTrend = [trendOf(row.m30r), trendOf(row.h1r)]; const htfTrendState = htfTrend.every((d) => d === side) ? 'TREND_WITH_BOTH' : htfTrend.some((d) => d && d !== side) ? 'TREND_AGAINST_ANY' : htfTrend.some((d) => d === side) ? 'TREND_WITH_ONE' : 'NO_HTF_TREND';
  const hr = new Date((b.time + 300) * 1000).getUTCHours(), mn = new Date((b.time + 300) * 1000).getUTCMinutes(); const hrS = (hr + 24 + p.sessShift) % 24; const ses = row.ses ?? 'NA'; const overlap = hrS >= 13 && hrS < 16; const sessOpen = [22, 7, 12].some((h) => hrS === h); const usData = (hrS === 12 && mn >= 30) || (hrS === 13 && mn < 30);
  const atrPct = F.atrPct[i]; const volState = atrPct == null ? 'NA' : atrPct < p.atrLo ? 'LOW' : atrPct > p.atrHi ? 'HIGH' : 'NORMAL'; let bigBar = false; for (let q = 0; q < 3; q++) if ((b5[i - q].high - b5[i - q].low) / A >= p.shock) bigBar = true; const spreadAbnormal = spreadP99[i] != null && b.spread_pts > spreadP99[i] && b.spread_pts >= 2 * spreadMed[i]; const shock = bigBar || (e.atrR != null && e.atrR >= 1.5) || spreadAbnormal; const contr = F.contraction[i]; const rangeState = contr == null ? 'NA' : contr < 0.7 ? 'CONTRACTION' : contr > 1.4 ? 'EXPANSION' : 'STABLE';
  const rg = row.rg5 ?? 'NA'; const regimeDir = rg === 'BULL_TREND' || rg === 'BEAR_TREND' ? (trendOf(rg) === side ? 'TREND_WITH' : 'TREND_AGAINST') : rg;
  const mom6 = F.mom6[i] ?? 0, mom12 = F.mom12[i] ?? 0, accel = F.accel[i] ?? 0, run = F.run[i] ?? 0; const momState = Math.abs(mom6) < p.mom ? 'FLAT' : Math.sign(mom6) === sgn ? 'SUPPORTIVE' : 'OPPOSING'; const exhaustion = Math.abs(mom12) >= 2.0 && Math.sign(mom12) === sgn && Math.sign(accel) === -sgn; const persistent = Math.sign(run) === sgn && Math.abs(run) >= 6;
  const hi24 = Math.max(...b5.slice(i - 23, i + 1).map((x) => x.high)), lo24 = Math.min(...b5.slice(i - 23, i + 1).map((x) => x.low)); const pos = hi24 > lo24 ? (e.geo.entry - lo24) / (hi24 - lo24) : 0.5; const posSide = side === 'BUY' ? pos : 1 - pos; const rangePos = posSide < 0.3 ? 'INSIDE_LOW' : posSide > 0.7 ? 'EDGE' : 'MID'; const width24 = F.rng24[i]; const compression = F.rng12[i] != null && F.rng12[i] <= 2.5; let postBreak = false; for (let q = 0; q < 6; q++) { const u = i - q; if (F.hi36p[u] == null) continue; if (side === 'BUY' ? b5[u].close > F.hi36p[u] : b5[u].close < F.lo36p[u]) postBreak = true; } let postReclaim = false; for (let q = 0; q < 6; q++) { if (side === 'BUY' ? F.sweepLow[i - q] : F.sweepHigh[i - q]) postReclaim = true; }
  const opp = side === 'BUY' ? F.lastSH[i] : F.lastSL[i]; const oppDist = opp ? (side === 'BUY' ? opp.price - e.geo.entry : e.geo.entry - opp.price) : null; const oppRatio = oppDist == null || oppDist > 6 * A ? Infinity : oppDist / risk; const location = oppRatio >= p.loc ? 'GOOD' : oppRatio >= 1.0 ? 'NEUTRAL' : 'BAD'; const sup = side === 'BUY' ? F.lastSL[i] : F.lastSH[i]; const supDistAtr = sup ? r3((side === 'BUY' ? e.geo.entry - sup.price : sup.price - e.geo.entry) / A) : null;
  const sw = row.swT && row.swAge != null && row.swAge <= 6 ? ((row.swT === 'SWEEP_LOW' && side === 'BUY') || (row.swT === 'SWEEP_HIGH' && side === 'SELL') ? 'IN_FAVOUR' : 'AGAINST') : 'NONE'; const eq = side === 'BUY' ? F.eqLow[i] : F.eqHigh[i];
  const tClose = b.time + 300; let news = 'NORMAL', newsFam = null; for (const ev of NEWS) { if (ev.t > tClose && ev.t - tClose <= p.news * 60) { news = 'PRE_NEWS'; newsFam = ev.family; break; } if (ev.t <= tClose && tClose - ev.t <= p.news * 60) { news = 'POST_NEWS'; newsFam = ev.family; } }
  const agreeCount = [s5, s15, m30, h1].filter((d) => d === side).length; const xtf = agreeCount >= 4 ? 'FULL' : agreeCount >= p.agree ? 'PARTIAL' : 'CONFLICT'; const agreeThr = p.agree;
  const rv = relVol[i]; const volAct = rv == null ? 'NA' : rv < 0.7 ? 'LOW' : rv > 1.5 ? 'HIGH' : 'NORMAL';
  return { htf, htfTrendState, m30, h1, s15, s5, b15, ses, hour: hrS, overlap, sessOpen, usData, volState, atrPct: r3(atrPct), shock, shockBigBar: bigBar, shockAtr: e.atrR != null && e.atrR >= 1.5, shockSpread: spreadAbnormal, rangeState, rg, regimeDir, momState, mom6: r3(mom6), exhaustion, persistent, rangePos, width24: r3(width24), compression, postBreak, postReclaim, location, oppRatio: Number.isFinite(oppRatio) ? r3(oppRatio) : null, supDistAtr, riskAtr: r3(risk / A), sweep: sw, equal: !!eq, news, newsFam, xtf, agreeCount, agreeThr, volAct, relVol: r3(rv) }; }
for (const pop of Object.keys(POP)) for (const e of POP[pop]) e.ctx = context(e);
console.log(`populations ${Object.entries(POP).map(([k, v]) => `${k}:${v.length}`).join(' ')}`);

// ---------- outcomes ----------
const MEMO = new Map();
function out(e, kind = 'ctl', cse = 'normal', drift = false) { const key = `${e.pop}|${e.i}|${e.side}|${kind}|${cse}|${drift}`; const m = MEMO.get(key); if (m) return m; const pol = kind === 'open' ? { type: 'OPEN' } : e.pop === 'CONTROL' ? { type: 'FIXED', tpPrice: e.geo.tp2 } : { type: 'FIXED', rr: 1.7 }; const o = simulate(b5, e, pol, COSTS[cse], { drift }); MEMO.set(key, o); return o; }
for (const pop of Object.keys(POP)) for (const e of POP[pop]) { const o = out(e, 'open'); e.open = o; e.wrong = o.status !== 'NO_DATA' && o.mfe_r < 0.5 && (o.exit === 'BROKER_SL' || o.exit === 'THESIS_INVALIDATION'); e.bad = o.status !== 'NO_DATA' && o.milestones[1] == null; e.right = o.status !== 'NO_DATA' && o.milestones[1] != null; /* NO_DATA open paths (last 288 bars of the data) are neither wrong nor bad nor right */ }
const rowsOf = (sigs, cse = 'normal', drift = false) => sigs.map((e) => ({ e, o: out(e, 'ctl', cse, drift) })).filter((x) => x.o.status !== 'NO_DATA' && x.o.status !== 'INVALID');
const inS = (S) => (e) => S === 'ALL' || e.split === S;

// ---------- controls ----------
const ctrl = (() => { const rand = rng(99); const leak = [], nul = []; for (let t = 600; t < N - 300; t += 37) { if (!ROWS.has(t)) continue; const a = F.atr[t]; const fut = b5[t + 12].close - b5[t].close; const mk = (side) => ({ i: t, side, atr: a, pop: 'X', geo: { entry: b5[t].close, sl: side === 'BUY' ? b5[t].close - a : b5[t].close + a } }); const o1 = simulate(b5, mk(fut >= 0 ? 'BUY' : 'SELL'), { type: 'FIXED', rr: 1 }), o2 = simulate(b5, mk(rand() < 0.5 ? 'BUY' : 'SELL'), { type: 'FIXED', rr: 1 }); if (o1.status !== 'NO_DATA' && !o1.gap) leak.push(o1.r); if (o2.status !== 'NO_DATA' && !o2.gap) nul.push(o2.r); }
  const sample = POP.CONTROL.slice(0, 400); const diff = mean(sample.map((e) => simulate(b5, e, { type: 'FIXED', tpPrice: e.geo.tp2 }, { spread: 0.24, slip: 0 }).pnl_usd)) - mean(sample.map((e) => simulate(b5, e, { type: 'FIXED', tpPrice: e.geo.tp2 }).pnl_usd)); const firstExitOk = sample.every((e) => { const o = out(e); return o.status === 'NO_DATA' || o.exitBar >= e.i + 1; });
  // prefix invariance of context: recompute the context of 200 signals against a truncated bar array (bars <= i) -- must be identical
  let prefixOk = true; for (const e of POP.CONTROL.filter((x) => x.i < N - 400).slice(0, 200)) { const saveAfter = b5.slice(e.i + 1, e.i + 30).map((b) => ({ ...b })); for (let k = e.i + 1; k < e.i + 30; k++) { b5[k].high += 50; b5[k].low -= 50; b5[k].close += 25; b5[k].volume *= 3; b5[k].spread_pts += 500; } const c2 = context(e); for (let k = e.i + 1; k < e.i + 30; k++) Object.assign(b5[k], saveAfter[k - e.i - 1]); if (JSON.stringify(c2) !== JSON.stringify(e.ctx)) prefixOk = false; }
  return { leak_mean_r: r3(mean(leak)), leak_n: leak.length, null_mean_r: r3(mean(nul)), null_n: nul.length, cost_test: { diff: r3(diff), expected: 0.10, pass: Math.abs(diff - 0.10) < 0.001 }, first_exit_after_entry: firstExitOk, context_prefix_invariance: prefixOk, news_events_in_range: NEWS.length }; })();
console.log('controls', JSON.stringify(ctrl)); if (!(ctrl.leak_mean_r > 0.3) || !(Math.abs(ctrl.null_mean_r) < 0.15) || !ctrl.cost_test.pass || !ctrl.first_exit_after_entry || !ctrl.context_prefix_invariance) throw new Error('CONTROL FAILED');

// ---------- statistics ----------
function seqWalk(rows) { const trades = []; let exitBar = -1, lastTrade = null, lastLoss = false; const skipped = { SAME_OR_EARLIER_CANDLE: 0, STALE_SAME_SETUP: 0, REVENGE_GUARD: 0 }; const occ = []; for (const x of [...rows].sort((a, b) => a.e.i - b.e.i)) { const ok = canReenter({ signal: x.e, exitBar, lastTrade, lastExitWasLoss: lastLoss }); if (!ok.ok) { skipped[ok.reason] = (skipped[ok.reason] ?? 0) + 1; continue; } trades.push(x); occ.push([x.e.i, x.o.exitBar]); exitBar = x.o.exitBar; lastTrade = x.e; lastLoss = x.o.r <= 0; } return { trades, skipped, occ }; }
function pathDD(rows, key = 'r') { let cum = 0, peak = 0, dd = 0, streak = 0, maxStreak = 0; for (const x of rows) { cum += x.o[key]; if (cum > peak) peak = cum; dd = Math.max(dd, peak - cum); if (x.o[key] <= 0) { streak++; maxStreak = Math.max(maxStreak, streak); } else streak = 0; } return { max_dd: r2(dd), final: r2(cum), max_loss_streak: maxStreak }; }
function stats(rows, sessSet = null, { ci = true, block = false } = {}) { const R = rows.map((x) => x.o.r); if (!R.length) return { n: 0 }; const w = R.filter((x) => x > 0), l = R.filter((x) => x <= 0); const gw = w.reduce((a, b) => a + b, 0), gl = -l.reduce((a, b) => a + b, 0); const U = rows.map((x) => x.o.pnl_usd); const perDay = {}; for (const x of rows) perDay[day(x.e.t)] = (perDay[day(x.e.t)] ?? 0) + 1; const counts = sessSet ? [...sessSet].map((d) => perDay[d] ?? 0) : null; const costU = rows.reduce((s, x) => s + x.o.cost_usd, 0); const ddR = pathDD(rows, 'r'), ddU = pathDD(rows, 'pnl_usd');
  return { n: R.length, win_rate: r3(w.length / R.length), avg_win_r: r3(mean(w)), avg_loss_r: l.length ? r3(-mean(l)) : null, expectancy_r: r3(mean(R)), expectancy_usd: r3(mean(U)), pf: gl > 0 ? r2(gw / gl) : (gw > 0 ? 99 : null), ci95_r: ci ? bootCI(R) : null, ci99_r: ci ? bootCI(R, 2000, 20260930, 0.01) : null, block_ci95_r: block ? blockCI(rows) : null, block_ci99_r: block ? blockCI(rows, 2000, 7, 0.01) : null, max_dd_r: ddR.max_dd, max_dd_usd: ddU.max_dd, net_r: ddR.final, max_loss_streak: ddR.max_loss_streak, wrong_direction_rate: r3(rows.filter((x) => x.e.wrong).length / R.length), bad_entry_rate: r3(rows.filter((x) => x.e.bad).length / R.length), right_direction_rate: r3(rows.filter((x) => x.e.right).length / R.length), mfe_open_r: r3(mean(rows.map((x) => x.e.open.mfe_r).filter((v) => v != null))), mae_r: r3(mean(rows.map((x) => x.o.mae_r))), mfe_r: r3(mean(rows.map((x) => x.o.mfe_r))), giveback_r: r3(mean(rows.filter((x) => x.o.mfe_r >= 0.5).map((x) => x.o.mfe_r - x.o.r))), reach_1r: r3(rows.filter((x) => x.e.open.milestones?.[1] != null).length / R.length), reach_1_7r: r3(rows.filter((x) => x.e.open.milestones?.[1.7] != null).length / R.length), open_path_unresolved: rows.filter((x) => x.e.open.status === 'NO_DATA').length, stop_reach: r3(rows.filter((x) => x.o.exit === 'BROKER_SL' || x.o.exit === 'THESIS_INVALIDATION').length / R.length), avg_bars: r2(mean(rows.map((x) => x.o.bars))), cost_usd: r3(costU / R.length), trades_per_session: counts ? { median: pct(counts, 0.5), p90: pct(counts, 0.9), mean: r2(mean(counts)) } : null, zero_trade_session_rate: counts ? r3(counts.filter((x) => x === 0).length / counts.length) : null, side_mix: rows.reduce((g, x) => { g[x.e.side] = (g[x.e.side] ?? 0) + 1; return g; }, {}), risk_usd_mean: r3(mean(rows.map((x) => Math.abs(x.e.geo.entry - x.e.geo.sl)))) }; }
const cell = (rows) => { const s = stats(rows, null, { ci: rows.length >= 30 }); return { n: s.n ?? 0, win_rate: s.win_rate, avg_win_r: s.avg_win_r, avg_loss_r: s.avg_loss_r, expectancy_r: s.expectancy_r, pf: s.pf, max_dd_r: s.max_dd_r, wrong_direction_rate: s.wrong_direction_rate, bad_entry_rate: s.bad_entry_rate, mfe_open_r: s.mfe_open_r, mae_r: s.mae_r, ci95_r: s.ci95_r }; };
const byState = (rows, f) => { const g = {}; for (const x of rows) (g[String(f(x.e))] ??= []).push(x); return Object.fromEntries(Object.entries(g).sort((a, b) => b[1].length - a[1].length).map(([k, v]) => [k, cell(v)])); };
function captureStats(S, rows, occ = []) { const by = {}; for (const x of rows) (by[x.e.i] ??= []).push(x.e.side); let valid = 0, late = 0, wrong = 0, none = 0, positioned = 0, noSetup = 0, gate = 0; for (const ev of EVENTS[S]) { let e = false, l = false, w = false; for (let j = ev.k - 6; j <= ev.k + 6; j++) for (const s of by[j] ?? []) { if (s === ev.dir) { if (j <= ev.k) e = true; else l = true; } else w = true; } if (e) valid++; else if (l) late++; else if (w) wrong++; else if (occ.some(([a, b]) => ev.k >= a && ev.k <= b)) positioned++; else { none++; const r = ROWS.get(ev.k); if (!r || r.wr === 'NO_ELIGIBLE_STRATEGY' || r.wr === 'CHOP') noSetup++; else gate++; } } const n = Math.max(1, EVENTS[S].length); return { events: EVENTS[S].length, capture_rate: r3((valid + late) / n), valid_entry_rate: r3(valid / n), late_entry_rate: r3(late / n), wrong_direction_rate: r3(wrong / n), already_positioned_rate: r3(positioned / n), no_signal_rate: r3(none / n), no_setup_or_trigger_rate: r3(noSetup / n), gate_or_filter_rate: r3(gate / n) }; }
// BLOCKED-by-V6 share of events: events where the unfiltered population had a same-direction signal in the window but the filter removed all of them
function blockedByFilter(S, allRows, keptRows) { const by = (rows) => { const m = {}; for (const x of rows) (m[x.e.i] ??= []).push(x.e.side); return m; }; const A = by(allRows), K = by(keptRows); let blocked = 0; for (const ev of EVENTS[S]) { let had = false, kept = false; for (let j = ev.k - 6; j <= ev.k + 6; j++) { if ((A[j] ?? []).includes(ev.dir)) had = true; if ((K[j] ?? []).includes(ev.dir)) kept = true; } if (had && !kept) blocked++; } return r3(blocked / Math.max(1, EVENTS[S].length)); }

// ---------- families ----------
const FAMILY = { A_HTF: (c) => c.htf, A2_HTF_TREND: (c) => c.htfTrendState, B_SESSION: (c) => c.ses, B2_TIME: (c) => (c.usData ? 'US_DATA_WINDOW' : c.overlap ? 'OVERLAP' : c.sessOpen ? 'SESSION_OPEN' : 'OTHER_TIME'), C_VOL: (c) => c.volState, C2_RANGE_STATE: (c) => c.rangeState, D_REGIME: (c) => c.regimeDir, E_MOM: (c) => c.momState, E2_MOM_FLAGS: (c) => (c.exhaustion ? 'EXHAUSTION' : c.persistent ? 'PERSISTENT' : 'NEITHER'), F_RANGE_POS: (c) => c.rangePos, F2_RANGE_FLAGS: (c) => (c.postBreak ? 'POST_BREAK' : c.postReclaim ? 'POST_RECLAIM' : c.compression ? 'COMPRESSION' : 'PLAIN'), G_LOCATION: (c) => c.location, H_SWEEP: (c) => c.sweep, H2_EQUAL: (c) => (c.equal ? 'EQUAL_LEVEL' : 'NONE'), I_NEWS: (c) => c.news, J_XTF: (c) => c.xtf, K_VOLUME: (c) => c.volAct, L_SHOCK: (c) => (c.shock ? 'SHOCK' : 'NORMAL') };
const FIXED = { 'C1 V6-HTF': (c) => c.htf !== 'HTF_CONFLICTING', 'C2 V6-AGREE': (c) => c.agreeCount >= c.agreeThr, 'C3 V6-MOM': (c) => c.momState !== 'OPPOSING', 'C4 V6-LOC': (c) => c.location !== 'BAD', 'C5 V6-SAFETY': (c) => !c.shock && c.news === 'NORMAL', 'C6 V6-DIR': (c) => [c.m30, c.h1].some((d) => d === c.sideRef) && ![c.m30, c.h1].some((d) => d && d !== c.sideRef) && c.momState !== 'OPPOSING' && c.location !== 'BAD' };
for (const pop of Object.keys(POP)) for (const e of POP[pop]) e.ctx.sideRef = e.side;
const SUPPORT = { A_HTF: (c) => c.htf === 'HTF_ALIGNED', D_REGIME: (c) => c.regimeDir === 'TREND_WITH', E_MOM: (c) => c.momState === 'SUPPORTIVE', J_XTF: (c) => c.xtf !== 'CONFLICT', G_LOCATION: (c) => c.location === 'GOOD', H_SWEEP: (c) => c.sweep === 'IN_FAVOUR', F_RANGE_POS: (c) => c.rangePos === 'INSIDE_LOW', C_VOL: (c) => c.volState === 'NORMAL', B_SESSION: (c) => c.ses === 'LONDON' || c.ses === 'NEW_YORK', K_VOLUME: (c) => c.volAct === 'HIGH', L_SHOCK: (c) => !c.shock, I_NEWS: (c) => c.news === 'NORMAL' };
function familyTables(pop, S) { const rows = rowsOf(POP[pop].filter(inS(S))); const base = cell(rows); const out = { base, families: {} }; for (const [fam, f] of Object.entries(FAMILY)) out.families[fam] = byState(rows, (e) => f(e.ctx)); return out; }
function deriveStateSets(T) { const sets = {}; for (const [fam, states] of Object.entries(T.families)) { const keep = Object.entries(states).filter(([, v]) => v.n >= 150 && v.expectancy_r > T.base.expectancy_r && v.wrong_direction_rate < T.base.wrong_direction_rate).map(([k]) => k); sets[fam] = { states: keep, supported: keep.length > 0 && keep.length < Object.keys(states).length }; } return sets; }
function filteredEval(pop, S, pred, { full = false, allRows = null } = {}) { const sigs = POP[pop].filter(inS(S)); const kept = sigs.filter((e) => pred(e.ctx, e)); const rows = rowsOf(kept); const w = seqWalk(rows); const st = stats(w.trades, sessions[S], { ci: w.trades.length >= 30, block: full }); const all = allRows ?? rowsOf(sigs); const res = { signals_in: sigs.length, signals_kept: kept.length, wait_share: r3(1 - kept.length / Math.max(1, sigs.length)), ...st, skipped: w.skipped, independent: cell(rows), move_capture: captureStats(S, rows, w.occ), blocked_events_share: blockedByFilter(S, all, rows) }; if (full) { const q = {}; for (const x of w.trades) (q[quarter(x.e.t)] ??= []).push(x); res.walk_forward = Object.fromEntries(Object.entries(q).sort().map(([k, v]) => { const s = stats(v, null, { ci: false }); return [k, { n: s.n, expectancy_r: s.expectancy_r, pf: s.pf, max_dd_r: s.max_dd_r, wrong_direction_rate: s.wrong_direction_rate, trades_per_session: r2(v.length / new Set(v.map((x) => day(x.e.t))).size) }]; })); res.quarters_positive_share = Object.keys(res.walk_forward).length ? r3(Object.values(res.walk_forward).filter((v) => v.expectancy_r > 0).length / Object.keys(res.walk_forward).length) : null; const stress = stats(seqWalk(rowsOf(kept, 'stress')).trades, null, { ci: false }); res.stress = { n: stress.n ?? 0, expectancy_r: stress.expectancy_r, pf: stress.pf }; const drift = stats(seqWalk(rowsOf(kept, 'normal', true)).trades, null, { ci: false }); res.drift = { n: drift.n ?? 0, expectancy_r: drift.expectancy_r, pf: drift.pf }; res.tiny_cells = tinyCells(w.trades); res.by_side = byState(w.trades, (e) => e.side); res.by_regime = byState(w.trades, (e) => e.ctx.rg); res.adverse = adverse(w.trades); res.capital = capital(w.trades); } return res; }
function tinyCells(trades) { const cells = {}; for (const x of trades) (cells[`${x.e.model}|${x.e.side}|${x.e.ctx.rg}`] ??= []).push(x.o.r); const net = trades.reduce((s, x) => s + x.o.r, 0); let maxTiny = 0, maxCell = null; const list = Object.entries(cells).map(([k, v]) => { const s = v.reduce((a, b) => a + b, 0); if (v.length < 30 && s > 0 && s > maxTiny) { maxTiny = s; maxCell = k; } return { cell: k, n: v.length, net_r: r2(s), share_of_net: net > 0 ? r3(s / net) : null }; }).sort((a, b) => b.net_r - a.net_r); return { top: list.slice(0, 8), max_tiny_cell: maxCell, max_tiny_cell_share: net > 0 ? r3(maxTiny / net) : null, pass: !(net > 0) || maxTiny / net <= 0.30 }; }
function adverse(trades) { if (!trades.length) return null; const rand = rng(11); const byM = {}; for (const x of trades) (byM[month(x.e.t)] ??= []).push(x.o.r); const dds = [], streaks = []; for (let k = 0; k < 500; k++) { const order = Object.values(byM).sort(() => rand() - 0.5); let cum = 0, peak = 0, dd = 0, stk = 0, ms = 0; for (const m of order) for (const r of [...m].sort(() => rand() - 0.5)) { cum += r; peak = Math.max(peak, cum); dd = Math.max(dd, peak - cum); if (r <= 0) { stk++; ms = Math.max(ms, stk); } else stk = 0; } dds.push(dd); streaks.push(ms); } return { dd_r_p50: r2(median(dds)), dd_r_p90: r2(pct(dds, 0.9)), dd_r_p99: r2(pct(dds, 0.99)), loss_streak_p50: median(streaks), loss_streak_p90: pct(streaks, 0.9) }; }
function capital(trades) { if (!trades.length) return null; const ddU = pathDD(trades, 'pnl_usd'); const margin = r2(mean(trades.map((x) => x.e.geo.entry)) * 100 * 0.01 / 200); const risk = mean(trades.map((x) => 1.5 * Math.abs(x.e.geo.entry - x.e.geo.sl) + 0.24)); return { lot: 0.01, net_usd: ddU.final, max_dd_usd: ddU.max_dd, mean_broker_sl_usd: r2(risk), margin_usd_approx: margin, by_capital: Object.fromEntries([62, 100, 1000, 10000].map((cap) => [cap, { max_dd_pct: r3(ddU.max_dd / cap), risk_pct: r3(risk / cap), margin_pct: r3(margin / cap), feasible_001_lot: cap >= 71 ? 'YES' : 'NO (MARGIN_SAFETY_VETO: equity below ~71 USD)' }])) }; }
function redundancy(pop, S) { const sigs = POP[pop].filter(inS(S)); const keys = Object.keys(SUPPORT); const flags = sigs.map((e) => Object.fromEntries(keys.map((k) => [k, SUPPORT[k](e.ctx) ? 1 : 0]))); const phi = {}; for (let a = 0; a < keys.length; a++) for (let b = a + 1; b < keys.length; b++) { let n11 = 0, n10 = 0, n01 = 0, n00 = 0; for (const f of flags) { const x = f[keys[a]], y = f[keys[b]]; if (x && y) n11++; else if (x) n10++; else if (y) n01++; else n00++; } const den = Math.sqrt((n11 + n10) * (n01 + n00) * (n11 + n01) * (n10 + n00)); phi[`${keys[a]}~${keys[b]}`] = den ? r3((n11 * n00 - n10 * n01) / den) : null; } const rates = Object.fromEntries(keys.map((k) => [k, r3(flags.filter((f) => f[k]).length / flags.length)])); const redundant = Object.entries(phi).filter(([, v]) => v != null && Math.abs(v) >= 0.5); return { support_rates: rates, phi, redundant_pairs: redundant.map(([k, v]) => `${k} (${v})`) }; }

// ---------- candidate predicates ----------
function candidatePreds(defn) { const preds = { ...FIXED }; const sets = defn.state_sets; preds['C7 V6-SIMPLE'] = (c) => defn.simple.every((k) => FIXED[k](c)); const supported = Object.entries(sets).filter(([, v]) => v.supported); preds['C8 V6-COMPOSITE'] = (c) => supported.every(([fam, v]) => v.states.includes(String(FAMILY[fam](c)))); return preds; }
function evalCandidates(pop, S, defn, { full = false } = {}) { const preds = candidatePreds(defn); const allRows = rowsOf(POP[pop].filter(inS(S))); const res = { CONTROL: filteredEval(pop, S, () => true, { full, allRows }) }; for (const [k, pred] of Object.entries(preds)) res[k] = filteredEval(pop, S, pred, { full, allRows }); return res; }
function neighbourhoodFor(pop, S, name, defn) { const nb = {}; const ev = (pred) => { const r = filteredEval(pop, S, pred); return { n: r.n ?? 0, expectancy_r: r.expectancy_r, pf: r.pf, wrong_direction_rate: r.wrong_direction_rate }; }; const recompute = (p) => { for (const e of POP[pop]) { e.ctx2 = context(e, p); e.ctx2.sideRef = e.side; } }; const withCtx = (pred) => (c, e) => pred(e.ctx2, e); const tests = { 'C1 V6-HTF': [], 'C2 V6-AGREE': [['agree', 1], ['agree', 3]], 'C3 V6-MOM': [['mom', 0.2], ['mom', 0.5]], 'C4 V6-LOC': [['loc', 1.5], ['loc', 2.0]], 'C5 V6-SAFETY': [['news', 30], ['news', 90], ['shock', 2.5], ['shock', 3.5]], 'C6 V6-DIR': [['mom', 0.2], ['mom', 0.5], ['loc', 1.5], ['loc', 2.0]], 'C7 V6-SIMPLE': [['mom', 0.2], ['mom', 0.5], ['loc', 1.5], ['loc', 2.0], ['agree', 1], ['agree', 3]], 'C8 V6-COMPOSITE': [['mom', 0.2], ['mom', 0.5], ['loc', 1.5], ['loc', 2.0], ['atrLo', 0.2], ['atrHi', 0.8], ['sessShift', 1], ['sessShift', -1]] }; const preds = candidatePreds(defn); const centre = ev(preds[name]); nb.centre = centre; for (const [pk, val] of tests[name] ?? []) { recompute({ ...P0, [pk]: val }); nb[`${pk}=${val}`] = ev(withCtx((c, e) => preds[name](c, e))); } const vals = Object.entries(nb).filter(([k]) => k !== 'centre').map(([, v]) => v.expectancy_r ?? -9); const cls = !vals.length ? (centre.expectancy_r > 0 ? 'ROBUST (no parameter)' : 'NEGATIVE_CENTRE') : vals.every((x) => x > 0) && centre.expectancy_r > 0 ? 'ROBUST' : centre.expectancy_r > 0 && vals.some((x) => x > 0) ? 'SENSITIVE' : centre.expectancy_r > 0 ? 'FRAGILE' : 'NEGATIVE_CENTRE'; nb.classification = cls; return nb; }

// ---------- run ----------
const result = { meta: { phase: PHASE, generated_utc: new Date().toISOString(), prereg_sha256: PREREG_SHA, control_baseline_sha256: CONTROL_SHA, v4_finalists_sha256: shaFile(join(REPO, 'research', 'entry_core_v4', 'configs', 'finalists.json')), news_file_sha256: shaFile(join(REPO, 'validation', 'v5_news_edge', 'events_usd_official.json')), controls: ctrl, populations: Object.fromEntries(Object.keys(POP).map((k) => [k, { all: POP[k].length, dev: POP[k].filter((e) => e.split === 'DEV').length, hold: POP[k].filter((e) => e.split === 'HOLD').length }])), params: P0, families: Object.keys(FAMILY), fixed_rules: Object.keys(FIXED), split: SPLIT, costs: COSTS, events: { DEV: EVENTS.DEV.length, HOLD: EVENTS.HOLD.length }, tick_volume_note: 'MT5 tick volume of a CFD symbol, not exchange volume' } };
console.log('DEV families ...'); result.DEV = { tables: {}, redundancy: {}, fixed: {} }; for (const pop of ['CONTROL', 'S3']) { result.DEV.tables[pop] = familyTables(pop, 'DEV'); result.DEV.redundancy[pop] = redundancy(pop, 'DEV'); }
{ const c = result.DEV.tables.CONTROL.base; const v5 = JSON.parse(readFileSync(join(REPO, 'research', 'trade_economics_v5', 'results', 'v5_results.json'), 'utf8')); const ref = v5.DEV.grid.CONTROL['CTL|PROD_TP2']; const seq = filteredEval('CONTROL', 'DEV', () => true); if (seq.n !== ref.n || seq.expectancy_r !== ref.expectancy_r || seq.max_dd_r !== ref.max_dd_r) throw new Error(`CONTROL does not reproduce V5 DEV: ${seq.n} ${seq.expectancy_r} ${seq.max_dd_r}`); const v4 = JSON.parse(readFileSync(join(REPO, 'research', 'entry_core_v4', 'results', 'v4_results.json'), 'utf8')); if (seq.move_capture.capture_rate !== v4.DEV.control.move_capture.capture_rate) throw new Error('CONTROL capture does not reproduce V4 DEV'); result.meta.controls.control_reproduces_v5_dev = true; void c; }
const defPath = join(CFG, 'finalists.json');
function deriveDefn() { const sets = deriveStateSets(result.DEV.tables.CONTROL); const base = result.DEV.fixed.CONTROL.CONTROL; const fixedVal = Object.entries(FIXED).filter(([k]) => !k.startsWith('C6')).map(([k, pred]) => { const r = result.DEV.fixed.CONTROL[k]; return { k, dev_n: r.n, improvement_r: r3(r.expectancy_r - base.expectancy_r), wd_lower: r.wrong_direction_rate < base.wrong_direction_rate, incremental: r.n >= 200 && r.expectancy_r - base.expectancy_r >= 0.05 && r.wrong_direction_rate < base.wrong_direction_rate }; }); const inc = fixedVal.filter((x) => x.incremental).sort((a, b) => b.improvement_r - a.improvement_r).slice(0, 3).map((x) => x.k); const simple = inc.length ? inc : [fixedVal.filter((x) => x.improvement_r != null).sort((a, b) => b.improvement_r - a.improvement_r)[0].k]; return { derived_from: 'DEV', state_sets: sets, fixed_rule_dev_value: fixedVal, simple, simple_note: inc.length ? 'intersection of the <=3 DEV-incremental fixed rules with the largest DEV improvement' : 'no fixed rule had DEV incremental value; V6-SIMPLE = the single best fixed rule', candidates: [...Object.keys(FIXED), 'C7 V6-SIMPLE', 'C8 V6-COMPOSITE'] }; }
if (PHASE === 'DEV') { const prelim = { state_sets: deriveStateSets(result.DEV.tables.CONTROL), simple: [] }; for (const pop of ['CONTROL', 'S3']) { const preds = { ...FIXED }; const allRows = rowsOf(POP[pop].filter(inS('DEV'))); result.DEV.fixed[pop] = { CONTROL: filteredEval(pop, 'DEV', () => true, { allRows }) }; for (const [k, pred] of Object.entries(preds)) result.DEV.fixed[pop][k] = filteredEval(pop, 'DEV', pred, { allRows }); } void prelim; const defn = deriveDefn(); result.finalist_definitions = defn; result.DEV.candidates = {}; for (const pop of ['CONTROL', 'S3']) result.DEV.candidates[pop] = evalCandidates(pop, 'DEV', defn); writeFileSync(defPath, JSON.stringify(defn, null, 1)); writeFileSync(join(OUT, 'v6_results_DEV_phase.json'), JSON.stringify(result, null, 1)); console.log('DERIVED', JSON.stringify({ simple: defn.simple, supported: Object.entries(defn.state_sets).filter(([, v]) => v.supported).map(([k, v]) => `${k}:${v.states.join('/')}`), fixed: defn.fixed_rule_dev_value })); console.log('finalists.json sha256', shaFile(defPath)); }
else { const defn = JSON.parse(readFileSync(defPath, 'utf8')); const frozen = readFileSync(join(CFG, 'finalists.sha256'), 'utf8').trim().split(/\s+/)[0]; if (shaFile(defPath) !== frozen) throw new Error('finalists.json does not match its frozen hash'); result.finalist_definitions = defn; result.finalists_sha256 = frozen; for (const pop of ['CONTROL', 'S3']) { const allRows = rowsOf(POP[pop].filter(inS('DEV'))); result.DEV.fixed[pop] = { CONTROL: filteredEval(pop, 'DEV', () => true, { allRows }) }; for (const [k, pred] of Object.entries(FIXED)) result.DEV.fixed[pop][k] = filteredEval(pop, 'DEV', pred, { allRows }); } result.DEV.candidates = {}; for (const pop of ['CONTROL', 'S3']) result.DEV.candidates[pop] = evalCandidates(pop, 'DEV', defn, { full: true });
  console.log('HOLD ...'); result.HOLD = { tables: {}, redundancy: {}, fixed: {}, candidates: {} }; for (const pop of ['CONTROL', 'S3']) { result.HOLD.tables[pop] = familyTables(pop, 'HOLD'); result.HOLD.redundancy[pop] = redundancy(pop, 'HOLD'); const allRows = rowsOf(POP[pop].filter(inS('HOLD'))); result.HOLD.fixed[pop] = { CONTROL: filteredEval(pop, 'HOLD', () => true, { allRows }) }; for (const [k, pred] of Object.entries(FIXED)) result.HOLD.fixed[pop][k] = filteredEval(pop, 'HOLD', pred, { allRows }); result.HOLD.candidates[pop] = evalCandidates(pop, 'HOLD', defn, { full: true }); }
  { const c = result.HOLD.candidates.CONTROL.CONTROL; const v5 = JSON.parse(readFileSync(join(REPO, 'research', 'trade_economics_v5', 'results', 'v5_results.json'), 'utf8')).HOLD.grid.CONTROL['CTL|PROD_TP2']; if (c.n !== v5.n || c.expectancy_r !== v5.expectancy_r || c.max_dd_r !== v5.max_dd_r) throw new Error('CONTROL does not reproduce V5 HOLD'); const v4 = JSON.parse(readFileSync(join(REPO, 'research', 'entry_core_v4', 'results', 'v4_results.json'), 'utf8')); if (c.move_capture.capture_rate !== v4.HOLD.control.move_capture.capture_rate || c.move_capture.wrong_direction_rate !== v4.HOLD.control.move_capture.wrong_direction_rate) throw new Error('CONTROL capture does not reproduce V4 HOLD'); const s3 = result.HOLD.candidates.S3.CONTROL; if (s3.n !== v4.HOLD.candidates.S3.n || s3.expectancy_r !== v4.HOLD.candidates.S3.expectancy_r) throw new Error('S3 does not reproduce V4 HOLD'); result.meta.controls.control_reproduces_v5_hold = true; }
  // incremental value per family (fixed rules) on both splits; neighbourhoods; ablation of the best candidate
  result.incremental = {}; for (const S of ['DEV', 'HOLD']) { result.incremental[S] = {}; for (const pop of ['CONTROL', 'S3']) { const base = result[S].fixed[pop].CONTROL; result.incremental[S][pop] = Object.fromEntries(Object.entries(result[S].fixed[pop]).filter(([k]) => k !== 'CONTROL').map(([k, v]) => [k, { n: v.n, expectancy_r: v.expectancy_r, improvement_r: r3(v.expectancy_r - base.expectancy_r), wrong_direction_rate: v.wrong_direction_rate, wd_change: r3(v.wrong_direction_rate - base.wrong_direction_rate), bad_entry_rate: v.bad_entry_rate, pf: v.pf, max_dd_r: v.max_dd_r, capture: v.move_capture.capture_rate, event_wd: v.move_capture.wrong_direction_rate, wait_share: v.wait_share, incremental: v.n >= 200 && v.expectancy_r - base.expectancy_r >= 0.05 && v.wrong_direction_rate < base.wrong_direction_rate }])); } }
  result.neighbourhoods = {}; for (const name of defn.candidates) result.neighbourhoods[name] = neighbourhoodFor('CONTROL', 'HOLD', name, defn);
  // decisions
  const H = result.HOLD.candidates.CONTROL, D = result.DEV.candidates.CONTROL, ctl = H.CONTROL; const dec = {}; for (const name of defn.candidates) { const c = H[name]; if (!c.n) { dec[name] = { status: 'EMPTY', reasons: ['no trades'] }; continue; } const reasons = []; if (!(c.wrong_direction_rate < ctl.wrong_direction_rate && c.move_capture.wrong_direction_rate < ctl.move_capture.wrong_direction_rate)) reasons.push(`(1) wrong direction not lower (trade ${c.wrong_direction_rate} vs ${ctl.wrong_direction_rate}; events ${c.move_capture.wrong_direction_rate} vs ${ctl.move_capture.wrong_direction_rate})`); if (!(c.bad_entry_rate < ctl.bad_entry_rate)) reasons.push('(2) bad-entry rate not lower'); if (!(c.expectancy_r > 0)) reasons.push('(3) expectancy<=0'); if (!(c.pf > 1.10)) reasons.push('(4) PF<=1.10'); if (!(c.expectancy_r >= ctl.expectancy_r + 0.10 && c.max_dd_r <= ctl.max_dd_r)) reasons.push(`(5) not a meaningful improvement (${c.expectancy_r} vs ${ctl.expectancy_r}; DD ${c.max_dd_r} vs ${ctl.max_dd_r})`); if (!(c.n >= 200)) reasons.push('(6) N<200'); if (!((c.quarters_positive_share ?? 0) >= 0.6)) reasons.push('(7) quarters positive <60%'); const nbc = result.neighbourhoods[name].classification; if (!nbc.startsWith('ROBUST')) reasons.push(`(8) thresholds ${nbc}`); if (c.tiny_cells && !c.tiny_cells.pass) reasons.push('(9) tiny-cell dependence'); if (!(c.stress.expectancy_r > 0)) reasons.push('(10) stress expectancy<=0'); if (!(c.ci95_r?.[0] > 0)) reasons.push('(11) trade CI includes 0'); if (!(c.block_ci95_r?.[0] > 0)) reasons.push('(11) session-block CI includes 0'); if (!(c.move_capture.capture_rate >= 0.5 * ctl.move_capture.capture_rate)) reasons.push(`(12) capture ${c.move_capture.capture_rate} < 50 % of CONTROL ${ctl.move_capture.capture_rate}`); if (!(D[name].expectancy_r > 0)) reasons.push('DEV expectancy<=0'); if (!(c.drift.expectancy_r > 0)) reasons.push('drift expectancy<=0'); const onlyCI = reasons.length > 0 && reasons.every((r) => r.startsWith('(11)')); dec[name] = { status: reasons.length ? (onlyCI ? 'PROMISING_INCONCLUSIVE (fails only the CI requirement)' : 'FAILS_GATE') : 'PASS', reasons, hold_n: c.n, hold_expectancy_r: c.expectancy_r, hold_pf: c.pf, hold_dd_r: c.max_dd_r, ci95_r: c.ci95_r, block_ci95_r: c.block_ci95_r, wrong_direction_rate: c.wrong_direction_rate, event_wd: c.move_capture.wrong_direction_rate, bad_entry_rate: c.bad_entry_rate, capture: c.move_capture.capture_rate, wait_share: c.wait_share, dev_expectancy_r: D[name].expectancy_r, stress_r: c.stress.expectancy_r }; }
  const passing = Object.entries(dec).filter(([, d]) => d.status === 'PASS').map(([k]) => k); const withN = Object.entries(dec).filter(([, d]) => d.hold_n >= 200); const best = passing[0] ?? (withN.sort((a, b) => (b[1].hold_expectancy_r ?? -9) - (a[1].hold_expectancy_r ?? -9))[0]?.[0] ?? null); const b = best ? H[best] : null; const bd = best ? dec[best] : null;
  // ablation of the best candidate (remove one component)
  const preds = candidatePreds(defn); result.ablation = {}; if (best) { const comps = best.startsWith('C7') ? defn.simple : best.startsWith('C8') ? Object.entries(defn.state_sets).filter(([, v]) => v.supported).map(([k]) => k) : best.startsWith('C6') ? ['HTF', 'MOM', 'LOC'] : best.startsWith('C5') ? ['SHOCK', 'NEWS'] : []; for (const S of ['DEV', 'HOLD']) { result.ablation[S] = { full: { n: result[S].candidates.CONTROL[best].n, expectancy_r: result[S].candidates.CONTROL[best].expectancy_r, wrong_direction_rate: result[S].candidates.CONTROL[best].wrong_direction_rate, capture: result[S].candidates.CONTROL[best].move_capture.capture_rate } }; for (const comp of comps) { let pred; if (best.startsWith('C7')) pred = (c) => defn.simple.filter((k) => k !== comp).every((k) => FIXED[k](c)); else if (best.startsWith('C8')) pred = (c) => Object.entries(defn.state_sets).filter(([k, v]) => v.supported && k !== comp).every(([fam, v]) => v.states.includes(String(FAMILY[fam](c)))); else if (best.startsWith('C6')) pred = (c) => (comp === 'HTF' ? true : [c.m30, c.h1].some((d) => d === c.sideRef) && ![c.m30, c.h1].some((d) => d && d !== c.sideRef)) && (comp === 'MOM' ? true : c.momState !== 'OPPOSING') && (comp === 'LOC' ? true : c.location !== 'BAD'); else pred = (c) => (comp === 'SHOCK' ? true : !c.shock) && (comp === 'NEWS' ? true : c.news === 'NORMAL'); const r = filteredEval('CONTROL', S, pred); result.ablation[S][`minus_${comp}`] = { n: r.n, expectancy_r: r.expectancy_r, wrong_direction_rate: r.wrong_direction_rate, capture: r.move_capture.capture_rate, delta_expectancy_vs_full: r3((r.expectancy_r ?? 0) - (result[S].candidates.CONTROL[best].expectancy_r ?? 0)) }; } } result.ablation.best = best; result.ablation.components = comps; void preds; }
  const incBoth = Object.keys(result.incremental.HOLD.CONTROL).filter((k) => result.incremental.HOLD.CONTROL[k].incremental && result.incremental.DEV.CONTROL[k].incremental); const incOne = Object.keys(result.incremental.HOLD.CONTROL).filter((k) => result.incremental.HOLD.CONTROL[k].incremental || result.incremental.DEV.CONTROL[k].incremental);
  const dirImproved = b ? ((ctl.wrong_direction_rate - b.wrong_direction_rate >= 0.03 && ctl.move_capture.wrong_direction_rate - b.move_capture.wrong_direction_rate >= 0.03 && b.n >= 200) ? 'YES' : (ctl.wrong_direction_rate - b.wrong_direction_rate >= 0.03 || ctl.move_capture.wrong_direction_rate - b.move_capture.wrong_direction_rate >= 0.03) ? 'INCONCLUSIVE' : 'NO') : 'NO';
  const anyInconclusive = Object.values(dec).some((d) => d.hold_n >= 200 && d.hold_expectancy_r > 0 && d.wrong_direction_rate < ctl.wrong_direction_rate && !(d.ci95_r?.[0] > 0));
  const bestFamily = Object.entries(result.incremental.HOLD.CONTROL).sort((a, b2) => (b2[1].improvement_r ?? -9) - (a[1].improvement_r ?? -9))[0]?.[0] ?? null;
  result.decisions = { candidates: dec, passing, best_candidate: best, best_information_family_by_hold_improvement: bestFamily, families_with_incremental_value_both_splits: incBoth, families_with_incremental_value_one_split: incOne, information_incremental_value: incBoth.length ? 'YES' : incOne.length ? 'INCONCLUSIVE' : 'NO', directional_accuracy_improved: dirImproved, entry_economics_improved: b ? (b.ci95_r?.[0] > ctl.expectancy_r && b.expectancy_r > 0 ? 'YES' : b.expectancy_r > ctl.expectancy_r ? 'INCONCLUSIVE' : 'NO') : 'NO', edge_demonstrated: passing.length ? 'YES' : anyInconclusive ? 'INCONCLUSIVE' : 'NO', demo_eligible: passing.length ? 'YES (subject to parity fixtures)' : 'NO', simple_vs_composite: { simple: { def: defn.simple, hold: pickC(H['C7 V6-SIMPLE']), dev: pickC(D['C7 V6-SIMPLE']) }, composite: { def: Object.entries(defn.state_sets).filter(([, v]) => v.supported).map(([k, v]) => `${k}:${v.states.join('/')}`), hold: pickC(H['C8 V6-COMPOSITE']), dev: pickC(D['C8 V6-COMPOSITE']) } }, control: pickC(ctl), best: b ? { ...pickC(b), name: best, status: bd.status, reasons: bd.reasons } : null };
  writeFileSync(join(OUT, 'v6_results.json'), JSON.stringify(result, null, 1)); console.log('DECISIONS', JSON.stringify({ ...result.decisions, candidates: undefined }, null, 1)); for (const [k, d] of Object.entries(dec)) console.log(k, d.status, 'n', d.hold_n, 'exp', d.hold_expectancy_r, 'pf', d.hold_pf, 'dd', d.hold_dd_r, 'wd', d.wrong_direction_rate, 'evwd', d.event_wd, 'bad', d.bad_entry_rate, 'cap', d.capture, 'wait', d.wait_share, 'dev', d.dev_expectancy_r, 'ci', JSON.stringify(d.ci95_r), d.reasons.join('; ')); }
function pickC(v) { return v ? { n: v.n, expectancy_r: v.expectancy_r, pf: v.pf, max_dd_r: v.max_dd_r, ci95_r: v.ci95_r, block_ci95_r: v.block_ci95_r, wrong_direction_rate: v.wrong_direction_rate, bad_entry_rate: v.bad_entry_rate, capture: v.move_capture?.capture_rate, event_wd: v.move_capture?.wrong_direction_rate, wait_share: v.wait_share, win_rate: v.win_rate, stress_r: v.stress?.expectancy_r } : null; }
console.log('written', PHASE);
