/**
 * V4 MULTI-YEAR MARKET-STATE EDGE DISCOVERY (daily / weekly direction, volatility). Research only.
 * Definitions, regions and gates are fixed in docs/XAUUSD_V4_RESEARCH_PROTOCOL.md (written before this ran).
 * Run from repo root: node validation/v4_market_state_edge/v4_states.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const HERE = dirname(fileURLToPath(import.meta.url));
const D = JSON.parse(readFileSync(join(HERE, 'xauusdm_daily_bars.json'), 'utf8'));
const r2 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 100) / 100);
const r3 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 1000) / 1000);
const dayOf = (t) => new Date(t * 1000).toISOString().slice(0, 10);
const yearOf = (t) => new Date(t * 1000).getUTCFullYear();
const REG = [['DISCOVERY', '2014-01-14', '2020-12-31'], ['VALIDATION', '2021-01-01', '2023-12-31'], ['HOLDOUT', '2024-01-01', '2026-09-25']];
const regionOf = (t) => { const d = dayOf(t); for (const [n, a, b] of REG) if (d >= a && d <= b) return n; return null; };
const periodOf = (t) => { const y = yearOf(t); return y < 2020 ? 'PRE_2020' : y <= 2022 ? '2020_2022' : '2023_PLUS'; };
const HD = [1, 2, 3, 5, 10, 20], HW = [1, 2, 4];
let seed = 20260926; const rnd = () => { seed = (seed * 1664525 + 1013904223) % 4294967296; return seed / 4294967296; };
const N = D.length; const C = D.map((b) => b.close);
// daily ATR14 (Wilder-style simple mean of true range over 14)
const TR = D.map((b, i) => (i === 0 ? b.high - b.low : Math.max(b.high - b.low, Math.abs(b.high - C[i - 1]), Math.abs(b.low - C[i - 1]))));
const ATR = TR.map((_, i) => (i < 14 ? null : TR.slice(i - 13, i + 1).reduce((a, b) => a + b, 0) / 14));
const SMA50 = C.map((_, i) => (i < 49 ? null : C.slice(i - 49, i + 1).reduce((a, b) => a + b, 0) / 50));
// weeks: group by the Monday-based week key; Sunday bar (UTC day 0) belongs to the following week
const weekKey = (t) => { const d = new Date(t * 1000); const wd = d.getUTCDay(); const monday = new Date(d); monday.setUTCDate(d.getUTCDate() - ((wd + 6) % 7)); if (wd === 0) monday.setUTCDate(monday.getUTCDate() + 7); return monday.toISOString().slice(0, 10); };
const weeks = []; { let cur = null; for (let i = 0; i < N; i++) { const k = weekKey(D[i].time); if (!cur || cur.key !== k) { cur = { key: k, first: i, last: i, open: D[i].open, high: D[i].high, low: D[i].low, close: D[i].close }; weeks.push(cur); } else { cur.last = i; cur.high = Math.max(cur.high, D[i].high); cur.low = Math.min(cur.low, D[i].low); cur.close = D[i].close; } } }
const WC = weeks.map((w) => w.close); const WTR = weeks.map((w, i) => (i === 0 ? w.high - w.low : Math.max(w.high - w.low, Math.abs(w.high - WC[i - 1]), Math.abs(w.low - WC[i - 1])))); const WATR = WTR.map((_, i) => (i < 8 ? null : WTR.slice(i - 7, i + 1).reduce((a, b) => a + b, 0) / 8)); const WSMA20 = WC.map((_, i) => (i < 19 ? null : WC.slice(i - 19, i + 1).reduce((a, b) => a + b, 0) / 20));
const weekIndexOfBar = new Array(N); weeks.forEach((w, wi) => { for (let i = w.first; i <= w.last; i++) weekIndexOfBar[i] = wi; });
const lastCompletedWeek = (i) => { const wi = weekIndexOfBar[i]; return weeks[wi].last === i ? wi : wi - 1; }; // week complete when its last bar is i
// volatility state: trailing 500-day percentile of ATR14 (past only)
const volState = new Array(N).fill(null), volTrans = new Array(N).fill(null);
for (let i = 520; i < N; i++) { const hist = ATR.slice(i - 500, i).filter((x) => x != null).sort((a, b) => a - b); const p33 = hist[Math.floor(hist.length * 0.33)], p67 = hist[Math.floor(hist.length * 0.67)]; volState[i] = ATR[i] <= p33 ? 'LOW' : ATR[i] >= p67 ? 'HIGH' : 'NORMAL'; const ratio = ATR[i] / ATR[i - 5]; volTrans[i] = ratio > 1.15 ? 'RISING' : ratio < 0.87 ? 'FALLING' : 'STABLE'; }
// daily states
const d1 = (i) => { const d = C[i] - C[i - 1]; return d > 0.1 * ATR[i] ? 'UP' : d < -0.1 * ATR[i] ? 'DOWN' : 'NEUTRAL'; };
const d2 = (i) => { const d = C[i] - C[i - 3]; return d > 0.3 * ATR[i] ? 'UP' : d < -0.3 * ATR[i] ? 'DOWN' : 'FLAT'; };
const d3 = (i) => (SMA50[i] == null || SMA50[i - 10] == null ? 'NO_TREND' : C[i] > SMA50[i] && SMA50[i] > SMA50[i - 10] ? 'UPTREND' : C[i] < SMA50[i] && SMA50[i] < SMA50[i - 10] ? 'DOWNTREND' : 'NO_TREND');
const w1 = (wi) => { if (wi < 8 || WATR[wi] == null) return null; const d = WC[wi] - WC[wi - 1]; return d > 0.25 * WATR[wi] ? 'UP' : d < -0.25 * WATR[wi] ? 'DOWN' : 'NEUTRAL'; };
const w2 = (wi) => { const a = w1(wi), b = w1(wi - 1); if (!a || !b) return null; return a === 'UP' && b === 'UP' ? 'ALIGNED_BULL' : a === 'DOWN' && b === 'DOWN' ? 'ALIGNED_BEAR' : 'MIXED'; };
const w3 = (wi) => (WSMA20[wi] == null || WSMA20[wi - 4] == null ? null : WC[wi] > WSMA20[wi] && WSMA20[wi] > WSMA20[wi - 4] ? 'UPTREND' : WC[wi] < WSMA20[wi] && WSMA20[wi] < WSMA20[wi - 4] ? 'DOWNTREND' : 'NO_TREND');
const align = (i) => { const wi = lastCompletedWeek(i); const dd = d3(i), ww = w3(wi); if (!ww) return null; if (dd === 'UPTREND' && ww === 'UPTREND') return 'ALIGNED_BULL'; if (dd === 'DOWNTREND' && ww === 'DOWNTREND') return 'ALIGNED_BEAR'; if (dd === 'UPTREND' && ww === 'DOWNTREND') return 'CONFLICT_D_UP_W_DOWN'; if (dd === 'DOWNTREND' && ww === 'UPTREND') return 'CONFLICT_D_DOWN_W_UP'; return 'NEUTRAL_OR_MIXED'; };
// forward measures from daily close i, horizons in bars (bars ~ trading days including Sunday bars)
function fwd(i, H) { const out = {}; const a = ATR[i], c0 = C[i]; let mfeL = 0, maeL = 0, tMfeL = 0, tMaeL = 0, f05L = null, f1L = null, f05S = null, f1S = null, rr = 0; for (let h = 1; h <= Math.max(...H); h++) { const b = D[i + h]; if (!b) return null; rr += TR[i + h]; const up = (b.high - c0) / a, dn = (c0 - b.low) / a; if (up > mfeL) { mfeL = up; tMfeL = h; } if (dn > maeL) { maeL = dn; tMaeL = h; } if (f05L === null) { if (up >= 0.5 && dn >= 0.5) f05L = 'A'; else if (up >= 0.5) f05L = 'F'; else if (dn >= 0.5) f05L = 'A'; } if (f1L === null) { if (up >= 1 && dn >= 1) f1L = 'A'; else if (up >= 1) f1L = 'F'; else if (dn >= 1) f1L = 'A'; } if (f05S === null) { if (dn >= 0.5 && up >= 0.5) f05S = 'A'; else if (dn >= 0.5) f05S = 'F'; else if (up >= 0.5) f05S = 'A'; } if (f1S === null) { if (dn >= 1 && up >= 1) f1S = 'A'; else if (dn >= 1) f1S = 'F'; else if (up >= 1) f1S = 'A'; } if (H.includes(h)) out[h] = { ret: (b.close - c0) / c0 * 100, atr: (b.close - c0) / a, absAtr: Math.abs(b.close - c0) / a, range: rr / a, atrRatio: ATR[i + h] != null ? ATR[i + h] / a : null, mfeL, maeL, tMfeL, tMaeL, mfeS: maeL, maeS: mfeL }; } out.f05L = f05L; out.f1L = f1L; out.f05S = f05S; out.f1S = f1S; return out; }
// daily observations
const obs = []; for (let i = 520; i < N - 21; i++) { const f = fwd(i, HD); if (!f || ATR[i] == null) continue; obs.push({ i, t: D[i].time, region: regionOf(D[i].time), year: yearOf(D[i].time), period: periodOf(D[i].time), d1: d1(i), d2: d2(i), d3: d3(i), align: align(i), vol: volState[i], trans: volTrans[i], f }); }
// weekly observations (at the last bar of each completed week, forward in weeks = 5 bars per week approx: use next week closes)
const wobs = []; for (let wi = 30; wi < weeks.length - 5; wi++) { const i = weeks[wi].last; if (regionOf(D[i].time) == null || ATR[i] == null) continue; const out = {}; const c0 = C[i], a = WATR[wi]; let mfeL = 0, maeL = 0; for (let k = 1; k <= 4; k++) { const w = weeks[wi + k]; if (!w) { break; } mfeL = Math.max(mfeL, (w.high - c0) / a); maeL = Math.max(maeL, (c0 - w.low) / a); if (HW.includes(k)) out[k] = { ret: (w.close - c0) / c0 * 100, atr: (w.close - c0) / a, mfeL, maeL, mfeS: maeL, maeS: mfeL }; } if (!out[4]) continue; wobs.push({ i, wi, t: D[i].time, region: regionOf(D[i].time), year: yearOf(D[i].time), period: periodOf(D[i].time), w1: w1(wi), w2: w2(wi), w3: w3(wi), f: out }); }
// statistics
function blockBoot(vals, h, B = 1000) { const n = vals.length; if (n < 20) return null; const L = Math.max(3, 2 * h); const ms = []; for (let b = 0; b < B; b++) { let s = 0, c = 0; while (c < n) { const start = Math.floor(rnd() * n); for (let k = 0; k < L && c < n; k++) { s += vals[(start + k) % n]; c++; } } ms.push(s / n); } ms.sort((a, b) => a - b); return { lo: ms[Math.floor(B * 0.025)], hi: ms[Math.floor(B * 0.975)], ms }; }
function summarizeDaily(list, dir, base, H = HD) { const n = list.length; if (!n) return { n: 0 }; const o = { n }; for (const h of H) { const atrs = list.map((e) => e.f[h].atr * (dir || 1)); const rets = list.map((e) => e.f[h].ret * (dir || 1)); const mean = atrs.reduce((a, b) => a + b, 0) / n; const sorted = [...atrs].sort((a, b) => a - b); const bb = blockBoot(atrs, h); const baseMean = base ? base[`h${h}`].raw_mean_atr * (dir || 1) : 0; const excess = mean - baseMean; const mfe = list.reduce((a, e) => a + (dir < 0 ? e.f[h].mfeS : e.f[h].mfeL), 0) / n, mae = list.reduce((a, e) => a + (dir < 0 ? e.f[h].maeS : e.f[h].maeL), 0) / n; const abs = [...atrs].map(Math.abs).sort((a, b) => a - b); const cut = abs[Math.floor(abs.length * 0.99)]; const trimmed = atrs.filter((x) => Math.abs(x) < cut); const lo = sorted[Math.floor(n * 0.01)], hi = sorted[Math.floor(n * 0.99)]; const wins = atrs.map((x) => Math.min(hi, Math.max(lo, x))); o[`h${h}`] = { raw_mean_atr: r3(mean), raw_mean_pct: r3(rets.reduce((a, b) => a + b, 0) / n), median_atr: r3(sorted[Math.floor(n / 2)]), excess_atr: r3(excess), excess_ci95_block: bb ? [r3(bb.lo - baseMean), r3(bb.hi - baseMean)] : null, p_excess_le_0: bb ? r2(bb.ms.filter((m) => m - baseMean <= 0).length / bb.ms.length * 100) : null, p_pos: r2(atrs.filter((x) => x > 0).length / n * 100), mfe: r2(mfe), mae: r2(mae), mfe_mae: r2(mae > 0 ? mfe / mae : null), t_mfe: r2(list.reduce((a, e) => a + (dir < 0 ? e.f[h].tMaeL : e.f[h].tMfeL), 0) / n), t_mae: r2(list.reduce((a, e) => a + (dir < 0 ? e.f[h].tMfeL : e.f[h].tMaeL), 0) / n), mean_no_top1pct: r3(trimmed.reduce((a, b) => a + b, 0) / Math.max(1, trimmed.length)), mean_winsor: r3(wins.reduce((a, b) => a + b, 0) / n), approx_independent: Math.round(n / h), abs_move_atr: r2(list.reduce((a, e) => a + e.f[h].absAtr, 0) / n), realized_range_atr: r2(list.reduce((a, e) => a + e.f[h].range, 0) / n), atr_ratio_fwd: r2(list.filter((e) => e.f[h].atrRatio != null).reduce((a, e) => a + e.f[h].atrRatio, 0) / Math.max(1, list.filter((e) => e.f[h].atrRatio != null).length)) }; } const key05 = dir < 0 ? 'f05S' : 'f05L', key1 = dir < 0 ? 'f1S' : 'f1L'; o.p_plus05_before_minus05 = r2(list.filter((e) => e.f[key05] === 'F').length / Math.max(1, list.filter((e) => e.f[key05]).length) * 100); o.p_plus1_before_minus1 = r2(list.filter((e) => e.f[key1] === 'F').length / Math.max(1, list.filter((e) => e.f[key1]).length) * 100); return o; }
function summarizeWeekly(list, dir, base) { const n = list.length; if (!n) return { n: 0 }; const o = { n }; for (const h of HW) { const atrs = list.map((e) => e.f[h].atr * (dir || 1)); const mean = atrs.reduce((a, b) => a + b, 0) / n; const sorted = [...atrs].sort((a, b) => a - b); const bb = blockBoot(atrs, h); const baseMean = base ? base[`w${h}`].raw_mean_atr * (dir || 1) : 0; const mfe = list.reduce((a, e) => a + (dir < 0 ? e.f[h].mfeS : e.f[h].mfeL), 0) / n, mae = list.reduce((a, e) => a + (dir < 0 ? e.f[h].maeS : e.f[h].maeL), 0) / n; o[`w${h}`] = { raw_mean_atr: r3(mean), raw_mean_pct: r3(list.reduce((a, e) => a + e.f[h].ret * (dir || 1), 0) / n), median_atr: r3(sorted[Math.floor(n / 2)]), excess_atr: r3(mean - baseMean), excess_ci95_block: bb ? [r3(bb.lo - baseMean), r3(bb.hi - baseMean)] : null, p_excess_le_0: bb ? r2(bb.ms.filter((m) => m - baseMean <= 0).length / bb.ms.length * 100) : null, p_pos: r2(atrs.filter((x) => x > 0).length / n * 100), mfe: r2(mfe), mae: r2(mae), mfe_mae: r2(mae > 0 ? mfe / mae : null) }; } return o; }
const dirOf = (name) => (/UP|BULL/.test(name) ? +1 : /DOWN|BEAR/.test(name) ? -1 : 0);
const R = { generated_at: new Date().toISOString(), bars: N, weeks: weeks.length, obs: obs.length, wobs: wobs.length, regions: REG, baseline: {}, weekly_baseline: {}, daily: {}, weekly: {}, alignment: {}, volatility: {}, transition: {}, matrix: {}, years: {} };
for (const [reg] of REG) { R.baseline[reg] = summarizeDaily(obs.filter((e) => e.region === reg), +1, null); R.weekly_baseline[reg] = summarizeWeekly(wobs.filter((e) => e.region === reg), +1, null); }
R.baseline.ALL = summarizeDaily(obs, +1, null); for (const y of [...new Set(obs.map((e) => e.year))]) R.years[y] = summarizeDaily(obs.filter((e) => e.year === y), +1, null);
function stateBlock(list, key, values, kind = 'daily') { const out = {}; for (const v of values) { const dir = dirOf(v) || +1; out[v] = { direction_sign: dirOf(v) }; for (const [reg] of REG) { const L = list.filter((e) => e[key] === v && e.region === reg); out[v][reg] = kind === 'daily' ? summarizeDaily(L, dir, R.baseline[reg]) : summarizeWeekly(L, dir, R.weekly_baseline[reg]); } if (kind === 'daily') { const byY = {}; for (const y of [...new Set(list.map((e) => e.year))].sort()) { const L = list.filter((e) => e[key] === v && e.year === y); if (L.length < 20) continue; const s = summarizeDaily(L, dir, R.years[y]); byY[y] = { n: s.n, excess_h10: s.h10.excess_atr, excess_h5: s.h5.excess_atr, excess_h20: s.h20.excess_atr }; } out[v].by_year = byY; const byP = {}; for (const p of ['PRE_2020', '2020_2022', '2023_PLUS']) { const L = list.filter((e) => e[key] === v && e.period === p); const baseP = summarizeDaily(list.filter((e) => e.period === p), +1, null); const s = summarizeDaily(L, dir, baseP); byP[p] = { n: s.n, excess_h10: s.h10?.excess_atr ?? null, mfe_mae_h10: s.h10?.mfe_mae ?? null }; } out[v].by_period = byP; const byV = {}; for (const vs of ['LOW', 'NORMAL', 'HIGH']) { const L = list.filter((e) => e[key] === v && e.vol === vs); const baseV = summarizeDaily(list.filter((e) => e.vol === vs), +1, null); const s = summarizeDaily(L, dir, baseV); byV[vs] = { n: s.n, excess_h10: s.h10?.excess_atr ?? null, mfe_mae_h10: s.h10?.mfe_mae ?? null }; } out[v].by_vol = byV; } } return out; }
R.daily.D1 = stateBlock(obs, 'd1', ['UP', 'DOWN', 'NEUTRAL']); R.daily.D2 = stateBlock(obs, 'd2', ['UP', 'DOWN', 'FLAT']); R.daily.D3 = stateBlock(obs, 'd3', ['UPTREND', 'DOWNTREND', 'NO_TREND']);
R.weekly.W1 = stateBlock(wobs, 'w1', ['UP', 'DOWN', 'NEUTRAL'], 'weekly'); R.weekly.W2 = stateBlock(wobs, 'w2', ['ALIGNED_BULL', 'ALIGNED_BEAR', 'MIXED'], 'weekly'); R.weekly.W3 = stateBlock(wobs, 'w3', ['UPTREND', 'DOWNTREND', 'NO_TREND'], 'weekly');
R.alignment = stateBlock(obs, 'align', ['ALIGNED_BULL', 'ALIGNED_BEAR', 'CONFLICT_D_UP_W_DOWN', 'CONFLICT_D_DOWN_W_UP', 'NEUTRAL_OR_MIXED']);
// volatility: magnitude prediction (state vs region baseline) with block bootstrap on realized range ratio
function magBlock(list, key, values) { const out = {}; for (const v of values) { out[v] = {}; for (const [reg] of REG) { const L = list.filter((e) => e[key] === v && e.region === reg); const B = obs.filter((e) => e.region === reg); if (L.length < 20) { out[v][reg] = { n: L.length }; continue; } const row = { n: L.length }; for (const h of [5, 10, 20]) { const lr = L.map((e) => e.f[h].range), br = B.map((e) => e.f[h].range); const lm = lr.reduce((a, b) => a + b, 0) / lr.length, bm = br.reduce((a, b) => a + b, 0) / br.length; const bb = blockBoot(lr, h); const la = L.map((e) => e.f[h].absAtr).reduce((a, b) => a + b, 0) / L.length, ba = B.map((e) => e.f[h].absAtr).reduce((a, b) => a + b, 0) / B.length; const lar = L.filter((e) => e.f[h].atrRatio != null), bar = B.filter((e) => e.f[h].atrRatio != null); row[`h${h}`] = { realized_range_ratio_vs_base: r3(lm / bm), range_ratio_ci95: bb ? [r3(bb.lo / bm), r3(bb.hi / bm)] : null, abs_move_ratio_vs_base: r3(la / ba), fwd_atr_ratio_state: r3(lar.reduce((a, e) => a + e.f[h].atrRatio, 0) / lar.length), fwd_atr_ratio_base: r3(bar.reduce((a, e) => a + e.f[h].atrRatio, 0) / bar.length), directional_reliability_p05_long: summarizeDaily(L, +1, null).p_plus05_before_minus05, mfe_mae_long: summarizeDaily(L, +1, null)[`h${h}`].mfe_mae }; } out[v][reg] = row; } } return out; }
R.volatility = magBlock(obs, 'vol', ['LOW', 'NORMAL', 'HIGH']);
for (const e of obs) e.vt = e.vol && e.trans ? `${e.vol}->${e.trans}` : null;
R.transition = magBlock(obs, 'vt', ['LOW->RISING', 'NORMAL->RISING', 'HIGH->FALLING', 'LOW->STABLE', 'HIGH->STABLE', 'NORMAL->STABLE', 'HIGH->RISING', 'LOW->FALLING']);
// direction x volatility matrix
for (const e of obs) { const a = e.align; e.cell = a && e.vol ? `${a.startsWith('CONFLICT') ? 'CONFLICT' : a}|${e.vol}` : null; }
R.matrix = stateBlock(obs, 'cell', ['ALIGNED_BULL|LOW', 'ALIGNED_BULL|NORMAL', 'ALIGNED_BULL|HIGH', 'ALIGNED_BEAR|LOW', 'ALIGNED_BEAR|NORMAL', 'ALIGNED_BEAR|HIGH', 'CONFLICT|LOW', 'CONFLICT|NORMAL', 'CONFLICT|HIGH', 'NEUTRAL_OR_MIXED|LOW', 'NEUTRAL_OR_MIXED|NORMAL', 'NEUTRAL_OR_MIXED|HIGH']);
// gate evaluation (pre-declared) for daily directional states
function gateDaily(rec) { const g = { pass: false }; const dr = rec.DISCOVERY; if (!dr || dr.n < 150) return { ...g, reason: 'N' }; const hs = [5, 10, 20].filter((h) => dr[`h${h}`].excess_atr > 0); const ciOk = [5, 10, 20].some((h) => dr[`h${h}`].excess_ci95_block && dr[`h${h}`].excess_ci95_block[0] > 0); const ratioOk = dr.h10.mfe_mae >= 1.10; const val = [5, 10, 20].filter((h) => (rec.VALIDATION[`h${h}`]?.excess_atr ?? -1) > 0); const hold = [5, 10, 20].filter((h) => (rec.HOLDOUT[`h${h}`]?.excess_atr ?? -1) > 0); const common = hs.filter((h) => val.includes(h) && hold.includes(h)); const years = Object.values(rec.by_year || {}); const posYears = years.filter((y) => y.excess_h10 > 0).length; const totalEx = years.reduce((a, y) => a + y.excess_h10 * y.n, 0); const maxShare = years.length ? Math.max(...years.map((y) => (totalEx > 0 ? (y.excess_h10 * y.n) / totalEx : 0))) : 1; const outlierOk = dr.h10.mean_no_top1pct - (dr.h10.raw_mean_atr - dr.h10.excess_atr) > 0 && dr.h10.mean_winsor - (dr.h10.raw_mean_atr - dr.h10.excess_atr) > 0; return { pass: hs.length >= 2 && ciOk && ratioOk && common.length >= 2 && years.length > 0 && posYears / years.length >= 0.6 && maxShare <= 0.4 && outlierOk, discovery_positive_horizons: hs, ci_ok: ciOk, ratio_ok: ratioOk, validation_positive: val, holdout_positive: hold, common_positive: common, pos_year_share: r2(years.length ? posYears / years.length : 0), max_year_share_of_excess: r2(maxShare), outlier_ok: outlierOk }; }
R.gates = {}; for (const [fam, block] of Object.entries({ D1: R.daily.D1, D2: R.daily.D2, D3: R.daily.D3, ALIGN: R.alignment, MATRIX: R.matrix })) { R.gates[fam] = {}; for (const [v, rec] of Object.entries(block)) { if (!rec.direction_sign) continue; R.gates[fam][v] = gateDaily(rec); } }
function gateWeekly(rec) { const dr = rec.DISCOVERY; if (!dr || dr.n < 40) return { pass: false, reason: 'N' }; const hs = HW.filter((h) => dr[`w${h}`].excess_atr > 0); const ciOk = HW.some((h) => dr[`w${h}`].excess_ci95_block && dr[`w${h}`].excess_ci95_block[0] > 0); const ratioOk = dr.w2.mfe_mae >= 1.10; const val = HW.filter((h) => (rec.VALIDATION[`w${h}`]?.excess_atr ?? -1) > 0); const hold = HW.filter((h) => (rec.HOLDOUT[`w${h}`]?.excess_atr ?? -1) > 0); const common = hs.filter((h) => val.includes(h) && hold.includes(h)); return { pass: hs.length >= 2 && ciOk && ratioOk && common.length >= 2, discovery_positive_horizons: hs, ci_ok: ciOk, ratio_ok: ratioOk, validation_positive: val, holdout_positive: hold, common_positive: common }; }
for (const [fam, block] of Object.entries({ W1: R.weekly.W1, W2: R.weekly.W2, W3: R.weekly.W3 })) { R.gates[fam] = {}; for (const [v, rec] of Object.entries(block)) { if (!rec.direction_sign) continue; R.gates[fam][v] = gateWeekly(rec); } }
writeFileSync(join(HERE, 'v4_results.json'), JSON.stringify(R, null, 1));
console.log(JSON.stringify({ bars: N, weeks: weeks.length, obs: obs.length, wobs: wobs.length, gates: R.gates }, null, 1));
