/**
 * CAPITAL HARVEST V2 -- RR threshold & entry frequency study under H2a management. RESEARCH ONLY.
 * Imports V1's corrected harvest engine (read-only). Reads Edge Lab bars, the enriched candidate set and lab rows
 * read-only; writes only research/capital_harvest_v2/results/. No execution module is imported. No production state touched.
 * Spec: PREREGISTRATION.md (hash asserted).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { COSTS, EQUITY_REF_USD, HORIZON_BARS, capitalRisk, canReenter, simulateTrade } from '../../capital_harvest_v1/scripts/harvest_engine.mjs';
const HERE = dirname(fileURLToPath(import.meta.url)); const REPO = join(HERE, '..', '..', '..'); const ROOT = join(REPO, 'research', 'capital_harvest_v2'); const OUT = join(ROOT, 'results'); mkdirSync(OUT, { recursive: true });
const PREREG_SHA = readFileSync(join(ROOT, 'PREREGISTRATION.sha256'), 'utf8').trim().split(/\s+/)[0];
if (createHash('sha256').update(readFileSync(join(ROOT, 'PREREGISTRATION.md'))).digest('hex') !== PREREG_SHA) throw new Error('PREREGISTRATION.md does not match its frozen hash');
const MARGIN = 20.78;
const LAB = join(REPO, 'handoff', 'edge_discovery_lab', 'data');
const BARS = JSON.parse(readFileSync(join(LAB, 'XAUUSDm_bars.json'), 'utf8')); const b5 = BARS['5m'];
const r2 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 100) / 100); const r3 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 1000) / 1000);
const iso = (t) => new Date(t * 1000).toISOString(); const day = (t) => iso(t).slice(0, 10); const month = (t) => iso(t).slice(0, 7); const quarter = (t) => { const d = new Date(t * 1000); return `${d.getUTCFullYear()}Q${Math.floor(d.getUTCMonth() / 3) + 1}`; };
const SPLIT = { dev: ['2025-05-07', '2025-12-31'], hold: ['2026-01-01', '2026-09-29'] };
const split = (t) => { const d = day(t); if (d >= SPLIT.dev[0] && d <= SPLIT.dev[1]) return 'DEV'; if (d >= SPLIT.hold[0] && d <= SPLIT.hold[1]) return 'HOLD'; return 'EXCLUDED'; };
const mean = (a) => (a.length ? a.reduce((s, x) => s + x, 0) / a.length : null); const median = (a) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); const m = s.length >> 1; return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2; };
const pct = (a, p) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); return s[Math.min(s.length - 1, Math.floor(p * s.length))]; };
function rng(seed) { let s = seed >>> 0; return () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
function bootCI(v, n = 2000, seed = 20260930) { if (v.length < 2) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0; for (let j = 0; j < v.length; j++) s += v[Math.floor(rand() * v.length)]; ms.push(s / v.length); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor(0.025 * n)]), r3(ms[Math.floor(0.975 * n)])]; }
const H2A = Object.freeze({ kind: 'RUN', m1: { usd: 3 }, buffer: { usd: 1 }, bankRun: true });
const qRr = (rr, m) => (m > 0 ? Math.min(10, Math.max(0, (10 * (rr - m)) / m)) : 0);

// ---------- load candidates ----------
const C = readFileSync(join(REPO, 'research', 'entry_architecture_v2', 'results', 'candidates.jsonl'), 'utf8').trim().split('\n').map((l) => JSON.parse(l)).filter((c) => split(c.t) !== 'EXCLUDED');
let completed = 0, eligible = 0; const sessions = new Set(); const sessBy = { DEV: new Set(), HOLD: new Set() };
for (const line of readFileSync(join(LAB, 'lab_rows.jsonl'), 'utf8').split('\n')) { if (!line) continue; const t = Number(line.slice(line.indexOf('"t":') + 4, line.indexOf(',', line.indexOf('"t":')))); const sp = split(t); if (sp === 'EXCLUDED') continue; completed++; const wr = line.includes('"wr":"CHOP"'); const elig = !line.includes('"elig":""'); if (!wr && elig) eligible++; sessions.add(day(t)); sessBy[sp].add(day(t)); }
for (const c of C) { c.rr = c.geo?.rr ?? null; c.split = split(c.t); c.qNoRr = c.q_final - (c.q_break?.qRr ?? 0); c.tp2Dist = c.geo ? Math.abs(c.geo.tp2 - c.geo.entry) : null; c.tp1Dist = c.geo ? Math.abs(c.geo.tp1 - c.geo.entry) : null; c.nonRR = c.vol_ok && c.overext_ok && !!c.geo && !c.fresh_opp && !c.two_factor && !c.htf_conflict; c.risk = c.geo ? capitalRisk({ entry: c.geo.entry, sl: c.geo.sl }) : null; }
const qPass = (c, m) => (c.q_final + (qRr(c.rr, m) - qRr(c.rr, 1.7))) >= c.q_th; // delta form: exact production reproduction at 1.70 (breakdown components are rounded in production)
const THRESH = { 'R0_1.70': 1.7, 'R1_1.50': 1.5, 'R2_1.25': 1.25, 'R3_1.00': 1.0, 'R4_NO_FIXED_RR': null };
const admits = (c, m) => c.nonRR && c.rr != null && (m == null ? (c.rr > 0 && c.tp2Dist >= 3.34 && qPass(c, 0)) : (c.rr >= m && qPass(c, m)));
const popA = C.filter((c) => c.nonRR && c.rr != null);
const sig = (c) => ({ i: c.i, t: c.t, side: c.side, model: c.model, anchor: c.anchor, entry: c.geo.entry, sl: c.geo.sl, tp1Dist: c.tp1Dist, atr: c.atr, rr: c.rr, rg5: c.rg5, ses: c.ses, split: c.split, risk: c.risk });
const S = Object.fromEntries(Object.entries(THRESH).map(([k, m]) => [k, popA.filter((c) => admits(c, m)).map(sig).sort((a, b) => a.i - b.i)]));
// production signal reproduction check: S at 1.70 must equal production's BUY/SELL set
const prodSet = new Set(C.filter((c) => c.act === 'BUY' || c.act === 'SELL').map((c) => c.i)); const s0Set = new Set(S['R0_1.70'].map((s) => s.i));
const consistency = { production_signals: prodSet.size, R0_signals: s0Set.size, in_R0_not_prod: [...s0Set].filter((i) => !prodSet.has(i)).length, in_prod_not_R0: [...prodSet].filter((i) => !s0Set.has(i)).length };
console.log('populationA', popA.length, 'S sizes', Object.fromEntries(Object.entries(S).map(([k, v]) => [k, v.length])), 'consistency', JSON.stringify(consistency));
if (consistency.in_R0_not_prod || consistency.in_prod_not_R0) throw new Error('R0 does not reproduce production signals');
// opposite-signal bars for the governed early exit: per threshold, the OPPOSITE side's admitted signals
const oppBars = (set, side) => set.filter((s) => s.side !== side).map((s) => s.i);

// ---------- controls ----------
const indep = (arr) => { const out = []; let lastI = -1e9, lastSide = null; for (const s of [...arr].sort((a, b) => a.i - b.i)) { if (s.side !== lastSide || s.i - lastI > 12) out.push(s); lastI = s.i; lastSide = s.side; } return out; };
const ctrl = (() => { const rand = rng(99); const leak = [], nul = []; for (const s of indep(S['R0_1.70'])) { if (s.i + 13 >= b5.length) continue; const fut = b5[s.i + 12].close - b5[s.i].close; const sym = { kind: 'FIXED', m1: { usd: s.atr } }; const mk = (side) => ({ bars: b5, i: s.i, side, entry: b5[s.i].close, sl: side === 'BUY' ? b5[s.i].close - s.atr : b5[s.i].close + s.atr, atr: s.atr, tp1Dist: s.atr, variant: sym, oppSignalBars: [] }); const o1 = simulateTrade(mk(fut >= 0 ? 'BUY' : 'SELL')), o2 = simulateTrade(mk(rand() < 0.5 ? 'BUY' : 'SELL')); if (o1.status === 'RESOLVED' && !o1.gap) leak.push(o1.pnl_usd); if (o2.status === 'RESOLVED' && !o2.gap) nul.push(o2.pnl_usd); }
  const sample = S['R0_1.70'].slice(0, 400); const a = sample.map((s) => simulateTrade({ bars: b5, i: s.i, side: s.side, entry: s.entry, sl: s.sl, atr: s.atr, tp1Dist: s.tp1Dist, variant: H2A, oppSignalBars: [] }).pnl_usd); const b = sample.map((s) => simulateTrade({ bars: b5, i: s.i, side: s.side, entry: s.entry, sl: s.sl, atr: s.atr, tp1Dist: s.tp1Dist, variant: H2A, oppSignalBars: [], costs: { spread: COSTS.normal.spread, slip: 0 } }).pnl_usd); const diff = mean(b) - mean(a);
  return { leak_mean_usd: r3(mean(leak)), leak_n: leak.length, null_mean_usd: r3(mean(nul)), null_n: nul.length, cost_test: { no_slip_minus_normal: r3(diff), expected: 0.1, pass: Math.abs(diff - 0.1) < 0.001 } }; })();
console.log('controls', JSON.stringify(ctrl));
if (!(ctrl.leak_mean_usd > 1.0) || !(Math.abs(ctrl.null_mean_usd) < 0.5) || !ctrl.cost_test.pass) throw new Error('CONTROL FAILED');

// ---------- helpers ----------
function runSequential(set, { costs = COSTS.normal, drift = false, cap = null } = {}) { const trades = []; let exitBar = -1, lastTrade = null, lastLoss = false; const skipped = { SAME_OR_EARLIER_CANDLE: 0, STALE_SAME_SETUP: 0, REVENGE_GUARD: 0, CAPITAL_RISK_TOO_HIGH: 0 }; const opp = { BUY: oppBars(set, 'BUY'), SELL: oppBars(set, 'SELL') };
  for (const s of set) { if (cap != null && s.risk.pctEquity > cap) { skipped.CAPITAL_RISK_TOO_HIGH++; continue; } const ok = canReenter({ signal: s, exitBar, lastTrade, lastExitWasLoss: lastLoss }); if (!ok.ok) { skipped[ok.reason]++; continue; } const o = simulateTrade({ bars: b5, i: s.i, side: s.side, entry: s.entry, sl: s.sl, atr: s.atr, tp1Dist: s.tp1Dist, variant: H2A, oppSignalBars: opp[s.side], costs, drift }); if (o.status === 'NO_DATA' || o.status === 'INVALID') continue; trades.push({ s, o }); exitBar = o.exitBar; lastTrade = s; lastLoss = o.pnl_usd <= 0; }
  return { trades, skipped }; }
function path(trades, start) { let bal = start, peak = start, dd = 0, minB = start, floorHit = false, streak = 0, maxStreak = 0; const lossSeqs = []; let seq = 0; for (const t of trades) { bal += t.o.pnl_usd; if (bal > peak) peak = bal; dd = Math.max(dd, peak - bal); minB = Math.min(minB, bal); if (bal <= MARGIN) floorHit = true; if (t.o.pnl_usd <= 0) { streak++; seq += t.o.pnl_usd; maxStreak = Math.max(maxStreak, streak); } else { if (streak) lossSeqs.push(-seq); streak = 0; seq = 0; } } if (streak) lossSeqs.push(-seq); return { start, final: r2(bal), min_balance: r2(minB), max_dd: r2(dd), margin_floor_hit: floorHit, max_loss_streak: maxStreak, loss_sequences: lossSeqs }; }
function depletion(trades, start = 60, draws = 500, seed = 7) { if (!trades.length) return null; const rand = rng(seed); const byM = {}; for (const t of trades) (byM[month(t.s.t)] ??= []).push(t.o.pnl_usd); const months = Object.values(byM); let hit = 0; for (let k = 0; k < draws; k++) { const order = [...months].sort(() => rand() - 0.5); let bal = start, h = false; for (const m of order) for (const p of [...m].sort(() => rand() - 0.5)) { bal += p; if (bal <= MARGIN) h = true; } if (h) hit++; } return r3(hit / draws); }
const groupExp = (trades, f) => { const g = {}; for (const t of trades) (g[String(f(t) ?? 'null')] ??= []).push(t.o.pnl_usd); return Object.fromEntries(Object.entries(g).sort().map(([k, v]) => [k, { n: v.length, exp_usd: r3(mean(v)), sum_usd: r2(v.reduce((a, b) => a + b, 0)) }])); };
function stats(trades, sessSet) { const P = trades.map((t) => t.o.pnl_usd); if (!P.length) return { trades: 0 }; const wins = P.filter((x) => x > 0), losses = P.filter((x) => x <= 0); const gw = wins.reduce((s, x) => s + x, 0), gl = -losses.reduce((s, x) => s + x, 0); const perDay = {}; for (const t of trades) perDay[day(t.s.t)] = (perDay[day(t.s.t)] ?? 0) + 1; const counts = [...sessSet].map((d) => perDay[d] ?? 0); const activeDays = Object.keys(perDay).length; const months = {}; for (const t of trades) months[month(t.s.t)] = (months[month(t.s.t)] ?? 0) + t.o.pnl_usd; const mv = Object.values(months); const p = path(trades, EQUITY_REF_USD); const avgW = mean(wins), avgL = losses.length ? -mean(losses) : null; const lossP75 = losses.length ? -pct(losses.map((x) => x), 0.25) : null; const winStreaks = [], lossStreaks = []; let cur = 0, sum = 0, kind = null; for (const x of P) { const k = x > 0 ? 'W' : 'L'; if (k === kind) { cur++; sum += x; } else { if (kind === 'W') winStreaks.push(sum); if (kind === 'L') lossStreaks.push(-sum); kind = k; cur = 1; sum = x; } } if (kind === 'W') winStreaks.push(sum); if (kind === 'L') lossStreaks.push(-sum);
  return { trades: P.length, win_rate: r3(wins.length / P.length), avg_win_usd: r2(avgW), avg_loss_usd: r2(avgL), wins_erased_by_one_loss: avgW && avgL ? r2(avgL / avgW) : null, expectancy_usd: r3(mean(P)), expectancy_r: r3(mean(trades.map((t) => t.o.r))), pf: gl > 0 ? r2(gw / gl) : (gw > 0 ? 99 : null), ci95_usd: bootCI(P), gross_profit_usd: r2(gw), gross_loss_usd: r2(gl), net_usd: r2(gw - gl), costs_usd: r2(trades.reduce((s, t) => s + t.o.cost_usd, 0)), net_per_active_day_usd: r3((gw - gl) / activeDays), active_days: activeDays, trades_per_session: { p10: pct(counts, 0.1), p25: pct(counts, 0.25), median: pct(counts, 0.5), p75: pct(counts, 0.75), p90: pct(counts, 0.9), mean: r2(mean(counts)) }, session_rate: { zero: r3(counts.filter((x) => x === 0).length / counts.length), one_to_three: r3(counts.filter((x) => x >= 1 && x <= 3).length / counts.length), four_to_six: r3(counts.filter((x) => x >= 4 && x <= 6).length / counts.length), seven_to_ten: r3(counts.filter((x) => x >= 7 && x <= 10).length / counts.length), over_ten: r3(counts.filter((x) => x > 10).length / counts.length) }, avg_hold_bars: r2(mean(trades.map((t) => t.o.bars))), median_mfe_usd: r2(median(trades.map((t) => t.o.mfe_usd))), median_mae_usd: r2(median(trades.map((t) => t.o.mae_usd))), milestone_hit_rate: r3(trades.filter((t) => t.o.reached_bar != null).length / P.length), protected_run_rate: r3(trades.filter((t) => t.o.decision === 'RUN').length / P.length), given_back_after_m1: r2(mean(trades.filter((t) => t.o.reached_bar != null).map((t) => t.o.given_back))), exit_mix: Object.fromEntries(Object.entries(trades.reduce((g, t) => { g[t.o.exit] = (g[t.o.exit] ?? 0) + 1; return g; }, {}))), months: mv.length, months_positive_share: mv.length ? r3(mv.filter((x) => x > 0).length / mv.length) : null, top5_share: gw > 0 ? r3([...P].sort((a, b) => b - a).slice(0, 5).filter((x) => x > 0).reduce((s, x) => s + x, 0) / gw) : null, path_62: p, loss_asymmetry: { median_win_streak_contribution: r2(median(winStreaks)), median_loss_streak_damage: r2(median(lossStreaks)), p95_loss_sequence: r2(pct(lossStreaks, 0.95)), largest_loss_sequence: r2(lossStreaks.length ? Math.max(...lossStreaks) : null), banks_to_recover_one_avg_loss: avgL ? r2(avgL / 2.9) : null, banks_to_recover_p75_loss: lossP75 ? r2(lossP75 / 2.9) : null, banks_to_recover_two_avg_losses: avgL ? r2(2 * avgL / 2.9) : null }, by_model: groupExp(trades, (t) => t.s.model), by_side: groupExp(trades, (t) => t.s.side), by_session: groupExp(trades, (t) => t.s.ses), by_regime: groupExp(trades, (t) => t.s.rg5), by_month: groupExp(trades, (t) => month(t.s.t)), by_quarter: groupExp(trades, (t) => quarter(t.s.t)), by_year: groupExp(trades, (t) => iso(t.s.t).slice(0, 4)), by_risk_band: groupExp(trades, (t) => t.s.risk.band) }; }

// ---------- milestone scan (per-signal, independent) ----------
const USD_M = [1, 2, 3, 5, 7.5, 10];
function milestoneScan(s, opp) { const sp = COSTS.normal.spread; const fill = s.side === 'BUY' ? s.entry + sp : s.entry; let mfe = 0; const first = {}; let stop = null, oppB = null; let oi = 0; while (oi < opp.length && opp[oi] <= s.i) oi++; const end = Math.min(b5.length - 1, s.i + HORIZON_BARS);
  for (let j = s.i + 1; j <= end; j++) { const b = b5[j]; if (s.side === 'BUY' ? b.low <= s.sl : (b.high + sp) >= s.sl) { stop = j - s.i; break; } const fav = s.side === 'BUY' ? b.high - fill : fill - (b.low + sp); if (fav > mfe) mfe = fav; for (const m of USD_M) if (first[m] == null && mfe >= m) first[m] = j - s.i; while (oi < opp.length && opp[oi] < j) oi++; if (oppB == null && oi < opp.length && opp[oi] === j) oppB = j - s.i; }
  return { first, stop, oppB, mfe }; }
function milestoneTable(set) { const ind = indep(set); const opp = { BUY: oppBars(set, 'BUY'), SELL: oppBars(set, 'SELL') }; const scans = ind.map((s) => milestoneScan(s, opp[s.side])); const out = { independent: ind.length }; for (const m of USD_M) { const hit = scans.filter((x) => x.first[m] != null); const beforeOpp = hit.filter((x, k) => scans[scans.indexOf(x)].oppB == null || x.first[m] <= scans[scans.indexOf(x)].oppB); out[`+${m}`] = { before_stop: r3(hit.length / ind.length), before_stop_and_opposite: r3(beforeOpp.length / ind.length), median_bars: median(hit.map((x) => x.first[m])) }; } out.stopped_before_1usd = r3(scans.filter((x) => x.stop != null && x.first[1] == null).length / ind.length); return out; }

// ---------- per-signal H2a outcomes for buckets (independent set) ----------
function perSignal(set, opp) { const ind = indep(set); const rows = ind.map((s) => ({ s, o: simulateTrade({ bars: b5, i: s.i, side: s.side, entry: s.entry, sl: s.sl, atr: s.atr, tp1Dist: s.tp1Dist, variant: H2A, oppSignalBars: opp[s.side] }) })).filter((x) => x.o.status !== 'NO_DATA' && x.o.status !== 'INVALID' && !x.o.gap); return rows; }
function indepStats(rows, extra = {}) { const P = rows.map((x) => x.o.pnl_usd); if (!P.length) return { n: 0 }; const w = P.filter((x) => x > 0), l = P.filter((x) => x <= 0); const gw = w.reduce((a, b) => a + b, 0), gl = -l.reduce((a, b) => a + b, 0); return { n: P.length, win_rate: r3(w.length / P.length), expectancy_usd: r3(mean(P)), ci95_usd: bootCI(P), pf: gl > 0 ? r2(gw / gl) : (gw > 0 ? 99 : null), avg_win_usd: r2(mean(w)), avg_loss_usd: l.length ? r2(-mean(l)) : null, median_mfe_usd: r2(median(rows.map((x) => x.o.mfe_usd))), median_mae_usd: r2(median(rows.map((x) => x.o.mae_usd))), milestone_hit_rate: r3(rows.filter((x) => x.o.reached_bar != null).length / P.length), sum_usd: r2(gw - gl), ...extra }; }

// ---------- run study (wrapped for repeatability check) ----------
function runStudy() {
  const out = { thresholds: {}, funnel: {}, buckets: {}, matrix: {}, capital_paths: {} };
  const base = runSequential(S['R0_1.70']); const baseH = stats(base.trades.filter((t) => t.s.split === 'HOLD'), sessBy.HOLD);
  for (const [k, m] of Object.entries(THRESH)) {
    const set = S[k]; const seq = runSequential(set); const H = seq.trades.filter((t) => t.s.split === 'HOLD'), D = seq.trades.filter((t) => t.s.split === 'DEV');
    const stress = runSequential(set, { costs: COSTS.stress }).trades.filter((t) => t.s.split === 'HOLD'); const drift = runSequential(set, { drift: true }).trades.filter((t) => t.s.split === 'HOLD');
    const sigDays = {}; for (const s of set) sigDays[day(s.t)] = (sigDays[day(s.t)] ?? 0) + 1;
    const incr = set.filter((s) => !s0Set.has(s.i)); const opp = { BUY: oppBars(set, 'BUY'), SELL: oppBars(set, 'SELL') }; const incrRows = perSignal(incr, opp);
    const incrH = incrRows.filter((x) => x.s.split === 'HOLD'), incrD = incrRows.filter((x) => x.s.split === 'DEV');
    const incrStress = perSignal(incr, opp).length ? indep(incr).map((s) => ({ s, o: simulateTrade({ bars: b5, i: s.i, side: s.side, entry: s.entry, sl: s.sl, atr: s.atr, tp1Dist: s.tp1Dist, variant: H2A, oppSignalBars: opp[s.side], costs: COSTS.stress }) })).filter((x) => x.o.status === 'RESOLVED' || x.o.status === 'OPEN_AT_HORIZON').filter((x) => !x.o.gap && x.s.split === 'HOLD') : [];
    out.thresholds[k] = { min_rr: m, signals: set.length, signals_dev: set.filter((s) => s.split === 'DEV').length, signals_hold: set.filter((s) => s.split === 'HOLD').length, independent_signals: indep(set).length, signals_per_session_mean: r2(set.length / sessions.size), sessions_with_zero_signals: r3([...sessions].filter((d) => !sigDays[d]).length / sessions.size), skipped: seq.skipped, ALL: stats(seq.trades, sessions), DEV: stats(D, sessBy.DEV), HOLD: stats(H, sessBy.HOLD), HOLD_stress: (() => { const x = stats(stress, sessBy.HOLD); return { expectancy_usd: x.expectancy_usd, pf: x.pf, net_usd: x.net_usd, trades: x.trades }; })(), HOLD_drift: (() => { const x = stats(drift, sessBy.HOLD); return { expectancy_usd: x.expectancy_usd, pf: x.pf, net_usd: x.net_usd }; })(), milestones: milestoneTable(set), incremental_vs_R0: { raw_signals: incr.length, independent: indep(incr).length, HOLD: indepStats(incrH, { by_model: groupExp(incrH, (x) => x.s.model), by_side: groupExp(incrH, (x) => x.s.side), by_month: groupExp(incrH, (x) => month(x.s.t)), by_session: groupExp(incrH, (x) => x.s.ses) }), DEV: indepStats(incrD), HOLD_stress: indepStats(incrStress) }, frequency_vs_R0: { hold_trades: H.length, r0_hold_trades: baseH.trades, change_pct: baseH.trades ? r3((H.length - baseH.trades) / baseH.trades) : null, hold_net_usd: stats(H, sessBy.HOLD).net_usd, r0_hold_net_usd: baseH.net_usd, hold_dd: path(H, EQUITY_REF_USD).max_dd, r0_hold_dd: baseH.path_62.max_dd },
      capital: { band_share: Object.fromEntries(['<=1%', '1-2%', '2-3%', '3-5%', '5-8%', '>8%'].map((b) => [b, r3(set.filter((s) => s.risk.band === b).length / set.length)])), median_expected_loss: r2(median(set.map((s) => s.risk.expectedLossUsd))), p75_expected_loss: r2(pct(set.map((s) => s.risk.expectedLossUsd), 0.75)), worst_expected_loss: r2(Math.max(...set.map((s) => s.risk.expectedLossUsd))), margin_burden_pct_62: r3(MARGIN / EQUITY_REF_USD), k_loss_effect_pct_of_62: (() => { const al = stats(H, sessBy.HOLD).avg_loss_usd ?? 0; return { two: r3(2 * al / EQUITY_REF_USD), three: r3(3 * al / EQUITY_REF_USD), five: r3(5 * al / EQUITY_REF_USD) }; })(), capital_for_median_risk: (() => { const med = median(set.map((s) => s.risk.expectedLossUsd)); return { le3pct: r2(med / 0.03), le2pct: r2(med / 0.02), le1pct: r2(med / 0.01) }; })(), paths: Object.fromEntries([60, 100, 250, 500, 1000].map((st) => [st, (() => { const p = path(seq.trades, st); return { min_balance: p.min_balance, max_dd: p.max_dd, margin_floor_hit: p.margin_floor_hit, final: p.final }; })()])), month_shuffled_floor_share_from_60: depletion(seq.trades, 60) } };
    for (const cap of [0.08, 0.05, 0.03]) { const cs = runSequential(set, { cap }); const ch = cs.trades.filter((t) => t.s.split === 'HOLD'); const st = stats(ch, sessBy.HOLD); out.matrix[`${k} x cap<=${Math.round(cap * 100)}%`] = { admitted_signals: set.filter((s) => s.risk.pctEquity <= cap).length, sequential_trades_hold: ch.length, expectancy_usd: st.expectancy_usd ?? null, pf: st.pf ?? null, ci95: st.ci95_usd ?? null, max_dd_62: st.path_62?.max_dd ?? null, empty: ch.length < 30 }; }
    out.matrix[`${k} x no cap`] = { admitted_signals: set.length, sequential_trades_hold: H.length, expectancy_usd: stats(H, sessBy.HOLD).expectancy_usd, pf: stats(H, sessBy.HOLD).pf, ci95: stats(H, sessBy.HOLD).ci95_usd, max_dd_62: path(H, EQUITY_REF_USD).max_dd, empty: false };
    // funnel (population B)
    const afterOver = C.filter((c) => c.vol_ok && c.overext_ok && c.geo); const rrPass = afterOver.filter((c) => (m == null ? (c.rr > 0 && c.tp2Dist >= 3.34) : c.rr >= m)); const qP = rrPass.filter((c) => qPass(c, m == null ? 0 : m)); const f1 = qP.filter((c) => !c.fresh_opp); const f2 = f1.filter((c) => !c.two_factor); const f3 = f2.filter((c) => !c.htf_conflict);
    out.funnel[k] = { completed_candles: completed, model_eligible: eligible, candidates: C.length, after_atr_floor: C.filter((c) => c.vol_ok).length, after_overextension: C.filter((c) => c.vol_ok && c.overext_ok).length, after_geometry: afterOver.length, after_rr: rrPass.length, after_quality: qP.length, after_fresh_choch: f1.length, after_two_factor: f2.length, after_htf: f3.length, signals: f3.length, safety_gates: 'News V2 / shock / spread / drift / breaker / identity not in replay (identical across thresholds)', sessions_with_zero_signals: out.thresholds[k].sessions_with_zero_signals, sequential_trades_per_session_hold: out.thresholds[k].HOLD.session_rate };
  }
  // incremental buckets
  const BUCKETS = [['<1.00', 0, 1.0], ['1.00-1.25', 1.0, 1.25], ['1.25-1.50', 1.25, 1.5], ['1.50-1.70', 1.5, 1.7], ['>=1.70', 1.7, Infinity]];
  for (const [name, lo, hi] of BUCKETS) { const set = popA.filter((c) => c.rr >= lo && c.rr < hi && qPass(c, lo)).map(sig).sort((a, b) => a.i - b.i); const opp = { BUY: oppBars(set, 'BUY'), SELL: oppBars(set, 'SELL') }; const rows = perSignal(set, opp); const rowsH = rows.filter((x) => x.s.split === 'HOLD'), rowsD = rows.filter((x) => x.s.split === 'DEV'); const stressRows = indep(set).map((s) => ({ s, o: simulateTrade({ bars: b5, i: s.i, side: s.side, entry: s.entry, sl: s.sl, atr: s.atr, tp1Dist: s.tp1Dist, variant: H2A, oppSignalBars: opp[s.side], costs: COSTS.stress }) })).filter((x) => (x.o.status === 'RESOLVED' || x.o.status === 'OPEN_AT_HORIZON') && !x.o.gap); const driftRows = indep(set).map((s) => ({ s, o: simulateTrade({ bars: b5, i: s.i, side: s.side, entry: s.entry, sl: s.sl, atr: s.atr, tp1Dist: s.tp1Dist, variant: H2A, oppSignalBars: opp[s.side], drift: true }) })).filter((x) => (x.o.status === 'RESOLVED' || x.o.status === 'OPEN_AT_HORIZON') && !x.o.gap); const seq = runSequential(set).trades;
    out.buckets[name] = { raw_n: set.length, independent_n: indep(set).length, all: indepStats(rows), HOLD: indepStats(rowsH), DEV: indepStats(rowsD), stress_all: indepStats(stressRows), drift_all: indepStats(driftRows), milestones: milestoneTable(set), sequential_max_dd_62: path(seq, EQUITY_REF_USD).max_dd, sequential_trades: seq.length, model_composition: Object.fromEntries(['MC', 'PB', 'BO', 'SR', 'MR'].map((mm) => [mm, set.filter((s) => s.model === mm).length])), side_split: { BUY: set.filter((s) => s.side === 'BUY').length, SELL: set.filter((s) => s.side === 'SELL').length }, session_distribution: Object.fromEntries(['ASIA', 'LONDON', 'NEW_YORK', 'OTHER'].map((ss) => [ss, set.filter((s) => s.ses === ss).length])), by_model_exp: groupExp(rows, (x) => x.s.model), by_side_exp: groupExp(rows, (x) => x.s.side), by_year_exp: groupExp(rows, (x) => iso(x.s.t).slice(0, 4)), by_session_exp: groupExp(rows, (x) => x.s.ses), median_expected_loss: r2(median(set.map((s) => s.risk.expectedLossUsd))) }; }
  return out;
}
const run1 = runStudy(); const run2 = runStudy();
const h1 = createHash('sha256').update(JSON.stringify(run1)).digest('hex'), h2 = createHash('sha256').update(JSON.stringify(run2)).digest('hex');
if (h1 !== h2) throw new Error('REPEATABILITY CONTROL FAILED');
// decisions
const r0 = run1.thresholds['R0_1.70'];
for (const k of ['R1_1.50', 'R2_1.25', 'R3_1.00', 'R4_NO_FIXED_RR']) { const t = run1.thresholds[k]; const inc = t.incremental_vs_R0; const h = inc.HOLD; const reasons = []; let status;
  if (!h.n) status = 'REJECTED';
  else if (h.expectancy_usd <= 0 || (h.pf ?? 0) <= 1.0) status = 'REJECTED';
  else { const ciOk = h.ci95_usd && h.ci95_usd[0] > 0; if (!ciOk) reasons.push('CI includes 0'); if (h.pf <= 1.10) reasons.push('PF<=1.10'); const posModels = Object.values(h.by_model).filter((v) => v.sum_usd > 0); const totPos = posModels.reduce((a, v) => a + v.sum_usd, 0); if (posModels.length && Math.max(...posModels.map((v) => v.sum_usd)) / totPos > 0.6) reasons.push('one model > 60% of positive contribution'); const posMonths = Object.values(h.by_month).filter((v) => v.sum_usd > 0); const totM = posMonths.reduce((a, v) => a + v.sum_usd, 0); if (posMonths.length && Math.max(...posMonths.map((v) => v.sum_usd)) / totM > 0.6) reasons.push('one month > 60% of positive contribution'); const sides = Object.values(h.by_side); if (sides.some((v) => v.exp_usd < 0)) reasons.push('one side negative'); if ((inc.HOLD_stress.expectancy_usd ?? -9) < -0.10) reasons.push('stress catastrophic'); const f = t.frequency_vs_R0; const netGain = r0.HOLD.net_usd ? (f.hold_net_usd - f.r0_hold_net_usd) / Math.abs(f.r0_hold_net_usd) : 0; const ddWorse = f.r0_hold_dd ? (f.hold_dd - f.r0_hold_dd) / f.r0_hold_dd : 0; if (ddWorse > Math.max(0, netGain)) reasons.push('drawdown worsens more than net improves'); if ((f.change_pct ?? 0) < 0.10) reasons.push('frequency increase < 10%'); if (inc.DEV.n && Math.sign(inc.DEV.expectancy_usd) !== Math.sign(h.expectancy_usd) && h.ci95_usd && (inc.DEV.expectancy_usd < h.ci95_usd[0] || inc.DEV.expectancy_usd > h.ci95_usd[1])) reasons.push('DEV/HOLD contradictory'); status = reasons.length ? 'INCONCLUSIVE' : 'RESEARCH_CANDIDATE'; }
  t.decision = { status, reasons, capital_flag: `median expected loss ${t.capital.median_expected_loss} USD = ${r3(t.capital.median_expected_loss / EQUITY_REF_USD)} of 62.07 USD; ${t.capital.band_share['>8%']} of admitted signals above 8%` }; }
const meta = { generated_utc: new Date().toISOString(), prereg_sha256: PREREG_SHA, results_hash: h1, repeatability_pass: h1 === h2, population_A: popA.length, candidates: C.length, sessions: sessions.size, sessions_dev: sessBy.DEV.size, sessions_hold: sessBy.HOLD.size, consistency, controls: ctrl, bonferroni_alpha: 0.0125, thresholds: THRESH, margin_0_01_usd: MARGIN, equity_ref: EQUITY_REF_USD };
writeFileSync(join(OUT, 'study_results.json'), JSON.stringify({ meta, ...run1 }, null, 1));
console.log(JSON.stringify({ decisions: Object.fromEntries(Object.entries(run1.thresholds).map(([k, v]) => [k, { signals: v.signals, hold_trades: v.HOLD.trades, hold_exp: v.HOLD.expectancy_usd, hold_pf: v.HOLD.pf, dd62: v.HOLD.path_62.max_dd, incr_n: v.incremental_vs_R0.HOLD.n, incr_exp: v.incremental_vs_R0.HOLD.expectancy_usd, incr_pf: v.incremental_vs_R0.HOLD.pf, status: v.decision?.status ?? 'CONTROL' }])) }, null, 1));
console.log('written', join(OUT, 'study_results.json'));
