// Generates the machine-derived markdown tables of the CAPITAL HARVEST MASTER handoff from results/study_results.json.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const HERE = dirname(fileURLToPath(import.meta.url)); const REPO = join(HERE, '..', '..', '..'); const R = JSON.parse(readFileSync(join(REPO, 'research', 'capital_harvest_master', 'results', 'study_results.json'), 'utf8'));
const OUT = join(REPO, 'handoff', 'CAPITAL_HARVEST_MASTER'); mkdirSync(OUT, { recursive: true });
const A = R.architectures; const EQ = R.meta.equities; const CANDS = ['CONTROL', 'CH_A', 'CH_B', 'CH_C', 'CH_D1', 'CH_D2', 'CH_D3']; const POL = ['null', '1', '2', '3', '5', '7.5', '10', 'PROD_VETO'];
const f = (x, d = 2) => (x == null ? '—' : typeof x === 'number' ? (Number.isInteger(x) ? String(x) : x.toFixed(d)) : String(x)); const ci = (c) => (c ? `[${f(c[0])}, ${f(c[1])}]` : '—'); const pc = (x) => (x == null ? '—' : `${(x * 100).toFixed(1)} %`);
const polName = (p) => (p === 'null' ? 'no cap' : p === 'PROD_VETO' ? 'production −50 veto' : `${p} %`);
const desc = { CONTROL: 'production stack (Edge Lab simulation)', CH_A: 'pct risk + production-like exits', CH_B: 'pct risk + bank at first close ≥ 1 R', CH_C: 'pct risk + protected run (1 R, 0.5 ATR)', CH_D1: 'adaptive (T 0.75 R, B 0.5 ATR)', CH_D2: 'adaptive (T 1.0 R, B 0.5 ATR)', CH_D3: 'adaptive (T 0.75 R, B 1.0 ATR)' };

// ---- DEVELOPMENT / HOLDOUT results (no cap = management effect isolated; and the 5 % policy at 500 USD as the smallest non-empty proportional case)
function block(title, key, eq, pol) {
  const rows = CANDS.map((c) => { const r = A[c].per_policy[pol][eq]; const s = r[key]; if (!s || !s.trades) return `| ${c} | 0 | | | | | | | | | | | | |`; return `| ${c} | ${s.trades} | ${s.independent_trades} | ${f(s.trades_per_session?.median, 0)} | ${pc(s.zero_trade_session_rate)} | ${f(s.avg_hold_bars, 1)} | ${pc(s.win_rate)} | ${f(s.avg_win_usd)} / ${f(s.avg_loss_usd)} | **${f(s.expectancy_usd, 3)}** | ${ci(s.ci95_usd)} | ${f(s.pf)} | ${f(key === 'HOLD' ? r.path_hold.max_drawdown_usd : r.path_dev.max_drawdown_usd)} (${pc(key === 'HOLD' ? r.path_hold.max_drawdown_pct_of_start : r.path_dev.max_drawdown_pct_of_start)}) | ${key === 'HOLD' ? r.path_hold.max_loss_streak : r.path_dev.max_loss_streak} | ${f(s.wins_erased_by_one_loss)} |`; });
  return `### ${title}\n| Candidate | Trades | Independent | Trades/session (median) | Zero-trade sessions | Avg hold (bars) | Win rate | Avg win / loss (USD) | Expectancy (USD) | 95 % CI | PF | Max DD from ${eq} USD (% of start) | Loss streak | Wins erased by one loss |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n${rows.join('\n')}\n`;
}
function stateBlock(title, key, eq, pol) {
  const rows = CANDS.map((c) => { const s = A[c].per_policy[pol][eq][key]; if (!s || !s.trades) return `| ${c} | 0 | | | | | | | | | | | | |`; return `| ${c} | ${s.trades} | ${pc(s.profit_available_rate)} | ${pc(s.protect_rate)} | ${pc(s.harvest_rate)} | ${pc(s.protected_run_rate)} | ${pc(s.early_exit_rate)} (${f(s.early_exit_avg_loss_usd)}) | ${f(s.mfe_mean_usd)} / ${f(s.mae_mean_usd)} | ${f(s.giveback?.mean)} / ${f(s.giveback?.median)} / ${f(s.giveback?.p75)} / ${f(s.giveback?.p90)} | ${f(s.premature_exit_cost_usd)} (n ${s.premature_exit_n}) | ${f(s.additional_profit_from_runners_usd)} (n ${s.runners_n}) | ${pc(s.cost_pct_of_gross_profit)} | ${pc(s.months_positive_share)} | ${pc(s.top5_share_of_gross_profit)} |`; });
  return `### ${title}\n| Candidate | Trades | Profit-available rate | Protect rate | Harvest rate | Protected-run rate | Early-exit rate (avg loss) | MFE / MAE mean (USD) | Give-back mean / median / P75 / P90 (USD) | Premature-exit cost (USD, n) | Additional profit from runners (USD, n) | Cost % of gross profit | Months positive | Top-5 share |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n${rows.join('\n')}\n`;
}
const exits = (key, eq, pol) => `### Exit mix (${key}, ${polName(pol)}, ${eq} USD)\n| Candidate | Exits |\n|---|---|\n${CANDS.map((c) => `| ${c} | ${Object.entries(A[c].per_policy[pol][eq][key]?.exit_mix ?? {}).map(([k, v]) => `${k} ${v}`).join(', ') || '—'} |`).join('\n')}\n`;
const dev = `# DEVELOPMENT RESULTS (2025-05-07 → 2025-12-31; ${R.meta.signals_dev} production signals; ${R.meta.sessions_dev} sessions)\n\nNormal costs. "No cap" isolates the management effect (every signal eligible, one position, re-entry rules). The 5 % policy from 500 USD is the smallest proportional case with ≥ 300 holdout trades for most candidates; the 10 % policy from 250 USD is shown for the capital view.\n\n${block('No capital cap — management effect only (paths from 1000 USD)', 'DEV', 1000, 'null')}\n${stateBlock('State and give-back metrics (no cap)', 'DEV', 1000, 'null')}\n${block('5 % policy, paths from 500 USD', 'DEV', 500, '5')}\n${block('10 % policy, paths from 250 USD', 'DEV', 250, '10')}\n${exits('DEV', 1000, 'null')}\nSource: research/capital_harvest_master/results/study_results.json (architectures.*.per_policy.*.*.DEV).\n`;
const hold = `# HOLDOUT RESULTS (2026-01-01 → 2026-09-29; ${R.meta.signals_hold} production signals; ${R.meta.sessions_hold} sessions; Bonferroni α ${R.meta.bonferroni_alpha.toFixed(4)})\n\nNormal costs unless stated. Decision rule: PREREGISTRATION §11.\n\n${block('No capital cap — management effect only (paths from 1000 USD)', 'HOLD', 1000, 'null')}\n${stateBlock('State and give-back metrics (no cap)', 'HOLD', 1000, 'null')}\n${block('5 % policy, paths from 500 USD', 'HOLD', 500, '5')}\n${stateBlock('State and give-back metrics (5 %, 500 USD)', 'HOLD', 500, '5')}\n${block('10 % policy, paths from 250 USD', 'HOLD', 250, '10')}\n${block('3 % policy, paths from 1000 USD', 'HOLD', 1000, '3')}\n${exits('HOLD', 1000, 'null')}\n## Decisions (frozen rule; first non-empty equity per policy, plus 62.07 / 250 / 1000 USD)\n| Candidate | Policy | First non-empty equity | Status there | Reasons / gaps | 62.07 USD | 250 USD | 1000 USD |\n|---|---|---|---|---|---|---|---|\n${Object.entries(R.decisions).flatMap(([c, d]) => Object.entries(d).map(([p, x]) => `| ${c} | ${p} % | ${x.first_nonempty_equity ?? '—'} | ${x.at_first_nonempty.status} | ${(x.at_first_nonempty.reasons ?? x.at_first_nonempty.promo_gaps ?? []).join(', ')} | ${x.at_62_07.status} | ${x.at_250.status} | ${x.at_1000.status} |`)).join('\n')}\n\nSUPPORTED_RESEARCH_LEAD count: ${R.meta.supported.length}. FORWARD_SHADOW_ELIGIBLE (frozen rule): ${R.meta.forward_shadow_eligible ? 'YES' : 'NO'}.\n`;
// ---- cost stress
const stress = `# COST / STRESS / ROBUSTNESS RESULTS (holdout)\n\nNORMAL: spread 0.24, slippage 0.10. STRESS: spread 0.60, slippage 0.20. DRIFT: fill at the next bar's open (+spread for BUY). Swap on overnight BUYs in all cases. CONTROL (Edge Lab production simulation) is available at normal cost only.\n\n| Candidate | Policy / equity | Normal exp (USD) | Normal PF | Stress exp (USD) | Stress PF | Stress CI | Drift exp (USD) | Drift PF | Verdict |\n|---|---|---|---|---|---|---|---|---|---|\n${CANDS.filter((c) => c !== 'CONTROL').flatMap((c) => [['null', 1000], ['5', 500], ['10', 250], ['3', 1000]].map(([p, e]) => { const r = A[c].per_policy[p][e]; const h = r.HOLD; if (!h.trades) return `| ${c} | ${polName(p)} / ${e} | 0 | | | | | | | EMPTY |`; return `| ${c} | ${polName(p)} / ${e} | ${f(h.expectancy_usd, 3)} | ${f(h.pf)} | ${f(r.HOLD_stress?.expectancy_usd, 3)} | ${f(r.HOLD_stress?.pf)} | ${ci(r.HOLD_stress?.ci95_usd)} | ${f(r.HOLD_drift?.expectancy_usd, 3)} | ${f(r.HOLD_drift?.pf)} | ${(r.HOLD_stress?.expectancy_usd ?? -1) > 0 ? 'survives stress' : 'REJECTED: negative under stress'} |`; })).join('\n')}\n\nReading: every candidate is profitable only under normal costs and negative under stress costs; cost as a share of gross profit is 6–7 % at normal cost, but the average win is only ≈ 8–10 USD against a 10 USD average loss, so a 0.46 USD round-trip cost increase (0.36 spread + 0.10 slippage) erases the margin. Per PREREGISTRATION §3 this alone REJECTS every candidate.\n`;
// ---- percentage risk matrix + capital survival
const matrix = `# PERCENTAGE RISK MATRIX (all ${R.meta.signals} production signals; governed exposure = 1.5 × structural + spread + slippage at 0.01 lot; margin = price/200)\n\n## Signal eligibility share by policy and equity\n| Equity (USD) | 1 % | 2 % | 3 % | 5 % | 7.5 % | 10 % | production −50 veto | Median exposure % of equity | P75 exposure % | Median structural % | Margin burden % |\n|---|---|---|---|---|---|---|---|---|---|---|---|\n${EQ.map((eq) => { const e = R.eligibility[eq]; return `| ${eq} | ${pc(e['1'].eligible_share)} | ${pc(e['2'].eligible_share)} | ${pc(e['3'].eligible_share)} | ${pc(e['5'].eligible_share)} | ${pc(e['7.5'].eligible_share)} | ${pc(e['10'].eligible_share)} | ${pc(e.PROD_VETO.eligible_share)} | ${f(e._risk.median_exposure_pct, 1)} | ${f(e._risk.p75_exposure_pct, 1)} | ${f(e._risk.median_structural_pct, 1)} | ${f(e._risk.margin_burden_pct, 1)} |`; }).join('\n')}\n\nBROKER CAN EXECUTE vs MCP SHOULD EXECUTE: the broker accepts a 0.01-lot order whenever free margin ≥ ≈ 21 USD (every equity above); MCP under a percentage policy admits only the share shown. The production −50 veto admits 0 % at 62.07 USD and 92 % at 75 USD (its ≈ 71 USD threshold).\n\n## Sequential paths (running equity decides eligibility; whole sample DEV+HOLD; normal costs)\n| Candidate | Policy | Equity | Trades (all / HOLD) | HOLD exp (USD) | HOLD PF | Max DD (USD, % of start) | Min balance | Loss streak | Margin-floor hit | Month-shuffled floor touch (HOLD) | Mean risk % per trade |\n|---|---|---|---|---|---|---|---|---|---|---|---|\n${CANDS.flatMap((c) => POL.flatMap((p) => EQ.map((e) => { const m = R.capital_matrix[`${c}|${p}|${e}`]; if (!m) return null; if (!m.trades_all) return `| ${c} | ${polName(p)} | ${e} | 0 / 0 | — | — | — | — | — | — | — | — |`; return `| ${c} | ${polName(p)} | ${e} | ${m.trades_all} / ${m.trades_hold} | ${f(m.hold_exp, 3)} | ${f(m.hold_pf)} | ${f(m.dd_all)} (${pc(m.dd_pct)}) | ${f(m.min_bal_all)} | ${m.loss_streak} | ${m.floor_hit ? 'YES' : 'no'} | ${pc(m.depletion_hold)} | ${f(m.risk_pct_mean, 1)} |`; }))).filter(Boolean).join('\n')}\n`;
const surv = `# CAPITAL SURVIVAL RESULTS (per starting equity; whole-sample sequential paths at normal cost; 0.01 lot fixed)\n\nNo balance is called "safe": these are simulated historical paths on production entries. "Eligibility" = share of signals the policy admits at that equity (fixed-equity view); "trades" = sequential trades actually taken with the running equity.\n\n${EQ.map((eq) => { const e = R.eligibility[eq]; const rows = CANDS.flatMap((c) => ['null', '3', '5', '10', 'PROD_VETO'].map((p) => { const m = R.capital_matrix[`${c}|${p}|${eq}`]; return `| ${c} | ${polName(p)} | ${pc(e[p].eligible_share)} | ${m.trades_all} | ${f(m.min_bal_all)} | ${f(m.dd_all)} (${pc(m.dd_pct)}) | ${m.loss_streak} | ${m.floor_hit ? 'YES' : 'no'} | ${pc(m.depletion_hold)} | ${f(m.risk_pct_mean, 1)} |`; })); return `## ${eq} USD — median exposure ${f(e._risk.median_exposure_pct, 1)} % of equity, margin burden ${f(e._risk.margin_burden_pct, 1)} %, production veto ${e._risk.production_veto_executable ? 'executable' : 'BLOCKS'}\n| Candidate | Policy | Eligibility | Trades | Min balance | Max DD (USD, %) | Loss streak | Margin floor hit | Month-shuffled floor touch | Mean risk % |\n|---|---|---|---|---|---|---|---|---|---|\n${rows.join('\n')}\n`; }).join('\n')}\nMinimum-lot constraint: at 0.01 lot the governed exposure of the median production signal is ≈ 9.8 USD; a 1 % policy needs ≈ 1000 USD to admit half the signals, 2 % ≈ 500 USD, 3 % ≈ 330 USD, 5 % ≈ 200 USD; at 62.07 USD only 10 % admits anything (26 % of signals, the tightest-stop quarter) and the resulting path loses that equity.\n`;
// ---- current model comparison
const cmp = `# CURRENT MODEL COMPARISON (holdout, same production entries)\n\n| Model | Capital rule | Position management | HOLD trades | Expectancy (USD) | 95 % CI | PF | Win rate | Avg win / loss | Max DD from 1000 (USD) | Loss streak | Months positive | Verdict vs CONTROL |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|\n${CANDS.map((c) => { const r = A[c].per_policy['null'][1000]; const h = r.HOLD; const ctl = A.CONTROL.per_policy['null'][1000]; const better = c === 'CONTROL' ? '—' : (h.pf >= ctl.HOLD.pf && r.path_hold.max_drawdown_usd <= ctl.path_hold.max_drawdown_usd) ? 'not worse on PF and DD' : (h.pf < ctl.HOLD.pf && r.path_hold.max_drawdown_usd > ctl.path_hold.max_drawdown_usd) ? 'WORSE on PF and DD' : 'mixed'; return `| ${c} (${desc[c]}) | ${c === 'CONTROL' ? '−50 USD veto (reported separately)' : 'pct policy (no cap here)'} | ${desc[c]} | ${h.trades} | ${f(h.expectancy_usd, 3)} | ${ci(h.ci95_usd)} | ${f(h.pf)} | ${pc(h.win_rate)} | ${f(h.avg_win_usd)} / ${f(h.avg_loss_usd)} | ${f(r.path_hold.max_drawdown_usd)} | ${r.path_hold.max_loss_streak} | ${pc(h.months_positive_share)} | ${better} |`; }).join('\n')}\n\nCONTROL_FIXED_50 vs percentage rule at the REAL equity (62.07 USD): the −50 veto admits 0 % of signals; the percentage policies admit 0 % (1–3 %), 3.7 % (5 %), 14.6 % (7.5 %), 26.2 % (10 %) — but every admitted subset is the tightest-stop quarter whose sequential path at 62.07 USD ends below its start (CAPITAL_SURVIVAL_RESULTS.md).\n`;
writeFileSync(join(OUT, 'DEVELOPMENT_RESULTS.md'), dev); writeFileSync(join(OUT, 'HOLDOUT_RESULTS.md'), hold); writeFileSync(join(OUT, 'COST_STRESS_RESULTS.md'), stress); writeFileSync(join(OUT, 'PERCENTAGE_RISK_MATRIX.md'), matrix); writeFileSync(join(OUT, 'CAPITAL_SURVIVAL_RESULTS.md'), surv); writeFileSync(join(OUT, 'CURRENT_MODEL_COMPARISON.md'), cmp);
console.log('tables written');
