/**
 * ENTRY EDGE V3 -- PB / MR / BO2 subsets under regime + direction + hysteresis (RESEARCH ONLY). Spec: ../V3_PREREGISTRATION.md (hash asserted).
 * EDGE_PHASE=DEV : diagnostics + candidate evaluation on DEVELOPMENT; derives the frozen finalists (hysteresis level per candidate) -> configs/finalists.json
 * EDGE_PHASE=FULL: asserts the finalists hash; evaluates DEV + HOLDOUT once -> results/v3_results.json
 * Same data, EXIT_F, costs and re-entry guard as V1/V2. No production module is modified.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { canReenter } from '../../../src/engine/capitalHarvest/positionManager.js';

const PHASE = process.env.EDGE_PHASE === 'FULL' ? 'FULL' : 'DEV';
const HERE = dirname(fileURLToPath(import.meta.url)); const REPO = join(HERE, '..', '..', '..'); const ROOT = join(REPO, 'research', 'entry_edge_v3'); const OUT = join(ROOT, 'results'); const CFG = join(ROOT, 'configs'); mkdirSync(OUT, { recursive: true }); mkdirSync(CFG, { recursive: true });
const PREREG_SHA = readFileSync(join(ROOT, 'V3_PREREGISTRATION.sha256'), 'utf8').trim().split(/\s+/)[0];
if (createHash('sha256').update(readFileSync(join(ROOT, 'V3_PREREGISTRATION.md'))).digest('hex') !== PREREG_SHA) throw new Error('V3_PREREGISTRATION hash mismatch');
const LAB = join(REPO, 'handoff', 'edge_discovery_lab', 'data');
const b5 = JSON.parse(readFileSync(join(LAB, 'XAUUSDm_bars.json'), 'utf8'))['5m'];
const COSTS = { normal: { spread: 0.24, slip: 0.10 }, stress: { spread: 0.60, slip: 0.20 } }; const SWAP = 0.56; const HORIZON = 288; const GAP = 3 * 3600;
const r2 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 100) / 100); const r3 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 1000) / 1000);
const iso = (t) => new Date(t * 1000).toISOString(); const day = (t) => iso(t).slice(0, 10); const month = (t) => iso(t).slice(0, 7); const quarter = (t) => { const d = new Date(t * 1000); return `${d.getUTCFullYear()}Q${Math.floor(d.getUTCMonth() / 3) + 1}`; };
const SPLIT = { dev: ['2025-05-07', '2025-12-31'], hold: ['2026-01-01', '2026-09-29'] };
const split = (t) => { const d = day(t); if (d >= SPLIT.dev[0] && d <= SPLIT.dev[1]) return 'DEV'; if (d >= SPLIT.hold[0] && d <= SPLIT.hold[1]) return 'HOLD'; return 'EXCLUDED'; };
const mean = (a) => (a.length ? a.reduce((s, x) => s + x, 0) / a.length : null); const median = (a) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); const m = s.length >> 1; return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2; }; const pct = (a, p) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); return s[Math.min(s.length - 1, Math.floor(p * s.length))]; };
function rng(seed) { let s = seed >>> 0; return () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
function bootCI(v, n = 2000, seed = 20260930, alpha = 0.05) { if (v.length < 2) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0; for (let j = 0; j < v.length; j++) s += v[Math.floor(rand() * v.length)]; ms.push(s / v.length); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor((alpha / 2) * n)]), r3(ms[Math.floor((1 - alpha / 2) * n)])]; }
function blockCI(rows, n = 2000, seed = 7, alpha = 0.05) { const g = {}; for (const r of rows) (g[day(r.e.t)] ??= []).push(r.o.r); const blocks = Object.values(g); if (blocks.length < 5) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0, c = 0; for (let j = 0; j < blocks.length; j++) { const b = blocks[Math.floor(rand() * blocks.length)]; for (const x of b) { s += x; c++; } } ms.push(s / c); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor((alpha / 2) * n)]), r3(ms[Math.floor((1 - alpha / 2) * n)])]; }

// ---------- data ----------
const ROWS = new Map(); const ROWLIST = []; const sessions = { DEV: new Set(), HOLD: new Set(), ALL: new Set() };
for (const line of readFileSync(join(LAB, 'lab_rows.jsonl'), 'utf8').split('\n')) { if (!line) continue; const r = JSON.parse(line); const sp = split(r.t); if (sp === 'EXCLUDED') continue; r.split = sp; ROWS.set(r.i, r); ROWLIST.push(r); sessions[sp].add(day(r.t)); sessions.ALL.add(day(r.t)); }
ROWLIST.sort((a, b) => a.i - b.i);
// hysteresis regimes H0..H3 (PREREGISTRATION section 5): reset at each session's first candle
const HK = [0, 1, 2, 3]; const HREG = Object.fromEntries(HK.map((k) => [k, new Map()])); const FLIPS = Object.fromEntries(HK.map((k) => [k, {}]));
{ let prevDay = null; const hist = []; const cur = {}; for (const r of ROWLIST) { const d = day(r.t); if (d !== prevDay) { prevDay = d; hist.length = 0; for (const k of HK) { cur[k] = r.rg5; FLIPS[k][d] = 0; } } hist.push(r.rg5); if (hist.length > 4) hist.shift();
    for (const k of HK) { if (k <= 1) { if (cur[k] !== r.rg5) { FLIPS[k][d]++; cur[k] = r.rg5; } } else { const ok = hist.length >= k && hist.slice(-k).every((x) => x === r.rg5); if (ok && cur[k] !== r.rg5) { FLIPS[k][d]++; cur[k] = r.rg5; } } HREG[k].set(r.i, cur[k]); } } }
const C = readFileSync(join(REPO, 'research', 'entry_architecture_v2', 'results', 'candidates.jsonl'), 'utf8').trim().split('\n').map((l) => JSON.parse(l)).filter((c) => split(c.t) !== 'EXCLUDED');
for (const c of C) { c.split = split(c.t); c.isSig = c.act === 'BUY' || c.act === 'SELL'; c.row = ROWS.get(c.i) ?? null; c.hreg = Object.fromEntries(HK.map((k) => [k, HREG[k].get(c.i) ?? c.rg5])); c.src = 'CAND'; }
console.log(`phase ${PHASE}; rows ${ROWLIST.length}; signals ${C.filter((c) => c.isSig).length}`);

// ---------- EXIT_F (identical to V1/V2) ----------
function exitF(e, costs = COSTS.normal, drift = false) { const { i, side } = e; const { entry, sl, tp2 } = e.geo; const sp = costs.spread, slip = costs.slip; const sgn = side === 'BUY' ? 1 : -1; let fill = side === 'BUY' ? entry + sp : entry, start = i + 1; if (drift) { if (i + 1 >= b5.length) return { status: 'NO_DATA' }; fill = side === 'BUY' ? b5[i + 1].open + sp : b5[i + 1].open; start = i + 2; } const d = Math.abs(entry - sl); if (!(d > 0)) return { status: 'INVALID' }; const brokerDist = 1.5 * d + sp; const end = Math.min(b5.length - 1, i + HORIZON); let mfe = 0, mae = 0, mae3 = 0, nights = 0, gap = false, exit = null, exitBar = null, pnl = 0;
  for (let j = start; j <= end; j++) { const b = b5[j], p = b5[j - 1]; if (b.time - p.time > GAP) gap = true; if (side === 'BUY' && Math.floor(b.time / 86400) !== Math.floor(p.time / 86400)) nights++; const adv = side === 'BUY' ? fill - b.low : (b.high + sp) - fill; const fav = side === 'BUY' ? b.high - fill : fill - (b.low + sp); if (adv > mae) mae = adv; if (j - i <= 3 && adv > mae3) mae3 = adv; if (adv >= brokerDist) { exit = 'BROKER_SL'; pnl = -brokerDist - slip; exitBar = j; break; } const tpHit = side === 'BUY' ? b.high >= tp2 : (b.low + sp) <= tp2; if (tpHit) { if (fav > mfe) mfe = fav; exit = 'TP2'; pnl = Math.abs(tp2 - fill) - slip; exitBar = j; break; } if (fav > mfe) mfe = fav; if (side === 'BUY' ? b.close < sl : b.close > sl) { exit = 'THESIS_INVALIDATION'; pnl = sgn * ((side === 'BUY' ? b.close : b.close + sp) - fill) - slip; exitBar = j; break; } }
  let status = 'RESOLVED'; if (!exit) { if (end < i + HORIZON) return { status: 'NO_DATA' }; status = 'OPEN_AT_HORIZON'; const b = b5[end]; exit = 'HORIZON'; pnl = sgn * ((side === 'BUY' ? b.close : b.close + sp) - fill) - slip; exitBar = end; } const swap = side === 'BUY' ? nights * SWAP : 0; pnl -= swap;
  return { status, gap, exit, exitBar, bars: exitBar - i, d: r3(d), pnl_usd: r3(pnl), r: r3(pnl / d), mfe_r: r3(mfe / d), mae_r: r3(mae / d), mae3_r: r3(mae3 / d), cost_usd: r3(sp + slip + swap), cost_r: r3((sp + slip + swap) / d) }; }
console.log('simulating ...'); const OC = { normal: C.map((c) => exitF(c)), stress: C.map((c) => exitF(c, COSTS.stress)), drift: C.map((c) => exitF(c, COSTS.normal, true)) }; C.forEach((c, k) => { c.k = k; });
const rowsOf = (pred, cse = 'normal') => C.map((c) => ({ e: c, o: OC[cse][c.k] })).filter((x) => x.e.isSig && pred(x.e) && x.o.status !== 'NO_DATA' && x.o.status !== 'INVALID');
const inS = (S) => (c) => S === 'ALL' || c.split === S;

// ---------- statistics (as V2) ----------
function seqWalk(rows) { const trades = []; let exitBar = -1, lastTrade = null, lastLoss = false; const skipped = { SAME_OR_EARLIER_CANDLE: 0, STALE_SAME_SETUP: 0, REVENGE_GUARD: 0 }; const occ = []; for (const x of [...rows].sort((a, b) => a.e.i - b.e.i)) { const ok = canReenter({ signal: x.e, exitBar, lastTrade, lastExitWasLoss: lastLoss }); if (!ok.ok) { skipped[ok.reason]++; continue; } trades.push(x); occ.push([x.e.i, x.o.exitBar]); exitBar = x.o.exitBar; lastTrade = x.e; lastLoss = x.o.r <= 0; } return { trades, skipped, occ }; }
function pathDD(rows, key = 'r') { let cum = 0, peak = 0, dd = 0, streak = 0, maxStreak = 0; for (const x of rows) { cum += x.o[key]; if (cum > peak) peak = cum; dd = Math.max(dd, peak - cum); if (x.o[key] <= 0) { streak++; maxStreak = Math.max(maxStreak, streak); } else streak = 0; } return { max_dd: r2(dd), final: r2(cum), max_loss_streak: maxStreak }; }
function stats(rows, sessSet = null, { ci = true, block = false } = {}) { const R = rows.map((x) => x.o.r); if (!R.length) return { n: 0 }; const w = R.filter((x) => x > 0), l = R.filter((x) => x <= 0); const gw = w.reduce((a, b) => a + b, 0), gl = -l.reduce((a, b) => a + b, 0); const U = rows.map((x) => x.o.pnl_usd); const perDay = {}; for (const x of rows) perDay[day(x.e.t)] = (perDay[day(x.e.t)] ?? 0) + 1; const counts = sessSet ? [...sessSet].map((d) => perDay[d] ?? 0) : null; const costU = rows.reduce((s, x) => s + x.o.cost_usd, 0); const ddR = pathDD(rows, 'r'), ddU = pathDD(rows, 'pnl_usd'); const losers = rows.filter((x) => x.o.r <= 0);
  return { n: R.length, win_rate: r3(w.length / R.length), avg_win_r: r3(mean(w)), avg_loss_r: l.length ? r3(-mean(l)) : null, expectancy_r: r3(mean(R)), expectancy_usd: r3(mean(U)), gross_expectancy_usd: r3(mean(U) + costU / R.length), pf: gl > 0 ? r2(gw / gl) : (gw > 0 ? 99 : null), ci95_r: ci ? bootCI(R) : null, ci99_r: ci ? bootCI(R, 2000, 20260930, 0.01) : null, block_ci95_r: block ? blockCI(rows) : null, block_ci99_r: block ? blockCI(rows, 2000, 7, 0.01) : null, max_dd_r: ddR.max_dd, max_dd_usd: ddU.max_dd, net_r: ddR.final, max_loss_streak: ddR.max_loss_streak, mfe_r: r3(mean(rows.map((x) => x.o.mfe_r))), mae_r: r3(mean(rows.map((x) => x.o.mae_r))), mae3_r: r3(mean(rows.map((x) => x.o.mae3_r))), avg_bars: r2(mean(rows.map((x) => x.o.bars))), cost_usd: r3(costU / R.length), cost_pct_gross: (mean(U) + costU / R.length) > 0 ? r3((costU / R.length) / (mean(U) + costU / R.length)) : null, trades_per_session: counts ? { median: pct(counts, 0.5), p10: pct(counts, 0.1), p90: pct(counts, 0.9), mean: r2(mean(counts)) } : null, zero_trade_session_rate: counts ? r3(counts.filter((x) => x === 0).length / counts.length) : null, top5_share: gw > 0 ? r3([...R].sort((a, b) => b - a).slice(0, 5).filter((x) => x > 0).reduce((s, x) => s + x, 0) / gw) : null, model_mix: Object.fromEntries(Object.entries(rows.reduce((g, x) => { g[x.e.model] = (g[x.e.model] ?? 0) + 1; return g; }, {}))), losers_reaching: losers.length ? { r025: r3(losers.filter((x) => x.o.mfe_r >= 0.25).length / losers.length), r050: r3(losers.filter((x) => x.o.mfe_r >= 0.5).length / losers.length), r100: r3(losers.filter((x) => x.o.mfe_r >= 1.0).length / losers.length) } : null }; }
const cell = (rows) => { const s = stats(rows, null, { ci: rows.length >= 30 }); return { n: s.n ?? 0, win_rate: s.win_rate, avg_win_r: s.avg_win_r, avg_loss_r: s.avg_loss_r, expectancy_r: s.expectancy_r, expectancy_usd: s.expectancy_usd, pf: s.pf, mfe_r: s.mfe_r, mae_r: s.mae_r, cost_r: s.n ? r3(mean(rows.map((x) => x.o.cost_r))) : null, ci95_r: s.ci95_r }; };

// ---------- subsets and candidates (PREREGISTRATION sections 4, 6) ----------
const P0 = { mr_atr: 1.0, bo_rng: 1.0, bo_atr: 1.0, bo_chase: 1.5 };
const fade = (c, h) => (c.side === 'BUY' && c.hreg[h] === 'BEAR_TREND') || (c.side === 'SELL' && c.hreg[h] === 'BULL_TREND');
const SUB = {
  PB_SELL: (c) => c.model === 'PB' && c.side === 'SELL',
  PB_RANGE: (c, h) => c.model === 'PB' && c.hreg[h] === 'RANGE',
  MR_LONG: (c, h) => c.model === 'MR' && c.side === 'BUY' && !fade(c, h),
  MR_HIGH_ATR: (c, h, p = P0) => c.model === 'MR' && c.atrR >= p.mr_atr && !fade(c, h),
  BO2: (c, h, p = P0) => c.model === 'BO' && c.row && c.row.rngA >= p.bo_rng && c.atrR >= p.bo_atr && c.overext_atr <= p.bo_chase,
};
const CAND = {
  'V3-A': (c, h, p) => SUB.PB_SELL(c) || SUB.PB_RANGE(c, h),
  'V3-B': (c, h, p) => SUB.MR_LONG(c, h) || SUB.MR_HIGH_ATR(c, h, p),
  'V3-C': (c, h, p) => SUB.BO2(c, h, p) || SUB.PB_SELL(c) || SUB.PB_RANGE(c, h),
  'V3-D': (c, h, p) => { const g = c.hreg[h]; if (g === 'RANGE') return c.model === 'PB' || (c.model === 'MR' && c.side === 'BUY'); if (g === 'BEAR_TREND') return c.model === 'PB' && c.side === 'SELL'; if (g === 'BULL_TREND') return false; return c.model === 'MR' && c.side === 'BUY' && c.atrR >= p.mr_atr; },
  'V3-E': (c, h, p) => (SUB.BO2(c, h, p) && c.hreg[h] !== 'RANGE') || SUB.PB_SELL(c),
};
const candRows = (name, S, h, p = P0, cse = 'normal') => rowsOf((c) => inS(S)(c) && CAND[name](c, h, p), cse);
const ctlRows = (S, cse = 'normal') => rowsOf(inS(S), cse);

// ---------- controls ----------
const ctrl = (() => { const rand = rng(99); const leak = [], nul = []; for (const c of C.filter((c, k) => c.isSig && k % 5 === 0)) { if (c.i + 13 >= b5.length) continue; const fut = b5[c.i + 12].close - b5[c.i].close; const mk = (side) => ({ i: c.i, side, geo: { entry: b5[c.i].close, sl: side === 'BUY' ? b5[c.i].close - c.atr : b5[c.i].close + c.atr, tp2: side === 'BUY' ? b5[c.i].close + c.atr : b5[c.i].close - c.atr } }); const o1 = exitF(mk(fut >= 0 ? 'BUY' : 'SELL')), o2 = exitF(mk(rand() < 0.5 ? 'BUY' : 'SELL')); if (o1.status !== 'NO_DATA' && !o1.gap) leak.push(o1.r); if (o2.status !== 'NO_DATA' && !o2.gap) nul.push(o2.r); }
  const s = C.slice(0, 400); const diff = mean(s.map((c) => exitF(c, { spread: 0.24, slip: 0 }).pnl_usd)) - mean(s.map((c) => exitF(c).pnl_usd));
  // hysteresis determinism / no look-ahead: H1 == H0 everywhere; H_k only differs from raw when the last k raw labels are not all equal to raw
  let h1eq = true, lookahead = 0; const byI = new Map(ROWLIST.map((r, idx) => [r.i, idx])); for (const r of ROWLIST) { if (HREG[1].get(r.i) !== HREG[0].get(r.i)) h1eq = false; for (const k of [2, 3]) { const hk = HREG[k].get(r.i); if (hk !== r.rg5) { const idx = byI.get(r.i); const last = ROWLIST.slice(Math.max(0, idx - k + 1), idx + 1).map((x) => x.rg5); if (last.length === k && last.every((x) => x === r.rg5) && day(ROWLIST[idx - k + 1].t) === day(r.t)) lookahead++; } } }
  const v2 = JSON.parse(readFileSync(join(REPO, 'research', 'entry_engine_core_rebuild_v2', 'results', 'v2_results.json'), 'utf8')); const ctlH = stats(seqWalk(ctlRows('HOLD')).trades, sessions.HOLD, { ci: false }); const reproduces = ctlH.n === v2.finalists.HOLD.CONTROL.n && ctlH.expectancy_r === v2.finalists.HOLD.CONTROL.expectancy_r;
  return { leak_mean_r: r3(mean(leak)), leak_n: leak.length, null_mean_r: r3(mean(nul)), null_n: nul.length, cost_test: { diff: r3(diff), expected: 0.10, pass: Math.abs(diff - 0.10) < 0.001 }, hysteresis_h1_equals_h0: h1eq, hysteresis_lookahead_violations: lookahead, control_reproduces_v2: reproduces, control_hold: { n: ctlH.n, expectancy_r: ctlH.expectancy_r } }; })();
console.log('controls', JSON.stringify(ctrl)); if (!(ctrl.leak_mean_r > 0.3) || !(Math.abs(ctrl.null_mean_r) < 0.15) || !ctrl.cost_test.pass || !ctrl.hysteresis_h1_equals_h0 || ctrl.hysteresis_lookahead_violations || !ctrl.control_reproduces_v2) throw new Error('CONTROL FAILED');

// ---------- move events (V1/V2 definition) ----------
const ATR14 = new Array(b5.length).fill(null); { let sum = 0; const tr = []; for (let k = 1; k < b5.length; k++) { const t = Math.max(b5[k].high - b5[k].low, Math.abs(b5[k].high - b5[k - 1].close), Math.abs(b5[k].low - b5[k - 1].close)); tr.push(t); sum += t; if (tr.length > 14) sum -= tr[tr.length - 15]; if (tr.length >= 14) ATR14[k] = sum / 14; } }
function findEvents(S) { if (S === 'ALL') return [...findEvents('DEV'), ...findEvents('HOLD')]; const events = []; let k = 500; const lo = S === 'DEV' ? SPLIT.dev[0] : SPLIT.hold[0], hi = S === 'DEV' ? SPLIT.dev[1] : SPLIT.hold[1]; while (k < b5.length - 25) { const d = day(b5[k].time); if (d < lo) { k++; continue; } if (d > hi) break; const a = ATR14[k]; if (!a) { k++; continue; } const c0 = b5[k].close; let up = null, dn = null, maxH = -Infinity, minL = Infinity; for (let j = k + 1; j <= k + 24; j++) { const b = b5[j]; if (b.time - b5[j - 1].time > GAP) break; maxH = Math.max(maxH, b.high); minL = Math.min(minL, b.low); if (up == null && maxH - c0 >= 3 * a && c0 - minL <= a) up = j; if (dn == null && c0 - minL >= 3 * a && maxH - c0 <= a) dn = j; if (up != null || dn != null) break; } if (up != null || dn != null) { events.push({ k, t: b5[k].time, dir: up != null ? 'BUY' : 'SELL' }); k += 24; } else k++; } return events; }
function captureStats(events, rows, occ = []) { const by = {}; for (const x of rows) (by[x.e.i] ??= []).push(x.e.side); let valid = 0, late = 0, wrong = 0, none = 0, positioned = 0, noSetup = 0, gate = 0; for (const ev of events) { let e = false, l = false, w = false; for (let j = ev.k - 6; j <= ev.k + 6; j++) for (const s of by[j] ?? []) { if (s === ev.dir) { if (j <= ev.k) e = true; else l = true; } else w = true; } if (e) valid++; else if (l) late++; else if (w) wrong++; else if (occ.some(([a, b]) => ev.k >= a && ev.k <= b)) positioned++; else { none++; const r = ROWS.get(ev.k); if (!r || r.wr === 'NO_ELIGIBLE_STRATEGY' || r.wr === 'CHOP') noSetup++; else gate++; } } const n = Math.max(1, events.length); return { events: events.length, capture_rate: r3((valid + late) / n), valid_entry_rate: r3(valid / n), late_entry_rate: r3(late / n), wrong_direction_rate: r3(wrong / n), already_positioned_rate: r3(positioned / n), no_signal_rate: r3(none / n), no_setup_or_trigger_rate: r3(noSetup / n), gate_or_filter_rate: r3(gate / n) }; }
const wrongDirCount = (events, rows) => { const by = {}; for (const x of rows) (by[x.e.i] ??= []).push(x.e.side); let w = 0; for (const ev of events) { let hit = false; for (let j = ev.k - 6; j <= ev.k + 6 && !hit; j++) if ((by[j] ?? []).some((s) => s !== ev.dir)) hit = true; if (hit) w++; } return w; };

// ---------- evaluation ----------
function evaluate(rows, S, { block = true } = {}) { const sess = sessions[S]; const w = seqWalk(rows); const st = stats(w.trades, sess, { block }); const q = {}; for (const x of w.trades) (q[quarter(x.e.t)] ??= []).push(x); const walk = Object.fromEntries(Object.entries(q).sort().map(([k, v]) => { const s = stats(v, null, { ci: false }); return [k, { n: s.n, expectancy_r: s.expectancy_r, pf: s.pf, max_dd_r: s.max_dd_r, trades_per_session: r2(v.length / new Set(v.map((x) => day(x.e.t))).size) }]; })); const pos = Object.values(walk).filter((v) => v.expectancy_r > 0).length;
  const shuffle = w.trades.length ? (() => { const rand = rng(11); const byM = {}; for (const x of w.trades) (byM[month(x.e.t)] ??= []).push(x.o.r); const dds = [], streaks = []; for (let k = 0; k < 500; k++) { const order = Object.values(byM).sort(() => rand() - 0.5); let cum = 0, peak = 0, dd = 0, stk = 0, ms = 0; for (const m of order) for (const r of [...m].sort(() => rand() - 0.5)) { cum += r; peak = Math.max(peak, cum); dd = Math.max(dd, peak - cum); if (r <= 0) { stk++; ms = Math.max(ms, stk); } else stk = 0; } dds.push(dd); streaks.push(ms); } return { dd_r_p50: r2(median(dds)), dd_r_p90: r2(pct(dds, 0.9)), dd_r_p99: r2(pct(dds, 0.99)), loss_streak_p50: median(streaks), loss_streak_p90: pct(streaks, 0.9) }; })() : null;
  const ex = {}; for (const x of w.trades) ex[x.o.exit] = (ex[x.o.exit] ?? 0) + 1; const exit_mix = Object.fromEntries(Object.entries(ex).map(([k, v]) => [k, r3(v / w.trades.length)])); return { signals: rows.length, ...st, exit_mix, skipped: w.skipped, walk_forward: walk, quarters_positive_share: Object.keys(walk).length ? r3(pos / Object.keys(walk).length) : null, adverse: shuffle, occ: w.occ, trades: w.trades }; }
function tinyCellDependence(trades, h) { const cells = {}; for (const x of trades) (cells[`${x.e.model}|${x.e.hreg[h]}|${x.e.side}`] ??= []).push(x.o.r); const net = trades.reduce((s, x) => s + x.o.r, 0); let tinyNet = 0, maxTiny = 0, maxTinyCell = null; const list = Object.entries(cells).map(([k, v]) => { const s = v.reduce((a, b) => a + b, 0); if (v.length < 30 && s > 0) { tinyNet += s; if (s > maxTiny) { maxTiny = s; maxTinyCell = k; } } return { cell: k, n: v.length, net_r: r2(s), share_of_net: net > 0 ? r3(s / net) : null }; }).sort((a, b) => b.net_r - a.net_r); /* PREREGISTRATION section 9 (7): per-cell rule -- no cell with N < 30 contributes more than 30 % of net R; the summed share is reported as a diagnostic only */ return { cells: list, max_tiny_cell: maxTinyCell, max_tiny_cell_share: net > 0 ? r3(maxTiny / net) : null, tiny_cells_positive_net_share_sum: net > 0 ? r3(tinyNet / net) : null, pass: !(net > 0) || maxTiny / net <= 0.30 }; }
function neighbourhood(name, S, h, p) { const out = {}; const ev = (hh, pp) => { const s = stats(seqWalk(candRows(name, S, hh, pp)).trades, null, { ci: false }); return { n: s.n, expectancy_r: s.expectancy_r, pf: s.pf }; }; const cls = (o) => { const v = Object.entries(o).filter(([k]) => k !== 'classification').map(([, x]) => x.expectancy_r ?? -9); const centre = v[Math.floor(v.length / 2)]; return v.every((x) => x > 0) ? 'ROBUST' : centre > 0 && v.some((x) => x > 0 && x !== centre) ? 'SENSITIVE' : centre > 0 ? 'FRAGILE' : 'NEGATIVE_CENTRE'; };
  const hs = [Math.max(0, h - 1), h, Math.min(3, h + 1)]; out.hysteresis_k = Object.fromEntries(hs.map((hh) => [hh, ev(hh, p)])); out.hysteresis_k.classification = cls(out.hysteresis_k);
  const uses = { mr_atr: /B|D/.test(name), bo_rng: /C|E/.test(name), bo_atr: /C|E/.test(name), bo_chase: /C|E/.test(name) }; const NB = { mr_atr: [0.9, 1.1], bo_rng: [0.8, 1.2], bo_atr: [0.9, 1.1], bo_chase: [1.25, 1.75] }; for (const [pk, [lo, hi]] of Object.entries(NB)) { if (!uses[pk]) continue; out[pk] = { [lo]: ev(h, { ...p, [pk]: lo }), [p[pk]]: ev(h, p), [hi]: ev(h, { ...p, [pk]: hi }) }; out[pk].classification = cls(out[pk]); } return out; }
function diagnostics(S) {
  const D = {}; const sess = sessions[S]; const events = findEvents(S); const ctl = evaluate(ctlRows(S), S); D.control = { ...ctl, move_capture: captureStats(events, ctlRows(S), ctl.occ), occ: undefined, trades: undefined };
  // hysteresis effects (per candidate per k)
  D.hysteresis = { flips_per_session: Object.fromEntries(HK.map((k) => { const v = Object.entries(FLIPS[k]).filter(([d]) => sess.has(d)).map(([, n]) => n); return [k, { median: median(v), p90: pct(v, 0.9), mean: r2(mean(v)) }]; })), per_candidate: {} };
  for (const name of Object.keys(CAND)) { D.hysteresis.per_candidate[name] = {}; const base = candRows(name, S, 0); const baseIds = new Set(base.map((x) => x.e.k)); const baseWinners = new Set(base.filter((x) => x.o.r > 0).map((x) => x.e.k)); for (const k of HK) { const rows = candRows(name, S, k); const ids = new Set(rows.map((x) => x.e.k)); const ev = evaluate(rows, S, { block: false }); D.hysteresis.per_candidate[name][k] = { signals: rows.length, trades: ev.n, expectancy_r: ev.expectancy_r, pf: ev.pf, max_dd_r: ev.max_dd_r, cost_usd: ev.cost_usd, wrong_direction_signals: wrongDirCount(events, rows), missed_valid_signals_vs_H0: [...baseWinners].filter((id) => !ids.has(id)).length, removed_vs_H0: [...baseIds].filter((id) => !ids.has(id)).length, added_vs_H0: [...ids].filter((id) => !baseIds.has(id)).length, move_capture: ev.n ? captureStats(events, rows, ev.occ).capture_rate : null }; } }
  // subsets, overlap
  D.subsets = {}; for (const [k, f] of Object.entries(SUB)) { const rows = rowsOf((c) => inS(S)(c) && f(c, 0, P0)); D.subsets[k] = { H0: cell(rows), H2: cell(rowsOf((c) => inS(S)(c) && f(c, 2, P0))), sequential_H0: (() => { const s = stats(seqWalk(rows).trades, sess, { ci: false }); return { n: s.n, expectancy_r: s.expectancy_r, pf: s.pf, max_dd_r: s.max_dd_r }; })() }; }
  const ids = Object.fromEntries(Object.entries(SUB).map(([k, f]) => [k, new Set(rowsOf((c) => inS(S)(c) && f(c, 0, P0)).map((x) => x.e.k))])); const names = Object.keys(SUB); const ov = {}; for (let a = 0; a < names.length; a++) for (let b = a + 1; b < names.length; b++) { const n = [...ids[names[a]]].filter((x) => ids[names[b]].has(x)).length; if (n) ov[`${names[a]}∩${names[b]}`] = n; } const union = new Set(names.flatMap((n) => [...ids[n]])); D.overlap = { sizes: Object.fromEntries(names.map((n) => [n, ids[n].size])), pairwise: ov, union: union.size, unique_to_one_subset: [...union].filter((x) => names.filter((n) => ids[n].has(x)).length === 1).length, incremental_contribution: Object.fromEntries(names.map((n) => { const others = new Set(names.filter((m) => m !== n).flatMap((m) => [...ids[m]])); const rows = rowsOf((c) => inS(S)(c) && ids[n].has(c.k) && !others.has(c.k)); return [n, { unique_n: rows.length, unique_expectancy_r: cell(rows).expectancy_r, unique_net_r: r2(rows.reduce((s, x) => s + x.o.r, 0)) }]; })) };
  // regime x direction matrix (H0 and H2) for PB, MR, BO2
  D.matrix = {}; for (const h of [0, 2]) { D.matrix[`H${h}`] = {}; for (const m of ['PB', 'MR', 'BO2']) { const rows = rowsOf((c) => inS(S)(c) && (m === 'BO2' ? SUB.BO2(c, h) : c.model === m)); const g = {}; for (const x of rows) (g[`${x.e.hreg[h]}|${x.e.side}`] ??= []).push(x); D.matrix[`H${h}`][m] = Object.fromEntries(Object.entries(g).sort((a, b) => b[1].length - a[1].length).map(([k, v]) => [k, cell(v)])); } }
  // setup/trigger, timing, location per candidate (H0 and H2)
  const tclass = (c) => (c.overext_atr < 0.15 ? 'PREMATURE' : c.overext_atr <= 1.0 ? 'CONFIRMED' : 'LATE_CHASED'); const terc = (rows, f) => { const v = rows.map(f).filter((x) => x != null).sort((a, b) => a - b); if (v.length < 9) return null; const c1 = v[Math.floor(v.length / 3)], c2 = v[Math.floor((2 * v.length) / 3)]; return { cuts: [r3(c1), r3(c2)], LOW: cell(rows.filter((x) => f(x) < c1)), MID: cell(rows.filter((x) => f(x) >= c1 && f(x) < c2)), HIGH: cell(rows.filter((x) => f(x) >= c2)) }; };
  D.timing = {}; D.location = {}; D.setup_trigger = {}; for (const name of Object.keys(CAND)) { const rows = candRows(name, S, 2); D.timing[name] = Object.fromEntries(['PREMATURE', 'CONFIRMED', 'LATE_CHASED'].map((k) => { const r = rows.filter((x) => tclass(x.e) === k); const s = stats(r, null, { ci: r.length >= 30 }); return [k, { ...cell(r), mae3_r: s.mae3_r, risk_atr: r.length ? r3(mean(r.map((x) => x.o.d / x.e.atr))) : null, tp2_atr: r.length ? r3(mean(r.map((x) => Math.abs(x.e.geo.tp2 - x.e.geo.entry) / x.e.atr))) : null }]; })); D.location[name] = { risk_atr: terc(rows, (x) => x.o.d / x.e.atr), tp2_atr: terc(rows, (x) => Math.abs(x.e.geo.tp2 - x.e.geo.entry) / x.e.atr), displacement_atr: terc(rows, (x) => x.e.overext_atr), same_side_swing_atr: terc(rows.filter((x) => x.e.row), (x) => (x.e.side === 'BUY' ? x.e.row.slD : -x.e.row.shD)) }; const ev = evaluate(rows, S, { block: false }); D.setup_trigger[name] = ev.n ? captureStats(events, rows, ev.occ) : null; }
  D.setup_trigger.CONTROL = D.control.move_capture; D.events = events.length; return D;
}
function deriveFinalists(D) { const fin = {}; for (const name of Object.keys(CAND)) { const pc = D.hysteresis.per_candidate[name]; const h0 = pc[0]; let best = 0; for (const k of [2, 3]) { const v = pc[k]; if (v.trades >= 100 && v.expectancy_r > (pc[best].expectancy_r ?? -9) && v.expectancy_r >= (h0.expectancy_r ?? -9) && v.max_dd_r <= (h0.max_dd_r ?? 9e9)) best = k; } fin[name] = { hysteresis_k: best, params: P0, dev_trades: pc[best].trades, dev_expectancy_r: pc[best].expectancy_r, h0_expectancy_r: h0.expectancy_r, h0_dd_r: h0.max_dd_r, selected_dd_r: pc[best].max_dd_r }; } return { derived_from: 'DEV', finalists: fin, note: 'hysteresis level chosen by the PREREGISTRATION section 5 rule; params fixed at the pre-registered values' }; }

// ---------- run ----------
const result = { meta: { phase: PHASE, generated_utc: new Date().toISOString(), prereg_sha256: PREREG_SHA, controls: ctrl, rows: ROWLIST.length, signals: C.filter((c) => c.isSig).length, sessions_dev: sessions.DEV.size, sessions_hold: sessions.HOLD.size, split: SPLIT, costs: COSTS, params: P0, hysteresis_family: HK } };
console.log('diagnostics DEV ...'); result.DEV = diagnostics('DEV');
const defPath = join(CFG, 'finalists.json');
if (PHASE === 'DEV') { const defn = deriveFinalists(result.DEV); writeFileSync(defPath, JSON.stringify(defn, null, 1)); result.finalist_definitions = defn; writeFileSync(join(OUT, 'v3_results_DEV_phase.json'), JSON.stringify(result, null, 1)); console.log('DERIVED', JSON.stringify(defn)); console.log('finalists.json sha256', createHash('sha256').update(readFileSync(defPath)).digest('hex')); }
else { const defn = JSON.parse(readFileSync(defPath, 'utf8')); const frozen = readFileSync(join(CFG, 'finalists.sha256'), 'utf8').trim().split(/\s+/)[0]; if (createHash('sha256').update(readFileSync(defPath)).digest('hex') !== frozen) throw new Error('finalists.json does not match its frozen hash'); result.finalist_definitions = defn; result.finalists_sha256 = frozen;
  console.log('diagnostics HOLD ...'); result.HOLD = diagnostics('HOLD');
  result.finalists = {}; for (const S of ['DEV', 'HOLD']) { result.finalists[S] = {}; const events = findEvents(S); const ctl = evaluate(ctlRows(S), S); result.finalists[S].CONTROL = { ...ctl, move_capture: captureStats(events, ctlRows(S), ctl.occ), stress: (() => { const s = stats(seqWalk(ctlRows(S, 'stress')).trades, null, { ci: false }); return { n: s.n, expectancy_r: s.expectancy_r, pf: s.pf }; })(), drift: (() => { const s = stats(seqWalk(ctlRows(S, 'drift')).trades, null, { ci: false }); return { n: s.n, expectancy_r: s.expectancy_r, pf: s.pf }; })(), tiny_cells: tinyCellDependence(ctl.trades, 0), occ: undefined, trades: undefined };
    for (const [name, F] of Object.entries(defn.finalists)) { const rows = candRows(name, S, F.hysteresis_k, F.params); const ev = evaluate(rows, S); const stress = stats(seqWalk(candRows(name, S, F.hysteresis_k, F.params, 'stress')).trades, null, { ci: false }); const drift = stats(seqWalk(candRows(name, S, F.hysteresis_k, F.params, 'drift')).trades, null, { ci: false }); const removed = ctlRows(S).filter((x) => !rows.some((y) => y.e.k === x.e.k)); result.finalists[S][name] = { hysteresis_k: F.hysteresis_k, ...ev, stress: { n: stress.n, expectancy_r: stress.expectancy_r, pf: stress.pf }, drift: { n: drift.n, expectancy_r: drift.expectancy_r, pf: drift.pf }, move_capture: ev.n ? captureStats(events, rows, ev.occ) : null, false_positive: { additional_signals_vs_control: 0, control_signals_removed: removed.length, removed_population: cell(removed) }, tiny_cells: ev.n ? tinyCellDependence(ev.trades, F.hysteresis_k) : null, neighbourhood: neighbourhood(name, S, F.hysteresis_k, F.params), occ: undefined, trades: undefined }; } }
  const H = result.finalists.HOLD, ctl = H.CONTROL; const dec = {}; for (const name of Object.keys(defn.finalists)) { const c = H[name]; const reasons = []; if (!c.n) { dec[name] = { status: 'EMPTY', reasons: ['no trades'] }; continue; } if (!(c.expectancy_r > 0)) reasons.push('(1) normal expectancy<=0'); if (!(c.stress.expectancy_r > 0)) reasons.push('(2) stress expectancy<=0'); if (!(c.pf > 1.10)) reasons.push('(3) PF<=1.10'); if (!(c.expectancy_r >= ctl.expectancy_r + 0.10)) reasons.push('(4) improvement < +0.10 R over CONTROL'); if (!(c.max_dd_r <= ctl.max_dd_r)) reasons.push('(5) DD worse than CONTROL'); if (!(c.n >= 200)) reasons.push('(6) N<200'); if (c.tiny_cells && !c.tiny_cells.pass) reasons.push('(7) tiny-cell dependence'); if (!((c.quarters_positive_share ?? 0) >= 0.6)) reasons.push('(8) quarters positive <60%'); const nbBad = Object.entries(c.neighbourhood).filter(([, v]) => v.classification !== 'ROBUST').map(([k, v]) => `${k}:${v.classification}`); if (nbBad.length) reasons.push(`(9) thresholds not ROBUST (${nbBad.join(', ')})`); if (!(c.ci95_r?.[0] > 0)) reasons.push('(10) trade CI includes 0'); if (!(c.block_ci95_r?.[0] > 0)) reasons.push('(10) session-block CI includes 0'); if (!(result.finalists.DEV[name].expectancy_r > 0)) reasons.push('DEV expectancy<=0'); if (!(c.drift.expectancy_r > 0)) reasons.push('drift expectancy<=0'); const onlyCI = reasons.length > 0 && reasons.every((r) => r.startsWith('(10)')); dec[name] = { status: reasons.length ? (onlyCI ? 'PROMISING_INCONCLUSIVE (fails only the CI requirement)' : 'FAILS_GATE') : 'PASS', reasons, hold_n: c.n, hold_expectancy_r: c.expectancy_r, hold_pf: c.pf, hold_dd_r: c.max_dd_r, ci95_r: c.ci95_r, block_ci95_r: c.block_ci95_r, dev_expectancy_r: result.finalists.DEV[name].expectancy_r }; }
  const passing = Object.entries(dec).filter(([, d]) => d.status === 'PASS').sort((a, b) => (H[b[0]].block_ci95_r?.[0] ?? -9) - (H[a[0]].block_ci95_r?.[0] ?? -9)); const best = passing[0]?.[0] ?? Object.entries(dec).filter(([, d]) => d.hold_n >= 200).sort((a, b) => (b[1].hold_expectancy_r ?? -9) - (a[1].hold_expectancy_r ?? -9))[0]?.[0] ?? null;
  const anyPos = Object.keys(defn.finalists).some((n) => H[n].n >= 200 && H[n].expectancy_r > 0 && !(H[n].ci95_r?.[0] > 0));
  result.decisions = { candidates: dec, passing: passing.map(([k]) => k), best_candidate: best, v3_pass: passing.length > 0, edge_demonstrated: passing.length ? 'YES' : anyPos ? 'INCONCLUSIVE' : 'NO', v3_beats_control: best ? ((H[best].ci95_r?.[0] > ctl.expectancy_r && H[best].max_dd_r <= ctl.max_dd_r) ? 'YES' : H[best].expectancy_r > ctl.expectancy_r ? 'INCONCLUSIVE' : 'NO') : 'NO', demo_eligible: passing.length ? 'YES (subject to parity fixtures)' : 'NO' };
  writeFileSync(join(OUT, 'v3_results.json'), JSON.stringify(result, null, 1)); console.log('DECISIONS', JSON.stringify(result.decisions, null, 1)); }
console.log('written', PHASE);
