/**
 * V12 ENTRY EDGE ISOLATION + REALIZED RISK HARDENING -- study runner (RESEARCH ONLY; HYPOTHETICAL_NOT_EXECUTED).
 * Spec: ../V12_PREREGISTRATION.md (hash asserted). EDGE_PHASE=DEV: Part A + Part B on DEV, candidate tests, buffer derivation ->
 * results/v12_dev.json + configs/v12_freeze.json. EDGE_PHASE=FULL: freeze verified; DEV + HOLDOUT once; replay; decisions.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { canReenter } from '../../../src/engine/capitalHarvest/positionManager.js';
import { simulateTrade, SWAP_PER_NIGHT } from '../../capital_harvest_v9/scripts/harvest.mjs';
import { initState, openPosition, settle, serialize, deserialize } from '../../risk_capital_v10/scripts/risk.mjs';
import { COSTS, loadContext, cfgOf as v10CfgOf } from '../../risk_capital_v10/scripts/sim.mjs';
import { entryFromRow, entryHash, integrateEntry, loadPlatformSpec } from '../../entry_risk_integration_v11/scripts/integrate.mjs';
import { MODELS, STAGES, stagesReached, probe, mirror, attributeLoss, outcomeLabel, timingFeatures, dayBlockCI, summarizeR } from './isolation.mjs';
import { calendarNights, nightsPossible, gapThroughOz, maxSwapLongUsd, envelopeExtraOz, worstPlausibleOz, realizedPnlOz, closureReachable, gapType, BASE_SLIP, SLIPPAGE_BUFFER } from './envelope.mjs';

const PHASE = process.env.EDGE_PHASE === 'FULL' ? 'FULL' : 'DEV';
const HERE = dirname(fileURLToPath(import.meta.url)); const ROOT = join(HERE, '..'); const REPO = join(ROOT, '..', '..');
const OUT = join(ROOT, 'results'); const CFG = join(ROOT, 'configs'); mkdirSync(OUT, { recursive: true }); mkdirSync(CFG, { recursive: true });
const sha = (s) => createHash('sha256').update(s).digest('hex'); const shaFile = (p) => sha(readFileSync(p));
if (shaFile(join(ROOT, 'V12_PREREGISTRATION.md')) !== readFileSync(join(ROOT, 'V12_PREREGISTRATION.sha256'), 'utf8').trim().split(/\s+/)[0]) throw new Error('V12_PREREGISTRATION hash mismatch');
const RISK_LIB = join(REPO, 'research', 'risk_capital_v10', 'scripts', 'risk.mjs'); const INTEG = join(REPO, 'research', 'entry_risk_integration_v11', 'scripts', 'integrate.mjs');
if (shaFile(RISK_LIB) !== '2fc1806a1e14748e430e75e6eb0fa58ce6ebf79ad63f4262d9275c0366e49cd0') throw new Error('V10 risk library changed');
if (shaFile(INTEG) !== '82c1e6c773745b43a5d22087384c8b79e68cb51a70edcb0fb78ba6b09de8cff1') throw new Error('V11 integration layer changed');
const r4 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 10000) / 10000); const r2 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 100) / 100);
const mean = (a) => (a.length ? a.reduce((s, x) => s + x, 0) / a.length : null); const pctl = (a, p) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); return s[Math.min(s.length - 1, Math.floor(p * s.length))]; };
const day = (t) => new Date(t * 1000).toISOString().slice(0, 10); const ci = (c) => ({ mean: r4(c.mean), lo: r4(c.lo), hi: r4(c.hi), n: c.n, days: c.days });
const LOG = join(REPO, 'state', 'xauusd_mt5_real_trade_log.jsonl');
const CTX = loadContext(); const B = CTX.bars; const F = CTX.F; const SPEC = loadPlatformSpec(LOG); const SWAPMAX = maxSwapLongUsd(LOG); const SWAP = SWAPMAX?.usd_per_oz_night ?? null;
const BASE = { kind: 'BASELINE' }; const NORMAL = { spread: COSTS.normal.spread, slip: COSTS.normal.slip }; const ZERO = { spread: 0, slip: 0 };
const simNightsOz = (e, exitBar) => { if (e.side !== 'BUY') return 0; let n = 0; for (let j = e.i + 1; j <= exitBar; j++) if (Math.floor(B[j].time / 86400) !== Math.floor(B[j - 1].time / 86400)) n++; return n * SWAP_PER_NIGHT; };

function loadRows(S) { const rows = []; for (const l of readFileSync(join(REPO, 'research', 'core_pattern_audit_v8', 'results', 'rows', `ALL_${S}.jsonl`), 'utf8').split('\n')) { if (l) rows.push(JSON.parse(l)); } return rows.sort((a, b) => a.i - b.i); }
const entriesOf = (rows) => rows.filter((r) => r.act === 'BUY' || r.act === 'SELL').map(entryFromRow);

// =================== PART A: ENTRY EDGE ISOLATION ===================
/** Standardized probe outcome for every (bar, side) carrying a model-layer trace: NET (NORMAL) and GROSS (zero cost, swap added back). */
function probeOutcomes(rows) { const P = new Map(); for (const row of rows) { if (!row.stB) continue; for (const side of ['BUY', 'SELL']) { const p = probe(B, F, row.i, side); if (!p) continue; const n = simulateTrade(B, F, p, BASE, NORMAL); const g = simulateTrade(B, F, p, BASE, ZERO); if (['NO_DATA', 'INVALID'].includes(n.status) || ['NO_DATA', 'INVALID'].includes(g.status)) continue; const R = Math.abs(p.entry - p.sl);
  P.set(`${row.i}|${side}`, { d: day(row.t), net: n.r, gross: (g.pnl_usd + simNightsOz(p, g.exitBar)) / R, mfe: n.mfe_r, mae: n.mae_r, tgt: n.exit === 'TARGET_170R' }); } } return P; }
function stageAnalysis(rows, P) {
  const base = {}; for (const side of ['BUY', 'SELL']) { const xs = [...P.entries()].filter(([k]) => k.endsWith(side)).map(([, v]) => v); base[side] = { n: xs.length, gross: mean(xs.map((x) => x.gross)), net: mean(xs.map((x) => x.net)), ci_gross: ci(dayBlockCI(xs.map((x) => ({ d: x.d, x: x.gross })))) }; }
  const opp = (s) => (s === 'BUY' ? 'SELL' : 'BUY'); const per = {}; const pooled = Object.fromEntries(STAGES.map((st) => [st, []]));
  for (const m of MODELS) { per[m] = {}; for (const side of ['BUY', 'SELL']) { per[m][side] = {}; const reach = rows.map((row) => [row, stagesReached(row, m, side)]);
    for (const st of STAGES) { const obs = []; const dir = []; for (const [row, r] of reach) { if (!r[st]) continue; const o = P.get(`${row.i}|${side}`); if (!o) continue; obs.push(o); const q = P.get(`${row.i}|${opp(side)}`); if (q) dir.push({ d: o.d, x: o.gross - q.gross }); pooled[st].push({ d: o.d, x: o.gross - base[side].gross }); }
      const s = summarizeR(obs.map((o) => o.net), { mfe: obs.map((o) => o.mfe), mae: obs.map((o) => o.mae), target: obs.map((o) => o.tgt) });
      per[m][side][st] = { n: obs.length, days: new Set(obs.map((o) => o.d)).size, net_r: r4(s.expectancy_r), gross_r: r4(mean(obs.map((o) => o.gross))), win_rate: r4(s.win_rate), pf: r4(s.pf), mfe_r: r4(s.mfe_r), mae_r: r4(s.mae_r), reach_170: r4(s.reach_170), edge_vs_baseline: ci(dayBlockCI(obs.map((o) => ({ d: o.d, x: o.gross - base[side].gross })))), direction_value: ci(dayBlockCI(dir)) }; } } }
  const pool = Object.fromEntries(STAGES.map((st) => [st, ci(dayBlockCI(pooled[st]))])); const trans = {}; for (let k = 1; k < STAGES.length; k++) trans[`${STAGES[k - 1]}->${STAGES[k]}`] = ci(dayBlockCI(pooled[STAGES[k]], pooled[STAGES[k - 1]]));
  return { baseline: Object.fromEntries(Object.entries(base).map(([k, v]) => [k, { n: v.n, gross_r: r4(v.gross), net_r: r4(v.net), ci_gross: v.ci_gross }])), per_model: per, pooled_edge: pool, pooled_transitions: trans };
}
/** Every valid entry with its OWN geometry: NET (NORMAL) and GROSS outcome, MFE/MAE, exit; mirror outcome (hindsight only). */
function entryOutcomes(ents) { const O = new Map(); for (const e of ents) { const n = simulateTrade(B, F, e, BASE, NORMAL); if (['NO_DATA', 'INVALID'].includes(n.status)) continue; const g = simulateTrade(B, F, e, BASE, ZERO); const R = Math.abs(e.entry - e.sl); const mr = simulateTrade(B, F, mirror(e), BASE, NORMAL);
  O.set(e.id, { d: day(e.t), net: n.r, gross: (g.pnl_usd + simNightsOz(e, g.exitBar)) / R, mfe: n.mfe_r, mae: n.mae_r, exit: n.exit, exitBar: n.exitBar, tgt: n.exit === 'TARGET_170R', mirror_win: mr.exit === 'TARGET_170R', pnl_oz: n.pnl_usd }); } return O; }
function walkTrades(ents, O) { let exitBar = -1, last = null, lastLoss = false; const out = []; for (const e of ents) { const o = O.get(e.id); if (!o || e.i <= exitBar) continue; if (!canReenter({ signal: e, exitBar, lastTrade: last, lastExitWasLoss: lastLoss }).ok) continue; out.push(e); exitBar = o.exitBar; last = { i: e.i, model: e.model, side: e.side, anchor: e.anchor }; lastLoss = o.pnl_oz <= 0; } return out; }
function strategyBreakdown(rows, ents, O, trades) { const res = {}; for (const m of [...MODELS, 'ALL']) { const sel = (x) => m === 'ALL' || x.model === m; const cnt = (st) => rows.reduce((s, row) => s + ['BUY', 'SELL'].filter((side) => (m === 'ALL' ? MODELS.some((mm) => stagesReached(row, mm, side)[st]) : stagesReached(row, m, side)[st])).length, 0);
  const tr = trades.filter(sel).map((e) => O.get(e.id)); const en = ents.filter(sel).map((e) => O.get(e.id)).filter(Boolean); const st = summarizeR(tr.map((o) => o.net), { mfe: tr.map((o) => o.mfe), mae: tr.map((o) => o.mae), target: tr.map((o) => o.tgt) }); const se = summarizeR(en.map((o) => o.net));
  res[m] = { observations: rows.filter((r) => r.stB).length, valid_patterns: cnt('PATTERN'), valid_setups: cnt('SETUP'), valid_triggers: cnt('TRIGGER'), valid_directions: cnt('DIRECTION'), valid_entries: ents.filter(sel).length, trades: tr.length, wins: st.wins, losses: st.losses, expectancy_r: r4(st.expectancy_r), gross_expectancy_r: r4(mean(tr.map((o) => o.gross))), pf: r4(st.pf), win_rate: r4(st.win_rate), mfe_r: r4(st.mfe_r), mae_r: r4(st.mae_r), reach_170: r4(st.reach_170), max_dd_r: r2(st.max_dd_r), net_r: r2(st.net_r), entries_expectancy_r: r4(se.expectancy_r), entries_pf: r4(se.pf), trades_ci: ci(dayBlockCI(tr.map((o) => ({ d: o.d, x: o.net })))) }; } return res; }
function attribution(S, byI, trades, O) { const recs = []; for (const e of trades) { const o = O.get(e.id); if (o.net > 0) continue; const cls = attributeLoss(byI.get(e.i), e); const lab = cls === 'VALID_LOSING_TRADE' ? outcomeLabel(o.mfe) : null; recs.push({ id: e.id, model: e.model, side: e.side, r: r4(o.net), mfe_r: r4(o.mfe), exit: o.exit, class: cls, outcome_label: lab, mirror_would_win: o.mirror_win, direction_outcome: lab === 'ADVERSE_FROM_START' ? (o.mirror_win ? 'OUTCOME_DIRECTION_MISS' : 'NOISE_BOTH_SIDES_LOSE') : lab ? 'DIRECTION_RIGHT_VALID_LOSS' : null }); }
  writeFileSync(join(OUT, `loss_attribution_${S}.jsonl`), recs.map((x) => JSON.stringify(x)).join('\n') + '\n');
  const cnt = (xs, k) => xs.reduce((g, x) => { g[x[k]] = (g[x[k]] ?? 0) + 1; return g; }, {}); const byModel = Object.fromEntries(MODELS.map((m) => { const xs = recs.filter((x) => x.model === m); return [m, { losses: xs.length, class: cnt(xs, 'class'), outcome: cnt(xs.filter((x) => x.outcome_label), 'outcome_label'), direction: cnt(xs.filter((x) => x.direction_outcome), 'direction_outcome') }]; }));
  return { losing_trades: recs.length, class: cnt(recs, 'class'), outcome_label: cnt(recs.filter((x) => x.outcome_label), 'outcome_label'), direction_outcome: cnt(recs.filter((x) => x.direction_outcome), 'direction_outcome'), by_model: byModel, file: `results/loss_attribution_${S}.jsonl` }; }
const FEATURES = ['bars_from_origin', 'anchor_dist_atr', 'sl_atr', 'bo_bars_since_event', 'mr_bars_since_sweep'];
function timingCuts(byI, ents) { const cuts = {}; for (const m of MODELS) { cuts[m] = {}; const fs = ents.filter((e) => e.model === m).map((e) => timingFeatures(byI.get(e.i), e)); for (const f of FEATURES) { const v = fs.map((x) => x[f]).filter(Number.isFinite); cuts[m][f] = v.length >= 20 ? [0.25, 0.5, 0.75].map((p) => pctl(v, p)) : null; } } return cuts; }
function timing(byI, ents, O, cuts) { const res = {}; for (const m of MODELS) { res[m] = {}; const xs = ents.filter((e) => e.model === m && O.has(e.id)).map((e) => ({ f: timingFeatures(byI.get(e.i), e), o: O.get(e.id) }));
  for (const f of FEATURES) { const c = cuts[m][f]; if (!c) continue; const q = (v) => (v <= c[0] ? 'Q1' : v <= c[1] ? 'Q2' : v <= c[2] ? 'Q3' : 'Q4'); res[m][f] = { cuts: c.map((v) => r4(v)), bins: Object.fromEntries(['Q1', 'Q2', 'Q3', 'Q4'].map((k) => { const ys = xs.filter((x) => Number.isFinite(x.f[f]) && q(x.f[f]) === k); return [k, { n: ys.length, net_r: r4(mean(ys.map((y) => y.o.net))), gross_r: r4(mean(ys.map((y) => y.o.gross))) }]; })) }; } } return res; }
const CANDIDATES = { C1_LOCATION_MARGINAL: (f) => f.anchor_dist_atr != null && f.anchor_dist_atr >= 2.0 && f.anchor_dist_atr <= 2.5 + 0.01, C2_LATE_TRIGGER: (f, c) => c && f.bars_from_origin != null && f.bars_from_origin > c[2], C3_EARLY_TRIGGER: (f, c) => c && f.bars_from_origin != null && f.bars_from_origin <= c[0] };
function candidateTests(byI, ents, O, cuts) { const res = {}; for (const [name, fn] of Object.entries(CANDIDATES)) { const g = [], rest = []; for (const e of ents) { const o = O.get(e.id); if (!o) continue; const f = timingFeatures(byI.get(e.i), e); (fn(f, cuts[e.model]?.bars_from_origin) ? g : rest).push({ d: o.d, x: o.net }); }
  const c = dayBlockCI(g, rest); res[name] = { n_group: g.length, n_rest: rest.length, mean_group: r4(mean(g.map((x) => x.x))), mean_rest: r4(mean(rest.map((x) => x.x))), diff: ci(c), pass: g.length >= 30 && c.hi != null && c.hi < 0 }; } return res; }
function partA(S, rows, frozen) { const ents = entriesOf(rows); const byI = new Map(rows.map((r) => [r.i, r])); const P = probeOutcomes(rows); const O = entryOutcomes(ents); const trades = walkTrades(ents, O); const cuts = frozen?.timing_cuts ?? timingCuts(byI, ents);
  return { cuts, out: { entries: ents.length, rows: rows.length, trace_rows: rows.filter((r) => r.stB).length, probes: P.size, stages: stageAnalysis(rows, P), strategy: strategyBreakdown(rows, ents, O, trades), attribution: attribution(S, byI, trades, O), timing: timing(byI, ents, O, cuts), candidates: candidateTests(byI, ents, O, cuts), entry_ci: ci(dayBlockCI(ents.filter((e) => O.has(e.id)).map((e) => ({ d: O.get(e.id).d, x: O.get(e.id).net })))) } }; }

// =================== PART B: REALIZED RISK HARDENING ===================
const RMODELS = ['SCENARIO_normal', 'SCENARIO_moderate', 'SCENARIO_severe', 'REALISTIC_normal', 'REALISTIC_moderate', 'REALISTIC_severe']; const RISKS = [0.001, 0.0025, 0.005, 0.01]; const ACCOUNTS = [1000, 5000, 10000];
function riskOutcomes(ents) { const O = {}; for (const [k, c] of Object.entries(COSTS)) { let stops = 0; O[k] = new Map(); for (const e of ents) { const o = simulateTrade(B, F, e, BASE, { spread: c.spread, slip: c.slip }); if (['NO_DATA', 'INVALID'].includes(o.status)) continue; const R = Math.abs(e.entry - e.sl); let det = 0; if (c.gapEvery && (o.exit === 'BROKER_SL' || o.exit === 'THESIS_INVALIDATION')) { stops++; if (stops % c.gapEvery === 0) det = c.gapR * R; }
  O[k].set(e.id, { pnl_oz: o.pnl_usd - det, exit: o.exit, exitBar: o.exitBar, exitT: B[o.exitBar].time + 300, R, detGap: det, simSwap: simNightsOz(e, o.exitBar), calNights: calendarNights(e.t + 300, B[o.exitBar].time + 300), gapThrough: o.exit === 'BROKER_SL' ? gapThroughOz({ bars: B, exitBar: o.exitBar, side: e.side, entry: e.entry, R }) : 0, nPossible: nightsPossible(B, e.i), closure: closureReachable(B, e.i), exitGap: gapType(B, o.exitBar) }); } } return O; }
function gapEvidence(ents, OR) { const xs = ents.map((e) => OR.normal.get(e.id)).filter((o) => o && o.exit === 'BROKER_SL'); const g = xs.map((o) => o.gapThrough / o.R); const grp = (f) => { const ys = xs.filter(f); const gy = ys.map((o) => o.gapThrough / o.R); return { exits: ys.length, with_gap_through: gy.filter((x) => x > 0).length, max_r: r4(Math.max(0, ...gy)), over_05r: gy.filter((x) => x > 0.5).length }; };
  return { broker_exits: xs.length, with_gap_through: g.filter((x) => x > 0).length, share: r4(g.filter((x) => x > 0).length / Math.max(1, g.length)), p99_r: r4(pctl(g, 0.99)), p995_r: r4(pctl(g, 0.995)), max_r: r4(Math.max(0, ...g)), max_usd_oz: r2(Math.max(0, ...xs.map((o) => o.gapThrough))), by_exit_gap_type: { IN_SESSION: grp((o) => o.exitGap === 'IN_SESSION'), SESSION: grp((o) => o.exitGap === 'SESSION'), CLOSURE: grp((o) => o.exitGap === 'CLOSURE') }, by_entry_closure_reachable: { YES: grp((o) => o.closure), NO: grp((o) => !o.closure) }, session_max_r: r4(Math.max(0, ...xs.filter((o) => o.exitGap !== 'CLOSURE').map((o) => o.gapThrough / o.R))), closure_max_r: r4(Math.max(0, ...xs.filter((o) => o.exitGap === 'CLOSURE').map((o) => o.gapThrough / o.R))) }; }
function riskWalk(ents, OR, rmodel, sizing, r, A, buf, { keep = false, startState = null, from = 0, upto = null } = {}) {
  const [kind, cost] = rmodel.split('_'); const O = OR[cost]; const S = COSTS[cost]; let W = startState ? deserialize(serialize(startState)) : { ctrl: initState(A), exitBar: -1, last: null, lastLoss: false, peak: A, maxDD: 0, rec: [] };
  for (let k = from; k < (upto ?? ents.length); k++) { const e = ents[k]; const o = O.get(e.id); if (!o) { W.rec.push({ id: e.id, outcome: 'NOT_EVALUABLE' }); continue; } if (e.i <= W.exitBar) { W.rec.push({ id: e.id, outcome: 'EXPOSURE_BLOCKED' }); continue; } if (!canReenter({ signal: e, exitBar: W.exitBar, lastTrade: W.last, lastExitWasLoss: W.lastLoss }).ok) { W.rec.push({ id: e.id, outcome: 'EXPOSURE_BLOCKED' }); continue; }
    const tiered = sizing === 'H2' || sizing === 'H3' || sizing === 'H0'; const gapR = tiered ? (o.closure ? buf.closure_gap_buffer_r : buf.session_gap_buffer_r) : buf.gap_buffer_r; // H0 is sized without buffers; its envelope is only reported
    const env = envelopeExtraOz({ side: e.side, R: o.R, nightsPossible: o.nPossible, swapRate: buf.swap_rate, slipBuffer: buf.slip_buffer, gapBufferR: gapR }); if (!env.ok) { W.rec.push({ id: e.id, outcome: 'FAIL_CLOSED', reason: env.reason }); continue; }
    if (sizing === 'H2' && o.closure) { W.rec.push({ id: e.id, model: e.model, R: o.R, outcome: 'RISK_REJECTED', reason: 'CLOSURE_GAP_EXPOSURE', hash_ok: true }); continue; }
    const cfg = { ...v10CfgOf('PCT', r, cost, SPEC), spec: SPEC, slipAllowance: sizing === 'H0' ? BASE_SLIP : BASE_SLIP + env.total };
    const out = integrateEntry(W.ctrl, e, { equity: W.ctrl.equity, spread: S.spread, quoteAgeSec: 0, signalAgeSec: 0, nowT: e.t + 300, spec: SPEC, cfg }); W.ctrl = out.state; const rec = out.record;
    if (rec.outcome !== 'RISK_ACCEPTED') { W.rec.push({ id: e.id, model: e.model, R: o.R, outcome: rec.outcome, reason: rec.reason, hash_ok: rec.entry_hash_after === entryHash(e) }); continue; }
    const pnlOz = realizedPnlOz({ model: kind, pnlOz: o.pnl_oz, side: e.side, simSwapOz: o.simSwap, detGapOz: o.detGap, calNights: o.calNights, swapRate: buf.swap_rate, exit: o.exit, gapThrough: o.gapThrough });
    const lots = rec.lots; const pnl = pnlOz * lots * SPEC.contract_size; const eq = W.ctrl.equity; const approved = eq * r; const maxPlaus = lots * SPEC.contract_size * worstPlausibleOz({ R: o.R, spread: S.spread, extra: env });
    W.ctrl = openPosition(W.ctrl, { id: e.id }, { lots, actual_risk: rec.planned_risk_usd }); W.ctrl = settle(W.ctrl, { pnlUsd: pnl, exitT: o.exitT }, cfg);
    W.rec.push({ id: e.id, model: e.model, side: e.side, R: o.R, outcome: 'RISK_ACCEPTED', lots, planned: rec.planned_risk_usd, approved, max_plausible: maxPlaus, pnl, mult: pnl < 0 ? -pnl / approved : 0, calNights: o.calNights, gapThrough: o.gapThrough, exit: o.exit, hash_ok: rec.entry_hash_after === entryHash(e) });
    W.peak = Math.max(W.peak, W.ctrl.equity); W.maxDD = Math.max(W.maxDD, (W.peak - W.ctrl.equity) / W.peak); W.exitBar = o.exitBar; W.last = { i: e.i, model: e.model, side: e.side, anchor: e.anchor }; W.lastLoss = pnl <= 0; }
  if (keep) return W; const acc = W.rec.filter((x) => x.outcome === 'RISK_ACCEPTED'); const los = acc.filter((x) => x.pnl < 0); const m = los.map((x) => x.mult);
  return { trades: acc.length, losing: los.length, min_lot_rejections: W.rec.filter((x) => x.reason === 'RISK_BELOW_MIN_LOT').length, closure_rejections: W.rec.filter((x) => x.reason === 'CLOSURE_GAP_EXPOSURE').length, risk_rejected: W.rec.filter((x) => x.outcome === 'RISK_REJECTED').length, fail_closed: W.rec.filter((x) => x.outcome === 'FAIL_CLOSED').length, exceed_share: r4(m.filter((x) => x > 1 + 1e-9).length / Math.max(1, m.length)), exceed_105_share: r4(m.filter((x) => x > 1.05).length / Math.max(1, m.length)), exceed_110_share: r4(m.filter((x) => x > 1.10).length / Math.max(1, m.length)), max_mult: r4(Math.max(0, ...m)), p99_mult: r4(pctl(m, 0.99)), mean_loss_mult: r4(mean(m)), max_plausible_above_approved_share: r4(acc.filter((x) => x.max_plausible > x.approved + 1e-9).length / Math.max(1, acc.length)), planned_above_approved: acc.filter((x) => x.planned > x.approved + 1e-9).length, end: r2(W.ctrl.equity), return_pct: r4(W.ctrl.equity / A - 1), max_dd_pct: r4(W.maxDD), entry_hash_mismatches: W.rec.filter((x) => x.hash_ok === false).length, swap_nights_total: acc.reduce((s, x) => s + (x.side === 'BUY' ? x.calNights : 0), 0), gap_through_trades: acc.filter((x) => x.gapThrough > 0).length };
}
function swapStudy(ents, OR, buf) { const cls = (n) => (n === 0 ? 'INTRADAY' : n === 1 ? 'OVERNIGHT' : 'WEEKEND_OR_MULTI'); const res = {}; for (const c of ['INTRADAY', 'OVERNIGHT', 'WEEKEND_OR_MULTI']) res[c] = { n: 0, buy: 0, losing: 0, planned_oz: [], swap_oz: [], mult: [] };
  for (const e of ents) { const o = OR.normal.get(e.id); if (!o) continue; const k = cls(o.calNights); const x = res[k]; x.n++; if (e.side === 'BUY') x.buy++; const planned = 1.5 * o.R + COSTS.normal.spread + BASE_SLIP; const swap = e.side === 'BUY' ? o.calNights * buf.swap_rate : 0; x.planned_oz.push(planned); x.swap_oz.push(swap);
    const pnl = realizedPnlOz({ model: 'REALISTIC', pnlOz: o.pnl_oz, side: e.side, simSwapOz: o.simSwap, detGapOz: o.detGap, calNights: o.calNights, swapRate: buf.swap_rate, exit: o.exit, gapThrough: o.gapThrough }); if (pnl < 0) { x.losing++; x.mult.push(-pnl / planned); } }
  return Object.fromEntries(Object.entries(res).map(([k, x]) => [k, { n: x.n, buy: x.buy, losing: x.losing, planned_oz_mean: r4(mean(x.planned_oz)), swap_oz_mean: r4(mean(x.swap_oz)), swap_share_of_planned: r4(mean(x.swap_oz) / mean(x.planned_oz)), exposure_oz_mean: r4(mean(x.planned_oz) + mean(x.swap_oz)), mult_mean: r4(mean(x.mult)), mult_p99: r4(pctl(x.mult, 0.99)), mult_max: r4(Math.max(0, ...x.mult)), exceed_share: r4(x.mult.filter((v) => v > 1 + 1e-9).length / Math.max(1, x.mult.length)) }])); }
function slipStudy(ents, OR) { const res = {}; for (const c of Object.keys(COSTS)) { const mult = []; for (const e of ents) { const o = OR[c].get(e.id); if (!o || o.pnl_oz + o.detGap >= 0) continue; const planned = 1.5 * o.R + COSTS[c].spread + BASE_SLIP; mult.push(-(o.pnl_oz + o.detGap + o.simSwap) / planned); } res[c] = { slippage: COSTS[c].slip, allowance: BASE_SLIP, losing: mult.length, exceed_share: r4(mult.filter((v) => v > 1 + 1e-9).length / Math.max(1, mult.length)), max_mult: r4(Math.max(0, ...mult)) }; } return res; }
function partB(S, ents, buf) { const OR = riskOutcomes(ents); const grid = {}; for (const sz of ['H0', 'H1', 'H2', 'H3']) { grid[sz] = {}; for (const r of RISKS) { grid[sz][r] = {}; for (const A of ACCOUNTS) { grid[sz][r][A] = {}; for (const rm of RMODELS) grid[sz][r][A][rm] = riskWalk(ents, OR, rm, sz, r, A, buf); } } }
  const ref = riskWalk(ents, OR, 'REALISTIC_normal', 'H3', 0.005, 10000, buf, { keep: true }); const ref0 = riskWalk(ents, OR, 'REALISTIC_normal', 'H0', 0.005, 10000, buf, { keep: true }); const ref1 = riskWalk(ents, OR, 'REALISTIC_normal', 'H1', 0.005, 10000, buf, { keep: true });
  const slq = (W) => { const ev = W.rec.filter((x) => x.outcome === 'RISK_ACCEPTED' || x.reason === 'RISK_BELOW_MIN_LOT'); const Rs = ev.map((x) => x.R); const cuts = [0.25, 0.5, 0.75].map((p) => pctl(Rs, p)); const q = (R) => (R <= cuts[0] ? 'Q1' : R <= cuts[1] ? 'Q2' : R <= cuts[2] ? 'Q3' : 'Q4'); return { cuts: cuts.map(r2), by_quartile: Object.fromEntries(['Q1', 'Q2', 'Q3', 'Q4'].map((k) => { const xs = ev.filter((x) => q(x.R) === k); return [k, { evaluated: xs.length, min_lot_rejected: xs.filter((x) => x.reason === 'RISK_BELOW_MIN_LOT').length }]; })), by_model: Object.fromEntries(MODELS.map((m) => { const xs = ev.filter((x) => x.model === m); return [m, { evaluated: xs.length, min_lot_rejected: xs.filter((x) => x.reason === 'RISK_BELOW_MIN_LOT').length }]; })) }; };
  writeFileSync(join(OUT, `risk_records_reference_${S}.jsonl`), ref.rec.map((x) => JSON.stringify(x)).join('\n') + '\n');
  return { entries: ents.length, gap: gapEvidence(ents, OR), swap: swapStudy(ents, OR, buf), slippage: slipStudy(ents, OR), grid, min_lot_reference: { H0: slq(ref0), H1: slq(ref1), H3: slq(ref) }, closure_reachable_entries: ents.filter((e) => OR.normal.get(e.id)?.closure).length, nights_possible: { buy_entries: ents.filter((e) => e.side === 'BUY').length, dist: ents.filter((e) => e.side === 'BUY').reduce((g, e) => { const n = OR.normal.get(e.id)?.nPossible; if (n != null) g[n] = (g[n] ?? 0) + 1; return g; }, {}) }, _OR: OR };
}

// =================== phases ===================
const FILLS = [{ src: 'REAL', side: 'SELL', slippage: 0, spread: 0.26, entry_drift: 1.32 }, { src: 'REAL', side: 'BUY', slippage: 0, spread: 0.26, entry_drift: 0.10 }, { src: 'DEMO', side: 'BUY', slippage: -0.06, spread: 0.26, entry_drift: 0.68 }];
const strip = (o) => JSON.parse(JSON.stringify(o, (k, v) => (k.startsWith('_') ? undefined : v)));
const DEVROWS = loadRows('DEV');
if (PHASE === 'DEV') {
  const A = partA('DEV', DEVROWS, null); const ents = entriesOf(DEVROWS); const OR = riskOutcomes(ents); const g = gapEvidence(ents, OR);
  const buf = { slip_buffer: SLIPPAGE_BUFFER, gap_buffer_r: g.p99_r ?? 0, session_gap_buffer_r: g.session_max_r ?? 0, closure_gap_buffer_r: g.closure_max_r ?? 0, swap_rate: SWAP, swap_source: 'max |swap_long| in the platform record history', slip_source: 'ASSUMPTION: MODERATE level (3 recorded fills, no stop-out fill data)' };
  const Bd = partB('DEV', ents, buf); const passed = Object.entries(A.out.candidates).filter(([, v]) => v.pass).map(([k]) => k);
  writeFileSync(join(OUT, 'v12_dev.json'), JSON.stringify(strip({ phase: 'DEV', generated_utc: new Date().toISOString(), spec: SPEC, fills_evidence: FILLS, partA: A.out, partB: Bd, buffers: buf }), null, 1));
  const freeze = { frozen_utc: new Date().toISOString(), prereg_sha: shaFile(join(ROOT, 'V12_PREREGISTRATION.md')), isolation_sha: shaFile(join(HERE, 'isolation.mjs')), envelope_sha: shaFile(join(HERE, 'envelope.mjs')), study_sha: shaFile(join(HERE, 'v12_study.mjs')), v11_integrate_sha: shaFile(INTEG), v10_risk_sha: shaFile(RISK_LIB), buffers: buf, timing_cuts: A.cuts, candidates_dev: A.out.candidates, candidates_frozen: passed };
  writeFileSync(join(CFG, 'v12_freeze.json'), JSON.stringify(freeze, null, 1)); console.log('pooled transitions', JSON.stringify(A.out.stages.pooled_transitions)); console.log('pooled edge', JSON.stringify(A.out.stages.pooled_edge)); console.log('candidates', JSON.stringify(A.out.candidates)); console.log('attribution', JSON.stringify(A.out.attribution.class), JSON.stringify(A.out.attribution.direction_outcome)); console.log('buffers', JSON.stringify(buf), 'gap', JSON.stringify(g));
} else {
  const fz = JSON.parse(readFileSync(join(CFG, 'v12_freeze.json'), 'utf8')); for (const [k, p] of [['prereg_sha', join(ROOT, 'V12_PREREGISTRATION.md')], ['isolation_sha', join(HERE, 'isolation.mjs')], ['envelope_sha', join(HERE, 'envelope.mjs')], ['study_sha', join(HERE, 'v12_study.mjs')], ['v11_integrate_sha', INTEG], ['v10_risk_sha', RISK_LIB]]) if (fz[k] !== shaFile(p)) throw new Error(`freeze violated: ${k}`);
  const HOLDROWS = loadRows('HOLD'); const res = { phase: 'FULL', generated_utc: new Date().toISOString(), freeze: fz, spec: SPEC, fills_evidence: FILLS, splits: {} };
  for (const [S, rows] of [['DEV', DEVROWS], ['HOLD', HOLDROWS]]) { const A = partA(S, rows, fz); const Bp = partB(S, entriesOf(rows), fz.buffers); res.splits[S] = { partA: A.out, partB: strip(Bp) }; if (S === 'HOLD') res._holdOR = Bp._OR; }
  // ---- candidate holdout test (frozen list only) ----
  res.candidates_holdout = Object.fromEntries(Object.entries(res.splits.HOLD.partA.candidates).map(([k, v]) => [k, { frozen_on_dev: fz.candidates_frozen.includes(k), hold: v, supported: fz.candidates_frozen.includes(k) && v.pass }]));
  // ---- risk replay: determinism + restart (HOLD, H1, PCT 0.50 %, 10,000 USD, REALISTIC_normal) ----
  const hEnts = entriesOf(HOLDROWS); const OR = res._holdOR; delete res._holdOR; const runRef = (o = {}) => riskWalk(hEnts, OR, 'REALISTIC_normal', 'H3', 0.005, 10000, fz.buffers, { keep: true, ...o }); const a = runRef(), b = runRef(); const half = Math.floor(hEnts.length / 2); const first = runRef({ upto: half }); const resumed = runRef({ startState: deserialize(serialize(first)), from: half });
  res.risk_replay = { deterministic: sha(JSON.stringify(a.rec)) === sha(JSON.stringify(b.rec)), restart_equals_uninterrupted: sha(JSON.stringify(resumed.rec)) === sha(JSON.stringify(a.rec)), restart_split_at: half, records: a.rec.length, identity_ok: a.rec.length === hEnts.length && new Set(a.rec.map((x) => x.id)).size === hEnts.length };
  // ---- H0 must reproduce V11 (same entries, sizes, outcomes) for the scenario models ----
  const v11 = JSON.parse(readFileSync(join(REPO, 'research', 'entry_risk_integration_v11', 'results', 'v11_results_FULL.json'), 'utf8')); const par = [];
  for (const S of ['DEV', 'HOLD']) for (const r of RISKS) for (const A2 of ACCOUNTS) for (const c of Object.keys(COSTS)) { const x = v11.splits[S].grid[A2][`PCT_${r}`][c]; const y = res.splits[S].partB.grid.H0[r][A2][`SCENARIO_${c}`]; par.push({ S, r, A: A2, c, v11_end: x.end, v12_end: y.end, same: x.end === y.end && x.trades === y.trades }); }
  res.integrity = { v11_parity_all_same: par.every((x) => x.same), v11_parity_mismatches: par.filter((x) => !x.same), entry_hash_mismatches: ['DEV', 'HOLD'].reduce((s2, S) => s2 + Object.values(res.splits[S].partB.grid).flatMap((g2) => Object.values(g2).flatMap((g3) => Object.values(g3).flatMap((g4) => Object.values(g4)))).reduce((t, x) => t + x.entry_hash_mismatches, 0), 0) };
  // ---- decisions (pre-registered) ----
  const st = (S) => res.splits[S].partA.stages; const trans = Object.keys(st('DEV').pooled_transitions).filter((k) => st('DEV').pooled_transitions[k].hi < 0 && st('HOLD').pooled_transitions[k].hi < 0);
  const losses = ['DEV', 'HOLD'].reduce((g, S) => { for (const [k, v] of Object.entries(res.splits[S].partA.attribution.class)) g[k] = (g[k] ?? 0) + v; return g; }, {}); const nLoss = Object.values(losses).reduce((a2, b2) => a2 + b2, 0);
  const ruleErr = Object.entries(losses).filter(([k, v]) => !['VALID_LOSING_TRADE', 'UNKNOWN'].includes(k) && v / nLoss >= 0.10).map(([k]) => k);
  const edgeStages = STAGES.filter((s2) => st('DEV').pooled_edge[s2].lo > 0 && st('HOLD').pooled_edge[s2].lo > 0);
  const anySupported = Object.values(res.candidates_holdout).some((x) => x.supported); const anyFrozen = fz.candidates_frozen.length > 0; const fewTrades = ['DEV', 'HOLD'].some((S) => res.splits[S].partA.strategy.ALL.trades < 30);
  const ENTRY_EDGE_STATUS = fewTrades ? 'INCONCLUSIVE' : anySupported ? 'EDGE_CORRECTION_SUPPORTED' : anyFrozen ? 'EDGE_CORRECTION_NOT_SUPPORTED' : (trans.length || ruleErr.length) ? 'EDGE_FAILURE_ISOLATED' : 'EDGE_FAILURE_NOT_ISOLATED';
  const statusOf = (sz) => { const G = res.splits.HOLD.partB.grid[sz]; const cells = (rm) => RISKS.flatMap((r) => ACCOUNTS.map((A2) => G[r][A2][rm])).filter((x) => x.losing >= 30); const nm = ['REALISTIC_normal', 'REALISTIC_moderate'].every((rm) => cells(rm).every((x) => x.exceed_share <= 0.01 && x.max_mult <= 1.10)); const sv = cells('REALISTIC_severe').every((x) => x.max_mult <= 1.50); const any = cells('REALISTIC_normal').length > 0; return { nm, sv, any, n: cells('REALISTIC_normal').length }; };
  const P3 = statusOf('H3'); const nmOk = P3.nm, sevOk = P3.sv, anyCells = P3.any; const cells = () => ({ length: P3.n });
  const buffersCalibrated = !String(fz.buffers.slip_source).startsWith('ASSUMPTION'); // pre-registration B4: HARDENED needs every buffer evidence-calibrated
  const statusName = (x) => (!x.any ? 'RISK_INCONCLUSIVE' : !x.nm ? 'RISK_FAILED' : x.sv && buffersCalibrated ? 'RISK_HARDENED' : 'RISK_PARTIALLY_HARDENED');
  const RISK_STATUS = !anyCells ? 'RISK_INCONCLUSIVE' : !nmOk ? 'RISK_FAILED' : sevOk && buffersCalibrated ? 'RISK_HARDENED' : 'RISK_PARTIALLY_HARDENED'; const statusBySizing = Object.fromEntries(['H1', 'H2', 'H3'].map((sz) => [sz, { ...statusOf(sz), status: statusName(statusOf(sz)) }]));
  res.decision = { ENTRY_EDGE_STATUS, ENTRY_FAILURE_STAGE: trans.length ? trans.join(', ') : ruleErr.length ? ruleErr.join(', ') : 'NO DETERMINISTIC FAILURE IDENTIFIED', stage_with_replicated_gross_edge: edgeStages, rule_error_classes_ge_10pct: ruleErr, losing_trades_classified: nLoss, loss_classes: losses, ENTRY_EDGE_REMAINING_PROBLEM: anySupported ? 'NO' : 'YES', RISK_STATUS, risk_criteria: { primary_sizing: 'H3 (Amendment 1)', normal_moderate_ok: nmOk, severe_ok: sevOk, cells_evaluated: cells().length, buffers_calibrated: buffersCalibrated }, risk_status_by_sizing: statusBySizing, SUPPORTED_RISK_PERCENTAGE: 'UNRESOLVED' };
  writeFileSync(join(OUT, 'v12_results_FULL.json'), JSON.stringify(res, null, 1)); console.log('decision', JSON.stringify(res.decision)); console.log('integrity', JSON.stringify({ v11_parity_all_same: res.integrity.v11_parity_all_same, entry_hash_mismatches: res.integrity.entry_hash_mismatches })); console.log('risk_replay', JSON.stringify(res.risk_replay)); console.log('candidates_holdout', JSON.stringify(res.candidates_holdout));
}
