/**
 * V8 CORE PATTERN EXECUTION AUDIT -- evaluation (RESEARCH ONLY). Spec: ../V8_PREREGISTRATION.md (hash asserted).
 * EDGE_PHASE=DEV evaluates DEV and writes configs/v8_freeze.json; EDGE_PHASE=FULL verifies the freeze, then evaluates DEV + HOLDOUT once.
 * Inputs: results/rows/<variant>_<DEV|HOLD>.jsonl (v8_replay.mjs), Edge Lab bars and rows (read-only).
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { canReenter } from '../../../src/engine/capitalHarvest/positionManager.js';
import { buildV4 } from '../../trade_economics_v5/scripts/v4_populations.mjs';
import { simulate } from '../../trade_economics_v5/scripts/exitPolicies.mjs';
import { VARIANTS, CORRECTIONS } from './corrections.mjs';

const PHASE = process.env.EDGE_PHASE === 'FULL' ? 'FULL' : 'DEV';
const HERE = dirname(fileURLToPath(import.meta.url)); const ROOT = join(HERE, '..'); const REPO = join(ROOT, '..', '..');
const OUT = join(ROOT, 'results'); const CFG = join(ROOT, 'configs'); mkdirSync(OUT, { recursive: true });
const shaFile = (p) => createHash('sha256').update(readFileSync(p)).digest('hex');
const PREREG_SHA = readFileSync(join(ROOT, 'V8_PREREGISTRATION.sha256'), 'utf8').trim().split(/\s+/)[0]; if (shaFile(join(ROOT, 'V8_PREREGISTRATION.md')) !== PREREG_SHA) throw new Error('V8_PREREGISTRATION hash mismatch');
const LAB = join(REPO, 'handoff', 'edge_discovery_lab', 'data');
const b5 = JSON.parse(readFileSync(join(LAB, 'XAUUSDm_bars.json'), 'utf8'))['5m']; const N = b5.length;
const COSTS = { normal: { spread: 0.24, slip: 0.10 }, stress: { spread: 0.60, slip: 0.20 } };
const r2 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 100) / 100); const r3 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 1000) / 1000);
const iso = (t) => new Date(t * 1000).toISOString(); const day = (t) => iso(t).slice(0, 10); const month = (t) => iso(t).slice(0, 7); const quarter = (t) => { const d = new Date(t * 1000); return `${d.getUTCFullYear()}Q${Math.floor(d.getUTCMonth() / 3) + 1}`; };
const SPLIT = { dev: ['2025-05-07', '2025-12-31'], hold: ['2026-01-01', '2026-09-29'] };
const split = (t) => { const d = day(t); if (d >= SPLIT.dev[0] && d <= SPLIT.dev[1]) return 'DEV'; if (d >= SPLIT.hold[0] && d <= SPLIT.hold[1]) return 'HOLD'; return 'EXCLUDED'; };
const mean = (a) => (a.length ? a.reduce((s, x) => s + x, 0) / a.length : null); const median = (a) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); const m = s.length >> 1; return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2; }; const pct = (a, p) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); return s[Math.min(s.length - 1, Math.floor(p * s.length))]; };
function rng(seed) { let s = seed >>> 0; return () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
function bootCI(v, n = 2000, seed = 20260930, alpha = 0.05) { if (v.length < 2) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0; for (let j = 0; j < v.length; j++) s += v[Math.floor(rand() * v.length)]; ms.push(s / v.length); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor((alpha / 2) * n)]), r3(ms[Math.floor((1 - alpha / 2) * n)])]; }
function blockCI(rows, n = 2000, seed = 7, alpha = 0.05) { const g = {}; for (const r of rows) (g[day(r.e.t)] ??= []).push(r.o.r); const blocks = Object.values(g); if (blocks.length < 5) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0, c = 0; for (let j = 0; j < blocks.length; j++) { const b = blocks[Math.floor(rand() * blocks.length)]; for (const x of b) { s += x; c++; } } ms.push(s / c); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor((alpha / 2) * n)]), r3(ms[Math.floor((1 - alpha / 2) * n)])]; }

// ---------- inputs ----------
const LABROWS = new Map(); const sessions = { DEV: new Set(), HOLD: new Set() };
for (const line of readFileSync(join(LAB, 'lab_rows.jsonl'), 'utf8').split('\n')) { if (!line) continue; const r = JSON.parse(line); const sp = split(r.t); if (sp === 'EXCLUDED') continue; LABROWS.set(r.i, r); sessions[sp].add(day(r.t)); }
const LABLIST = [...LABROWS.values()].sort((a, b) => a.i - b.i); const FIRST_I = LABLIST[0].i, LAST_I = LABLIST[LABLIST.length - 1].i;
const V4 = buildV4(b5, LABROWS, { split, day, SPLIT, FIRST_I, LAST_I }); const F = V4.F; const EVENTS = V4.EVENTS;
const SPLITS = PHASE === 'FULL' ? ['DEV', 'HOLD'] : ['DEV'];
const ROWS = {}; const META = {};
for (const v of Object.keys({ CONTROL: 1, CONTROL_COPY: 1, ...VARIANTS })) { ROWS[v] = new Map(); META[v] = {}; for (const S of SPLITS) { const p = join(OUT, 'rows', `${v}_${S}.jsonl`); if (!existsSync(p)) throw new Error(`missing rows ${v} ${S}`); for (const line of readFileSync(p, 'utf8').split('\n')) { if (!line) continue; const r = JSON.parse(line); ROWS[v].set(r.i, r); } META[v][S] = JSON.parse(readFileSync(join(OUT, 'rows', `${v}_${S}.meta.json`), 'utf8')); } }
const VAR_LIST = Object.keys(VARIANTS);

// ---------- gate 1: replay fidelity ----------
const fidelity = (() => {
  const res = { stage_parity: {}, control_vs_lab: {}, copy_vs_control: { compared: 0, identical: 0 } };
  for (const v of Object.keys(ROWS)) res.stage_parity[v] = Object.fromEntries(SPLITS.map((S) => [S, { checked: META[v][S].stage_parity.checked, mismatch: META[v][S].stage_parity.mismatch }]));
  const fields = ['act', 'wr', 'mdl', 'cs', 'q', 'qth', 'rr']; const mis = Object.fromEntries(fields.map((f) => [f, 0])); let compared = 0, missing = 0; const examples = [];
  for (const [i, lab] of LABROWS) { if (!SPLITS.includes(split(lab.t))) continue; const r = ROWS.CONTROL.get(i); if (!r) { missing++; continue; } compared++; const mine = { act: r.act, wr: r.wr, mdl: r.mdl, cs: r.cs, q: r.q, qth: r.qth, rr: r.g?.rr != null ? r3(r.g.rr) : null }; for (const f of fields) if ((mine[f] ?? null) !== (lab[f] ?? null)) { mis[f]++; if (examples.length < 10) examples.push({ i, f, lab: lab[f], v8: mine[f] }); } }
  res.control_vs_lab = { compared, missing, mismatches: mis, examples };
  for (const [i, r] of ROWS.CONTROL) { res.copy_vs_control.compared++; if (JSON.stringify(r) === JSON.stringify(ROWS.CONTROL_COPY.get(i))) res.copy_vs_control.identical++; }
  return res;
})();
console.log('fidelity', JSON.stringify({ lab: fidelity.control_vs_lab.mismatches, missing: fidelity.control_vs_lab.missing, copy: fidelity.copy_vs_control }));
if (Object.values(fidelity.control_vs_lab.mismatches).some((x) => x > 0) || fidelity.control_vs_lab.missing > 0 || fidelity.copy_vs_control.identical !== fidelity.copy_vs_control.compared || Object.values(fidelity.stage_parity).some((o) => Object.values(o).some((s) => s.mismatch > 0))) throw new Error('REPLAY FIDELITY FAILED');

// ---------- signals and outcomes ----------
const MEMO = new Map();
function out(e, kind, cse = 'normal', drift = false) { const key = `${e.i}|${e.side}|${e.geo.entry}|${e.geo.sl}|${e.geo.tp2}|${kind}|${cse}|${drift}`; const m = MEMO.get(key); if (m) return m; const pol = kind === 'open' ? { type: 'OPEN' } : kind === 'fix170' ? { type: 'FIXED', rr: 1.7 } : { type: 'FIXED', tpPrice: e.geo.tp2 }; const o = simulate(b5, e, pol, COSTS[cse], { drift }); MEMO.set(key, o); return o; }
const SIG = {};
for (const v of VAR_LIST) { SIG[v] = []; for (const r of [...ROWS[v].values()].sort((a, b) => a.i - b.i)) { if (r.act !== 'BUY' && r.act !== 'SELL') continue; const e = { i: r.i, t: r.t, side: r.act, model: r.mdl, anchor: r.anc ?? r.g.e, org: r.org, geo: { entry: r.g.e, sl: r.g.sl, tp2: r.g.tp2 }, rr: r.g.rr, obj: r.g.obj, risk_atr: r.g.ra, atr: F.atr[r.i], split: split(r.t), pop: v }; const o = out(e, 'open'); e.open = o; e.wrong = o.status !== 'NO_DATA' && o.mfe_r < 0.5 && (o.exit === 'BROKER_SL' || o.exit === 'THESIS_INVALIDATION'); e.bad = o.status !== 'NO_DATA' && o.milestones[1] == null; e.right = o.status !== 'NO_DATA' && o.milestones[1] != null; SIG[v].push(e); } }
const rowsOf = (sigs, kind = 'ctl', cse = 'normal', drift = false) => sigs.map((e) => ({ e, o: out(e, kind, cse, drift) })).filter((x) => x.o.status !== 'NO_DATA' && x.o.status !== 'INVALID');
function seqWalk(rows) { const trades = []; let exitBar = -1, lastTrade = null, lastLoss = false; const skipped = { SAME_OR_EARLIER_CANDLE: 0, STALE_SAME_SETUP: 0, REVENGE_GUARD: 0 }; const occ = []; for (const x of [...rows].sort((a, b) => a.e.i - b.e.i)) { const ok = canReenter({ signal: x.e, exitBar, lastTrade, lastExitWasLoss: lastLoss }); if (!ok.ok) { skipped[ok.reason] = (skipped[ok.reason] ?? 0) + 1; continue; } trades.push(x); occ.push([x.e.i, x.o.exitBar]); exitBar = x.o.exitBar; lastTrade = x.e; lastLoss = x.o.r <= 0; } return { trades, skipped, occ }; }
function pathDD(rows, key = 'r') { let cum = 0, peak = 0, dd = 0, streak = 0, maxStreak = 0; for (const x of rows) { cum += x.o[key]; if (cum > peak) peak = cum; dd = Math.max(dd, peak - cum); if (x.o[key] <= 0) { streak++; maxStreak = Math.max(maxStreak, streak); } else streak = 0; } return { max_dd: r2(dd), final: r2(cum), max_loss_streak: maxStreak }; }
function stats(rows, sessSet = null, { ci = true, block = false } = {}) { const R = rows.map((x) => x.o.r); if (!R.length) return { n: 0 }; const w = R.filter((x) => x > 0), l = R.filter((x) => x <= 0); const gw = w.reduce((a, b) => a + b, 0), gl = -l.reduce((a, b) => a + b, 0); const U = rows.map((x) => x.o.pnl_usd); const perDay = {}; for (const x of rows) perDay[day(x.e.t)] = (perDay[day(x.e.t)] ?? 0) + 1; const counts = sessSet ? [...sessSet].map((d) => perDay[d] ?? 0) : null; const costU = rows.reduce((s, x) => s + x.o.cost_usd, 0); const ddR = pathDD(rows, 'r'), ddU = pathDD(rows, 'pnl_usd');
  return { n: R.length, win_rate: r3(w.length / R.length), avg_win_r: r3(mean(w)), avg_loss_r: l.length ? r3(-mean(l)) : null, expectancy_r: r3(mean(R)), expectancy_usd: r3(mean(U)), pf: gl > 0 ? r2(gw / gl) : (gw > 0 ? 99 : null), ci95_r: ci ? bootCI(R) : null, block_ci95_r: block ? blockCI(rows) : null, max_dd_r: ddR.max_dd, max_dd_usd: ddU.max_dd, net_r: ddR.final, net_usd: ddU.final, max_loss_streak: ddR.max_loss_streak, wrong_direction_rate: r3(rows.filter((x) => x.e.wrong).length / R.length), bad_entry_rate: r3(rows.filter((x) => x.e.bad).length / R.length), mfe_open_r: r3(mean(rows.map((x) => x.e.open.mfe_r).filter((v) => v != null))), mae_r: r3(mean(rows.map((x) => x.o.mae_r))), mfe_r: r3(mean(rows.map((x) => x.o.mfe_r))), reach_1r: r3(rows.filter((x) => x.e.open.milestones?.[1] != null).length / R.length), reach_1_7r: r3(rows.filter((x) => x.e.open.milestones?.[1.7] != null).length / R.length), avg_bars: r2(mean(rows.map((x) => x.o.bars))), cost_usd: r3(costU / R.length), trades_per_session: counts ? { median: pct(counts, 0.5), p90: pct(counts, 0.9), mean: r2(mean(counts)) } : null, side_mix: rows.reduce((g, x) => { g[x.e.side] = (g[x.e.side] ?? 0) + 1; return g; }, {}), model_mix: rows.reduce((g, x) => { g[x.e.model] = (g[x.e.model] ?? 0) + 1; return g; }, {}) }; }
function captureStats(S, sigRows, occ = []) { const by = {}; for (const x of sigRows) (by[x.e.i] ??= []).push(x.e.side); let valid = 0, late = 0, wrong = 0, none = 0, positioned = 0; for (const ev of EVENTS[S]) { let e = false, l = false, w = false; for (let j = ev.k - 6; j <= ev.k + 6; j++) for (const s of by[j] ?? []) { if (s === ev.dir) { if (j <= ev.k) e = true; else l = true; } else w = true; } if (e) valid++; else if (l) late++; else if (w) wrong++; else if (occ.some(([a, b]) => ev.k >= a && ev.k <= b)) positioned++; else none++; } const n = Math.max(1, EVENTS[S].length); return { events: EVENTS[S].length, capture_rate: r3((valid + late) / n), valid_entry_rate: r3(valid / n), late_entry_rate: r3(late / n), wrong_direction_rate: r3(wrong / n), already_positioned_rate: r3(positioned / n), no_signal_rate: r3(none / n) }; }
function adverse(trades) { if (!trades.length) return null; const rand = rng(11); const byM = {}; for (const x of trades) (byM[month(x.e.t)] ??= []).push(x.o.r); const dds = [], streaks = []; for (let k = 0; k < 500; k++) { const order = Object.values(byM).sort(() => rand() - 0.5); let cum = 0, peak = 0, dd = 0, stk = 0, ms = 0; for (const m of order) for (const r of [...m].sort(() => rand() - 0.5)) { cum += r; peak = Math.max(peak, cum); dd = Math.max(dd, peak - cum); if (r <= 0) { stk++; ms = Math.max(ms, stk); } else stk = 0; } dds.push(dd); streaks.push(ms); } return { dd_r_p50: r2(median(dds)), dd_r_p90: r2(pct(dds, 0.9)), dd_r_p99: r2(pct(dds, 0.99)), loss_streak_p50: median(streaks), loss_streak_p90: pct(streaks, 0.9) }; }
function capital(trades) { if (!trades.length) return null; const ddU = pathDD(trades, 'pnl_usd'); const margin = r2(mean(trades.map((x) => x.e.geo.entry)) * 100 * 0.01 / 200); const risk = mean(trades.map((x) => 1.5 * Math.abs(x.e.geo.entry - x.e.geo.sl) + 0.24)); return { lot: 0.01, net_usd: ddU.final, max_dd_usd: ddU.max_dd, mean_broker_sl_usd: r2(risk), margin_usd_approx: margin, by_capital: Object.fromEntries([62, 100, 1000, 10000].map((cap) => [cap, { max_dd_pct: r3(ddU.max_dd / cap), risk_pct: r3(risk / cap), margin_pct: r3(margin / cap), feasible_001_lot: cap >= 71 ? 'YES' : 'NO (MARGIN_SAFETY_VETO: equity below ~71 USD)' }])) }; }
const walkForward = (trades) => { const q = {}; for (const x of trades) (q[quarter(x.e.t)] ??= []).push(x); return Object.fromEntries(Object.entries(q).sort().map(([k, v]) => { const s = stats(v, null, { ci: false }); return [k, { n: s.n, expectancy_r: s.expectancy_r, pf: s.pf, max_dd_r: s.max_dd_r, wrong_direction_rate: s.wrong_direction_rate }]; })); };

function evaluate(v, S) {
  const sigs = SIG[v].filter((e) => e.split === S); const all = rowsOf(sigs); const w = seqWalk(all); const st = stats(w.trades, sessions[S], { ci: true, block: true });
  const stress = seqWalk(rowsOf(sigs, 'ctl', 'stress')); const drift = seqWalk(rowsOf(sigs, 'ctl', 'normal', true)); const f170 = seqWalk(rowsOf(sigs, 'fix170')); const f170s = seqWalk(rowsOf(sigs, 'fix170', 'stress'));
  const timing = sigs.map((e) => (Number.isInteger(e.org) ? e.i - e.org : null)).filter((x) => x != null);
  return { signals: sigs.length, signal_model_mix: sigs.reduce((g, e) => { g[e.model] = (g[e.model] ?? 0) + 1; return g; }, {}), signal_side_mix: sigs.reduce((g, e) => { g[e.side] = (g[e.side] ?? 0) + 1; return g; }, {}), signal_wrong_direction_rate: r3(sigs.filter((e) => e.wrong).length / Math.max(1, sigs.length)),
    entry_timing_bars_from_origin: { mean: r2(mean(timing)), median: median(timing), p90: pct(timing, 0.9) }, sl_risk_atr: { mean: r3(mean(sigs.map((e) => e.risk_atr).filter((x) => x != null))), median: r3(median(sigs.map((e) => e.risk_atr).filter((x) => x != null))) }, tp2_r: { mean: r3(mean(sigs.map((e) => e.rr).filter((x) => x != null))), share_at_cap_3r: r3(sigs.filter((e) => e.rr >= 2.995).length / Math.max(1, sigs.length)), share_below_1_70: r3(sigs.filter((e) => Math.abs(e.geo.tp2 - e.geo.entry) / Math.abs(e.geo.entry - e.geo.sl) < 1.7 - 1e-9).length / Math.max(1, sigs.length)) },
    primary: st, stress: stats(stress.trades, null, { ci: true }), drift: stats(drift.trades, null, { ci: false }), fixed_170r: stats(f170.trades, null, { ci: true }), fixed_170r_stress: stats(f170s.trades, null, { ci: false }), skipped: w.skipped, capture: captureStats(S, all, w.occ), walk_forward: walkForward(w.trades), adverse: adverse(w.trades), capital: capital(w.trades), _trades: w.trades, _occ: w.occ, _all: all };
}

// ---------- decision differences vs CONTROL (with explainability) ----------
const PRIM = ['st5', 'ev5', 'sw5', 'b15', 'b15r', 'choch', 'm30s', 'm30r', 'h1r', 'stB', 'stS', 'elig', 'trig', 'rg5', 'stale'];
function decisionDiff(v, S) { let bars = 0, actDiff = 0, sigDiff = 0, unexplained = 0, primDiff = 0; const byChange = {}; const ex = []; for (const [i, c] of ROWS.CONTROL) { if (split(c.t) !== S) continue; const r = ROWS[v].get(i); bars++; const p = PRIM.some((k) => JSON.stringify(c[k] ?? null) !== JSON.stringify(r[k] ?? null)); if (p) primDiff++; const ca = c.act === 'WAIT' ? `WAIT:${c.wr}` : `${c.act}:${c.mdl}`, ra = r.act === 'WAIT' ? `WAIT:${r.wr}` : `${r.act}:${r.mdl}`; if (ca !== ra) { actDiff++; if ((c.act !== 'WAIT') !== (r.act !== 'WAIT') || c.act !== r.act) sigDiff++; const key = `${ca} -> ${ra}`; byChange[key] = (byChange[key] ?? 0) + 1; const d5 = VARIANTS[v].includes('D5') && r.wr === 'RR_NOT_ACCEPTABLE' && c.g?.rr === 1.7; if (!p && !d5) { unexplained++; if (ex.length < 10) ex.push({ i, t: iso(c.t), control: ca, variant: ra }); } } } return { bars, primitive_changed_bars: primDiff, primitive_changed_share: r3(primDiff / Math.max(1, bars)), decision_changed_bars: actDiff, decision_changed_share: r3(actDiff / Math.max(1, bars)), signal_changed_bars: sigDiff, unexplained_changes: unexplained, unexplained_examples: ex, top_changes: Object.entries(byChange).sort((a, b) => b[1] - a[1]).slice(0, 12).map(([k, n]) => ({ change: k, n })) }; }

// ---------- forensics ----------
const LATE = { MC: 3, PB: 3, BO: 10, SR: 0, MR: 3 };
const CLASS_OF_FIX = { D1: 'A', D2: 'A', D3: 'A', D4: 'D', D5: 'C', D6: 'E' };
function wrongDirectionForensics(S, ctl) {
  const out = []; for (const x of ctl._trades.filter((t) => t.e.wrong)) { const e = x.e; const i = e.i; let cls = null, fix = null;
    for (let j = i; j <= i + 3 && j < N; j++) if (j > 0 && b5[j].time - b5[j - 1].time > 3 * 3600) cls = 'G';
    if (!cls && Number.isInteger(e.org) && i - e.org > LATE[e.model]) cls = 'E';
    if (!cls) { const a = ROWS.ALL.get(i); if (!(a.act === e.side && a.mdl === e.model)) { const singles = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6'].filter((d) => { const r = ROWS[d].get(i); return !(r.act === e.side && r.mdl === e.model); }); fix = singles[0] ?? 'COMBINED'; cls = a.act !== 'WAIT' && a.act !== e.side ? 'B' : (CLASS_OF_FIX[fix] ?? 'A'); } }
    if (!cls) cls = 'I';
    const r = ROWS.CONTROL.get(i); out.push({ i, t: iso(e.t), model: e.model, side: e.side, cls, fix, entry: e.geo.entry, sl: e.geo.sl, tp2: e.geo.tp2, r: x.o.r, mfe_open_r: e.open.mfe_r, exit: x.o.exit, context: { b15: r.b15, b15r: r.b15r, rg5: r.rg5, m30r: r.m30r, h1r: r.h1r, st5: r.st5 }, stages: { BUY: r.stB, SELL: r.stS }, all_variant: `${ROWS.ALL.get(i).act}:${ROWS.ALL.get(i).mdl ?? ROWS.ALL.get(i).wr}` }); }
  const by = {}; for (const o of out) by[o.cls] = (by[o.cls] ?? 0) + 1; const byFix = {}; for (const o of out) if (o.fix) byFix[o.fix] = (byFix[o.fix] ?? 0) + 1; const byModel = {}; for (const o of out) { (byModel[o.model] ??= {}); byModel[o.model][o.cls] = (byModel[o.model][o.cls] ?? 0) + 1; }
  return { trades: ctl._trades.length, wrong_trades: out.length, by_class: by, by_fix: byFix, by_model: byModel, implementation_caused: out.filter((o) => ['A', 'B', 'C', 'D', 'E', 'G'].includes(o.cls)).length, examples: out.slice(0, 40) };
}
const GATE_CLASS = { OVEREXTENDED: 'LOCATION_BLOCKED', RR_NOT_ACCEPTABLE: 'RR_BLOCKED', VOLATILITY_INSUFFICIENT: 'RISK_BLOCKED', INVALID_GEOMETRY: 'RISK_BLOCKED', NO_GOOD_ENTRY: 'MODEL_BLOCKED:QUALITY', ENTRY_CONFLICT: 'MODEL_BLOCKED:CONTEXT_VETO', HTF_CONFLICT: 'MODEL_BLOCKED:CONTEXT_VETO' };
const GATE_ORDER = ['LOCATION_BLOCKED', 'RR_BLOCKED', 'RISK_BLOCKED', 'MODEL_BLOCKED:QUALITY', 'MODEL_BLOCKED:CONTEXT_VETO'];
function missedForensics(v, S, ev) {
  const rowsV = ROWS[v]; const sigBy = {}; for (const x of ev._all) (sigBy[x.e.i] ??= []).push(x.e.side); const res = []; const D = (s) => (s === 'BUY' ? 'B' : 'S');
  for (const e of EVENTS[S]) { const side = e.dir; let cls = null, sub = null;
    let aligned = false, late = false, opp = false; for (let j = e.k - 6; j <= e.k + 6; j++) for (const s of sigBy[j] ?? []) { if (s === side) { if (j <= e.k) aligned = true; else late = true; } else if (j <= e.k) opp = true; }
    if (aligned) cls = 'CAPTURED'; else if (late) cls = 'LATE'; else if (opp) cls = 'WRONG_SIDE_SIGNAL'; else if (ev._occ.some(([a, b]) => e.k >= a && e.k <= b)) cls = 'POSITION_OCCUPIED';
    if (!cls) { const win = []; for (let j = e.k - 6; j <= e.k; j++) { const r = rowsV.get(j); if (r) win.push(r); }
      if (!win.length || win.every((r) => ['INSUFFICIENT_DATA', 'BIAS_UNAVAILABLE', 'DATA_UNAVAILABLE_STALE'].includes(r.wr))) cls = 'DATA_UNAVAILABLE';
      else { const gates = win.filter((r) => r.cs === side && GATE_CLASS[r.wr]).map((r) => GATE_CLASS[r.wr]); const g = GATE_ORDER.find((x) => gates.includes(x));
        if (g) cls = g; else { const stKey = side === 'BUY' ? 'stB' : 'stS'; const maxStage = Math.max(0, ...win.map((r) => Math.max(...(r[stKey] ?? '00000').split('').map(Number))));
          if (maxStage >= 3) { cls = 'MODEL_BLOCKED:BIAS'; const r3w = win.find((r) => (r[stKey] ?? '').includes('3')); sub = r3w.cs && r3w.cs !== side ? 'PRIORITY_OTHER_SIDE' : r3w.wr === 'CHOP' ? 'CHOP' : (r3w.b15 === 'NEUTRAL' ? 'NEUTRAL_BIAS' : r3w.b15 === (side === 'BUY' ? 'BEARISH' : 'BULLISH') ? 'OPPOSING_BIAS' : 'NOT_ELIGIBLE'); }
          else cls = maxStage === 2 ? 'NO_TRIGGER' : maxStage === 1 ? 'NO_SETUP' : 'NO_PATTERN'; } } }
    res.push({ k: e.k, t: iso(b5[e.k].time), side, cls, sub, D: D(side) }); }
  const by = {}; for (const x of res) by[x.cls] = (by[x.cls] ?? 0) + 1; const sub = {}; for (const x of res) if (x.sub) sub[x.sub] = (sub[x.sub] ?? 0) + 1;
  return { events: res.length, by_class: by, bias_block_detail: sub, _list: res };
}
function engineErrors(S, ctlMissed, allMissed) { const allBy = new Map(allMissed._list.map((x) => [x.k, x])); const list = []; for (const x of ctlMissed._list) { if (x.cls === 'CAPTURED') continue; const a = allBy.get(x.k); if (a.cls !== 'CAPTURED') continue; const singles = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6'].filter((d) => { const ev = EVAL[d][S]; const has = ev._all.some((y) => y.e.side === x.side && y.e.i >= x.k - 6 && y.e.i <= x.k); return has; }); list.push({ k: x.k, t: x.t, side: x.side, control_class: x.cls, fixes: singles.length ? singles : ['COMBINED'] }); } const lost = []; for (const x of ctlMissed._list) { if (x.cls !== 'CAPTURED') continue; const a = allBy.get(x.k); if (a.cls !== 'CAPTURED') lost.push({ k: x.k, t: x.t, side: x.side, corrected_class: a.cls }); } const byFix = {}; for (const x of list) for (const f of x.fixes) byFix[f] = (byFix[f] ?? 0) + 1; const lostBy = {}; for (const x of lost) lostBy[x.corrected_class] = (lostBy[x.corrected_class] ?? 0) + 1; return { missed_valid_patterns_before: list.length, by_fix: byFix, examples: list.slice(0, 25), no_longer_captured: lost.length, no_longer_captured_by_class: lostBy, missed_valid_patterns_after: 0 }; }
function contextLag(v, S) { const rowsV = [...ROWS[v].values()].filter((r) => split(r.t) === S).sort((a, b) => a.i - b.i); const items = []; let lastKey = null;
  for (const r of rowsV) { if (r.act !== 'WAIT' || !r.ag) continue; for (const a of r.ag) { if (!a.pass) continue; if (!['NO_ELIGIBLE_STRATEGY', 'CHOP'].includes(r.wr) && !(r.cs && r.cs[0] !== a.s)) continue; const side = a.s === 'B' ? 'BUY' : 'SELL'; const key = `${side}|${a.m}`; const episodeStart = !(lastKey && lastKey.key === key && r.i - lastKey.i <= 3); lastKey = { key, i: r.i }; if (!episodeStart) continue;
    const want = side === 'BUY' ? 'BULLISH' : 'BEARISH'; let alignedIn = null; for (let j = r.i + 1; j <= r.i + 6; j++) { const n2 = ROWS[v].get(j); if (n2 && n2.b15 === want) { alignedIn = j - r.i; break; } }
    const blockedBy = r.wr === 'CHOP' ? (r.rg5 === 'CHOP_UNCERTAIN' ? '5m CHOP_UNCERTAIN' : '15m CHOP (no eligible models)') : r.cs && r.cs[0] !== a.s ? `priority: ${r.mdl} ${r.cs} selected` : r.b15 === 'NEUTRAL' ? `15m NEUTRAL bias (${r.b15r}): ${a.m} not eligible` : r.b15 !== want ? `15m ${r.b15} bias opposes ${side}` : `model ${a.m} not in eligible set ${r.elig}`;
    const e = { i: r.i, t: r.t, side, model: a.m, geo: { entry: a.e, sl: a.sl, tp2: a.tp2 }, atr: F.atr[r.i], anchor: a.anc, pop: 'LAG' }; const o = out(e, 'ctl'); const op = out(e, 'open');
    items.push({ pattern_valid_at: iso(r.t + 300), side, model: a.m, context_state_at: `15m ${r.b15}/${r.b15r}, 5m ${r.rg5}, 30m ${r.m30r}, 1H ${r.h1r}`, blocked_by: blockedBy, would_have_been_valid: 'YES', bias_aligned_within_6_bars: alignedIn != null ? `YES (${alignedIn})` : 'NO', r: o.status === 'NO_DATA' ? null : o.r, wrong: op.status !== 'NO_DATA' && op.mfe_r < 0.5 && (op.exit === 'BROKER_SL' || op.exit === 'THESIS_INVALIDATION') }); } }
  const by = {}; for (const x of items) { const k = x.blocked_by.replace(/\(.*\)/, '').replace(/: (MC|PB|BO|SR|MR) not eligible/, ': model not eligible').replace(/priority: .*/, 'priority: other side selected').trim(); (by[k] ??= []).push(x); }
  const summary = Object.fromEntries(Object.entries(by).map(([k, v2]) => { const R = v2.map((x) => x.r).filter((x) => x != null); return [k, { episodes: v2.length, aligned_within_6: v2.filter((x) => x.bias_aligned_within_6_bars.startsWith('YES')).length, mean_r_descriptive: r3(mean(R)), wrong_direction_rate: r3(v2.filter((x) => x.wrong).length / v2.length), by_model: v2.reduce((g, x) => { g[x.model] = (g[x.model] ?? 0) + 1; return g; }, {}) }]; }));
  return { episodes: items.length, summary, examples: items.slice(0, 30) };
}
function eligibilityTrace(v, S) { const rowsV = [...ROWS[v].values()].filter((r) => split(r.t) === S); const res = {}; for (const m of ['MC', 'PB', 'BO', 'SR', 'MR']) { let elig = 0, trig = 0, sel = 0, sig = 0, pre = 0, agB = 0, agS = 0; for (const r of rowsV) { if ((r.elig ?? '').includes(m)) elig++; const t = (r.trig ?? '').split(',').filter((x) => x.startsWith(m)); if (t.length) { trig++; if (r.mdl === m) sel++; else pre++; } if (r.mdl === m && (r.act === 'BUY' || r.act === 'SELL')) sig++; const idx = ['MC', 'PB', 'BO', 'SR', 'MR'].indexOf(m); if ((r.stB ?? '')[idx] === '3') agB++; if ((r.stS ?? '')[idx] === '3') agS++; } res[m] = { eligible_bars: elig, triggered_under_real_bias: trig, selected: sel, preempted_by_higher_priority: pre, final_signals: sig, bias_agnostic_triggers: { BUY: agB, SELL: agS } }; } const waits = {}; for (const r of rowsV) { const k = r.act === 'WAIT' ? r.wr : 'SIGNAL'; waits[k] = (waits[k] ?? 0) + 1; } return { bars: rowsV.length, models: res, decision_mix: waits }; }
function stageFunnel(v, S) { const rowsV = [...ROWS[v].values()].filter((r) => split(r.t) === S && r.stB); const res = {}; ['MC', 'PB', 'BO', 'SR', 'MR'].forEach((m, idx) => { const c = { BUY: [0, 0, 0, 0], SELL: [0, 0, 0, 0] }; for (const r of rowsV) { c.BUY[Number(r.stB[idx])]++; c.SELL[Number(r.stS[idx])]++; } res[m] = Object.fromEntries(Object.entries(c).map(([s, a]) => [s, { pattern_or_more: a[1] + a[2] + a[3], setup_or_more: a[2] + a[3], trigger: a[3] }])); }); return { bars: rowsV.length, models: res }; }

// ---------- run ----------
const EVAL = {}; for (const v of VAR_LIST) { EVAL[v] = {}; for (const S of SPLITS) EVAL[v][S] = evaluate(v, S); }
const strip = (ev) => Object.fromEntries(Object.entries(ev).filter(([k]) => !k.startsWith('_')));
const res = { phase: PHASE, generated_utc: new Date().toISOString(), prereg_sha: PREREG_SHA, fidelity, splits: SPLITS, sessions: Object.fromEntries(SPLITS.map((S) => [S, sessions[S].size])), events: Object.fromEntries(SPLITS.map((S) => [S, EVENTS[S].length])), variants: {}, diffs: {}, forensics: {} };
for (const v of VAR_LIST) { res.variants[v] = Object.fromEntries(SPLITS.map((S) => [S, strip(EVAL[v][S])])); if (v !== 'CONTROL') res.diffs[v] = Object.fromEntries(SPLITS.map((S) => [S, decisionDiff(v, S)])); }
for (const S of SPLITS) { const cm = missedForensics('CONTROL', S, EVAL.CONTROL[S]); const am = missedForensics('ALL', S, EVAL.ALL[S]); res.forensics[S] = { wrong_direction_control: wrongDirectionForensics(S, EVAL.CONTROL[S]), missed_control: { events: cm.events, by_class: cm.by_class, bias_block_detail: cm.bias_block_detail }, missed_corrected: { events: am.events, by_class: am.by_class, bias_block_detail: am.bias_block_detail }, engine_errors: engineErrors(S, cm, am), context_lag_control: contextLag('CONTROL', S), context_lag_corrected: contextLag('ALL', S), eligibility_control: eligibilityTrace('CONTROL', S), eligibility_corrected: eligibilityTrace('ALL', S), stages_control: stageFunnel('CONTROL', S), stages_corrected: stageFunnel('ALL', S) }; }
// control reproduction check against V7
const v7 = { DEV: { n: 878, expectancy_r: -0.055 }, HOLD: { n: 1163, expectancy_r: -0.064, pf: 0.93, max_dd_r: 98.89, wrong_direction_rate: 0.297 } };
res.control_reproduces_v7 = Object.fromEntries(SPLITS.map((S) => { const p = res.variants.CONTROL[S].primary; const want = v7[S]; return [S, { want, got: { n: p.n, expectancy_r: p.expectancy_r, pf: p.pf, max_dd_r: p.max_dd_r, wrong_direction_rate: p.wrong_direction_rate }, pass: Object.entries(want).every(([k, x]) => Math.abs((p[k] ?? NaN) - x) < 1e-6) }]; }));
console.log('control reproduces V7', JSON.stringify(res.control_reproduces_v7));
if (!Object.values(res.control_reproduces_v7).every((x) => x.pass)) throw new Error('CONTROL does not reproduce V7');
// decision
if (PHASE === 'FULL') { const a = res.variants.ALL.HOLD, d = res.variants.ALL.DEV, c = res.variants.CONTROL.HOLD; const q = Object.entries(a.walk_forward).filter(([k]) => k.startsWith('2026')); const checks = { hold_expectancy_gt_0: a.primary.expectancy_r > 0, hold_ci_lower_gt_0: (a.primary.ci95_r?.[0] ?? -1) > 0, hold_pf_gt_1_10: a.primary.pf > 1.10, hold_stress_gt_0: a.stress.expectancy_r > 0, hold_quarters_positive_ge_2_of_3: q.filter(([, x]) => x.expectancy_r > 0).length >= 2, dev_expectancy_gt_0: d.primary.expectancy_r > 0 }; const all = Object.values(checks).every(Boolean); res.decision = { checks, better_than_control_hold: a.primary.expectancy_r > c.primary.expectancy_r, EDGE_DEMONSTRATED: all ? 'YES' : (checks.hold_expectancy_gt_0 && a.primary.expectancy_r > c.primary.expectancy_r ? 'INCONCLUSIVE' : 'NO'), DEMO_ELIGIBLE: 'NO' }; }
writeFileSync(join(OUT, `v8_results_${PHASE}.json`), JSON.stringify(res, null, 1));
if (PHASE === 'DEV') { const freeze = { frozen_utc: new Date().toISOString(), prereg_sha: PREREG_SHA, corrections_sha: shaFile(join(HERE, 'corrections.mjs')), engines_manifest_sha: shaFile(join(CFG, 'engines.sha256')), replay_sha: shaFile(join(HERE, 'v8_replay.mjs')), study_sha: shaFile(join(HERE, 'v8_study.mjs')), dev_results_sha: shaFile(join(OUT, 'v8_results_DEV.json')) }; writeFileSync(join(CFG, 'v8_freeze.json'), JSON.stringify(freeze, null, 1)); console.log('frozen', JSON.stringify(freeze)); }
else { const fz = JSON.parse(readFileSync(join(CFG, 'v8_freeze.json'), 'utf8')); const now = { prereg_sha: PREREG_SHA, corrections_sha: shaFile(join(HERE, 'corrections.mjs')), engines_manifest_sha: shaFile(join(CFG, 'engines.sha256')), replay_sha: shaFile(join(HERE, 'v8_replay.mjs')) }; for (const [k, x] of Object.entries(now)) if (fz[k] !== x) throw new Error(`freeze violated: ${k}`); console.log('freeze verified; decision', JSON.stringify(res.decision)); }
console.log('done', PHASE);
