/**
 * NEW INFORMATION V7 -- new data (silver, dollar index, Nasdaq, release timestamps, broker spread) x directional accuracy on FROZEN entries (RESEARCH ONLY).
 * Spec: ../V7_PREREGISTRATION.md (hash asserted). EDGE_PHASE=DEV derives configs/finalists.json; EDGE_PHASE=FULL evaluates DEV + HOLDOUT once -> results/v7_results.json.
 * Timestamp rule: a cross-asset bar is usable at the gold decision (close of bar i) only if its close time <= that moment. NA -> pass-through (no WAIT).
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { canReenter } from '../../../src/engine/capitalHarvest/positionManager.js';
import { buildV4 } from '../../trade_economics_v5/scripts/v4_populations.mjs';
import { simulate } from '../../trade_economics_v5/scripts/exitPolicies.mjs';
import { crossFeatures, dataQuality, alignIndex, atr14Series, PARITY_TOL } from './crossAsset.mjs';

const PHASE = process.env.EDGE_PHASE === 'FULL' ? 'FULL' : 'DEV';
const HERE = dirname(fileURLToPath(import.meta.url)); const REPO = join(HERE, '..', '..', '..'); const ROOT = join(REPO, 'research', 'new_information_v7'); const OUT = join(ROOT, 'results'); const CFG = join(ROOT, 'configs'); mkdirSync(OUT, { recursive: true }); mkdirSync(CFG, { recursive: true });
const shaFile = (p) => createHash('sha256').update(readFileSync(p)).digest('hex');
const PREREG_SHA = readFileSync(join(ROOT, 'V7_PREREGISTRATION.sha256'), 'utf8').trim().split(/\s+/)[0]; if (shaFile(join(ROOT, 'V7_PREREGISTRATION.md')) !== PREREG_SHA) throw new Error('V7_PREREGISTRATION hash mismatch');
const CONTROL_SHA = readFileSync(join(ROOT, 'V7_CONTROL_BASELINE.sha256'), 'utf8').trim().split(/\s+/)[0]; if (shaFile(join(ROOT, 'V7_CONTROL_BASELINE.md')) !== CONTROL_SHA) throw new Error('V7_CONTROL_BASELINE hash mismatch');
const LAB = join(REPO, 'handoff', 'edge_discovery_lab', 'data');
const b5 = JSON.parse(readFileSync(join(LAB, 'XAUUSDm_bars.json'), 'utf8'))['5m']; const N = b5.length;
const XAG = JSON.parse(readFileSync(join(LAB, 'XAGUSDm_bars.json'), 'utf8')); const DXY = JSON.parse(readFileSync(join(LAB, 'DXYm_bars.json'), 'utf8')); const UST = JSON.parse(readFileSync(join(LAB, 'USTECm_bars.json'), 'utf8'));
const COSTS = { normal: { spread: 0.24, slip: 0.10 }, stress: { spread: 0.60, slip: 0.20 } };
const r2 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 100) / 100); const r3 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 1000) / 1000);
const iso = (t) => new Date(t * 1000).toISOString(); const day = (t) => iso(t).slice(0, 10); const month = (t) => iso(t).slice(0, 7); const quarter = (t) => { const d = new Date(t * 1000); return `${d.getUTCFullYear()}Q${Math.floor(d.getUTCMonth() / 3) + 1}`; };
const SPLIT = { dev: ['2025-05-07', '2025-12-31'], hold: ['2026-01-01', '2026-09-29'] };
const split = (t) => { const d = day(t); if (d >= SPLIT.dev[0] && d <= SPLIT.dev[1]) return 'DEV'; if (d >= SPLIT.hold[0] && d <= SPLIT.hold[1]) return 'HOLD'; return 'EXCLUDED'; };
const mean = (a) => (a.length ? a.reduce((s, x) => s + x, 0) / a.length : null); const median = (a) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); const m = s.length >> 1; return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2; }; const pct = (a, p) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); return s[Math.min(s.length - 1, Math.floor(p * s.length))]; };
function rng(seed) { let s = seed >>> 0; return () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
function bootCI(v, n = 2000, seed = 20260930, alpha = 0.05) { if (v.length < 2) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0; for (let j = 0; j < v.length; j++) s += v[Math.floor(rand() * v.length)]; ms.push(s / v.length); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor((alpha / 2) * n)]), r3(ms[Math.floor((1 - alpha / 2) * n)])]; }
function blockCI(rows, n = 2000, seed = 7, alpha = 0.05) { const g = {}; for (const r of rows) (g[day(r.e.t)] ??= []).push(r.o.r); const blocks = Object.values(g); if (blocks.length < 5) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0, c = 0; for (let j = 0; j < blocks.length; j++) { const b = blocks[Math.floor(rand() * blocks.length)]; for (const x of b) { s += x; c++; } } ms.push(s / c); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor((alpha / 2) * n)]), r3(ms[Math.floor((1 - alpha / 2) * n)])]; }

// ---------- data ----------
const ROWS = new Map(); const ROWLIST = []; const sessions = { DEV: new Set(), HOLD: new Set(), ALL: new Set() };
for (const line of readFileSync(join(LAB, 'lab_rows.jsonl'), 'utf8').split('\n')) { if (!line) continue; const r = JSON.parse(line); const sp = split(r.t); if (sp === 'EXCLUDED') continue; r.split = sp; ROWS.set(r.i, r); ROWLIST.push(r); sessions[sp].add(day(r.t)); sessions.ALL.add(day(r.t)); }
ROWLIST.sort((a, b) => a.i - b.i); const FIRST_I = ROWLIST[0].i, LAST_I = ROWLIST[ROWLIST.length - 1].i;
const C = readFileSync(join(REPO, 'research', 'entry_architecture_v2', 'results', 'candidates.jsonl'), 'utf8').trim().split('\n').map((l) => JSON.parse(l)).filter((c) => split(c.t) !== 'EXCLUDED');
const V4 = buildV4(b5, ROWS, { split, day, SPLIT, FIRST_I, LAST_I }); const F = V4.F; const EVENTS = V4.EVENTS;
const V4DEFN = JSON.parse(readFileSync(join(REPO, 'research', 'entry_core_v4', 'configs', 'finalists.json'), 'utf8'));
const NEWS = JSON.parse(readFileSync(join(REPO, 'validation', 'v5_news_edge', 'events_usd_official.json'), 'utf8')).events.map((e) => ({ t: Math.floor(Date.parse(e.utc) / 1000), family: e.family })).filter((e) => e.t >= b5[0].time && e.t <= b5[N - 1].time + 300).sort((a, b) => a.t - b.t);
const POP = {}; POP.CONTROL = C.filter((c) => c.act === 'BUY' || c.act === 'SELL').map((c) => ({ i: c.i, t: c.t, side: c.side, model: c.model, anchor: c.anchor ?? c.geo.entry, geo: { entry: c.geo.entry, sl: c.geo.sl, tp2: c.geo.tp2 }, atr: c.atr, atrR: c.atrR, split: split(c.t), pop: 'CONTROL' }));
{ const g = V4.GRID.find((x) => x.key === V4DEFN.finalists.S3.grid_key); POP.S3 = V4.generate(g).filter((s) => !s.block).map((s) => ({ i: s.i, t: s.t, side: s.side, model: 'C', anchor: s.anchor, geo: { entry: s.geo.entry, sl: s.geo.sl, tp2: s.geo.tp2 }, atr: s.atr, atrR: ROWS.get(s.i)?.atrR ?? null, split: s.split, pop: 'S3' })); }
// ---------- cross-asset series, quality, alignment ----------
const SERIES = { XAG5: XAG['5m'], XAG15: XAG['15m'], DXY5: DXY['5m'], DXY15: DXY['15m'], UST15: UST['15m'] };
const QUALITY = Object.fromEntries(Object.entries(SERIES).map(([k, s]) => [k, dataQuality(s, k.endsWith('15') ? 900 : 300, b5[0].time, b5[N - 1].time)]));
const ALIGN = { XAG5: alignIndex(SERIES.XAG5, 300), XAG15: alignIndex(SERIES.XAG15, 900), DXY5: alignIndex(SERIES.DXY5, 300), DXY15: alignIndex(SERIES.DXY15, 900), UST15: alignIndex(SERIES.UST15, 900) };
const ATR = { XAG5: atr14Series(SERIES.XAG5), XAG15: atr14Series(SERIES.XAG15), DXY5: atr14Series(SERIES.DXY5), DXY15: atr14Series(SERIES.DXY15), UST15: atr14Series(SERIES.UST15) };
const goldRelVol = new Array(N).fill(null), spreadRank = new Array(N).fill(null), spreadMedRatio = new Array(N).fill(null); { for (let t = 48; t < N; t++) { let s = 0; for (let q = 1; q <= 48; q++) s += b5[t - q].volume; goldRelVol[t] = s ? b5[t].volume / (s / 48) : null; } for (let t = 300; t < N; t++) { let below = 0; const w = []; for (let q = 1; q <= 288; q++) { const v = b5[t - q].spread_pts; w.push(v); if (v < b5[t].spread_pts) below++; } w.sort((a, b) => a - b); spreadRank[t] = below / 288; spreadMedRatio[t] = b5[t].spread_pts / w[144]; } }
const P0 = { silver_opp: 0.75, silver_conf: 0.5, dxy_with: 0.75, dxy_shock: 2.5, ustec: 0.75, act_div: 0.7, macro_win: 120, spread_p: 0.9, delay: 0 };
function features(e, p = P0) { const i = e.i; const tClose = b5[i].time + 300 - p.delay * 300; const sgn = e.side === 'BUY' ? 1 : -1; const cf = crossFeatures({ tClose, series: SERIES, align: ALIGN, atr: ATR }); const gAct = goldRelVol[i];
  let release = null, approaching = false; for (const ev of NEWS) { if (ev.t > b5[i].time + 300 && ev.t - (b5[i].time + 300) <= 30 * 60) approaching = true; if (ev.t <= b5[i].time + 300 && (b5[i].time + 300) - ev.t <= p.macro_win * 60) release = ev; } let reaction = null; if (release) { const j = b5.findIndex((b, k) => k > i - 60 && b.time >= release.t); if (j >= 0 && j < i && b5[j].time + 300 <= b5[i].time + 300) reaction = Math.sign(b5[j].close - b5[j].open) || 0; }
  return { ...cf, gold_act: r3(gAct), spread_rank: r3(spreadRank[i]), spread_med_ratio: r3(spreadMedRatio[i]), release_family: release?.family ?? null, release_reaction: reaction, approaching, sgn }; }
for (const pop of Object.keys(POP)) for (const e of POP[pop]) e.f = features(e);
console.log(`phase ${PHASE}; populations ${Object.entries(POP).map(([k, v]) => `${k}:${v.length}`).join(' ')}; news ${NEWS.length}`);
const NA = (v) => v == null;
const RULES = {
  'N1 SILVER_OPPOSE': { source: 'XAGUSDm', param: 'silver_opp', pred: (f, p) => (NA(f.silver_mom6) ? false : f.sgn * f.silver_mom6 <= -p.silver_opp), na: (f) => NA(f.silver_mom6) },
  'N2 SILVER_CONFIRM': { source: 'XAGUSDm', param: 'silver_conf', pred: (f, p) => (NA(f.silver_mom6) ? false : !(f.sgn * f.silver_mom6 >= p.silver_conf)), na: (f) => NA(f.silver_mom6) },
  'N3 DXY_WITH': { source: 'DXYm', param: 'dxy_with', pred: (f, p) => (NA(f.dxy_mom6) ? false : f.sgn * f.dxy_mom6 >= p.dxy_with), na: (f) => NA(f.dxy_mom6) },
  'N4 DXY_SHOCK': { source: 'DXYm', param: 'dxy_shock', pred: (f, p) => (NA(f.dxy_range_mult) ? false : f.dxy_range_mult >= p.dxy_shock), na: (f) => NA(f.dxy_range_mult) },
  'N5 USTEC_RISK': { source: 'USTECm', param: 'ustec', pred: (f, p) => (NA(f.ustec_mom2) ? false : f.sgn * f.ustec_mom2 >= p.ustec), na: (f) => NA(f.ustec_mom2) },
  'N6 ACTIVITY_DIVERGENCE': { source: 'XAGUSDm tick volume + XAUUSDm tick volume', param: 'act_div', pred: (f, p) => (NA(f.silver_act) || NA(f.gold_act) ? false : f.gold_act >= 1.5 && f.silver_act <= p.act_div), na: (f) => NA(f.silver_act) || NA(f.gold_act) },
  'N7 MACRO_REACTION': { source: 'official release timestamps + XAUUSD price (DERIVED)', param: 'macro_win', pred: (f) => f.approaching || (f.release_reaction != null && f.release_reaction !== 0 && f.sgn !== f.release_reaction), na: () => false },
  'N8 SPREAD_STATE': { source: 'XAUUSDm broker spread (execution state)', param: 'spread_p', pred: (f, p) => (NA(f.spread_rank) ? false : f.spread_rank > p.spread_p || f.spread_med_ratio >= 1.5), na: (f) => NA(f.spread_rank) },
};
const GRIDS = { silver_opp: [0.5, 0.75, 1.0], silver_conf: [0.3, 0.5, 0.75], dxy_with: [0.5, 0.75, 1.0], dxy_shock: [2.0, 2.5, 3.0], ustec: [0.5, 0.75, 1.0], act_div: [0.6, 0.7, 0.8], macro_win: [60, 120, 180], spread_p: [0.85, 0.9, 0.95] };
const CANDS = Object.keys(RULES);

// ---------- outcomes ----------
const MEMO = new Map();
function out(e, kind = 'ctl', cse = 'normal', drift = false) { const key = `${e.pop}|${e.i}|${e.side}|${kind}|${cse}|${drift}`; const m = MEMO.get(key); if (m) return m; const pol = kind === 'open' ? { type: 'OPEN' } : e.pop === 'CONTROL' ? { type: 'FIXED', tpPrice: e.geo.tp2 } : { type: 'FIXED', rr: 1.7 }; const o = simulate(b5, e, pol, COSTS[cse], { drift }); MEMO.set(key, o); return o; }
for (const pop of Object.keys(POP)) for (const e of POP[pop]) { const o = out(e, 'open'); e.open = o; e.wrong = o.status !== 'NO_DATA' && o.mfe_r < 0.5 && (o.exit === 'BROKER_SL' || o.exit === 'THESIS_INVALIDATION'); e.bad = o.status !== 'NO_DATA' && o.milestones[1] == null; e.right = o.status !== 'NO_DATA' && o.milestones[1] != null; }
const rowsOf = (sigs, cse = 'normal', drift = false) => sigs.map((e) => ({ e, o: out(e, 'ctl', cse, drift) })).filter((x) => x.o.status !== 'NO_DATA' && x.o.status !== 'INVALID');
const inS = (S) => (e) => S === 'ALL' || e.split === S;

// ---------- controls ----------
const ctrl = (() => { const rand = rng(99); const leak = [], nul = []; for (let t = 600; t < N - 300; t += 37) { if (!ROWS.has(t)) continue; const a = F.atr[t]; const fut = b5[t + 12].close - b5[t].close; const mk = (side) => ({ i: t, side, atr: a, pop: 'X', geo: { entry: b5[t].close, sl: side === 'BUY' ? b5[t].close - a : b5[t].close + a } }); const o1 = simulate(b5, mk(fut >= 0 ? 'BUY' : 'SELL'), { type: 'FIXED', rr: 1 }), o2 = simulate(b5, mk(rand() < 0.5 ? 'BUY' : 'SELL'), { type: 'FIXED', rr: 1 }); if (o1.status !== 'NO_DATA' && !o1.gap) leak.push(o1.r); if (o2.status !== 'NO_DATA' && !o2.gap) nul.push(o2.r); }
  const sample = POP.CONTROL.slice(0, 400); const diff = mean(sample.map((e) => simulate(b5, e, { type: 'FIXED', tpPrice: e.geo.tp2 }, { spread: 0.24, slip: 0 }).pnl_usd)) - mean(sample.map((e) => simulate(b5, e, { type: 'FIXED', tpPrice: e.geo.tp2 }).pnl_usd)); const firstExitOk = sample.every((e) => { const o = out(e); return o.status === 'NO_DATA' || o.exitBar >= e.i + 1; });
  // prefix invariance of cross-asset features: truncate every cross series at the decision time and recompute
  let prefixOk = true, tested = 0; for (const e of POP.CONTROL.filter((x, k) => k % 37 === 0).slice(0, 200)) { const tClose = b5[e.i].time + 300; const trunc = Object.fromEntries(Object.entries(SERIES).map(([k, s]) => [k, s.filter((b) => b.time + (k.endsWith('15') ? 900 : 300) <= tClose)])); const align2 = { XAG5: alignIndex(trunc.XAG5, 300), XAG15: alignIndex(trunc.XAG15, 900), DXY5: alignIndex(trunc.DXY5, 300), DXY15: alignIndex(trunc.DXY15, 900), UST15: alignIndex(trunc.UST15, 900) }; const atr2 = Object.fromEntries(Object.entries(trunc).map(([k, s]) => [k, atr14Series(s)])); const a = crossFeatures({ tClose, series: SERIES, align: ALIGN, atr: ATR }), b = crossFeatures({ tClose, series: trunc, align: align2, atr: atr2 }); tested++; if (JSON.stringify(a) !== JSON.stringify(b)) prefixOk = false; }
  // timestamp rule: no feature bar closes after the decision
  let tsOk = true; for (const e of POP.CONTROL.slice(0, 2000)) { const tClose = b5[e.i].time + 300; for (const k of ['xag5_bar_close', 'dxy_bar_close', 'ustec_bar_close']) if (e.f[k] != null && e.f[k] > tClose) tsOk = false; }
  return { leak_mean_r: r3(mean(leak)), leak_n: leak.length, null_mean_r: r3(mean(nul)), null_n: nul.length, cost_test: { diff: r3(diff), expected: 0.10, pass: Math.abs(diff - 0.10) < 0.001 }, first_exit_after_entry: firstExitOk, cross_prefix_invariance: prefixOk, prefix_tested: tested, timestamp_rule_no_future_bar: tsOk }; })();
console.log('controls', JSON.stringify(ctrl)); if (!(ctrl.leak_mean_r > 0.3) || !(Math.abs(ctrl.null_mean_r) < 0.15) || !ctrl.cost_test.pass || !ctrl.first_exit_after_entry || !ctrl.cross_prefix_invariance || !ctrl.timestamp_rule_no_future_bar) throw new Error('CONTROL FAILED');

// ---------- live / replay parity (shadow observer records) ----------
function parity() { const p = join(REPO, 'state', 'shadow', 'observations.jsonl'); if (!existsSync(p)) return { available: false }; const obs = readFileSync(p, 'utf8').split('\n').filter(Boolean).map((l) => { try { return JSON.parse(l); } catch { return null; } }).filter((o) => o && o.cross_asset); const res = {}; const idxOf = { XAGUSDm: new Map(SERIES.XAG15.map((b, i) => [b.time, i])), DXYm: new Map(SERIES.DXY15.map((b, i) => [b.time, i])), USTECm: new Map(SERIES.UST15.map((b, i) => [b.time, i])) }; const ser = { XAGUSDm: SERIES.XAG15, DXYm: SERIES.DXY15, USTECm: SERIES.UST15 };
  for (const sym of ['XAGUSDm', 'DXYm', 'USTECm']) { let comparable = 0, closeMatch = 0, retMatch = 0, zMatch = 0, staleLive = 0; const zd = []; for (const o of obs) { const c = o.cross_asset[sym]; if (!c) continue; if (!c.available) { staleLive++; continue; } const i = idxOf[sym].get(c.bar_time); if (i == null || i < 100) continue; comparable++; const S = ser[sym]; if (Math.abs(S[i].close - c.close) < 1e-6) closeMatch++; const ret = Math.log(S[i].close / S[i - 1].close); if (Math.abs(ret - c.ret_15m) < 1e-4) retMatch++; /* shadow core lastReturnZ: z of the last return against the 96 returns BEFORE it, population sd */ const rets = []; for (let k = i - 96; k < i; k++) rets.push(Math.log(S[k].close / S[k - 1].close)); const m = mean(rets); const sd = Math.sqrt(rets.reduce((a, b) => a + (b - m) * (b - m), 0) / rets.length); const z = (ret - m) / sd; zd.push(Math.abs(z - c.z_96)); if (Math.abs(z - c.z_96) <= PARITY_TOL.z) zMatch++; } res[sym] = { live_records: obs.filter((o) => o.cross_asset[sym]).length, live_stale: staleLive, comparable, close_match_rate: comparable ? r3(closeMatch / comparable) : null, ret_match_rate: comparable ? r3(retMatch / comparable) : null, z_match_rate: comparable ? r3(zMatch / comparable) : null, z_abs_diff_median: r3(median(zd)), z_abs_diff_p95: r3(pct(zd, 0.95)), pass: comparable >= 50 && closeMatch / comparable >= 0.95 && retMatch / comparable >= 0.95 }; } return { available: true, records: obs.length, first: obs[0]?.decision_time_utc, last: obs[obs.length - 1]?.decision_time_utc, tolerance: PARITY_TOL, by_symbol: res, pass: Object.values(res).every((r) => r.pass) }; }
const PARITY = parity(); console.log('parity', JSON.stringify(PARITY));

// ---------- statistics (as V6) ----------
function seqWalk(rows) { const trades = []; let exitBar = -1, lastTrade = null, lastLoss = false; const skipped = { SAME_OR_EARLIER_CANDLE: 0, STALE_SAME_SETUP: 0, REVENGE_GUARD: 0 }; const occ = []; for (const x of [...rows].sort((a, b) => a.e.i - b.e.i)) { const ok = canReenter({ signal: x.e, exitBar, lastTrade, lastExitWasLoss: lastLoss }); if (!ok.ok) { skipped[ok.reason] = (skipped[ok.reason] ?? 0) + 1; continue; } trades.push(x); occ.push([x.e.i, x.o.exitBar]); exitBar = x.o.exitBar; lastTrade = x.e; lastLoss = x.o.r <= 0; } return { trades, skipped, occ }; }
function pathDD(rows, key = 'r') { let cum = 0, peak = 0, dd = 0, streak = 0, maxStreak = 0; for (const x of rows) { cum += x.o[key]; if (cum > peak) peak = cum; dd = Math.max(dd, peak - cum); if (x.o[key] <= 0) { streak++; maxStreak = Math.max(maxStreak, streak); } else streak = 0; } return { max_dd: r2(dd), final: r2(cum), max_loss_streak: maxStreak }; }
function stats(rows, sessSet = null, { ci = true, block = false } = {}) { const R = rows.map((x) => x.o.r); if (!R.length) return { n: 0 }; const w = R.filter((x) => x > 0), l = R.filter((x) => x <= 0); const gw = w.reduce((a, b) => a + b, 0), gl = -l.reduce((a, b) => a + b, 0); const U = rows.map((x) => x.o.pnl_usd); const perDay = {}; for (const x of rows) perDay[day(x.e.t)] = (perDay[day(x.e.t)] ?? 0) + 1; const counts = sessSet ? [...sessSet].map((d) => perDay[d] ?? 0) : null; const costU = rows.reduce((s, x) => s + x.o.cost_usd, 0); const ddR = pathDD(rows, 'r'), ddU = pathDD(rows, 'pnl_usd');
  return { n: R.length, win_rate: r3(w.length / R.length), avg_win_r: r3(mean(w)), avg_loss_r: l.length ? r3(-mean(l)) : null, expectancy_r: r3(mean(R)), expectancy_usd: r3(mean(U)), pf: gl > 0 ? r2(gw / gl) : (gw > 0 ? 99 : null), ci95_r: ci ? bootCI(R) : null, ci99_r: ci ? bootCI(R, 2000, 20260930, 0.01) : null, block_ci95_r: block ? blockCI(rows) : null, block_ci99_r: block ? blockCI(rows, 2000, 7, 0.01) : null, max_dd_r: ddR.max_dd, max_dd_usd: ddU.max_dd, net_r: ddR.final, max_loss_streak: ddR.max_loss_streak, wrong_direction_rate: r3(rows.filter((x) => x.e.wrong).length / R.length), bad_entry_rate: r3(rows.filter((x) => x.e.bad).length / R.length), right_direction_rate: r3(rows.filter((x) => x.e.right).length / R.length), open_path_unresolved: rows.filter((x) => x.e.open.status === 'NO_DATA').length, mfe_open_r: r3(mean(rows.map((x) => x.e.open.mfe_r).filter((v) => v != null))), mae_r: r3(mean(rows.map((x) => x.o.mae_r))), mfe_r: r3(mean(rows.map((x) => x.o.mfe_r))), giveback_r: r3(mean(rows.filter((x) => x.o.mfe_r >= 0.5).map((x) => x.o.mfe_r - x.o.r))), reach_1r: r3(rows.filter((x) => x.e.open.milestones?.[1] != null).length / R.length), reach_1_7r: r3(rows.filter((x) => x.e.open.milestones?.[1.7] != null).length / R.length), stop_reach: r3(rows.filter((x) => x.o.exit === 'BROKER_SL' || x.o.exit === 'THESIS_INVALIDATION').length / R.length), avg_bars: r2(mean(rows.map((x) => x.o.bars))), cost_usd: r3(costU / R.length), trades_per_session: counts ? { median: pct(counts, 0.5), p90: pct(counts, 0.9), mean: r2(mean(counts)) } : null, zero_trade_session_rate: counts ? r3(counts.filter((x) => x === 0).length / counts.length) : null, side_mix: rows.reduce((g, x) => { g[x.e.side] = (g[x.e.side] ?? 0) + 1; return g; }, {}), risk_usd_mean: r3(mean(rows.map((x) => Math.abs(x.e.geo.entry - x.e.geo.sl)))) }; }
const cell = (rows) => { const s = stats(rows, null, { ci: rows.length >= 30 }); return { n: s.n ?? 0, win_rate: s.win_rate, avg_win_r: s.avg_win_r, avg_loss_r: s.avg_loss_r, expectancy_r: s.expectancy_r, pf: s.pf, max_dd_r: s.max_dd_r, wrong_direction_rate: s.wrong_direction_rate, bad_entry_rate: s.bad_entry_rate, mfe_open_r: s.mfe_open_r, mae_r: s.mae_r, ci95_r: s.ci95_r }; };
const byState = (rows, f) => { const g = {}; for (const x of rows) (g[String(f(x.e))] ??= []).push(x); return Object.fromEntries(Object.entries(g).sort((a, b) => b[1].length - a[1].length).map(([k, v]) => [k, cell(v)])); };
function captureStats(S, rows, occ = []) { const by = {}; for (const x of rows) (by[x.e.i] ??= []).push(x.e.side); let valid = 0, late = 0, wrong = 0, none = 0, positioned = 0, noSetup = 0, gate = 0; for (const ev of EVENTS[S]) { let e = false, l = false, w = false; for (let j = ev.k - 6; j <= ev.k + 6; j++) for (const s of by[j] ?? []) { if (s === ev.dir) { if (j <= ev.k) e = true; else l = true; } else w = true; } if (e) valid++; else if (l) late++; else if (w) wrong++; else if (occ.some(([a, b]) => ev.k >= a && ev.k <= b)) positioned++; else { none++; const r = ROWS.get(ev.k); if (!r || r.wr === 'NO_ELIGIBLE_STRATEGY' || r.wr === 'CHOP') noSetup++; else gate++; } } const n = Math.max(1, EVENTS[S].length); return { events: EVENTS[S].length, capture_rate: r3((valid + late) / n), valid_entry_rate: r3(valid / n), late_entry_rate: r3(late / n), wrong_direction_rate: r3(wrong / n), already_positioned_rate: r3(positioned / n), no_signal_rate: r3(none / n), no_setup_or_trigger_rate: r3(noSetup / n), gate_or_filter_rate: r3(gate / n) }; }
function blockedByFilter(S, allRows, keptRows) { const by = (rows) => { const m = {}; for (const x of rows) (m[x.e.i] ??= []).push(x.e.side); return m; }; const A = by(allRows), K = by(keptRows); let blocked = 0; for (const ev of EVENTS[S]) { let had = false, kept = false; for (let j = ev.k - 6; j <= ev.k + 6; j++) { if ((A[j] ?? []).includes(ev.dir)) had = true; if ((K[j] ?? []).includes(ev.dir)) kept = true; } if (had && !kept) blocked++; } return r3(blocked / Math.max(1, EVENTS[S].length)); }
function tinyCells(trades) { const cells = {}; for (const x of trades) (cells[`${x.e.model}|${x.e.side}|${ROWS.get(x.e.i)?.rg5 ?? 'NA'}`] ??= []).push(x.o.r); const net = trades.reduce((s, x) => s + x.o.r, 0); let maxTiny = 0, maxCell = null; const list = Object.entries(cells).map(([k, v]) => { const s = v.reduce((a, b) => a + b, 0); if (v.length < 30 && s > 0 && s > maxTiny) { maxTiny = s; maxCell = k; } return { cell: k, n: v.length, net_r: r2(s), share_of_net: net > 0 ? r3(s / net) : null }; }).sort((a, b) => b.net_r - a.net_r); return { top: list.slice(0, 8), max_tiny_cell: maxCell, max_tiny_cell_share: net > 0 ? r3(maxTiny / net) : null, pass: !(net > 0) || maxTiny / net <= 0.30 }; }
function adverse(trades) { if (!trades.length) return null; const rand = rng(11); const byM = {}; for (const x of trades) (byM[month(x.e.t)] ??= []).push(x.o.r); const dds = [], streaks = []; for (let k = 0; k < 500; k++) { const order = Object.values(byM).sort(() => rand() - 0.5); let cum = 0, peak = 0, dd = 0, stk = 0, ms = 0; for (const m of order) for (const r of [...m].sort(() => rand() - 0.5)) { cum += r; peak = Math.max(peak, cum); dd = Math.max(dd, peak - cum); if (r <= 0) { stk++; ms = Math.max(ms, stk); } else stk = 0; } dds.push(dd); streaks.push(ms); } return { dd_r_p50: r2(median(dds)), dd_r_p90: r2(pct(dds, 0.9)), dd_r_p99: r2(pct(dds, 0.99)), loss_streak_p50: median(streaks), loss_streak_p90: pct(streaks, 0.9) }; }
function capital(trades) { if (!trades.length) return null; const ddU = pathDD(trades, 'pnl_usd'); const margin = r2(mean(trades.map((x) => x.e.geo.entry)) * 100 * 0.01 / 200); const risk = mean(trades.map((x) => 1.5 * Math.abs(x.e.geo.entry - x.e.geo.sl) + 0.24)); return { lot: 0.01, net_usd: ddU.final, max_dd_usd: ddU.max_dd, mean_broker_sl_usd: r2(risk), margin_usd_approx: margin, by_capital: Object.fromEntries([62, 100, 1000, 10000].map((cap) => [cap, { max_dd_pct: r3(ddU.max_dd / cap), risk_pct: r3(risk / cap), margin_pct: r3(margin / cap), feasible_001_lot: cap >= 71 ? 'YES' : 'NO (MARGIN_SAFETY_VETO: equity below ~71 USD)' }])) }; }
function filteredEval(pop, S, pred, { full = false, allRows = null, p = P0 } = {}) { const sigs = POP[pop].filter(inS(S)); const feats = p === P0 ? (e) => e.f : (e) => features(e, p); const kept = sigs.filter((e) => !pred(feats(e), p)); const naCount = sigs.filter((e) => pred.na ? pred.na(feats(e)) : false).length; const rows = rowsOf(kept); const w = seqWalk(rows); const st = stats(w.trades, sessions[S], { ci: w.trades.length >= 30, block: full }); const all = allRows ?? rowsOf(sigs); const res = { signals_in: sigs.length, signals_kept: kept.length, wait_share: r3(1 - kept.length / Math.max(1, sigs.length)), na_share: r3(naCount / Math.max(1, sigs.length)), ...st, skipped: w.skipped, independent: cell(rows), move_capture: captureStats(S, rows, w.occ), blocked_events_share: blockedByFilter(S, all, rows) }; if (full) { const q = {}; for (const x of w.trades) (q[quarter(x.e.t)] ??= []).push(x); res.walk_forward = Object.fromEntries(Object.entries(q).sort().map(([k, v]) => { const s = stats(v, null, { ci: false }); return [k, { n: s.n, expectancy_r: s.expectancy_r, pf: s.pf, max_dd_r: s.max_dd_r, wrong_direction_rate: s.wrong_direction_rate, trades_per_session: r2(v.length / new Set(v.map((x) => day(x.e.t))).size) }]; })); res.quarters_positive_share = Object.keys(res.walk_forward).length ? r3(Object.values(res.walk_forward).filter((v) => v.expectancy_r > 0).length / Object.keys(res.walk_forward).length) : null; const stress = stats(seqWalk(rowsOf(kept, 'stress')).trades, null, { ci: false }); res.stress = { n: stress.n ?? 0, expectancy_r: stress.expectancy_r, pf: stress.pf }; const drift = stats(seqWalk(rowsOf(kept, 'normal', true)).trades, null, { ci: false }); res.drift = { n: drift.n ?? 0, expectancy_r: drift.expectancy_r, pf: drift.pf }; res.tiny_cells = tinyCells(w.trades); res.by_side = byState(w.trades, (e) => e.side); res.adverse = adverse(w.trades); res.capital = capital(w.trades); } return res; }
const mkPred = (name, p) => { const r = RULES[name]; const f = (feat, pp) => r.pred(feat, pp ?? p); f.na = r.na; return f; };

// ---------- family state tables (descriptive, one source at a time) ----------
const STATES = { silver_mom6: (f) => (NA(f.silver_mom6) ? 'NA' : f.sgn * f.silver_mom6 <= -0.75 ? 'OPPOSES_STRONG' : f.sgn * f.silver_mom6 <= -0.3 ? 'OPPOSES' : f.sgn * f.silver_mom6 >= 0.75 ? 'AGREES_STRONG' : f.sgn * f.silver_mom6 >= 0.3 ? 'AGREES' : 'FLAT'), silver_act: (f) => (NA(f.silver_act) ? 'NA' : f.silver_act < 0.7 ? 'LOW' : f.silver_act > 1.5 ? 'HIGH' : 'NORMAL'), activity_divergence: (f) => (NA(f.silver_act) || NA(f.gold_act) ? 'NA' : f.gold_act >= 1.5 && f.silver_act <= 0.7 ? 'GOLD_ONLY' : f.gold_act >= 1.5 && f.silver_act >= 1.5 ? 'BOTH_HIGH' : f.gold_act < 0.7 && f.silver_act >= 1.5 ? 'SILVER_ONLY' : 'OTHER'), dxy_mom6: (f) => (NA(f.dxy_mom6) ? 'NA' : f.sgn * f.dxy_mom6 >= 0.75 ? 'WITH_STRONG' : f.sgn * f.dxy_mom6 >= 0.3 ? 'WITH' : f.sgn * f.dxy_mom6 <= -0.75 ? 'AGAINST_STRONG' : f.sgn * f.dxy_mom6 <= -0.3 ? 'AGAINST' : 'FLAT'), dxy_source: (f) => f.dxy_source ?? 'NA', dxy_shock: (f) => (NA(f.dxy_range_mult) ? 'NA' : f.dxy_range_mult >= 2.5 ? 'SHOCK' : 'NORMAL'), ustec_mom2: (f) => (NA(f.ustec_mom2) ? 'NA' : f.sgn * f.ustec_mom2 >= 0.75 ? 'RISK_WITH_STRONG' : f.sgn * f.ustec_mom2 >= 0.3 ? 'RISK_WITH' : f.sgn * f.ustec_mom2 <= -0.75 ? 'RISK_AGAINST_STRONG' : f.sgn * f.ustec_mom2 <= -0.3 ? 'RISK_AGAINST' : 'FLAT'), macro: (f) => (f.approaching ? 'APPROACHING_30M' : f.release_reaction == null ? 'NO_RELEASE' : f.release_reaction === 0 ? 'POST_RELEASE_FLAT' : f.sgn === f.release_reaction ? 'POST_RELEASE_WITH_REACTION' : 'POST_RELEASE_AGAINST_REACTION'), spread_state: (f) => (NA(f.spread_rank) ? 'NA' : f.spread_med_ratio >= 1.5 ? 'EXPANDED_1.5x' : f.spread_rank > 0.9 ? 'HIGH_P90' : f.spread_rank < 0.1 ? 'LOW_P10' : 'NORMAL') };
function stateTables(pop, S) { const rows = rowsOf(POP[pop].filter(inS(S))); const base = cell(rows); const out = { base, states: {} }; for (const [k, f] of Object.entries(STATES)) out.states[k] = byState(rows, (e) => f(e.f)); return out; }
// redundancy with V6 flags
const V6FLAGS = { htf_aligned: (e) => { const r = ROWS.get(e.i) ?? {}; const d = (s) => (s === 'BULLISH' ? 'BUY' : s === 'BEARISH' ? 'SELL' : null); return d(r.m30s) === e.side && d(r.h1s) === e.side; }, mom_supportive: (e) => { const m = F.mom6[e.i] ?? 0; return Math.sign(m) === (e.side === 'BUY' ? 1 : -1) && Math.abs(m) >= 0.3; }, regime_trend_with: (e) => { const rg = ROWS.get(e.i)?.rg5; return (rg === 'BULL_TREND' && e.side === 'BUY') || (rg === 'BEAR_TREND' && e.side === 'SELL'); }, gold_vol_high: (e) => (e.f.gold_act ?? 0) > 1.5, gold_shock: (e) => (e.atrR ?? 0) >= 1.5 || [0, 1, 2].some((q) => (b5[e.i - q].high - b5[e.i - q].low) / e.atr >= 3), news_window: (e) => e.f.release_reaction != null || e.f.approaching, session_ny: (e) => ROWS.get(e.i)?.ses === 'NEW_YORK' };
function redundancy(pop, S, defn) { const sigs = POP[pop].filter(inS(S)); const newFlags = Object.fromEntries(CANDS.map((k) => [k, (e) => mkPred(k, paramsFor(defn, k))(e.f)])); const all = { ...newFlags, ...V6FLAGS }; const keys = Object.keys(all); const vals = sigs.map((e) => Object.fromEntries(keys.map((k) => [k, all[k](e) ? 1 : 0]))); const phi = {}; for (const a of CANDS) for (const b of keys) { if (a === b) continue; let n11 = 0, n10 = 0, n01 = 0, n00 = 0; for (const v of vals) { const x = v[a], y = v[b]; if (x && y) n11++; else if (x) n10++; else if (y) n01++; else n00++; } const den = Math.sqrt((n11 + n10) * (n01 + n00) * (n11 + n01) * (n10 + n00)); phi[`${a}~${b}`] = den ? r3((n11 * n00 - n10 * n01) / den) : null; } return { rates: Object.fromEntries(keys.map((k) => [k, r3(vals.filter((v) => v[k]).length / vals.length)])), phi, redundant_pairs: Object.entries(phi).filter(([, v]) => v != null && Math.abs(v) >= 0.5).map(([k, v]) => `${k} (${v})`) }; }
const paramsFor = (defn, name) => ({ ...P0, [RULES[name].param]: defn.finalists[name].value });

// ---------- run ----------
const result = { meta: { phase: PHASE, generated_utc: new Date().toISOString(), prereg_sha256: PREREG_SHA, control_baseline_sha256: CONTROL_SHA, controls: ctrl, parity: PARITY, data_quality: QUALITY, series_hashes: { XAGUSDm: shaFile(join(LAB, 'XAGUSDm_bars.json')), DXYm: shaFile(join(LAB, 'DXYm_bars.json')), USTECm: shaFile(join(LAB, 'USTECm_bars.json')), news: shaFile(join(REPO, 'validation', 'v5_news_edge', 'events_usd_official.json')) }, populations: Object.fromEntries(Object.keys(POP).map((k) => [k, { all: POP[k].length, dev: POP[k].filter((e) => e.split === 'DEV').length, hold: POP[k].filter((e) => e.split === 'HOLD').length }])), params: P0, grids: GRIDS, candidates: Object.fromEntries(CANDS.map((k) => [k, { source: RULES[k].source, param: RULES[k].param }])), split: SPLIT, costs: COSTS, events: { DEV: EVENTS.DEV.length, HOLD: EVENTS.HOLD.length }, news_events_in_range: NEWS.length, na_rates: Object.fromEntries(CANDS.map((k) => [k, r3(POP.CONTROL.filter((e) => RULES[k].na(e.f)).length / POP.CONTROL.length)])) } };
console.log('DEV ...'); result.DEV = { tables: {}, grid: {} }; for (const pop of ['CONTROL', 'S3']) { result.DEV.tables[pop] = stateTables(pop, 'DEV'); const allRows = rowsOf(POP[pop].filter(inS('DEV'))); result.DEV.grid[pop] = { CONTROL: filteredEval(pop, 'DEV', Object.assign(() => false, { na: () => false }), { allRows }) }; for (const k of CANDS) for (const v of GRIDS[RULES[k].param]) { const p = { ...P0, [RULES[k].param]: v }; result.DEV.grid[pop][`${k}|${v}`] = filteredEval(pop, 'DEV', mkPred(k, p), { allRows, p }); } }
{ const c = result.DEV.grid.CONTROL.CONTROL; const v6 = JSON.parse(readFileSync(join(REPO, 'research', 'information_edge_v6', 'results', 'v6_results.json'), 'utf8')).DEV.candidates.CONTROL.CONTROL; if (c.n !== v6.n || c.expectancy_r !== v6.expectancy_r || c.max_dd_r !== v6.max_dd_r || c.wrong_direction_rate !== v6.wrong_direction_rate || c.move_capture.capture_rate !== v6.move_capture.capture_rate) throw new Error(`CONTROL does not reproduce V6 DEV: ${c.n} ${c.expectancy_r} ${c.max_dd_r} ${c.wrong_direction_rate}`); result.meta.controls.control_reproduces_v6_dev = true; }
const defPath = join(CFG, 'finalists.json');
function derive() { const fin = {}; for (const k of CANDS) { const pts = GRIDS[RULES[k].param].map((v) => ({ v, r: result.DEV.grid.CONTROL[`${k}|${v}`] })); const elig = pts.filter((x) => x.r.n >= 200); const chosen = (elig.length ? elig : pts).sort((a, b) => (b.r.expectancy_r ?? -9) - (a.r.expectancy_r ?? -9) || Math.abs(GRIDS[RULES[k].param].indexOf(a.v) - 1) - Math.abs(GRIDS[RULES[k].param].indexOf(b.v) - 1))[0]; const base = result.DEV.grid.CONTROL.CONTROL; fin[k] = { source: RULES[k].source, param: RULES[k].param, value: chosen.v, dev_n: chosen.r.n, dev_expectancy_r: chosen.r.expectancy_r, dev_improvement_r: r3(chosen.r.expectancy_r - base.expectancy_r), dev_wd: chosen.r.wrong_direction_rate, dev_wd_lower: chosen.r.wrong_direction_rate < base.wrong_direction_rate, dev_incremental: chosen.r.n >= 200 && chosen.r.expectancy_r - base.expectancy_r >= 0.05 && chosen.r.wrong_direction_rate < base.wrong_direction_rate, wait_share: chosen.r.wait_share, na_share: chosen.r.na_share }; } const inc = CANDS.filter((k) => fin[k].dev_incremental); return { derived_from: 'DEV', finalists: fin, combination: inc.length >= 2 ? { components: inc.slice(0, 3), rule: 'intersection of WAITs (WAIT if any component waits)' } : { components: [], rule: 'no combination: fewer than two sources have DEV incremental value' }, candidates: [...CANDS, ...(inc.length >= 2 ? ['N9 COMBINATION'] : [])] }; }
function candPred(defn, name) { if (name === 'N9 COMBINATION') { const comps = defn.combination.components; const f = (feat) => comps.some((k) => mkPred(k, paramsFor(defn, k))(feat)); f.na = () => false; return f; } return mkPred(name, paramsFor(defn, name)); }
if (PHASE === 'DEV') { const defn = derive(); result.finalist_definitions = defn; result.DEV.candidates = {}; for (const pop of ['CONTROL', 'S3']) { const allRows = rowsOf(POP[pop].filter(inS('DEV'))); result.DEV.candidates[pop] = { CONTROL: filteredEval(pop, 'DEV', Object.assign(() => false, { na: () => false }), { allRows }) }; for (const k of defn.candidates) result.DEV.candidates[pop][k] = filteredEval(pop, 'DEV', candPred(defn, k), { allRows, p: k === 'N9 COMBINATION' ? P0 : paramsFor(defn, k) }); } result.DEV.redundancy = redundancy('CONTROL', 'DEV', defn); writeFileSync(defPath, JSON.stringify(defn, null, 1)); writeFileSync(join(OUT, 'v7_results_DEV_phase.json'), JSON.stringify(result, null, 1)); console.log('DERIVED', JSON.stringify(defn.finalists)); console.log('COMBO', JSON.stringify(defn.combination)); console.log('finalists.json sha256', shaFile(defPath)); }
else { const defn = JSON.parse(readFileSync(defPath, 'utf8')); const frozen = readFileSync(join(CFG, 'finalists.sha256'), 'utf8').trim().split(/\s+/)[0]; if (shaFile(defPath) !== frozen) throw new Error('finalists.json does not match its frozen hash'); result.finalist_definitions = defn; result.finalists_sha256 = frozen;
  for (const S of ['DEV', 'HOLD']) { if (S === 'HOLD') { result.HOLD = { tables: {}, grid: {} }; for (const pop of ['CONTROL', 'S3']) { result.HOLD.tables[pop] = stateTables(pop, 'HOLD'); const allRows = rowsOf(POP[pop].filter(inS('HOLD'))); result.HOLD.grid[pop] = { CONTROL: filteredEval(pop, 'HOLD', Object.assign(() => false, { na: () => false }), { allRows }) }; for (const k of CANDS) for (const v of GRIDS[RULES[k].param]) { const p = { ...P0, [RULES[k].param]: v }; result.HOLD.grid[pop][`${k}|${v}`] = filteredEval(pop, 'HOLD', mkPred(k, p), { allRows, p }); } } } result[S].candidates = {}; for (const pop of ['CONTROL', 'S3']) { const allRows = rowsOf(POP[pop].filter(inS(S))); result[S].candidates[pop] = { CONTROL: filteredEval(pop, S, Object.assign(() => false, { na: () => false }), { full: true, allRows }) }; for (const k of defn.candidates) result[S].candidates[pop][k] = filteredEval(pop, S, candPred(defn, k), { full: true, allRows, p: k === 'N9 COMBINATION' ? P0 : paramsFor(defn, k) }); } result[S].redundancy = redundancy('CONTROL', S, defn); }
  { const c = result.HOLD.candidates.CONTROL.CONTROL; const v6 = JSON.parse(readFileSync(join(REPO, 'research', 'information_edge_v6', 'results', 'v6_results.json'), 'utf8')).HOLD.candidates.CONTROL.CONTROL; if (c.n !== v6.n || c.expectancy_r !== v6.expectancy_r || c.max_dd_r !== v6.max_dd_r || c.wrong_direction_rate !== v6.wrong_direction_rate || c.move_capture.wrong_direction_rate !== v6.move_capture.wrong_direction_rate) throw new Error('CONTROL does not reproduce V6 HOLD'); const s3 = result.HOLD.candidates.S3.CONTROL, v6s3 = JSON.parse(readFileSync(join(REPO, 'research', 'information_edge_v6', 'results', 'v6_results.json'), 'utf8')).HOLD.candidates.S3.CONTROL; if (s3.n !== v6s3.n || s3.expectancy_r !== v6s3.expectancy_r) throw new Error('S3 does not reproduce V6 HOLD'); result.meta.controls.control_reproduces_v6_hold = true; }
  // delay sensitivity (one extra bar of feed lag) and neighbourhoods on HOLD
  result.delay = {}; result.neighbourhoods = {}; for (const k of defn.candidates) { const base = result.HOLD.candidates.CONTROL[k]; if (k !== 'N9 COMBINATION') { const pD = { ...paramsFor(defn, k), delay: 1 }; const d = filteredEval('CONTROL', 'HOLD', mkPred(k, pD), { p: pD }); result.delay[k] = { hold_expectancy_r: base.expectancy_r, delayed_expectancy_r: d.expectancy_r, delta: r3((d.expectancy_r ?? 0) - (base.expectancy_r ?? 0)), sign_flip: Math.sign(d.expectancy_r ?? 0) !== Math.sign(base.expectancy_r ?? 0) && base.n > 0, pass: Math.abs((d.expectancy_r ?? 0) - (base.expectancy_r ?? 0)) < 0.03 && !(Math.sign(d.expectancy_r ?? 0) !== Math.sign(base.expectancy_r ?? 0) && base.n > 0) }; const nb = {}; for (const v of GRIDS[RULES[k].param]) { const r = result.HOLD.grid.CONTROL[`${k}|${v}`]; nb[`${RULES[k].param}=${v}`] = { n: r.n, expectancy_r: r.expectancy_r, pf: r.pf, wrong_direction_rate: r.wrong_direction_rate }; } const vals = Object.values(nb).map((x) => x.expectancy_r ?? -9); const centre = base.expectancy_r ?? -9; nb.classification = vals.every((x) => x > 0) ? 'ROBUST' : centre > 0 && vals.some((x) => x > 0) ? 'SENSITIVE' : centre > 0 ? 'FRAGILE' : 'NEGATIVE_CENTRE'; result.neighbourhoods[k] = nb; } else { result.neighbourhoods[k] = { classification: base.expectancy_r > 0 ? 'ROBUST (components tested individually)' : 'NEGATIVE_CENTRE' }; result.delay[k] = { pass: true, note: 'components tested individually' }; } }
  // incremental value per candidate, both splits
  result.incremental = {}; for (const S of ['DEV', 'HOLD']) { result.incremental[S] = {}; for (const pop of ['CONTROL', 'S3']) { const base = result[S].candidates[pop].CONTROL; result.incremental[S][pop] = Object.fromEntries(defn.candidates.map((k) => { const v = result[S].candidates[pop][k]; return [k, { n: v.n, expectancy_r: v.expectancy_r, improvement_r: r3((v.expectancy_r ?? 0) - base.expectancy_r), wrong_direction_rate: v.wrong_direction_rate, wd_change: r3((v.wrong_direction_rate ?? 0) - base.wrong_direction_rate), event_wd: v.move_capture.wrong_direction_rate, bad_entry_rate: v.bad_entry_rate, pf: v.pf, max_dd_r: v.max_dd_r, capture: v.move_capture.capture_rate, wait_share: v.wait_share, na_share: v.na_share, incremental: v.n >= 200 && (v.expectancy_r ?? -9) - base.expectancy_r >= 0.05 && v.wrong_direction_rate < base.wrong_direction_rate }]; })); } }
  // ablation of the best candidate (remove the new source = CONTROL; for the combination remove one component at a time)
  const H = result.HOLD.candidates.CONTROL, D = result.DEV.candidates.CONTROL, ctl = H.CONTROL; const dec = {}; const srcPass = (k) => { if (k === 'N9 COMBINATION') return { quality: true, parity: true }; const src = RULES[k].source; const q = src.startsWith('XAGUSDm') ? QUALITY.XAG5.pass : src.startsWith('DXYm') ? QUALITY.DXY5.pass && QUALITY.DXY15.pass : src.startsWith('USTECm') ? QUALITY.UST15.pass : true; const par = src.startsWith('XAGUSDm') ? PARITY.by_symbol?.XAGUSDm?.pass : src.startsWith('DXYm') ? PARITY.by_symbol?.DXYm?.pass : src.startsWith('USTECm') ? PARITY.by_symbol?.USTECm?.pass : true; return { quality: !!q, parity: !!par }; };
  for (const k of defn.candidates) { const c = H[k]; if (!c.n) { dec[k] = { status: 'EMPTY', reasons: ['no trades'] }; continue; } const reasons = []; const sp = srcPass(k); if (!sp.quality || (result.meta.na_rates[k] ?? 0) > 0.05) reasons.push(`(1) data quality (NA share ${result.meta.na_rates[k]})`); if (!result.delay[k].pass) reasons.push(`(2) timestamp/delay sensitivity (Δ ${result.delay[k].delta})`); if (!(c.wrong_direction_rate < ctl.wrong_direction_rate && c.move_capture.wrong_direction_rate < ctl.move_capture.wrong_direction_rate)) reasons.push(`(3) wrong direction not lower (trade ${c.wrong_direction_rate} vs ${ctl.wrong_direction_rate}; events ${c.move_capture.wrong_direction_rate} vs ${ctl.move_capture.wrong_direction_rate})`); if (!(c.bad_entry_rate < ctl.bad_entry_rate)) reasons.push('(4) bad-entry rate not lower'); if (!(c.expectancy_r > 0)) reasons.push('(5) expectancy<=0'); if (!(c.pf > 1.10)) reasons.push('(6) PF<=1.10'); if (!(c.expectancy_r >= ctl.expectancy_r + 0.10 && c.max_dd_r <= ctl.max_dd_r)) reasons.push(`(7) not a meaningful improvement (${c.expectancy_r} vs ${ctl.expectancy_r}; DD ${c.max_dd_r} vs ${ctl.max_dd_r})`); if (!(c.n >= 200)) reasons.push('(8) N<200'); if (!((c.quarters_positive_share ?? 0) >= 0.6)) reasons.push('(9) quarters positive <60%'); if (!result.neighbourhoods[k].classification.startsWith('ROBUST')) reasons.push(`(10) thresholds ${result.neighbourhoods[k].classification}`); if (!(c.stress.expectancy_r > 0)) reasons.push('(11) stress expectancy<=0'); if (!(c.ci95_r?.[0] > 0)) reasons.push('(12) trade CI includes 0'); if (!(c.block_ci95_r?.[0] > 0)) reasons.push('(12) session-block CI includes 0'); if (!(c.move_capture.capture_rate >= 0.5 * ctl.move_capture.capture_rate)) reasons.push('(13) capture < 50 % of CONTROL'); if (!sp.parity) reasons.push('(14) live/replay parity not passed for the source'); if (c.tiny_cells && !c.tiny_cells.pass) reasons.push('tiny-cell dependence'); if (!(D[k].expectancy_r > 0)) reasons.push('DEV expectancy<=0'); if (!(c.drift.expectancy_r > 0)) reasons.push('drift expectancy<=0'); const onlyCI = reasons.length > 0 && reasons.every((r) => r.startsWith('(12)')); dec[k] = { status: reasons.length ? (onlyCI ? 'PROMISING_INCONCLUSIVE (fails only the CI requirement)' : 'FAILS_GATE') : 'PASS', reasons, hold_n: c.n, hold_expectancy_r: c.expectancy_r, hold_pf: c.pf, hold_dd_r: c.max_dd_r, ci95_r: c.ci95_r, block_ci95_r: c.block_ci95_r, wrong_direction_rate: c.wrong_direction_rate, event_wd: c.move_capture.wrong_direction_rate, bad_entry_rate: c.bad_entry_rate, capture: c.move_capture.capture_rate, wait_share: c.wait_share, na_share: c.na_share, dev_expectancy_r: D[k].expectancy_r, stress_r: c.stress.expectancy_r, source: k === 'N9 COMBINATION' ? defn.combination.components.join(' + ') : RULES[k].source }; }
  const passing = Object.entries(dec).filter(([, d]) => d.status === 'PASS').map(([k]) => k); const withN = Object.entries(dec).filter(([, d]) => d.hold_n >= 200); const best = passing[0] ?? (withN.sort((a, b) => (b[1].hold_expectancy_r ?? -9) - (a[1].hold_expectancy_r ?? -9))[0]?.[0] ?? null); const b = best ? H[best] : null;
  result.ablation = best ? { best, HOLD: { with_source: { n: b.n, expectancy_r: b.expectancy_r, wrong_direction_rate: b.wrong_direction_rate, capture: b.move_capture.capture_rate }, without_source: { n: ctl.n, expectancy_r: ctl.expectancy_r, wrong_direction_rate: ctl.wrong_direction_rate, capture: ctl.move_capture.capture_rate }, delta_expectancy: r3(b.expectancy_r - ctl.expectancy_r), essential: Math.abs(b.expectancy_r - ctl.expectancy_r) >= 0.05 }, DEV: { with_source: { n: D[best].n, expectancy_r: D[best].expectancy_r, wrong_direction_rate: D[best].wrong_direction_rate }, without_source: { n: D.CONTROL.n, expectancy_r: D.CONTROL.expectancy_r, wrong_direction_rate: D.CONTROL.wrong_direction_rate }, delta_expectancy: r3(D[best].expectancy_r - D.CONTROL.expectancy_r) } } : null;
  const incBoth = defn.candidates.filter((k) => result.incremental.HOLD.CONTROL[k].incremental && result.incremental.DEV.CONTROL[k].incremental); const incOne = defn.candidates.filter((k) => result.incremental.HOLD.CONTROL[k].incremental || result.incremental.DEV.CONTROL[k].incremental);
  const dirImproved = b ? ((ctl.wrong_direction_rate - b.wrong_direction_rate >= 0.03 && ctl.move_capture.wrong_direction_rate - b.move_capture.wrong_direction_rate >= 0.03 && b.n >= 200) ? 'YES' : (ctl.wrong_direction_rate - b.wrong_direction_rate >= 0.03 || ctl.move_capture.wrong_direction_rate - b.move_capture.wrong_direction_rate >= 0.03) ? 'INCONCLUSIVE' : 'NO') : 'NO';
  const anyInconclusive = Object.values(dec).some((d) => d.hold_n >= 200 && d.hold_expectancy_r > 0 && d.wrong_direction_rate < ctl.wrong_direction_rate && !(d.ci95_r?.[0] > 0));
  const bestInfo = Object.entries(result.incremental.HOLD.CONTROL).sort((a, b2) => (b2[1].improvement_r ?? -9) - (a[1].improvement_r ?? -9))[0]?.[0] ?? null;
  result.decisions = { candidates: dec, passing, best_candidate: best, best_new_information: bestInfo, best_new_information_source: bestInfo ? dec[bestInfo]?.source ?? null : null, new_data_sources_tested: ['XAGUSDm 5m/15m (silver)', 'DXYm 5m/15m (dollar index CFD)', 'USTECm 15m (Nasdaq CFD)', 'XAGUSDm tick activity', 'official USD release timestamps (reaction, derived)', 'XAUUSDm broker spread (execution state)'], forward_only_candidates: ['MT5 market depth / order-book imbalance (no history; broker-synthetic CFD depth)', 'execution latency / slippage logs (not captured)'], unavailable: ['COMEX exchange volume', 'Treasury yields (no instrument captured)', 'release surprise values (no consensus data)', 'news sentiment feeds'], families_with_incremental_value_both_splits: incBoth, families_with_incremental_value_one_split: incOne, information_incremental_value: incBoth.length ? 'YES' : incOne.length ? 'INCONCLUSIVE' : 'NO', directional_accuracy_improved: dirImproved, trade_economics_improved: b ? (b.ci95_r?.[0] > ctl.expectancy_r && b.expectancy_r > 0 ? 'YES' : b.expectancy_r > ctl.expectancy_r ? 'INCONCLUSIVE' : 'NO') : 'NO', edge_demonstrated: passing.length ? 'YES' : anyInconclusive ? 'INCONCLUSIVE' : 'NO', demo_eligible: passing.length ? 'YES (subject to parity fixtures)' : 'NO', data_quality: Object.values(QUALITY).every((q) => q.pass) ? 'PASS' : 'FAIL', timestamp_integrity: ctrl.cross_prefix_invariance && ctrl.timestamp_rule_no_future_bar && Object.values(result.delay).every((d) => d.pass) ? 'PASS' : 'FAIL', live_replay_parity: PARITY.pass ? 'PASS' : 'FAIL', control: pickC(ctl), best: b ? { ...pickC(b), name: best, status: dec[best].status, reasons: dec[best].reasons } : null };
  writeFileSync(join(OUT, 'v7_results.json'), JSON.stringify(result, null, 1)); console.log('DECISIONS', JSON.stringify({ ...result.decisions, candidates: undefined }, null, 1)); for (const [k, d] of Object.entries(dec)) console.log(k, d.status, 'n', d.hold_n, 'exp', d.hold_expectancy_r, 'pf', d.hold_pf, 'dd', d.hold_dd_r, 'wd', d.wrong_direction_rate, 'evwd', d.event_wd, 'bad', d.bad_entry_rate, 'cap', d.capture, 'wait', d.wait_share, 'na', d.na_share, 'dev', d.dev_expectancy_r, 'ci', JSON.stringify(d.ci95_r), (d.reasons ?? []).join('; ')); }
function pickC(v) { return v ? { n: v.n, expectancy_r: v.expectancy_r, pf: v.pf, max_dd_r: v.max_dd_r, ci95_r: v.ci95_r, block_ci95_r: v.block_ci95_r, wrong_direction_rate: v.wrong_direction_rate, bad_entry_rate: v.bad_entry_rate, capture: v.move_capture?.capture_rate, event_wd: v.move_capture?.wrong_direction_rate, wait_share: v.wait_share, win_rate: v.win_rate, stress_r: v.stress?.expectancy_r } : null; }
console.log('written', PHASE);
