/**
 * CAPITAL HARVEST V1 -- study runner. RESEARCH ONLY. Reads Edge Lab bars, the enriched candidate set and the
 * Edge Lab production-stack simulation read-only; writes only results/. Spec: PREREGISTRATION.md (hash asserted).
 * No execution module is imported. No production state is touched.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { COSTS, EQUITY_REF_USD, MARGIN_0_01_LOT_USD, HORIZON_BARS, capitalRisk, canReenter, simulateTrade, continuationEvidence } from './harvest_engine.mjs';
const HERE = dirname(fileURLToPath(import.meta.url)); const REPO = join(HERE, '..', '..', '..'); const ROOT = join(REPO, 'research', 'capital_harvest_v1'); const OUT = join(ROOT, 'results'); mkdirSync(OUT, { recursive: true });
const PREREG_SHA = readFileSync(join(ROOT, 'PREREGISTRATION.sha256'), 'utf8').trim().split(/\s+/)[0];
if (createHash('sha256').update(readFileSync(join(ROOT, 'PREREGISTRATION.md'))).digest('hex') !== PREREG_SHA) throw new Error('PREREGISTRATION.md does not match its frozen hash');
const LAB = join(REPO, 'handoff', 'edge_discovery_lab', 'data');
const BARS = JSON.parse(readFileSync(join(LAB, 'XAUUSDm_bars.json'), 'utf8')); const b5 = BARS['5m'];
const r2 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 100) / 100); const r3 = (n) => (n == null || !Number.isFinite(n) ? null : Math.round(n * 1000) / 1000);
const iso = (t) => new Date(t * 1000).toISOString(); const day = (t) => iso(t).slice(0, 10); const month = (t) => iso(t).slice(0, 7);
const SPLIT = { dev: ['2025-05-07', '2025-12-31'], hold: ['2026-01-01', '2026-09-29'] };
const split = (t) => { const d = day(t); if (d >= SPLIT.dev[0] && d <= SPLIT.dev[1]) return 'DEV'; if (d >= SPLIT.hold[0] && d <= SPLIT.hold[1]) return 'HOLD'; return 'EXCLUDED'; };
const mean = (a) => (a.length ? a.reduce((s, x) => s + x, 0) / a.length : null); const median = (a) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); const m = s.length >> 1; return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2; };
const pct = (a, p) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); return s[Math.min(s.length - 1, Math.floor(p * s.length))]; };
function rng(seed) { let s = seed >>> 0; return () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
function bootCI(v, n = 2000, seed = 20260930) { if (v.length < 2) return null; const rand = rng(seed); const ms = []; for (let k = 0; k < n; k++) { let s = 0; for (let j = 0; j < v.length; j++) s += v[Math.floor(rand() * v.length)]; ms.push(s / v.length); } ms.sort((a, b) => a - b); return [r3(ms[Math.floor(0.025 * n)]), r3(ms[Math.floor(0.975 * n)])]; }

// ---------- signals (production entries) ----------
const C = readFileSync(join(REPO, 'research', 'entry_architecture_v2', 'results', 'candidates.jsonl'), 'utf8').trim().split('\n').map((l) => JSON.parse(l));
const SIG = C.filter((c) => (c.act === 'BUY' || c.act === 'SELL') && c.geo && split(c.t) !== 'EXCLUDED').map((c) => ({ i: c.i, t: c.t, side: c.side, model: c.model, anchor: c.anchor, entry: c.geo.entry, sl: c.geo.sl, tp1Dist: Math.abs(c.geo.tp1 - c.geo.entry), tp2Dist: Math.abs(c.geo.tp2 - c.geo.entry), rr: c.geo.rr, atr: c.atr, atrR: c.atrR, q: c.q_final, rg5: c.rg5, ses: c.ses, split: split(c.t) })).sort((a, b) => a.i - b.i);
const OPP = { BUY: SIG.filter((s) => s.side === 'SELL').map((s) => s.i), SELL: SIG.filter((s) => s.side === 'BUY').map((s) => s.i) };
const sessions = new Set(); const sessBy = { DEV: new Set(), HOLD: new Set() };
for (const line of readFileSync(join(LAB, 'lab_rows.jsonl'), 'utf8').split('\n')) { if (!line) continue; const t = Number(line.slice(line.indexOf('"t":') + 4, line.indexOf(',', line.indexOf('"t":')))); const sp = split(t); if (sp === 'EXCLUDED') continue; sessions.add(day(t)); sessBy[sp].add(day(t)); }
console.log(`signals ${SIG.length} (DEV ${SIG.filter((s) => s.split === 'DEV').length}, HOLD ${SIG.filter((s) => s.split === 'HOLD').length}); sessions ${sessions.size}`);

// ---------- capital risk ----------
const riskRows = SIG.map((s) => ({ ...capitalRisk({ entry: s.entry, sl: s.sl }), split: s.split, model: s.model }));
const bands = ['<=1%', '1-2%', '2-3%', '3-5%', '5-8%', '>8%'];
const capital = { equity_ref: EQUITY_REF_USD, margin_0_01_lot: MARGIN_0_01_LOT_USD, margin_burden_pct: r3(MARGIN_0_01_LOT_USD / EQUITY_REF_USD), stop_distance_usd: { p10: r2(pct(riskRows.map((r) => r.stopDistance), 0.1)), p25: r2(pct(riskRows.map((r) => r.stopDistance), 0.25)), median: r2(median(riskRows.map((r) => r.stopDistance))), p75: r2(pct(riskRows.map((r) => r.stopDistance), 0.75)), p90: r2(pct(riskRows.map((r) => r.stopDistance), 0.9)) }, expected_loss_usd_median: r2(median(riskRows.map((r) => r.expectedLossUsd))), band_counts: Object.fromEntries(bands.map((b) => [b, riskRows.filter((r) => r.band === b).length])), band_share: Object.fromEntries(bands.map((b) => [b, r3(riskRows.filter((r) => r.band === b).length / riskRows.length)])), minimum_lot_constraint: { share_above_2pct: r3(riskRows.filter((r) => r.pctEquity > 0.02).length / riskRows.length), share_above_3pct: r3(riskRows.filter((r) => r.pctEquity > 0.03).length / riskRows.length), share_above_5pct: r3(riskRows.filter((r) => r.pctEquity > 0.05).length / riskRows.length), share_above_8pct: r3(riskRows.filter((r) => r.pctEquity > 0.08).length / riskRows.length), note: 'at 0.01 lot the position cannot be made smaller; the only lever is candidate rejection (CAPITAL_RISK_TOO_HIGH)' }, by_model_median_stop: Object.fromEntries(['MC', 'PB', 'BO', 'SR', 'MR'].map((m) => [m, r2(median(riskRows.filter((r) => r.model === m).map((r) => r.stopDistance)))])) };
const medStop = median(riskRows.map((r) => r.expectedLossUsd)), p75Stop = pct(riskRows.map((r) => r.expectedLossUsd), 0.75);
capital.account_scale = [60, 100, 500, 1000].map((eq) => ({ equity: eq, risk_pct_median_stop: r3(medStop / eq), risk_pct_p75_stop: r3(p75Stop / eq), harvest_pct: { '2usd': r3(2 / eq), '3usd': r3(3 / eq), '5usd': r3(5 / eq) }, margin_burden_pct: r3(MARGIN_0_01_LOT_USD / eq), min_lot_constraint: eq < 100 ? 'binding: 0.01 lot is the only size; median structural risk is > 5% of equity' : eq < 500 ? 'binding for tight risk budgets (<= 3%)' : 'not binding at <= 1% for median stops (0.02-0.05 lot would be the natural size)' }));
capital.examples_61 = { gains: Object.fromEntries([1, 2, 3, 5, 10].map((u) => [`+${u}`, r3(u / 61)])), losses: Object.fromEntries([1, 2, 3, 5, 10, 20, 50].map((u) => [`-${u}`, r3(-u / 61)])) };

// ---------- milestone analysis (before architectures) ----------
const indep = (arr) => { const out = []; let lastI = -1e9, lastSide = null; for (const s of arr) { if (s.side !== lastSide || s.i - lastI > 12) out.push(s); lastI = s.i; lastSide = s.side; } return out; };
const SIGI = indep(SIG);
const USD_M = [1, 2, 3, 5, 7.5, 10], R_M = [0.25, 0.5, 0.75, 1.0];
function milestoneScan(s) { const sp = COSTS.normal.spread; const fill = s.side === 'BUY' ? s.entry + sp : s.entry; const risk = Math.abs(s.entry - s.sl); let mfe = 0; const firstBar = {}; let stopBar = null, oppBar = null; const opp = OPP[s.side]; let oi = 0; while (oi < opp.length && opp[oi] <= s.i) oi++; const end = Math.min(b5.length - 1, s.i + HORIZON_BARS);
  for (let j = s.i + 1; j <= end; j++) { const b = b5[j]; const stop = s.side === 'BUY' ? b.low <= s.sl : (b.high + sp) >= s.sl; if (stop) { stopBar = j; break; } const fav = s.side === 'BUY' ? b.high - fill : fill - (b.low + sp); if (fav > mfe) mfe = fav; for (const m of USD_M) if (firstBar[`$${m}`] == null && mfe >= m) firstBar[`$${m}`] = j - s.i; for (const m of R_M) if (firstBar[`${m}R`] == null && mfe >= m * risk) firstBar[`${m}R`] = j - s.i; while (oi < opp.length && opp[oi] < j) oi++; if (oppBar == null && oi < opp.length && opp[oi] === j) oppBar = j; }
  return { firstBar, stopBar: stopBar == null ? null : stopBar - s.i, oppBar: oppBar == null ? null : oppBar - s.i, mfe, risk }; }
const scans = SIGI.map((s) => ({ s, m: milestoneScan(s) }));
const milestones = {}; for (const key of [...USD_M.map((m) => `$${m}`), ...R_M.map((m) => `${m}R`)]) { const hit = scans.filter((x) => x.m.firstBar[key] != null); const beforeOpp = hit.filter((x) => x.m.oppBar == null || x.m.firstBar[key] <= x.m.oppBar); milestones[key] = { independent_signals: scans.length, reached_before_stop: r3(hit.length / scans.length), reached_before_stop_and_opposite_signal: r3(beforeOpp.length / scans.length), median_bars_to_reach: median(hit.map((x) => x.m.firstBar[key])), dev_rate: r3(scans.filter((x) => x.s.split === 'DEV' && x.m.firstBar[key] != null).length / scans.filter((x) => x.s.split === 'DEV').length), hold_rate: r3(scans.filter((x) => x.s.split === 'HOLD' && x.m.firstBar[key] != null).length / scans.filter((x) => x.s.split === 'HOLD').length) }; }
milestones._stop_first_share = r3(scans.filter((x) => x.m.stopBar != null && Object.keys(x.m.firstBar).length === 0).length / scans.length);
milestones._mfe_usd_distribution = { p25: r2(pct(scans.map((x) => x.m.mfe), 0.25)), median: r2(median(scans.map((x) => x.m.mfe))), p75: r2(pct(scans.map((x) => x.m.mfe), 0.75)), p90: r2(pct(scans.map((x) => x.m.mfe), 0.9)) };
milestones._structural_risk_usd_median = r2(median(scans.map((x) => x.m.risk)));

// ---------- variants ----------
const VARIANTS = {
  'H1_$2': { kind: 'FIXED', m1: { usd: 2 } }, 'H1_$3': { kind: 'FIXED', m1: { usd: 3 } }, 'H1_$5': { kind: 'FIXED', m1: { usd: 5 } }, 'H1_0.5R': { kind: 'FIXED', m1: { r: 0.5 } }, 'H1_1.0R': { kind: 'FIXED', m1: { r: 1.0 } },
  'H2a_bankrun_$3': { kind: 'RUN', m1: { usd: 3 }, buffer: { usd: 1 }, bankRun: true }, 'H2b_alwaysrun_$3': { kind: 'RUN', m1: { usd: 3 }, buffer: { usd: 1 }, bankRun: false },
  'H3a_0.5ATR': { kind: 'RUN', m1: { atr: 0.5 }, buffer: { atr: 0.25 }, bankRun: true }, 'H3b_0.75ATR': { kind: 'RUN', m1: { atr: 0.75 }, buffer: { atr: 0.25 }, bankRun: true },
  'H4a_tp1_trail': { kind: 'TRAIL', m1: { tp1: true } }, 'H4b_0.5R_trail': { kind: 'TRAIL', m1: { r: 0.5 } },
};
function runSequential(variant, { costs = COSTS.normal, drift = false } = {}) { const trades = []; let exitBar = -1, lastTrade = null, lastLoss = false; const skipped = { SAME_OR_EARLIER_CANDLE: 0, STALE_SAME_SETUP: 0, REVENGE_GUARD: 0 };
  for (const s of SIG) { const ok = canReenter({ signal: s, exitBar, lastTrade, lastExitWasLoss: lastLoss }); if (!ok.ok) { skipped[ok.reason]++; continue; } const o = simulateTrade({ bars: b5, i: s.i, side: s.side, entry: s.entry, sl: s.sl, atr: s.atr, tp1Dist: s.tp1Dist, variant, oppSignalBars: OPP[s.side], costs, drift }); if (o.status === 'NO_DATA' || o.status === 'INVALID') continue; trades.push({ s, o }); exitBar = o.exitBar; lastTrade = s; lastLoss = o.pnl_usd <= 0; }
  return { trades, skipped }; }
function pathStats(trades, start = EQUITY_REF_USD) { let bal = start, peak = start, maxDD = 0, minBal = start, streak = 0, maxStreak = 0; const dds = []; let recover = [], sincePeak = 0; for (const t of trades) { bal += t.o.pnl_usd; if (bal > peak) { if (sincePeak > 0) recover.push(sincePeak); peak = bal; sincePeak = 0; } else sincePeak++; const dd = peak - bal; dds.push(dd); if (dd > maxDD) maxDD = dd; if (bal < minBal) minBal = bal; if (t.o.pnl_usd <= 0) { streak++; if (streak > maxStreak) maxStreak = streak; } else streak = 0; } return { final_balance: r2(bal), min_balance: r2(minBal), max_drawdown_usd: r2(maxDD), median_drawdown_usd: r2(median(dds)), max_loss_streak: maxStreak, median_trades_to_recover_peak: median(recover), unrecovered_trades_at_end: sincePeak }; }
function depletion(trades, draws = 500, seed = 7) { if (!trades.length) return null; const rand = rng(seed); const byM = {}; for (const t of trades) (byM[month(t.s.t)] ??= []).push(t.o.pnl_usd); const months = Object.values(byM); let d50 = 0, dMargin = 0; for (let k = 0; k < draws; k++) { const order = [...months].sort(() => rand() - 0.5); let bal = EQUITY_REF_USD, hit50 = false, hitM = false; for (const m of order) { const mm = [...m].sort(() => rand() - 0.5); for (const p of mm) { bal += p; if (bal <= 31.0) hit50 = true; if (bal <= MARGIN_0_01_LOT_USD) hitM = true; } } if (hit50) d50++; if (hitM) dMargin++; } return { draws, share_touching_31usd: r3(d50 / draws), share_touching_margin_21usd: r3(dMargin / draws) }; }
function stats(trades, sessSet) { const P = trades.map((t) => t.o.pnl_usd); if (!P.length) return { trades: 0 }; const wins = P.filter((x) => x > 0), losses = P.filter((x) => x <= 0); const gw = wins.reduce((s, x) => s + x, 0), gl = -losses.reduce((s, x) => s + x, 0); const sorted = [...P].sort((a, b) => b - a); const perDay = {}; for (const t of trades) perDay[day(t.s.t)] = (perDay[day(t.s.t)] ?? 0) + 1; const counts = [...sessSet].map((d) => perDay[d] ?? 0); const activeDays = Object.keys(perDay).length; const months = {}; for (const t of trades) months[month(t.s.t)] = (months[month(t.s.t)] ?? 0) + t.o.pnl_usd; const mv = Object.values(months); const costs = trades.reduce((s, t) => s + t.o.cost_usd, 0); const reached = trades.filter((t) => t.o.reached_bar != null); const ran = trades.filter((t) => t.o.decision === 'RUN'); const bars = trades.reduce((s, t) => s + t.o.bars, 0);
  return { trades: P.length, win_rate: r3(wins.length / P.length), avg_win_usd: r2(mean(wins)), avg_loss_usd: r2(losses.length ? -mean(losses) : null), win_loss_ratio: wins.length && losses.length ? r2(mean(wins) / -mean(losses)) : null, wins_erased_by_one_loss: wins.length && losses.length ? r2(-mean(losses) / mean(wins)) : null, expectancy_usd: r3(mean(P)), expectancy_r: r3(mean(trades.map((t) => t.o.r))), pf: gl > 0 ? r2(gw / gl) : (gw > 0 ? 99 : null), ci95_usd: bootCI(P), gross_profit_usd: r2(gw), gross_loss_usd: r2(gl), costs_usd: r2(costs), net_usd: r2(gw - gl), cost_pct_of_gross_harvest: gw > 0 ? r3(costs / (gw + costs)) : null, net_per_active_day_usd: r3((gw - gl) / activeDays), active_days: activeDays, trades_per_session: { p10: pct(counts, 0.1), p25: pct(counts, 0.25), median: pct(counts, 0.5), p75: pct(counts, 0.75), p90: pct(counts, 0.9), mean: r2(mean(counts)) }, zero_trade_session_rate: r3(counts.filter((x) => x === 0).length / counts.length), avg_hold_bars: r2(mean(trades.map((t) => t.o.bars))), median_hold_bars: median(trades.map((t) => t.o.bars)), time_in_market_share: r3(bars / (sessSet.size * 288)), top5_share_of_gross_profit: gw > 0 ? r3(sorted.slice(0, 5).filter((x) => x > 0).reduce((s, x) => s + x, 0) / gw) : null, months: mv.length, months_positive_share: mv.length ? r3(mv.filter((x) => x > 0).length / mv.length) : null, milestone_hit_rate: r3(reached.length / P.length), protected_run_rate: r3(ran.length / P.length), profit_given_back_after_m1_usd: r2(mean(reached.map((t) => t.o.given_back))), exit_mix: Object.fromEntries(Object.entries(trades.reduce((g, t) => { g[t.o.exit] = (g[t.o.exit] ?? 0) + 1; return g; }, {}))), open_at_horizon: trades.filter((t) => t.o.status === 'OPEN_AT_HORIZON').length, mfe_mean_usd: r2(mean(trades.map((t) => t.o.mfe_usd))), mae_mean_usd: r2(mean(trades.map((t) => t.o.mae_usd))), path: pathStats(trades), depletion: depletion(trades), by_model: Object.fromEntries(['MC', 'PB', 'BO', 'SR', 'MR'].map((m) => { const x = trades.filter((t) => t.s.model === m); return [m, { n: x.length, exp_usd: r3(mean(x.map((t) => t.o.pnl_usd))) }]; })), by_side: Object.fromEntries(['BUY', 'SELL'].map((m) => { const x = trades.filter((t) => t.s.side === m); return [m, { n: x.length, exp_usd: r3(mean(x.map((t) => t.o.pnl_usd))) }]; })), by_session: Object.fromEntries(['ASIA', 'LONDON', 'NEW_YORK', 'OTHER'].map((m) => { const x = trades.filter((t) => t.s.ses === m); return [m, { n: x.length, exp_usd: r3(mean(x.map((t) => t.o.pnl_usd))) }]; })), by_risk_band: Object.fromEntries(bands.map((b) => { const x = trades.filter((t) => capitalRisk({ entry: t.s.entry, sl: t.s.sl }).band === b); return [b, { n: x.length, exp_usd: r3(mean(x.map((t) => t.o.pnl_usd))), avg_loss: r2(-mean(x.filter((t) => t.o.pnl_usd <= 0).map((t) => t.o.pnl_usd)) || null) }]; })) }; }

// ---------- H0 control: Edge Lab production-stack simulation ----------
const LT = JSON.parse(readFileSync(join(LAB, 'lab_trades.json'), 'utf8')).filter((t) => t.signal && t.taken && t.prod && !t.prod.skipped && split(t.t) !== 'EXCLUDED');
const H0 = LT.map((t) => ({ s: { i: t.i, t: t.t, side: t.side, model: t.model, entry: t.entry, sl: t.sl, ses: (C.find((c) => c.i === t.i) || {}).ses ?? 'OTHER', split: split(t.t) }, o: { pnl_usd: r3(t.prod.pnl - COSTS.normal.slip), r: r3((t.prod.pnl - COSTS.normal.slip) / t.prod.risk), bars: t.prod.hold, exit: t.prod.exit, cost_usd: COSTS.normal.spread + COSTS.normal.slip, reached_bar: t.prod.mfe >= 3 ? 1 : null, given_back: r3(t.prod.mfe - t.prod.pnl), decision: null, mfe_usd: t.prod.mfe, mae_usd: t.prod.mae, status: 'RESOLVED', exitBar: t.prod.closeIdx } }));
const arch = { H0_current: { note: 'Edge Lab production-stack simulation (broker structural/monetary stops, +30 USD TP, adaptive management) on the same signals, minus 0.10 USD slippage; entries and management as production, NOT structural exits', ALL: stats(H0, sessions), DEV: stats(H0.filter((t) => t.s.split === 'DEV'), sessBy.DEV), HOLD: stats(H0.filter((t) => t.s.split === 'HOLD'), sessBy.HOLD) } };

// ---------- controls ----------
console.log('controls ...');
const ctrl = (() => { const rand = rng(99); const leak = [], nul = []; for (const s of SIGI) { if (s.i + 13 >= b5.length) continue; const fut = b5[s.i + 12].close - b5[s.i].close; const sym = { kind: 'FIXED', m1: { usd: s.atr } }; const mk = (side) => ({ bars: b5, i: s.i, side, entry: b5[s.i].close, sl: side === 'BUY' ? b5[s.i].close - s.atr : b5[s.i].close + s.atr, atr: s.atr, tp1Dist: s.atr, variant: sym, oppSignalBars: [] }); const o1 = simulateTrade(mk(fut >= 0 ? 'BUY' : 'SELL')), o2 = simulateTrade(mk(rand() < 0.5 ? 'BUY' : 'SELL')); if (o1.status === 'RESOLVED' && !o1.gap) leak.push(o1.pnl_usd); if (o2.status === 'RESOLVED' && !o2.gap) nul.push(o2.pnl_usd); }
  // cost test as pure accounting on IDENTICAL paths: slippage 0.10 vs 0 (spread changes stop timing, so it is tested by unit test, not by path comparison)
  const v = VARIANTS['H1_$3']; const base = runSequential(v).trades; const noSlip = base.map((t) => simulateTrade({ bars: b5, i: t.s.i, side: t.s.side, entry: t.s.entry, sl: t.s.sl, atr: t.s.atr, tp1Dist: t.s.tp1Dist, variant: v, oppSignalBars: OPP[t.s.side], costs: { spread: COSTS.normal.spread, slip: 0 } }).pnl_usd); const diff = mean(noSlip) - mean(base.map((t) => t.o.pnl_usd));
  return { control_geometry: 'symmetric: stop 1 ATR, fixed target 1 ATR (see PREREGISTRATION correction log)', leak_mean_usd: r3(mean(leak)), leak_n: leak.length, null_mean_usd: r3(mean(nul)), null_n: nul.length, cost_test: { no_slip_minus_normal_usd: r3(diff), expected: 0.10, pass: Math.abs(diff - 0.10) < 0.001, note: 'slippage is pure accounting on identical paths; spread application (BUY fill = close + spread) is asserted by unit tests' } }; })();
console.log(JSON.stringify(ctrl));
if (!(ctrl.leak_mean_usd > 1.0) || !(Math.abs(ctrl.null_mean_usd) < 0.5) || !ctrl.cost_test.pass) throw new Error('CONTROL FAILED ' + JSON.stringify(ctrl));

// ---------- run variants ----------
const dedupChecks = { same_candle_violations: 0, ratchet_violations: 0, revenge_violations: 0 };
for (const [name, v] of Object.entries(VARIANTS)) {
  const { trades, skipped } = runSequential(v); const stress = runSequential(v, { costs: COSTS.stress }).trades; const drift = runSequential(v, { drift: true }).trades;
  for (let k = 1; k < trades.length; k++) { if (trades[k].s.i <= trades[k - 1].o.exitBar) dedupChecks.same_candle_violations++; if (trades[k - 1].o.pnl_usd <= 0 && trades[k].s.side === trades[k - 1].s.side && trades[k].s.i - trades[k - 1].o.exitBar <= 3) dedupChecks.revenge_violations++; }
  dedupChecks.ratchet_violations += trades.reduce((s, t) => s + (t.o.ratchetViolations ?? 0), 0);
  const H = trades.filter((t) => t.s.split === 'HOLD'), D = trades.filter((t) => t.s.split === 'DEV');
  arch[name] = { variant: v, skipped_reentries: skipped, ALL: stats(trades, sessions), DEV: stats(D, sessBy.DEV), HOLD: stats(H, sessBy.HOLD), HOLD_stress: (() => { const x = stats(stress.filter((t) => t.s.split === 'HOLD'), sessBy.HOLD); return { expectancy_usd: x.expectancy_usd, pf: x.pf, net_usd: x.net_usd }; })(), HOLD_drift: (() => { const x = stats(drift.filter((t) => t.s.split === 'HOLD'), sessBy.HOLD); return { expectancy_usd: x.expectancy_usd, pf: x.pf, net_usd: x.net_usd }; })() };
  if (v.kind === 'RUN' && v.bankRun) { const reached = trades.filter((t) => t.o.reached_bar != null); const bank = reached.filter((t) => t.o.decision === 'BANK'), run = reached.filter((t) => t.o.decision === 'RUN'); const alwaysRun = { ...v, bankRun: false }; const cf = reached.map((t) => { const o = simulateTrade({ bars: b5, i: t.s.i, side: t.s.side, entry: t.s.entry, sl: t.s.sl, atr: t.s.atr, tp1Dist: t.s.tp1Dist, variant: alwaysRun, oppSignalBars: OPP[t.s.side] }); const m1 = t.o.m1_usd; return { dec: t.o.decision, bank: r3(m1 - COSTS.normal.slip), run: o.pnl_usd, strong: t.o.decision === 'RUN' }; }); arch[name].bank_vs_run = { reached_m1: reached.length, banked: bank.length, ran: run.length, banked_mean_usd: r3(mean(bank.map((t) => t.o.pnl_usd))), ran_mean_usd: r3(mean(run.map((t) => t.o.pnl_usd))), counterfactual: { weak_evidence: { n: cf.filter((x) => !x.strong).length, bank_mean: r3(mean(cf.filter((x) => !x.strong).map((x) => x.bank))), run_mean: r3(mean(cf.filter((x) => !x.strong).map((x) => x.run))) }, strong_evidence: { n: cf.filter((x) => x.strong).length, bank_mean: r3(mean(cf.filter((x) => x.strong).map((x) => x.bank))), run_mean: r3(mean(cf.filter((x) => x.strong).map((x) => x.run))) } }, run_floor_hit_within_3_bars_share: r3(run.filter((t) => t.o.exit !== 'MILESTONE_BANK' && t.o.bars - t.o.reached_bar <= 3).length / Math.max(1, run.length)), run_exit_mix: Object.fromEntries(Object.entries(run.reduce((g, t) => { g[t.o.exit] = (g[t.o.exit] ?? 0) + 1; return g; }, {}))) }; }
  if (v.kind === 'TRAIL' || (v.kind === 'RUN' && !v.bankRun)) { const run = trades.filter((t) => t.o.decision === 'RUN'); arch[name].protected_run = { ran: run.length, mean_usd: r3(mean(run.map((t) => t.o.pnl_usd))), floor_hit_within_3_bars_share: r3(run.filter((t) => t.o.bars - t.o.reached_bar <= 3).length / Math.max(1, run.length)), given_back_mean: r2(mean(run.map((t) => t.o.given_back))), exit_mix: Object.fromEntries(Object.entries(run.reduce((g, t) => { g[t.o.exit] = (g[t.o.exit] ?? 0) + 1; return g; }, {}))) }; }
  console.log(name, JSON.stringify({ hold: { n: arch[name].HOLD.trades, exp: arch[name].HOLD.expectancy_usd, pf: arch[name].HOLD.pf, win: arch[name].HOLD.win_rate, aw: arch[name].HOLD.avg_win_usd, al: arch[name].HOLD.avg_loss_usd, dd: arch[name].HOLD.path?.max_drawdown_usd, tpd: arch[name].HOLD.trades_per_session?.median } }));
}
if (dedupChecks.same_candle_violations || dedupChecks.ratchet_violations || dedupChecks.revenge_violations) throw new Error('DEDUP/RATCHET CONTROL FAILED ' + JSON.stringify(dedupChecks));

// ---------- decisions ----------
const h0 = arch.H0_current.HOLD;
for (const [name, a] of Object.entries(arch)) { if (name === 'H0_current') continue; const h = a.HOLD; if (!h.trades) { a.decision = { status: 'REJECTED', reason: 'no trades' }; continue; }
  const erased = h.wins_erased_by_one_loss ?? 99; const dd = h.path.max_drawdown_usd; const dep = h.depletion?.share_touching_margin_21usd ?? 0; let status, reasons = [];
  if (h.expectancy_usd <= 0) reasons.push('expectancy<=0'); if ((h.pf ?? 0) < 1.0) reasons.push('PF<1'); if (erased > 5) reasons.push('avg loss > 5x avg win'); if (dd > 31.0) reasons.push('maxDD>31USD'); if (dep > 0.05) reasons.push('margin-floor risk>5%');
  if (reasons.length) status = 'REJECTED';
  else if (h.net_per_active_day_usd <= (h0.net_per_active_day_usd ?? 0) + 0.10 || ((h.ci95_usd?.[0] ?? -1) <= 0 && (h.pf ?? 0) < 1.10)) status = 'NO_IMPROVEMENT';
  else { const promo = h.trades >= 300 && (h.ci95_usd?.[0] ?? -1) > 0 && h.pf >= 1.2 && erased <= 3 && dd <= 18.6 && h.path.max_loss_streak <= 10 && (a.DEV.expectancy_usd ?? -1) > 0 && (a.HOLD_stress.expectancy_usd ?? -1) > 0 && (a.HOLD_drift.expectancy_usd ?? -1) > 0 && (h.months_positive_share ?? 0) >= 0.6 && (h.top5_share_of_gross_profit ?? 1) <= 0.3 && (h.cost_pct_of_gross_harvest ?? 1) <= 0.5; status = promo ? 'ELIGIBLE_FOR_FORWARD_SHADOW_VALIDATION' : 'INTERESTING_RESEARCH_LEAD'; }
  a.decision = { status, reject_reasons: reasons, vs_h0: { exp_usd: h.expectancy_usd, h0_exp_usd: h0.expectancy_usd, net_per_day: h.net_per_active_day_usd, h0_net_per_day: h0.net_per_active_day_usd, trades: h.trades, h0_trades: h0.trades, dd: dd, h0_dd: h0.path.max_drawdown_usd } }; }

const meta = { generated_utc: new Date().toISOString(), prereg_sha256: PREREG_SHA, signals: SIG.length, independent_signals: SIGI.length, sessions: sessions.size, sessions_dev: sessBy.DEV.size, sessions_hold: sessBy.HOLD.size, controls: ctrl, dedup_ratchet_checks: dedupChecks, variants: Object.keys(VARIANTS), bonferroni_alpha: 0.05 / 11, costs: COSTS, equity_ref: EQUITY_REF_USD };
writeFileSync(join(OUT, 'study_results.json'), JSON.stringify({ meta, capital, milestones, architectures: arch }, null, 1));
console.log(JSON.stringify({ decisions: Object.fromEntries(Object.entries(arch).filter(([k]) => k !== 'H0_current').map(([k, v]) => [k, v.decision.status])) }));
console.log('written', join(OUT, 'study_results.json'));
