/**
 * V8 FORWARD SHADOW -- report renderer (read-only on the store). Renders the 16 required reports. Every trade statistic is
 * HYPOTHETICAL_NOT_EXECUTED; only FORWARD_LIVE, non-duplicate signals count. Definitions are the ones
 * pre-registered in research/v8_forward_shadow/V8F_PREREGISTRATION.md. There is NO sample-size gate and NO trade target: the
 * reports show the evidence accumulated over the observation period, and the owner decides when it is sufficient.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { canReenter } from '../../../src/engine/capitalHarvest/positionManager.js';
import { MODELS, WAIT_CATEGORIES, MISSED_CLASSES, WRONG_CLASSES, SAFETY, RR } from './lib.mjs';

const jsonl = (p) => (existsSync(p) ? readFileSync(p, 'utf8').split('\n').filter(Boolean).map((l) => { try { return JSON.parse(l); } catch { return null; } }).filter(Boolean) : []);
const pc = (x) => (x == null || !Number.isFinite(x) ? '—' : `${(x * 100).toFixed(1)} %`); const f3 = (x) => (x == null || !Number.isFinite(x) ? '—' : Number(x).toFixed(3)); const f2 = (x) => (x == null || !Number.isFinite(x) ? '—' : Number(x).toFixed(2));
const iso = (t) => new Date(t * 1000).toISOString().slice(0, 16).replace('T', ' ');
const mean = (a) => (a.length ? a.reduce((s, x) => s + x, 0) / a.length : null);

export function stats(rows, key = 'fix170_normal') { const R = rows.map((x) => x.o?.[key]?.r).filter((x) => x != null); if (!R.length) return { n: 0 }; const w = R.filter((x) => x > 0), l = R.filter((x) => x <= 0); const gw = w.reduce((a, b) => a + b, 0), gl = -l.reduce((a, b) => a + b, 0); let cum = 0, peak = 0, dd = 0, stk = 0, ms = 0; for (const r of R) { cum += r; peak = Math.max(peak, cum); dd = Math.max(dd, peak - cum); if (r <= 0) { stk++; ms = Math.max(ms, stk); } else stk = 0; } const mfe = rows.map((x) => x.o?.open_normal?.mfe_r).filter((v) => v != null); const giveback = rows.filter((x) => (x.o?.[key]?.mfe_r ?? 0) >= 0.5).map((x) => x.o[key].mfe_r - x.o[key].r); return { n: R.length, win_rate: w.length / R.length, avg_win: mean(w), avg_loss: l.length ? -mean(l) : null, expectancy: mean(R), pf: gl > 0 ? gw / gl : (gw > 0 ? 99 : null), max_dd: dd, loss_streak: ms, mfe: mean(mfe), mae: mean(rows.map((x) => x.o?.open_normal?.mae_r).filter((v) => v != null)), reach170: rows.filter((x) => x.o?.open_normal?.milestones?.['1.7']).length / rows.length, giveback: mean(giveback), duration: mean(rows.map((x) => x.o?.[key]?.bars).filter((v) => v != null)), wrong: rows.filter((x) => x.o?.wrong_direction).length / rows.length }; }
function seqWalk(rows, key = 'fix170_normal') { const trades = []; let exitBar = -1, last = null, lastLoss = false; for (const x of [...rows].sort((a, b) => a.d.bar_time - b.d.bar_time)) { const i = x.d.bar_time / 300; const sig = { i, model: x.d.candidate.model, side: x.d.candidate.side, anchor: x.d.candidate.anchor }; const ok = canReenter({ signal: sig, exitBar, lastTrade: last, lastExitWasLoss: lastLoss }); if (!ok.ok) continue; trades.push(x); exitBar = i + (x.o[key].bars ?? 0); last = sig; lastLoss = x.o[key].r <= 0; } return trades; }
const statRow = (label, s) => `| ${label} | ${s.n ?? 0} | ${pc(s.win_rate)} | ${f2(s.avg_win)} / ${f2(s.avg_loss)} | ${f3(s.expectancy)} | ${f2(s.pf)} | ${f2(s.max_dd)} | ${s.loss_streak ?? '—'} | ${f2(s.mfe)} / ${f2(s.mae)} | ${pc(s.reach170)} | ${f2(s.giveback)} | ${f2(s.duration)} | ${pc(s.wrong)} |`;
const statHead = '| Set | n | Win | Avg win / loss (R) | Expectancy (R) | PF | Max DD (R) | Loss streak | MFE / MAE (R) | 1.70R reach | Give-back (R) | Duration (bars) | Wrong-direction |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|';

export function analyse(dir) {
  const D = jsonl(join(dir, 'decisions.jsonl')); const O = new Map(jsonl(join(dir, 'outcomes.jsonl')).map((o) => [o.id, o])); const EV = jsonl(join(dir, 'events.jsonl')); const PAR = jsonl(join(dir, 'parity.jsonl')); const REV = jsonl(join(dir, 'revisions.jsonl'));
  const status = existsSync(join(dir, 'status.json')) ? JSON.parse(readFileSync(join(dir, 'status.json'), 'utf8')) : {};
  const fwd = D.filter((d) => d.provenance === 'FORWARD_LIVE'); const by = (e) => fwd.filter((d) => d.engine === e);
  const A = {}; for (const e of ['V8', 'CONTROL']) { const ds = by(e); const sigs = ds.filter((d) => d.counted_signal); const set = sigs; const lab = set.map((d) => ({ d, o: O.get(d.id) })).filter((x) => x.o);
    A[e] = { decisions: ds.length, late_decisions: D.filter((d) => d.engine === e && d.provenance !== 'FORWARD_LIVE').length, valid_setups: ds.filter((d) => d.valid_setup && !d.duplicate).length, signals: sigs.length, duplicates: ds.filter((d) => d.duplicate).length, safety_blocked: ds.filter((d) => d.valid_setup && !d.shadow_signal).length, labelled: lab.length, pending: set.length - lab.length, lab, set, ds,
      per_signal: stats(lab), stress: stats(lab, 'fix170_stress'), tp2: stats(lab, 'tp2_normal'), tp2_stress: stats(lab, 'tp2_stress'), seq: stats(seqWalk(lab)), seq_stress: stats(seqWalk(lab, 'fix170_stress'), 'fix170_stress'),
      waits: ds.filter((d) => d.action === 'WAIT').reduce((g, d) => { g[d.wait_category ?? 'NONE'] = (g[d.wait_category ?? 'NONE'] ?? 0) + 1; return g; }, {}), regression: ['D1', 'D2', 'D3', 'D4', 'D5', 'D6'].reduce((g, k) => { g[k] = { OK: ds.filter((d) => d.regression?.[k] === 'OK').length, VIOLATION: ds.filter((d) => d.regression?.[k] === 'VIOLATION').length, VIOLATION_ON_SIGNALS: ds.filter((d) => d.valid_setup && d.regression?.[k] === 'VIOLATION').length }; return g; }, {}),
      parity: { checked: PAR.filter((p) => p.engine === e).length, inputs_equal: PAR.filter((p) => p.engine === e && p.inputs_equal).length, match: PAR.filter((p) => p.engine === e && p.match === true).length, mismatch: PAR.filter((p) => p.engine === e && p.match === false), input_changed: PAR.filter((p) => p.engine === e && !p.inputs_equal).length },
      stage_parity_mismatch: ds.filter((d) => (d.stage_parity_mismatch ?? []).length).length, integrity_fail: ds.filter((d) => d.data_integrity && Object.values(d.data_integrity).includes('FAIL')).length,
      missed: EV.reduce((g, x) => { const c = x[e]?.cls ?? 'NA'; g[c] = (g[c] ?? 0) + 1; return g; }, {}), wrong: lab.filter((x) => x.o.wrong_direction || x.o.against_entry).reduce((g, x) => { const c = x.o.forensics?.cls ?? 'OTHER'; g[c] = (g[c] ?? 0) + 1; return g; }, {}),
      models: Object.fromEntries(MODELS.map((m, idx) => { const obs = ds.filter((d) => d.stages && (d.stages.BUY[idx] !== '0' || d.stages.SELL[idx] !== '0')).length; const trig = ds.filter((d) => d.stages && (d.stages.BUY[idx] === '3' || d.stages.SELL[idx] === '3')).length; const vs = ds.filter((d) => d.valid_setup && !d.duplicate && d.candidate?.model === m).length; const sg = lab.filter((x) => x.d.candidate.model === m); const s = stats(sg); const evs = EV.filter((x) => x[e] && (x[e].cls === 'MISSED' || x[e].cls === 'DETECTED_LATE')); return [m, { observations: obs, triggers: trig, valid_setups: vs, signals: sigs.filter((d) => d.candidate.model === m).length, labelled: sg.length, wrong: sg.filter((x) => x.o.wrong_direction).length, valid_losses: sg.filter((x) => x.o.forensics?.cls === 'VALID_LOSING_TRADE').length, missed_or_late_events: evs.length, stat: s }]; })),
      buy_share: sigs.length ? sigs.filter((d) => d.candidate.side === 'BUY').length / sigs.length : null, origin_bars: mean(sigs.map((d) => d.candidate.bars_from_origin).filter((v) => v != null)), latency: sigs.map((d) => d.latency_sec) };
  }
  // over-correction flags (pre-registered)
  const v = A.V8, c = A.CONTROL; const share = (x, m) => (x.signals ? x.set.filter((d) => d.candidate.model === m).length / x.signals : 0); const det = (x) => (EV.length ? (x.missed.DETECTED_CORRECTLY ?? 0) / EV.length : null);
  const flags = []; const nInfo = `(V8 ${v.signals} / CONTROL ${c.signals} signals)`; if (c.signals > 0 && v.signals < 0.8 * c.signals) flags.push(`V8 signals < 80 % of CONTROL ${nInfo}`); for (const m of MODELS) if (v.signals > 0 && c.signals > 0 && Math.abs(share(v, m) - share(c, m)) > 0.15) flags.push(`model share shift > 15 points: ${m} ${nInfo}`); if (v.signals > 0 && c.signals > 0 && Math.abs(v.buy_share - c.buy_share) > 0.15) flags.push(`BUY/SELL share differs from CONTROL by > 15 points ${nInfo}`); if (v.origin_bars != null && c.origin_bars != null && v.origin_bars > c.origin_bars + 1) flags.push(`mean entry lateness > CONTROL + 1 bar ${nInfo}`); if (EV.length > 0 && det(v) < det(c) - 0.05) flags.push(`DETECTED_CORRECTLY share below CONTROL by > 5 points (${EV.length} events)`);
  const implErr = (x) => Object.entries(x.wrong).filter(([k]) => k !== 'VALID_LOSING_TRADE').reduce((s, [, n]) => s + n, 0);
  const regOnSig = (x) => Object.values(x.regression).reduce((s, r) => s + r.VIOLATION_ON_SIGNALS, 0);
  const clean = v.parity.mismatch.length === 0 && regOnSig(v) === 0 && Object.values(v.regression).every((r) => r.VIOLATION === 0) && v.stage_parity_mismatch === 0 && implErr(v) === 0 && (v.missed.MISSED ?? 0) === 0 && (v.missed.BLOCKED_INCORRECTLY ?? 0) === 0;
  const obsStart = status.observation_start ?? (D.length ? new Date(Math.min(...D.map((d) => Date.parse(d.decision_time_utc)))).toISOString() : null);
  const obsEnd = D.length ? new Date(Math.max(...D.map((d) => (d.bar_time + 300) * 1000))).toISOString() : null;
  const elapsedH = obsStart && obsEnd ? Math.max(0, (Date.parse(obsEnd) - Date.parse(obsStart)) / 36e5) : 0;
  const LIMIT = { MC: 3, PB: 3, BO: 10, SR: 0, MR: 3 };
  const evidence = (x) => { const setups = x.ds.filter((d) => d.valid_setup && !d.duplicate); const invalid = setups.filter((d) => Object.values(d.regression ?? {}).includes('VIOLATION') || (d.stage_parity_mismatch ?? []).length || (X0.O.get(d.id)?.forensics && X0.O.get(d.id).forensics.cls !== 'VALID_LOSING_TRADE')).length; return { total_candidates: x.ds.filter((d) => d.candidate_side).length, valid_setups: setups.length, shadow_signals: x.signals, missed_valid_setups: x.missed.MISSED ?? 0, incorrect_blocks: x.missed.BLOCKED_INCORRECTLY ?? 0, invalid_setups_accepted: invalid, late_signals: (x.missed.DETECTED_LATE ?? 0) + x.set.filter((d) => d.candidate.bars_from_origin > (LIMIT[d.candidate.model] ?? 99)).length, wrong_direction_decisions: x.lab.filter((y) => y.o.wrong_direction).length, valid_losing_trades: x.wrong.VALID_LOSING_TRADE ?? 0, implementation_errors: implErr(x), d1_d6_regressions: Object.values(x.regression).reduce((s, r) => s + r.VIOLATION, 0) }; };
  const X0 = { O }; const ev = { V8: evidence(v), CONTROL: evidence(c) };
  const coreStatus = clean ? 'NO RULE VIOLATION OBSERVED SO FAR' : 'RULE VIOLATIONS OBSERVED (see D1-D6 regression, replay parity and forensics)';
  return { D, O, EV, PAR, REV, status, A, flags, clean, implErr, regOnSig, obs: { start: obsStart, end: obsEnd, elapsed_hours: elapsedH }, ev, coreStatus, demo: 'NO' };
}

export function renderReports({ dir, outDir }) {
  const X = analyse(dir); const { A, EV, status } = X; mkdirSync(outDir, { recursive: true }); const v = A.V8, c = A.CONTROL;
  const elapsed = (h) => `${Math.floor(h / 24)} d ${Math.floor(h % 24)} h ${Math.round((h % 1) * 60)} min`;
  const head = (t) => `# ${t}\n\nV8 FORWARD SHADOW VALIDATION · MEASURE ONLY · EXECUTION_AUTHORITY = NONE · every trade figure is HYPOTHETICAL_NOT_EXECUTED · generated ${new Date().toISOString()}\n\n**ACCUMULATED EVIDENCE** for the observation period ${X.obs.start ?? '—'} → ${X.obs.end ?? '—'} (${elapsed(X.obs.elapsed_hours)}). There is no sample-size gate and no trade target: the market decides how many setups occur, and the owner decides when the evidence is sufficient.\n\nEngines on identical live inputs (Exness XAUUSDm via the read-only MT5 reader): **V8** = frozen corrected core (research/core_pattern_audit_v8/engines/ALL, hash-verified at start); **CONTROL** = production src/engine.\n\n`;
  const R = {};
  const sigTable = (x, label) => `### ${label} (${x.signals} counted signals; ${x.valid_setups} valid setups; ${x.safety_blocked} blocked by execution safety; ${x.duplicates} duplicates not counted)\n| Bar close (UTC) | Model | Side | Stages BUY / SELL | Entry | Structural SL | SL source | Risk (USD @0.01) | 1.70R TP | Engine TP2 (RR) | Spread | ATR14 | Session | Context (15m / 5m / 30m / 1H) | Safety | Decision | Outcome 1.70R (R) | Wrong-dir |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n${x.set.map((d) => { const o = X.O.get(d.id); const cd = d.candidate; return `| ${d.bar_close_utc.slice(0, 16)} | ${cd.model} | ${cd.side} | ${d.stages?.BUY ?? '—'} / ${d.stages?.SELL ?? '—'} | ${cd.entry} | ${cd.stop_loss} | ${cd.sl_source} | ${f2(cd.risk_distance)} | ${cd.tp_170r} | ${cd.tp2_engine} (${cd.rr_engine}) | ${d.spread_usd ?? '—'} | ${d.atr14 ?? '—'} | ${d.session} | ${d.bias.direction}/${d.bias.regime} · ${d.regime5} · ${d.m30.regime} · ${d.h1.regime} | ${d.safety?.block ? d.safety.block.category : 'OK'} news ${d.news_state} | SHADOW_SIGNAL=TRUE EXECUTED=FALSE | ${o ? f3(o.fix170_normal.r) : 'pending'} | ${o ? (o.wrong_direction ? 'YES' : 'no') : '—'} |`; }).join('\n') || '| none yet | | | | | | | | | | | | | | | | | |'}`;
  const evLine = (k, label) => `| ${label} | ${X.ev.V8[k]} | ${X.ev.CONTROL[k]} |`;
  R.V8_FORWARD_SHADOW_REPORT = head('V8_FORWARD_SHADOW_REPORT') + `| Evidence | V8 corrected | CONTROL |\n|---|---|---|\n| OBSERVATION_START | ${X.obs.start ?? '—'} | same |\n| OBSERVATION_END (last decided candle close) | ${X.obs.end ?? '—'} | same |\n| ELAPSED_TIME | ${elapsed(X.obs.elapsed_hours)} | same |\n| Market candles observed (forward decisions) | ${v.decisions} | ${c.decisions} |\n| Late / non-forward decisions (never counted) | ${v.late_decisions} | ${c.late_decisions} |\n${evLine('total_candidates', 'TOTAL_CANDIDATES (a model produced a candidate)')}\n${evLine('valid_setups', 'VALID_SETUPS (full core rule chain passed, non-duplicate)')}\n${evLine('shadow_signals', 'SHADOW SIGNALS (after execution safety; EXECUTED = FALSE)')}\n${evLine('missed_valid_setups', 'MISSED_VALID_SETUPS')}\n${evLine('incorrect_blocks', 'INCORRECT_BLOCKS')}\n${evLine('invalid_setups_accepted', 'INVALID_SETUPS_INCORRECTLY_ACCEPTED')}\n${evLine('late_signals', 'LATE_SIGNALS')}\n${evLine('wrong_direction_decisions', 'WRONG_DIRECTION_DECISIONS')}\n${evLine('valid_losing_trades', 'VALID_LOSING_TRADES')}\n${evLine('implementation_errors', 'IMPLEMENTATION_ERRORS')}\n${evLine('d1_d6_regressions', 'D1-D6 REGRESSIONS (violations, all decisions)')}\n| Move events classified | ${EV.length} | ${EV.length} |\n| Replay parity checked / mismatches | ${v.parity.checked} / ${v.parity.mismatch.length} | ${c.parity.checked} / ${c.parity.mismatch.length} |\n\nCore rule correctness (V8): **${X.coreStatus}**. Zero setups in a period is a valid observation; no minimum count is required and no rule is changed during observation. DEMO_ELIGIBLE = **NO** (owner review only; never automatic).\n\n## Hypothetical economics (per counted signal, 1.70R target, NORMAL cost)\n${statHead}\n${statRow('V8', v.per_signal)}\n${statRow('CONTROL', c.per_signal)}\n\nA few winning or losing trades prove neither success nor failure.\n\n## Safety assertions\nREAL_TRADE_PLACED NO · DEMO_TRADE_PLACED NO · POSITION_MODIFIED NO · EXECUTION_AUTHORITY NONE · SILVER_EXECUTION OFF · DOM_EXECUTION OFF · CAPITAL_HARVEST OFF · AUTO_SCALING OFF · MARTINGALE OFF · AVERAGING_DOWN OFF · RR 1.70 · LOT 0.01.\n`;
  R.V8_FORWARD_SIGNAL_LOG = head('V8_FORWARD_SIGNAL_LOG') + `${sigTable(v, 'V8 corrected core')}\n\n${sigTable(c, 'CONTROL (production engine, same inputs)')}\n\nStage digits per model MC PB BO SR MR: 0 none, 1 pattern, 2 setup, 3 trigger (bias-agnostic). Every row: SHADOW_SIGNAL = TRUE, EXECUTED = FALSE.\n`;
  const modelTable = (x) => `| Model | Observations (pattern+) | Triggers | Valid setups | Shadow signals | Labelled | Missed / late move events | Wrong-direction | Valid losses | 1.70R reach | MFE / MAE (R) | Expectancy (R) | PF |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|\n${MODELS.map((m) => { const z = x.models[m]; return `| ${m} | ${z.observations} | ${z.triggers} | ${z.valid_setups} | ${z.signals} | ${z.labelled} | — | ${z.wrong} | ${z.valid_losses} | ${pc(z.stat.reach170)} | ${f2(z.stat.mfe)} / ${f2(z.stat.mae)} | ${f3(z.stat.expectancy)} | ${f2(z.stat.pf)} |`; }).join('\n')}`;
  R.V8_STRATEGY_FORWARD_BREAKDOWN = head('V8_STRATEGY_FORWARD_BREAKDOWN') + `## V8 corrected\n${modelTable(v)}\n\n## CONTROL\n${modelTable(c)}\n\nMissed / late move events are attributed per engine in V8_MISSED_SETUP_FORWARD (an event is not tied to a single model).\n`;
  const evRow = (x) => MISSED_CLASSES.map((k) => `| ${k} | ${x.missed[k] ?? 0} |`).join('\n');
  R.V8_MISSED_SETUP_FORWARD = head('V8_MISSED_SETUP_FORWARD') + `Move events (≥ 3 ATR within 24 bars before 1 ATR adverse, the V3–V8 definition) are evaluated only after 24 bars have passed; the decisions examined are the ones recorded at their original timestamps (no hindsight signals).\n\n| Class | V8 |\n|---|---|\n${evRow(v)}\n\n| Class | CONTROL |\n|---|---|\n${evRow(c)}\n\nMISSED_VALID_SETUP_COUNT (V8) = ${v.missed.MISSED ?? 0}; INCORRECT_BLOCK_COUNT (V8) = ${v.missed.BLOCKED_INCORRECTLY ?? 0}; LATE (V8) = ${v.missed.DETECTED_LATE ?? 0}.\n\n## Events\n| Onset (UTC) | Direction | V8 | V8 reason | CONTROL | CONTROL reason |\n|---|---|---|---|---|---|\n${EV.slice(-60).map((e) => `| ${e.onset_utc.slice(0, 16)} | ${e.dir} | ${e.V8.cls} | ${e.V8.why} | ${e.CONTROL.cls} | ${e.CONTROL.why} |`).join('\n') || '| none matured yet | | | | | |'}\n`;
  const wrongRows = (x) => WRONG_CLASSES.map((k) => `| ${k} | ${x.wrong[k] ?? 0} |`).join('\n');
  R.V8_WRONG_DIRECTION_FORWARD = head('V8_WRONG_DIRECTION_FORWARD') + `Every labelled signal whose hypothetical 1.70R outcome is ≤ 0 or whose open path was wrong-direction (MFE < 0.5 R and the structural stop reached) is re-verified: data integrity, staleness, timing, structure / sweep oracles (D1/D2), PB depth (D3), RR before rounding (D5), MR side (D4) and overextension, stage decomposition of the traded model, model direction rule, stop side.\n\n| Class | V8 |\n|---|---|\n${wrongRows(v)}\n\n| Class | CONTROL |\n|---|---|\n${wrongRows(c)}\n\nVALID_LOSING_TRADES (V8) = ${v.wrong.VALID_LOSING_TRADE ?? 0}; IMPLEMENTATION_ERROR_COUNT (V8) = ${X.implErr(v)}.\n`;
  const waitRows = (x) => WAIT_CATEGORIES.map((k) => `| ${k} | ${x.waits[k] ?? 0} | ${pc((x.waits[k] ?? 0) / Math.max(1, x.decisions))} |`).join('\n');
  const topDetails = (x) => { const g = {}; for (const d of x.ds) if (d.action === 'WAIT') { const key = `${d.wait_category}: ${String(d.wait_detail ?? '').replace(/score \d+ < threshold \d+/, 'score < threshold').replace(/[\d.]+s old/, 'N s old').slice(0, 110)}`; g[key] = (g[key] ?? 0) + 1; } return Object.entries(g).sort((a, b) => b[1] - a[1]).slice(0, 15).map(([k, n]) => `| ${k} | ${n} |`).join('\n'); };
  const trans = (() => { const m = {}; const cByBar = new Map(c.ds.map((d) => [d.bar_time, d])); for (const d of v.ds) { const x = cByBar.get(d.bar_time); if (!x) continue; const a = x.action === 'WAIT' ? x.wait_category : `${x.action}`; const b = d.action === 'WAIT' ? d.wait_category : `${d.action}`; if (a !== b) { const k = `${a} → ${b}`; m[k] = (m[k] ?? 0) + 1; } } return Object.entries(m).sort((p, q) => q[1] - p[1]).slice(0, 15).map(([k, n]) => `| ${k} | ${n} |`).join('\n'); })();
  R.V8_WAIT_REASON_ANALYSIS = head('V8_WAIT_REASON_ANALYSIS') + `Every WAIT carries one of the 15 allowed categories and an exact detail (no generic "low quality": the quality gate is reported as OTHER_GOVERNED_REASON with the score, threshold, threshold basis and the weakest components).\n\n| Category (V8) | Bars | Share of decisions |\n|---|---|---|\n${waitRows(v)}\n\n| Category (CONTROL) | Bars | Share |\n|---|---|---|\n${waitRows(c)}\n\n## Most frequent exact reasons (V8)\n| Reason | Bars |\n|---|---|\n${topDetails(v) || '| — | |'}\n\n## Decision changes CONTROL → V8 on the same bar\n| Change | Bars |\n|---|---|\n${trans || '| none | |'}\n`;
  const lat = (x) => { const a = x.ds.map((d) => d.latency_sec).filter((t) => t != null).sort((p, q) => p - q); return a.length ? `median ${a[a.length >> 1]} s, p90 ${a[Math.floor(a.length * 0.9)]} s, max ${a.at(-1)} s` : '—'; };
  R.V8_TIMING_ANALYSIS = head('V8_TIMING_ANALYSIS') + `| Item | V8 | CONTROL |\n|---|---|---|\n| Decision latency after the 5m close (all forward decisions) | ${lat(v)} | ${lat(c)} |\n| Mean bars from setup origin to signal | ${f2(v.origin_bars)} | ${f2(c.origin_bars)} |\n| Signals later than the model limit (MC/PB/MR 3, BO 10, SR 0) | ${v.set.filter((d) => d.candidate.bars_from_origin > ({ MC: 3, PB: 3, BO: 10, SR: 0, MR: 3 }[d.candidate.model])).length} | ${c.set.filter((d) => d.candidate.bars_from_origin > ({ MC: 3, PB: 3, BO: 10, SR: 0, MR: 3 }[d.candidate.model])).length} |\n| DETECTED_LATE move events | ${v.missed.DETECTED_LATE ?? 0} | ${c.missed.DETECTED_LATE ?? 0} |\n| Decisions taken more than 120 s after the close (not counted) | ${v.late_decisions} | ${c.late_decisions} |\n\nThe decision is taken on the last COMPLETED 5m candle (forming bar excluded on every timeframe, integrity-checked per decision); entry = that candle's close (hypothetical).\n`;
  R.V8_SL_ANALYSIS = head('V8_SL_ANALYSIS') + `Structural SL = the model's invalidation anchor ∓ 0.25 ATR (floor 0.5 ATR, wrong-side fallback 1.5 ATR) — unchanged; never tightened or widened. 0.01 lot = 1 oz: 1 USD of price = 1 USD of risk.\n\n| Bar close | Engine | Model | Side | Entry | SL | SL distance (USD) | Risk at 0.01 lot (USD) | % of 10,000 DEMO | % of 62.07 REAL | SL source | Invalidation |\n|---|---|---|---|---|---|---|---|---|---|---|---|\n${[...v.set, ...c.set].sort((a, b) => a.bar_time - b.bar_time).map((d) => { const cd = d.candidate; return `| ${d.bar_close_utc.slice(0, 16)} | ${d.engine} | ${cd.model} | ${cd.side} | ${cd.entry} | ${cd.stop_loss} | ${f2(cd.risk_distance)} | ${f2(cd.risk_distance)} | ${pc(cd.risk_distance / SAFETY.demoEquityUsd)} | ${pc(cd.risk_distance / SAFETY.realEquityUsd)} | ${cd.sl_source} | ${({ MC: 'momentum-leg base', PB: 'pullback extreme', BO: 'retest extreme', SR: 'rejection wick', MR: 'sweep-bar extreme' })[cd.model]} |`; }).join('\n') || '| none yet | | | | | | | | | | | |'}\n\nBroker fail-safe (production, unchanged): 1.5 × structural distance + spread.\n`;
  const rrCheck = (x) => x.set.filter((d) => Math.abs(Math.abs(d.candidate.tp_170r - d.candidate.entry) / d.candidate.risk_distance - RR) > 0.002).length;
  R.V8_RR_ANALYSIS = head('V8_RR_ANALYSIS') + `TP = entry ± 1.70 × structural risk distance. Verified per signal: |TP − entry| / risk = 1.70 (tolerance 0.002 for 3-decimal rounding of stored prices).\n\n| | V8 | CONTROL |\n|---|---|---|\n| Signals | ${v.signals} | ${c.signals} |\n| 1.70R TP mismatches | ${rrCheck(v)} | ${rrCheck(c)} |\n| Engine RR below 1.70 before rounding (D5) | ${v.regression.D5.VIOLATION_ON_SIGNALS} | ${c.regression.D5.VIOLATION_ON_SIGNALS} |\n| Mean engine TP2 RR | ${f2(mean(v.set.map((d) => d.candidate.rr_engine_unrounded)))} | ${f2(mean(c.set.map((d) => d.candidate.rr_engine_unrounded)))} |\n\nThe hypothetical outcome uses the fixed 1.70R target (owner rule); the engine's structural TP2 (≥ 1.70R) is tracked as a secondary series (V8_COST_STRESS).\n`;
  R.V8_COST_STRESS = head('V8_COST_STRESS') + `NORMAL = spread 0.24 + slippage 0.10 USD; STRESS = 0.60 + 0.20 USD; entry pays the spread (BUY), exit pays slippage; broker fail-safe 1.5R + spread intrabar; thesis invalidation on a confirmed close beyond the structural stop; 288-bar horizon; swap 0.56 USD per BUY night.\n\n${statHead}\n${statRow('V8 per signal · 1.70R · NORMAL', v.per_signal)}\n${statRow('V8 per signal · 1.70R · STRESS', v.stress)}\n${statRow('V8 per signal · engine TP2 · NORMAL', v.tp2)}\n${statRow('V8 per signal · engine TP2 · STRESS', v.tp2_stress)}\n${statRow('V8 one position at a time · 1.70R · NORMAL', v.seq)}\n${statRow('V8 one position at a time · 1.70R · STRESS', v.seq_stress)}\n${statRow('CONTROL per signal · 1.70R · NORMAL', c.per_signal)}\n${statRow('CONTROL per signal · 1.70R · STRESS', c.stress)}\n${statRow('CONTROL one position · 1.70R · NORMAL', c.seq)}\n\nNo edge is claimed before costs or on an interim sample.\n`;
  const integ = (x) => { const g = {}; for (const d of x.ds) for (const [k, r] of Object.entries(d.data_integrity ?? {})) { g[k] ??= { PASS: 0, FAIL: 0 }; g[k][r]++; } return Object.entries(g).map(([k, r]) => `| ${k} | ${r.PASS} | ${r.FAIL} |`).join('\n'); };
  R.V8_DATA_INTEGRITY = head('V8_DATA_INTEGRITY') + `Checked on every decision: window length 499 per timeframe, monotonic and aligned timestamps, no forming bar (bar + timeframe ≤ decision time), OHLC geometry, decision bar = last completed 5m bar. Inputs are hashed per decision and archived first-seen; later broker revisions of a confirmed bar are logged, never used to repair a past decision.\n\n| Check (V8 decisions) | PASS | FAIL |\n|---|---|---|\n${integ(v) || '| — | | |'}\n\n| Item | V8 | CONTROL |\n|---|---|---|\n| Decisions failing integrity (recorded DATA_UNAVAILABLE) | ${v.integrity_fail} | ${c.integrity_fail} |\n| STALE_DATA decisions (V8 fails closed; CONTROL decides) | ${v.waits.STALE_DATA ?? 0} | stale inputs used: ${c.ds.filter((d) => d.input_stale).length} |\n| DATA_UNAVAILABLE decisions | ${v.waits.DATA_UNAVAILABLE ?? 0} | ${c.waits.DATA_UNAVAILABLE ?? 0} |\n| Duplicate signals suppressed | ${v.duplicates} | ${c.duplicates} |\n| Broker revisions of archived confirmed bars | ${X.REV.length} | |\n| Restart determinism | decision id = hash(schema, engine, symbol, timeframe, bar time); a restarted runner never re-decides a bar | |\n`;
  R.V8_REPLAY_PARITY = head('V8_REPLAY_PARITY') + `Sample: every valid setup / signal and every top-of-hour decision, re-evaluated at least 60 s later from the first-seen bar archive with the same engine. Input windows are compared by hash first; equal inputs must give identical action, wait reason and category, model, side, entry, SL, TP2, RR, 1.70R TP, stages and origin.\n\n| | V8 | CONTROL |\n|---|---|---|\n| Checked | ${v.parity.checked} | ${c.parity.checked} |\n| Inputs identical | ${v.parity.inputs_equal} | ${c.parity.inputs_equal} |\n| Decision identical | ${v.parity.match} | ${c.parity.match} |\n| Mismatches | ${v.parity.mismatch.length} | ${c.parity.mismatch.length} |\n| Inputs changed (broker revision; not an engine mismatch) | ${v.parity.input_changed} | ${c.parity.input_changed} |\n| Stage decomposition vs model functions: decisions with a mismatch | ${v.stage_parity_mismatch} | ${c.stage_parity_mismatch} |\n\n${v.parity.mismatch.length ? `Mismatches: ${v.parity.mismatch.map((p) => `${new Date(p.bar_time * 1000).toISOString()} ${p.diffs.join(',')}`).join('; ')}` : 'No mismatch.'} REPLAY_PARITY = ${v.parity.mismatch.length === 0 ? 'PASS' : 'FAIL'}.\n`;
  const regRows = (x) => ['D1', 'D2', 'D3', 'D4', 'D5', 'D6'].map((k) => `| ${k} | ${x.regression[k].OK} | ${x.regression[k].VIOLATION} | ${x.regression[k].VIOLATION_ON_SIGNALS} |`).join('\n');
  R.V8_D1_D6_REGRESSION = head('V8_D1_D6_REGRESSION') + `Independent oracles written from the specification: D1 structure state and last BOS/CHoCH from time-ordered breaks; D2 most recent sweep; D3 PB depth ≥ 1 ATR on PB setups; D4 MR entry on the far side of its midpoint; D5 RR ≥ 1.70 before rounding; D6 no decision on a stale 5m/15m/30m snapshot.\n\n| Check | V8 OK | V8 VIOLATION | V8 violations on setups |\n|---|---|---|---|\n${regRows(v)}\n\n| Check | CONTROL OK | CONTROL VIOLATION | CONTROL violations on setups |\n|---|---|---|---|\n${regRows(c)}\n\nCONTROL violations show the defects still live in production on forward data; V8 must stay at zero (any V8 violation = regression).\n`;
  R.V8_OVER_CORRECTION_ANALYSIS = head('V8_OVER_CORRECTION_ANALYSIS') + `| Measure | V8 | CONTROL |\n|---|---|---|\n| Counted signals | ${v.signals} | ${c.signals} |\n| WAIT share of decisions | ${pc(1 - (v.signals + v.safety_blocked + v.duplicates) / Math.max(1, v.decisions))} | ${pc(1 - (c.signals + c.safety_blocked + c.duplicates) / Math.max(1, c.decisions))} |\n| BUY share of signals | ${pc(v.buy_share)} | ${pc(c.buy_share)} |\n| Model mix | ${MODELS.map((m) => `${m} ${v.set.filter((d) => d.candidate.model === m).length}`).join(', ')} | ${MODELS.map((m) => `${m} ${c.set.filter((d) => d.candidate.model === m).length}`).join(', ')} |\n| Mean bars from origin | ${f2(v.origin_bars)} | ${f2(c.origin_bars)} |\n| Move events detected correctly | ${v.missed.DETECTED_CORRECTLY ?? 0} | ${c.missed.DETECTED_CORRECTLY ?? 0} |\n| CONTROL signals not produced by V8 (outcome mean R) | ${(() => { const vt = new Set(v.set.map((d) => d.bar_time)); const gone = c.lab.filter((x) => !vt.has(x.d.bar_time)); return `${gone.length} (${f3(mean(gone.map((x) => x.o.fix170_normal.r)))})`; })()} | |\n\nOVER_CORRECTION_CANDIDATE flags (descriptive, computed on whatever has been observed; the sample size is shown and small samples are noisy): ${X.flags.length ? X.flags.map((f) => `**${f}**`).join('; ') : 'none'}. No code is changed because of a flag; flags are evidence for the owner's review.\n`;
  R.V8_CORE_EXECUTION_REVIEW = head('V8_CORE_EXECUTION_REVIEW') + `Evidence for the owner's review of core execution. There is no automatic verdict and no completion gate.\n\n| Measure | V8 CONTROL (production, same inputs) | V8 CORRECTED SHADOW |\n|---|---|---|\n| Valid setups / shadow signals | ${c.valid_setups} / ${c.signals} | ${v.valid_setups} / ${v.signals} |\n| Pattern / setup / trigger parity (stage mismatches) | ${c.stage_parity_mismatch} | ${v.stage_parity_mismatch} |\n| Specification violations on setups (D1-D6) | ${X.regOnSig(c)} | ${X.regOnSig(v)} |\n| Missed / incorrect blocks / late | ${X.ev.CONTROL.missed_valid_setups} / ${X.ev.CONTROL.incorrect_blocks} / ${X.ev.CONTROL.late_signals} | ${X.ev.V8.missed_valid_setups} / ${X.ev.V8.incorrect_blocks} / ${X.ev.V8.late_signals} |\n| Invalid setups incorrectly accepted | ${X.ev.CONTROL.invalid_setups_accepted} | ${X.ev.V8.invalid_setups_accepted} |\n| Wrong-direction (labelled) | ${pc(c.per_signal.wrong)} | ${pc(v.per_signal.wrong)} |\n| Valid losses / implementation errors | ${c.wrong.VALID_LOSING_TRADE ?? 0} / ${X.implErr(c)} | ${v.wrong.VALID_LOSING_TRADE ?? 0} / ${X.implErr(v)} |\n| Expectancy (R, 1.70R, NORMAL) | ${f3(c.per_signal.expectancy)} | ${f3(v.per_signal.expectancy)} |\n| PF | ${f2(c.per_signal.pf)} | ${f2(v.per_signal.pf)} |\n| MFE / MAE (R) | ${f2(c.per_signal.mfe)} / ${f2(c.per_signal.mae)} | ${f2(v.per_signal.mfe)} / ${f2(v.per_signal.mae)} |\n| 1.70R reach | ${pc(c.per_signal.reach170)} | ${pc(v.per_signal.reach170)} |\n| Max DD (R, per-signal sequence) | ${f2(c.per_signal.max_dd)} | ${f2(v.per_signal.max_dd)} |\n| STRESS expectancy (R) | ${f3(c.stress.expectancy)} | ${f3(v.stress.expectancy)} |\n\nCore rule correctness (V8): **${X.coreStatus}**. How to read it: V8 is correct while its replay parity, D1-D6 regressions, stage parity, implementation errors, missed setups and incorrect blocks stay at zero. CONTROL violations show the defects V8 removes. The owner decides when the observation period is long enough.\n`;
  R.DEMO_VALIDATION_GATE = head('DEMO_VALIDATION_GATE') + `**DEMO_ELIGIBLE = NO.** DEMO is never enabled automatically and there is no signal-count rule. Eligibility depends only on the owner's explicit review of the five areas below; this page lists the evidence collected so far.\n\n## Owner review checklist\n| Area | Evidence so far |\n|---|---|\n| CORE RULE CORRECTNESS | ${X.coreStatus}; D1-D6 violations V8 ${X.ev.V8.d1_d6_regressions} (CONTROL ${X.ev.CONTROL.d1_d6_regressions}); replay mismatches ${v.parity.mismatch.length}; stage mismatches ${v.stage_parity_mismatch}; implementation errors ${X.implErr(v)} |\n| FORWARD BEHAVIOUR | ${v.decisions} candles observed over ${elapsed(X.obs.elapsed_hours)}; ${v.valid_setups} valid setups, ${v.signals} shadow signals; missed ${X.ev.V8.missed_valid_setups}, incorrect blocks ${X.ev.V8.incorrect_blocks}, late ${X.ev.V8.late_signals}; over-correction flags ${X.flags.length} |\n| RISK CONTROL | structural SL on every setup (V8_SL_ANALYSIS); RR 1.70 verified (V8_RR_ANALYSIS); lot 0.01; no averaging, martingale or scaling |\n| COST REALISM | 1.70R NORMAL ${f3(v.per_signal.expectancy)} R vs STRESS ${f3(v.stress.expectancy)} R per signal (V8_COST_STRESS) |\n| STABILITY | daily evidence snapshots (state/v8_shadow/snapshots/), replay parity ${v.parity.match}/${v.parity.checked}, data-integrity failures ${v.integrity_fail}, broker revisions ${X.REV.length} |\n\n## Future DEMO specification (prepared only; NOT started)\n| Item | Value |\n|---|---|\n| Account | 10,000 USD DEMO |\n| Lot | 0.01 (USER_FIXED) |\n| RR | 1.70 |\n| AUTO_SCALING / MARTINGALE / AVERAGING_DOWN | OFF / OFF / OFF |\n| Risk governance | percentage-of-equity cap per trade (structural distance x 0.01 lot as % of equity), structural SL, broker stops level and margin availability; no universal fixed-dollar loss |\n| Engine | the frozen V8 corrected core exactly as validated (engines manifest hash), no new filters |\n| Safety | production News V2, spread <= 0.60, drift guard, shock state, breaker, broker fail-safe SL |\n| REAL | prohibited; no automatic deployment is prepared |\n`;
  for (const [k, md] of Object.entries(R)) writeFileSync(join(outDir, `${k}.md`), md);
  writeFileSync(join(outDir, 'forward_summary.json'), JSON.stringify({ generated_utc: new Date().toISOString(), observation: X.obs, sample_size_gate: 'NONE', trade_count_target: 'NONE', evidence: X.ev, V8: { decisions: v.decisions, valid_setups: v.valid_setups, signals: v.signals, labelled: v.labelled, per_signal: v.per_signal, stress: v.stress, missed: v.missed, wrong: v.wrong, regression: v.regression, parity: { ...v.parity, mismatch: v.parity.mismatch.length } }, CONTROL: { decisions: c.decisions, valid_setups: c.valid_setups, signals: c.signals, labelled: c.labelled, per_signal: c.per_signal, stress: c.stress, missed: c.missed, wrong: c.wrong, regression: c.regression, parity: { ...c.parity, mismatch: c.parity.mismatch.length } }, events: EV.length, flags: X.flags, clean: X.clean, core_rule_correctness: X.coreStatus, demo_eligible: X.demo }, null, 1));
  return { reports: Object.keys(R).length, core_status: X.coreStatus, demo: X.demo, v8_valid_setups: v.valid_setups, v8_signals: v.signals };
}
